SET ESC \;

delete from tbaadm.MOD WHERE mop_ID = 'CLIA' and bank_id='43';
delete from tbaadm.MOD_TXT WHERE mop_ID = 'CLIA' and bank_id='43';
delete from tbaadm.MNO WHERE mop_ID = 'CLIA' and bank_id='43';
delete from tbaadm.OAT WHERE mop_ID = 'CLIA' and bank_id='43';


variable mopNum varchar2(3);


begin
SELECT NVL(TO_CHAR(MAX(TO_NUMBER(MOP_NUM))+1), '43') into :mopNum FROM tbaadm.MNO WHERE MENU_ID = 'ONSDBMNU' and bank_id='43';
end;
/

Insert into TBAADM.MOD (MOP_ID,ENTITY_CRE_FLG,DEL_FLG,MOP_TYPE,EXE_NAME,INPUT_FILENAME,ADDITIONAL_PARAMS,DB_STATUS,MOP_TERM_CLASS_1,MOP_TERM_CLASS_2,MOP_TERM_CLASS_3,MOP_TERM_CLASS_4,MOP_TERM_CLASS_5,MOP_TERM_CLASS_6,MOP_TERM_CLASS_7,MOP_TERM_CLASS_8,MOP_TERM_CLASS_9,MOP_TERM_CLASS_10,MOP_MENU_PARAM,MOP_MENU_SECU_IND,MOP_ACPT_PASSWD_FLG,MOP_TERM_TYPE,MOP_EXECUTION_TYPE,NODE_TYPE,LOG_OPERATION_FLG,MOD_TENOR,LCHG_USER_ID,RCRE_USER_ID,LCHG_TIME,RCRE_TIME,TS_CNT,WORK_CLASS,TEMPLATE_DETAILS,BANK_ID,AUTOVER_PARAM_AREA,SAVE_AS_ENABLED_FLG,SCHD_BATCH_FLAG,FREE_CODE1,ENABLE_INQ_AUDIT_FLG,INQ_AUDIT_START_DATE,INQ_AUDIT_END_DATE,MIN_VERIFIER_WORK_CLASS,REPLICATE_FLG,LITERAL_CONTEXT) values ('CLIA','Y','N','U','http://$W/$A/','Customize/Customize_ctrl.jsp?sessionid=$S','&sectok=$T&finsessionid=$S&fabsessionid=$C&mo=CLIA&mtype=F','F','BT',null,null,null,null,null,null,null,null,null,'FINW','M','N',null,null,null,null,'F','TBAADM','TBAADM',to_date('24-OCT-18','DD-MON-RR'),to_date('24-OCT-18','DD-MON-RR'),0,'003600600N650650N999999N',null,'43',null,null,null,null,null,null,null,null,null,null);
/
Insert into TBAADM.MOD_TXT (MOP_ID,LANG_CODE,USER_MOP_ID,MOP_TEXT,MOP_HELP_TEXT,ENTITY_CRE_FLG,LCHG_USER_ID,RCRE_USER_ID,LCHG_TIME,RCRE_TIME,TS_CNT,BANK_ID) values ('CLIA','FRENCH','CLIA','Legacy Interest Adjustment',null,'Y','TBAADM','TBAADM',to_date('24-OCT-18','DD-MON-RR'),to_date('24-OCT-18','DD-MON-RR'),0,'43');
/
Insert into TBAADM.MOD_TXT (MOP_ID,LANG_CODE,USER_MOP_ID,MOP_TEXT,MOP_HELP_TEXT,ENTITY_CRE_FLG,LCHG_USER_ID,RCRE_USER_ID,LCHG_TIME,RCRE_TIME,TS_CNT,BANK_ID) values ('CLIA','INFENG','CLIA','Legacy Interest Adjustment',null,'Y','TBAADM','TBAADM',to_date('24-OCT-18','DD-MON-RR'),to_date('24-OCT-18','DD-MON-RR'),0,'43');
/
Insert into TBAADM.OAT (MOP_ID,APPL_ID,LCHG_USER_ID,LCHG_TIME,RCRE_USER_ID,RCRE_TIME,TS_CNT,BANK_ID) values ('CLIA','GU','TBAADM',to_date('24-OCT-18','DD-MON-RR'),'TBAADM',to_date('24-OCT-18','DD-MON-RR'),0,'43');
/
Insert into TBAADM.OAT (MOP_ID,APPL_ID,LCHG_USER_ID,LCHG_TIME,RCRE_USER_ID,RCRE_TIME,TS_CNT,BANK_ID) values ('CLIA','NC','TBAADM',to_date('24-OCT-18','DD-MON-RR'),'TBAADM',to_date('24-OCT-18','DD-MON-RR'),0,'43');
/
begin
Insert into TBAADM.MNO (MENU_ID,MOP_NUM,MOP_ID,ENTITY_CRE_FLG,MENU_TYPE,LCHG_USER_ID,LCHG_TIME,RCRE_USER_ID,RCRE_TIME,TS_CNT,BANK_ID) values ('ONSDBMNU',:mopNum,'CLIA','Y','U','TBAADM',to_date('24-OCT-18','DD-MON-RR'),'TBAADM',to_date('24-OCT-18','DD-MON-RR'),0,'43');
end;
/

SET ESC OFF;
commit;