SET DEFINE OFF;
Insert into CUSTOM.C_CPVALUE
(BANK_ID,PARAMETER_ID,LEVELCODE_1,LEVELCODE_2,PARAMETER_VALUE,ENTITY_CRE_FLG,DEL_FLG,RCRE_USER_ID,RCRE_TIME,LCHG_USER_ID,LCHG_TIME,MODULE_NAME)
values 
('43','DORMANCY_PERIOD_SB','ALL','','1080','Y','N','TBAADM',sysdate,'TBAADM',sysdate,'SB');
Insert into CUSTOM.C_CPVALUE
(BANK_ID,PARAMETER_ID,LEVELCODE_1,LEVELCODE_2,PARAMETER_VALUE,ENTITY_CRE_FLG,DEL_FLG,RCRE_USER_ID,RCRE_TIME,LCHG_USER_ID,LCHG_TIME,MODULE_NAME)
values 
('43','DORMANCY_PERIOD_CA','ALL','','360','Y','N','TBAADM',sysdate,'TBAADM',sysdate,'CA');
COMMIT;