logging:
  level:
    ROOT: INFO
    org.hibernate: INFO
    com.equitybank.gag.telco_b2c: INFO
    com.netflix.discovery.DiscoveryClient: INFO

server:
  port: 9443
  ssl:
    enabled: true
    key-store: ${CD_SSL_KEYSTORE_LOCATION}
    key-store-password: ${CD_SSL_KEYSTORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: ${CD_SSL_KEYSTORE_ALIAS}

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: ${CD_SPRING_DATASOURCE_URL}
    username: ${CD_SPRING_DATASOURCE_USERNAME}
    password: ${CD_SPRING_DATASOURCE_PASSWORD}
    hikari:
      idleTimeout: 60000
      connectionTimeout: 60000
      maxLifetime: 30000
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.Oracle12cDialect
      ddl-auto: update
    show-sql: false

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

signature:
  validation:
    certificate:
      path: ${CD_SECURITY_CHANNELS_CERTIFICATE_FOLDER}