logging:
  level:
    ROOT: INFO
    org.hibernate: INFO
    com.equitybank.gag.telco_b2c: INFO
    com.netflix.discovery.DiscoveryClient: INFO

server:
  port: 8500

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/gag?useSSL=false&allowPublicKeyRetrieval=true
    username: bishop
    password: bishop
    hikari:
      idleTimeout: 60000
      connectionTimeout: 60000
      maxLifetime: 30000
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect  # Update dialect for MySQL 8
      ddl-auto: update
    show-sql: false

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false