#!/bin/bash

# ==================================================================================================
# SCRIPT: check-modified-files.sh
#
# PURPOSE:
#   Detects J2EE file changes (NEW, MODIFIED, DELETED) from Git and prepares deployment artifacts.
#
# SCOPE:
#   - fincore/custom/**
#   - crm/customization/**
#
# OUTPUT:
#   - newFiles/ | modifiedFiles/ | deletedFiles/
#   - deployment-manifest.txt
#   - deployment-audit.txt
#   - metadata.json  (includes deploy_shared_servers / deploy_dedicated_servers flags)
#
# NOTE:
#   Used in CI phase only. Deployment handled separately by deploy-j2ee.sh.
#
# AUTHOR: Kennedy Gatimu
# ==================================================================================================

echo
echo "------------------------------- J2EE CHANGE DETECTION PROGRAM STARTING -------------------------------"
echo "START TIME: $(date)"
echo

AZURE_WORKING_DIR=$(pwd)
echo "AZURE WORKING DIRECTORY: $AZURE_WORKING_DIR"
echo

# ---------------------------------------------------------------------------------------------------------------------
# ARTIFACT DIRECTORIES
# Folders where changed files are staged before being packaged into the build artifact.
# These are recreated fresh on every CI run to avoid stale files from previous builds.
# ---------------------------------------------------------------------------------------------------------------------
NEW_FILES_DIR="$AZURE_WORKING_DIR/newFiles"
MODIFIED_FILES_DIR="$AZURE_WORKING_DIR/modifiedFiles"
DELETED_FILES_DIR="$AZURE_WORKING_DIR/deletedFiles"

# ---------------------------------------------------------------------------------------------------------------------
# OUTPUT FILES
# Files generated by this script and consumed by downstream pipeline stages.
# ---------------------------------------------------------------------------------------------------------------------
NEW_FILES_LIST=newFilesPath.txt           # lists all new file paths
MODIFIED_FILES_LIST=modifiedFilesPath.txt # lists all modified file paths
DELETED_FILES_LIST=deletedFilesPath.txt   # lists all deleted file paths
MANIFEST_FILE=deployment-manifest.txt     # one entry per changed file: FILE_CHANGE_TYPE|FILE_PATH
AUDIT_FILE=deployment-audit.txt           # full audit trail with author and commit info per file
METADATA_FILE=metadata.json               # JSON summary consumed by pipeline routing logic
TEMP_DETAILS_FILE=fileDetails.tmp         # temporary file used to build the metadata files array

# ---------------------------------------------------------------------------------------------------------------------
# DEPLOYMENT TARGET FLAGS
# Set by detect_deployment_targets() after scanning the completed manifest.
# Used in metadata.json and pipeline tag routing to decide which CD stages to trigger.
#   DEPLOY_DEDICATED_BANKS   : true if any bank file was changed
#   DEPLOY_DEDICATED_BANK_IDS: array of specific bank IDs with changes (e.g. "54" "55")
#                              used to emit precise routing tags e.g. J2EE-54, J2EE-55
#                              Note: Finserve (99) and global files map to bank 54 (same server)
# ---------------------------------------------------------------------------------------------------------------------
DEPLOY_DEDICATED_BANKS=false
DEPLOY_DEDICATED_BANK_IDS=()

# ---------------------------------------------------------------------------------------------------------------------
# LOGGING UTILITIES
# log()        : prints an informational message with [INFO] prefix
# error_exit() : prints an error message and immediately stops the script
# ---------------------------------------------------------------------------------------------------------------------
log() {
    echo "[INFO] $1"
}

error_exit() {
    echo "[ERROR] $1"
    echo "[ERROR] Script stopped at: $(date)"
    exit 1
}

# ---------------------------------------------------------------------------------------------------------------------
# FUNCTION: create_directory
#
# Ensures a clean directory exists at the given path.
# If it already exists it is deleted and recreated — guarantees no stale files from a previous run.
#
# Arguments:
#   $1 dir_path : full path of the directory to create
# ---------------------------------------------------------------------------------------------------------------------
create_directory() {
    local dir_path=$1

    echo "------------------------------------------------------------"
    log "Creating directory: $dir_path"

    if [ -d "$dir_path" ]; then
        log "Directory already exists — recreating to ensure a clean state..."
        rm -rvf "$dir_path" || true
        mkdir -vp "$dir_path"
        log "Directory recreated: $dir_path"
    else
        mkdir -vp "$dir_path"
        log "Directory created: $dir_path"
    fi
    echo
}

# ---------------------------------------------------------------------------------------------------------------------
# FUNCTION: create_file
#
# Ensures a clean empty file exists at the given path.
# If it already exists it is deleted and recreated — guarantees no stale content from a previous run.
#
# Arguments:
#   $1 file_path : full path of the file to create
# ---------------------------------------------------------------------------------------------------------------------
create_file() {
    local file_path=$1

    echo "------------------------------------------------------------"
    log "Creating file: $file_path"

    if [ -f "$file_path" ]; then
        log "File already exists — recreating to ensure a clean state..."
        rm -vf "$file_path" || true
        touch "$file_path"
        log "File recreated: $file_path"
    else
        touch "$file_path"
        log "File created: $file_path"
    fi
    echo
}

# ---------------------------------------------------------------------------------------------------------------------
# FUNCTION: is_j2ee_file
#
# Returns true (0) if the file belongs to the J2EE scope (fincore or crm paths).
# Files outside this scope are skipped — they belong to other projects in the same repo.
#
# Arguments:
#   $1 file_path : the file path from git diff
# ---------------------------------------------------------------------------------------------------------------------
is_j2ee_file() {
    local file_path=$1

    if [[ "$file_path" == fincore/* || "$file_path" == crm/* ]]; then
        return 0  # true — belongs to J2EE scope
    else
        return 1  # false — not a J2EE file, skip it
    fi
}

# ---------------------------------------------------------------------------------------------------------------------
# FUNCTION: get_finacle_app
#
# Returns which Finacle app a file belongs to, based on its path prefix.
# The return value is echoed so it can be captured with $(...).
#
# Arguments:
#   $1 file_path : the file path to inspect
# ---------------------------------------------------------------------------------------------------------------------
get_finacle_app() {
    local file_path=$1

    if [[ "$file_path" == fincore/* ]]; then
        echo "fincore"
    elif [[ "$file_path" == crm/* ]]; then
        echo "crm"
    else
        echo "unknown"
    fi
}

# ---------------------------------------------------------------------------------------------------------------------
# FUNCTION: check_new_files
#
# Copies newly added files into the newFiles/ staging directory.
# Records each file in the manifest, audit log, and temp details file.
#
# Arguments:
#   $1 : newline-separated list of new file paths from git diff
# ---------------------------------------------------------------------------------------------------------------------
check_new_files() {
    local files_array
    local file_path
    local finacle_app

    echo "============================================================"
    echo "                 COPYING NEW FILES"
    echo "============================================================"

    log "New file(s) detected. Preparing staging directory: $NEW_FILES_DIR"

    [ ! -d "$NEW_FILES_DIR" ]   && create_directory "$NEW_FILES_DIR"
    [ ! -f "$NEW_FILES_LIST" ]  && create_file "$NEW_FILES_LIST"

    readarray -t files_array <<< "$1"

    for file_path in "${files_array[@]}"; do
        if is_j2ee_file "$file_path"; then
            if [ -f "$file_path" ]; then
                log "Copying NEW file : $file_path : $NEW_FILES_DIR"
                cp --parents "$file_path" "$NEW_FILES_DIR"

                echo "$file_path"                                       >> "$NEW_FILES_LIST"
                echo "NEW|$file_path"                                   >> "$MANIFEST_FILE"
                echo "NEW|$file_path|AUTHOR=$AUTHOR|COMMIT=$COMMIT_ID" >> "$AUDIT_FILE"

                finacle_app=$(get_finacle_app "$file_path")
                echo "$file_path|$finacle_app|NEW"                     >> "$TEMP_DETAILS_FILE"
            else
                log "WARNING: File listed in git diff but not found on disk — skipping: $file_path"
            fi
        fi
    done

    cp "$NEW_FILES_LIST" "$NEW_FILES_DIR"
    echo
}

# ---------------------------------------------------------------------------------------------------------------------
# FUNCTION: check_modified_files
#
# Copies modified files into the modifiedFiles/ staging directory.
# Records each file in the manifest, audit log, and temp details file.
#
# Arguments:
#   $1 : newline-separated list of modified file paths from git diff
# ---------------------------------------------------------------------------------------------------------------------
check_modified_files() {
    local files_array
    local file_path
    local finacle_app

    echo "============================================================"
    echo "                 COPYING MODIFIED FILES"
    echo "============================================================"

    log "Modified file(s) detected. Preparing staging directory: $MODIFIED_FILES_DIR"

    [ ! -d "$MODIFIED_FILES_DIR" ]   && create_directory "$MODIFIED_FILES_DIR"
    [ ! -f "$MODIFIED_FILES_LIST" ]  && create_file "$MODIFIED_FILES_LIST"

    readarray -t files_array <<< "$1"

    for file_path in "${files_array[@]}"; do
        if is_j2ee_file "$file_path"; then
            if [ -f "$file_path" ]; then
                log "Copying MODIFIED file : $file_path : $MODIFIED_FILES_DIR"
                cp --parents "$file_path" "$MODIFIED_FILES_DIR"

                echo "$file_path"                                            >> "$MODIFIED_FILES_LIST"
                echo "MODIFIED|$file_path"                                   >> "$MANIFEST_FILE"
                echo "MODIFIED|$file_path|AUTHOR=$AUTHOR|COMMIT=$COMMIT_ID" >> "$AUDIT_FILE"

                finacle_app=$(get_finacle_app "$file_path")
                echo "$file_path|$finacle_app|MODIFIED"                     >> "$TEMP_DETAILS_FILE"
            else
                log "WARNING: File listed in git diff but not found on disk — skipping: $file_path"
            fi
        fi
    done

    cp "$MODIFIED_FILES_LIST" "$MODIFIED_FILES_DIR"
    echo
}

# ---------------------------------------------------------------------------------------------------------------------
# FUNCTION: check_deleted_files
#
# Records deleted files in the manifest, audit log, and temp details.
# Deleted files no longer exist on disk — we only track their paths for the deploy script.
#
# Arguments:
#   $1 : newline-separated list of deleted file paths from git diff
# ---------------------------------------------------------------------------------------------------------------------
check_deleted_files() {
    local files_array
    local file_path
    local finacle_app

    echo "============================================================"
    echo "                 TRACKING DELETED FILES"
    echo "============================================================"

    log "Deleted file(s) detected. Preparing tracking directory: $DELETED_FILES_DIR"

    [ ! -d "$DELETED_FILES_DIR" ]   && create_directory "$DELETED_FILES_DIR"
    [ ! -f "$DELETED_FILES_LIST" ]  && create_file "$DELETED_FILES_LIST"

    readarray -t files_array <<< "$1"

    for file_path in "${files_array[@]}"; do
        if is_j2ee_file "$file_path"; then
            log "Tracking deleted file: $file_path"

            echo "$file_path"                                            >> "$DELETED_FILES_LIST"
            echo "DELETED|$file_path"                                    >> "$MANIFEST_FILE"
            echo "DELETED|$file_path|AUTHOR=$AUTHOR|COMMIT=$COMMIT_ID"  >> "$AUDIT_FILE"

            finacle_app=$(get_finacle_app "$file_path")
            echo "$file_path|$finacle_app|DELETED"                      >> "$TEMP_DETAILS_FILE"
        fi
    done

    cp "$DELETED_FILES_LIST" "$DELETED_FILES_DIR"
    echo
}

# ---------------------------------------------------------------------------------------------------------------------
# FUNCTION: detect_deployment_targets
#
# Scans the completed manifest and builds the DEPLOY_DEDICATED_BANK_IDS list.
# Must be called AFTER all file change functions so the manifest is fully populated.
#
# Rules:
#   - Every bank file maps to that bank's ID (e.g. /55/ → J2EE-55)
#   - Finserve (99) and global files map to Kenya (54) — all share the same server
#
# Results are written to the audit file and included in metadata.json for pipeline routing.
# ---------------------------------------------------------------------------------------------------------------------
detect_deployment_targets() {
    echo "============================================================"
    echo "         DETECTING DEPLOYMENT TARGET SERVER GROUPS"
    echo "============================================================"

    if [ ! -f "$MANIFEST_FILE" ]; then
        log "No manifest file found — skipping target detection."
        return
    fi

    if [ ! -s "$MANIFEST_FILE" ]; then
        log "Manifest file is empty — no deployment targets to detect."
        return
    fi

    local file_change_type
    local file_path
    local raw_bank_id
    local tag_bank_id

    log "Scanning manifest: $MANIFEST_FILE"
    echo

    # Read each manifest line — format: FILE_CHANGE_TYPE|FILE_PATH
    while IFS='|' read -r file_change_type file_path; do

        [ -z "$file_path" ] && continue                     # skip any blank lines

        # Extract bank identifier from the 3rd path segment
        raw_bank_id=$(echo "$file_path" | cut -d '/' -f3)

        # Finserve (99) and global files live on Kenya's (54) servers — tag them as J2EE-54
        if [ "$raw_bank_id" == "99" ] || [ "$raw_bank_id" == "global" ]; then
            tag_bank_id="54"
        else
            tag_bank_id="$raw_bank_id"
        fi

        DEPLOY_DEDICATED_BANKS=true

        # Collect tag_bank_id into DEPLOY_DEDICATED_BANK_IDS — no duplicates
        if [[ ! " ${DEPLOY_DEDICATED_BANK_IDS[*]} " == *" $tag_bank_id "* ]]; then
            DEPLOY_DEDICATED_BANK_IDS+=("$tag_bank_id")
        fi

        log "[TARGET] bank: $raw_bank_id | tag: J2EE-$tag_bank_id | change: $file_change_type | file: $file_path"

    done < "$MANIFEST_FILE"

    echo
    echo "------------------------------------------------------------"
    echo "DEPLOYMENT TARGET DETECTION RESULT"
    echo "------------------------------------------------------------"
    echo "  DEPLOY_DEDICATED_SERVERS  : $DEPLOY_DEDICATED_BANKS"
    echo "  DEPLOY_DEDICATED_BANK_IDS : ${DEPLOY_DEDICATED_BANK_IDS[*]:-none}"
    echo "------------------------------------------------------------"
    echo

    # Write results to audit file for traceability
    echo "DEPLOY_DEDICATED_SERVERS=$DEPLOY_DEDICATED_BANKS"              >> "$AUDIT_FILE"
    echo "DEPLOY_DEDICATED_BANK_IDS=${DEPLOY_DEDICATED_BANK_IDS[*]}"    >> "$AUDIT_FILE"
}

# =====================================================================================================================
# SCRIPT BODY — all functions are defined above; execution starts here
# =====================================================================================================================

# ---------------------------------------------------------------------------------------------------------------------
# STEP 1: INITIALISE OUTPUT FILES
# Create the manifest and audit files fresh on every run.
# Clear the temp details file if it exists from a previous run.
# ---------------------------------------------------------------------------------------------------------------------
create_file "$MANIFEST_FILE"
create_file "$AUDIT_FILE"
rm -f "$TEMP_DETAILS_FILE"              # clear any leftover temp data from a previous run

# ---------------------------------------------------------------------------------------------------------------------
# STEP 2: GATHER COMMIT INFORMATION
# Reads metadata from the commit being deployed.
# git log -2 | tail -1 intentionally targets the developer's commit, not the PR merge commit.
# (Merge commits are always the most recent; the developer's commit is always second.)
# ---------------------------------------------------------------------------------------------------------------------
COMMIT_ID=$(git log -2 --format=format:%h | tail -1)
BRANCH=${BUILD_SOURCEBRANCHNAME:-$(git rev-parse --abbrev-ref HEAD)}

# Map the branch name to its deployment environment
if   [[ "$BRANCH" == "develop" ]]; then ENV="SIT"
elif [[ "$BRANCH" == "release" ]]; then ENV="UAT"
elif [[ "$BRANCH" == "main"    ]]; then ENV="PROD"
else                                    ENV="UNKNOWN"
fi

AUTHOR=$(git show --pretty=format:"%an" "$COMMIT_ID" | head -1)
EMAIL=$(git show --pretty=format:"%ae" "$COMMIT_ID" | head -1)
COMMIT_MSG=$(git show --pretty=format:"%s"  "$COMMIT_ID" | head -1)
COMMIT_DATE=$(git show --pretty=format:"%cd" "$COMMIT_ID" | head -1)

echo "ENVIRONMENT  : $ENV"
echo "BRANCH       : $BRANCH"
echo "COMMIT       : $COMMIT_ID"
echo "AUTHOR       : $AUTHOR"
echo "AUTHOR EMAIL : $EMAIL"
echo "COMMIT MSG   : $COMMIT_MSG"
echo "COMMIT DATE  : $COMMIT_DATE"
echo

# Write core commit info to the audit file for traceability
echo "ENV=$ENV"              >> "$AUDIT_FILE"
echo "COMMIT_ID=$COMMIT_ID"  >> "$AUDIT_FILE"
echo "AUTHOR=$AUTHOR"        >> "$AUDIT_FILE"

# ---------------------------------------------------------------------------------------------------------------------
# STEP 3: DETECT FILE CHANGES
# Queries git for each category of file change in the developer's commit.
#   A = Added (new files)
#   C = Copied (file copied to a new path — treated as NEW at its destination)
#   M = Modified
#   D = Deleted
#   T = Type changed (e.g. symlink became a regular file — treated as MODIFIED)
# ---------------------------------------------------------------------------------------------------------------------
NEW_FILES=$(git show --diff-filter=A --name-only --format="" "$COMMIT_ID")
COPY_FILES=$(git show --diff-filter=C --name-only --format="" "$COMMIT_ID")
MODIFIED_FILES=$(git show --diff-filter=M --name-only --format="" "$COMMIT_ID")
DELETED_FILES=$(git show --diff-filter=D --name-only --format="" "$COMMIT_ID")
TYPE_FILES=$(git show --diff-filter=T --name-only --format="" "$COMMIT_ID")

[ -n "$NEW_FILES" ]      && check_new_files      "$NEW_FILES"
[ -n "$COPY_FILES" ]     && check_new_files      "$COPY_FILES"      # copied = new file at destination
[ -n "$MODIFIED_FILES" ] && check_modified_files "$MODIFIED_FILES"
[ -n "$DELETED_FILES" ]  && check_deleted_files  "$DELETED_FILES"
[ -n "$TYPE_FILES" ]     && check_modified_files "$TYPE_FILES"

# ---------------------------------------------------------------------------------------------------------------------
# STEP 4: DETECT DEPLOYMENT TARGETS
# Must run AFTER all change detection so the manifest is fully populated.
# ---------------------------------------------------------------------------------------------------------------------
detect_deployment_targets

# ---------------------------------------------------------------------------------------------------------------------
# STEP 5: CREATE METADATA FILE
# Produces a JSON file consumed by the Azure pipeline routing logic to decide which
# CD release pipelines to trigger based on which server groups were affected.
# ---------------------------------------------------------------------------------------------------------------------
echo "============================================================"
echo "                 CREATING METADATA FILE"
echo "============================================================"

if [ -f "$NEW_FILES_LIST" ];      then NEW_COUNT=$(wc -l < "$NEW_FILES_LIST");           else NEW_COUNT=0;      fi
if [ -f "$MODIFIED_FILES_LIST" ]; then MODIFIED_COUNT=$(wc -l < "$MODIFIED_FILES_LIST"); else MODIFIED_COUNT=0; fi
if [ -f "$DELETED_FILES_LIST" ];  then DELETED_COUNT=$(wc -l < "$DELETED_FILES_LIST");   else DELETED_COUNT=0;  fi

log "New files      : $NEW_COUNT"
log "Modified files : $MODIFIED_COUNT"
log "Deleted files  : $DELETED_COUNT"
echo

# Build the dedicated_bank_ids JSON array in pure bash e.g. [] or ["55"] or ["55","56"]
if [ ${#DEPLOY_DEDICATED_BANK_IDS[@]} -eq 0 ]; then
    dedicated_ids_json="[]"
else
    dedicated_ids_json="["
    for i in "${!DEPLOY_DEDICATED_BANK_IDS[@]}"; do
        [ $i -gt 0 ] && dedicated_ids_json+=","
        dedicated_ids_json+="\"${DEPLOY_DEDICATED_BANK_IDS[$i]}\""
    done
    dedicated_ids_json+="]"
fi

{
echo "{"
echo "  \"application\": \"J2EE\","
echo "  \"buildTime\": \"$(date)\","
echo "  \"environment\": \"$ENV\","
echo "  \"branch\": \"$BRANCH\","
echo "  \"commitId\": \"$COMMIT_ID\","
echo "  \"author\": \"$AUTHOR\","
echo "  \"email\": \"$EMAIL\","
echo "  \"message\": \"$COMMIT_MSG\","
echo "  \"commitDate\": \"$COMMIT_DATE\","
echo "  \"newFilesCount\": $NEW_COUNT,"
echo "  \"modifiedFilesCount\": $MODIFIED_COUNT,"
echo "  \"deletedFilesCount\": $DELETED_COUNT,"
echo "  \"deploy_dedicated_servers\": $DEPLOY_DEDICATED_BANKS,"
echo "  \"dedicated_bank_ids\": $dedicated_ids_json,"
echo "  \"files\": ["

if [ -f "$TEMP_DETAILS_FILE" ]; then
    awk -F'|' '{
        printf "    {\"path\":\"%s\",\"app\":\"%s\",\"type\":\"%s\"}", $1,$2,$3
        if (NR != total) printf ","
        printf "\n"
    }' total=$(wc -l < "$TEMP_DETAILS_FILE") "$TEMP_DETAILS_FILE"
fi

echo "  ]"
echo "}"
} > "$METADATA_FILE"

log "Metadata file created: $METADATA_FILE"
cat "$METADATA_FILE"
echo

# ---------------------------------------------------------------------------------------------------------------------
# EXECUTION SUMMARY
# ---------------------------------------------------------------------------------------------------------------------
echo
echo "============================================================"
echo "                     EXECUTION SUMMARY"
echo "============================================================"
echo "ENVIRONMENT : $ENV"
echo "BRANCH      : $BRANCH"
echo "COMMIT ID   : $COMMIT_ID"
echo "AUTHOR      : $AUTHOR"
echo "DATE        : $COMMIT_DATE"
echo
echo "-------------------- FILE CHANGE COUNTS --------------------"
echo "NEW FILES      : $NEW_COUNT"
echo "MODIFIED FILES : $MODIFIED_COUNT"
echo "DELETED FILES  : $DELETED_COUNT"
echo
echo "-------------------- DEPLOYMENT TARGETS --------------------"
echo "DEDICATED SERVERS : $DEPLOY_DEDICATED_BANKS"
echo "DEDICATED BANK IDS: ${DEPLOY_DEDICATED_BANK_IDS[*]:-none}"
echo
echo "-------------------- FILE CHANGE DETAILS -------------------"
if [ -f "$MANIFEST_FILE" ]; then
    while IFS= read -r line; do
        FILE_CHANGE_TYPE=$(echo "$line" | cut -d'|' -f1)
        FILE_PATH=$(echo "$line" | cut -d'|' -f2)
        printf "[%-9s] %s\n" "$FILE_CHANGE_TYPE" "$FILE_PATH"
    done < "$MANIFEST_FILE"
else
    echo "No changes detected."
fi

echo
echo "============================================================"
echo "END TIME: $(date)"
echo "============================================================"
echo
