<%--
//Generated by Customization WB Generator
//Do not edit this file directly.
//Instead, modify the properties in the tool and regenerate.
--%>
<%@ page import="FABCommon.SecurityInfo70"%>
<%@ page import="applcommon.ParseValue" %>
<%@ page import="com.infy.bbu.jsputil.*"%>
<%@ taglib uri="taglib.tld" prefix="arjsp" %>
<arjsp:init groupName="Customize" isEntryPoint="false" />

<%
	String sProfileId = ProfilesManager.getProfileInSession(session);
	String sSubGrpName = (String)ARJspCurr.getInput("subGroupName","");
	String sGrpName = ARJspCurr.getCurrentGroup();
	String sPopUpExceptionWindow = (String)ARJspCurr.getInput(sGrpName+".PopUpExceptionWindow" ,"false");
	String sReferralMode = (String)ARJspCurr.getInput("refSubMode" ,"");
	ARJspCurr.setInput(sGrpName+".PopUpExceptionWindow","false");
	SecurityInfo70 securityInfo = (SecurityInfo70)session.getAttribute("FinUserInfo");
	String BODDate = (String)((securityInfo.bodDate).substring(0,10));
%>
<script>
	var sPopUpExceptionWindow = '<%=sPopUpExceptionWindow%>';
	var sReferralMode = '<%=sReferralMode%>' ;
	var subGroupName = '<%=ParseValue.checkString(ARJspCurr.getInput("subGroupName",""))%>';
	var contextSolId = '<%=ParseValue.checkString(securityInfo.contextSolId)%>';
	var funcCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".funcCode",""))%>';
	var setID = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".setID",""))%>';
	var zoneDate = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".zoneDate_ui",""))%>';
	var zoneCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".zoneCode",""))%>';
	var BODDate = '<%=BODDate%>';
</script>


<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showFABZoneCode.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showICTMZoneCodeList.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showInClgZoneCode.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/custom/javascripts/custom_functions.js"></script>
<script language="javascript" src="../Renderer/custom/javascripts/custom_common_functions.js"></script>
<script language="javascript" src="../Renderer/custom/javascripts/cust_fetch_list.js"></script>

<script language="JavaScript">
	printBlock();
	printFooterBlock();
</script>

