<%--
//Generated by Customization WB Generator
//Do not edit this file directly.
//Instead, modify the properties in the tool and regenerate.
--%>

<%@ page import="java.util.HashMap,applcommon.ParseValue,finbranchUtil.CustomMultiRecHandler" %>
<%@ page import="com.infy.bbu.jsputil.*"%>
<%@ page import="java.util.Vector"%>
<%@ page import="FABCommon.SecurityInfo70"%>
<%@ taglib uri="taglib.tld" prefix="arjsp" %>
<arjsp:init groupName="Customize" isEntryPoint="false" />

<%
	String sProfileId = ProfilesManager.getProfileInSession(session);
        String sSubGrpName = (String)ARJspCurr.getInput("subGroupName","");
        String sGrpName = ARJspCurr.getCurrentGroup();
        String pageName = (String)ARJspCurr.getInput("jspName","");
        String sPopUpExceptionWindow = (String)ARJspCurr.getInput(sGrpName+".PopUpExceptionWindow" ,"false");
        String sReferralMode = (String)ARJspCurr.getInput("refSubMode" ,"");
        ARJspCurr.setInput(sGrpName+".PopUpExceptionWindow","false");
        SecurityInfo70 securityInfo = (SecurityInfo70)session.getAttribute("FinUserInfo");
%>
<script>

	var sPopUpExceptionWindow = '<%=ParseValue.checkString(sPopUpExceptionWindow)%>';
        var sReferralMode = '<%=ParseValue.checkString(sReferralMode)%>';
        var subGroupName = '<%=ParseValue.checkString(ARJspCurr.getInput("subGroupName",""))%>';
        var BODDate= '<%= ParseValue.checkString((securityInfo.bodDate).substring(0,10))%>';
        var funcCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".funcCode",""))%>';
        var acctId = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".acctId",""))%>';
	var custId = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".custId",""))%>';
	var custName = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".custName",""))%>';
	var empId = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".empId",""))%>';
	var empName = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".empName",""))%>';
	var preferentialLevel = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".preferentialLevel",""))%>';
	var startDate = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".startDate",""))%>';
	var endDate = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".endDate",""))%>';
	var percent = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".percent",""))%>';
	var value1 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".value1",""))%>';
	var value2 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".value2",""))%>';
	var acctName = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".acctName",""))%>';
	var custName = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".custName",""))%>';
	var evtTypeDesc = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".evtTypeDesc",""))%>';	
	var evtType = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".evtType",""))%>';
	var evtId = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".evtId",""))%>';
	var customerType = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".customerType",""))%>';	
	var segmentationLevel = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".segmentationLevel",""))%>';	

	var minamt = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".minamt",""))%>';
	var maxamt = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".maxamt",""))%>';

	var tmpCrncyCode = 'INR';


</script>
	<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("resource_functions.js",sProfileId)%>" > </script>
        <script language="javascript" src="../Renderer/custom/javascripts/custom_functions.js"></script>
        <script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("common_functions.js",sProfileId)%>"></script>
	<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showCurrency.js",sProfileId)%>" > </script>
	<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showSearcher.js",sProfileId)%>" > </script>
	<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("getEvtIdList.js",sProfileId)%>" > </script>	
<script language="JavaScript">
</script>

<script language="JavaScript">
        printBlock();
        printFooterBlock();
</script>
