--====================================================================================================                    
-- Table Name             : CUSTOM.FCFTT_MOD
-- Synonym Name           : CUSTOM.FCFTT_MOD                  
-- Date                   : 7-FEB-2018                    
-- Description            : This table is used for adding advertising code.     
-- Author                 : lakshmi.rajanala       
-- Modification History   :                    
-- <Version No.>         <Date>                 <Author Name>               <Description>                    
--====================================================================================================

DROP TABLE CUSTOM.FCFTT_MOD CASCADE CONSTRAINTS;

CREATE TABLE CUSTOM.FCFTT_MOD
(
  ACID            VARCHAR2(11 CHAR),
  BANK_ID         VARCHAR2(8 CHAR),
  FREE_CODE_1     VARCHAR2(16 CHAR),
  FREE_CODE_2     VARCHAR2(16 CHAR),
  FREE_CODE_3     VARCHAR2(16 CHAR),
  FREE_CODE_4     VARCHAR2(16 CHAR),
  FREE_CODE_5     VARCHAR2(16 CHAR),
  FREE_CODE_6     VARCHAR2(16 CHAR),
  FREE_CODE_7     VARCHAR2(16 CHAR),
  FREE_CODE_8     VARCHAR2(16 CHAR),
  FREE_CODE_9     VARCHAR2(16 CHAR),
  FREE_CODE_10    VARCHAR2(16 CHAR),
  FREE_CODE_11    VARCHAR2(16 CHAR),
  FREE_CODE_12    VARCHAR2(16 CHAR),
  FREE_CODE_13    VARCHAR2(16 CHAR),
  FREE_CODE_14    VARCHAR2(16 CHAR),
  FREE_CODE_15    VARCHAR2(16 CHAR),
  FREE_CODE_16    VARCHAR2(16 CHAR),
  FREE_CODE_17    VARCHAR2(16 CHAR),
  FREE_CODE_18    VARCHAR2(16 CHAR),
  FREE_CODE_19    VARCHAR2(16 CHAR),
  FREE_CODE_20    VARCHAR2(16 CHAR),
  FREE_CODE_21    VARCHAR2(16 CHAR),
  FREE_CODE_22    VARCHAR2(16 CHAR),
  FREE_CODE_23    VARCHAR2(16 CHAR),
  FREE_CODE_24    VARCHAR2(16 CHAR),
  FREE_CODE_25    VARCHAR2(16 CHAR),
  FREE_CODE_26    VARCHAR2(16 CHAR),
  FREE_CODE_27    VARCHAR2(16 CHAR),
  FREE_CODE_28    VARCHAR2(16 CHAR),
  FREE_CODE_29    VARCHAR2(16 CHAR),
  FREE_CODE_30    VARCHAR2(16 CHAR),
  FREE_CODE_31    VARCHAR2(16 CHAR),
  FREE_CODE_32    VARCHAR2(16 CHAR),
  FREE_CODE_33    VARCHAR2(16 CHAR),
  FREE_CODE_34    VARCHAR2(16 CHAR),
  FREE_CODE_35    VARCHAR2(16 CHAR),
  FREE_CODE_36    VARCHAR2(16 CHAR),
  FREE_CODE_37    VARCHAR2(16 CHAR),
  FREE_CODE_38    VARCHAR2(16 CHAR),
  FREE_CODE_39    VARCHAR2(16 CHAR),
  FREE_CODE_40    VARCHAR2(16 CHAR),
  FREE_CODE_41    VARCHAR2(16 CHAR),
  FREE_CODE_42    VARCHAR2(16 CHAR),
  FREE_CODE_43    VARCHAR2(16 CHAR),
  FREE_CODE_44    VARCHAR2(16 CHAR),
  FREE_CODE_45    VARCHAR2(16 CHAR),
  FREE_CODE_46    VARCHAR2(16 CHAR),
  FREE_CODE_47    VARCHAR2(16 CHAR),
  FREE_CODE_48    VARCHAR2(16 CHAR),
  FREE_CODE_49    VARCHAR2(16 CHAR),
  FREE_CODE_50    VARCHAR2(16 CHAR),
  FREE_CODE_51    VARCHAR2(16 CHAR),
  FREE_CODE_52    VARCHAR2(16 CHAR),
  FREE_CODE_53    VARCHAR2(16 CHAR),
  FREE_CODE_54    VARCHAR2(16 CHAR),
  FREE_CODE_55    VARCHAR2(16 CHAR),
  FREE_TEXT_1     VARCHAR2(80 CHAR),
  FREE_TEXT_2     VARCHAR2(80 CHAR),
  FREE_TEXT_3     VARCHAR2(80 CHAR),
  FREE_TEXT_4     VARCHAR2(80 CHAR),
  FREE_TEXT_5     VARCHAR2(80 CHAR),
  FREE_TEXT_6     VARCHAR2(80 CHAR),
  FREE_TEXT_7     VARCHAR2(80 CHAR),
  FREE_TEXT_8     VARCHAR2(80 CHAR),
  FREE_TEXT_9     VARCHAR2(80 CHAR),
  FREE_TEXT_10    VARCHAR2(80 CHAR),
  FREE_TEXT_11    VARCHAR2(80 CHAR),
  FREE_TEXT_12    VARCHAR2(80 CHAR),
  FREE_TEXT_13    VARCHAR2(80 CHAR),
  FREE_TEXT_14    VARCHAR2(80 CHAR),
  FREE_TEXT_15    VARCHAR2(80 CHAR),
  FREE_TEXT_16    VARCHAR2(80 CHAR),
  FREE_TEXT_17    VARCHAR2(80 CHAR),
  FREE_TEXT_18    VARCHAR2(80 CHAR),
  FREE_TEXT_19    VARCHAR2(80 CHAR),
  FREE_TEXT_20    VARCHAR2(80 CHAR),
  DEL_FLG         CHAR(1 BYTE),
  ENTITY_CRE_FLG  CHAR(1 BYTE),
  LCHG_USER_ID    VARCHAR2(15 CHAR),
  LCHG_TIME       DATE,
  RCRE_USER_ID    VARCHAR2(15 CHAR),
  RCRE_TIME       DATE,
  TS_CNT          NUMBER(5)
);


CREATE UNIQUE INDEX CUSTOM.FCFTT_M ON CUSTOM.FCFTT_MOD
(ACID, BANK_ID)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             16K
            MINEXTENTS       1
            MAXEXTENTS       505
            PCTINCREASE      50
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

DROP SYNONYM CUSTOM.FCFTT_M;

CREATE SYNONYM CUSTOM.FCFTT_M FOR CUSTOM.FCFTT_MOD;

GRANT INSERT, SELECT, UPDATE, DELETE ON CUSTOM.FCFTT_MOD TO TBAADM;

GRANT INSERT, SELECT, UPDATE, DELETE ON CUSTOM.FCFTT_MOD TO TBAGEN;

GRANT INSERT, SELECT, UPDATE, DELETE ON CUSTOM.FCFTT_MOD TO TBAUTIL;

COMMIT;



