Insert into CUSTOM.C_CPMASTER
   (MODULE_NAME, PARAMETER_LEVEL, PARAMETER_ID, PARAMETER_DESC, PARAMETER_TYPE, QUERY_ID, LIST_TYPE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID)
 Values
   ('LOANS', 'BNKL', 'LPDN', 'LOAN DISB CHARGES NON PAST DUE', 'AN', ' ', 'FT', 'Y', 'N', 'TBAADM', SYSDATE, 'TBAADM', SYSDATE, '43');
Insert into CUSTOM.C_CPMASTER
   (MODULE_NAME, PARAMETER_LEVEL, PARAMETER_ID, PARAMETER_DESC, PARAMETER_TYPE, QUERY_ID, LIST_TYPE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID)
 Values
   ('LOANS', 'BNKL', 'LPDY', 'LOAN DISB CHARGES PAST DUE', 'AN', ' ', 'FT', 'Y', 'N', 'TBAADM', SYSDATE, 'TBAADM', SYSDATE, '43');
Insert into CUSTOM.C_CPVALUE
   (PARAMETER_ID, LEVELCODE_1, PARAMETER_VALUE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID, MODULE_NAME)
 Values
   ('LPDN', 'ALL', '', 'Y', 'N', 'TBAADM', SYSDATE, 'TBAADM', SYSDATE, '43', 'LOANS');
Insert into CUSTOM.C_CPVALUE
   (PARAMETER_ID, LEVELCODE_1, PARAMETER_VALUE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID, MODULE_NAME)
 Values
   ('LPDY', 'ALL', '', 'Y', 'N', 'TBAADM', SYSDATE, 'TBAADM', SYSDATE, '43', 'LOANS');
COMMIT;
