//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT026332:" Code de réception ",FLT026333:"Identifiant du rôle ",FLT026334:" Lmt Cred Cash 5( limite de crédit de liquidité ou cash crédit ) ",FLT026335:"Transfr Cred Lmt ( limite de transfert de crédit )",FLT026336:"Clearing Cred Lmt  (solde de crédit de liquidité)",FLT026337:"Trésorerie Int Sol Lmt ( limite de solde initial de la trésorerie)",FLT026338:"Transfr Int Sol Lmt  (limite de transfert initial du solde)",FLT026339:"Clrg Int Sol Lmt  (limite de solde de liquidité) ",FLT026340:" Devise",FLT026341:"Sélectionner--",FLT026342:" AJOUTER",FLT026343:"MODIFIER",FLT026344:" VERIFIER",FLT026345:"DEMANDE",FLT026346:"ANNULER"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);
