//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY
var jspRes={FLT026332:"Fonction",FLT026333:"Sélectionner",FLT026334:": R-Rejeter",FLT026337:"Numéro de compte",FLT026338:": Numéro dinstrument",FLT026339:"Montant de linstrument"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);
