//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT026331:" Nom du fichier",FLT004977:" (Aller)",FLT031869:" SIG dentreprise",FLT031872:"Menu CORPSIG pour SVS",FLT000193:"Envoyer  (soumettre) ",FLT001721:"Annuler /Effacer "};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY 
var jspErr={};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);
