//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT022001:"Signaler (rapporter) à  ",FLT022002:"Type de de sous transaction (transfert) ",FLT022003:"Télécharger le nom du fichier",FLT022004:"Test? (Y/N)",FLT022005:"Remarques du Transaction (transfert)",FLT022006:" Renommer le fichier dentrée",FLT022007:"S-relevé  P-Tarif "};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);
