//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT027769:"FLT027769: Modification de dénomination de guichet",FAT000703:"Fonction",FTT000072:" Devise",FLT014433:"FLT014433: Identité (ID)   du revendeur",FHP000439:"Id Sol",FLT012410:"Sélectionner--",FLT027766:"M-Modifier",FLT027767:"V-Vérifier ",FLT027768:"FLT027768: I-Enquêter/S’informer",FLT027575:"X-Annuler"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY
var jspErr={FAT000924:"Enter a value in the field."};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);

