--====================================================================================================
-- Table Name: DMG_NOTE_TRAN_DETAIL_TBL
-- Synonym Name : C_DNTD
-- Date: 8-June-2018
-- Description: This table is used for Capturing Commission Transactions Details for Damaged Notes
-- Author: Anshul_Singh04
-- Modification History :
--<Version No.> <Date> <Author Name> <Description>
--====================================================================================================

DROP TABLE CUSTOM.DMG_NOTE_TRAN_DETAIL_TBL CASCADE CONSTRAINTS;

CREATE TABLE CUSTOM.DMG_NOTE_TRAN_DETAIL_TBL
(
	TRAN_ID			   VARCHAR2(9 CHAR),
	TRAN_DATE     	   DATE,
	TRAN_TYPE		   CHAR(1 BYTE),
	TRAN_SUB_TYPE	   VARCHAR2(2 CHAR),
	INIT_SOL_ID		   VARCHAR2(8 CHAR),
	CRNCY_CODE         VARCHAR2(3 CHAR),
	DMG_NOTE_AMT	   NUMBER(20,4),
	CHARGE_AMT		   NUMBER(20,4),
	VAT_AMT			   NUMBER(20,4),
	ACCT_ID		 	   VARCHAR2(16 CHAR),
	COMM_ACCT_ID 	   VARCHAR2(16 CHAR),
	VAT_ACCT_ID        VARCHAR2(16 CHAR),
	RATE_CODE		   VARCHAR2(5 CHAR),
	RATE			   NUMBER(21,10),
	CHRG_TRAN_ID	   VARCHAR2(9 CHAR),
	CHRG_TRAN_DATE     DATE,
	RCRE_USER_ID       VARCHAR2(15 CHAR),
	RCRE_TIME          DATE,
	BANK_ID            VARCHAR2(8 CHAR),
	TRAN_STATUS 	   CHAR (1 BYTE),
	FAILURE_REMARKS    VARCHAR2(200 CHAR)
);

DROP INDEX CUSTOM.IDX_DMG_NOTE_TRAN;

CREATE UNIQUE INDEX CUSTOM.IDX_DMG_NOTE_TRAN ON CUSTOM.DMG_NOTE_TRAN_DETAIL_TBL
(TRAN_ID,TRAN_DATE,BANK_ID);

DROP SYNONYM CUSTOM.C_DNTD;

CREATE SYNONYM CUSTOM.C_DNTD FOR CUSTOM.DMG_NOTE_TRAN_DETAIL_TBL;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.DMG_NOTE_TRAN_DETAIL_TBL TO TBAADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.DMG_NOTE_TRAN_DETAIL_TBL TO TBAGEN;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.DMG_NOTE_TRAN_DETAIL_TBL TO TBAUTIL;
