logging:
  level:
    ROOT: INFO
    org.hibernate: INFO
    com.equitybank.gag.telco_b2c: INFO
    com.netflix.discovery.DiscoveryClient: INFO

server:
  port: 8072

# JWT bearer token configs
security:
  jwt:
    secret-key: "icUIRr1mA+NjF944xIsVO1b47I1PgCZjCGoJxSgtAds="
  user:
    username: "uat"
    password: "R7$wY9xt*bdQ&z5w"
