logging:
  level:
    ROOT: INFO
    org.hibernate: INFO
    com.equitybank.gag.telco_b2c: INFO
    com.netflix.discovery.DiscoveryClient: INFO

server:
  ssl:
    enabled: true
    key-store: '/Users/bishop/Programming/projects/work/WorkSpace/NetBeans/GAG/GAGApplications/Broker-Migration/certs/EQUITY-MTN-SS.p12'
    key-store-password: 'Ja6XzA129fT4'
    key-store-type: PKCS12
    key-alias: tomcat

# For multiple server port configuration
http:
  port: 8072
https:
  port: 9443

# JWT bearer token configs
security:
  jwt:
    secret-key: "icUIRr1mA+NjF944xIsVO1b47I1PgCZjCGoJxSgtAds="
  user:
    username: "uat"
    password: "R7$wY9xt*bdQ%26z5w"
