spring:
  application:
#    name: VODACOM-MONEY-B2C-MS
     name: dummy-telco-b2c-ms
  profiles:
    active: uat

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    service-url:
#      defaultZone: http://localhost:8581/eureka/

# actuator configs
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true # for gracefully shutting down the app - http://localhost:<PortNumber>/actuator/shutdown
    health:
      show-details: when_authorized
  info:
    env:
      enabled: true