DROP TABLE CUSTOM.CUST_SOL_MAINTANANCE CASCADE CONSTRAINTS;

CREATE TABLE CUSTOM.CUST_SOL_MAINTANANCE
(
  SOL_ID   VARCHAR2(20 BYTE)                    NOT NULL,
  DIS_FLG  VARCHAR2(1 BYTE)                     NOT NULL,
  BANK_ID  VARCHAR2(8 CHAR)
);

CREATE UNIQUE INDEX CUSTOM.IDX_CUST_SOL_MAINTANANCE ON CUSTOM.CUST_SOL_MAINTANANCE
(SOL_ID, DIS_FLG);








DROP SYNONYM CUSTOM.C_SOLMNT;

CREATE SYNONYM CUSTOM.C_SOLMNT FOR CUSTOM.CUST_SOL_MAINTANANCE;

DROP SYNONYM TBAADM.C_SOLMNT;

CREATE SYNONYM TBAADM.C_SOLMNT FOR CUSTOM.CUST_SOL_MAINTANANCE;

DROP SYNONYM TBAGEN.C_SOLMNT;

CREATE SYNONYM TBAGEN.C_SOLMNT FOR CUSTOM.CUST_SOL_MAINTANANCE;

DROP SYNONYM TBAUTIL.C_SOLMNT;

CREATE SYNONYM TBAUTIL.C_SOLMNT FOR CUSTOM.CUST_SOL_MAINTANANCE;

GRANT SELECT ON CUSTOM.CUST_SOL_MAINTANANCE TO ALLTAB;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.CUST_SOL_MAINTANANCE TO TBAADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.CUST_SOL_MAINTANANCE TO TBAGEN;

GRANT SELECT ON CUSTOM.CUST_SOL_MAINTANANCE TO TBAUTIL;
