CREATE TABLE CUSTOM.OLD_ACCT_MAP
(
  OLD_NUM      VARCHAR2(13 BYTE),
  FORACID      VARCHAR2(15 BYTE),
  SOL_ID       VARCHAR2(8 BYTE),
  REALM_BAL    NUMBER,
  FINACLE_BAL  NUMBER,
  BANK_ID      VARCHAR2(3 BYTE)
);


CREATE UNIQUE INDEX CUSTOM.IDX_OLD_ACCT_MAP ON CUSTOM.OLD_ACCT_MAP
(SOL_ID, OLD_NUM, FORACID, BANK_ID);


CREATE SYNONYM CUSTOM.OLD_ACCT_MAP_AM FOR CUSTOM.OLD_ACCT_MAP;


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON CUSTOM.OLD_ACCT_MAP TO TBAADM;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON CUSTOM.OLD_ACCT_MAP TO TBAGEN;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON CUSTOM.OLD_ACCT_MAP TO TBAUTIL;
