CREATE TABLE CUSTOM.PAYBILLCOLL_UPLOAD_TABLE
(
  RECEIPT          VARCHAR2(20 BYTE),
  PAYBILL_DATE     VARCHAR2(50 BYTE),
  DETAILS          VARCHAR2(255 BYTE),
  AMOUNT           NUMBER(10,2),
  OTHERPARTYINFO   VARCHAR2(100 BYTE),
  OTHERPARTYNAME   VARCHAR2(100 BYTE),
  ACCOUNTNUMBER    VARCHAR2(100 BYTE),
  ENTRY_USER_ID    VARCHAR2(15 BYTE),
  SOL_ID           VARCHAR2(8 BYTE),
  ACCT_NAME        VARCHAR2(100 BYTE),
  ACCT_CRNCY_CODE  VARCHAR2(5 BYTE),
  VALID            VARCHAR2(1 BYTE)             DEFAULT 'N',
  REMARKS          VARCHAR2(100 BYTE),
  CHECKSUM         LONG,
  BANK_ID          VARCHAR2(10 BYTE)
);


--CREATE PUBLIC SYNONYM C_PAYBILLCOLL FOR PAYBILLCOLL_UPLOAD_TABLE;


CREATE SYNONYM CUSTOM.C_PAYBILLCOLL FOR CUSTOM.PAYBILLCOLL_UPLOAD_TABLE;


GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.PAYBILLCOLL_UPLOAD_TABLE TO TBAADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.PAYBILLCOLL_UPLOAD_TABLE TO TBAGEN;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.PAYBILLCOLL_UPLOAD_TABLE TO TBAUTIL;
