DROP TABLE CUSTOM.STAFFSAL CASCADE CONSTRAINTS;

CREATE TABLE CUSTOM.STAFFSAL
(
  SRNO      NUMBER(10),
  SOLID     VARCHAR2(8 BYTE),
  OLDACC    VARCHAR2(15 BYTE),
  AMT       VARCHAR2(30 BYTE),
  TRANTYPE  VARCHAR2(2 BYTE),
  NEWACC    VARCHAR2(15 BYTE),
  BANK_ID   VARCHAR2(3 BYTE)
);




GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.STAFFSAL TO TBAADM;


GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.STAFFSAL TO TBAGEN;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.STAFFSAL TO TBAUTIL;


