DROP SEQUENCE CUSTOM.CHQBOOKDOWNLOAD_SEQ_11;

CREATE SEQUENCE CUSTOM.CHQBOOKDOWNLOAD_SEQ_11
  START WITH 5452
  MAXVALUE 99999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


DROP SEQUENCE CUSTOM.CHQBOOKDOWNLOAD_SEQ_50;

CREATE SEQUENCE CUSTOM.CHQBOOKDOWNLOAD_SEQ_50
  START WITH 6160
  MAXVALUE 99999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


DROP SEQUENCE CUSTOM.CHQBOOKDOWNLOAD_SEQ_54;

CREATE SEQUENCE CUSTOM.CHQBOOKDOWNLOAD_SEQ_54
  START WITH 7359
  MAXVALUE 99999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


DROP SEQUENCE CUSTOM.CHQBOOKDOWNLOAD_SEQ_55;

CREATE SEQUENCE CUSTOM.CHQBOOKDOWNLOAD_SEQ_55
  START WITH 4793
  MAXVALUE 99999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


DROP SEQUENCE CUSTOM.CHQBOOKDOWNLOAD_SEQ_56;

CREATE SEQUENCE CUSTOM.CHQBOOKDOWNLOAD_SEQ_56
  START WITH 10122
  MAXVALUE 99999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

  
GRANT SELECT ON CUSTOM.CHQBOOKDOWNLOAD_SEQ_11 TO TBAADM;

GRANT SELECT ON CUSTOM.CHQBOOKDOWNLOAD_SEQ_50 TO TBAADM;

GRANT SELECT ON CUSTOM.CHQBOOKDOWNLOAD_SEQ_54 TO TBAADM;

GRANT SELECT ON CUSTOM.CHQBOOKDOWNLOAD_SEQ_55 TO TBAADM;

GRANT SELECT ON CUSTOM.CHQBOOKDOWNLOAD_SEQ_56 TO TBAADM;

GRANT SELECT ON CUSTOM.CHQBOOKDOWNLOAD_SEQ_11 TO TBAGEN;

GRANT SELECT ON CUSTOM.CHQBOOKDOWNLOAD_SEQ_50 TO TBAGEN;

GRANT SELECT ON CUSTOM.CHQBOOKDOWNLOAD_SEQ_54 TO TBAGEN;

GRANT SELECT ON CUSTOM.CHQBOOKDOWNLOAD_SEQ_55 TO TBAGEN;

GRANT SELECT ON CUSTOM.CHQBOOKDOWNLOAD_SEQ_56 TO TBAGEN;

GRANT SELECT ON CUSTOM.CHQBOOKDOWNLOAD_SEQ_11 TO TBAUTIL;

GRANT SELECT ON CUSTOM.CHQBOOKDOWNLOAD_SEQ_50 TO TBAUTIL;

GRANT SELECT ON CUSTOM.CHQBOOKDOWNLOAD_SEQ_54 TO TBAUTIL;

GRANT SELECT ON CUSTOM.CHQBOOKDOWNLOAD_SEQ_55 TO TBAUTIL;

GRANT SELECT ON CUSTOM.CHQBOOKDOWNLOAD_SEQ_56 TO TBAUTIL;
