CREATE TABLE CUSTOM.C_CPARAM_MASTER_TABLE
(
  MODULE_NAME      VARCHAR2(30 BYTE),
  PARAMETER_LEVEL  VARCHAR2(10 BYTE),
  PARAMETER_ID     VARCHAR2(30 BYTE),
  PARAMETER_DESC   VARCHAR2(50 BYTE),
  PARAMETER_TYPE   VARCHAR2(7 BYTE),
  QUERY_ID         VARCHAR2(5 BYTE),
  LIST_TYPE        VARCHAR2(2 BYTE),
  ENTITY_CRE_FLG   CHAR(1 BYTE),
  DEL_FLG          CHAR(1 BYTE),
  RCRE_USER_ID     VARCHAR2(15 BYTE),
  RCRE_TIME        DATE,
  LCHG_USER_ID     VARCHAR2(15 BYTE),
  LCHG_TIME        DATE,
  BANK_ID          VARCHAR2(10 CHAR)            NOT NULL
);


CREATE UNIQUE INDEX CUSTOM.IDX_C_CPARAM_MASTER_TABLE ON CUSTOM.C_CPARAM_MASTER_TABLE
(PARAMETER_ID, MODULE_NAME, BANK_ID);


CREATE SYNONYM TBAADM.CUST_C_CPARAM_MASTER_TABLE FOR CUSTOM.C_CPARAM_MASTER_TABLE;


CREATE SYNONYM TBAGEN.CUST_C_CPARAM_MASTER_TABLE FOR CUSTOM.C_CPARAM_MASTER_TABLE;


CREATE SYNONYM TBAUTIL.CUST_C_CPARAM_MASTER_TABLE FOR CUSTOM.C_CPARAM_MASTER_TABLE;


CREATE SYNONYM CUSTOM.CUST_C_CPARAM_MASTER_TABLE FOR CUSTOM.C_CPARAM_MASTER_TABLE;


CREATE SYNONYM TBAADM.C_CPMASTER FOR CUSTOM.C_CPARAM_MASTER_TABLE;


CREATE SYNONYM TBAGEN.C_CPMASTER FOR CUSTOM.C_CPARAM_MASTER_TABLE;


CREATE SYNONYM CUSTOM.C_CPMASTER FOR CUSTOM.C_CPARAM_MASTER_TABLE;


CREATE SYNONYM TBAUTIL.C_CPMASTER FOR CUSTOM.C_CPARAM_MASTER_TABLE;


CREATE SYNONYM TBAADM.C_CPARAM_MASTER_TABLE FOR CUSTOM.C_CPARAM_MASTER_TABLE;


CREATE SYNONYM TBAGEN.C_CPARAM_MASTER_TABLE FOR CUSTOM.C_CPARAM_MASTER_TABLE;


CREATE SYNONYM TBAUTIL.C_CPARAM_MASTER_TABLE FOR CUSTOM.C_CPARAM_MASTER_TABLE;


GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.C_CPARAM_MASTER_TABLE TO TBAGEN;

GRANT SELECT ON CUSTOM.C_CPARAM_MASTER_TABLE TO TBAUTIL;
