CREATE TABLE CUSTOM.CUST_DENOM_MASTER
(
  SOL_ID        VARCHAR2(20 BYTE)               NOT NULL,
  CRNCY_CODE    VARCHAR2(5 BYTE)                NOT NULL,
  DENOM_IND     CHAR(1 BYTE)                    NOT NULL,
  DENOM_VALUE   NUMBER(10,2)                    NOT NULL,
  DENOM_COUNT   NUMBER(20),
  TELLER_ID     VARCHAR2(20 BYTE),
  RCRE_USER_ID  VARCHAR2(15 BYTE)               NOT NULL,
  RCRE_TIME     DATE                            NOT NULL,
  LCHG_USER_ID  VARCHAR2(15 BYTE)               NOT NULL,
  LCHG_TIME     DATE                            NOT NULL,
  DEL_FLG       CHAR(1 BYTE)                    NOT NULL,
  BANK_ID       VARCHAR2(8 CHAR)
);


CREATE UNIQUE INDEX CUSTOM.IDX_CUST_DENOM_MASTER ON CUSTOM.CUST_DENOM_MASTER
(SOL_ID, CRNCY_CODE, DENOM_IND, DENOM_VALUE, TELLER_ID, 
BANK_ID);


CREATE SYNONYM CUSTOM.C_DENM FOR CUSTOM.CUST_DENOM_MASTER;


CREATE SYNONYM TBAGEN.C_DENM FOR CUSTOM.CUST_DENOM_MASTER;


CREATE SYNONYM TBAUTIL.C_DENM FOR CUSTOM.CUST_DENOM_MASTER;


CREATE SYNONYM TBAADM.C_DENM FOR CUSTOM.CUST_DENOM_MASTER;


GRANT SELECT ON CUSTOM.CUST_DENOM_MASTER TO READONLY;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.CUST_DENOM_MASTER TO TBAADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.CUST_DENOM_MASTER TO TBAGEN;

GRANT SELECT ON CUSTOM.CUST_DENOM_MASTER TO TBAUTIL;
