DROP TABLE CUSTOM.INTENT_REV_TRAN_DETAIL_TBL CASCADE CONSTRAINTS;

CREATE TABLE CUSTOM.INTENT_REV_TRAN_DETAIL_TBL
(
  IE_TXN_REF_NO          VARCHAR2(10 CHAR),
  ENTITY1_TRAN_ID        VARCHAR2(9 CHAR),
  ENTITY1_TRAN_DATE      DATE,
  ENTITY2_TRAN_ID        VARCHAR2(9 CHAR),
  ENTITY2_TRAN_DATE      DATE,
  ORG_CHRG_TRAN_ID       VARCHAR2(9 CHAR),
  ORG_CHARGE_TRAN_DATE   DATE,
  ENTITY1_REV_TRAN_ID    VARCHAR2(9 CHAR),
  ENTITY1_REV_TRAN_DATE  DATE,
  ENTITY2_REV_TRAN_ID    VARCHAR2(9 CHAR),
  ENTITY2_REV_TRAN_DATE  DATE,
  REV_CHRG_TRAN_ID       VARCHAR2(9 CHAR),
  REV_CHARGE_TRAN_DATE   DATE,
  DEL_FLG                CHAR(1 BYTE),
  ENTITY_CRE_FLG         CHAR(1 BYTE),
  RCRE_USER_ID           VARCHAR2(15 CHAR),
  RCRE_TIME              DATE,
  LCHG_USER_ID           VARCHAR2(15 CHAR),
  LCHG_TIME              DATE,
  BANK_ID                VARCHAR2(8 CHAR)
);






DROP SYNONYM CUSTOM.IEREV;

CREATE SYNONYM CUSTOM.IEREV FOR CUSTOM.INTENT_REV_TRAN_DETAIL_TBL;

DROP SYNONYM TBAADM.INTENT_REV_TRAN_DETAIL_TBL;

CREATE SYNONYM TBAADM.INTENT_REV_TRAN_DETAIL_TBL FOR CUSTOM.INTENT_REV_TRAN_DETAIL_TBL;

DROP SYNONYM TBAGEN.IEREV;

CREATE SYNONYM TBAGEN.IEREV FOR CUSTOM.INTENT_REV_TRAN_DETAIL_TBL;

DROP SYNONYM TBAGEN.INTENT_REV_TRAN_DETAIL_TBL;

CREATE SYNONYM TBAGEN.INTENT_REV_TRAN_DETAIL_TBL FOR CUSTOM.INTENT_REV_TRAN_DETAIL_TBL;

DROP SYNONYM TBAUTIL.IEREV;

CREATE SYNONYM TBAUTIL.IEREV FOR CUSTOM.INTENT_REV_TRAN_DETAIL_TBL;

DROP SYNONYM TBAUTIL.INTENT_REV_TRAN_DETAIL_TBL;

CREATE SYNONYM TBAUTIL.INTENT_REV_TRAN_DETAIL_TBL FOR CUSTOM.INTENT_REV_TRAN_DETAIL_TBL;

GRANT SELECT ON CUSTOM.INTENT_REV_TRAN_DETAIL_TBL TO ALLTAB;

GRANT SELECT ON CUSTOM.INTENT_REV_TRAN_DETAIL_TBL TO TBAADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.INTENT_REV_TRAN_DETAIL_TBL TO TBAGEN;

GRANT SELECT ON CUSTOM.INTENT_REV_TRAN_DETAIL_TBL TO TBAUTIL;

