ALTER TABLE CUSTOM.FX_REVAL
 DROP PRIMARY KEY CASCADE;
DROP TABLE CUSTOM.FX_REVAL CASCADE CONSTRAINTS;

CREATE TABLE CUSTOM.FX_REVAL
(
  CURRENCY_CODE      VARCHAR2(3 BYTE),
  RATE_CODE          VARCHAR2(10 BYTE),
  PNL_ACCOUNT        VARCHAR2(30 BYTE),
  HOMECY_ACCOUNT     VARCHAR2(30 BYTE),
  FOREIGNCY_ACCOUNT  VARCHAR2(30 BYTE),
  BANK_ID            VARCHAR2(8 BYTE)
);

ALTER TABLE CUSTOM.FX_REVAL ADD (
  CONSTRAINT PKEY12
 PRIMARY KEY
 (CURRENCY_CODE, BANK_ID)
    USING INDEX 
);

CREATE UNIQUE INDEX CUSTOM.PKEY12 ON CUSTOM.FX_REVAL
(CURRENCY_CODE, BANK_ID);

GRANT SELECT ON CUSTOM.FX_REVAL TO ALLTAB;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.FX_REVAL TO TBAADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.FX_REVAL TO TBAGEN;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.FX_REVAL TO TBAUTIL;
