<%--
//Generated by Customization WB Generator
//Do not edit this file directly.
//Instead, modify the properties in the tool and regenerate.
--%>

<%@ page import="applcommon.ParseValue" %>
<%@ page import="com.infy.bbu.jsputil.*"%>
<%@ page import="java.util.Vector"%>
<%@ taglib uri="taglib.tld" prefix="arjsp" %>
<arjsp:init groupName="Customize" isEntryPoint="false" />

<%
	String sProfileId = ProfilesManager.getProfileInSession(session);
	String sSubGrpName = (String)ARJspCurr.getInput("subGroupName","");
	String sGrpName = ARJspCurr.getCurrentGroup();
	String pageName = (String)ARJspCurr.getInput("jspName","");
	String sPopUpExceptionWindow = (String)ARJspCurr.getInput(sGrpName+".PopUpExceptionWindow" ,"false");
	String sReferralMode = (String)ARJspCurr.getInput("refSubMode" ,"");
	ARJspCurr.setInput(sGrpName+".PopUpExceptionWindow","false");


	int iCurrentSetSize = Integer.parseInt((String)ARJspCurr.getInput(sSubGrpName+"_"+pageName+".setSize","0"));
	int iListMaxDisplay = Integer.parseInt((String)ARJspCurr.getInput(sSubGrpName+"_"+pageName+".MaxRecsPerPage","0"));
	int iCurrentPage = Integer.parseInt((String)ARJspCurr.getInput(sSubGrpName+"_"+pageName+".currentPage","0"));
	int startRecord = (iCurrentPage-1)*iListMaxDisplay;
	int iMaxPage=Integer.parseInt((String)ARJspCurr.getInput(sSubGrpName+"_"+pageName+".maxPage","0"));
	int dispNum = startRecord + iListMaxDisplay;
	int iCounter;
	Vector vctMRMField = new Vector();
	vctMRMField.add("rowNum");
	vctMRMField.add("glDate");
	vctMRMField.add("valueDate");
	vctMRMField.add("instrNo");
	vctMRMField.add("withdrawalAmt");
	vctMRMField.add("depositAmt");
	vctMRMField.add("balanceAmt");
	vctMRMField.add("narrative");
	ARJspCurr.setInput(sSubGrpName+"_"+pageName+".mrmFields", vctMRMField);
%>
<script>

	var sPopUpExceptionWindow = '<%=sPopUpExceptionWindow%>';
	var sReferralMode = '<%=sReferralMode%>' ;

	var subGroupName = '<%=ParseValue.checkString(ARJspCurr.getInput("subGroupName",""))%>';
	var funcCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".funcCode",""))%>';

	var accountID = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".accountID",""))%>';
	var ccySolID = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".ccySolID",""))%>';
	var acctName = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".acctName",""))%>';
var glSubhead = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".glSubhead",""))%>';
var balance = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".balance",""))%>';
var openingBal = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".openingBal",""))%>';
var closingBal = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".closingBal",""))%>';
var floatBal = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".floatBal",""))%>';
var fundsInClearing = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".fundsInClearing",""))%>';
var availAmt = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".availAmt",""))%>';
var effAvailAmt = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".effAvailAmt",""))%>';
var customerStat = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".customerStat",""))%>';
var acctOpenDate = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".acctOpenDate",""))%>';
var acctStatus = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".acctStatus",""))%>';
var acctStatusDate = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".acctStatusDate",""))%>';
var purgeDate = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".purgeDate",""))%>';
var address1 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".address1",""))%>';
var address2 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".address2",""))%>';
var address3 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".address3",""))%>';
var city = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".city",""))%>';
var state = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".state",""))%>';
var country = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".country",""))%>';
var postalCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".postalCode",""))%>';
var phoneType = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".phoneType",""))%>';
var telexNo = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".telexNo",""))%>';
var phoneNo = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".phoneNo",""))%>';
var emailType = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".emailType",""))%>';
var emailID = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".emailID",""))%>';

var fromDate = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".fromDate",""))%>';
var toDate = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".toDate",""))%>';
var fromAmt = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".fromAmt",""))%>';
var toAmt = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".toAmt",""))%>';
var fromInstrumentNo = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".fromInstrumentNo",""))%>';
var toInstrumentNo = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".toInstrumentNo",""))%>';
var orderBy = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".orderBy",""))%>';
var lastNTran = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".lastNTran",""))%>';


var rowNum = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".rowNum",""))%>';
var glDate = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".glDate",""))%>';
var valueDate = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".valueDate",""))%>';
var instrNo = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".instrNo",""))%>';
var withdrawalAmt = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".withdrawalAmt",""))%>';
var depositAmt = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".depositAmt",""))%>';
var balanceAmt = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".balanceAmt",""))%>';
var narrative = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".narrative",""))%>';

	var CurrentPage = '<%=iCurrentPage%>';
	var MaxPage = '<%=iMaxPage%>';
	var startRecord = <%=startRecord%>;
	var ListMaxDisplay = <%=iListMaxDisplay%>;
	var CurrentSetSize = '<%=iCurrentSetSize%>';

	var iListMaxDisplay='<%=iListMaxDisplay%>';
	var rowNum = new Array(iListMaxDisplay);
	var glDate = new Array(iListMaxDisplay);
	var valueDate = new Array(iListMaxDisplay);
	var instrNo = new Array(iListMaxDisplay);
	var withdrawalAmt = new Array(iListMaxDisplay);
	var depositAmt = new Array(iListMaxDisplay);
	var balanceAmt = new Array(iListMaxDisplay);
	var narrative = new Array(iListMaxDisplay);
</script>


<%
	for(int i=0;i<iListMaxDisplay;i++)
	{
		iCounter= startRecord + i;
	%>
	<script language="JavaScript">
	
		rowNum['<%=i%>']= '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+"_"+pageName+".rowNum_"+iCounter,""))%>';
		glDate['<%=i%>']= '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+"_"+pageName+".glDate_"+iCounter,""))%>';
		valueDate['<%=i%>']= '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+"_"+pageName+".valueDate_"+iCounter,""))%>';
		instrNo['<%=i%>']= '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+"_"+pageName+".instrNo_"+iCounter,""))%>';
		withdrawalAmt['<%=i%>']= '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+"_"+pageName+".withdrawalAmt_"+iCounter,""))%>';
		depositAmt['<%=i%>']= '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+"_"+pageName+".depositAmt_"+iCounter,""))%>';
		balanceAmt['<%=i%>']= '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+"_"+pageName+".balanceAmt_"+iCounter,""))%>';
		narrative['<%=i%>']= '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+"_"+pageName+".narrative_"+iCounter,""))%>';
	</script>
	<%
	}
%>

<script language="JavaScript">
	printBlock();
	printFooterBlock();
</script>

