<%--
//Generated by Customization WB Generator
//Do not edit this file directly.
//Instead, modify the properties in the tool and regenerate.
--%>

<%@ page import="applcommon.ParseValue" %>
<%@ page import="com.infy.bbu.jsputil.*"%>
<%@ page import="java.util.Vector"%>
<%@ page import="FABCommon.SecurityInfo70"%>
<%@ taglib uri="taglib.tld" prefix="arjsp" %>
<arjsp:init groupName="Customize" isEntryPoint="false" />

<%
	String sProfileId = ProfilesManager.getProfileInSession(session);
	String sSubGrpName = (String)ARJspCurr.getInput("subGroupName","");
	String sGrpName = ARJspCurr.getCurrentGroup();
	String pageName = (String)ARJspCurr.getInput("jspName","");
	String sPopUpExceptionWindow = (String)ARJspCurr.getInput(sGrpName+".PopUpExceptionWindow" ,"false");
	String sReferralMode = (String)ARJspCurr.getInput("refSubMode" ,"");
	ARJspCurr.setInput(sGrpName+".PopUpExceptionWindow","false");
	SecurityInfo70 securityInfo = (SecurityInfo70)session.getAttribute("FinUserInfo");

%>
<script>

	var sPopUpExceptionWindow = '<%=sPopUpExceptionWindow%>';
	var sReferralMode = '<%=sReferralMode%>' ;
	
	var crncyCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".crncyCode",""))%>';
	var solId = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".solId",""))%>';
	var acctName = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".acctName",""))%>';
	
	var subGroupName = '<%=ParseValue.checkString(ARJspCurr.getInput("subGroupName",""))%>';
	var BODDate= "<%=(securityInfo.bodDate).substring(0,10)%>";
	var acctID = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".acctID",""))%>';
	var fromDate = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".fromDate",""))%>';
	var toDate = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".toDate",""))%>';
	var fromAmt = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".fromAmt",""))%>';
	var toAmt = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".toAmt",""))%>';
	var fromInstrumentNo = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".fromInstrumentNo",""))%>';
	var toInstrumentNo = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".toInstrumentNo",""))%>';
	var orderBy = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".orderBy",""))%>';
	var lastNTran = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".lastNTran",""))%>';
	var targetEntity = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".targetEntity",""))%>';
	var targetEntityDesc = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".targetEntityDesc",""))%>';
</script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("cust_pre_evt.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("cust_post_evt.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("common_functions.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showAccountIdList.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/custom/javascripts/<%=VRPKeys.getCustomFile("custom_functions.js",sProfileId)%>"></script>


<script language="JavaScript">
	printBlock();
	printFooterBlock();
</script>

