SET DEFINE OFF;

Insert into CUSTOM.C_CPARAM_MASTER_TABLE
   (MODULE_NAME, PARAMETER_LEVEL, PARAMETER_ID, PARAMETER_DESC, PARAMETER_TYPE, QUERY_ID, LIST_TYPE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID)
 Values
   ('ISLM', 'BNKL', 'CONBACID', 'Conventional Contra Bacid', 'AN', ' ', 'FT', 'Y', 'N', 'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE, '11');
   
Insert into CUSTOM.C_CPARAM_MASTER_TABLE
   (MODULE_NAME, PARAMETER_LEVEL, PARAMETER_ID, PARAMETER_DESC, PARAMETER_TYPE, QUERY_ID, LIST_TYPE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID)
 Values
   ('ISLM', 'BNKL', 'ISLBACID', 'Islamic Contra Bacid', 'AN', ' ', 'FT', 'Y', 'N', 'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE, '11');

Insert into CUSTOM.C_CPARAM_MASTER_TABLE
   (MODULE_NAME, PARAMETER_LEVEL, PARAMETER_ID, PARAMETER_DESC, PARAMETER_TYPE, QUERY_ID, LIST_TYPE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID)
 Values
   ('ISLM', 'BNKL', 'ISLM_ERROR_01', 'Cursor opening error', 'AN', ' ', 'FT', 'Y', 'N', 'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE, '11');

Insert into CUSTOM.C_CPARAM_MASTER_TABLE
   (MODULE_NAME, PARAMETER_LEVEL, PARAMETER_ID, PARAMETER_DESC, PARAMETER_TYPE, QUERY_ID, LIST_TYPE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID)
 Values
   ('ISLM', 'BNKL', 'ISLM_ERROR_02', 'Fetching from GSH table failed', 'AN', ' ', 'FT', 'Y', 'N', 'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE, '11');

Insert into CUSTOM.C_CPARAM_MASTER_TABLE
   (MODULE_NAME, PARAMETER_LEVEL, PARAMETER_ID, PARAMETER_DESC, PARAMETER_TYPE, QUERY_ID, LIST_TYPE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID)
 Values
   ('ISLM', 'BNKL', 'ISLM_ERROR_03', 'Conventional Contra not setup', 'AN', ' ', 'FT', 'Y', 'N', 'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE, '11');

Insert into CUSTOM.C_CPARAM_MASTER_TABLE
   (MODULE_NAME, PARAMETER_LEVEL, PARAMETER_ID, PARAMETER_DESC, PARAMETER_TYPE, QUERY_ID, LIST_TYPE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID)
 Values
   ('ISLM', 'BNKL', 'ISLM_ERROR_04', 'Islamic Contra not setup', 'AN', ' ', 'FT', 'Y', 'N', 'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE, '11');

Insert into CUSTOM.C_CPARAM_MASTER_TABLE
   (MODULE_NAME, PARAMETER_LEVEL, PARAMETER_ID, PARAMETER_DESC, PARAMETER_TYPE, QUERY_ID, LIST_TYPE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID)
 Values
   ('ISLM', 'BNKL', 'ISLM_ERROR_05', 'Conventional GL not fetched', 'AN', ' ', 'FT', 'Y', 'N', 'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE, '11');


Insert into CUSTOM.C_CPARAM_MASTER_TABLE
   (MODULE_NAME, PARAMETER_LEVEL, PARAMETER_ID, PARAMETER_DESC, PARAMETER_TYPE, QUERY_ID, LIST_TYPE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID)
 Values
   ('ISLM', 'BNKL', 'ISLM_ERROR_06', 'Islamic GL not fetched', 'AN', ' ', 'FT', 'Y', 'N', 'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE, '11');


Insert into CUSTOM.C_CPARAM_MASTER_TABLE
   (MODULE_NAME, PARAMETER_LEVEL, PARAMETER_ID, PARAMETER_DESC, PARAMETER_TYPE, QUERY_ID, LIST_TYPE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID)
 Values
   ('ISLM', 'BNKL', 'ISLM_ERROR_07', 'Credit transaction amount not fetched', 'AN', ' ', 'FT', 'Y', 'N', 'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE, '11');


Insert into CUSTOM.C_CPARAM_MASTER_TABLE
   (MODULE_NAME, PARAMETER_LEVEL, PARAMETER_ID, PARAMETER_DESC, PARAMETER_TYPE, QUERY_ID, LIST_TYPE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID)
 Values
   ('ISLM', 'BNKL', 'ISLM_ERROR_08', 'Debit transaction amount not fetched', 'AN', ' ', 'FT', 'Y', 'N', 'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE, '11');


Insert into CUSTOM.C_CPARAM_MASTER_TABLE
   (MODULE_NAME, PARAMETER_LEVEL, PARAMETER_ID, PARAMETER_DESC, PARAMETER_TYPE, QUERY_ID, LIST_TYPE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID)
 Values
   ('ISLM', 'BNKL', 'ISLM_ERROR_09', 'Insertion to custom table failed', 'AN', ' ', 'FT', 'Y', 'N', 'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE, '11');
   
COMMIT;
