SET DEFINE OFF;
Insert into CUSTOM.C_CPARAM_VALUE_TABLE
   (PARAMETER_ID, PARAMETER_VALUE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID, MODULE_NAME)
 Values
   ('ACCTNUM', '0018000100096', 'Y', 'N', 'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE, '50', 'ERP');
Insert into CUSTOM.C_CPARAM_VALUE_TABLE
   (PARAMETER_ID, PARAMETER_VALUE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID, MODULE_NAME)
 Values
   ('COUNT', '9999', 'Y', 'N', 'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE, '50', 'ERP');
Insert into CUSTOM.C_CPARAM_VALUE_TABLE
   (PARAMETER_ID, PARAMETER_VALUE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID, MODULE_NAME)
 Values
   ('PARTICULAR', 'ERP TRAN ', 'Y', 'N', 'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE, '50', 'ERP');
Insert into CUSTOM.C_CPARAM_VALUE_TABLE
   (PARAMETER_ID, PARAMETER_VALUE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID, MODULE_NAME)
 Values
   ('RATECODE', 'NOR', 'Y', 'N', 'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE, '50', 'ERP');
Insert into CUSTOM.C_CPARAM_VALUE_TABLE
   (PARAMETER_ID, PARAMETER_VALUE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID, MODULE_NAME)
 Values
   ('TRAN_NAME', 'ERP TRAN ', 'Y', 'N', 'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE, '50', 'ERP');

COMMIT;
