
DROP SEQUENCE CUSTOM.CUST_IE_TXN_REF_NO_SEQ;

CREATE SEQUENCE CUSTOM.CUST_IE_TXN_REF_NO_SEQ
  START WITH 263256
  MAXVALUE 999999
  MINVALUE 1
  CYCLE
  NOCACHE
  NOORDER;

DROP SYNONYM CUSTOM.IE_TXN_REF_NO_SEQ;

CREATE SYNONYM CUSTOM.IE_TXN_REF_NO_SEQ FOR CUSTOM.CUST_IE_TXN_REF_NO_SEQ;

GRANT SELECT ON CUSTOM.CUST_IE_TXN_REF_NO_SEQ TO TBAGEN;


