DROP TABLE CUSTOM.C_LOCATION CASCADE CONSTRAINTS;

CREATE TABLE CUSTOM.C_LOCATION
(
  LOCATION_DESC  VARCHAR2(80 BYTE),
  LOCATION_CODE  VARCHAR2(8 BYTE),
  BANK_ID        VARCHAR2(8 BYTE)
);

CREATE INDEX CUSTOM.C_LOCATION ON CUSTOM.C_LOCATION
(LOCATION_DESC);

GRANT SELECT ON CUSTOM.C_LOCATION TO ALLTAB;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.C_LOCATION TO TBAADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.C_LOCATION TO TBAGEN;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.C_LOCATION TO TBAUTIL;
