DROP TABLE CUSTOM.CASHDX_CUSTOM CASCADE CONSTRAINTS;

CREATE TABLE CUSTOM.CASHDX_CUSTOM
(
  CUSTOMER_NAME       VARCHAR2(100 BYTE),
  ID_NUM              VARCHAR2(100 BYTE),
  PHONE_NUM           VARCHAR2(100 BYTE),
  SUPPORTING_DETAILS  VARCHAR2(100 BYTE),
  RCRE_TIME           DATE,
  BANK_ID             VARCHAR2(10 BYTE),
  SOL_ID              VARCHAR2(10 BYTE),
  USER_ID             VARCHAR2(100 BYTE),
  NATIONALITY         VARCHAR2(100 BYTE)
);

