DROP TABLE CUSTOM.FIN_DD_UPLOAD_TABLE CASCADE CONSTRAINTS;

CREATE TABLE CUSTOM.FIN_DD_UPLOAD_TABLE
(
  PROCESS_ID             NUMBER,
  BANK                   VARCHAR2(2 BYTE),
  BRANCHCODE             VARCHAR2(3 BYTE),
  PAYEENAME              VARCHAR2(80 BYTE),
  AMOUNT                 NUMBER(20,4),
  IND                    VARCHAR2(1 BYTE),
  CCY                    VARCHAR2(3 BYTE),
  DIVPAYABLESAC          VARCHAR2(16 BYTE),
  BANKERSCHEQAC          VARCHAR2(16 BYTE),
  REMARKS                VARCHAR2(40 BYTE),
  INSTTYPE               VARCHAR2(10 BYTE),
  INSTALPHA              VARCHAR2(10 BYTE),
  INSTNUMBER             VARCHAR2(10 BYTE),
  PROCESSED_FLAG         VARCHAR2(10 BYTE),
  FIN_TRAN_ID            VARCHAR2(10 BYTE),
  FIN_TRAN_DATE          DATE,
  FIN_PART_TRAN_SRLNUM   VARCHAR2(10 BYTE),
  FIN_PSTD_FLG           VARCHAR2(10 BYTE),
  STATUS                 VARCHAR2(100 BYTE),
  ORACLE_CHECK_STATUS    VARCHAR2(120 BYTE),
  CHECK_ID               NUMBER,
  CREATED_BY             NUMBER,
  CREATION_DATE          DATE,
  LAST_UPDATED_BY        NUMBER,
  LAST_UPDATE_DATE       DATE,
  TRANSACTION_INDICATOR  VARCHAR2(10 BYTE),
  BANK_ID                VARCHAR2(3 BYTE)
);



GRANT SELECT ON CUSTOM.FIN_DD_UPLOAD_TABLE TO ALLTAB;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.FIN_DD_UPLOAD_TABLE TO ERPGL;

GRANT INSERT, SELECT ON CUSTOM.FIN_DD_UPLOAD_TABLE TO FINREPORTS;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.FIN_DD_UPLOAD_TABLE TO TBAADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.FIN_DD_UPLOAD_TABLE TO TBAGEN;
