--====================================================================================================
-- Table Name: CHARGE_TRAN_DETAIL_TBL
-- Synonym Name : C_CTDT
-- Date: 19-OCT-2018
-- Description: This table is used for Capturing Charge Transactions Details for Transactions.
-- Author: Anshul_Singh04
-- Modification History :
--<Version No.> <Date> <Author Name> <Description>
--====================================================================================================

DROP TABLE CUSTOM.CHARGE_TRAN_DETAIL_TBL CASCADE CONSTRAINTS;

CREATE TABLE CUSTOM.CHARGE_TRAN_DETAIL_TBL
(
	PARENT_TRAN_ID			VARCHAR2(9 CHAR),
	PARENT_TRAN_DATE     	DATE,
	EVENT_TYPE			   	VARCHAR2(5 CHAR),
	EVENT_ID			   	VARCHAR2(25 CHAR),
	SERVICE_SOL_ID		  	VARCHAR2(8 CHAR),
	CHRG_TRAN_ID	  		VARCHAR2(9 CHAR),
	CHRG_TRAN_DATE     		DATE,
	COLL_CRNCY_CODE         VARCHAR2(3 CHAR),
	CHRG_AMT	   			NUMBER(20,4),
	VAT_AMT	   				NUMBER(20,4),
	RCRE_USER_ID       		VARCHAR2(15 CHAR),
	RCRE_TIME          		DATE,
	BANK_ID            		VARCHAR2(8 CHAR)
)
/* STORE_START */
INITRANS 64 STORAGE (FREELISTS 16) 
TABLESPACE CUSTOM_TBLS
/* STORE_END */
/
DROP INDEX CUSTOM.IDX_CHRG_TRAN_DTL;

CREATE UNIQUE INDEX CUSTOM.IDX_CHRG_TRAN_DTL ON CUSTOM.CHARGE_TRAN_DETAIL_TBL
(PARENT_TRAN_ID,PARENT_TRAN_DATE,BANK_ID);

DROP SYNONYM CUSTOM.C_CTDT;

CREATE SYNONYM CUSTOM.C_CTDT FOR CUSTOM.CHARGE_TRAN_DETAIL_TBL;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.CHARGE_TRAN_DETAIL_TBL TO TBAADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.CHARGE_TRAN_DETAIL_TBL TO TBAGEN;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.CHARGE_TRAN_DETAIL_TBL TO TBAUTIL;
COMMIT;