SET DEFINE OFF;
Insert into CUSTOM.C_CPMASTER
(BANK_ID,MODULE_NAME,PARAMETER_LEVEL,PARAMETER_ID,PARAMETER_DESC,PARAMETER_TYPE,QUERY_ID,LIST_TYPE,ENTITY_CRE_FLG,DEL_FLG,RCRE_USER_ID,RCRE_TIME,LCHG_USER_ID,LCHG_TIME)
values 
('43','SB','BNKL','DORMANCY_PERIOD_SB','DORMANCY PERIOD FOR CUSTOM AUTOCLOSURE BATCH','NI','','FT','Y','N','TBAADM',sysdate,'TBAADM',sysdate);
Insert into CUSTOM.C_CPMASTER
(BANK_ID,MODULE_NAME,PARAMETER_LEVEL,PARAMETER_ID,PARAMETER_DESC,PARAMETER_TYPE,QUERY_ID,LIST_TYPE,ENTITY_CRE_FLG,DEL_FLG,RCRE_USER_ID,RCRE_TIME,LCHG_USER_ID,LCHG_TIME)
values 
('43','CA','BNKL','DORMANCY_PERIOD_CA','DORMANCY PERIOD FOR CUSTOM AUTOCLOSURE BATCH','NI','','FT','Y','N','TBAADM',sysdate,'TBAADM',sysdate);
COMMIT;
