<%--
//Generated by Customization WB Generator
//Do not edit this file directly.
//Instead, modify the properties in the tool and regenerate.
--%>

<%@ page import="applcommon.ParseValue" %>
<%@ page import="com.infy.bbu.jsputil.*"%>
<%@ page import="FABCommon.SecurityInfo70"%>
<%@ taglib uri="taglib.tld" prefix="arjsp" %>
<arjsp:init groupName="Customize" isEntryPoint="false" />

<%
	String sProfileId = ProfilesManager.getProfileInSession(session);
	String sSubGrpName = (String)ARJspCurr.getInput("subGroupName","");
	String sGrpName = ARJspCurr.getCurrentGroup();
	String sPopUpExceptionWindow = (String)ARJspCurr.getInput(sGrpName+".PopUpExceptionWindow" ,"false");
	String sReferralMode = (String)ARJspCurr.getInput("refSubMode" ,"");
	ARJspCurr.setInput(sGrpName+".PopUpExceptionWindow","false");
	SecurityInfo70 securityInfo = (SecurityInfo70)session.getAttribute("FinUserInfo");
    String funcCode=request.getParameter("cfreval.funcCode")!=null ?request.getParameter("cfreval.funcCode"):"";
    String currCode=request.getParameter("cfreval.currCode")!=null ?request.getParameter("cfreval.currCode"):"";
%>


<script>

	var sPopUpExceptionWindow = '<%=sPopUpExceptionWindow%>';
	var sReferralMode = '<%=sReferralMode%>' ;

	var subGroupName = '<%=ParseValue.checkString(ARJspCurr.getInput("subGroupName",""))%>';
	var funcCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".funcCode",""))%>';
	var currCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".currCode",""))%>';
	var rateCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".rateCode",""))%>';
	var pnlAccnt = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".pnlAccnt",""))%>';
	var homeCyAccnt = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".homeCyAccnt",""))%>';
	var foreignCyAccnt = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".foreignCyAccnt",""))%>';

</script>
<script language="javascript" src="../Renderer/javascripts/custom_functions.js"></script>
<script language="javascript" src="../Renderer/javascripts/lists/showRefCode.js" > </script>
<script language="javascript" src="../Renderer/javascripts/lists/showAccountIdList.js" > </script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("cust_pre_evt.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("cust_evt.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/custom/javascripts/<%=VRPKeys.getCustomFile("common_functions.js",sProfileId)%>"></script>

<script language="JavaScript">
	printBlock();
	printFooterBlock();
</script>

