<%--
//Generated by Customization WB Generator
//Do not edit this file directly.
//Instead, modify the properties in the tool and regenerate.
--%>

<%@ page import="applcommon.ParseValue" %>
<%@ page import="com.infy.bbu.jsputil.*"%>
<%@ page import="java.util.Vector"%>
<%@ taglib uri="taglib.tld" prefix="arjsp" %>
<arjsp:init groupName="Customize" isEntryPoint="false" />

<%
	String sProfileId = ProfilesManager.getProfileInSession(session);
	String sSubGrpName = (String)ARJspCurr.getInput("subGroupName","");
	String sGrpName = ARJspCurr.getCurrentGroup();
	String pageName = (String)ARJspCurr.getInput("jspName","");
	String sPopUpExceptionWindow = (String)ARJspCurr.getInput(sGrpName+".PopUpExceptionWindow" ,"false");
	String sReferralMode = (String)ARJspCurr.getInput("refSubMode" ,"");
	ARJspCurr.setInput(sGrpName+".PopUpExceptionWindow","false");

	fabclasses.FinErrException fex= (fabclasses.FinErrException)ARJspCurr.getInput(sGrpName+".fex",null);
	com.infy.COTP.LinkList displayErrLL= null;
	if(fex != null) displayErrLL= fex.getErrLL();
	int iCount = 0;
	FABInquiry.Err errObj = null;
	String tempErrStr = "";
	String errFound = "0";
	if ( displayErrLL != null ) 
	{
	    	for(iCount = 0; iCount < displayErrLL.size() ; iCount++)
		{
       		errObj = (FABInquiry.Err)displayErrLL.elementAt(iCount);
			tempErrStr = errObj.errDesc;
			if(tempErrStr.equalsIgnoreCase("Could Not Get Response from Server"))
			{
				System.out.println("error found");
				errFound = "1";
			}
			else
			{
				System.out.println("error not found");
			}
    		}
	}


%>
<script>

	var sPopUpExceptionWindow = '<%=sPopUpExceptionWindow%>';
	var sReferralMode = '<%=sReferralMode%>' ;
	
	var subGroupName = '<%=ParseValue.checkString(ARJspCurr.getInput("subGroupName",""))%>';
	var contractId = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".contractId",""))%>';
	var accName = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".accName",""))%>';
	var accCCY = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".accCCY",""))%>';
	var maxAvailAmt = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".maxAvailAmt",""))%>';
	var contractPeriodMM = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".contractPeriodMM",""))%>';
	var availAmt = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".availAmt",""))%>';
	var availPeriodMM = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".availPeriodMM",""))%>';
	var chrgAmt = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".chrgAmt",""))%>';
	var netTodAmount = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".netTodAmount",""))%>';
	var remarks = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".remarks",""))%>';
	var funcCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".funcCode",""))%>';
	var accNum = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".accNum",""))%>';
	var availReqId = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".availReqId",""))%>';
	var expDate = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".expDate",""))%>';
	var totAvailedAmt = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".totAvailedAmt",""))%>';
	var errStr = '<%=errFound%>' ;
</script>

<script language="JavaScript">
	printBlock();
	printFooterBlock();
</script>
