<!---------------------------------------------------------------------------------------------------------------->
<!--Name                : ctoda_det1_ginc.jsp 
<!--Description         : This is the criteria page ginc file for ctoda menu
<!--Date                : 04-07-2013
<!--Author              :  
<!--Called By           : None    
<!--Calling jsp         : None
<!--Menu Option         : ctoda
<!--Modification History:
<!--	Version No.	      	Date		         Author		Description
<!--	-------        		----------        	-----------	------------------
<!--	 0.1					26.08.2013			Kalvin		created for TO 361667									
<!--	 				
<!---------------------------------------------------------------------------------------------------------------->
<%--
//Generated by Customization WB Generator
//Do not edit this file directly.
//Instead, modify the properties in the tool and regenerate.
--%>
<%@ page import="finbranchUtil.*" %>
<%@ page import="applcommon.ParseValue" %>
<%@ page import="com.infy.bbu.jsputil.*"%>
<%@ page import="FABCommon.SecurityInfo70"%>
<%@ page import="java.util.Vector"%>
<%@ taglib uri="taglib.tld" prefix="arjsp" %>
<arjsp:init groupName="Customize" isEntryPoint="false" />

<%
	String sProfileId = ProfilesManager.getProfileInSession(session);
	String sSubGrpName = (String)ARJspCurr.getInput("subGroupName","");
	String sGrpName = ARJspCurr.getCurrentGroup();
	String pageName = (String)ARJspCurr.getInput("jspName","");
	String sPopUpExceptionWindow = (String)ARJspCurr.getInput(sGrpName+".PopUpExceptionWindow" ,"false");
	String sReferralMode = (String)ARJspCurr.getInput("refSubMode" ,"");
	ARJspCurr.setInput(sGrpName+".PopUpExceptionWindow","false");


	int iCurrentSetSize = Integer.parseInt((String)ARJspCurr.getInput(sSubGrpName+".setSize","0"));
	int iListMaxDisplay = Integer.parseInt((String)ARJspCurr.getInput(sSubGrpName+".MaxRecsPerPage","0"));
	int iCurrentPage = Integer.parseInt((String)ARJspCurr.getInput(sSubGrpName+".currentPage","1"));
	int startRecord = (iCurrentPage-1)*iListMaxDisplay;
	int iMaxPage=Integer.parseInt((String)ARJspCurr.getInput(sSubGrpName+".maxPage","0"));
	int dispNum = startRecord + iListMaxDisplay;
	int iCounter;

	Vector vctMRMField = new Vector();

	vctMRMField.add("rowNum");
	vctMRMField.add("reqId");
	vctMRMField.add("limId");
	vctMRMField.add("acctNo");
	vctMRMField.add("acctName");
	vctMRMField.add("amount");
	vctMRMField.add("status");
	vctMRMField.add("remrks");
	vctMRMField.add("grntDate");
	vctMRMField.add("expDate");
	ARJspCurr.setInput(sSubGrpName+"_"+pageName+".mrmFields", vctMRMField);
%>

<script>

	var sPopUpExceptionWindow = '<%=sPopUpExceptionWindow%>';
	var sReferralMode = '<%=sReferralMode%>' ;

	var subGroupName = '<%=ParseValue.checkString(ARJspCurr.getInput("subGroupName",""))%>';
	var funcCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".funcCode",""))%>';

	var accNo = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".accNo",""))%>';
	var acctname = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".acctname",""))%>';
	var clrBal = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".clrBal",""))%>';
	var custid = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".custid",""))%>';
	var acctOpnDate = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".acctOpnDate",""))%>';
	var lastTranDate = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".lastTranDate",""))%>';
	var schmType = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".schmType",""))%>';

	var rowNum = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".rowNum",""))%>';
	var reqId = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".reqId",""))%>';
	var limId = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".limId",""))%>';
	var acctNum = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".acctNo",""))%>';
	var acctName = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".acctName",""))%>';
	var amount = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".amount",""))%>';
	var status = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".status",""))%>';
	var remrks = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".remrks",""))%>';
	var grntDate = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".grntDate",""))%>';
	var expDate = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".apprvdPrd",""))%>';
	
	var CurrentPage = '<%=iCurrentPage%>';
	var MaxPage = '<%=iMaxPage%>';
	var startRecord = '<%=startRecord%>';
	var ListMaxDisplay = '<%=iListMaxDisplay%>';
	var CurrentSetSize = '<%=iCurrentSetSize%>';

	var iListMaxDisplay='<%=iListMaxDisplay%>';
	var rowNum = new Array(iListMaxDisplay);
	var reqId = new Array(iListMaxDisplay);
	var limId = new Array(iListMaxDisplay);
	var acctNum = new Array(iListMaxDisplay);
	var acctName = new Array(iListMaxDisplay);
	var amount = new Array(iListMaxDisplay);
	var status = new Array(iListMaxDisplay);
	var remrks = new Array(iListMaxDisplay);
	var grntDate = new Array(iListMaxDisplay);
	var expDate = new Array(iListMaxDisplay);
	//alert("iListMaxDisplay="+iListMaxDisplay);

	</script>


<%
	for(int i=0;i<iListMaxDisplay;i++)
	{
		iCounter= startRecord + i;
		System.out.println(iCounter);
	%>
	<script language="JavaScript">
		//alert("hmm" + '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".reqId_"+iCounter,""))%>');
		//rowNum['<%=i%>']= '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".rowNum_"+iCounter,""))%>';
		reqId['<%=i%>']= '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".reqId_"+iCounter,""))%>';
		limId['<%=i%>']= '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".limId_"+iCounter,""))%>';
		acctNum['<%=i%>']= '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".acctNum_"+iCounter,""))%>';
		acctName['<%=i%>']= '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".acctName_"+iCounter,""))%>';
		amount['<%=i%>']= '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".amount_"+iCounter,""))%>';
		status['<%=i%>']= '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".status_"+iCounter,""))%>';
		remrks['<%=i%>']= '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".remrks_"+iCounter,""))%>';
		grntDate['<%=i%>']= '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".grntDate_"+iCounter,""))%>';
		expDate['<%=i%>']= '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".expDate_"+iCounter,""))%>';
		
		

	</script>
	<%
	}
%>

<script language="javascript" src="../Renderer/custom/javascripts/<%=VRPKeys.getFile("custom_functions.js",sProfileId)%>"></script>
<script language="JavaScript">
	printBlock();
	printFooterBlock();
</script>


