version: '3.9'
services:
  papss-middleware-db:
    image: postgres:15
    container_name: papss_middleware_db
    environment:
      POSTGRES_USER: papss
      POSTGRES_PASSWORD: fg4rHwc7kkPQcqXv
      POSTGRES_DB: papssdb
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - papss-network
  papss-middleware:
    image: ghcr.io/papssafrica/papss-middleware-service:main
    container_name: papss-middleware
    restart: always
    volumes:
      - /Users/test/Documents/papss/papss-middleware-service/src/main/resources/keystore:/var/papss/certs
      - /Users/test/Documents/projects/papss/papss-middleware-service/src/main/resources/application-sudo.yml:/app/config/application.yml
    environment:
      - SPRING_CONFIG_LOCATION=/app/config/application.yml
    ports:
      - "8080:8080"
    networks:
      - papss-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "yourStrong(!)Password"
    volumes:
      - sqlserver_data:/var/opt/mssql
    command: >
      bash -c "
        /opt/mssql/bin/sqlservr &
        sleep 20 &&
        /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'yourStrong(!)Password' -Q \"IF DB_ID('papssdb') IS NULL CREATE DATABASE papssdb;\" &&
        tail -f /dev/null
      "
    restart: unless-stopped
volumes:
  pg_data:
  sqlserver_data:

networks:
  papss-network:
    driver: bridge
