CREATE SEQUENCE CUSTOM.CHQBOOKREQ_SEQ_55
  START WITH 1000
  MAXVALUE 99999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


GRANT SELECT ON CUSTOM.CHQBOOKREQ_SEQ_55 TO TBAADM;

GRANT SELECT ON CUSTOM.CHQBOOKREQ_SEQ_55 TO TBAGEN;

GRANT SELECT ON CUSTOM.CHQBOOKREQ_SEQ_55 TO TBAUTIL;

CREATE SEQUENCE CUSTOM.CHQBOOKREQ_SEQ_54
  START WITH 100054
  MAXVALUE 99999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


GRANT SELECT ON CUSTOM.CHQBOOKREQ_SEQ_54 TO TBAADM;

GRANT SELECT ON CUSTOM.CHQBOOKREQ_SEQ_54 TO TBAGEN;

GRANT SELECT ON CUSTOM.CHQBOOKREQ_SEQ_54 TO TBAUTIL;


CREATE SEQUENCE CUSTOM.CHQBOOKREQ_SEQ_56
  START WITH 10000
  MAXVALUE 99999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


GRANT SELECT ON CUSTOM.CHQBOOKREQ_SEQ_56 TO TBAADM;

GRANT SELECT ON CUSTOM.CHQBOOKREQ_SEQ_56 TO TBAGEN;

GRANT SELECT ON CUSTOM.CHQBOOKREQ_SEQ_56 TO TBAUTIL;


CREATE SEQUENCE CUSTOM.CHQBOOKREQ_SEQ_50
  START WITH 10000
  MAXVALUE 99999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


GRANT SELECT ON CUSTOM.CHQBOOKREQ_SEQ_50 TO TBAADM;

GRANT SELECT ON CUSTOM.CHQBOOKREQ_SEQ_50 TO TBAGEN;

GRANT SELECT ON CUSTOM.CHQBOOKREQ_SEQ_50 TO TBAUTIL;


CREATE SEQUENCE CUSTOM.CHQBOOKREQ_SEQ_11
  START WITH 182442
  MAXVALUE 99999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


GRANT SELECT ON CUSTOM.CHQBOOKREQ_SEQ_11 TO TBAADM;

GRANT SELECT ON CUSTOM.CHQBOOKREQ_SEQ_11 TO TBAGEN;

GRANT SELECT ON CUSTOM.CHQBOOKREQ_SEQ_11 TO TBAUTIL;

