CREATE TABLE CUSTOM.CATOD_SANCTION_HIST_TABLE
(
  REQUEST_ID      VARCHAR2(16 BYTE),
  ACCT_NUM        VARCHAR2(16 BYTE),
  ACCT_NAME       VARCHAR2(80 BYTE),
  CARD_NUM        VARCHAR2(19 BYTE),
  CUST_ID         VARCHAR2(9 BYTE),
  SCHM_TYPE       VARCHAR2(5 BYTE),
  REQ_AMT         NUMBER(10,2),
  REQ_PERIOD      NUMBER(2),
  SOL_ID          VARCHAR2(8 BYTE),
  REQ_TYPE        CHAR(1 BYTE)                  DEFAULT 'F',
  STATUS_FLG      CHAR(1 BYTE)                  DEFAULT 'P',
  REMARKS         VARCHAR2(30 BYTE),
  CREATED_BY      VARCHAR2(15 BYTE),
  CREATED_DATE    DATE,
  MODIFIED_BY     VARCHAR2(15 BYTE),
  MODIFIED_DATE   DATE,
  VERIFY_BY       VARCHAR2(15 BYTE),
  VERIFY_DATE     DATE,
  SANCT_DATE      DATE,
  SANCT_PERIOD    NUMBER(2),
  EXPIRY_DATE     DATE,
  SANCT_AMT       NUMBER(10,2),
  RCRE_USER       VARCHAR2(15 BYTE),
  RCRE_DATE       DATE,
  LCHG_USER       VARCHAR2(15 BYTE),
  LCHG_DATE       DATE,
  E_TYPE          CHAR(2 BYTE),
  EXT_REQ         NUMBER(2),
  EXT_APP         NUMBER(2),
  ENC_REQ         NUMBER(10,2),
  ENC_APP         NUMBER(10,2),
  MSG_IND         CHAR(1 BYTE)                  DEFAULT 'B',
  EMAIL_FLG       CHAR(1 BYTE)                  DEFAULT 'N',
  SMS_FLG         CHAR(1 BYTE)                  DEFAULT 'N',
  IS_DELETED      CHAR(1 BYTE)                  DEFAULT 'N',
  ADM_FEES        CHAR(1 BYTE)                  DEFAULT 'N',
  CLS_FLG         CHAR(1 BYTE)                  DEFAULT 'N',
  BANK_ID         VARCHAR2(10 BYTE),
  ENTITY_CRE_FLG  CHAR(1 BYTE),
  DEL_FLG         CHAR(1 BYTE),
  FEE             NUMBER,
  FEE_TRAN_ID     VARCHAR2(8 BYTE)
);


CREATE SYNONYM CUSTOM.CATOD_SANCTION_HIST_TABLE_SYN FOR CUSTOM.CATOD_SANCTION_HIST_TABLE;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON CUSTOM.CATOD_SANCTION_HIST_TABLE TO TBAADM;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON CUSTOM.CATOD_SANCTION_HIST_TABLE TO TBAGEN;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON CUSTOM.CATOD_SANCTION_HIST_TABLE TO TBAUTIL;



