DROP SEQUENCE CUSTOM.WAY4CCARDPAYMENTS;

CREATE SEQUENCE CUSTOM.WAY4CCARDPAYMENTS
  START WITH 203
  MAXVALUE 9999999
  MINVALUE 1
  CYCLE
  NOCACHE
  ORDER;

  
GRANT SELECT ON CUSTOM.WAY4CCARDPAYMENTS TO TBAADM;

GRANT SELECT ON CUSTOM.WAY4CCARDPAYMENTS TO TBAGEN;
