CREATE SEQUENCE CUSTOM.CATODSCORE_SEQ_54
  START WITH 258
  MAXVALUE 99999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


GRANT SELECT ON CUSTOM.CATODSCORE_SEQ_54 TO CRMBATCHUSER;

GRANT SELECT ON CUSTOM.CATODSCORE_SEQ_54 TO CRMUSER;

GRANT SELECT ON CUSTOM.CATODSCORE_SEQ_54 TO DEDUPADM;

GRANT SELECT ON CUSTOM.CATODSCORE_SEQ_54 TO TBAGEN;

GRANT SELECT ON CUSTOM.CATODSCORE_SEQ_54 TO TBAADM;

GRANT SELECT ON CUSTOM.CATODSCORE_SEQ_54 TO TBAUTIL;

GRANT SELECT ON CUSTOM.CATODSCORE_SEQ_54 TO CUSTOM;


