CREATE TABLE CUSTOM.C_ICBM
(
  REQ_ID           VARCHAR2(9 BYTE),
  FORACID          VARCHAR2(16 BYTE),
  BRANCH_ID        VARCHAR2(8 BYTE),
  BEGIN_CHQ_NUM    VARCHAR2(8 BYTE),
  NUM_OF_CHB       NUMBER(4),
  NUM_OF_CHQ_LVS   NUMBER(4),
  AUTH_USER_ID     VARCHAR2(15 BYTE),
  REQ_STATUS       CHAR(1 BYTE),
  REQ_DATE         DATE,
  DOWNLOAD_ID      VARCHAR2(15 BYTE),
  DOWNLOAD_DATE    DATE,
  LCHG_USER_ID     VARCHAR2(15 BYTE),
  LCHG_TIME        DATE,
  RCRE_USER_ID     VARCHAR2(15 BYTE),
  RCRE_TIME        DATE,
  DEL_FLG          CHAR(1 BYTE),
  BANK_ID          VARCHAR2(3 BYTE),
  BEGIN_CHQ_ALPHA  VARCHAR2(10 BYTE),
  INST_TYPE        VARCHAR2(10 BYTE)
);


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON CUSTOM.C_ICBM TO TBAADM;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON CUSTOM.C_ICBM TO TBAGEN;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON CUSTOM.C_ICBM TO TBAUTIL;
