#!/bin/bash

# Export the Jasypt secret key as an environment variable
export CD_SPRING_DATASOURCE_URL="#{CD-SPRING-DATASOURCE-URL}#"
export CD_SPRING_DATASOURCE_USERNAME="#{CD-SPRING-DATASOURCE-USERNAME}#"
export CD_SPRING_DATASOURCE_PASSWORD="#{CD-SPRING-DATASOURCE-PASSWORD}#"

export CD_AFRICELL_B2C_REGISTRATION_CONSUMERKEY="#{CD-AFRICELL-B2C-REGISTRATION-CONSUMERKEY}#"
export CD_AFRICELL_B2C_REGISTRATION_CONSUMERSECRET="#{CD-AFRICELL-B2C-REGISTRATION-CONSUMERSECRET}#"
export CD_AFRICELL_B2C_CONSUMERKEY="#{CD-AFRICELL-B2C-CONSUMERKEY}#"
export CD_AFRICELL_B2C_CONSUMERSECRET="#{CD-AFRICELL-B2C-CONSUMERSECRET}#"
export CD_AFRICELL_B2C_DISBURSEMENT_URL="http://10.59.1.140:8280/BankInitBankToSVA/1.0"
export CD_AFRICELL_B2C_TOKEN_URL="https://10.59.1.140:8280/token"
export CD_AFRICELL_B2C_REGISTRATION_URL="http://10.59.1.140:8280/BankRegX/1.0"
export CD_AFRICELL_B2C_REGISTRATION_TOKEN_URL="http://10.59.1.140:8280/token"

export CD_AFRICELL_AIRTIME_USERID="#{CD-AFRICELL-AIRTIME-USERID}#"
export CD_AFRICELL_AIRTIME_USERNAME="#{CD-AFRICELL-AIRTIME-USERNAME}#"
export CD_AFRICELL_AIRTIME_PASSWORD="#{CD-AFRICELL-AIRTIME-PASSWORD}#"
export CD_AFRICELL_AIRTIME_BANKID="#{CD-AFRICELL-AIRTIME-BANKID}#"
export CD_AFRICELL_AIRTIME_URL="http://localhost:8087/BundlesService.asmx/SubscriberCreditTransfer"

# Print a confirmation message
echo "Environment variables have been set."