//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT004977:" (Aller)",FLT033359:"Custom Account Mapping Inquiry Menu",FLT033445:"Function :",FLT033360:"Select RIB/Account No. :",FLT033361:" Enter  RIB/Account No. :",FLT004977:" (Aller)",FLT001439:"Effacer",FLT012129:"Demande"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY 
var jspErr={};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);
