//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT026332:" Code de réception ",FLT026333:" ID du sol",FLT026334:"Test?(Y/N)",FLT026335:"Remarques",FLT026341:"Sélectionner",FLT026342:"P-Processus "};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);
