//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT11000228:"Numéro de compte",FLT11000028:"Non du chéquier ",FLT019668:"Numéro de début du série cheque ",FLT11000029:"Numéro de la fin du série cheque ",FLT11000129:"Demande de la  situation ( statut, Etat)"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);
