//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT000204:"Fonction",FLT11000028:"Numéro de compte",FLT11000027:"Demande de  l’ Identifiant"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);
