//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT004977:" (Aller)",FLT032040:"Cheque Upload Menu",FLT006657:"Fonction",FLT007695:"Request No:",FLT000193:"Télécharger ",FLT000194:"Valider",FLT001721:"Effacer",FLT032041:"U-UPLOAD",FLT032042:"D-DOWNLOAD",FLT026526:" OK"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY 
var jspErr={};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);

