//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT004977:" (Aller)",FLT032043:"Cheque Book Charge Maintainance",FLT006657:"Fonction",FLT032046:" Nom du module",FLT001602:"Event ID",FLT001456:"Event Type",FLT012932:"Code du système  (combinaison) ",FLT032119:" Code de la  devise",FLT000193:"Envoyer  (soumettre) ",FLT000194:"Valider",FLT001721:"Annuler /Effacer ",FLT026526:" OK"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY 
var jspErr={};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);

