//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT026332:" Code de réception ",FLT026333:"Numéro de compte",FLT026334:"État actuel",FLT026335:"Nouveau statut/Nouvelle situation",FLT026341:"Sélectionner--",FLT026342:"A-Activer",FLT026343:"V-Vérifier ",FLT026344:"X-Annuler"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

