//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={
             FLT026332:"Numéro de compte",
			 FLT026336:" de telle  période",
			 FLT026337:"à l’autre  période",
			 FLT001824:": Imprimer les détails lorsquaucune transaction",
			 FLT002784 :"Imprimer"
           };
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);
