//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT004977:" (Aller)",FLT031826:"Negotiation Margin Maintanence at Role Level",FLT006657:"Fonction",FLT031833:" rôle de ID",FLT031834:"Transfer Margin Amount",FLT000193:"Envoyer  (soumettre) ",FLT000194:"Valider",FLT001721:"Annuler /Effacer ",FLT026526:" OK"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY 
var jspErr={};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);
