//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT004977:" (Aller)",FLT031701:" TRAME (TABLEAU)  DE MAITENANCE DES COMMERÇANTS",FLT006657:"Fonction",FLT031732:" NOM DES COMMERCANTS ",FLT031733:"ID TERMINAL / POS",FLT031734:"ACHAT  PAYABLE A / C",FLT031735:" CASHBACK  PAYABLE  A / C (remboursement payable)",FLT031736:" CASHBACK  COMMANDE   A / C  (Commande du remboursment)",FLT031737:"COMPTE DE REGLEMENT s",FLT031738:"CASHBACK COMM(%)",FLT031739:"PURCHASE COMM(%)",FLT031740:"ID DU CANAL (CHAINE)",FLT031741:"CONFIRM(Y/N)",FLT000193:"Envoyer  (soumettre) ",FLT000194:"Valider",FLT001721:"Annuler /Effacer ",FLT026526:" OK"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY 
var jspErr={};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);
