//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT004977:" (Aller)",FLT648046:"Penalty Charge Maintenance",FLT006657:"Fonction",FLT030172:"Account ID",FLT004977:" (Aller)",FLT001439:"Effacer",FLT648047:"Sélectionner--",FLT648032:"  I- S’informer/ Enquêter  ",FLT648048:"W-Waiving"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY 
var jspErr={};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);
