//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT026332:"Fonction",FLT026344:"SELECTIONNER",FLT026333:"ID de L’employé",FLT026334:"Nom du fichier",FLT026335:"le nom mal assorti ",FLT026336:"Dr.A/c.ID",FLT026337:"Type de téléchargent ",FLT026338:"Rétention  de place ",FLT026339:"Mode de test",FLT026340:"Renommé le dossier ",FLT026341:"Code de la facturation",FLT026342:"Procédure ",FLT026343:"Télécharger "};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);
