//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT004977:" (Aller)",FLT031700:" Partage de la vente",FLT006657:"Fonction",FLT031589:"Id Sol",FLT031590:" numéro didentification / numéro didentification numérique",FLT031587:" Nom du client",FLT031596:" ID de la commande",FLT025922:" Date de la commande",FLT004977:" (Aller)",FLT001439:"Effacer",FLT031317:"Sélectionner--",FLT031309:"A-Ajouter",FLT031318:"M-Modifier",FLT031323:"  I- S’informer/ Enquêter  ",FLT031340:"V-Vérifier ",FLT031341:" Annuler"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY 
var jspErr={};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);
