//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT0320451:"Numéro d’ Identification",FLT004977:" (Aller)",FLT031839:"Partage de page d’achat ",FLT006657:"Fonction",FLT031347:"Type de transaction ",FLT032045:"Numéro  CDSC",FLT031841:"Numéro d’ordre ",FLT031846:"Numéro de compte",FLT004977:" (Aller)",FLT001439:"Effacer",FLT031507:"Sélectionner--",FLT031836:"A—Ajouter ",FLT03183661:"H—retenir ",FLT031837:"I—Enquêter/Demander",FLT031838:" V - Verifier",FLT031844:"Transfer-",FLT031845:"(Espèce, devise, monnaie)--",FLT03184611:"ID de la transaction"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY 
var jspErr={};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);
