//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT004977:" (Aller)",FLT031590:" Disponibilité manuelle de TOD",FLT112254:"Fonction",FLT112259:" Identification du compte ( ID du compte)",FLT031592:" ID de demande de disponibilité",FLT004977:" (Aller)",FLT001439:"Effacer",FLT700022:"Sélectionner--",FLT031595:" A - Ajouter",FLT034011:" I – Demander/s’informer ",FLT031596:"M - Modifier",FLT031297:" V - Vérifier",FLT033219:" X - Annuler"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY
var jspErr={FAT000924:"Enter a value in the field."};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);
