//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT004977:" (Aller)",FLT648026:"Cheque Certification Status",FLT006657:"Fonction",FLT648034:"Numéro de compte",FLT648035:"Cheque Number",FLT002671:"Statut",FLT648036:"Cheque Amount",FLT648037:"Paid Amount",FLT000193:"Envoyer  (soumettre) ",FLT000194:"Valider",FLT001721:"Annuler /Effacer ",FLT648038:"Y-Certified Cheque",FLT648039:"Z-Certified Cheque released",FLT648040:"P-Paid",FLT026526:" OK"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY 
var jspErr={};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);
