//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT004977:" (Aller)",FLT648026:"Cheque Certification Status",FLT006657:"Fonction",FLT648034:"Numéro de compte",FLT648035:"Cheque Number",FLT004977:" (Aller)",FLT001439:"Effacer",FLT648027:"SELECTIONNER",FLT648028:"A-Add Certified Cheque",FLT648029:"R-Release Certified Cheque",FLT648030:"M-Pay Certified Cheque",FLT648031:"V-Vérifier ",FLT648032:"  I- S’informer/ Enquêter  ",FLT648033:"X-Annuler"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY 
var jspErr={};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);
