//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT000003:"Numéro de compte",FLT000004:"Fonction",FLT000005:"SELECTIONNER--",FLT000009: "M - Modifier",FLT000010:" I – Demander/s’informer ",FLT000011: " Type dinstallation ",FLT000012: " numéro dinstallation "};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);
