//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT028900:" Transaction d’échange en espèces",FLT030311:" De telle  monnaie",FLT030541:" A   telle   Monnaie",FLT030647:" Montant reçu",FLT030726:" montant en devise",FLT030897:" montant en devise",FLT031293:" Code tarif / tarif",FLT031294:" Identifiant de lévénement de facturation",FHP000241:"Montant facturé",FLT031295:" Numéro de référence du Trésor ( de la trésorerie)"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY 
var jspErr={};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);
