//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT014433:" Identité (ID)   du revendeur",FLT015533:" Devise",FLT1024473:" Sol Set Id ( identité de l’installation du solde) ",FLS1000009:"FLS1000009: Rapport de position"};

var jspErr={CTRF100003:"Field must be Entered"};
