//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY
var jspRes={FLT000885:" (Aller)",FLT000572:" Rapport dintérêt client",FLT111600:" Type",FLT111601:" Critères 1",FLT111602:" Critère 2",FLT111603:" Espace réservé du compte",FLT111604:" Définir lID",FLT111605:" Devise",FLT111606:" date du début du  transfert",FLT111607:" Date de fin du transfert",FLT111608:" Numéro de compte GL",FLT111609:" ID Transfert ",FLT111610:" Date de transfert",FLT111611:" Pour définir lID",FLT000193:"Envoyer  (soumettre) ",FLT000194:"Valider",FLT000192:"Effacer",FLT001166:" OK"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY 
var jspErr={};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);
