//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT004977:" (Aller)",FLT021036:" Avis de frais dengagement de syndicat",FLT112254:"Fonction",FLT000637:"Date de la zone",FLT007523:"Code de la  zone",FLT009829:" Code Zone CCY",FLT031841:" Appel sortant",FLT003971:" A / c. Détails",FLT031846:" Cr. A / C No.",FLT031847:" Cr. Montant",FLT031848:" A / C   Aucun Texte 1",FLT031849:" A / C  Aucun  Texte 2",FLT000916:" Détails de linstrument  (mécanisme)",FLT031850:"Montant de linstrument",FLT021766:" Numéro  dinstrument",FLT007745:"Date de linstrument",FLT031851:" Numéro de compte payant",FLT007794:"Code bancaire",FLT031027:" Code de la transaction",FLT031835:" Numéro du série ",FLT031836:" ID du Transfert (transaction)",FLT031857:" Payant A / c. prénom",FLT009907:"Code delagence",FLT031850:"Montant de linstrument",FLT021766:" Numéro  dinstrument",FLT031858:" Image",FLT007745:"Date de linstrument",FLT031851:" Numéro de compte payant",FLT007794:"Code bancaire",FLT031027:" Code de la transaction",FLT031835:" Numéro du série ",FLT031836:" ID du Transfert (transaction)",FLT031857:" Payant A / c. prénom",FLT009907:"Code delagence",FLT000193:"Envoyer  (soumettre) ",FLT021284:"Valider",FLT027575:"Annuler /Effacer ",FLT026526:" OK"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY 
var jspErr={};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);
