CREATE TABLE CUSTOM.CUST_CHQ_BOOK_TABLE
(
  BEGIN_CHQ_NUM    VARCHAR2(8 BYTE),
  ACID             VARCHAR2(11 BYTE),
  FORACID          VARCHAR2(16 BYTE),
  BEGIN_CHQ_ALPHA  VARCHAR2(6 BYTE),
  INST_TYPE        VARCHAR2(5 BYTE),
  ENTITY_CRE_FLG   CHAR(1 BYTE),
  DEL_FLG          CHAR(1 BYTE),
  CHQ_ISSU_DATE    DATE,
  CHQ_NUM_OF_LVS   NUMBER(4),
  CHQ_LVS_STAT     VARCHAR2(100 BYTE),
  NUM_PAID         NUMBER(3),
  NUM_UNUSED       NUMBER(3),
  NUM_STOPED       NUMBER(3),
  NUM_CAUTIONED    NUMBER(3),
  NUM_DESTROYED    NUMBER(3),
  RCRE_USER_ID     VARCHAR2(15 BYTE),
  RCRE_TIME        DATE,
  LCHG_USER_ID     VARCHAR2(15 BYTE),
  LCHG_TIME        DATE,
  BANK_ID          VARCHAR2(8 BYTE)
);


CREATE INDEX CUSTOM.IDX_C_CBT_ACCT_ID ON CUSTOM.CUST_CHQ_BOOK_TABLE
(ACID, FORACID, INST_TYPE);


CREATE INDEX CUSTOM.IDX_C_CBT_CHQ_ISSU_DATE ON CUSTOM.CUST_CHQ_BOOK_TABLE
(CHQ_ISSU_DATE);


CREATE SYNONYM CUSTOM.C_CBT FOR CUSTOM.CUST_CHQ_BOOK_TABLE;


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON CUSTOM.CUST_CHQ_BOOK_TABLE TO TBAADM;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON CUSTOM.CUST_CHQ_BOOK_TABLE TO TBAGEN;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON CUSTOM.CUST_CHQ_BOOK_TABLE TO TBAUTIL;
