

CREATE TABLE CUSTOM.CREM
(
  CREM_SEQ              NUMBER(10),
  BWAY_SEQUENCENO       VARCHAR2(15 BYTE),
  REMIT_CCY             VARCHAR2(3 BYTE),
  REMIT_AMT             VARCHAR2(25 BYTE),
  OPER_ACCT             VARCHAR2(16 BYTE),
  OPER_CHRG_ACCT        VARCHAR2(16 BYTE),
  REM_CUST_ID           VARCHAR2(9 BYTE),
  REM_CUST_NAME         VARCHAR2(80 BYTE),
  REM_CUST_ADDR1        VARCHAR2(45 BYTE),
  REM_CUST_ADDR2        VARCHAR2(45 BYTE),
  REM_CUST_ADDR3        VARCHAR2(45 BYTE),
  REM_CUST_CNTRY_CODE   VARCHAR2(5 BYTE),
  BEN_PARTY_ID          VARCHAR2(9 BYTE),
  BEN_PARTY_NAME        VARCHAR2(80 BYTE),
  BEN_PARTY_ADDR1       VARCHAR2(45 BYTE),
  BEN_PARTY_ADDR2       VARCHAR2(45 BYTE),
  BEN_PARTY_ADDR3       VARCHAR2(45 BYTE),
  BEN_PARTY_CNTRY_CODE  VARCHAR2(5 BYTE),
  BEN_PARTY_ACID        VARCHAR2(16 BYTE),
  BENE_BK_BIC           VARCHAR2(12 BYTE),
  BENE_BK_CODE          VARCHAR2(6 BYTE),
  BENE_BR_CODE          VARCHAR2(6 BYTE),
  PAYEE_BK_BIC          VARCHAR2(12 BYTE),
  PAYEE_BK_CODE         VARCHAR2(6 BYTE),
  PAYEE_BR_CODE         VARCHAR2(6 BYTE),
  VALUE_DATE            DATE,
  PROCESS_FLG           CHAR(1 BYTE),
  LCHG_USER_ID          VARCHAR2(15 BYTE),
  LCHG_TIME             DATE,
  RCRE_USER_ID          VARCHAR2(15 BYTE),
  RCRE_TIME             DATE,
  FREE_TEXT_1           VARCHAR2(50 BYTE),
  FREE_TEXT_2           VARCHAR2(50 BYTE),
  FREE_TEXT_3           VARCHAR2(50 BYTE),
  BANK_ID               VARCHAR2(10 BYTE)
)
;


CREATE UNIQUE INDEX CUSTOM.CREM_SRLNO_UNIQ ON CUSTOM.CREM
(CREM_SEQ)
           ;

CREATE OR REPLACE SYNONYM CUSTOM.CREM1 FOR CUSTOM.CREM;


GRANT SELECT ON CUSTOM.CREM TO ALLTAB;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.CREM TO TBAADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.CREM TO TBAGEN;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.CREM TO TBAUTIL;

