DROP TABLE CUSTOM.CUST_CHQ_BOOK_MOD1_TABLE CASCADE CONSTRAINTS;

CREATE TABLE CUSTOM.CUST_CHQ_BOOK_MOD1_TABLE
(
  FORACID        VARCHAR2(16 BYTE),
  INST_TYPE      VARCHAR2(5 BYTE),
  BEGIN_CHQ_NUM  VARCHAR2(8 BYTE),
  OLD_STATUS     VARCHAR2(100 BYTE),
  NEW_STATUS     VARCHAR2(100 BYTE),
  DEL_FLG        CHAR(1 BYTE),
  RCRE_USER_ID   VARCHAR2(15 BYTE),
  RCRE_TIME      DATE,
  LCHG_USER_ID   VARCHAR2(15 BYTE),
  LCHG_TIME      DATE,
  BANK_ID        VARCHAR2(5 BYTE)
);



DROP SYNONYM CUSTOM.C_CBT_MOD1;

CREATE SYNONYM CUSTOM.C_CBT_MOD1 FOR CUSTOM.CUST_CHQ_BOOK_MOD1_TABLE;

GRANT SELECT ON CUSTOM.CUST_CHQ_BOOK_MOD1_TABLE TO ALLTAB;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.CUST_CHQ_BOOK_MOD1_TABLE TO TBAADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.CUST_CHQ_BOOK_MOD1_TABLE TO TBAGEN;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.CUST_CHQ_BOOK_MOD1_TABLE TO TBAUTIL;
