DROP TABLE CUSTOM.SECURITY CASCADE CONSTRAINTS;

CREATE TABLE CUSTOM.SECURITY
(
  SECURITY_DPA_      NUMBER(5)                  NOT NULL,
  SECURITY_EIT_      VARCHAR2(50 BYTE),
  SECURITYADDR       VARCHAR2(100 BYTE),
  SECURITYCODE       VARCHAR2(50 BYTE)          NOT NULL,
  SECURITYMKTPRICE   NUMBER(19,4)               NOT NULL,
  SECURITYNAME       VARCHAR2(100 BYTE)         NOT NULL,
  ORDERSECTYPE_DPA_  NUMBER(3)                  NOT NULL,
  IMMOBILISED        NUMBER(2)                  NOT NULL,
  SECTOR_DPA_        NUMBER(10),
  IMPORTCODE         VARCHAR2(50 BYTE),
  CLOSINGDATE        DATE,
  PRICE              NUMBER(19,4),
  OFFERINGS          NUMBER(2)                  NOT NULL,
  CANTRADE           NUMBER(2)                  NOT NULL,
  BANKACCOUNT_DPA_   NUMBER(10),
  ETSCODE            VARCHAR2(50 BYTE),
  IPOCODE            VARCHAR2(50 BYTE),
  IPOCLOSED          NUMBER(3)                  NOT NULL,
  IPOSMSCHARGE       FLOAT(126),
  STARTDATE          DATE,
  REQUIRESEXTRA      NUMBER(3),
  BATCHSIZE          NUMBER(3),
  DEFAULTSELECTION   NUMBER(3),
  RATIO              FLOAT(126),
  MINIMUMQUANTITY    NUMBER(5),
  STEPQUANTITY       NUMBER(5),
  OFFERINGTYPE       NUMBER(3),
  REQUIRESHOLDINGS   NUMBER(3),
  ISRIGHT            NUMBER(3)                  NOT NULL,
  PARENTSECURITY     NUMBER(5),
  SHOWING            NUMBER(3),
  ISCLOSED           NUMBER(3),
  REGISTRAR          VARCHAR2(50 BYTE),
  PARVALUE           FLOAT(126),
  AUDITORS           VARCHAR2(50 BYTE),
  FINANCIALYEND      VARCHAR2(50 BYTE),
  SHARESISSUED       FLOAT(126),
  DIRECTORS          VARCHAR2(100 BYTE),
  DELETED            VARCHAR2(10 BYTE),
  TRANSFERFEE        NUMBER(5),
  BANK_ID            VARCHAR2(8 BYTE)
);

GRANT SELECT ON CUSTOM.SECURITY TO ALLTAB;

GRANT SELECT ON CUSTOM.SECURITY TO TBAADM;

GRANT SELECT ON CUSTOM.SECURITY TO TBAGEN;
