set echo off 
set feedback off
set head off
set lines 3000
set verify off
set pages 0

SELECT 
	FORACID||'|'||SOL_ID||'|'||SCHM_TYPE||'|'||SCHM_CODE||'|'||BALANCE_AMOUNT||'|'||INT_RATE_DR||'|'||
	ACCRUED_UPTO_DATE_DR||'|'||TOT_ACCRUED_AMOUNT_DR||'|'||BOOKED_UPTO_DATE_DR||'|'||TOT_BOOKED_AMOUNT_DR||'|'||
	INT_CALC_UPTO_DATE_DR||'|'||LAST_BOOKED_TRAN_ID_DR||'|'||LAST_BOOKED_TRAN_DATE_DR||'|'||TOT_INT_AMOUNT_DR||'|'||
	TRAN_PARTICULAR_DR||'|'||INT_RATE_CR||'|'||ACCRUED_UPTO_DATE_CR||'|'||TOT_ACCRUED_AMOUNT_CR||'|'||
	BOOKED_UPTO_DATE_CR||'|'||TOT_BOOKED_AMOUNT_CR||'|'||INT_CALC_UPTO_DATE_CR||'|'||LAST_BOOKED_TRAN_ID_CR||'|'||
	LAST_BOOKED_TRAN_DATE_CR||'|'||TOT_INT_AMOUNT_CR||'|'||TRAN_PARTICULAR_CR||'|'||TOT_NRML_INT_SUSP_AMT||'|'||
	TOT_PENAL_INT_SUSP_AMT||'|'||INCOME_ACCT_BACID||'|'||EXPENSE_ACCT_BACID||'|'||
	INT_SUSP_ACCT||'|'||
	DPD_CNTR||'|'||PD_XFER_DATE||'|'||PD_FLG||'|'||MAIN_CLASSIFICATION_USER||'|'||
	SUB_CLASSIFICATION_USER||'|'||NRML_INCOME_ACCT_DIFF||'|'||PENAL_INCOME_ACCT_DIFF||'|'||
	NRML_SUSP_ACCT_DIFF||'|'||PENAL_SUSP_ACCT_DIFF||'|'||NRML_EXPENSE_ACCT_DIFF||'|'||
	BONUS_INT_TRAN_ID||'|'||BONUS_INT_UPTO_DATE||'|'||BONUS_INT_AMT||'|'||
	EXPENSE_ACCT_BACID||'|'||ACCT_CRNCY_CODE||'|'||INCOME_ACCT||'|'||EXPENSE_ACCT||'|'||
	INT_RECV_ACCT||'|'||INT_RECV_DIFF||'|'|| INT_PAY_ACCT||'|'||INT_PAY_DIFF
FROM  CUSTOM.C_GLIR_EOD_HIST
WHERE BANK_ID = '&1'
AND RECON_DATE = to_date('&2','dd-mm-yyyy')-1
/
