INSERT INTO FIMASTER.FIUSB_SERVICE_PROVIDER_TABLE ( FIUSB_SRV_PROV_ID, FIUSB_SRV_PROV_NAME,
FIUSB_SRV_PROV_DESC, HOST_INTERFACE_NODE_ID, HOST_INTERFACE_NODE_STATUS, FIUSB_SRV_PROV_LMU,
FIUSB_SRV_PROV_LMD, FIUSB_SRV_PROV_VER_NO, FIUSB_SRV_PROV_STATUS,
FIUSB_SRV_PROV_CLASS_NAME ) VALUES
(FIMASTER.FIUSB_SRV_PROV_ID_SEQ.nextval, 'srvProvSBAcctAddCustom', 'This Finacle Business Message allows an external channel or a client to request for opening a Saving.','1001', 'processed', 'SYSTEM'
,sysdate, 1, 'processed', 'com.infosys.ci.srvprov.FCORModuleBeanLookUpServiceProvider');

 commit;

INSERT INTO FIMASTER.FIUSB_SERVICE_REQUESTOR_TABLE ( FIUSB_SRV_REQ_ID, FIUSB_SRV_REQ_TYPE,
FIUSB_SRV_INVOC_MODE, FIUSB_SRV_REQ_LMU, FIUSB_SRV_REQ_LMD, FIUSB_SRV_REQ_VER_NO, FIUSB_SRV_REQ_STATUS,
FIUSB_SRV_REQ_TYPE_VERSION, FIUSB_SRV_REQ_NAME, FIUSB_SRV_REQ_DESC, FIUSB_NOT_SRV_REQ_ID,
FIUSB_NOT_SRV_REQ_STATUS, FIUSB_SRV_INTERACTION_TYPE) VALUES
( FIMASTER.FIUSB_SRV_REQ_ID_SEQ.NEXTVAL,'SBAcctAddCustom', 'SYNCHRONOUS', 'SYSTEM',  sysdate, 1, 'processed', '10.2','SBAcctAddCustom',
'SBAcctAddCustom', NULL, NULL, 'Invoker');

commit;

INSERT INTO FIMASTER.FIUSB_SERVICE_INTERFACE_TABLE ( FIUSB_SRV_INT_ID, FIUSB_SRV_PROV_ID,
FIUSB_REVERSAL_SRV_INT_ID, FIUSB_SRV_INT_LMU, FIUSB_SRV_INT_LMD, FIUSB_SRV_INT_VER_NO,
FIUSB_SRV_INT_STATUS, FIUSB_SRV_PROV_STATUS, FIUSB_SRV_INT_NAME, FIUSB_SRV_INT_DESC,
FIUSB_REVERSAL_SRV_INT_STATUS, FIUSB_REQ_MAPPER, FIUSB_RESP_MAPPER, FIUSB_SRV_INT_VERSION, FIUSB_MAPPER_STATUS,message_type,message_sub_type) VALUES
( FIMASTER.FIUSB_SRV_INTER_ID_SEQ.NEXTVAL, FIMASTER.FIUSB_SRV_PROV_ID_SEQ.CURRVAL, NULL, 'SYSTEM',sysdate, 1, 'processed', 'processed',
'srvIntSBAcctAddCustom','srvIntSBAcctAddCustom', NULL, NULL,NULL, '10.2', 'processed','XML','FIXML');

commit;

Insert into FIMASTER.FIUSB_SRV_REQ_MAPPING_TABLE
   (FIUSB_SRV_REQ_ID, FIUSB_SRV_INT_ID, FIUSB_SRV_REQ_STATUS, FIUSB_SRV_INT_STATUS, FIUSB_PROV_INVOC_MODE,
    FIUSB_PROV_TIMEOUT)
 Values
   (FIMASTER.FIUSB_SRV_REQ_ID_SEQ.currval, FIMASTER.FIUSB_SRV_INTER_ID_SEQ.currval, 'processed', 'processed', 'S',
    NULL);
    
 commit;
