
DROP TABLE CUSTOM.CLIA CASCADE CONSTRAINTS;

CREATE TABLE CUSTOM.CLIA
(
	Loan_Accnt		VARCHAR2(16 CHAR),
	Operative_Accnt	VARCHAR2(16 CHAR),
	Crncy_Code		VARCHAR2(5 CHAR),
	Adj_Amt			NUMBER(20,4),	
	Finacle_Int 	NUMBER(20,4),	
	Legacy_Int 		NUMBER(20,4),	
	Adj_Till_Date 	DATE,	
	Tran_Id 		VARCHAR2(9 CHAR),	
	Tran_date     	DATE,
	RCRE_TIME       DATE,
	RCRE_USER_ID    VARCHAR2(15 CHAR),	
	BANK_ID         VARCHAR2(8 CHAR)
);

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.CLIA TO TBAADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.CLIA TO TBAGEN;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.CLIA TO TBAUTIL;
COMMIT;