insert into CUSTOM.C_CPVALUE (PARAMETER_ID, LEVELCODE_1, LEVELCODE_2, PARAMETER_VALUE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID, MODULE_NAME) values ('DOC_EXP_VAL_EXCP', 'ALL', NULL, 'A5', 'Y', 'N', 'TBAADM', TO_DATE('2018-06-13 09:47:54', 'YYYY-MM-DD HH24:MI:SS'), 'TBAADM', TO_DATE('2018-06-13 09:47:54', 'YYYY-MM-DD HH24:MI:SS'), '43', 'OT'); 
commit;
