//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT031316:"Maintenance du  Contrat  Auto TOD",FAT000703:"Fonction",FLT031310:"Numéro de compte",FLT024006:"ID du Contrat",FLT031317:"Nom (intitulé) du compte",FLT031318:"Solde",FAT000934:"Code du système  (combinaison) ",FLT031323:"Montant minimum du contrat",FLT031324:"Montant maximal du contrat",FLT031340:"Période maximale du contrat",FLT031341:"Contrat CCY / montant",FLT031342:" Période du contrat",FTT000416:"les Charges",FAT001227:" Code de la  raison de résiliation "};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY 
var jspErr={};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);
