// GENERATED BY JSGEN. DO NOT MODIFY.
var applangcode="INFENG";
var jspRes={FLT000160:"Détails de la partie liée",FLT000450:"Nom",FLT000162:" Code de relation",FLT000163:"Code de désignation",FLT014293:"Ligne dadresse 1",FLT014294:"Ligne dadresse 2",FLT014295:"Ligne d’adresse 3",FLT000089:"Ville",FLT000090:"Etat",FLT000092:"Pays",FLT000091:" Code postal",FLT000496:"Numéro de téléphone 1",FLT000497:"Numéro de téléphone 2",FLT000166:" Numéro de fax",FLT000167:"Identification de le-mail",FLT004652:"Numéro didentification fiscale",FLT000536:"Supprimer.",FLT000144:"Aucun texte ",FLT000145:"Identifiant CIF      ",FLT000146:"Aucun Texte  2",FLT000147:"Aucun Texte  3",FLT000148:"Aucun Texte 4",FLT000193:"Envoyer  (soumettre) ",FLT000192:"Annuler /Effacer ",FLT001166:" OK",FLT000194:"Valider",FLT001439:"Effacer"};

var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);
