//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT026332:"DATE DU  DÉBUT",FLT026333:"DATE DE  LA  FIN", FLT026334:"COPIE",FLT026335:"ID  DU TÉLÉCHARGEMENT  "};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);
