//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT004977:"Aller",FLT033459:"Code de la Commission Maintenance pour LC / BG",FLT006657:"Fonction",FLT033469:"Code de la commission :",FLT033470:"Description de la Commission :",FLT033491:"Pourcentage de commission :",FLT033492:"Taux de TVA (%) :",FLT000193:"Soumettre",FLT000194:"Valider",FLT001721:"Annuler",FLT026526:"D'accord",FLT033493:"Commission minimale:"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY 
var jspErr={};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);
