//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT004977:"Aller",FLT031826:"Négociation Marge Entretien Has Rôle Niveau",FLT006657:"Fonction",FLT001088:"Rôle ID",FLT004203:"De Devise",FLT025288:"opération Type",FLT004977:"Aller",FLT001439:"Clair",FLT031698:"--Sélectionner--",FLT031827:"A - Ajouter",FLT031828:"M - Modifier",FLT031829:"V - Vérifier",FLT031830:"X - Annuler",FLT031831:"I - Renseigner",FLT031832:"D - Effacer",FLT017004:"T - Transfert",FLT034217:"C - En espèces"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY 
var jspErr={};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);
