//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT004977:"Aller",FLT648092:"Rajustement des intérêts sur les prêts hérités",FLT648093:"Identifiant du compte de prêt",FLT648094:"Intérêts calculés jusa",FLT030604:"Devise",FLT648095:"Intérêt pour Finacle",FLT648096:"Intérêt pour l'héritage",FLT648097:"Intérêt da ajusté",FLT648098:"Rajustement actuel des intérêts",FLT648099:"Compte opérationnel",FLT648100:"Code du taux de conversion",FLT003129:"Créer une transaction",FLT001721:"Clair",FLT026526:"D'accord"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY 
var jspErr={};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);
