//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT026332:" Code de réception ",FLT026333:" ID du sol",FLT026334:"Code du système  (combinaison) ",FLT026335:" Date",FLT026341:"Sélectionner--",FLT026342:"B-Bloc (blocage)  ",FLT026343:"U-Déblocage "};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

