//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT000003:"Identifiant CIF      ",FLT000004:"Fonction",FLT000005:"Sélectionnez",FLT000006:"Ajouter",FLT000007:" Modifier",FLT000008:"Demande /Enquête",FLT000009: "Supprimer"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);
