//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT004977:"Aller",FLT033791:"Maintien du pourcentage de pénalité personnalisé",FLT033107:"Une fonction:",FLT033801:"Nom de domaine:",FLT033802:"Pourcentage:",FLT033803:"Supprimer le drapeau:",FLT000193:"Soumettre",FLT001721:"Annuler",FLT026526:"D'accord"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY 
var jspErr={};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);

