//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT004977:"Aller",FLT032047:"Maintainace d'intérêt préférentiel",FLT006657:"Fonction",FLT031943:"ID de rôle",FLT004977:"Aller",FLT001439:"Clair",FLT031699:"A-ajouter",FLT031700:"M-Modifier",FLT031702:"V-Vérifier",FLT031701:"I-Renseigner",FLT031733:"X-Annuler",FLT031732:"D-Effacer"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY
var jspErr={};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);

