//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT004977:"Aller",FLT032047:"Maintainace d'intérêt préférentiel",FLT006657:"Fonction",FLT031943:"ID de rôle",FLT032090:"Intérêt préférentiel (%)",FLT000193:"Soumettre",FLT000194:"Valider",FLT001721:"Annuler",FLT026526:"D'accord"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY
var jspErr={};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);
