//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT004977:" (Aller)",FLT031859:"FLT031859: Système déchange – Détails dachat ",FLT006657:"Fonction",FLT031347:"Type de transaction ",FLT032045:"Numéro  CDSC",FLT031846:"Numéro de compte",FLT032156:"FLT032156: Numéro de référence",FLT031850:"ID de la transaction",FLT032220:"numéro de série",FLT021862:"Date de la transaction (transfert)",FLT013609:"FLT013609: marquer la rétention ",FLT031854:"Remarques du Transaction (transfert)",FLT002043:"FLT002043: Détails dachat",FLT032091:"FLT032091: numéro de ligne",FLT031522:"FLT031522: Code  de sécurité ",FLT031524:"FLT031524: Nom de sécurité ",FLT031526:"FLT031526: Prix demandé",FLT029546:"FLT029546: Dépôt",FLT031562:"FLT031562: No  d’Actions (partage, cotisation)",FLT031863:"FLT031863: Montant Commandé",FLT031739:"FLT031739: Pourcentage commun ",FLT032155:"FLT032155: Montant Commun ",FLT031571:"FLT031571: Timbre",FLT031865:"FLT031865: Montant total ",FLT031577:"FLT031577: (Reste, actif, net, résidu)",FLT031767:"FLT031767: date de la commande ",FLT032012:"FLT032012: Effacer",FLT032091:"FLT032091: numéro de ligne",FLT031522:"FLT031522: Code  de sécurité ",FLT031524:"FLT031524: Nom de sécurité ",FLT031526:"FLT031526: Prix demandé",FLT029546:"FLT029546: Dépôt",FLT031562:"FLT031562: No  d’Actions (partage, cotisation)",FLT031863:"FLT031863: Montant Commandé",FLT031739:"FLT031739: Pourcentage commun ",FLT032155:"FLT032155: Montant Commun ",FLT031571:"FLT031571: Timbre",FLT031865:"FLT031865: Montant total ",FLT031577:"FLT031577: (Reste, actif, net, résidu)",FLT031767:"FLT031767: date de la commande ",FLT032012:"FLT032012: Effacer",FLT031766:"FLT031766: Total des taxes",FLT000193:"Envoyer  (soumettre) ",FLT000194:"Valider",FLT001721:"Annuler /Effacer ",FLT026526:" OK",FLT0265262:"FLT0265262: Détails du compte",FLT0265263:"FLT0265263: CDSC Détails",
FLT032045:"FLT0265262: Détails du compte",FLT031846:"FLT0265263: CDSC Détails"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY
var jspErr={FAT000924:"Enter a value in the field."};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);
