//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT004977:"aller",FLT648026:"Vérifier le statut de certification",FLT006657:"Une fonction",FLT648034:"Numéro de compte",FLT648035:"Numéro du chèque",FLT004977:"aller",FLT001439:"Clair",FLT648027:"--SÉLECTIONNER--",FLT648028:"A-Ajouter un chèque certifié",FLT648029:"R-Libérer le chèque certifié",FLT648030:"M-Payer le chèque certifié",FLT648031:"V-Vérifier",FLT648032:"I-Renseigner",FLT648033:"X-Annuler"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY 
var jspErr={};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);
