//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT004977:"aller",FLT648026:"Vérifier le statut de certification",FLT006657:"Une fonction",FLT648034:"Numéro de compte",FLT648035:"Numéro du chèque",FLT002671:"Statut",FLT648036:"Montant du chèque",FLT648037:"Montant payé",FLT000193:"Soumettre",FLT000194:"Valider",FLT001721:"Annuler",FLT648038:"Y-Chèque certifié",FLT648039:"Z-Certified Check libéré",FLT648040:"P-Payé",FLT026526:"D'accord"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY 
var jspErr={};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);
