//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT004977:" (Aller)",FLT031734:"FLT031734: Maintenance des dénominations monétaires",FLT112254:"Fonction",FLT030604:" Devise",FLT031735:"FLT031735: Point décimal autorisé",FLT003523:"FLT003523: Dénomination",FLT000193:"Envoyer  (soumettre) ",FLT021284:"Valider",FLT027575:"Annuler /Effacer ",FLT026526:" OK"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY 
var jspErr={};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);
