//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT026332:"Fonction",FLT026333:"FLT019770: ID  de l’utilisateur",FLT026334:"SELECTIONNER"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);
