spring:
  application:
    name: papss-inbound-technical-service-ms
  profiles:
    active: prod

eureka:
  instance:
    hostname: papss-inbound-technical-service-ms
    prefer-ip-address: false  # Use hostname instead of IP
  client:
    service-url:
      defaultZone: http://localhost:8765/eureka/

#actuator configs
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    jolokia:
      enabled: true
    shutdown:
      enabled: true #for gracefully shutting down the app - http://localhost:<PortNumber>/actuator/shutdown
    health:
      show-details: when_authorized
  info:
    env:
      enabled: true