
  CREATE TABLE "CUSTOM"."CUSTOM_FINACLEUSER_STATUS_TBL" 
   (	"USER_ID" VARCHAR2(10 CHAR), 
	"EMP_ID" VARCHAR2(10 CHAR), 
	"BANK_ID" VARCHAR2(8 CHAR), 
	"API_NAME" VARCHAR2(25 CHAR), 
	"EFM_USER_FLG" VARCHAR2(10 CHAR), 
	"EFM_REMARKS" VARCHAR2(200 CHAR), 
	"CORE_USER_FLG" VARCHAR2(10 CHAR), 
	"CORE_REMARKS" VARCHAR2(200 CHAR), 
	"SSO_USER_FLG" VARCHAR2(10 CHAR), 
	"SSO_REMARKS" VARCHAR2(200 CHAR), 
	"CRM_USER_FLG" VARCHAR2(10 CHAR), 
	"CRM_REMARKS" VARCHAR2(200 CHAR), 
	"SVS_USER_FLG" VARCHAR2(10 CHAR), 
	"SVS_REMARKS" VARCHAR2(200 CHAR), 
	"RI_USER_FLG" VARCHAR2(10 CHAR), 
	"RI_REMARKS" VARCHAR2(200 CHAR), 
	"LCHG_USER_ID" VARCHAR2(15 CHAR), 
	"LCHG_TIME" DATE, 
	"RCRE_USER_ID" VARCHAR2(15 CHAR), 
	"RCRE_TIME" DATE, 
	 CONSTRAINT "C_USERSTATUS" UNIQUE ("USER_ID", "API_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 16384 NEXT 16384 MINEXTENTS 1 MAXEXTENTS 505
  PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CUSTOM_TBLS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 16384 NEXT 16384 MINEXTENTS 1 MAXEXTENTS 505
  PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CUSTOM_TBLS" ;

CREATE OR REPLACE SYNONYM "CUSTOM"."C_FINACLEUSER_STATUS_TBL" FOR "CUSTOM"."CUSTOM_FINACLEUSER_STATUS_TBL";

  GRANT DELETE ON "CUSTOM"."CUSTOM_FINACLEUSER_STATUS_TBL" TO "TBAGEN";
  GRANT UPDATE ON "CUSTOM"."CUSTOM_FINACLEUSER_STATUS_TBL" TO "TBAADM";
  GRANT SELECT ON "CUSTOM"."CUSTOM_FINACLEUSER_STATUS_TBL" TO "TBAADM";
  GRANT INSERT ON "CUSTOM"."CUSTOM_FINACLEUSER_STATUS_TBL" TO "TBAADM";
  GRANT DELETE ON "CUSTOM"."CUSTOM_FINACLEUSER_STATUS_TBL" TO "TBAADM";
  GRANT UPDATE ON "CUSTOM"."CUSTOM_FINACLEUSER_STATUS_TBL" TO "TBAUTIL";
  GRANT SELECT ON "CUSTOM"."CUSTOM_FINACLEUSER_STATUS_TBL" TO "TBAUTIL";
  GRANT INSERT ON "CUSTOM"."CUSTOM_FINACLEUSER_STATUS_TBL" TO "TBAUTIL";
  GRANT DELETE ON "CUSTOM"."CUSTOM_FINACLEUSER_STATUS_TBL" TO "TBAUTIL";
  GRANT UPDATE ON "CUSTOM"."CUSTOM_FINACLEUSER_STATUS_TBL" TO "TBAGEN";
  GRANT SELECT ON "CUSTOM"."CUSTOM_FINACLEUSER_STATUS_TBL" TO "TBAGEN";
  GRANT INSERT ON "CUSTOM"."CUSTOM_FINACLEUSER_STATUS_TBL" TO "TBAGEN";
