DROP TABLE CUSTOM.C_WTH_ACCT_OPEN_ACCT_INFO CASCADE CONSTRAINTS;

CREATE TABLE CUSTOM.C_WTH_ACCT_OPEN_ACCT_INFO
(
  TAX_TO_BE_RECOVERED         NUMBER(20,4),
  FORACID                     VARCHAR2(16 CHAR ),
  LCHG_USER_ID                VARCHAR2(15 CHAR),
  LCHG_TIME                   DATE,
  RCRE_USER_ID                VARCHAR2(15 CHAR),
  RCRE_TIME                   DATE,
  DEL_FLG                     CHAR (1 Byte),
  ENTITY_CRE_FLG              CHAR (1 Byte),
  BANK_ID                     VARCHAR2(8 CHAR)
 ) 
 TABLESPACE SYSTEM;
 
 
 CREATE UNIQUE INDEX CUSTOM.IDX_C_WTH_ACCT_OPEN_ACCT_INFO ON CUSTOM.C_WTH_ACCT_OPEN_ACCT_INFO
 (FORACID,BANK_ID)
 LOGGING
 TABLESPACE IDX_TRANS
 PCTFREE    10
 INITRANS   2
 MAXTRANS   255
 STORAGE    (
             INITIAL          1M
             NEXT             1M
             MINEXTENTS       1
             MAXEXTENTS       UNLIMITED
             PCTINCREASE      0
             BUFFER_POOL      DEFAULT
            )
NOPARALLEL;

DROP SYNONYM CUSTOM.C_WTHAOO;

CREATE SYNONYM CUSTOM.C_WTHAOO FOR CUSTOM.C_WTH_ACCT_OPEN_ACCT_INFO;


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON CUSTOM.C_WTH_ACCT_OPEN_ACCT_INFO TO TBAADM;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON CUSTOM.C_WTH_ACCT_OPEN_ACCT_INFO TO TBAGEN;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON CUSTOM.C_WTH_ACCT_OPEN_ACCT_INFO TO TBAUTIL;





 
