DROP TABLE CUSTOM.ATM_COMM_DISTRIBUTION CASCADE CONSTRAINTS;

CREATE TABLE CUSTOM.ATM_COMM_DISTRIBUTION
(
  BOD_DATE            DATE,
  MAIN_SOL_COMM_ACNT  VARCHAR2(15 BYTE),
  TRAN_ID             VARCHAR2(15 BYTE),
  TRAN_DATE           DATE,
  TRAN_AMT            NUMBER,
  ATM_SOL_ID          VARCHAR2(5 BYTE),
  ATM_SOL_COMM        NUMBER,
  ATM_SOL_COMM_ACCT   VARCHAR2(15 BYTE),
  ATM_ID              VARCHAR2(15 BYTE),
  CUST_SOL_ID         VARCHAR2(5 BYTE),
  CUST_SOL_COMM       NUMBER,
  CUST_SOL_COMM_ACCT  VARCHAR2(15 BYTE)
);

GRANT DELETE, INSERT, UPDATE ON CUSTOM.ATM_COMM_DISTRIBUTION TO TBAADM;

GRANT DELETE, INSERT, UPDATE ON CUSTOM.ATM_COMM_DISTRIBUTION TO TBAGEN;

GRANT DELETE, INSERT, UPDATE ON CUSTOM.ATM_COMM_DISTRIBUTION TO TBAUTIL;
