CREATE TABLE CUSTOM.CUSTOM_HIST_TRAN_HEADER_TABLE
(
  TRAN_DATE                 DATE,
  TRAN_ID                   VARCHAR2(9 CHAR),
  DEL_FLG                   CHAR(1 BYTE),
  TRAN_TYPE                 CHAR(1 BYTE),
  TRAN_SUB_TYPE             VARCHAR2(2 CHAR),
  NUM_CR_TRAN_ENTRY         NUMBER(4),
  NUM_DR_TRAN_ENTRY         NUMBER(4),
  NUM_CR_TRAN_PSTD          NUMBER(4),
  NUM_DR_TRAN_PSTD          NUMBER(4),
  NUM_TRAN_VFD              NUMBER(4),
  NUM_TRAN_DELETED          NUMBER(4),
  TRAN_CRE_MODE             CHAR(1 BYTE),
  RESTRICT_MODIFY_IND       CHAR(1 BYTE),
  REMARKS                   VARCHAR2(30 CHAR),
  LCHG_USER_ID              VARCHAR2(15 CHAR),
  LCHG_TIME                 DATE,
  RCRE_USER_ID              VARCHAR2(15 CHAR),
  RCRE_TIME                 DATE,
  PST_FLG                   CHAR(1 BYTE),
  DELIVERY_CHANNEL_ID       VARCHAR2(10 CHAR),
  INIT_SOL_ID               VARCHAR2(8 CHAR),
  IGNORE_XCPN_FLG           CHAR(1 BYTE),
  NUM_TRAN_PURGED           NUMBER(4),
  B2K_EVENT_TYPE            VARCHAR2(5 CHAR),
  TS_CNT                    NUMBER(5),
  REFERRAL_EVENT_TYPE       VARCHAR2(10 CHAR),
  BANK_ID                   VARCHAR2(8 CHAR),
  SYS_ENTERED_USER_MOD_FLG  CHAR(1 BYTE)
);


CREATE UNIQUE INDEX CUSTOM.IDX_CUST_HIST_TRAN_HEADER_TBL ON CUSTOM.CUSTOM_HIST_TRAN_HEADER_TABLE
(TRAN_DATE, TRAN_ID, BANK_ID)
;


CREATE SYNONYM TBAGEN.HTH FOR CUSTOM.CUSTOM_HIST_TRAN_HEADER_TABLE;


CREATE SYNONYM TBAUTIL.HTH FOR CUSTOM.CUSTOM_HIST_TRAN_HEADER_TABLE;


CREATE SYNONYM CUSTOM.C_HTH FOR CUSTOM.CUSTOM_HIST_TRAN_HEADER_TABLE;


GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.CUSTOM_HIST_TRAN_HEADER_TABLE TO CRMUSER;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.CUSTOM_HIST_TRAN_HEADER_TABLE TO TBAGEN;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.CUSTOM_HIST_TRAN_HEADER_TABLE TO TBAUTIL;
