CREATE TABLE CUSTOM.CUST_ROLE_CREDT_LMT_TABLE
(
  ROLE_ID                      VARCHAR2(15 BYTE),
  USER_CASH_CR_LIM             NUMBER(20,4),
  USER_CLG_CR_LIM              NUMBER(20,4),
  USER_XFER_CR_LIM             NUMBER(20,4),
  USER_INTERSOL_CASH_CR_LIMIT  NUMBER(20,4),
  USER_INTERSOL_CLG_CR_LIMIT   NUMBER(20,4),
  USER_INTERSOL_XFER_CR_LIMIT  NUMBER(20,4),
  CRNCY_CODE                   VARCHAR2(3 BYTE),
  DEL_FLG                      CHAR(1 BYTE),
  ENT_CRE_FLG                  CHAR(1 BYTE),
  LCHG_USER_ID                 VARCHAR2(15 BYTE),
  LCHG_TIME                    DATE,
  RCRE_USER_ID                 VARCHAR2(15 BYTE),
  RCRE_TIME                    DATE,
  BANK_ID                      VARCHAR2(3 BYTE)
);


CREATE UNIQUE INDEX CUSTOM.IDX_CRCL ON CUSTOM.CUST_ROLE_CREDT_LMT_TABLE
(ROLE_ID, CRNCY_CODE, BANK_ID);


CREATE SYNONYM CUSTOM.CRCL FOR CUSTOM.CUST_ROLE_CREDT_LMT_TABLE;


CREATE SYNONYM CUSTOM.TBA_ROLE_CREDT_LMT_TBL FOR CUSTOM.CUST_ROLE_CREDT_LMT_TABLE;

