CREATE TABLE CUSTOM.MERCHANTS_TABLE
(
  CHANNEL_ID                VARCHAR2(10 BYTE),
  MERCHANT_DESC             VARCHAR2(100 BYTE),
  MERCHANT_ID               VARCHAR2(100 BYTE),
  MERCH_PURCHASE_PAYABLE    VARCHAR2(16 BYTE),
  MERCH_CASHBACK_PAYABLE    VARCHAR2(16 BYTE),
  MERCH_COMM_PAYABLE        VARCHAR2(16 BYTE),
  MERCH_SETTLEMENT_ACCOUNT  VARCHAR2(16 BYTE),
  MERCH_CASHBACK_COMM       VARCHAR2(5 BYTE),
  MERCH_PURCHASE_COMM       VARCHAR2(5 BYTE),
  ENTERER_ID                VARCHAR2(15 BYTE),
  ENTERER_DATE              DATE,
  ENTITY_CRE_FLG            VARCHAR2(1 BYTE),
  VFD_USER_ID               VARCHAR2(15 BYTE),
  VFD_DATE                  DATE,
  AUDIT_BOD_DATE            DATE,
  AUDIT_SRL_NUM             VARCHAR2(100 BYTE),
  DEL_FLG                   VARCHAR2(1 BYTE),
  BANK_ID                   VARCHAR2(10 BYTE)
);


CREATE SYNONYM CUSTOM.C_MERCHANTS FOR CUSTOM.MERCHANTS_TABLE;


CREATE SYNONYM TBAADM.C_MERCHANTS FOR CUSTOM.MERCHANTS_TABLE;


CREATE SYNONYM TBAGEN.C_MERCHANTS FOR CUSTOM.MERCHANTS_TABLE;


CREATE SYNONYM TBAUTIL.C_MERCHANTS FOR CUSTOM.MERCHANTS_TABLE;


GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.MERCHANTS_TABLE TO TBAADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.MERCHANTS_TABLE TO TBAGEN;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.MERCHANTS_TABLE TO TBAUTIL;
