CREATE TABLE CUSTOM.UPLD_CHKSUM_DTLS
(
  MENU_ID        VARCHAR2(8 BYTE),
  UPL_FILE_NAME  VARCHAR2(80 BYTE),
  CHECK_SUM      VARCHAR2(150 BYTE),
  UPL_USER_ID    VARCHAR2(15 BYTE),
  UPL_TIME       DATE,
  BANK_ID        VARCHAR2(8 BYTE)
)
TABLESPACE CUSTOM_TBLS;

CREATE UNIQUE INDEX CUSTOM.IDX_C_UCD ON CUSTOM.UPLD_CHKSUM_DTLS
(MENU_ID, CHECK_SUM, BANK_ID);

DROP SYNONYM CUSTOM.C_UCD;

CREATE SYNONYM CUSTOM.C_UCD FOR CUSTOM.UPLD_CHKSUM_DTLS;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON CUSTOM.UPLD_CHKSUM_DTLS TO TBAADM;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON CUSTOM.UPLD_CHKSUM_DTLS TO TBAGEN;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON CUSTOM.UPLD_CHKSUM_DTLS TO TBAUTIL;
