CREATE TABLE CUSTOM.CUST_CHQ_BOOK_INST_TABLE
(
  INST_TYPE  VARCHAR2(5 BYTE),
  INST_DESC  VARCHAR2(30 BYTE),
  DEL_FLG    CHAR(1 BYTE),
  BANK_ID    VARCHAR2(8 BYTE)
);


CREATE UNIQUE INDEX CUSTOM.IDX_C_CBT_INT_INST_TYPE ON CUSTOM.CUST_CHQ_BOOK_INST_TABLE
(INST_TYPE);


CREATE SYNONYM CUSTOM.C_CBT_INT FOR CUSTOM.CUST_CHQ_BOOK_INST_TABLE;


GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.CUST_CHQ_BOOK_INST_TABLE TO TBAADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.CUST_CHQ_BOOK_INST_TABLE TO TBAGEN;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.CUST_CHQ_BOOK_INST_TABLE TO TBAUTIL;
