DROP TABLE CUSTOM.CUST_SAL_UPLD_PROCESS_TABLE CASCADE CONSTRAINTS;

CREATE TABLE CUSTOM.CUST_SAL_UPLD_PROCESS_TABLE
(
  EMPLOYER         VARCHAR2(10 BYTE),
  EMPLOYEE_ID      VARCHAR2(15 BYTE),
  UPL_ACCT_NO      VARCHAR2(16 BYTE),
  ACCT_CRNCY_CODE  VARCHAR2(3 BYTE),
  UPL_ACCT_NAME    VARCHAR2(80 BYTE),
  SAL_CR_AMT       NUMBER(20,4),
  TRAN_PARTICULAR  VARCHAR2(50 BYTE),
  SOL_ID           VARCHAR2(8 BYTE),
  FORACID          VARCHAR2(16 BYTE),
  UPL_KEY          VARCHAR2(6 BYTE),
  UPL_DATE         DATE,
  UPL_STATUS       CHAR(1 BYTE),
  LCHG_USER_ID     VARCHAR2(15 BYTE),
  LCHG_TIME        DATE,
  RCRE_USER_ID     VARCHAR2(15 BYTE),
  RCRE_TIME        DATE,
  CHRG_FLG         CHAR(1 BYTE),
  DEL_FLG          CHAR(1 BYTE),
  INVALID          VARCHAR2(2 BYTE),
  RMK              VARCHAR2(100 BYTE),
  GAM_ACCT         VARCHAR2(80 BYTE),
  GAM_EMP_ID       VARCHAR2(10 BYTE),
  BATCH            VARCHAR2(1 BYTE),
  GAM_SOL_ID       VARCHAR2(8 BYTE),
  BANK_ID          VARCHAR2(8 BYTE)
);

CREATE INDEX CUSTOM.IDX_C_EMP_USR ON CUSTOM.CUST_SAL_UPLD_PROCESS_TABLE
(EMPLOYER, RCRE_USER_ID, BANK_ID);

CREATE INDEX CUSTOM.IDX_C_SUP_EMPLOYER ON CUSTOM.CUST_SAL_UPLD_PROCESS_TABLE
(EMPLOYER, UPL_STATUS, CHRG_FLG, DEL_FLG, BANK_ID);

CREATE INDEX CUSTOM.IDX_C_SUP_FORACID ON CUSTOM.CUST_SAL_UPLD_PROCESS_TABLE
(FORACID, BANK_ID);

CREATE INDEX CUSTOM.IDX_C_SUP_UPL_ACCT_NO ON CUSTOM.CUST_SAL_UPLD_PROCESS_TABLE
(UPL_ACCT_NO, SOL_ID, BANK_ID);

DROP SYNONYM CUSTOM.C_SUP;

CREATE SYNONYM CUSTOM.C_SUP FOR CUSTOM.CUST_SAL_UPLD_PROCESS_TABLE;

GRANT SELECT ON CUSTOM.CUST_SAL_UPLD_PROCESS_TABLE TO ALLTAB;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.CUST_SAL_UPLD_PROCESS_TABLE TO TBAADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.CUST_SAL_UPLD_PROCESS_TABLE TO TBAGEN;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.CUST_SAL_UPLD_PROCESS_TABLE TO TBAUTIL;

