CREATE SEQUENCE CUSTOM.ACCM_REQ_ID
  START WITH 148
  MAXVALUE 9999999
  MINVALUE 1
  CYCLE
  NOCACHE
  ORDER;


GRANT SELECT ON CUSTOM.ACCM_REQ_ID TO TBAADM;

GRANT SELECT ON CUSTOM.ACCM_REQ_ID TO TBAGEN;
