DROP TABLE CUSTOM.IGLS_NOM_ACCT_CRE_TABLE CASCADE CONSTRAINTS;

CREATE TABLE CUSTOM.IGLS_NOM_ACCT_CRE_TABLE
(
  MEMBER_ID       VARCHAR2(13 BYTE),
  CIF_ID          VARCHAR2(32 BYTE),
  SOL_ID          VARCHAR2(8 BYTE),
  SCHM_CODE_1     VARCHAR2(5 BYTE),
  SCHM_CODE_2     VARCHAR2(5 BYTE),
  CRNCY_CODE      VARCHAR2(5 BYTE),
  SB_ACCOUNT_1    VARCHAR2(16 BYTE),
  SB_ACCOUNT_2    VARCHAR2(16 BYTE),
  ACCT_REQ_USER   VARCHAR2(15 BYTE),
  ACCT_REQ_TIME   DATE,
  ACCT_CRE_USER   VARCHAR2(15 BYTE),
  ACCT_CRE_TIME   DATE,
  ACCT_OPEN_DATE  DATE,
  DEL_FLG         CHAR(1 BYTE)                  DEFAULT 'N',
  VERIFY_CNT      NUMBER                        DEFAULT 0,
  STATUS          CHAR(1 BYTE)                  DEFAULT 'R',
  RCRE_USER       VARCHAR2(15 BYTE),
  RCRE_TIME       DATE,
  LCHG_USER       VARCHAR2(15 BYTE),
  LCHG_TIME       DATE,
  ACCT_MGR        VARCHAR2(15 BYTE),
  PF_NO           VARCHAR2(15 BYTE),
  GRP_REG_NO      VARCHAR2(30 BYTE),
  BORROWING_TYPE  VARCHAR2(1 BYTE)              DEFAULT 'M',
  COUNTRY_ID      CHAR(2 BYTE),
  BANK_ID         VARCHAR2(8 BYTE)
);

GRANT SELECT ON CUSTOM.IGLS_NOM_ACCT_CRE_TABLE TO ALLTAB;

GRANT SELECT ON CUSTOM.IGLS_NOM_ACCT_CRE_TABLE TO DBREAD;

GRANT SELECT ON CUSTOM.IGLS_NOM_ACCT_CRE_TABLE TO EBETLUSR;

GRANT INSERT, UPDATE ON CUSTOM.IGLS_NOM_ACCT_CRE_TABLE TO EFRNT;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.IGLS_NOM_ACCT_CRE_TABLE TO TBAADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.IGLS_NOM_ACCT_CRE_TABLE TO TBAGEN;

GRANT SELECT ON CUSTOM.IGLS_NOM_ACCT_CRE_TABLE TO TBAUTIL;
