 CREATE SEQUENCE CUSTOM.ORD_ID_SEQ
  START WITH 1
  MAXVALUE 99999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


GRANT SELECT ON CUSTOM.ORD_ID_SEQ TO TBAGEN;

GRANT SELECT ON CUSTOM.ORD_ID_SEQ TO TBAUTIL;
