
CREATE TABLE CUSTOM.CUST_PSPFILEPATH
(
  RPT_FILE_PATH   VARCHAR2(200 CHAR),
  USER_ID         VARCHAR2(50 CHAR),
  BANK_ID         VARCHAR2(10 CHAR),
  DEL_FLG         VARCHAR2(10 CHAR),
  RCRE_USER_TIME  DATE
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             16K
            MINEXTENTS       1
            MAXEXTENTS       505
            PCTINCREASE      50
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE INDEX CUSTOM.IDX_C_PSPFILEPATH ON CUSTOM.CUST_PSPFILEPATH
(USER_ID,BANK_ID)
LOGGING
TABLESPACE CUSTOM_IDXSPACE
PCTFREE    10
INITRANS   50
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        32
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

DROP SYNONYM CUSTOM.C_PSPFL;

CREATE OR REPLACE SYNONYM CUSTOM.C_PSPFL FOR CUSTOM.CUST_PSPFILEPATH;


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON CUSTOM.CUST_PSPFILEPATH TO TBAADM;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON CUSTOM.CUST_PSPFILEPATH TO TBAGEN;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON CUSTOM.CUST_PSPFILEPATH TO TBAUTIL;
