CREATE TABLE CUSTOM.CUST_MOB_BRANCH_TABLE
(
  SOL_ID        VARCHAR2(8 BYTE),
  SCHM_CODE     VARCHAR2(5 BYTE),
  MBM_DATE      DATE,
  MBM_STATUS    CHAR(1 BYTE),
  LCHG_USER_ID  VARCHAR2(15 BYTE),
  LCHG_TIME     DATE,
  RCRE_USER_ID  VARCHAR2(15 BYTE),
  RCRE_TIME     DATE,
  DEL_FLG       CHAR(1 BYTE),
  BANK_ID       VARCHAR2(10 BYTE)
)
;


CREATE SYNONYM CUSTOM.C_MBM FOR CUSTOM.CUST_MOB_BRANCH_TABLE;


CREATE SYNONYM TBAUTIL.C_MBM FOR CUSTOM.CUST_MOB_BRANCH_TABLE;


CREATE SYNONYM TBAGEN.C_MBM FOR CUSTOM.CUST_MOB_BRANCH_TABLE;


CREATE SYNONYM TBAADM.C_MBM FOR CUSTOM.CUST_MOB_BRANCH_TABLE;


GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.CUST_MOB_BRANCH_TABLE TO TBAADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.CUST_MOB_BRANCH_TABLE TO TBAGEN;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.CUST_MOB_BRANCH_TABLE TO TBAUTIL;
