DROP table INTENT_REV_TRAN_DETAIL_TBL
/
DROP SYNONYM TBAADM.INTENT_REV_TRAN_DETAIL_TBL
/
DROP SYNONYM TBAGEN.INTENT_REV_TRAN_DETAIL_TBL
/
DROP SYNONYM TBAUTIL.INTENT_REV_TRAN_DETAIL_TBL
/
DROP SYNONYM TBAADM.IEREV
/
DROP SYNONYM TBAGEN.IEREV
/
DROP SYNONYM TBAUTIL.IEREV
/
CREATE TABLE CUSTOM.INTENT_REV_TRAN_DETAIL_TBL(
IE_TXN_REF_NO			VARCHAR2(10 CHAR),
ENTITY1_TRAN_ID			VARCHAR2(9 CHAR),
ENTITY1_TRAN_DATE		DATE,
ENTITY2_TRAN_ID			VARCHAR2(9 CHAR),
ENTITY2_TRAN_DATE		DATE,
ORG_CHRG_TRAN_ID		VARCHAR2(9 CHAR),
ORG_CHARGE_TRAN_DATE		DATE,
ENTITY1_REV_TRAN_ID		VARCHAR2(9 CHAR),
ENTITY1_REV_TRAN_DATE		DATE,
ENTITY2_REV_TRAN_ID		VARCHAR2(9 CHAR),
ENTITY2_REV_TRAN_DATE		DATE,
REV_CHRG_TRAN_ID		VARCHAR2(9 CHAR),
REV_CHARGE_TRAN_DATE		DATE,
DEL_FLG				CHAR(1),
ENTITY_CRE_FLG			CHAR(1),
RCRE_USER_ID			VARCHAR2(15 CHAR),
RCRE_TIME			DATE,
LCHG_USER_ID                    VARCHAR2(15 CHAR),
LCHG_TIME                       DATE,
BANK_ID				VARCHAR2(8 CHAR)
)
/

CREATE SYNONYM TBAADM.INTENT_REV_TRAN_DETAIL_TBL FOR INTENT_REV_TRAN_DETAIL_TBL
/
CREATE SYNONYM TBAGEN.INTENT_REV_TRAN_DETAIL_TBL FOR INTENT_REV_TRAN_DETAIL_TBL
/
CREATE SYNONYM TBAUTIL.INTENT_REV_TRAN_DETAIL_TBL FOR INTENT_REV_TRAN_DETAIL_TBL
/
CREATE SYNONYM TBAADM.IEREV FOR INTENT_REV_TRAN_DETAIL_TBL
/
CREATE SYNONYM TBAGEN.IEREV FOR INTENT_REV_TRAN_DETAIL_TBL
/
CREATE SYNONYM TBAUTIL.IEREV FOR INTENT_REV_TRAN_DETAIL_TBL
/
CREATE SYNONYM CUSTOM.IEREV FOR INTENT_REV_TRAN_DETAIL_TBL
/
GRANT SELECT, INSERT, UPDATE, DELETE ON INTENT_REV_TRAN_DETAIL_TBL TO TBAGEN
/
GRANT SELECT ON INTENT_REV_TRAN_DETAIL_TBL TO TBAUTIL
/
GRANT SELECT ON INTENT_REV_TRAN_DETAIL_TBL TO TBAADM
/
COMMIT
/

