DROP TABLE CUSTOM.ATM_COMM_DISTRIBUTION_ERR CASCADE CONSTRAINTS;

CREATE TABLE CUSTOM.ATM_COMM_DISTRIBUTION_ERR
(
  BOD_DATE   DATE,
  TRAN_ID    VARCHAR2(15 BYTE),
  TRAN_DATE  DATE,
  ERR        VARCHAR2(1000 BYTE)
);


GRANT SELECT ON CUSTOM.ATM_COMM_DISTRIBUTION_ERR TO ALLTAB;

GRANT SELECT ON CUSTOM.ATM_COMM_DISTRIBUTION_ERR TO PUBLIC;
