DROP SEQUENCE CUSTOM.ADT_CUSTOM_SEQUENCE;

CREATE SEQUENCE CUSTOM.ADT_CUSTOM_SEQUENCE
  START WITH 6
  MAXVALUE 99999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


GRANT SELECT ON CUSTOM.ADT_CUSTOM_SEQUENCE TO TBAADM;

GRANT SELECT ON CUSTOM.ADT_CUSTOM_SEQUENCE TO TBAGEN;
