CREATE TABLE CUSTOM.MODULEDET_MOD
(
  MODULE_ID       VARCHAR2(30 CHAR),
  MODULE_DESC     VARCHAR2(50 CHAR),
  DEL_FLG         CHAR(1 BYTE),
  RCRE_USER_ID    VARCHAR2(15 CHAR),
  RCRE_TIME       DATE,
  LCHG_USER_ID    VARCHAR2(15 CHAR),
  LCHG_TIME       DATE,
  ENTITY_CRE_FLG  CHAR(1 BYTE),
  TS_COUNT        NUMBER(5),
  BANK_ID         VARCHAR2(10 CHAR)
);


CREATE SYNONYM TBAADM.MODULEMOD FOR CUSTOM.MODULEDET_MOD;


CREATE SYNONYM TBAGEN.MODULEMOD FOR CUSTOM.MODULEDET_MOD;


CREATE SYNONYM TBAUTIL.MODULEMOD FOR CUSTOM.MODULEDET_MOD;


CREATE SYNONYM CUSTOM.MODULEMOD FOR CUSTOM.MODULEDET_MOD;


GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.MODULEDET_MOD TO TBAADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.MODULEDET_MOD TO TBAGEN;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.MODULEDET_MOD TO TBAUTIL;
