CREATE TABLE CUSTOM.C_BIO_CUST_OVERDUE
(
  CNTRY_CODE     VARCHAR2(25 BYTE),
  CUST_ID        VARCHAR2(50 BYTE),
  OVER_RIDE_FLG  CHAR(1 BYTE),
  RCRE_USER_ID   VARCHAR2(30 BYTE),
  RCRE_TIME      DATE,
  DEL_FLG        CHAR(1 BYTE),
  BANK_ID        VARCHAR2(20 BYTE)
);


CREATE INDEX CUSTOM.IDX_C_BIO_CUST_OVERDUE ON CUSTOM.C_BIO_CUST_OVERDUE
(CUST_ID, BANK_ID);


CREATE SYNONYM CUSTOM.C_BIO_CUST_OVERDUE_SYN FOR CUSTOM.C_BIO_CUST_OVERDUE;


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON CUSTOM.C_BIO_CUST_OVERDUE TO TBAADM;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON CUSTOM.C_BIO_CUST_OVERDUE TO TBAGEN;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON CUSTOM.C_BIO_CUST_OVERDUE TO TBAUTIL;
