CREATE TABLE CUST_ISL_TAWARRUQ_ACCT_TBL(
TAWARRUQ_ACCT_NUM		VARCHAR2(16 CHAR),
PURCHASE_REF_NO			VARCHAR2(12 CHAR),
BANK_ID				VARCHAR2(8 CHAR)
)
/

CREATE SYNONYM TBAADM.CUST_ISL_TAWARRUQ_ACCT_TBL FOR CUST_ISL_TAWARRUQ_ACCT_TBL
/
CREATE SYNONYM TBAGEN.CUST_ISL_TAWARRUQ_ACCT_TBL FOR CUST_ISL_TAWARRUQ_ACCT_TBL
/
CREATE SYNONYM TBAUTIL.CUST_ISL_TAWARRUQ_ACCT_TBL FOR CUST_ISL_TAWARRUQ_ACCT_TBL
/
CREATE SYNONYM TBAADM.CITA FOR CUST_ISL_TAWARRUQ_ACCT_TBL
/
CREATE SYNONYM TBAGEN.CITA FOR CUST_ISL_TAWARRUQ_ACCT_TBL
/
CREATE SYNONYM TBAUTIL.CITA FOR CUST_ISL_TAWARRUQ_ACCT_TBL
/
CREATE SYNONYM CUSTOM.CITA FOR CUST_ISL_TAWARRUQ_ACCT_TBL
/
GRANT SELECT, INSERT, UPDATE, DELETE ON CUST_ISL_TAWARRUQ_ACCT_TBL TO TBAGEN
/
GRANT SELECT ON CUST_ISL_TAWARRUQ_ACCT_TBL TO TBAUTIL
/
COMMIT
/

