DROP TABLE CUSTOM.BULK_CIF CASCADE CONSTRAINTS;

CREATE TABLE CUSTOM.BULK_CIF
(
  NATIONAL_ID     VARCHAR2(16 BYTE),
  ENTITY_CRE_FLG  VARCHAR2(5 BYTE),
  SOL_ID          VARCHAR2(8 BYTE),
  FIRST_NAME      VARCHAR2(25 BYTE),
  MIDDLE_NAME     VARCHAR2(25 BYTE),
  SUR_NAME        VARCHAR2(25 BYTE),
  GENDER          VARCHAR2(8 BYTE),
  ADDRESS         VARCHAR2(180 BYTE),
  BANK_ID         VARCHAR2(8 BYTE),
  DATE_OF_BIRTH   DATE,
  CIF_ID          VARCHAR2(16 BYTE),
  FORACID         VARCHAR2(16 BYTE),
  OTHERS          VARCHAR2(80 BYTE),
  ERROR_CODE      VARCHAR2(500 BYTE),
  SCHM_CODE       VARCHAR2(10 BYTE)
);




GRANT SELECT ON CUSTOM.BULK_CIF TO ALLTAB;

GRANT DELETE, INSERT, UPDATE ON CUSTOM.BULK_CIF TO SMBOGORI;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.BULK_CIF TO TBAADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.BULK_CIF TO TBAGEN;
