DROP TABLE CUSTOM.STATEMENTCHRGS CASCADE CONSTRAINTS;

CREATE TABLE CUSTOM.STATEMENTCHRGS
(
  FORACID  VARCHAR2(16 BYTE),
  PAGE     NUMBER(20,4),
  SOL_ID   VARCHAR2(5 BYTE),
  BANK_ID  VARCHAR2(3 BYTE)
);

CREATE INDEX CUSTOM.IDX_C_STAT_FORACID ON CUSTOM.STATEMENTCHRGS
(FORACID, BANK_ID);

DROP SYNONYM CUSTOM.C_STAT;

CREATE SYNONYM CUSTOM.C_STAT FOR CUSTOM.STATEMENTCHRGS;



GRANT SELECT ON CUSTOM.STATEMENTCHRGS TO ALLTAB;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.STATEMENTCHRGS TO TBAADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.STATEMENTCHRGS TO TBAGEN;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.STATEMENTCHRGS TO TBAUTIL;


