#!/bin/bash

# Export the Jasypt secret key as an environment variable
export JASYPT_ENCRYPTOR_PASSWORD="#{JASYPT-ENCRYPTOR-PASSWORD}#"
export CD_SPRING_DATASOURCE_URL="#{CD-SPRING-DATASOURCE-URL}#"
export CD_SPRING_DATASOURCE_USERNAME="#{CD-SPRING-DATASOURCE-USERNAME}#"
export CD_SPRING_DATASOURCE_PASSWORD="#{SPRING-DATASOURCE-PASSWORD}#"

export CD_AIRTEL_B2C_CONSUMERKEY="#{CD-AIRTEL-B2C-CONSUMERKEY}#"
export CD_AIRTEL_B2C_CONSUMERSECRET="#{CD-AIRTEL-B2C-CONSUMERSECRET}#"
export CD_AIRTEL_B2C_KYC_URL="https://openapiuat.airtel.africa/standard/v1/users"
export CD_AIRTEL_B2C_DISBURSEMENT_URL="https://openapiuat.airtel.africa/bank-to-wallet/v1/payments/"
export CD_AIRTEL_B2C_TOKEN_URL="https://openapiuat.airtel.africa/auth/oauth2/token"
export CD_AIRTEL_B2C_STATUS_CHECK_URL="https://openapiuat.airtel.africa/bank-to-wallet/v1/payments"
export CD_AIRTEL_B2C_HOST_HEADER="openapiuat.airtel.africa"

export CD_AIRTEL_FLOAT_PURCHASE_CONSUMERKEY="#{CD-AIRTEL-FLOAT-PURCHASE-CONSUMERKEY}#"
export CD_AIRTEL_FLOAT_PURCHASE_CONSUMERSECRET="#{CD-AIRTEL-FLOAT-PURCHASE-CONSUMERSECRET}#"
export CD_AIRTEL_FLOAT_PURCHASE_KYC_URL="https://openapiuat.airtel.africa/standard/v1/users"
export CD_AIRTEL_FLOAT_PURCHASE_DISBURSEMENT_URL="https://openapiuat.airtel.africa/allocation"
export CD_AIRTEL_FLOAT_PURCHASE_TOKEN_URL="https://openapiuat.airtel.africa/auth/oauth2/token"
export CD_AIRTEL_FLOAT_PURCHASE_STATUS_CHECK_URL="https://openapiuat.airtel.africa/allocation/txn/status"

export CD_AIRTEL_AIRTIME_PURCHASE_REQUEST_URL="http://localhost:8086/airtime/buy"
export CD_AIRTEL_AIRTIME_PURCHASE_PIN="#{CD-AIRTEL-AIRTIME-PURCHASE-PIN}#"
export CD_AIRTEL_AIRTIME_PURCHASE_CHANNEL_MSISDN="#{CD-AIRTEL-AIRTIME-PURCHASE-CHANNEL-MSISDN}#"
export CD_AIRTEL_AIRTIME_PURCHASE_PASSWORD="#{CD-AIRTEL-AIRTIME-PURCHASE-PASSWORD}#"
export CD_AIRTEL_AIRTIME_PURCHASE_EXTCODE="#{CD-AIRTEL-AIRTIME-PURCHASE-EXTCODE}#"
export CD_AIRTEL_AIRTIME_PURCHASE_LOGINID="#{CD-AIRTEL-AIRTIME-PURCHASE-LOGINID}#"

export CD_AIRTEL_AIRTIME_PURCHASE_URL_LOGIN="EQUITY"
export CD_AIRTEL_AIRTIME_PURCHASE_URL_PASSWORD="12345"
export CD_AIRTEL_AIRTIME_PURCHASE_REQUEST_GATEWAY_CODE="UAT"
export CD_AIRTEL_AIRTIME_PURCHASE_URL_REQUEST_GATEWAY_TYPE="EXTGW"
export CD_AIRTEL_AIRTIME_PURCHASE_URL_SOURCE_TYPE="EXTGW"
export CD_AIRTEL_AIRTIME_PURCHASE_URL_SERVICE_PORT="190"


export CD_AIRTEL_OPENAPI_ENCRYPTION_KEY="#{CD-AIRTEL-OPENAPI-ENCRYPTION-KEY}#"


export KE_AIRTEL_FLOAT_PURCHASE_CONSUMERKEY="2adf76ac-2354-46d1-b393-060d7ac63b08"
export KE_AIRTEL_FLOAT_PURCHASE_CONSUMERSECRET="5b4605c8-4703-4834-aadd-dece5867c0b8"
export KE_AIRTEL_FLOAT_PURCHASE_KYC_URL="https://openapiuat.airtel.africa/standard/v1/users"
export KE_AIRTEL_FLOAT_PURCHASE_DISBURSEMENT_URL="https://openapiuat.airtel.africa/allocation"
export KE_AIRTEL_FLOAT_PURCHASE_TOKEN_URL="https://openapiuat.airtel.africa/auth/oauth2/token"
export KE_AIRTEL_FLOAT_PURCHASE_STATUS_CHECK_URL="https://openapiuat.airtel.africa/allocation/txn/status"
export KE_AIRTEL_B2C_HOST_HEADER="openapiuat.airtel.africa"
export KE_AIRTEL_OPENAPI_ENCRYPTION_KEY="#{CD-AIRTEL-OPENAPI-ENCRYPTION-KEY}#"


# Print a confirmation message
echo "Environment variables have been set."