<%-- /*=============================================================*
# Source Name           : package_det_ginc.jsp
# Menu Option           : CGSTNST
# Author                : SANJANA
# Date                  : 12-JUL-2019
# Module                : CGSTNST CUSTOM  CHARGE SET UP MENU
#=============================================================**/--%>
<%--
//Generated by Customization WB Generator
//Do not edit this file directly.
//Instead, modify the properties in the tool and regenerate.
--%>

<%@ page import="applcommon.ParseValue" %>
<%@ page import="com.infy.bbu.jsputil.*"%>
<%@ taglib uri="taglib.tld" prefix="arjsp" %>
<%@ page import="FABCommon.SecurityInfo70"%>
<arjsp:init groupName="Customize" isEntryPoint="false" />


<%
	String sProfileId = ProfilesManager.getProfileInSession(session);
	String sSubGrpName = (String)ARJspCurr.getInput("subGroupName","");
	String sGrpName = ARJspCurr.getCurrentGroup();
	String pageName = (String)ARJspCurr.getInput("jspName",""); 
	String sPopUpExceptionWindow = (String)ARJspCurr.getInput(sGrpName+".PopUpExceptionWindow" ,"false");
	String sReferralMode = (String)ARJspCurr.getInput("refSubMode" ,"");
	ARJspCurr.setInput(sGrpName+".PopUpExceptionWindow","false");
	SecurityInfo70 securityInfo = (SecurityInfo70)session.getAttribute("FinUserInfo");
%>
<script>

	var sPopUpExceptionWindow = '<%=sPopUpExceptionWindow%>';
	var sReferralMode = '<%=sReferralMode%>' ;
	var subGroupName = '<%=ParseValue.checkString(ARJspCurr.getInput("subGroupName",""))%>';
	var varValue = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".varValue",""))%>';
	var delFlag = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".delFlag",""))%>';
	var funcCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".funcCode",""))%>';
	var contextSolId = '<%= ParseValue.checkString(securityInfo.contextSolId)%>';
	var homeCrncyCode = '<%= ParseValue.checkString(securityInfo.homeCrncyCode)%>';	
	var packageCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".packageCode",""))%>';
	var packageDesc = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".packageDesc",""))%>';
	var product1 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".product1",""))%>';
	var product2 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".product2",""))%>';
	var product3 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".product3",""))%>';
	var product4 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".product4",""))%>';
	var BODDate = '<%= ParseValue.checkString((securityInfo.bodDate).substring(0,10))%>';
	var product5 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".product5",""))%>';
	var product6 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".product6",""))%>';
        var product7 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".product7",""))%>';
        var product8 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".product8",""))%>';
        var product9 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".product9",""))%>';
	var product10 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".product10",""))%>';
	var packagePrising = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".packagePrising",""))%>';
	var crncy = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".crncy",""))%>';	
	var solId = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".solId",""))%>';	
	var schmCodeDesc1 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".schmCodeDesc1",""))%>';	
	var schmCodeDesc2 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".schmCodeDesc2",""))%>';
	var schmCodeDesc3 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".schmCodeDesc3",""))%>';
        var schmCodeDesc4 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".schmCodeDesc4",""))%>';
	var schmCodeDesc5 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".schmCodeDesc5",""))%>';
        var schmCodeDesc6 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".schmCodeDesc6",""))%>';
	var schmCodeDesc7 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".schmCodeDesc7",""))%>';
        var schmCodeDesc8 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".schmCodeDesc8",""))%>';
	var schmCodeDesc9 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".schmCodeDesc9",""))%>';
        var schmCodeDesc10 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".schmCodeDesc10",""))%>';
	var schmCode1 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".schmCode1",""))%>';	
	var schmCode2 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".schmCode2",""))%>';
	var schmCode3 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".schmCode3",""))%>';
        var schmCode4 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".schmCode4",""))%>';
	var schmCode5 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".schmCode5",""))%>';
        var schmCode6 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".schmCode6",""))%>';
	var schmCode7 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".schmCode7",""))%>';
        var schmCode8 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".schmCode8",""))%>';
	var schmCode9 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".schmCode9",""))%>';
        var schmCode10 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".schmCode10",""))%>';	
	var value1 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".value1",""))%>';
        var value2 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".value2",""))%>';	
	var tmpCrncyCode = 'homeCrncyCode';
</script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showSchmCodes.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showSearcher.js",sProfileId)%>" > </script>
<script>
	printBlock();
	printFooterBlock();
</script>


