<%--
//Generated by Customization WB Generator
//Do not edit this file directly.
//Instead, modify the properties in the tool and regenerate.
--%>

<%@ page import="applcommon.ParseValue" %>
<%@ page import="com.infy.bbu.jsputil.*"%>
<%@ page import="java.util.Vector"%>
<%@ page import="applcommon.AppProperties" %>
<%@ taglib uri="taglib.tld" prefix="arjsp" %>
<arjsp:init groupName="Customize" isEntryPoint="false" />

<%
	String sProfileId = ProfilesManager.getProfileInSession(session);
	String sSubGrpName = (String)ARJspCurr.getInput("subGroupName","");
	String sGrpName = ARJspCurr.getCurrentGroup();
	String pageName = (String)ARJspCurr.getInput("jspName","");
	String sPopUpExceptionWindow = (String)ARJspCurr.getInput(sGrpName+".PopUpExceptionWindow" ,"false");
	String sReferralMode = (String)ARJspCurr.getInput("refSubMode" ,"");
	ARJspCurr.setInput(sGrpName+".PopUpExceptionWindow","false");
	
	String fromAppId = AppProperties.getProperty("CORE_Server");
	String svsServer = AppProperties.getProperty("SVS_Server");
	String svs_flag = AppProperties.getProperty("SVS_FLAG");
	String SVS_Verfication_Mandatory = AppProperties.getProperty("SVS_Verfication_Mandatory_DRTRAN");


%>
<script>

	var sPopUpExceptionWindow = '<%=ParseValue.checkString(sPopUpExceptionWindow)%>';
	var sReferralMode = '<%=ParseValue.checkString(sReferralMode)%>';
	var subGroupName = '<%=ParseValue.checkString(ARJspCurr.getInput("subGroupName",""))%>';
	var drAcctNum = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".drAcctNum",""))%>';
	var acctEntityId = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".acctEntityId",""))%>';
	var acctSolId = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".acctSolId",""))%>';
	var acctCrncy = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".acctCrncy",""))%>';
	var acctName = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".acctName",""))%>';
	var opAcctNum = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".crAcctNum",""))%>';
    	var opAcctEntityId = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".crAcctEntityId",""))%>';
	var opAcctSolId = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".crAcctSolId",""))%>';
	var opAcctCrncy = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".crAcctCrncy",""))%>';
	var opAcctName = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".crAcctName",""))%>';
	var PLAcctNum = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".taxAcctNum",""))%>';
	var PLAcctEntityId = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".taxAcctEntityId",""))%>';
	var PLAcctSolId = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".taxAcctSolId",""))%>';
	var PLAcctCrncy = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".taxAcctCrncy",""))%>';
	var PLAcctName = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".taxAcctName",""))%>';
	var IntrstAmt = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".IntrstAmt",""))%>';
	
</script>

<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("common_functions.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/custom/javascripts/<%=VRPKeys.getFile("custom_functions.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/custom/javascripts/<%=VRPKeys.getCustomFile("cust_fetch_list.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getCustomFile("showAccountIdList.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showRateCodes.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showSearcher.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showRefCode.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("cust_common_functions.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("cust_pre_evt.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("cust_post_evt.js",sProfileId)%>"></script>




<script language="JavaScript">
</script>

<script language="JavaScript">
	printBlock();
	printFooterBlock();
</script>

