<%--
//Generated by Customization WB Generator
//Do not edit this file directly.
//Instead, modify the properties in the tool and regenerate.
--%>

<%@ page import="applcommon.ParseValue" %>
<%@ page import="com.infy.bbu.jsputil.*"%>
<%@ page import="java.util.Vector"%>
<%@ taglib uri="taglib.tld" prefix="arjsp" %>
<arjsp:init groupName="Customize" isEntryPoint="false" />

<%
	String sProfileId = ProfilesManager.getProfileInSession(session);
	String sSubGrpName = (String)ARJspCurr.getInput("subGroupName","");
	String sGrpName = ARJspCurr.getCurrentGroup();
	String pageName = (String)ARJspCurr.getInput("jspName","");
	String sPopUpExceptionWindow = (String)ARJspCurr.getInput(sGrpName+".PopUpExceptionWindow" ,"false");
	String sReferralMode = (String)ARJspCurr.getInput("refSubMode" ,"");
	ARJspCurr.setInput(sGrpName+".PopUpExceptionWindow","false");

%>
<script>

	var sPopUpExceptionWindow = '<%=sPopUpExceptionWindow%>';
	var sReferralMode = '<%=sReferralMode%>' ;

	var subGroupName = '<%=ParseValue.checkString(ARJspCurr.getInput("subGroupName",""))%>';
	var funcCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".funcCode",""))%>';
	var funcCodeV = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".funcCodeV",""))%>';
	var refNum = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".refNum",""))%>';
	var AcctNum = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".AcctNum",""))%>';
	var critAcctName = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".critAcctName",""))%>';
	var critSolId = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".critSolId",""))%>';
	var critAcctCrncy = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".critAcctCrncy",""))%>';
	var billAcctId = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".billAcctId",""))%>';
	var billerId = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".billerId",""))%>';
	var payRefNum = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".payRefNum",""))%>';
	var payAcctId = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".payAcctId",""))%>';
	var solId = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".solId",""))%>';
	var crncyCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".crncyCode",""))%>';
	var acctName = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".acctName",""))%>';
	var typOfServ = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".typOfServ",""))%>';
	var tmpAmtField = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".tmpAmtField",""))%>';
	var valType = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".valType",""))%>';
	var billerCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".billerCode",""))%>';

</script>

<script language="javascript" src="../Renderer/custom/javascripts/<%=VRPKeys.getFile("custom_functions.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("cust_pre_evt.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("cust_post_evt.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("common_functions.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("custom_common_functions.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showAccountIdList.js",sProfileId)%>"></script>

<script language="JavaScript">
	printBlock();
	printFooterBlock();
</script>

