trigger:
  - develop
  - release
  - main

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'crequitydevtest'
  DEVImageRepository: 'world-remit-business-service/build-dev'
  UATImageRepository: 'world-remit-business-service/build-uat'
  PRODImageRepository: 'world-remit-business-service/build-prod'
  containerRegistry: 'crequitydevtest.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
  - stage: BuildDEV
    condition: and(always(), contains(variables['Build.SourceBranch'], 'refs/heads/develop'))
    displayName: DEV
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              options: '-Dspring.profiles.active=$(DEV_SPRING_PROFILES_ACTIVE)'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              javaHomeOption: 'JDKVersion'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false
          - task: replacetokens@3
            inputs:
              targetFiles: '**/*.yaml'
              encoding: 'auto'
              writeBOM: true
              actionOnMissing: 'warn'
              keepToken: false
              tokenPrefix: '#{'
              tokenSuffix: '}#'
          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(system.defaultworkingdirectory)'
              Contents: |
                **/*.jar
                **/*.yaml
              TargetFolder: '$(build.artifactstagingdirectory)'
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'dev_drop'
              publishLocation: 'Container'
          - task: Docker@2
            displayName: Build and push an image to container registry
            inputs:
              command: buildAndPush
              repository: $(DEVImageRepository)
              dockerfile: $(dockerfilePath)
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: |
                $(tag)
                latest

  - stage: BuildUAT
    condition: and(always(), contains(variables['Build.SourceBranch'], 'refs/heads/release'))
    displayName: UAT
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              options: '-Dspring.profiles.active=$(UAT_SPRING_PROFILES_ACTIVE)'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              javaHomeOption: 'JDKVersion'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false
          - task: replacetokens@3
            inputs:
              targetFiles: '**/*.yaml'
              encoding: 'auto'
              writeBOM: true
              actionOnMissing: 'warn'
              keepToken: false
              tokenPrefix: '#{'
              tokenSuffix: '}#'
          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(system.defaultworkingdirectory)'
              Contents: |
                **/*.jar
                **/*.yaml
              TargetFolder: '$(build.artifactstagingdirectory)'
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'uat_drop'
              publishLocation: 'Container'
          - task: Docker@2
            displayName: Build and push an image to container registry
            inputs:
              command: buildAndPush
              repository: $(UATImageRepository)
              dockerfile: $(dockerfilePath)
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: |
                $(tag)
                latest
				
  - stage: BuildPROD
    condition: and(always(), contains(variables['Build.SourceBranch'], 'refs/heads/main'))
    displayName: PROD
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              options: '-Dspring.profiles.active=$(PROD_SPRING_PROFILES_ACTIVE)'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              javaHomeOption: 'JDKVersion'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false
          - task: replacetokens@3
            inputs:
              targetFiles: '**/*.yaml'
              encoding: 'auto'
              writeBOM: true
              actionOnMissing: 'warn'
              keepToken: false
              tokenPrefix: '#{'
              tokenSuffix: '}#'
          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(system.defaultworkingdirectory)'
              Contents: |
                **/*.jar
                **/*.yaml
              TargetFolder: '$(build.artifactstagingdirectory)'
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'prod_drop'
              publishLocation: 'Container'
          - task: Docker@2
            displayName: Build and push an image to container registry
            inputs:
              command: buildAndPush
              repository: $(PRODImageRepository)
              dockerfile: $(dockerfilePath)
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: |
                $(tag)
                latest
