apiVersion: apps/v1
kind: Deployment
metadata:
    name: world-remit-business-service
spec:
    replicas: 1
    minReadySeconds: 10
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxUnavailable: 1
            maxSurge: 1
    template:
        metadata:
            name: world-remit-business-service
            labels:
                app: world-remit-business-service
        spec:
            containers:
                - name: world-remit-business-service
                  image: crequitydevtest.azurecr.io/world-remit-business-service/build-uat:#{Build.BuildId}#
                  imagePullPolicy: Always
                  resources:
                      requests:
                          memory: "512Mi"
                          cpu: "250m"
                      limits:
                          memory: "1024Mi"
                          cpu: "500m"
                  ports:
                      - containerPort: 8701
                  env:
                      - name: SPRING_PROFILE
                        value: uat

    selector:
        matchLabels:
            app: world-remit-business-service

---

apiVersion: v1
kind: Service
metadata:
    name: world-remit-business-service-service
    annotations:
        service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
    type: LoadBalancer
    ports:
        - port: 8701
    selector:
        app: world-remit-business-service

