DROP TABLE CUSTOM.CUST_UAD_MAIN_TABLE

CREATE TABLE CUSTOM.CUST_UAD_MAIN_TABLE
(
    USER_ID        VARCHAR2(30 Byte),
    ACTUAL_ROLE_ID    VARCHAR2(30 Byte),
    TEMPORARY_ROLE_ID    VARCHAR2(30 Byte),
    EXPIRY_DATE         DATE,
    ENTITY_CRE_FLG      CHAR(1 Byte),
    DEL_FLG        CHAR(1 Byte),
    RCRE_USER_ID    VARCHAR2(15 Byte),
    RCRE_TIME           DATE,
    LCHG_USER_ID        VARCHAR2(15 Byte),
    LCHG_TIME           DATE,
    BANK_ID        VARCHAR2(8 Char)
)
TABLESPACE CUSTOM_TBLS
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;

DROP INDEX CUSTOM.C_UAD_IDX;

CREATE UNIQUE INDEX CUSTOM.C_UAD_IDX on CUSTOM.CUST_UAD_MAIN_TABLE(USER_ID) TABLESPACE CUSTOM_IDXSPACE;

DROP PUBLIC SYNONYM C_UAD;

CREATE OR REPLACE SYNONYM custom.C_UAD for custom.CUST_UAD_MAIN_TABLE;

CREATE OR REPLACE SYNONYM tbagen.C_UAD for custom.CUST_UAD_MAIN_TABLE;

CREATE OR REPLACE SYNONYM tbautil.C_UAD for custom.CUST_UAD_MAIN_TABLE;

CREATE OR REPLACE SYNONYM tbaadm.C_UAD for custom.CUST_UAD_MAIN_TABLE;

GRANT ALL ON custom.CUST_UAD_MAIN_TABLE TO TBAGEN,TBAUTIL,TBAADM;



