DROP TABLE CUSTOM.CUST_MAIN_DENOM_MASTER CASCADE CONSTRAINTS;

CREATE TABLE CUSTOM.CUST_MAIN_DENOM_MASTER
(
  SOL_ID        VARCHAR2(20 BYTE)               NOT NULL,
  CRNCY_CODE    VARCHAR2(5 BYTE)                NOT NULL,
  DENOM_IND     CHAR(1 BYTE)                    NOT NULL,
  DENOM_VALUE   NUMBER(10,2)                    NOT NULL,
  RCRE_USER_ID  VARCHAR2(15 BYTE)               NOT NULL,
  RCRE_TIME     DATE                            NOT NULL,
  LCHG_USER_ID  VARCHAR2(15 BYTE)               NOT NULL,
  LCHG_TIME     DATE                            NOT NULL,
  DEL_FLG       CHAR(1 BYTE)                    NOT NULL,
  BANK_ID       VARCHAR2(8 BYTE)
);

CREATE UNIQUE INDEX CUSTOM.IDX_CUST_MAIN_DENOM_MASTER ON CUSTOM.CUST_MAIN_DENOM_MASTER
(CRNCY_CODE, DENOM_IND, DENOM_VALUE, BANK_ID);

DROP SYNONYM CUSTOM.C_MDNM;

CREATE SYNONYM CUSTOM.C_MDNM FOR CUSTOM.CUST_MAIN_DENOM_MASTER;

DROP SYNONYM TBAADM.C_MDNM;

CREATE SYNONYM TBAADM.C_MDNM FOR CUSTOM.CUST_MAIN_DENOM_MASTER;

DROP SYNONYM TBAGEN.C_MDNM;

CREATE SYNONYM TBAGEN.C_MDNM FOR CUSTOM.CUST_MAIN_DENOM_MASTER;

DROP SYNONYM TBAUTIL.C_MDNM;

CREATE SYNONYM TBAUTIL.C_MDNM FOR CUSTOM.CUST_MAIN_DENOM_MASTER;

GRANT SELECT ON CUSTOM.CUST_MAIN_DENOM_MASTER TO ALLTAB;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.CUST_MAIN_DENOM_MASTER TO TBAADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.CUST_MAIN_DENOM_MASTER TO TBAGEN;

GRANT SELECT ON CUSTOM.CUST_MAIN_DENOM_MASTER TO TBAUTIL;
