CREATE TABLE CUSTOM.CUST_CHQ_BOOK_MOD_TABLE
(
  BEGIN_CHQ_NUM      VARCHAR2(8 BYTE),
  ACID               VARCHAR2(11 BYTE),
  FORACID            VARCHAR2(16 BYTE),
  BEGIN_CHQ_ALPHA    VARCHAR2(6 BYTE),
  INST_TYPE          VARCHAR2(5 BYTE),
  ENTITY_CRE_FLG     CHAR(1 BYTE),
  DEL_FLG            CHAR(1 BYTE),
  CHQ_ISSU_DATE      DATE,
  CHQ_NUM_OF_LVS     NUMBER(4),
  CHQ_LVS_STAT       VARCHAR2(100 BYTE),
  NUM_PAID           NUMBER(3),
  NUM_UNUSED         NUMBER(3),
  NUM_STOPED         NUMBER(3),
  NUM_CAUTIONED      NUMBER(3),
  NUM_DESTROYED      NUMBER(3),
  FUNCTION           CHAR(1 BYTE),
  INP_BEGIN_CHQ_NUM  VARCHAR2(8 BYTE),
  INP_NUM_OF_LVS     VARCHAR2(4 BYTE),
  RCRE_USER_ID       VARCHAR2(15 BYTE),
  RCRE_TIME          DATE,
  LCHG_USER_ID       VARCHAR2(15 BYTE),
  LCHG_TIME          DATE,
  BANK_ID            VARCHAR2(5 BYTE)
);


CREATE INDEX CUSTOM.IDX_C_CBT_MOD_CHQ_ISSU_DATE ON CUSTOM.CUST_CHQ_BOOK_MOD_TABLE
(ACID, FORACID, INST_TYPE, BANK_ID);


CREATE SYNONYM CUSTOM.C_CBT_MOD FOR CUSTOM.CUST_CHQ_BOOK_MOD_TABLE;


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON CUSTOM.CUST_CHQ_BOOK_MOD_TABLE TO TBAADM;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON CUSTOM.CUST_CHQ_BOOK_MOD_TABLE TO TBAGEN;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON CUSTOM.CUST_CHQ_BOOK_MOD_TABLE TO TBAUTIL;
