CREATE TABLE CUSTOM.BCHQ_UPLOAD_TABLE
(
  REQ_ID         VARCHAR2(5 BYTE),
  FORACID        VARCHAR2(16 BYTE),
  BRANCH_CODE    VARCHAR2(6 BYTE),
  BEGIN_CHQ_NUM  VARCHAR2(8 BYTE),
  NUM_OF_CHB     NUMBER(4),
  REQ_STATUS     CHAR(1 BYTE),
  REQ_DATE       DATE,
  DOWNLOAD_ID    VARCHAR2(15 BYTE),
  DOWNLOAD_DATE  DATE,
  AUTH_USER_ID   VARCHAR2(15 BYTE),
  AUTH_TIME      DATE,
  RCRE_USER_ID   VARCHAR2(15 BYTE),
  RCRE_TIME      DATE,
  DEL_FLG        CHAR(1 BYTE),
  BANK_ID        VARCHAR2(8 BYTE)
);


CREATE SYNONYM CUSTOM.C_BCHQ FOR CUSTOM.BCHQ_UPLOAD_TABLE;


GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.BCHQ_UPLOAD_TABLE TO TBAADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.BCHQ_UPLOAD_TABLE TO TBAGEN;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.BCHQ_UPLOAD_TABLE TO TBAUTIL;
