<%--
//Generated by Customization WB Generator
//Do not edit this file directly.
//Instead, modify the properties in the tool and regenerate.
--%>

<%@ page import="applcommon.ParseValue" %>
<%@ page import="com.infy.bbu.jsputil.*"%>
<%@ taglib uri="taglib.tld" prefix="arjsp" %>
<arjsp:init groupName="Customize" isEntryPoint="false" />

<%
	String sProfileId = ProfilesManager.getProfileInSession(session);
	String sSubGrpName = (String)ARJspCurr.getInput("subGroupName","");
	String sGrpName = ARJspCurr.getCurrentGroup();
	String sPopUpExceptionWindow = (String)ARJspCurr.getInput(sGrpName+".PopUpExceptionWindow" ,"false");
	String sReferralMode = (String)ARJspCurr.getInput("refSubMode" ,"");
	ARJspCurr.setInput(sGrpName+".PopUpExceptionWindow","false");

%>
<script>

	var sPopUpExceptionWindow = '<%=sPopUpExceptionWindow%>';
	var sReferralMode = '<%=sReferralMode%>' ;
	var subGroupName = '<%=ParseValue.checkString(ARJspCurr.getInput("subGroupName",""))%>';
	var funcCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".funcCode",""))%>';
	var foracid = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".foracid",""))%>';
	//363800
	var acctname = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".acctname",""))%>';
	//363800
	var regNo = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".regNo",""))%>';
	var stdName = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".stdName",""))%>';

</script>


<script language="javascript" src="../Renderer/javascripts/lists/showAccountIdList.js" > </script>
<script language="javascript" src="../Renderer/custom/javascripts/custom_functions.js"></script>
<script language="javascript" src="../Renderer/custom/javascripts/custom_common_functions.js"></script>
<script language="javascript" src="../Renderer/custom/javascripts/cust_fetch_list.js"></script>

<script language="JavaScript">
	printBlock();
	printFooterBlock();
</script>
