CREATE TABLE custom.C_EQLM
(
ACCT_NO VARCHAR2(16 BYTE),
CRNCY_CODE VARCHAR2(3 BYTE),
SOL_ID VARCHAR2(8 BYTE),
PART_TRAN_TYPE CHAR(1 BYTE),
TRAN_AMT NUMBER(14,2),
TRAN_PARTICULARS VARCHAR2(30 BYTE),
ACCT_RPT_CODE VARCHAR2(5 BYTE),
REF_NUM VARCHAR2(20 BYTE),
TRAN_STATUS VARCHAR2(3 BYTE),
TRAN_ID VARCHAR2(10 BYTE),
TRAN_DATE DATE,
BOD_DATE DATE,
PROCESSED_FLG CHAR(1 BYTE),
BANK_ID	VARCHAR2(10 CHAR)
)
TABLESPACE CUSTOM_TBLS
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            NEXT             496K
            MINEXTENTS       1
            MAXEXTENTS       505
            PCTINCREASE      50
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.C_EQLM TO TBAADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.C_EQLM TO TBAGEN;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.C_EQLM TO TBAUTIL;


