DROP SEQUENCE CUSTOM.MOBEE_PUSH_SMS_SEQUENCE;

CREATE SEQUENCE CUSTOM.MOBEE_PUSH_SMS_SEQUENCE
  START WITH 56580473
  MAXVALUE 99999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


GRANT SELECT ON CUSTOM.MOBEE_PUSH_SMS_SEQUENCE TO TBAADM;

GRANT SELECT ON CUSTOM.MOBEE_PUSH_SMS_SEQUENCE TO TBAGEN;


