DROP TABLE CUSTOM.INTERCOUNTRY_TRANS_TABLE CASCADE CONSTRAINTS;

CREATE TABLE CUSTOM.INTERCOUNTRY_TRANS_TABLE
(
  INIT_SOL_ID            VARCHAR2(8 BYTE),
  SOL_DESC               VARCHAR2(132 BYTE),
  TRAN_DATE              DATE,
  TRAN_ID                VARCHAR2(9 BYTE),
  PART_TRAN_SRL_NUM      VARCHAR2(4 BYTE),
  TRAN_AMT               NUMBER(20,4),
  FEE_AMT                NUMBER(20,4),
  TRAN_TYPE              VARCHAR2(1 BYTE),
  TRAN_SUB_TYPE          VARCHAR2(2 BYTE),
  PART_TRAN_TYPE         VARCHAR2(1 BYTE),
  TRAN_PARTICULAR        VARCHAR2(50 BYTE),
  ENTRY_USER_ID          VARCHAR2(15 BYTE),
  PSTD_USER_ID           VARCHAR2(15 BYTE),
  ENTRY_DATE             DATE,
  PSTD_DATE              DATE,
  FCFORACID              VARCHAR2(20 BYTE),
  FCNAME                 VARCHAR2(30 BYTE),
  RATE                   NUMBER(20,4),
  AMOUNTINFCY            NUMBER(20,4),
  FCCRNCY_CODE           VARCHAR2(5 BYTE),
  STATUS                 VARCHAR2(3 BYTE),
  INT_TRAN_DATE          DATE,
  INT_TRAN_ID            VARCHAR2(9 BYTE),
  INT_PART_TRAN_SRL_NUM  VARCHAR2(4 BYTE),
  COUNTRY_CODE           VARCHAR2(3 BYTE),
  BANK_ID                VARCHAR2(8 CHAR)
);

CREATE INDEX CUSTOM.IDX_C_INIT_SOL_ID ON CUSTOM.INTERCOUNTRY_TRANS_TABLE
(INIT_SOL_ID, BANK_ID);

CREATE INDEX CUSTOM.IDX_C_FCFORACID ON CUSTOM.INTERCOUNTRY_TRANS_TABLE
(FCFORACID, BANK_ID);

CREATE UNIQUE INDEX CUSTOM.CU_INTCNTRY_IDX ON CUSTOM.INTERCOUNTRY_TRANS_TABLE
(COUNTRY_CODE, TRAN_DATE, TRAN_ID, PART_TRAN_SRL_NUM, BANK_ID);



DROP SYNONYM CUSTOM.C_INTERCOUNTRY;

CREATE SYNONYM CUSTOM.C_INTERCOUNTRY FOR CUSTOM.INTERCOUNTRY_TRANS_TABLE;

GRANT SELECT ON CUSTOM.INTERCOUNTRY_TRANS_TABLE TO ALLTAB;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.INTERCOUNTRY_TRANS_TABLE TO TBAADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.INTERCOUNTRY_TRANS_TABLE TO TBAGEN;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.INTERCOUNTRY_TRANS_TABLE TO TBAUTIL;
