DROP TABLE CUSTOM.LMT_TRANSFER_TABLE CASCADE CONSTRAINTS;

CREATE TABLE CUSTOM.LMT_TRANSFER_TABLE
(
  XFR_ID          VARCHAR2(10 CHAR),
  ENTITY_CRE_FLG  CHAR(1 BYTE),
  DEL_FLG         CHAR(1 BYTE),
  XFR_START_DATE  DATE,
  XFR_CRNCY_CODE  VARCHAR2(3 CHAR),
  XFR_LIMIT_AMT   NUMBER(20,4),
  BANK_ID         VARCHAR2(8 CHAR),
  PURPOSE         VARCHAR2(15 CHAR)
);

CREATE UNIQUE INDEX CUSTOM.IDX_LMT_TRANSFER_TABLE ON CUSTOM.LMT_TRANSFER_TABLE
(XFR_ID, BANK_ID);


DROP SYNONYM CUSTOM.LMT;

CREATE SYNONYM CUSTOM.LMT FOR CUSTOM.LMT_TRANSFER_TABLE;

GRANT SELECT ON CUSTOM.LMT_TRANSFER_TABLE TO ALLTAB;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.LMT_TRANSFER_TABLE TO TBAADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.LMT_TRANSFER_TABLE TO TBAGEN;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.LMT_TRANSFER_TABLE TO TBAUTIL;
