DROP TABLE CUSTOM.CUST_INW_REJECT_TABLE CASCADE CONSTRAINTS;

CREATE TABLE CUSTOM.CUST_INW_REJECT_TABLE
(
  SET_NUM           VARCHAR2(12 BYTE),
  SOL_ID            VARCHAR2(8 BYTE),
  ZONE_CODE         VARCHAR2(10 BYTE),
  ZONE_DATE         DATE,
  FORACID           VARCHAR2(16 BYTE),
  INSTNO            VARCHAR2(8 BYTE),
  INSTAMT           NUMBER(20,4),
  REJ_CODE          VARCHAR2(2 BYTE),
  REJ_DATE          DATE,
  VALUE_DATE        DATE,
  DRAWEE_BANK_CODE  VARCHAR2(6 BYTE),
  DRAWEE_BR_CODE    VARCHAR2(6 BYTE),
  DRAWEE_SORT_CODE  VARCHAR2(9 BYTE),
  PRES_BANK_CODE    VARCHAR2(6 BYTE),
  PRES_BR_CODE      VARCHAR2(6 BYTE),
  PRES_SORT_CODE    VARCHAR2(9 BYTE),
  ISS_BANK_CODE     VARCHAR2(6 BYTE),
  ISS_BR_CODE       VARCHAR2(6 BYTE),
  TRAN_RMKS         VARCHAR2(50 BYTE),
  LCHG_USER_ID      VARCHAR2(15 BYTE),
  LCHG_TIME         DATE,
  RCRE_USER_ID      VARCHAR2(15 BYTE),
  RCRE_TIME         DATE,
  ENTITY_CRE_FLG    CHAR(1 BYTE),
  DEL_FLG           CHAR(1 BYTE),
  BANK_ID           VARCHAR2(3 BYTE)
);



DROP SYNONYM CUSTOM.C_IRT;

CREATE SYNONYM CUSTOM.C_IRT FOR CUSTOM.CUST_INW_REJECT_TABLE;

GRANT SELECT ON CUSTOM.CUST_INW_REJECT_TABLE TO ALLTAB;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.CUST_INW_REJECT_TABLE TO TBAADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.CUST_INW_REJECT_TABLE TO TBAGEN;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.CUST_INW_REJECT_TABLE TO TBAUTIL;
