DROP TABLE CUSTOM.CUST_DENOM_MASTER_CR_TMP CASCADE CONSTRAINTS;

CREATE TABLE CUSTOM.CUST_DENOM_MASTER_CR_TMP
(
  SOL_ID        VARCHAR2(20 BYTE)               NOT NULL,
  CRNCY_CODE    VARCHAR2(5 BYTE)                NOT NULL,
  DENOM_IND     CHAR(1 BYTE)                    NOT NULL,
  DENOM_VALUE   NUMBER(10,2)                    NOT NULL,
  DENOM_COUNT   NUMBER(20),
  TELLER_ID     VARCHAR2(20 BYTE),
  RCRE_USER_ID  VARCHAR2(15 BYTE)               NOT NULL,
  RCRE_TIME     DATE                            NOT NULL,
  LCHG_USER_ID  VARCHAR2(15 BYTE)               NOT NULL,
  LCHG_TIME     DATE                            NOT NULL,
  DEL_FLG       CHAR(1 BYTE)                    NOT NULL,
  BANK_ID       VARCHAR2(8 CHAR)
);

CREATE UNIQUE INDEX CUSTOM.IDX_C_DENM_CR ON CUSTOM.CUST_DENOM_MASTER_CR_TMP
(SOL_ID, CRNCY_CODE, DENOM_IND, DENOM_VALUE, TELLER_ID, 
BANK_ID);


DROP SYNONYM CUSTOM.C_DENM_CR;

CREATE SYNONYM CUSTOM.C_DENM_CR FOR CUSTOM.CUST_DENOM_MASTER_CR_TMP;

DROP SYNONYM TBAADM.C_DENM_CR;

CREATE SYNONYM TBAADM.C_DENM_CR FOR CUSTOM.CUST_DENOM_MASTER_CR_TMP;

DROP SYNONYM TBAGEN.C_DENM_CR;

CREATE SYNONYM TBAGEN.C_DENM_CR FOR CUSTOM.CUST_DENOM_MASTER_CR_TMP;

DROP SYNONYM TBAUTIL.C_DENM_CR;

CREATE SYNONYM TBAUTIL.C_DENM_CR FOR CUSTOM.CUST_DENOM_MASTER_CR_TMP;

GRANT SELECT ON CUSTOM.CUST_DENOM_MASTER_CR_TMP TO ALLTAB;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.CUST_DENOM_MASTER_CR_TMP TO TBAADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.CUST_DENOM_MASTER_CR_TMP TO TBAGEN;

GRANT SELECT ON CUSTOM.CUST_DENOM_MASTER_CR_TMP TO TBAUTIL;
