SET DEFINE OFF;
Insert into TBAADM.TPYT
   (TEMPLATE_TYPE, FIELD_NAME, DEL_FLG, LITERAL_CODE, DATA_SIZE, DATA_TYPE, DISPLAY_TYPE, MULTI_BYTE, JUSTIFICATION, DISPLAY_SIZE, DISPLAY_LENGTH, INDEX_ORDER, STYLE, ENABLED, MANDATORY, LCHG_USER_ID, LCHG_TIME, RCRE_USER_ID, RCRE_TIME, TS_CNT, BANK_ID)
 Values
   ('XYZ', 'TEST', 'N', 'TEST NAME', 10, 'date', 'TX', 'Y', 'L', 10, 10, 0, 'text', 'Y', 'Y', 'SYSTEM', TO_DATE('07/31/2013 15:46:13', 'MM/DD/YYYY HH24:MI:SS'), 'SYSTEM', TO_DATE('07/31/2013 15:46:13', 'MM/DD/YYYY HH24:MI:SS'), 1, '54');
COMMIT;
