<%--
//Generated by Customization WB Generator
//Do not edit this file directly.
//Instead, modify the properties in the tool and regenerate.
--%>

<%@ page import="applcommon.ParseValue" %>
<%@ page import="com.infy.bbu.jsputil.*"%>
<%@ taglib uri="taglib.tld" prefix="arjsp" %>
<arjsp:init groupName="Customize" isEntryPoint="false" />

<%
	String sProfileId = ProfilesManager.getProfileInSession(session);
	String sSubGrpName = (String)ARJspCurr.getInput("subGroupName","");
	String sGrpName = ARJspCurr.getCurrentGroup();
	String sPopUpExceptionWindow = (String)ARJspCurr.getInput(sGrpName+".PopUpExceptionWindow" ,"false");
	String sReferralMode = (String)ARJspCurr.getInput("refSubMode" ,"");
	ARJspCurr.setInput(sGrpName+".PopUpExceptionWindow","false");

%>
<script>

	var sPopUpExceptionWindow = '<%=sPopUpExceptionWindow%>';
	var sReferralMode = '<%=sReferralMode%>' ;

	var subGroupName = '<%=ParseValue.checkString(ARJspCurr.getInput("subGroupName",""))%>';
	var funcCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".funcCode",""))%>';
	var acctNo = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".acctNo",""))%>';
	var contractId = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".contractId",""))%>';
	var acctname = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".acctname",""))%>';
	var solId = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".solId",""))%>';
	var schmCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".schmCode",""))%>';
	var minAmount = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".minAmount",""))%>';
	var maxAmount = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".maxAmount",""))%>';
	var maxContrctPeriod = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".maxContrctPeriod",""))%>';
	var crncyCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".crncyCode",""))%>';
	var contrctAmt = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".contrctAmt",""))%>';
	var contractPeriod = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".contractPeriod",""))%>';
	var charges = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".charges",""))%>';
	var remarks = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".remarks",""))%>';
	var funcCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".funcCode",""))%>';
	var creDateValue = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".creDateValue",""))%>';
	
</script>



<script language="JavaScript">
	printBlock();
	printFooterBlock();
</script>

