## Enabling H2 Console
#spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
#spring.datasource.url=jdbc:sqlserver://sql-omnichannel-uat-001.database.windows.net:1433;database=imt-hub;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
#spring.datasource.username=sql-imt-wr@sql-omnichannel-uat-001
#spring.datasource.password=FaiyqCtXqx85Ad4zohYG
#spring.jpa.show-sql=true
#spring.jpa.hibernate.format_sql = true

#TO DO deactivate this after testing
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.url=jdbc:sqlserver://equity-dev-test-001.database.windows.net:1433;database=worldRemitUatTesting;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.datasource.username=sql-equity-admin
spring.datasource.password=h3xzqqc73Tigy84pEiHQQPQap
spring.jpa.show-sql=true
spring.jpa.hibernate.format_sql=true

## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto=update
spring.datasource.auto-commit=true

#web logging
logging.level.root=INFO
logging.level.root.org.springframework=INFO
logging.level.root.org.apache.kafka=DEBUG
logging.level.org.hibernate=INFO  

#token
app.token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zaWQiOiJjNDAxZmQxMmE3NDA0M2VkYTU2Y2I3NTNlN2M4YmRlMiIsImh0dHA6Ly9qd3Qud29ybGRyZW1pdC5jb20vaXNzdWVyaWQiOiIwNThiODM0MDZmNzI0YTJiOTU3ZDZkNjQzNjVmNzQ5NiIsImh0dHA6Ly9qd3Qud29ybGRyZW1pdC5jb20vbWFjaGluZSI6ImNvcmludC1vcHMtcG9ydGFsLTdjNzlkNWJjODctZHJzd3giLCJleHAiOjE2NzExMTU0MTIsImlzcyI6ImNvcmludC53b3JsZHJlbWl0LmNvbSIsImF1ZCI6InByZCJ9.PSuxul6L31OSlJkpIVWaVAVGoMQ6FM8QXfK3_gMh7Ek

##Kafka configuration
#kafka.topic=transactionStart
#spring.kafka.bootstrap-servers=equity-uat.servicebus.windows.net:9093
#spring.kafka.client-id=transactionGroup
#spring.kafka.properties.sasl.mechanism=PLAIN
#spring.kafka.properties.security.protocol=SASL_SSL
#spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="$ConnectionString" password="Endpoint=sb://equity-uat.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=NGtha8iV72Sw1C5c64GUOynnu+MFlenvYPDcDYLlBEE=";
#spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
#spring.kafka.consumer.auto-offset-reset=earliest

#Kafka configuration
#kafka.topic=transactionStart
spring.kafka.consumer.topic=transactionStart
spring.kafka.bootstrap-servers=equity-preprod.servicebus.windows.net:9093
spring.kafka.client-id=transactionGroup
spring.kafka.properties.sasl.mechanism=PLAIN
spring.kafka.properties.security.protocol=SASL_SSL
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="$ConnectionString" password="Endpoint=sb://equity-preprod.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=yRG/w/+Bre6c7tI3+jPBiST+aBaM9IsK1sqBVlPKXno=";
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.auto-offset-reset=earliest

#Digital Signature and certificate
sender.KeystorePath=src/main/resources/worldRemitSender_keystore.jks
receiver.KeystorePath=src/main/resources/worldRemitReceiver_keystore.jks
password=chengeit
sender.keypair.alias=worldRemitSenderKeyPair
receiver.keypair.alias=worldRemitReceiverKeyPair
keystore.instance=JKS
algorithm=SHA256withRSA

# Specify the instrumentation key of your Application Insights resource.
azure.application-insights.instrumentation-key=486a19ef-1bfb-4080-ae71-e5db46f0b638
# Specify the name of your spring boot application. This can be any logical name you would like to give to your app.