package com.equitybank.imt.worldremit.producer.services.impl;

import com.equitybank.imt.worldremit.producer.dto.TransactionDTO;
import com.equitybank.imt.worldremit.producer.models.domain.Transaction;
import com.equitybank.imt.worldremit.producer.models.http.PropertiesMap;
import com.equitybank.imt.worldremit.producer.models.http.requests.TransactionAwaiting;
import com.equitybank.imt.worldremit.producer.models.http.requests.TransactionChangeStatus;
import com.equitybank.imt.worldremit.producer.models.http.requests.WebHook;
import com.equitybank.imt.worldremit.producer.models.http.responses.Batch;
import com.equitybank.imt.worldremit.producer.models.repository.TransactionDataRepository;
import com.equitybank.imt.worldremit.producer.retrofit.ConsumerService;
import com.equitybank.imt.worldremit.producer.retrofit.WRService;
import com.equitybank.imt.worldremit.producer.services.WRProcessorService;
import com.google.gson.Gson;
import com.microsoft.applicationinsights.TelemetryClient;
import com.microsoft.applicationinsights.telemetry.ExceptionTelemetry;
import com.microsoft.applicationinsights.telemetry.SeverityLevel;
import java.util.HashMap;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.kafka.core.KafkaTemplate;
import org.springframework.kafka.support.SendResult;
import org.springframework.stereotype.Service;
import org.springframework.util.concurrent.ListenableFuture;
import org.springframework.util.concurrent.ListenableFutureCallback;
import retrofit2.Call;
import retrofit2.Callback;
import retrofit2.Response;

import java.util.Optional;
import java.util.UUID;
import javax.persistence.PersistenceException;
import javax.validation.ConstraintViolationException;

@Service
@Slf4j
public class WRProcessorImpl implements WRProcessorService {

    private WRService wrService;
    private ConsumerService consumerService;
    private KafkaTemplate kafkaTemplate;
    private TransactionDataRepository transactionDataRepository;

    @Value("${kafka.topic}")
    private String topic;

    @Autowired
    TelemetryClient telemetryClient;

    @Autowired
    Gson gson;

    HashMap<String, String> telemetryMap = new HashMap<>();

    WRProcessorImpl(WRService wrService, ConsumerService consumerService, KafkaTemplate kafkaTemplate, TransactionDataRepository transactionDataRepository) {
        this.wrService = wrService;
        this.consumerService = consumerService;
        this.kafkaTemplate = kafkaTemplate;
        this.transactionDataRepository = transactionDataRepository;
    }

    /**
     * A batchId is a unique uuid string generated by us (Equity) and sent to WR
     * A correspondentId [maybe null]
     */
    @Override
    public void processTransactionAwaiting(String worldremitaction) {
        if (worldremitaction.equalsIgnoreCase("0")) {
            transactionAwaitingStatus(worldremitaction);
        } else {
//            transactionAwaiting();
            transactionAwaiting(worldremitaction);  //For UAT testing only
        }
    }

    private void transactionAwaitingStatus(String worldremitaction) {
        log.info("TRANSACTIONSTATUS {} RECEIVED", worldremitaction);
        telemetryClient.trackTrace("TRANSACTIONSTATUS {} " + worldremitaction + " RECEIVED", SeverityLevel.Information);

        wrService.getAwaitingTransactionStatus().enqueue(new Callback<Batch>() {
            @Override
            public void onResponse(Call<Batch> call, Response<Batch> response) {
                Batch batch = response.body();
                batch.getContent().forEach(data
                        -> {
                    Transaction transaction = TransactionDTO.createTransactionFromKafka(data.getTransaction());
                    Optional<Transaction> optionalTransaction = transactionDataRepository.findByWorldRemitId(transaction.getWorldRemitId());
                    //These 3 txns below are being exempted to avoid an infite loop from WR system.
                    //WR team refused to remove them from the status awaiting list thus creatng infinite loop.
                    //The txns are not formated corrected and therefore will never be processed successfully in our system
                    //We are exempting them to avoid unnessary consumsion of resources on our end.
                    String reference = data.getTransaction().getReference();
                    String wrid = String.valueOf(data.getTransaction().getWorldRemitId());
                    if (transaction.getReference().equals("795424990001") || transaction.getReference().equals("796096810001") || transaction.getReference().equals("796098400001")) {
                        log.info("Reference: " + transaction.getReference() + " Already exists in our system");
                        telemetryClient.trackTrace("Reference: " + transaction.getReference() + " Already exists in our system", SeverityLevel.Error);
                    } else {
                        TransactionChangeStatus transactionChangeStatus = new TransactionChangeStatus();
                        transactionChangeStatus.setResponseCode("0033");
                        transactionChangeStatus.setResponseMessage("Success");
                        transactionChangeStatus.setTxnReference(transaction.getWrid());
                        PropertiesMap map = new PropertiesMap();
                        transactionChangeStatus.setResponseCode("0033");
                        map.addProperty("responsecode", "0033");
                        map.addProperty("responsemessage", "Transaction not found");
                        map.addProperty("mycustom1", "Transaction with Reference ID [" + transaction.getWorldRemitId() + "] is  not found ");
                        transactionChangeStatus.setProperties(map);
                        if (!optionalTransaction.isPresent()) {
                            setResponse(transaction, transactionChangeStatus);
                        } else {
                            log.info("Sending To Kafka: " + transaction.getWorldRemitId());
                            telemetryClient.trackTrace("Sending To Kafka: " + transaction.getWorldRemitId(), SeverityLevel.Information);
                            sendTransactionToKafka(optionalTransaction.get(), reference, wrid, transactionChangeStatus);
                        }
                    }

                });
            }

            @Override
            public void onFailure(Call<Batch> call, Throwable throwable) {
                log.info("TRANSACTION STATUS ERROR {}", throwable.fillInStackTrace());
                telemetryClient.trackTrace("TRANSACTION STATUS ERROR " + throwable.getMessage(), SeverityLevel.Error);

                ExceptionTelemetry et = new ExceptionTelemetry(throwable);
                telemetryClient.trackException(et);
            }
        });
    }

//    private void transactionAwaiting() {
    private void transactionAwaiting(String worldremitaction) { // for UAT testing only
        Transaction transaction;
        transaction = gson.fromJson(worldremitaction, Transaction.class);
        log.info("worldremitaction ::: " + worldremitaction);
        log.info("Transaction ::: " + transaction);

        transaction.setMessage("Transaction sent to consumer for processing and locked");

        Optional<Transaction> optionalTransaction = transactionDataRepository.findByWorldRemitId(transaction.getWorldRemitId());
        if (!optionalTransaction.isPresent()) {
            transactionDataRepository.save(transaction);
        }
        ListenableFuture<SendResult<String, Transaction>> future = kafkaTemplate.send(topic, transaction);
        future.addCallback(new ListenableFutureCallback<SendResult<String, Transaction>>() {
            Transaction transaction1;

            @Override
            public void onSuccess(SendResult<String, Transaction> result) {
                transaction1 = optionalTransaction.get();
                transaction1.setStatus("PROCESSING");
                transaction1.setMessage("Transaction is being processed");
                log.info(transaction1.getReference() + ": Sent To Kafka Success".toUpperCase());
                telemetryClient.trackTrace(transaction1.getReference() + ": Sent To Kafka Success".toUpperCase(), SeverityLevel.Information);
                transactionDataRepository.save(transaction1);
            }

            @Override
            public void onFailure(Throwable ex) {
                transaction1.setStatus("FAILED");
                transaction1.setMessage("Transaction not written to kafka " + ex.getMessage());
                transactionDataRepository.save(transaction1);
                log.info(transaction1.getReference() + ": Sent To Kafka Fail".toUpperCase());
                telemetryClient.trackTrace(transaction1.getReference() + ": Sent To Kafka Failed".toUpperCase(), SeverityLevel.Information);
            }
        });
        
//        TransactionAwaiting transactionAwaiting = new TransactionAwaiting();
//        String correspondentId = UUID.randomUUID().toString();
//        String batchId = UUID.randomUUID().toString();
//        transactionAwaiting.setLockTransaction(false);
//        transactionAwaiting.setProducts(null);
//        transactionAwaiting.setCorrespondentId("232323");
//        transactionAwaiting.setTop(1);
//        transactionAwaiting.setSkip(0);
//        transactionAwaiting.setBatchId("32452");
//        log.info("Transaction Awaiting Request Body: " + transactionAwaiting);
//        telemetryClient.trackTrace("Transaction Awaiting Request Body: " + transactionAwaiting, SeverityLevel.Information);
//        wrService.getAwaitingTransaction(transactionAwaiting).enqueue(new Callback<Batch>() {
//            @Override
//            public void onResponse(Call<Batch> call, Response<Batch> response) {
//                Batch batch = response.body();
//                log.info("BATCH {}", batch);
//                telemetryClient.trackTrace("BATCH: " + batch, SeverityLevel.Information);
//                batch.getContent().forEach(data
//                        -> {
//                    Transaction transaction = TransactionDTO.createTransactionFromKafka(data.getTransaction());
//                    String reference = data.getTransaction().getReference();
//                    String wrid = String.valueOf(data.getTransaction().getWorldRemitId());
//                    TransactionChangeStatus transactionChangeStatus = new TransactionChangeStatus();
//                    transactionChangeStatus.setResponseCode("1");
//                    transactionChangeStatus.setResponseMessage("Success");
//                    transactionChangeStatus.setTxnReference(reference);
//                    try {
//                        Optional<Transaction> optionalTransaction = transactionDataRepository.findByWorldRemitId(transaction.getWorldRemitId());
//                        if (!optionalTransaction.isPresent()) {
//                            transaction.setStatus("INITIALIZED");
//                            transaction.setMessage("Transaction sent to consumer for processing");
//                            transaction.setUnlockStatus("000");
//                            transactionDataRepository.save(transaction);
//                            sendTransactionToKafka(transaction, reference, wrid, transactionChangeStatus);
//                            log.info("Transaction: " + optionalTransaction.get().getWorldRemitId() + " sent to consumer for processing");
//                            telemetryClient.trackTrace("Transaction: " + optionalTransaction.get().getWorldRemitId() + " sent to consumer for processing", SeverityLevel.Information);
//
//                        } else {
//                            //scenarios locking failed
//                            sendTransactionToKafka(transaction, reference, wrid, transactionChangeStatus);
//                            log.info("DUPLICATE TRANSACTION {}", optionalTransaction.get().getWorldRemitId());
//                            telemetryClient.trackTrace("DUPLICATE TRANSACTION {}" + optionalTransaction.get().getWorldRemitId(), SeverityLevel.Error);
//                        }
//                    } catch (ConstraintViolationException e) {
//                        log.info("TRANSACTION ERROR {} {} {}", e.getMessage(), "ConstraintViolationException occurred while processing transaction reference ", transaction.getReference());
//                        telemetryClient.trackTrace("ConstraintViolationException : " + e.getMessage() + " FOR TRANSACTION " + transaction.getReference(), SeverityLevel.Critical);
//                        telemetryMap.put("reference", transaction.getReference());
//                        telemetryClient.trackException(e, telemetryMap, null);
//
//                    } catch (PersistenceException e) {
//                        log.info("TRANSACTION ERROR {} {} {}", e.getMessage(), "PersistenceException occurred while processing transaction reference ", transaction.getReference());
//                        telemetryClient.trackTrace("PersistenceException : " + e.getMessage() + " FOR TRANSACTION " + transaction.getReference(), SeverityLevel.Critical);
//                        telemetryMap.put("reference", transaction.getReference());
//                        telemetryClient.trackException(e, telemetryMap, null);
//
//                    } catch (Exception e) {
//                        log.info("TRANSACTION ERROR {} {} {}", e.getMessage(), "Exception occurred while processing transaction reference ", transaction.getReference());
//                        telemetryClient.trackTrace("Exception : " + e.getMessage() + " FOR TRANSACTION " + transaction.getReference(), SeverityLevel.Critical);
//                        telemetryMap.put("reference", transaction.getReference());
//                        telemetryClient.trackException(e, telemetryMap, null);
//                    }
//
//                });
//            }
//
//            @Override
//            public void onFailure(Call<Batch> call, Throwable throwable) {
//                log.info("AWAITING ERROR{} ", throwable.getMessage());
//                telemetryClient.trackTrace("AWAITING ERROR: " + throwable.getMessage(), SeverityLevel.Information);
//
//                ExceptionTelemetry et = new ExceptionTelemetry(throwable);
//                telemetryClient.trackException(et);
//            }
//        });
    }

    private void setResponse(Transaction transaction, TransactionChangeStatus transactionChangeStatus) {
        wrService.setTransactionResponse(transaction.getWorldRemitId(), transaction.getWorldRemitId(), transactionChangeStatus).enqueue(new Callback<Void>() {
            @Override
            public void onResponse(Call<Void> call, Response<Void> response) {
                log.info(transaction.getWorldRemitId() + " TRANSACTION RESPONSE {}", response.code());
                telemetryClient.trackTrace(transaction.getWorldRemitId() + " TRANSACTION RESPONSE { " + response.code() + " }", SeverityLevel.Information);
                transaction.setMessage("Transaction: " + transaction.getWorldRemitId() + " In The Transaction Awaiting Status List Does Not Exist In Our Systems");
                transaction.setStatus("FAILED - TRANSACTION NOT FOUND");
                transactionDataRepository.save(transaction);
            }

            @Override
            public void onFailure(Call<Void> call, Throwable throwable) {
                log.info(transaction.getWorldRemitId() + " PUBLISH ERROR {}", throwable.getMessage());
                telemetryClient.trackTrace(transaction.getWorldRemitId() + " PUBLISH ERROR {}" + throwable.getMessage(), SeverityLevel.Error);
                transaction.setMessage("Transaction: " + transaction.getWorldRemitId() + " In The Transaction Awaiting Status List Does Not Exist In Our Systems");
                transaction.setStatus("FAILED - TRANSACTION NOT FOUND");
                transactionDataRepository.save(transaction);

                ExceptionTelemetry et = new ExceptionTelemetry(throwable);
                telemetryClient.trackException(et);
            }
        });
    }

    public void sendTransactionToKafka(Transaction transaction, String reference, String wrid, TransactionChangeStatus transactionChangeStatus) {
        ListenableFuture<SendResult<String, Transaction>> future = kafkaTemplate.send(topic, transaction);
        future.addCallback(
                new ListenableFutureCallback<SendResult<String, Transaction>>() {
            @Override
            public void onSuccess(SendResult<String, Transaction> result) {
                log.info(reference + ": Sending To Kafka Success. Kafka Producer Offset Value: " + result.getRecordMetadata().offset());
                telemetryClient.trackTrace(reference + ": Sending To Kafka Success. Kafka Producer Offset Value: " + result.getRecordMetadata().offset(), SeverityLevel.Information);

                transaction.setStatus("PROCESSING");
                transaction.setMessage("Transaction is being processed. " + "Kafka Producer Offset Value: " + result.getRecordMetadata().offset());
                transactionDataRepository.save(transaction);
                log.info("Locking Transaction " + reference + " on Kafka Success");
                telemetryClient.trackTrace("Locking Transaction " + reference + " on Kafka Success", SeverityLevel.Information);

                lockTransaction(reference, transactionChangeStatus, wrid, transaction);
            }

            @Override
            public void onFailure(Throwable ex) {
                transaction.setStatus("FAILED");
                transaction.setMessage("Transaction not written to kafka " + ex.getMessage());
                transactionDataRepository.save(transaction);
                log.info("Transaction  " + reference + " Not written to kafka. PUBLISH ERROR {}", ex.getMessage());
                telemetryClient.trackTrace("Transaction  " + reference + " Not written to kafka. PUBLISH ERROR {}" + ex.getMessage(), SeverityLevel.Error);

                ExceptionTelemetry et = new ExceptionTelemetry(ex);
                telemetryClient.trackException(et);
            }
        }
        );
        //lock only on receiving ACK

    }

    private void lockTransaction(String reference, TransactionChangeStatus transactionChangeStatus, String wrid, Transaction transaction) {
        PropertiesMap map = new PropertiesMap();
        map.addProperty("responsecode", "1");
        map.addProperty("responsemessage", "Transaction Locked");
        map.addProperty("txnreference", reference);
        map.addProperty("mycustom1", "Lock Transaction");
        transactionChangeStatus.setProperties(map);

        Optional<Transaction> optionalTransactionLock = transactionDataRepository.findByWorldRemitId(reference);
        HashMap<String, Object> lockMap = new HashMap<>();

        //lock transaction once written to kafka
        wrService.setTransactionLocked(wrid, reference, transactionChangeStatus).enqueue(new Callback<Void>() {
            @Override
            public void onResponse(Call<Void> call, Response<Void> response) {
                log.info(reference + " LOCK STATUS: " + response.code() + ". Transaction Change Status: " + transactionChangeStatus + ". Response Body: " + response.toString());
                telemetryClient.trackTrace(reference + " LOCK STATUS: " + response.code() + ". Transaction Change Status: " + transactionChangeStatus + ". Response Body: " + response.toString(), SeverityLevel.Information);

                PropertiesMap locProperties = transactionChangeStatus.getProperties();
                String lockResponse = response.toString();

                if (optionalTransactionLock.isPresent()) {
                    lockMap.put("lockResponseCode", response.code());
                    lockMap.put("locProperties", locProperties);
                    lockMap.put("lockResponse", lockResponse);
                    log.info("lockMap::: " + lockMap);

                    transaction.setLockStatus(lockMap.get("lockResponseCode").toString());
                    transaction.setLockMessage(lockMap.get("locProperties").toString());
                    transaction.setLockResponse(lockMap.get("lockResponse").toString());
                    transactionDataRepository.save(transaction);

                } else {
                    log.info(reference + " Does Not Exist In Transaction Table");
                    telemetryClient.trackTrace(reference + " Does Not Exist In Transaction Table", SeverityLevel.Information);

                }

            }

            @Override
            public void onFailure(Call<Void> call, Throwable throwable) {
                log.info(reference + " LOCK ERROR: " + throwable.getMessage());
                telemetryClient.trackTrace(reference + " LOCK ERROR: " + throwable.getMessage(), SeverityLevel.Error);

                if (optionalTransactionLock.isPresent()) {
                    transaction.setLockStatus("LOCK FAILED");
                    transaction.setLockMessage(throwable.getMessage());
                    transaction.setLockResponse(null);
                    transactionDataRepository.save(transaction);

                } else {
                    log.info(reference + " Does Not Exist In Transaction Table");
                    telemetryClient.trackTrace(reference + " Does Not Exist In Transaction Table", SeverityLevel.Information);

                }

                ExceptionTelemetry et = new ExceptionTelemetry(throwable);
                telemetryClient.trackException(et);
            }
        });
    }

    @Override
    public void createWebHook(WebHook webHook) {
        wrService.createWebhook(webHook).enqueue(new Callback<WebHook>() {
            @Override
            public void onResponse(Call<WebHook> call, Response<WebHook> response) {
                log.info("Creating webhook.... CODE {} BODY {}", response.code(), response.body());
                telemetryClient.trackTrace("Creating webhook.... CODE: " + response.code() + " BODY: " + response.body(), SeverityLevel.Information);
            }

            @Override
            public void onFailure(Call<WebHook> call, Throwable throwable) {
                log.info("Creating webhook .... ERROR {}", throwable.getMessage());
                telemetryClient.trackTrace("Creating webhook .... ERROR " + throwable.getMessage(), SeverityLevel.Error);

                ExceptionTelemetry et = new ExceptionTelemetry(throwable);
                telemetryClient.trackException(et);
            }
        });
    }
}
