//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT004977:"Go",FLT031700:"Share Sell Trading",FLT006657:"Function",FLT031589:"Sol Id",FLT031590:"ID No./Cdsc No.",FLT031587:"Client Name",FLT031596:"Order Id.",FLT025922:"Order Date",FLT004977:"Go",FLT001439:"Clear",FLT031317:"--Select--",FLT031309:"A-Add",FLT031318:"M-Modify",FLT031323:"I-Inquire",FLT031340:"V-Verify",FLT031341:"C-Cancel"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY 
var jspErr={};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);
