spring:
  application:
    name: papss-middleware-service
  datasource:
    url: jdbc:postgresql://localhost:5432/papssdb
    username: papss
    password: fg4rHwc7kkPQcqXv
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: HikariCP
      auto-commit: false
      maximum-pool-size: 10
      minimum-idle: 1
      initialization-fail-timeout: 1

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        boot.allow_jdbc_metadata_access: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        jdbc.batch_size: 50
        order_inserts: true
        order_updates: true
        connection.provider_disables_autocommit: true
    open-in-view: false


logging:
  level:
    com.papss.middleware.service.inbound: ERROR
    org.springframework.web.client.RestTemplate: INFO
    org.apache.http: INFO
    com.papss.middleware: INFO

papss:
  participants:
#    - apiKey: 706b3dac-21ca-4755-906f-841117db9eab
#      country: KE
#      inst_bic: KE0002NP
#      inst_id: KE0002NP
#      salt: supersecretsalt
#      sslKeyAlias: tesn
#      keyStorePath: /Users/test/Documents/projects/papss/papss-middleware-service/src/main/resources/keystore/client.jks
#      keyPass: secure
#      keyStoreType: JKS
#      provider: SunJCE
#    - apiKey: 706b3dac-21ca-4755-906f-841117db9eab
#      country: KE
#      inst_bic: KE1012
#      inst_id: KE1012
#      salt: supersecretsalt
#      sslKeyAlias: tesn
#      keyStorePath: /Users/test/Documents/projects/papss/papss-middleware-service/src/main/resources/keystore/client.jks
#      keyPass: secure
#      keyStoreType: JKS
#      provider: SunJCE
#    - apiKey: 706b3dac-21ca-4755-906f-841117db9eab
#      country: DJ
#      inst_bic: OMGGDJCK
#      inst_id: DJ1009
#      salt: supersecretsalt
#      sslKeyAlias: tesb
#      keyStorePath: /Users/test/Documents/papss/papss-middleware-service/src/main/resources/keystore/client.jks
#      keyPass: secure
#      keyStoreType: JKS
#      provider: SunJCE
#    - apiKey: 706b3dac-21ca-4755-906f-841117db9eab
#      country: AX
#      inst_bic: AFXMAXAD
#      inst_id: AX2001
#      salt: supersecretsalt
#      sslKeyAlias: etz
#      keyStorePath: /Users/test/Documents/papss/papss-middleware-service/src/main/resources/keystore/etz-c1.jks
#      keyPass: secure
#      keyStoreType: JKS
#      provider: SunJCE

    - apiKey: 706b3dac-21ca-4755-906f-841117db9eab
      country: AX
      inst_bic: AFXMAXAB
      inst_id: AX2004
      salt: supersecretsalt
      sslKeyAlias: etz
      keyStorePath: /Users/test/Documents/papss/papss-middleware-service/src/main/resources/keystore/etz-c1.jks
      keyPass: secure
      keyStoreType: JKS
      provider: SunJCE
#
    - apiKey: 706b3dac-21ca-4755-906f-841117db9eab
      country: AX
      inst_bic: AX2005
      inst_id: AX2005
      salt: supersecretsalt
      sslKeyAlias: etz
      keyStorePath: /Users/test/Documents/papss/papss-middleware-service/src/main/resources/keystore/etz-c1.jks
      keyPass: secure
      keyStoreType: JKS
      provider: SunJCE

#    - apiKey: 706b3dac-21ca-4755-906f-841117db9eab
#      country: AX
#      inst_bic: AX2001
#      inst_id: AFXMAXAD
#      salt: supersecretsalt
#      sslKeyAlias: etz
#      keyStorePath: /Users/test/Documents/papss/papss-middleware-service/src/main/resources/keystore/etz-c1.jks
#      keyPass: secure
#      keyStoreType: JKS
#      provider: SunJCE
#    - apiKey: 706b3dac-21ca-4755-906f-841117db9eab
#      country: DJ
#      inst_bic: ZCHLZMLU
#      inst_id: ZM2002
#      salt: supersecretsalt
#      sslKeyAlias: tezd
#      keyStorePath: /Users/test/Documents/projects/papss/papss-middleware-service/src/main/resources/keystore/client.jks
#      keyPass: secure
#      keyStoreType: JKS
#      provider: SunJCE

  system:
    enableInbound: true
    enableOutbound: true
    pollingExecutorsPerParticipant: 3
    toClearingSystemId: XA0001
    ipsBaseUrl: pm.test.papssnet.papss.com
    ipsPort: 443
#core:
#  banking:
#    url: http://sandbox-api.xcelapp.com/xcel-papss
#    path:
#      credit-transfer: "/etz/funds-transfer"
#      name-inquiry: "/etz/name-enquiry"
#      recon: "/settlement-recon"
#      tx-confirmation: "/etz/txn-confirmation"
#      recall-request: "/recall-request"
#      payment-return: "/payment-return"

core:
  banking:
    url: http://localhost:8082/papss-core-banking-mock-server
    path:
      credit-transfer: "/ft"
      name-inquiry: "/name-enquiry"
      recon: "/settlement-recon"
      tx-confirmation: "/txn-confirmation"
      payment-return: "/payment-return"

#springdoc:
#  api-docs:
#    path: /api-docs
#    enabled: false
#  swagger-ui:
#    path: /swagger-ui.html
#    enabled: false
