spring:
  application:
    name: papss-middleware-service
  datasource:
    url: jdbc:postgresql://localhost:5432/papssdb
    username: papss
    password: fg4rHwc7kkPQcqXv
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: HikariCP
      auto-commit: false
      maximum-pool-size: 10
      minimum-idle: 1
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      leak-detection-threshold: 5000
      initialization-fail-timeout: 1

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        boot.allow_jdbc_metadata_access: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        jdbc.batch_size: 50
        order_inserts: true
        order_updates: true
        connection.provider_disables_autocommit: true
    open-in-view: false


logging:
  level:
    com.papss.middleware.service.inbound: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    org.apache.http: DEBUG

papss:
  participants:
#    - apiKey: 706b3dac-21ca-4755-906f-841117db9eab
#      country: KE
#      inst_bic: PSTLKEKE
#      inst_id: KE0002NP
#      salt: supersecretsalt
#      sslKeyAlias: tesn
#      keyStorePath: /Users/test/Documents/papss/papss-middleware-service/src/main/resources/keystore/client.jks
#      keyPass: secure
#      keyStoreType: JKS
#      provider: SunJCE
#    - apiKey: 706b3dac-21ca-4755-906f-841117db9eab
#      country: KE
#      inst_bic: PSTLKEKE
#      inst_id: KE1012
#      salt: supersecretsalt
#      sslKeyAlias: tesn
#      keyStorePath: /Users/test/Documents/papss/papss-middleware-service/src/main/resources/keystore/client.jks
#      keyPass: secure
#      keyStoreType: JKS
#      provider: SunJCE
    - apiKey: 706b3dac-21ca-4755-906f-841117db9eab
      country: DJ
      inst_bic: OMGGDJCK
      inst_id: DJ1009
      salt: supersecretsalt
      sslKeyAlias: tesb
      keyStorePath:  /Users/test/Documents/papss/papss-middleware-service/src/main/resources/keystore/client.jks
      keyPass: secure
      keyStoreType: JKS
      provider: SunJCE
#    - apiKey: 706b3dac-21ca-4755-906f-841117db9eab
#      country: GH
#      inst_bic: AX2005
#      inst_id: AX2005
#      salt: supersecretsalt
#      sslKeyAlias: tesa
#      keyStorePath: /Users/jeze/Documents/projects/papss/papss-middleware-service/src/main/resources/keystore/client.jks
#      keyPass: secure
#      keyStoreType: JKS
#      provider: SunJCE
    - apiKey: 706b3dac-21ca-4755-906f-841117db9eab
      country: ZM
      inst_bic: ZCHLZMLU
      inst_id: ZM2002
      salt: supersecretsalt
      sslKeyAlias: tezd
      keyStorePath: /Users/test/Documents/papss/papss-middleware-service/src/main/resources/keystore/client.jks
      keyPass: secure
      keyStoreType: JKS
      provider: SunJCE

  system:
    enableInbound: true
    enableOutbound: true
    pollingExecutorThreadDelay: 10000
    pollingExecutorThreadRate: 10000
    pollingExecutorsPerParticipant: 2
    pollingSleepTime: 5000
    toClearingSystemId: XA0001
    ipsBaseUrl: pm.test.papssnet.papss.com
    ipsPort: 443
core:
  banking:
    url: http://localhost:8082/papss-core-banking-mock-server
    path:
      credit-transfer: "/ft"
      name-inquiry: "/name-enquiry"
      recon: "/settlement-recon"
      tx-confirmation: "/txn-confirmation"
      recall-request: "/recall-request"
      payment-return: "/payment-return"
