DROP SEQUENCE CUSTOM.YUCASH_RFI_SEQ;

CREATE SEQUENCE CUSTOM.YUCASH_RFI_SEQ
  START WITH 372599
  MAXVALUE 99999999
  MINVALUE 1
  NOCYCLE
  CACHE 10
  NOORDER;
  
DROP SYNONYM CUSTOM.YUCASH_RFI_SEQ_SYN;

CREATE SYNONYM CUSTOM.YUCASH_RFI_SEQ_SYN FOR CUSTOM.YUCASH_RFI_SEQ;

GRANT SELECT ON CUSTOM.YUCASH_RFI_SEQ TO TBAADM;

GRANT SELECT ON CUSTOM.YUCASH_RFI_SEQ TO TBAGEN;

GRANT SELECT ON CUSTOM.YUCASH_RFI_SEQ TO TBAUTIL;
