DROP TABLE CUSTOM.C_UBP_DETAILS CASCADE CONSTRAINTS;

CREATE TABLE CUSTOM.C_UBP_DETAILS
(
  BILL_PAY_REF_NUM            VARCHAR2(20 CHAR),
  MODE_OF_PAY                 VARCHAR2(1 CHAR),
  BILLER_ID                   VARCHAR2(10 CHAR),
  BILLER_ACCT_ID              VARCHAR2(16 CHAR),
  BILLER_BNK_ID               VARCHAR2(8 CHAR),
  PAYER_ACCT_ID               VARCHAR2(16 CHAR),
  PAYER_BNK_ID                VARCHAR2(8 CHAR),
  REF_CRNCY                   VARCHAR2(3 CHAR),
  NAME                        VARCHAR2(80 CHAR),
  BILL_AMT                    NUMBER(20,4),
  BILLER_REF_NUM              VARCHAR2(50 CHAR),
  RATE_CODE                   VARCHAR2(5 CHAR),
  RATE                        NUMBER(21,10),
  TOTAL_AMT                   NUMBER(20,4),
  CHARGE_EVNT_ID              VARCHAR2(25 CHAR),
  CHARGE_AMT                  NUMBER(20,4),
  INSTRMNT_TYPE               VARCHAR2(5 CHAR),
  INSTRMNT_ALPHA              VARCHAR2(6 CHAR),
  INSTRMNT_NUM                VARCHAR2(16 CHAR),
  INSTRMNT_DATE               DATE,
  TRAN_PARTICULARS            VARCHAR2(50 CHAR),
  TRAN_RMKS                   VARCHAR2(100 CHAR),
  TRAN_ID                     VARCHAR2(9 CHAR),
  APP_CATEGORY                VARCHAR2(2 CHAR),
  FREETEXT1                   VARCHAR2(80 CHAR),
  FREETEXT2                   VARCHAR2(80 CHAR),
  FREETEXT3                   VARCHAR2(80 CHAR),
  FREETEXT4                   VARCHAR2(80 CHAR),
  FREETEXT5                   VARCHAR2(80 CHAR),
  FREETEXT6                   VARCHAR2(80 CHAR),
  FREETEXT7                   VARCHAR2(80 CHAR),
  NOSTRO_ACCT                 VARCHAR2(16 CHAR),
  VOSTRO_ACCT                 VARCHAR2(16 CHAR),
  REVERSE_FLG                 CHAR(1 BYTE),
  INTER_ENTITY_TRANID         VARCHAR2(9 BYTE),
  TRAN_DATE                   DATE,
  INTER_ENTITY_TRAN_DATE      DATE,
  INTER_ENTITY_RATE           NUMBER(21,10),
  INTER_ENTITY_RATE_CODE      VARCHAR2(5 CHAR),
  INTER_ENTITY_REV_TRAN_ID    VARCHAR2(9 CHAR),
  INTER_ENTITY_REV_TRAN_DATE  DATE,
  REV_TRAN_ID                 VARCHAR2(9 CHAR),
  REV_TRAN_DATE               DATE,
  CHARGE_TRAN_ID              VARCHAR2(9 CHAR),
  CHARGE_CRNCY                VARCHAR2(3 CHAR),
  CHARGE_TRAN_DATE            DATE,
  REV_CHARGE_TRAN_ID          VARCHAR2(9 CHAR),
  REV_CHARGE_TRAN_DATE        DATE,
  RISK_NOTE                   CHAR(1 CHAR),
  TYP_OF_SERV                 VARCHAR2(10 CHAR),
  VAL_TYPE                    CHAR(4 CHAR),
  CLG_ZONE_CODE               VARCHAR2(10 CHAR),
  CLG_ZONE_DATE               DATE,
  SET_NUM                     VARCHAR2(6 CHAR),
  REM_DYN_FLD                 CLOB,
  SRL_NUM                     VARCHAR2(6 CHAR),
  NOTIFY_FLG                  CHAR(1 CHAR),
  TREA_REF_NUM                VARCHAR2(20 BYTE),
  TREA_RATE                   NUMBER(21,10)
);

CREATE INDEX CUSTOM.C_UBP_DATE_ID_IDX ON CUSTOM.C_UBP_DETAILS
(TRAN_DATE, TRAN_ID);

CREATE INDEX CUSTOM.C_UBP_PK ON CUSTOM.C_UBP_DETAILS
(BILL_PAY_REF_NUM);


CREATE INDEX CUSTOM.C_UBP_BILLER_ID_IDX ON CUSTOM.C_UBP_DETAILS
(FREETEXT7, BILLER_BNK_ID);

DROP SYNONYM CUSTOM.C_UBP;

CREATE SYNONYM CUSTOM.C_UBP FOR CUSTOM.C_UBP_DETAILS;

GRANT SELECT ON CUSTOM.C_UBP_DETAILS TO ALLTAB;

GRANT SELECT ON CUSTOM.C_UBP_DETAILS TO STMNT_USER;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.C_UBP_DETAILS TO TBAADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.C_UBP_DETAILS TO TBAGEN;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.C_UBP_DETAILS TO TBAUTIL;
