ALTER TABLE CUSTOM.ORDER_HEADER
 DROP PRIMARY KEY CASCADE;
DROP TABLE CUSTOM.ORDER_HEADER CASCADE CONSTRAINTS;

CREATE TABLE CUSTOM.ORDER_HEADER
(
  ORD_ID                       NUMBER(8)        NOT NULL,
  ORD_ORDER_NO                 VARCHAR2(50 BYTE),
  ORD_ACID                     VARCHAR2(11 BYTE) NOT NULL,
  ORD_OWN_CONTRIBUTION_AMOUNT  NUMBER(12,2),
  ORD_OWN_CONTRIBUTION_ACCT    VARCHAR2(16 BYTE),
  ORD_STATUS                   VARCHAR2(1 BYTE) NOT NULL,
  ORD_CREATED_BY               VARCHAR2(20 BYTE) NOT NULL,
  ORD_CREATE_DATE              DATE             NOT NULL,
  ORD_VERIFY_BY                VARCHAR2(20 BYTE),
  ORD_VERIFY_DATE              DATE,
  ORD_DISB_FLG                 VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL,
  ORD_RECOV_CHARGES_FROM       VARCHAR2(1 BYTE) DEFAULT 'L' NOT NULL,
  BANK_ID                      VARCHAR2(8 CHAR),
  DEL_FLG                      VARCHAR2(1 BYTE)
);

ALTER TABLE CUSTOM.ORDER_HEADER ADD (
  PRIMARY KEY
 (ORD_ID, BANK_ID)
    USING INDEX 
    );

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON CUSTOM.ORDER_HEADER TO TBAADM;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON CUSTOM.ORDER_HEADER TO TBAGEN;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON CUSTOM.ORDER_HEADER TO TBAUTIL;
