CREATE TABLE INTERENTITY_PAGL_TM_TBL(
IE_TXN_REF_NO			VARCHAR2(10 CHAR),
PART_TRAN_SRL_NUM		VARCHAR2(4 CHAR),
RCRE_USER_ID			VARCHAR2(15 CHAR)
)
/

CREATE SYNONYM TBAADM.INTERENTITY_PAGL_TM_TBL FOR INTERENTITY_PAGL_TM_TBL
/
CREATE SYNONYM TBAGEN.INTERENTITY_PAGL_TM_TBL FOR INTERENTITY_PAGL_TM_TBL
/
CREATE SYNONYM TBAUTIL.INTERENTITY_PAGL_TM_TBL FOR INTERENTITY_PAGL_TM_TBL
/
CREATE SYNONYM TBAADM.IEPAGLTM FOR INTERENTITY_PAGL_TM_TBL
/
CREATE SYNONYM TBAGEN.IEPAGLTM FOR INTERENTITY_PAGL_TM_TBL
/
CREATE SYNONYM TBAUTIL.IEPAGLTM FOR INTERENTITY_PAGL_TM_TBL
/
CREATE SYNONYM CUSTOM.IEPAGLTM FOR INTERENTITY_PAGL_TM_TBL
/
GRANT SELECT, INSERT, UPDATE, DELETE ON INTERENTITY_PAGL_TM_TBL TO TBAGEN
/
GRANT SELECT ON INTERENTITY_PAGL_TM_TBL TO TBAUTIL
/
COMMIT
/

