CREATE TABLE CUSTOM.CUST_KBADDS_UPLD_PROCESS_TABLE
(
  REASONCODE        VARCHAR2(2 BYTE),
  EFTTRANCODE       VARCHAR2(20 BYTE),
  AMOUNT            NUMBER(20,2),
  DEBITBANKCODE     VARCHAR2(2 BYTE),
  DEBITBANKBRANCH   VARCHAR2(3 BYTE),
  DEBITACCTNUM      VARCHAR2(15 BYTE),
  CREDITBANKCODE    VARCHAR2(2 BYTE),
  CREDITBANKBRANCH  VARCHAR2(3 BYTE),
  CREDITACCTNUM     VARCHAR2(15 BYTE),
  INSTBANKCODE      VARCHAR2(2 BYTE),
  INSTBANKBRANCH    VARCHAR2(3 BYTE),
  ORIGINATOR_CODE   VARCHAR2(25 BYTE),
  ORIGINATOR_REF    VARCHAR2(15 BYTE),
  POLICYNUM1        VARCHAR2(20 BYTE),
  POLICYNUM2        VARCHAR2(20 BYTE),
  REMARKS           VARCHAR2(25 BYTE),
  RCRE_USER_ID      VARCHAR2(15 BYTE),
  UPL_STATUS        VARCHAR2(1 BYTE),
  DEL_FLG           VARCHAR2(1 BYTE)            DEFAULT 'N',
  STATUS            VARCHAR2(5 BYTE),
  SOL_ID            VARCHAR2(15 BYTE),
  BANK_ID           VARCHAR2(8 BYTE)
);


CREATE SYNONYM CUSTOM.C_KBADDS FOR CUSTOM.CUST_KBADDS_UPLD_PROCESS_TABLE;


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON CUSTOM.CUST_KBADDS_UPLD_PROCESS_TABLE TO TBAADM;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON CUSTOM.CUST_KBADDS_UPLD_PROCESS_TABLE TO TBAGEN;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON CUSTOM.CUST_KBADDS_UPLD_PROCESS_TABLE TO TBAUTIL;
