DROP TABLE CUSTOM.C_WTH_GSP_DET CASCADE CONSTRAINTS;

CREATE TABLE CUSTOM.C_WTH_GSP_DET
(
  WTH_TAX_APP_FLG  CHAR(1 CHAR),
  WTH_TAX_PCNT     NUMBER(20,4),
  BACID            VARCHAR2(16 CHAR),
  SCHM_TYPE        VARCHAR2(3 CHAR),
  SCHM_CODE        VARCHAR2(5 CHAR),
  MOP_ID           VARCHAR2(8 CHAR),
  DEL_FLG          CHAR(1 BYTE),
  ENTITY_CRE_FLG   CHAR(1 BYTE),
  BANK_ID          VARCHAR2(8 CHAR)
);

CREATE UNIQUE INDEX CUSTOM.C_WTH_GSP_DET_PK ON CUSTOM.C_WTH_GSP_DET
(SCHM_TYPE, SCHM_CODE, MOP_ID, BANK_ID);



DROP SYNONYM CUSTOM.C_WTHD;

CREATE SYNONYM CUSTOM.C_WTHD FOR CUSTOM.C_WTH_GSP_DET;


GRANT SELECT ON CUSTOM.C_WTH_GSP_DET TO ALLTAB;

GRANT SELECT ON CUSTOM.C_WTH_GSP_DET TO TBAADM;

GRANT SELECT ON CUSTOM.C_WTH_GSP_DET TO TBAGEN;

GRANT SELECT ON CUSTOM.C_WTH_GSP_DET TO TBAUTIL;
