DROP TABLE CUSTOM.CUST_OFFLINE_BRANCH_TABLE CASCADE CONSTRAINTS;

CREATE TABLE CUSTOM.CUST_OFFLINE_BRANCH_TABLE
(
  SOL_ID        VARCHAR2(8 BYTE),
  MBM_DATE      DATE,
  MBM_STATUS    CHAR(1 BYTE),
  LCHG_USER_ID  VARCHAR2(15 BYTE),
  LCHG_TIME     DATE,
  RCRE_USER_ID  VARCHAR2(15 BYTE),
  RCRE_TIME     DATE,
  DEL_FLG       CHAR(1 BYTE),
  BANK_ID       VARCHAR2(3 BYTE)
);

DROP SYNONYM CUSTOM.C_OBM;

CREATE SYNONYM CUSTOM.C_OBM FOR CUSTOM.CUST_OFFLINE_BRANCH_TABLE;

GRANT SELECT ON CUSTOM.CUST_OFFLINE_BRANCH_TABLE TO ALLTAB;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.CUST_OFFLINE_BRANCH_TABLE TO TBAADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.CUST_OFFLINE_BRANCH_TABLE TO TBAGEN;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.CUST_OFFLINE_BRANCH_TABLE TO TBAUTIL;
