 CREATE SEQUENCE CUSTOM.CUST_MEMO_AUDIT_SEQ_11
  START WITH 729980
  MAXVALUE 99999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


GRANT SELECT ON CUSTOM.CUST_MEMO_AUDIT_SEQ_11 TO TBAGEN;

GRANT SELECT ON CUSTOM.CUST_MEMO_AUDIT_SEQ_11 TO TBAUTIL;

 CREATE SEQUENCE CUSTOM.CUST_MEMO_AUDIT_SEQ_50
  START WITH 729980
  MAXVALUE 99999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


GRANT SELECT ON CUSTOM.CUST_MEMO_AUDIT_SEQ_50 TO TBAGEN;

GRANT SELECT ON CUSTOM.CUST_MEMO_AUDIT_SEQ_50 TO TBAUTIL;



 CREATE SEQUENCE CUSTOM.CUST_MEMO_AUDIT_SEQ_54
  START WITH 729980
  MAXVALUE 99999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


GRANT SELECT ON CUSTOM.CUST_MEMO_AUDIT_SEQ_54 TO TBAGEN;

GRANT SELECT ON CUSTOM.CUST_MEMO_AUDIT_SEQ_54 TO TBAUTIL;


 CREATE SEQUENCE CUSTOM.CUST_MEMO_AUDIT_SEQ_55
  START WITH 729980
  MAXVALUE 99999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


GRANT SELECT ON CUSTOM.CUST_MEMO_AUDIT_SEQ_55 TO TBAGEN;

GRANT SELECT ON CUSTOM.CUST_MEMO_AUDIT_SEQ_55 TO TBAUTIL;



 CREATE SEQUENCE CUSTOM.CUST_MEMO_AUDIT_SEQ_56
  START WITH 729980
  MAXVALUE 99999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


GRANT SELECT ON CUSTOM.CUST_MEMO_AUDIT_SEQ_56 TO TBAGEN;

GRANT SELECT ON CUSTOM.CUST_MEMO_AUDIT_SEQ_56 TO TBAUTIL;

