CREATE TABLE CUSTOM.CATOD_MASTER_TABLE
(
  ACCT_NUM          VARCHAR2(30 BYTE),
  BRANCH_ID         NUMBER,
  CONTRACT_AMT      NUMBER,
  CUST_ID           VARCHAR2(20 BYTE),
  DEPARTMENT        VARCHAR2(40 BYTE),
  EMPLOYER          VARCHAR2(40 BYTE),
  KEY_SEQ           VARCHAR2(50 BYTE),
  MAX_CNTRT_AMT     NUMBER,
  MAX_CNTRT_PERIOD  NUMBER,
  REC_TIMESTAMP     DATE,
  SCORE             NUMBER,
  BANK_ID           VARCHAR2(8 CHAR),
  ENTITY_CRE_FLG    CHAR(1 BYTE),
  DEL_FLG           CHAR(1 BYTE),
  MOD_FLG           CHAR(1 BYTE)                DEFAULT 'N'
);


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON CUSTOM.CATOD_MASTER_TABLE TO TBAADM;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON CUSTOM.CATOD_MASTER_TABLE TO TBAGEN;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON CUSTOM.CATOD_MASTER_TABLE TO TBAUTIL;
