-----------------MARA -----------------------------------------

-- Create Host Interface Node
Insert into FIMASTER.HOST_INTERFACE_NODE_TABLE
   (HOST_INTERFACE_NODE_ID, HOST_INTERFACE_CODE, HOST_INTERFACE_DESC, REQUEST_PORT_ID, RESPONSE_PORT_ID, 
    PORT_STATUS, USER_GROUP_ID, USER_GROUP_STATUS,HOST_TYPE)
Values
   (FIMASTER.HOST_INTERFACE_NODE_SEQ.nextval, 'MaraGetDtl', 'FINACLE MARA-WS', NULL, NULL, 
    'processed', 1001, 'processed','EXTERNAL')
/

----------------------------- get payment details -----------------------------------------------

--Create Service Provider
INSERT INTO FIMASTER.FIUSB_SERVICE_PROVIDER_TABLE ( FIUSB_SRV_PROV_ID, FIUSB_SRV_PROV_NAME,
FIUSB_SRV_PROV_DESC, HOST_INTERFACE_NODE_ID, HOST_INTERFACE_NODE_STATUS, FIUSB_SRV_PROV_LMU,
FIUSB_SRV_PROV_LMD, FIUSB_SRV_PROV_VER_NO, FIUSB_SRV_PROV_STATUS,
FIUSB_SRV_PROV_CLASS_NAME ) VALUES 
(FIMASTER.FIUSB_SRV_PROV_ID_SEQ.nextval, 'MaraGetDtl', 'MaraGetDtl', FIMASTER.HOST_INTERFACE_NODE_SEQ.currval, 'processed', 'SYSTEM'
,sysdate, 1, 'processed', 'com.infosys.ci.custom.fioutbound.MaraGetPymtDtlsServiceProvider')
/

--Create Requestor 
INSERT INTO FIMASTER.FIUSB_SERVICE_REQUESTOR_TABLE ( FIUSB_SRV_REQ_ID, FIUSB_SRV_REQ_TYPE, 
FIUSB_SRV_INVOC_MODE, FIUSB_SRV_REQ_LMU, FIUSB_SRV_REQ_LMD, FIUSB_SRV_REQ_VER_NO, FIUSB_SRV_REQ_STATUS,
FIUSB_SRV_REQ_TYPE_VERSION, FIUSB_SRV_REQ_NAME, FIUSB_SRV_REQ_DESC, FIUSB_NOT_SRV_REQ_ID,
FIUSB_NOT_SRV_REQ_STATUS, FIUSB_SRV_INTERACTION_TYPE) VALUES 
( FIMASTER.FIUSB_SRV_REQ_ID_SEQ.NEXTVAL,'MaraGetDtl', 'SYNCHRONOUS', 'SYSTEM',  sysdate, 1, 'processed', '10.2','MaraGetDtl', 
'Interface for Finacle and Mara', NULL, NULL, 'Invoker')
/

--Create Service Interface 
INSERT INTO FIMASTER.FIUSB_SERVICE_INTERFACE_TABLE ( FIUSB_SRV_INT_ID, FIUSB_SRV_PROV_ID,
FIUSB_REVERSAL_SRV_INT_ID, FIUSB_SRV_INT_LMU, FIUSB_SRV_INT_LMD, FIUSB_SRV_INT_VER_NO,
FIUSB_SRV_INT_STATUS, FIUSB_SRV_PROV_STATUS, FIUSB_SRV_INT_NAME, FIUSB_SRV_INT_DESC,
FIUSB_REVERSAL_SRV_INT_STATUS, FIUSB_REQ_MAPPER, FIUSB_RESP_MAPPER, FIUSB_SRV_INT_VERSION, FIUSB_MAPPER_STATUS,message_type,message_sub_type) VALUES
( FIMASTER.FIUSB_SRV_INTER_ID_SEQ.NEXTVAL, FIMASTER.FIUSB_SRV_PROV_ID_SEQ.CURRVAL, NULL, 'SYSTEM',sysdate, 1, 'processed', 'processed', 
'MaraGetDtl','Interface for Finacle and Mara-WS', NULL, NULL,NULL, '10.2', 'processed','NVPSTR','FINVP')
/

-- Create  Service Mapping
Insert into FIMASTER.FIUSB_SRV_REQ_MAPPING_TABLE
   (FIUSB_SRV_REQ_ID, FIUSB_SRV_INT_ID, FIUSB_SRV_REQ_STATUS, FIUSB_SRV_INT_STATUS, FIUSB_PROV_INVOC_MODE, 
    FIUSB_PROV_TIMEOUT)
Values
   (FIMASTER.FIUSB_SRV_REQ_ID_SEQ.currval, FIMASTER.FIUSB_SRV_INTER_ID_SEQ.currval, 'processed', 'processed', 'S', 
    NULL)
/

----------------------------- update payment details ----------------------------------------------

--Create Service Provider
INSERT INTO FIMASTER.FIUSB_SERVICE_PROVIDER_TABLE ( FIUSB_SRV_PROV_ID, FIUSB_SRV_PROV_NAME,
FIUSB_SRV_PROV_DESC, HOST_INTERFACE_NODE_ID, HOST_INTERFACE_NODE_STATUS, FIUSB_SRV_PROV_LMU,
FIUSB_SRV_PROV_LMD, FIUSB_SRV_PROV_VER_NO, FIUSB_SRV_PROV_STATUS,
FIUSB_SRV_PROV_CLASS_NAME ) VALUES 
(FIMASTER.FIUSB_SRV_PROV_ID_SEQ.nextval, 'MaraUpdateDtl', 'MaraUpdateDtl', FIMASTER.HOST_INTERFACE_NODE_SEQ.currval, 'processed', 'SYSTEM'
,sysdate, 1, 'processed', 'com.infosys.ci.custom.fioutbound.MaraUpdatePymtDtlsServiceProvider')
/

--Create Requestor 
INSERT INTO FIMASTER.FIUSB_SERVICE_REQUESTOR_TABLE ( FIUSB_SRV_REQ_ID, FIUSB_SRV_REQ_TYPE, 
FIUSB_SRV_INVOC_MODE, FIUSB_SRV_REQ_LMU, FIUSB_SRV_REQ_LMD, FIUSB_SRV_REQ_VER_NO, FIUSB_SRV_REQ_STATUS,
FIUSB_SRV_REQ_TYPE_VERSION, FIUSB_SRV_REQ_NAME, FIUSB_SRV_REQ_DESC, FIUSB_NOT_SRV_REQ_ID,
FIUSB_NOT_SRV_REQ_STATUS, FIUSB_SRV_INTERACTION_TYPE) VALUES 
( FIMASTER.FIUSB_SRV_REQ_ID_SEQ.NEXTVAL,'MaraUpdateDtl', 'SYNCHRONOUS', 'SYSTEM',  sysdate, 1, 'processed', '10.2','MaraUpdateDtl', 
'Interface for Finacle and Mara', NULL, NULL, 'Invoker')
/

--Create Service Interface 
INSERT INTO FIMASTER.FIUSB_SERVICE_INTERFACE_TABLE ( FIUSB_SRV_INT_ID, FIUSB_SRV_PROV_ID,
FIUSB_REVERSAL_SRV_INT_ID, FIUSB_SRV_INT_LMU, FIUSB_SRV_INT_LMD, FIUSB_SRV_INT_VER_NO,
FIUSB_SRV_INT_STATUS, FIUSB_SRV_PROV_STATUS, FIUSB_SRV_INT_NAME, FIUSB_SRV_INT_DESC,
FIUSB_REVERSAL_SRV_INT_STATUS, FIUSB_REQ_MAPPER, FIUSB_RESP_MAPPER, FIUSB_SRV_INT_VERSION, FIUSB_MAPPER_STATUS,message_type,message_sub_type) VALUES
( FIMASTER.FIUSB_SRV_INTER_ID_SEQ.NEXTVAL, FIMASTER.FIUSB_SRV_PROV_ID_SEQ.CURRVAL, NULL, 'SYSTEM',sysdate, 1, 'processed', 'processed', 
'MaraUpdateDtl','Interface for Finacle and Mara- update details', NULL, NULL,NULL, '10.2', 'processed','NVPSTR','FINVP')
/

-- Create  Service Mapping
Insert into FIMASTER.FIUSB_SRV_REQ_MAPPING_TABLE
   (FIUSB_SRV_REQ_ID, FIUSB_SRV_INT_ID, FIUSB_SRV_REQ_STATUS, FIUSB_SRV_INT_STATUS, FIUSB_PROV_INVOC_MODE, 
    FIUSB_PROV_TIMEOUT)
Values
   (FIMASTER.FIUSB_SRV_REQ_ID_SEQ.currval, FIMASTER.FIUSB_SRV_INTER_ID_SEQ.currval, 'processed', 'processed', 'S', 
    NULL)
/

----------------------------------------- KRA --------------------------------------------------------

-- Create Host Interface Node
Insert into FIMASTER.HOST_INTERFACE_NODE_TABLE
   (HOST_INTERFACE_NODE_ID, HOST_INTERFACE_CODE, HOST_INTERFACE_DESC, REQUEST_PORT_ID, RESPONSE_PORT_ID, 
    PORT_STATUS, USER_GROUP_ID, USER_GROUP_STATUS,HOST_TYPE)
Values
   (FIMASTER.HOST_INTERFACE_NODE_SEQ.nextval, 'KRA', 'FINACLE KRA outbound call', NULL, NULL, 
    'processed', 1001, 'processed','EXTERNAL');
/

------------------------------------ get biller code -------------------------------------------------

--Create Service Provider
INSERT INTO FIMASTER.FIUSB_SERVICE_PROVIDER_TABLE ( FIUSB_SRV_PROV_ID, FIUSB_SRV_PROV_NAME,
FIUSB_SRV_PROV_DESC, HOST_INTERFACE_NODE_ID, HOST_INTERFACE_NODE_STATUS, FIUSB_SRV_PROV_LMU,
FIUSB_SRV_PROV_LMD, FIUSB_SRV_PROV_VER_NO, FIUSB_SRV_PROV_STATUS,
FIUSB_SRV_PROV_CLASS_NAME ) VALUES 
(FIMASTER.FIUSB_SRV_PROV_ID_SEQ.nextval, 'KRAGetBillerCode', 'KRAGetBillerCode', FIMASTER.HOST_INTERFACE_NODE_SEQ.currval, 'processed', 'SYSTEM'
,sysdate, 1, 'processed', 'com.infosys.ci.custom.fioutbound.KRAGetBillerCodeServiceProvider');
/

--Create Requestor 
INSERT INTO FIMASTER.FIUSB_SERVICE_REQUESTOR_TABLE ( FIUSB_SRV_REQ_ID, FIUSB_SRV_REQ_TYPE, 
FIUSB_SRV_INVOC_MODE, FIUSB_SRV_REQ_LMU, FIUSB_SRV_REQ_LMD, FIUSB_SRV_REQ_VER_NO, FIUSB_SRV_REQ_STATUS,
FIUSB_SRV_REQ_TYPE_VERSION, FIUSB_SRV_REQ_NAME, FIUSB_SRV_REQ_DESC, FIUSB_NOT_SRV_REQ_ID,
FIUSB_NOT_SRV_REQ_STATUS, FIUSB_SRV_INTERACTION_TYPE) VALUES 
( FIMASTER.FIUSB_SRV_REQ_ID_SEQ.NEXTVAL,'KRAGetBillerCode', 'SYNCHRONOUS', 'SYSTEM',  sysdate, 1, 'processed', '10.2','KRAGetBillerCode', 
'Interface for Finacle and KRA', NULL, NULL, 'Invoker');
/

--Create Service Interface 
INSERT INTO FIMASTER.FIUSB_SERVICE_INTERFACE_TABLE ( FIUSB_SRV_INT_ID, FIUSB_SRV_PROV_ID,
FIUSB_REVERSAL_SRV_INT_ID, FIUSB_SRV_INT_LMU, FIUSB_SRV_INT_LMD, FIUSB_SRV_INT_VER_NO,
FIUSB_SRV_INT_STATUS, FIUSB_SRV_PROV_STATUS, FIUSB_SRV_INT_NAME, FIUSB_SRV_INT_DESC,
FIUSB_REVERSAL_SRV_INT_STATUS, FIUSB_REQ_MAPPER, FIUSB_RESP_MAPPER, FIUSB_SRV_INT_VERSION, FIUSB_MAPPER_STATUS,message_type,message_sub_type) VALUES
( FIMASTER.FIUSB_SRV_INTER_ID_SEQ.NEXTVAL, FIMASTER.FIUSB_SRV_PROV_ID_SEQ.CURRVAL, NULL, 'SYSTEM',sysdate, 1, 'processed', 'processed', 
'KRAGetBillerCode','Interface for Finacle and KRA - get biller code', NULL, NULL,NULL, '10.2', 'processed','NVPSTR','FINVP');
/

-- Create  Service Mapping
Insert into FIMASTER.FIUSB_SRV_REQ_MAPPING_TABLE
   (FIUSB_SRV_REQ_ID, FIUSB_SRV_INT_ID, FIUSB_SRV_REQ_STATUS, FIUSB_SRV_INT_STATUS, FIUSB_PROV_INVOC_MODE, 
    FIUSB_PROV_TIMEOUT)
Values
   (FIMASTER.FIUSB_SRV_REQ_ID_SEQ.currval, FIMASTER.FIUSB_SRV_INTER_ID_SEQ.currval, 'processed', 'processed', 'S', 
    NULL);
/

--------------------------------- get validation object ----------------------------------------------

--Create Service Provider
INSERT INTO FIMASTER.FIUSB_SERVICE_PROVIDER_TABLE ( FIUSB_SRV_PROV_ID, FIUSB_SRV_PROV_NAME,
FIUSB_SRV_PROV_DESC, HOST_INTERFACE_NODE_ID, HOST_INTERFACE_NODE_STATUS, FIUSB_SRV_PROV_LMU,
FIUSB_SRV_PROV_LMD, FIUSB_SRV_PROV_VER_NO, FIUSB_SRV_PROV_STATUS,
FIUSB_SRV_PROV_CLASS_NAME ) VALUES 
(FIMASTER.FIUSB_SRV_PROV_ID_SEQ.nextval, 'KRAGetValidationsObj', 'KRAGetValidationsObj', FIMASTER.HOST_INTERFACE_NODE_SEQ.currval, 'processed', 'SYSTEM'
,sysdate, 1, 'processed', 'com.infosys.ci.custom.fioutbound.KRAGetValidationsObjServiceProvider');
/

--Create Requestor 
INSERT INTO FIMASTER.FIUSB_SERVICE_REQUESTOR_TABLE ( FIUSB_SRV_REQ_ID, FIUSB_SRV_REQ_TYPE, 
FIUSB_SRV_INVOC_MODE, FIUSB_SRV_REQ_LMU, FIUSB_SRV_REQ_LMD, FIUSB_SRV_REQ_VER_NO, FIUSB_SRV_REQ_STATUS,
FIUSB_SRV_REQ_TYPE_VERSION, FIUSB_SRV_REQ_NAME, FIUSB_SRV_REQ_DESC, FIUSB_NOT_SRV_REQ_ID,
FIUSB_NOT_SRV_REQ_STATUS, FIUSB_SRV_INTERACTION_TYPE) VALUES 
( FIMASTER.FIUSB_SRV_REQ_ID_SEQ.NEXTVAL,'KRAGetValidationsObj', 'SYNCHRONOUS', 'SYSTEM',  sysdate, 1, 'processed', '10.2','KRAGetValidationsObj', 
'Interface for Finacle and KRA', NULL, NULL, 'Invoker');
/

--Create Service Interface 
INSERT INTO FIMASTER.FIUSB_SERVICE_INTERFACE_TABLE ( FIUSB_SRV_INT_ID, FIUSB_SRV_PROV_ID,
FIUSB_REVERSAL_SRV_INT_ID, FIUSB_SRV_INT_LMU, FIUSB_SRV_INT_LMD, FIUSB_SRV_INT_VER_NO,
FIUSB_SRV_INT_STATUS, FIUSB_SRV_PROV_STATUS, FIUSB_SRV_INT_NAME, FIUSB_SRV_INT_DESC,
FIUSB_REVERSAL_SRV_INT_STATUS, FIUSB_REQ_MAPPER, FIUSB_RESP_MAPPER, FIUSB_SRV_INT_VERSION, FIUSB_MAPPER_STATUS,message_type,message_sub_type) VALUES
( FIMASTER.FIUSB_SRV_INTER_ID_SEQ.NEXTVAL, FIMASTER.FIUSB_SRV_PROV_ID_SEQ.CURRVAL, NULL, 'SYSTEM',sysdate, 1, 'processed', 'processed', 
'KRAGetValidationsObj','Interface for Finacle and KRA - get validations object', NULL, NULL,NULL, '10.2', 'processed','NVPSTR','FINVP');
/

-- Create  Service Mapping
Insert into FIMASTER.FIUSB_SRV_REQ_MAPPING_TABLE
   (FIUSB_SRV_REQ_ID, FIUSB_SRV_INT_ID, FIUSB_SRV_REQ_STATUS, FIUSB_SRV_INT_STATUS, FIUSB_PROV_INVOC_MODE, 
    FIUSB_PROV_TIMEOUT)
Values
   (FIMASTER.FIUSB_SRV_REQ_ID_SEQ.currval, FIMASTER.FIUSB_SRV_INTER_ID_SEQ.currval, 'processed', 'processed', 'S', 
    NULL);
/

-------------------------------------- FDSA ----------------------------------------------------------

-- Create Host Interface Node
Insert into FIMASTER.HOST_INTERFACE_NODE_TABLE
   (HOST_INTERFACE_NODE_ID, HOST_INTERFACE_CODE, HOST_INTERFACE_DESC, REQUEST_PORT_ID, RESPONSE_PORT_ID, 
    PORT_STATUS, USER_GROUP_ID, USER_GROUP_STATUS,HOST_TYPE)
Values
   (FIMASTER.HOST_INTERFACE_NODE_SEQ.nextval, 'FDSA', 'FINACLE KRA outbound call', NULL, NULL, 
    'processed', 1001, 'processed','EXTERNAL');
/

------------------------------------ Get Order -----------------------------------------------------

--Create Service Provider
INSERT INTO FIMASTER.FIUSB_SERVICE_PROVIDER_TABLE ( FIUSB_SRV_PROV_ID, FIUSB_SRV_PROV_NAME,
FIUSB_SRV_PROV_DESC, HOST_INTERFACE_NODE_ID, HOST_INTERFACE_NODE_STATUS, FIUSB_SRV_PROV_LMU,
FIUSB_SRV_PROV_LMD, FIUSB_SRV_PROV_VER_NO, FIUSB_SRV_PROV_STATUS,
FIUSB_SRV_PROV_CLASS_NAME ) VALUES 
(FIMASTER.FIUSB_SRV_PROV_ID_SEQ.nextval, 'FDSA', 'FDSAGetOrder', FIMASTER.HOST_INTERFACE_NODE_SEQ.currval, 'processed', 'SYSTEM'
,sysdate, 1, 'processed', 'com.infosys.ci.custom.fioutbound.FDSAGetOrderServiceProvider');
/

--Create Requestor 
INSERT INTO FIMASTER.FIUSB_SERVICE_REQUESTOR_TABLE ( FIUSB_SRV_REQ_ID, FIUSB_SRV_REQ_TYPE, 
FIUSB_SRV_INVOC_MODE, FIUSB_SRV_REQ_LMU, FIUSB_SRV_REQ_LMD, FIUSB_SRV_REQ_VER_NO, FIUSB_SRV_REQ_STATUS,
FIUSB_SRV_REQ_TYPE_VERSION, FIUSB_SRV_REQ_NAME, FIUSB_SRV_REQ_DESC, FIUSB_NOT_SRV_REQ_ID,
FIUSB_NOT_SRV_REQ_STATUS, FIUSB_SRV_INTERACTION_TYPE) VALUES 
( FIMASTER.FIUSB_SRV_REQ_ID_SEQ.NEXTVAL,'FDSAGetOrder', 'SYNCHRONOUS', 'SYSTEM',  sysdate, 1, 'processed', '10.2','FDSAGetOrder', 
'Interface for Finacle and FDSA', NULL, NULL, 'Invoker');
/

--Create Service Interface 
INSERT INTO FIMASTER.FIUSB_SERVICE_INTERFACE_TABLE ( FIUSB_SRV_INT_ID, FIUSB_SRV_PROV_ID,
FIUSB_REVERSAL_SRV_INT_ID, FIUSB_SRV_INT_LMU, FIUSB_SRV_INT_LMD, FIUSB_SRV_INT_VER_NO,
FIUSB_SRV_INT_STATUS, FIUSB_SRV_PROV_STATUS, FIUSB_SRV_INT_NAME, FIUSB_SRV_INT_DESC,
FIUSB_REVERSAL_SRV_INT_STATUS, FIUSB_REQ_MAPPER, FIUSB_RESP_MAPPER, FIUSB_SRV_INT_VERSION, FIUSB_MAPPER_STATUS,message_type,message_sub_type) VALUES
( FIMASTER.FIUSB_SRV_INTER_ID_SEQ.NEXTVAL, FIMASTER.FIUSB_SRV_PROV_ID_SEQ.CURRVAL, NULL, 'SYSTEM',sysdate, 1, 'processed', 'processed', 
'FDSAGetOrder','Interface for Finacle and FDSA - get order', NULL, NULL,NULL, '10.2', 'processed','NVPSTR','FINVP');
/

-- Create  Service Mapping
Insert into FIMASTER.FIUSB_SRV_REQ_MAPPING_TABLE
   (FIUSB_SRV_REQ_ID, FIUSB_SRV_INT_ID, FIUSB_SRV_REQ_STATUS, FIUSB_SRV_INT_STATUS, FIUSB_PROV_INVOC_MODE, 
    FIUSB_PROV_TIMEOUT)
Values
   (FIMASTER.FIUSB_SRV_REQ_ID_SEQ.currval, FIMASTER.FIUSB_SRV_INTER_ID_SEQ.currval, 'processed', 'processed', 'S', 
    NULL);
/
