SET DEFINE OFF;
Insert into CUSTOM.C_CPMASTER
   (MODULE_NAME, PARAMETER_LEVEL, PARAMETER_ID, PARAMETER_DESC, PARAMETER_TYPE, LIST_TYPE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID)
 Values
   ('TRADE_FINANCE', 'BNKL', 'OCTMCHRGEVT', 'CHARGE EVENT ID', 'AN', 'FT', 'Y', 'N', 'USER1', TO_DATE('06/07/2013 13:53:33', 'MM/DD/YYYY HH24:MI:SS'), 'USER1', TO_DATE('06/07/2013 13:53:33', 'MM/DD/YYYY HH24:MI:SS'), '11');
Insert into CUSTOM.C_CPMASTER
   (MODULE_NAME, PARAMETER_LEVEL, PARAMETER_ID, PARAMETER_DESC, PARAMETER_TYPE, LIST_TYPE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID)
 Values
   ('TRADE_FINANCE', 'BNKL', 'OCTMCHRGEVT', 'CHARGE EVENT ID', 'AN', 'FT', 'Y', 'N', 'USER1', TO_DATE('06/07/2013 13:53:33', 'MM/DD/YYYY HH24:MI:SS'), 'USER1', TO_DATE('06/07/2013 13:53:33', 'MM/DD/YYYY HH24:MI:SS'), '50');
Insert into CUSTOM.C_CPMASTER
   (MODULE_NAME, PARAMETER_LEVEL, PARAMETER_ID, PARAMETER_DESC, PARAMETER_TYPE, LIST_TYPE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID)
 Values
   ('TRADE_FINANCE', 'BNKL', 'OCTMCHRGEVT', 'CHARGE EVENT ID', 'AN', 'FT', 'Y', 'N', 'USER1', TO_DATE('06/07/2013 13:53:33', 'MM/DD/YYYY HH24:MI:SS'), 'USER1', TO_DATE('06/07/2013 13:53:33', 'MM/DD/YYYY HH24:MI:SS'), '54');
Insert into CUSTOM.C_CPMASTER
   (MODULE_NAME, PARAMETER_LEVEL, PARAMETER_ID, PARAMETER_DESC, PARAMETER_TYPE, LIST_TYPE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID)
 Values
   ('TRADE_FINANCE', 'BNKL', 'OCTMCHRGEVT', 'CHARGE EVENT ID', 'AN', 'FT', 'Y', 'N', 'USER1', TO_DATE('06/07/2013 13:53:33', 'MM/DD/YYYY HH24:MI:SS'), 'USER1', TO_DATE('06/07/2013 13:53:33', 'MM/DD/YYYY HH24:MI:SS'), '55');
Insert into CUSTOM.C_CPMASTER
   (MODULE_NAME, PARAMETER_LEVEL, PARAMETER_ID, PARAMETER_DESC, PARAMETER_TYPE, LIST_TYPE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID)
 Values
   ('TRADE_FINANCE', 'BNKL', 'OCTMCHRGEVT', 'CHARGE EVENT ID', 'AN', 'FT', 'Y', 'N', 'USER1', TO_DATE('06/07/2013 13:53:33', 'MM/DD/YYYY HH24:MI:SS'), 'USER1', TO_DATE('06/07/2013 13:53:33', 'MM/DD/YYYY HH24:MI:SS'), '56');
COMMIT;
