<?xml version="1.0" encoding="UTF-8"?>
<!-- Montran Corporation 2017 - RP -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="urn:montran:overdraftSet.001"
           elementFormDefault="qualified"
           targetNamespace="urn:montran:overdraftSet.001">

    <xs:element name="overdraftSet">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="CreDtTm" type="xs:dateTime"/>
                <xs:element name="accounts" type="AccountList"/>
            </xs:sequence>
            <xs:attribute name="instgAgtBIC" type="BICIdentifier" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="AccountList">
        <xs:sequence>
            <xs:element name="account" type="AccountInfo" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="AccountInfo">
        <xs:attribute name="agtBIC" type="BICIdentifier" use="required"/>
        <xs:attribute name="ccy" type="ActiveCurrencyCode" use="required"/>
        <xs:attribute name="overdraft" type="Amount_SimpleType"/>
    </xs:complexType>

    <!-- Supporting simple Types -->
    <xs:simpleType name="Amount_SimpleType">
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="0.00"/>
            <xs:fractionDigits value="2"/>
            <xs:totalDigits value="17"/>
            <xs:maxInclusive value="999999999999999.99"/>
            <xs:pattern value="[0-9]{0,15}([\.]([0-9]{0,2})){0,1}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="ActiveCurrencyCode">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z]{3,3}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="BICIdentifier">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z]{6,6}[A-Z2-9][A-NP-Z0-9]([A-Z0-9]{3,3}){0,1}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="ConditionType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="COMPLETE"/>
            <xs:enumeration value="HOLD"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>