<?xml version="1.0" encoding="UTF-8"?>
<!-- Montran Corporation 2017-2019 (RP) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="urn:montran:positions.001" elementFormDefault="qualified"
           targetNamespace="urn:montran:positions.001">
    <xs:element name="positions">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="snapshot" type="SnapshotInfo"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="SnapshotInfo">
        <xs:sequence>
            <xs:element name="conditions" type="ConditionsList" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="instgAgtCrlSysId" type="ClrSysMmbId" use="required"/>
        <xs:attribute name="lastTranSeq" type="xs:long" use="required"/>
        <xs:attribute name="timestamp" type="xs:dateTime" use="required"/>
    </xs:complexType>

    <xs:complexType name="ConditionsList">
        <xs:sequence>
            <xs:element name="condition" type="ConditionInfo" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="agtCrlSysId" type="ClrSysMmbId" use="required"/>
        <xs:attribute name="agtId" type="xs:integer"/>
    </xs:complexType>

    <xs:complexType name="ConditionInfo">
        <xs:attribute name="accountCode" type="Max15Text" use="required"/>
        <xs:attribute name="ccy" type="ActiveCurrencyCode" use="required"/>
        <xs:attribute name="condType" type="ConditionType"/>
        <xs:attribute name="balance" type="BalanceAmount_SimpleType"/>
        <xs:attribute name="overdraft" type="Amount_SimpleType"/>
        <xs:attribute name="debitAmount" type="Amount_SimpleType"/>
        <xs:attribute name="debitCount" type="xs:integer"/>
        <xs:attribute name="creditAmount" type="Amount_SimpleType"/>
        <xs:attribute name="creditCount" type="xs:integer"/>
    </xs:complexType>

    <!-- Supporting simple Types -->
    <xs:simpleType name="Amount_SimpleType">
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="0.00"/>
            <xs:fractionDigits value="2"/>
            <xs:totalDigits value="17"/>
            <xs:maxInclusive value="999999999999999.99"/>
            <xs:pattern value="[0-9]{0,15}([\.]([0-9]{0,2})){0,1}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="BalanceAmount_SimpleType">
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="-999999999999999.99"/>
            <xs:fractionDigits value="2"/>
            <xs:totalDigits value="17"/>
            <xs:maxInclusive value="999999999999999.99"/>
            <xs:pattern value="[\-]{0,1}[0-9]{0,15}([\.]([0-9]{0,2})){0,1}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="ActiveCurrencyCode">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z]{3,3}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="ClrSysMmbId">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z]{2,2}[1-9]{1,4}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="ConditionType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="COMPLETE"/>
            <xs:enumeration value="HOLD"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="Max15Text">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="15"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>