CREATE TABLE CUSTOM.INTERENTITY_CASH_WTHDRW_TBL
(
  IE_TXN_REF_NO                 VARCHAR2(10 CHAR),
  INIT_ENTITY_ID                VARCHAR2(8 CHAR),
  TARGET_ENTITY_ID              VARCHAR2(8 CHAR),
  ENTITY1_TRAN_ID               VARCHAR2(9 CHAR),
  ENTITY1_TRAN_DATE             DATE,
  ENTITY2_TRAN_ID               VARCHAR2(9 CHAR),
  ENTITY2_TRAN_DATE             DATE,
  ENTITY1_SETTLEMENT_STATUS     CHAR(1 BYTE),
  ENTITY2_SETTLEMENT_STATUS     CHAR(1 BYTE),
  CENTRAL_SETTLEMENT_STATUS     CHAR(1 BYTE),
  ENTITY1_SETTLEMENT_TRAN_ID    VARCHAR2(9 CHAR),
  ENTITY1_SETTLEMENT_TRAN_DATE  DATE,
  ENTITY2_SETTLEMENT_TRAN_ID    VARCHAR2(9 CHAR),
  ENTITY2_SETTLEMENT_TRAN_DATE  DATE,
  CENTRAL_SETTLEMENT_TRAN_ID    VARCHAR2(9 CHAR),
  CENTRAL_SETTLEMENT_TRAN_DATE  DATE,
  DR_ACCOUNT_ID                 VARCHAR2(16 CHAR),
  TRAN_AMT                      NUMBER(20,4),
  TRAN_CRNCY_CODE               VARCHAR2(3 CHAR),
  CHARGE_AMT                    NUMBER(20,4),
  CHARGE_AMT_CCY                VARCHAR2(3 CHAR),
  TRAN_AMT_IN_HARD_CCY          NUMBER(20,4),
  HARD_CRNCY_CODE               VARCHAR2(3 CHAR),
  CHARGE_AMT_IN_USD             NUMBER(20,4),
  IN_CP_ACCOUNT_ID              VARCHAR2(16 CHAR),
  OUT_CP_ACCOUNT_ID             VARCHAR2(16 CHAR),
  ENTITY1_VOSTRO_ACCOUNT_ID     VARCHAR2(16 CHAR),
  ENTITY1_INCOME_ACCOUNT_ID     VARCHAR2(16 CHAR),
  ENTITY2_VOSTRO_ACCOUNT_ID     VARCHAR2(16 CHAR),
  CENTRAL_SETTLEMENT_ACCOUNT    VARCHAR2(16 CHAR),
  CENTRAL_ENTITY1_NOSTRO        VARCHAR2(16 CHAR),
  CENTRAL_ENTITY2_NOSTRO        VARCHAR2(16 CHAR),
  FREE_TEXT1                    VARCHAR2(50 CHAR),
  FREE_TEXT2                    VARCHAR2(50 CHAR),
  FREE_TEXT3                    VARCHAR2(50 CHAR),
  FREE_TEXT4                    VARCHAR2(50 CHAR),
  FREE_TEXT5                    VARCHAR2(50 CHAR),
  LCHG_USER_ID                  VARCHAR2(15 CHAR),
  LCHG_TIME                     DATE,
  RCRE_USER_ID                  VARCHAR2(15 CHAR),
  RCRE_TIME                     DATE
);


CREATE SYNONYM TBAGEN.IECWD FOR INTERENTITY_CASH_WTHDRW_TBL;


CREATE SYNONYM TBAADM.INTERENTITY_CASH_WTHDRW_TBL FOR CUSTOM.INTERENTITY_CASH_WTHDRW_TBL;


CREATE SYNONYM TBAGEN.INTERENTITY_CASH_WTHDRW_TBL FOR CUSTOM.INTERENTITY_CASH_WTHDRW_TBL;


CREATE SYNONYM TBAUTIL.INTERENTITY_CASH_WTHDRW_TBL FOR CUSTOM.INTERENTITY_CASH_WTHDRW_TBL;


CREATE SYNONYM TBAADM.IECWD FOR CUSTOM.INTERENTITY_CASH_WTHDRW_TBL;


CREATE SYNONYM TBAUTIL.IECWD FOR CUSTOM.INTERENTITY_CASH_WTHDRW_TBL;


CREATE SYNONYM CUSTOM.IECWD FOR CUSTOM.INTERENTITY_CASH_WTHDRW_TBL;


GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.INTERENTITY_CASH_WTHDRW_TBL TO TBAGEN;

GRANT SELECT ON CUSTOM.INTERENTITY_CASH_WTHDRW_TBL TO TBAUTIL;
