DROP TABLE CUSTOM.CUST_INSTITUTE_CUSTOMERS CASCADE CONSTRAINTS;

CREATE TABLE CUSTOM.CUST_INSTITUTE_CUSTOMERS
(
  ACCTNUM  VARCHAR2(16 BYTE),
  REFNUM   VARCHAR2(50 BYTE),
  NAME     VARCHAR2(300 BYTE),
  DEL_FLG  CHAR(1 BYTE),
  BANK_ID  VARCHAR2(3 BYTE)
);

CREATE UNIQUE INDEX CUSTOM.CIC_PK ON CUSTOM.CUST_INSTITUTE_CUSTOMERS
(ACCTNUM, REFNUM, BANK_ID);


DROP SYNONYM CUSTOM.C_CIC;

CREATE SYNONYM CUSTOM.C_CIC FOR CUSTOM.CUST_INSTITUTE_CUSTOMERS;

GRANT SELECT ON CUSTOM.CUST_INSTITUTE_CUSTOMERS TO ALLTAB;

GRANT DELETE, INSERT, UPDATE ON CUSTOM.CUST_INSTITUTE_CUSTOMERS TO SMBOGORI;

GRANT SELECT ON CUSTOM.CUST_INSTITUTE_CUSTOMERS TO STMNT_USER;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.CUST_INSTITUTE_CUSTOMERS TO TBAADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.CUST_INSTITUTE_CUSTOMERS TO TBAGEN;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.CUST_INSTITUTE_CUSTOMERS TO TBAUTIL;
