DROP TABLE CUSTOM.CUST_AUTH_MATRIX_ID CASCADE CONSTRAINTS;

CREATE TABLE CUSTOM.CUST_AUTH_MATRIX_ID
(
  EXCP_CODE              VARCHAR2(3 CHAR),
  AUTH_MATRIX_ID     VARCHAR2(5 CHAR),
  BANK_ID                VARCHAR2(8 CHAR)
);

DROP SYNONYM CUSTOM.C_CAM;
CREATE OR REPLACE SYNONYM CUSTOM.C_CAM FOR CUSTOM.CUST_AUTH_MATRIX_ID;
GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.CUST_AUTH_MATRIX_ID TO CUSTOM;
GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.CUST_AUTH_MATRIX_ID TO TBAGEN;
GRANT SELECT ON CUSTOM.CUST_AUTH_MATRIX_ID TO TBAUTIL;
