ALTER TABLE CUSTOM.SALE_DETAILS
 DROP PRIMARY KEY CASCADE;
DROP TABLE CUSTOM.SALE_DETAILS CASCADE CONSTRAINTS;

CREATE TABLE CUSTOM.SALE_DETAILS
(
  SERIALNUM      VARCHAR2(80 CHAR),
  CODE           VARCHAR2(80 CHAR),
  HOLDINGS       VARCHAR2(80 CHAR),
  AMOUNT         NUMBER(20,4),
  SHARES_TRADED  VARCHAR2(16 CHAR),
  SELLING_PRICE  VARCHAR2(16 CHAR),
  ACCT_NUM       VARCHAR2(16 CHAR),
  HOLDING_BAL    NUMBER(20,4),
  TRANS_DATE     DATE,
  REF_NUM        VARCHAR2(100 BYTE),
  TRANS_STATUS   VARCHAR2(1 BYTE),
  ENTERED_BY     VARCHAR2(20 BYTE),
  VERIFIED_BY    VARCHAR2(20 BYTE),
  CUSTOMERNAMES  VARCHAR2(100 BYTE),
  CDSC_NUMBER    VARCHAR2(50 BYTE)              NOT NULL,
  DELETED_BY     VARCHAR2(50 BYTE),
  SOL_ID         VARCHAR2(10 BYTE)
);

CREATE INDEX CUSTOM.ACCT_NUM_IDX ON CUSTOM.SALE_DETAILS
(ACCT_NUM);

CREATE UNIQUE INDEX CUSTOM.SALE_DETAILS_PK ON CUSTOM.SALE_DETAILS
(SERIALNUM);

ALTER TABLE CUSTOM.SALE_DETAILS ADD (
  CONSTRAINT SALE_DETAILS_PK
 PRIMARY KEY
 (SERIALNUM)
    USING INDEX );
	
GRANT SELECT ON CUSTOM.SALE_DETAILS TO ALLTAB;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.SALE_DETAILS TO TBAADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.SALE_DETAILS TO TBAGEN;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.SALE_DETAILS TO TBAUTIL;


