DROP TABLE CUSTOM.C_WTH_ACCT_OPEN CASCADE CONSTRAINTS;

CREATE TABLE CUSTOM.C_WTH_ACCT_OPEN
(
  WTH_TAX_APP_FLG  CHAR(1 BYTE),
  FORACID          VARCHAR2(16 CHAR),
  SCHM_TYPE        VARCHAR2(3 CHAR),
  SCHM_CODE        VARCHAR2(5 CHAR),
  LCHG_USER_ID     VARCHAR2(15 CHAR),
  LCHG_TIME        DATE,
  RCRE_USER_ID     VARCHAR2(15 CHAR),
  RCRE_TIME        DATE,
  DEL_FLG          CHAR(1 BYTE),
  ENTITY_CRE_FLG   CHAR(1 BYTE),
  BANK_ID          VARCHAR2(8 CHAR)
);

CREATE UNIQUE INDEX CUSTOM.IDX_C_WTH_ACCT_OPEN ON CUSTOM.C_WTH_ACCT_OPEN
(FORACID, BANK_ID);

DROP SYNONYM CUSTOM.C_WTHAO;

CREATE SYNONYM CUSTOM.C_WTHAO FOR CUSTOM.C_WTH_ACCT_OPEN;

GRANT SELECT ON CUSTOM.C_WTH_ACCT_OPEN TO ALLTAB;

GRANT SELECT ON CUSTOM.C_WTH_ACCT_OPEN TO TBAADM;

GRANT SELECT ON CUSTOM.C_WTH_ACCT_OPEN TO TBAGEN;

GRANT SELECT ON CUSTOM.C_WTH_ACCT_OPEN TO TBAUTIL;
