CREATE TABLE CUSTOM.MODULE_DETAILS
(
  MODULE_ID       VARCHAR2(30 CHAR),
  MODULE_DESC     VARCHAR2(50 CHAR),
  DEL_FLG         CHAR(1 BYTE),
  RCRE_USER_ID    VARCHAR2(15 CHAR),
  RCRE_TIME       DATE,
  LCHG_USER_ID    VARCHAR2(15 CHAR),
  LCHG_TIME       DATE,
  ENTITY_CRE_FLG  CHAR(1 BYTE),
  TS_COUNT        NUMBER(5),
  BANK_ID         VARCHAR2(10 CHAR)
);


CREATE SYNONYM TBAADM.MODULE FOR CUSTOM.MODULE_DETAILS;


CREATE SYNONYM TBAUTIL.MODULE FOR CUSTOM.MODULE_DETAILS;


CREATE SYNONYM TBAGEN.MODULE FOR CUSTOM.MODULE_DETAILS;


CREATE SYNONYM CUSTOM.MODULE FOR CUSTOM.MODULE_DETAILS;


GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.MODULE_DETAILS TO TBAADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.MODULE_DETAILS TO TBAGEN;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.MODULE_DETAILS TO TBAUTIL;
