DROP TABLE CUSTOM.EXCANRE_TABLE CASCADE CONSTRAINTS;

CREATE TABLE CUSTOM.EXCANRE_TABLE
(
  CLIENTCDSNO    VARCHAR2(30 BYTE),
  ACCOUNTNUMBER  VARCHAR2(30 BYTE),
  AMOUNT         NUMBER(10,2),
  ASATDATE       DATE,
  FORACID        VARCHAR2(16 BYTE),
  SOL_ID         VARCHAR2(8 BYTE),
  ACCNT_CRNCY    VARCHAR2(5 BYTE),
  REMARKS        VARCHAR2(100 BYTE),
  VALID          VARCHAR2(1 BYTE),
  PAYMENT_DPA    NUMBER(10),
  BANK_ID        VARCHAR2(8 BYTE)
);

DROP SYNONYM CUSTOM.C_EXCANRE;

CREATE SYNONYM CUSTOM.C_EXCANRE FOR CUSTOM.EXCANRE_TABLE;


GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.EXCANRE_TABLE TO TBAADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.EXCANRE_TABLE TO TBAGEN;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.EXCANRE_TABLE TO TBAUTIL;
