CREATE SEQUENCE CUSTOM.CATODSCORE_SEQ_55
  START WITH 258
  MAXVALUE 99999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


GRANT SELECT ON CUSTOM.CATODSCORE_SEQ_55 TO CRMBATCHUSER;

GRANT SELECT ON CUSTOM.CATODSCORE_SEQ_55 TO CRMUSER;

GRANT SELECT ON CUSTOM.CATODSCORE_SEQ_55 TO DEDUPADM;

GRANT SELECT ON CUSTOM.CATODSCORE_SEQ_55 TO TBAGEN;

GRANT SELECT ON CUSTOM.CATODSCORE_SEQ_55 TO TBAADM;

GRANT SELECT ON CUSTOM.CATODSCORE_SEQ_55 TO TBAUTIL;

GRANT SELECT ON CUSTOM.CATODSCORE_SEQ_55 TO CUSTOM;
