--DROP TABLE CUSTOM.DUTYDIFFPERIOD CASCADE CONSTRAINTS;

CREATE TABLE CUSTOM.DUTYDIFFPERIOD
(
  ENDDATE        DATE,
  STARTDATE      DATE,
  EXCISEDUTYACC  VARCHAR2(16 BYTE),
  SOL_ID         VARCHAR2(8 BYTE),
  ENDPERIOD      NUMBER(20,4),
  STARTPERIOD    NUMBER(20,4),
  DIFFAMOUNT     NUMBER(20,4),
  PERCNTAMOUNT   NUMBER(20,4),
  FORACID        VARCHAR2(16 BYTE),
  ACCT_NAME      VARCHAR2(80 BYTE),
  PROCESSDATE    DATE,
  PROCESSFLG     CHAR(1 BYTE),
  SEQUENCE       VARCHAR2(80 BYTE),
  BANK_ID	 VARCHAR2(8 CHAR)
)
TABLESPACE CUSTOM_TBLS
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;

GRANT ALL ON CUSTOM.DUTYDIFFPERIOD TO TBAADM, TBAGEN, TBAUTIL;

