DROP FUNCTION CUSTOM.GET_ACCT_STATUS;

CREATE OR REPLACE FUNCTION CUSTOM.GET_ACCT_STATUS(CATOD_ACCT_NUM IN TBAADM.GAM.FORACID%type,v_bank_id IN VARCHAR2)
	RETURN VARCHAR2
IS
	CATOD_OUT VARCHAR2(100);

BEGIN
	/* CHECKING WHETHER ACCOUNT IS VALID OR NOT */
	BEGIN
		SELECT 'SUCCESS' INTO CATOD_OUT FROM TBAADM.GAM
		WHERE ENTITY_CRE_FLG = 'Y'
		AND DEL_FLG = 'N'
		AND FORACID = CATOD_ACCT_NUM
		AND bank_id = v_bank_id;
	EXCEPTION WHEN NO_DATA_FOUND THEN
		CATOD_OUT := 'INVALID ACCOUNT NUM';
	END;

	IF (CATOD_OUT='SUCCESS') THEN
		/* CHECKING WHTHER ACCOUNT IS AUTHORISED OR NOT */
        BEGIN
            SELECT 'SUCCESS' INTO CATOD_OUT FROM TBAADM.GAM,TBAADM.DAR
            WHERE DAR.SCHM_CODE = GAM.SCHM_CODE
            AND DAR.DAT_REF_TYPE='UG'
            AND GAM.ACCT_OWNERSHIP IN ('C','E')
--            AND GAM.SCHM_TYPE IN (SELECT CODE_VALUE FROM CATOD_CODE_TABLE WHERE CODE_TYPE = 'S' AND IS_DELETED='N')
--            AND GAM.SCHM_CODE NOT IN (SELECT CODE_VALUE FROM CATOD_CODE_TABLE WHERE CODE_TYPE = 'B' AND IS_DELETED='N')
		and gam.bank_id = dar.bank_id
		and GAM.bank_id = v_bank_id
            AND GAM.FORACID = CATOD_ACCT_NUM;
        EXCEPTION WHEN NO_DATA_FOUND THEN
            CATOD_OUT := 'ACCOUNT IS NOT AUTHORIZED FOR TOD.';
        END;

        IF (CATOD_OUT='SUCCESS') THEN
            /* CHECKING WHTHER ACCOUNT IS CLOSED OR NOT */
            BEGIN
                SELECT 'SUCCESS' INTO CATOD_OUT FROM TBAADM.GAM
                WHERE ENTITY_CRE_FLG = 'Y'
                AND DEL_FLG = 'N'
                AND ACCT_CLS_FLG != 'Y'
		AND GAM.bank_id = v_bank_id
                AND FORACID = CATOD_ACCT_NUM;
            EXCEPTION WHEN NO_DATA_FOUND THEN
                CATOD_OUT := 'ACCOUNT IS CLOSED';
            END;

            IF (CATOD_OUT='SUCCESS') THEN
                /* CHECKING WHTHER ACCOUNT IS FREEZED OR NOT */
                BEGIN
                    SELECT 'SUCCESS' INTO CATOD_OUT FROM TBAADM.GAM
                    WHERE ENTITY_CRE_FLG = 'Y'
                    AND DEL_FLG = 'N'
                    AND ACCT_CLS_FLG != 'Y'
                    AND TRIM(FREZ_CODE) IS NULL
			AND GAM.bank_id = v_bank_id
                    AND FORACID = CATOD_ACCT_NUM;
                EXCEPTION WHEN NO_DATA_FOUND THEN
                    CATOD_OUT := 'ACCOUNT IS FREEZED';
                END;

                IF (CATOD_OUT='SUCCESS') THEN
                    /* CHECKING WHTHER ACCOUNT IS ACTIVE OR NOT */
                    BEGIN
                        SELECT 'SUCCESS' INTO CATOD_OUT FROM TBAADM.SMT,TBAADM.GAM
                        WHERE SMT.ACID = GAM.ACID
                        AND SMT.ACCT_STATUS = 'A'
			AND GAM.BANK_id = v_bank_id
                        AND GAM.FORACID = CATOD_ACCT_NUM;
                    EXCEPTION WHEN NO_DATA_FOUND THEN
                        CATOD_OUT := 'ACCOUNT IS INACTIVE / DORMANT';
                    END;
                END IF;
            END IF;
        END IF;
    END IF;
RETURN CATOD_OUT;

END GET_ACCT_STATUS;
/


DROP SYNONYM CUSTOM.CATOD_GET_ACCT_STATUS;

CREATE SYNONYM CUSTOM.CATOD_GET_ACCT_STATUS FOR CUSTOM.GET_ACCT_STATUS;


GRANT EXECUTE, DEBUG ON CUSTOM.GET_ACCT_STATUS TO TBAADM;

GRANT EXECUTE, DEBUG ON CUSTOM.GET_ACCT_STATUS TO TBAGEN;

GRANT EXECUTE, DEBUG ON CUSTOM.GET_ACCT_STATUS TO TBAUTIL;
