DROP TABLE CUSTOM.ISLAMIC_BAL_DETAIL_TBL CASCADE CONSTRAINTS;

CREATE TABLE CUSTOM.ISLAMIC_BAL_DETAIL_TBL
(
  TRAN_ID           VARCHAR2(9 CHAR),
  TRAN_DATE         DATE,
  GL_SUB_HEAD_CODE  VARCHAR2(5 CHAR),
  CRNCY_CODE        VARCHAR2(3 CHAR),
  SOL_ID            VARCHAR2(8 CHAR),
  BANK_ID           VARCHAR2(8 CHAR)
)
TABLESPACE CUSTOM_TBLS;
DROP SYNONYM TBAADM.ISLAMIC_BAL_DETAIL_TBL;
CREATE SYNONYM TBAADM.ISLAMIC_BAL_DETAIL_TBL FOR CUSTOM.ISLAMIC_BAL_DETAIL_TBL;


DROP SYNONYM TBAGEN.ISLAMIC_BAL_DETAIL_TBL;
CREATE SYNONYM TBAGEN.ISLAMIC_BAL_DETAIL_TBL FOR CUSTOM.ISLAMIC_BAL_DETAIL_TBL;


DROP SYNONYM TBAUTIL.ISLAMIC_BAL_DETAIL_TBL;
CREATE SYNONYM TBAUTIL.ISLAMIC_BAL_DETAIL_TBL FOR CUSTOM.ISLAMIC_BAL_DETAIL_TBL;


DROP SYNONYM TBAADM.ISLBAL;
CREATE SYNONYM TBAADM.ISLBAL FOR CUSTOM.ISLAMIC_BAL_DETAIL_TBL;


DROP SYNONYM TBAGEN.ISLBAL;
CREATE SYNONYM TBAGEN.ISLBAL FOR CUSTOM.ISLAMIC_BAL_DETAIL_TBL;


DROP SYNONYM TBAUTIL.ISLBAL;
CREATE SYNONYM TBAUTIL.ISLBAL FOR CUSTOM.ISLAMIC_BAL_DETAIL_TBL;


DROP SYNONYM CUSTOM.ISLBAL;
CREATE SYNONYM CUSTOM.ISLBAL FOR CUSTOM.ISLAMIC_BAL_DETAIL_TBL;

CREATE INDEX CUSTOM.IDX_ISLBAL ON CUSTOM.ISLBAL(TRAN_ID,TRAN_DATE)

GRANT ALL ON CUSTOM.ISLAMIC_BAL_DETAIL_TBL TO TBAADM,TBAGEN,TBAUTIL;
