/
CREATE TABLE CUSTOM.INT_CHANGE_HAGTM
(
	  AGENT_CODE    VARCHAR2(10 CHAR),
	  CRNCY_CODE    VARCHAR2(3 CHAR),
	  BANK_ID       VARCHAR2(8 CHAR),
	  TICKET_NO     VARCHAR2(50 BYTE),
	  STATUS_FLG    VARCHAR2(5 BYTE),
	  ENTERER_ID    VARCHAR2(50 BYTE),
	  ENTERER_DATE  DATE
);
/
commit;
/
CREATE TABLE CUSTOM.AUDIT_HAGTM
(
	  SOL_ID                 VARCHAR2(8 CHAR),
	  AGENT_CODE             VARCHAR2(10 CHAR),
	  DEL_FLG                CHAR(1 BYTE),
	  AGENT_SHORT_NAME       VARCHAR2(10 CHAR),
	  AGENT_TITLE_CODE       VARCHAR2(5 CHAR),
	  AGENT_NAME             VARCHAR2(40 CHAR),
	  AGENT_ADDR1            VARCHAR2(45 CHAR),
	  AGENT_ADDR2            VARCHAR2(45 CHAR),
	  AGENT_CITY_CODE        VARCHAR2(5 CHAR),
	  AGENT_STATE_CODE       VARCHAR2(5 CHAR),
	  AGENT_PIN              VARCHAR2(10 CHAR),
	  AGENT_PHONE_NUM        VARCHAR2(12 CHAR),
	  SECURITY_AMT           NUMBER(20,4),
	  EXPECTED_COLLECTION    NUMBER(20,4),
	  NO_OF_ACCT_OPENED      NUMBER(4),
	  OPER_CREDIT_ACID       VARCHAR2(11 CHAR),
	  INOPER_CREDIT_ACID     VARCHAR2(11 CHAR),
	  ITAX_PCNT              NUMBER(9,6),
	  INT_AMT_CEILING        NUMBER(20,4),
	  FREE_TEXT              VARCHAR2(60 CHAR),
	  LCHG_USER_ID           VARCHAR2(15 CHAR),
	  LCHG_TIME              DATE,
	  RCRE_USER_ID           VARCHAR2(15 CHAR),
	  RCRE_TIME              DATE,
	  CRNCY_CODE             VARCHAR2(3 CHAR),
	  TS_CNT                 NUMBER(5),
	  BANK_ID                VARCHAR2(8 CHAR),
	  AGENT_ADDR3            VARCHAR2(45 CHAR),
	  AGENT_CNTRY_CODE       VARCHAR2(5 CHAR),
	  MOD_ENTER_USER_ID      CHAR(7 BYTE),
	  MOD_ENTER_AUDIT_DATE   DATE,
	  MOD_CHEKER_USER_ID     CHAR(7 BYTE),
	  MOD_CHEKER_AUDIT_DATE  DATE,
	  TICKET_NO              CHAR(100 BYTE)
);
/
commit;
/

