/
update tbaadm.gam set  product_group =''  where bank_id='43' and product_group ='RECOV'  and schm_type='LAA';
/
commit;
/
update tbaadm.gam set  product_group ='RECOV'  where bank_id='43'  and foracid in (
	select ACCT_NUM from (
		SELECT   GAM.SOL_ID, (GAM.SCHM_CODE) PRODUCT, (GAM.ACCT_MGR_USER_ID) ACCTMGR,
		GAM.FORACID ACCT_NUM, LAM.DMD_SATISFY_MTHD, GAM.ACCT_NAME,
		(OPGAM.FORACID) REPACCT, (OPGAM.ACCT_NAME) REPACCTNAME,
		(OPGAM.CLR_BAL_AMT) OPSBALANCE, LAM.DIS_AMT,
		ABS (GAM.CLR_BAL_AMT) OST_BAL,
		ABS (  SUM (NVL (DECODE (LDT.DMD_FLOW_ID,'PRDEM', NVL (DMD_AMT, 0)- NVL (TOT_ADJ_AMT, 0),0),0))+
			SUM (NVL (DECODE (LDT.DMD_FLOW_ID,'INDEM', NVL (DMD_AMT, 0)
						- NVL (TOT_ADJ_AMT, 0),0),0))+ SUM (NVL (DECODE (LDT.DMD_FLOW_ID,'OCDEM',
						NVL (DMD_AMT, 0)- NVL (TOT_ADJ_AMT, 0),0),0))+ SUM (NVL (DECODE (LDT.DMD_FLOW_ID,
						'PIDEM', NVL (DMD_AMT, 0)
						- NVL (TOT_ADJ_AMT, 0),0),0))) TOTAL_ARREAS, GAC.DPD_CNTR OVD_DAYS,
		REF_DESC SUB_CLASSIFICATION_SYSTEM,
		(SYSTEM_CLASSIFICATION_DATE) LASTCLASSDATE,OPGAM.LIEN_AMT,OPGAM.CLR_BAL_AMT,OPGAM.foracid,OPGAM.FREZ_CODE,OPGAM.FREZ_REASON_CODE
		,(select REF_DESC from tbaadm.rct where bank_id='43' and REF_REC_TYPE='31' and REF_CODE=OPGAM.FREZ_REASON_CODE and rownum<2) as  FREZ_REASON_CODE_DESC
		FROM TBAADM.GAM, TBAADM.LAM, TBAADM.LDT, TBAADM.ACD, TBAADM.RCT, TBAADM.GAC, TBAADM.GAM OPGAM
		WHERE ACD.B2K_ID = GAM.ACID
		AND GAM.ACID = LAM.ACID
		AND GAM.ACID = LDT.ACID
		AND GAC.ACID = GAM.ACID
		AND LAM.OP_ACID = OPGAM.ACID
		AND RCT.REF_CODE = ACD.SUB_CLASSIFICATION_SYSTEM
		AND GAM.SCHM_TYPE = 'LAA'
		AND GAM.ACCT_CLS_FLG = 'N'
		AND ACD.B2K_TYPE = 'ACCNT'
		AND GAM.BANK_ID = '43'
		AND RCT.REF_REC_TYPE = '92'
		AND (GAC.CHRGE_OFF_FLG != 'Y' OR GAC.CHRGE_OFF_FLG IS NULL)
		HAVING ABS (  SUM (NVL (DECODE (LDT.DMD_FLOW_ID,'PRDEM', NVL (DMD_AMT, 0)- NVL (TOT_ADJ_AMT, 0),0),0))+
			SUM (NVL (DECODE (LDT.DMD_FLOW_ID,'INDEM', NVL (DMD_AMT, 0)
						- NVL (TOT_ADJ_AMT, 0),0),0))+ SUM (NVL (DECODE (LDT.DMD_FLOW_ID,'OCDEM',
						NVL (DMD_AMT, 0)- NVL (TOT_ADJ_AMT, 0),0),0))+ SUM (NVL (DECODE (LDT.DMD_FLOW_ID,
						'PIDEM', NVL (DMD_AMT, 0)
						- NVL (TOT_ADJ_AMT, 0),0),0))) >0
		GROUP BY GAM.SOL_ID,
		(GAM.SCHM_CODE),(GAM.ACCT_MGR_USER_ID),GAM.FORACID,LAM.DMD_SATISFY_MTHD,GAM.ACCT_NAME,
		(OPGAM.FORACID),(OPGAM.ACCT_NAME),(OPGAM.CLR_BAL_AMT),LAM.DIS_AMT,ABS (GAM.CLR_BAL_AMT),REF_DESC,(SYSTEM_CLASSIFICATION_DATE), GAC.DPD_CNTR,OPGAM.LIEN_AMT
		,OPGAM.FREZ_CODE,OPGAM.FREZ_REASON_CODE));
/
commit;
/
exit;

