# ===================================================================
# Spring Boot configuration for the "prod" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

logging:
  level:
    ROOT: INFO

    com:
      equitybank:
        payments:
          imt:
            b2c:
              drcbroker: INFO

spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false

  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sql-equity-admin
    password: h3xzqqc73Tigy84pEiHQQPQap
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:sqlserver://equity-dev-test-001.database.windows.net:1433;database=imtB2CTechDRCBrokerMS;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLServer2012Dialect
    show-sql: false

    properties:
      hibernate:
        enable_lazy_load_no_trans: true

server:
  port: 8284
  shutdown: graceful # see https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-graceful-shutdown
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
    min-response-size: 1024

#Enable signature validation
signature:
  enabled: true

#Token Generation Parameters
token:
  grant-type: password
  username: GAG
  password: GagPasswordTest@123


