INSERT INTO TELCO_B2C_PARAM_CONFIGS (id, config_id, config_value, config_bin_value, config_desc, config_status)
VALUES (1, 'Telcos_CD', 'AIRTEL_CD|VODACOM_CD|ORANGE_CD|AFRICELL_CD', 'AIRTEL_CD|VODACOM_CD|ORANGE_CD|AFRICELL_CD', 'Telcos in DRC', 'ENABLED');




DESCRIBE TELCO_B2C_TRANSACTION_DETAILS;

DESCRIBE TELCO_B2C_PAYLOAD_DETAILS;

DESCRIBE TELCO_B2C_STATUS_DETAILS;

DESCRIBE TELCO_B2C_CALLBACK;

Describe TELCO_B2C_PARAM_CONFIGS;


Select * from TELCO_B2C_STATUS_DETAILS where date_updated LIKE '2024-08-02 06%';

Select * from TELCO_B2C_PAYLOAD_DETAILS where date_updated LIKE '2024-08-02 06%';

Select * from TELCO_B2C_TRANSACTION_DETAILS where date_updated LIKE '2024-08-02 06%';

-- Select * from TELCO_B2C_NOTIFICATION where date_updated LIKE '2024-08-02 06%';


-- drop table TELCO_B2C_CALLBACK;

-- drop table TELCO_B2C_STATUS_DETAILS;

-- drop table TELCO_B2C_PAYLOAD_DETAILS;

-- drop table TELCO_B2C_TRANSACTION_DETAILS;

-- drop table TELCO_B2C_PARAM_CONFIGS;

