DROP TABLE CUSTOM.PORDM_MER CASCADE CONSTRAINTS;

CREATE TABLE CUSTOM.PORDM_MER
(
  BENEFNAME       VARCHAR2(100 BYTE),
  ENTITY_CRE_FLG  VARCHAR2(5 BYTE),
  SOL_ID          VARCHAR2(8 BYTE),
  AWINSTACCT      VARCHAR2(30 BYTE),
  BENFADDRESS1    VARCHAR2(100 BYTE),
  BENEFCTRYCODE   VARCHAR2(16 BYTE),
  BIC             VARCHAR2(20 BYTE),
  AMOUNT          VARCHAR2(20 BYTE),
  BANK_ID         VARCHAR2(8 BYTE),
  FORACID         VARCHAR2(16 BYTE),
  OTHERS          VARCHAR2(80 BYTE),
  ERROR_CODE      VARCHAR2(500 BYTE),
  FREETEXT1       VARCHAR2(30 BYTE),
  REMITCRNCY      VARCHAR2(5 BYTE),
  BOD_DATE        DATE,
  SEQUENCE        VARCHAR2(20 BYTE),
  ERROR_DESC      VARCHAR2(500 BYTE),
  CORE_REF_NO     VARCHAR2(100 BYTE)
);
