DROP SEQUENCE CUSTOM.CREM_SEQ;

CREATE SEQUENCE CUSTOM.CREM_SEQ
  START WITH 3
  MAXVALUE 99999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;
  
DROP SYNONYM CUSTOM.CREM_SEQ_SEQ;

CREATE SYNONYM CUSTOM.CREM_SEQ_SEQ FOR CUSTOM.CREM_SEQ;

GRANT SELECT ON CUSTOM.CREM_SEQ TO TBAADM;

GRANT SELECT ON CUSTOM.CREM_SEQ TO TBAGEN;

GRANT SELECT ON CUSTOM.CREM_SEQ TO TBAUTIL;
