DROP SEQUENCE CUSTOM.MERCHA_SEQ;

CREATE SEQUENCE CUSTOM.MERCHA_SEQ
  START WITH 6341
  MAXVALUE 9999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
  
  
GRANT SELECT ON CUSTOM.MERCHA_SEQ TO ADM_PARALLEL_EXECUTE_TASK;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO ALLSEQ;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO ALLSYN;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO ALLTAB;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO APDMADM;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO APPQOSSYS;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO AQ_ADMINISTRATOR_ROLE;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO AQ_USER_ROLE;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO CEADM;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO CONNECT;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO COREDBA;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO CORESEQ;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO CORESYN;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO CORETAB;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO COREUSER;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO CRMUSER;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO CSADM;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO DATAPUMP_EXP_FULL_DATABASE;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO DATAPUMP_IMP_FULL_DATABASE;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO DBA;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO DBFS_ROLE;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO DBREAD;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO DBSNMP;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO DEDUPADM;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO DEDUPBATUSER;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO DELETE_CATALOG_ROLE;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO DIP;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO DNLDADM;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO EBETLUSR;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO EXECUTE_CATALOG_ROLE;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO EXP_FULL_DATABASE;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO FCONN;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO FCONN2;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO FDMADM;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO FIEJB;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO FIMASTER;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO FINDBA;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO FINRIADM;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO FINRIGEN;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO FINRIUTIL;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO FINSCHEDULER;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO FINUSER;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO FINUSERPLUS;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO FISALONE;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO FISISCONN;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO FISISDBA;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO FISISSEQ;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO FISISSYN;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO FISISTAB;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO FISISUSER;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO FRES;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO GATHER_SYSTEM_STATISTICS;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO GLOBAL_AQ_USER_ROLE;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO HS_ADMIN_EXECUTE_ROLE;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO HS_ADMIN_ROLE;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO HS_ADMIN_SELECT_ROLE;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO IMP_FULL_DATABASE;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO INTADM;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO INTBATCHUSER;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO LOGSTDBY_ADMINISTRATOR;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO MIGBATCHUSER;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO OEM_ADVISOR;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO PUBLIC;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO RECOVERY_CATALOG_OWNER;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO RESOURCE;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO RIDBA;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO RIUSER;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO ROLEGEN;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO SCHEDULER_ADMIN;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO SELECT_CATALOG_ROLE;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO SISSELUSER;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO SSOADM;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO SSODBA;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO SSOGEN;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO SSOSEQ;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO SSOSYN;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO SSOTAB;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO SSOUSER;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO SSOUTIL;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO SVSBULKROLE;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO SVSBULKUSER;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO SVSROLE;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO SVSUSER;


GRANT SELECT ON CUSTOM.MERCHA_SEQ TO OEM_MONITOR;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO ORACLE_OCM;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO OUTLN;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO PEASUSER;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO TBAADM;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO TBAGEN;

GRANT SELECT ON CUSTOM.MERCHA_SEQ TO TBAUTIL;
