CREATE TABLE CUSTOM.MSG_POPUP_TABLE
(
  FORACID     VARCHAR2(16 BYTE),
  MSG_TEXT_1  VARCHAR2(50 BYTE),
  MSG_TEXT_2  VARCHAR2(50 BYTE),
  MSG_TEXT_3  VARCHAR2(50 BYTE),
  MSG_TEXT_4  VARCHAR2(50 BYTE),
  MSG_TEXT_5  VARCHAR2(50 BYTE),
  MSG_TEXT_6  VARCHAR2(50 BYTE),
  MSG_TEXT_7  VARCHAR2(50 BYTE),
  MSG_TEXT_8  VARCHAR2(50 BYTE),
  DEL_FLG     CHAR(1 BYTE),
  BANK_ID     VARCHAR2(8 BYTE)
);


CREATE INDEX CUSTOM.IDX_C_MOP_FORACID ON CUSTOM.MSG_POPUP_TABLE
(FORACID, BANK_ID);


CREATE SYNONYM CUSTOM.C_MOP FOR CUSTOM.MSG_POPUP_TABLE;


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON CUSTOM.MSG_POPUP_TABLE TO TBAADM;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON CUSTOM.MSG_POPUP_TABLE TO TBAGEN;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON CUSTOM.MSG_POPUP_TABLE TO TBAUTIL;
