DROP TABLE CUSTOM.ATM_SHARE_TOTPOST CASCADE CONSTRAINTS;

CREATE TABLE CUSTOM.ATM_SHARE_TOTPOST
(
  MAIN_SOL            CHAR(3 BYTE),
  MAIN_SOL_COMM_ACNT  VARCHAR2(15 BYTE),
  ATM_SOL_ID          VARCHAR2(5 BYTE),
  ATM_SOL_COMM_ACCT   VARCHAR2(15 BYTE),
  CUST_SOL_ID         VARCHAR2(5 BYTE),
  CUST_SOL_COMM_ACCT  VARCHAR2(15 BYTE),
  TOTAL               NUMBER,
  ATM_SOL_COMM        NUMBER,
  CUST_SOL_COMM       NUMBER,
  PROCESS_FLAG        VARCHAR2(1 CHAR)          DEFAULT 'N',
  SEQUENCE_NO         NUMBER,
  PROCESS_DATE        DATE,
  BANK_ID             VARCHAR2(3 BYTE)
);

CREATE UNIQUE INDEX CUSTOM.ATM_PK ON CUSTOM.ATM_SHARE_TOTPOST
(MAIN_SOL_COMM_ACNT, SEQUENCE_NO, BANK_ID);

DROP SYNONYM CUSTOM.ATM_SHARE_TOTPOST_ATM;

CREATE SYNONYM CUSTOM.ATM_SHARE_TOTPOST_ATM FOR CUSTOM.ATM_SHARE_TOTPOST;

GRANT SELECT ON CUSTOM.ATM_SHARE_TOTPOST TO ALLTAB;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.ATM_SHARE_TOTPOST TO TBAADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.ATM_SHARE_TOTPOST TO TBAGEN;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.ATM_SHARE_TOTPOST TO TBAUTIL;
