CREATE SEQUENCE CUSTOM.CUST_DENOM_CASHX_SEQ
  START WITH 83
  MAXVALUE 99999999
  MINVALUE 1
  CYCLE
  NOCACHE
  NOORDER;


CREATE SYNONYM CUSTOM.DENOM_CASHX_SEQ FOR CUSTOM.CUST_DENOM_CASHX_SEQ;


GRANT SELECT ON CUSTOM.CUST_DENOM_CASHX_SEQ TO TBAGEN;

GRANT SELECT ON CUSTOM.CUST_DENOM_MASTER_CR_TMP TO ALLTAB;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.CUST_DENOM_MASTER_CR_TMP TO TBAADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.CUST_DENOM_MASTER_CR_TMP TO TBAGEN;

GRANT SELECT ON CUSTOM.CUST_DENOM_MASTER_CR_TMP TO TBAUTIL;
