-- Author 	: Dileep
-- SQL to insert new Error code developed for EFT/CHQ validation. 
-- One more field is added in the CustInfo API for identifying the origin of the request
-- and the same will be validated and thrown appropriate error message

SET DEFINE OFF;
Insert into CUSTOM.C_CPVALUE
   (PARAMETER_ID, LEVELCODE_1, PARAMETER_VALUE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID, MODULE_NAME)
 Values
   ('ERR114', 'ALL', 'PaymentType is mandatory. Valid Values K/E', 'Y', 'N', 'SYSTEM', TO_DATE('07/31/2013 13:25:52', 'MM/DD/YYYY HH24:MI:SS'), 'SYSTEM', TO_DATE('07/31/2013 13:25:52', 'MM/DD/YYYY HH24:MI:SS'), '11', 'VERACIOUS');
Insert into CUSTOM.C_CPVALUE
   (PARAMETER_ID, LEVELCODE_1, PARAMETER_VALUE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID, MODULE_NAME)
 Values
   ('ERR114', 'ALL', 'PaymentType is mandatory. Valid Values K/E', 'Y', 'N', 'SYSTEM', TO_DATE('07/31/2013 13:26:27', 'MM/DD/YYYY HH24:MI:SS'), 'SYSTEM', TO_DATE('07/31/2013 13:26:27', 'MM/DD/YYYY HH24:MI:SS'), '50', 'VERACIOUS');
Insert into CUSTOM.C_CPVALUE
   (PARAMETER_ID, LEVELCODE_1, PARAMETER_VALUE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID, MODULE_NAME)
 Values
   ('ERR114', 'ALL', 'PaymentType is mandatory. Valid Values K/E', 'Y', 'N', 'SYSTEM', TO_DATE('07/31/2013 13:26:44', 'MM/DD/YYYY HH24:MI:SS'), 'SYSTEM', TO_DATE('07/31/2013 13:26:44', 'MM/DD/YYYY HH24:MI:SS'), '54', 'VERACIOUS');
Insert into CUSTOM.C_CPVALUE
   (PARAMETER_ID, LEVELCODE_1, PARAMETER_VALUE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID, MODULE_NAME)
 Values
   ('ERR114', 'ALL', 'PaymentType is mandatory. Valid Values K/E', 'Y', 'N', 'SYSTEM', TO_DATE('07/31/2013 13:27:03', 'MM/DD/YYYY HH24:MI:SS'), 'SYSTEM', TO_DATE('07/31/2013 13:27:03', 'MM/DD/YYYY HH24:MI:SS'), '55', 'VERACIOUS');
Insert into CUSTOM.C_CPVALUE
   (PARAMETER_ID, LEVELCODE_1, PARAMETER_VALUE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID, MODULE_NAME)
 Values
   ('ERR114', 'ALL', 'PaymentType is mandatory. Valid Values K/E', 'Y', 'N', 'SYSTEM', TO_DATE('07/31/2013 13:27:24', 'MM/DD/YYYY HH24:MI:SS'), 'SYSTEM', TO_DATE('07/31/2013 13:27:24', 'MM/DD/YYYY HH24:MI:SS'), '56', 'VERACIOUS');

Insert into CUSTOM.C_CPMASTER
   (MODULE_NAME, PARAMETER_LEVEL, PARAMETER_ID, PARAMETER_DESC, PARAMETER_TYPE, LIST_TYPE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID)
 Values
   ('VERACIOUS', 'BNKL', 'ERR114', 'ERR114', 'AN', 'FT', 'Y', 'N', 'SYSTEM', TO_DATE('07/31/2013 13:23:33', 'MM/DD/YYYY HH24:MI:SS'), 'SYSTEM', TO_DATE('07/31/2013 13:23:33', 'MM/DD/YYYY HH24:MI:SS'), '11');
Insert into CUSTOM.C_CPMASTER
   (MODULE_NAME, PARAMETER_LEVEL, PARAMETER_ID, PARAMETER_DESC, PARAMETER_TYPE, LIST_TYPE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID)
 Values
   ('VERACIOUS', 'BNKL', 'ERR114', 'ERR114', 'AN', 'FT', 'Y', 'N', 'SYSTEM', TO_DATE('07/31/2013 13:24:10', 'MM/DD/YYYY HH24:MI:SS'), 'SYSTEM', TO_DATE('07/31/2013 13:24:10', 'MM/DD/YYYY HH24:MI:SS'), '50');
Insert into CUSTOM.C_CPMASTER
   (MODULE_NAME, PARAMETER_LEVEL, PARAMETER_ID, PARAMETER_DESC, PARAMETER_TYPE, LIST_TYPE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID)
 Values
   ('VERACIOUS', 'BNKL', 'ERR114', 'ERR114', 'AN', 'FT', 'Y', 'N', 'SYSTEM', TO_DATE('07/31/2013 13:24:38', 'MM/DD/YYYY HH24:MI:SS'), 'SYSTEM', TO_DATE('07/31/2013 13:24:38', 'MM/DD/YYYY HH24:MI:SS'), '54');
Insert into CUSTOM.C_CPMASTER
   (MODULE_NAME, PARAMETER_LEVEL, PARAMETER_ID, PARAMETER_DESC, PARAMETER_TYPE, LIST_TYPE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID)
 Values
   ('VERACIOUS', 'BNKL', 'ERR114', 'ERR114', 'AN', 'FT', 'Y', 'N', 'SYSTEM', TO_DATE('07/31/2013 13:25:02', 'MM/DD/YYYY HH24:MI:SS'), 'SYSTEM', TO_DATE('07/31/2013 13:25:02', 'MM/DD/YYYY HH24:MI:SS'), '55');
Insert into CUSTOM.C_CPMASTER
   (MODULE_NAME, PARAMETER_LEVEL, PARAMETER_ID, PARAMETER_DESC, PARAMETER_TYPE, LIST_TYPE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID)
 Values
   ('VERACIOUS', 'BNKL', 'ERR114', 'ERR114', 'AN', 'FT', 'Y', 'N', 'SYSTEM', TO_DATE('07/31/2013 13:25:27', 'MM/DD/YYYY HH24:MI:SS'), 'SYSTEM', TO_DATE('07/31/2013 13:25:27', 'MM/DD/YYYY HH24:MI:SS'), '56');
COMMIT;
