<%--
//Generated by Customization WB Generator
//Do not edit this file directly.
//Instead, modify the properties in the tool and regenerate.
--%>

<%@ page import="applcommon.ParseValue" %>
<%@ page import="com.infy.bbu.jsputil.*"%>
<%@ taglib uri="taglib.tld" prefix="arjsp" %>
<arjsp:init groupName="Customize" isEntryPoint="false" />

<%
	String sProfileId = ProfilesManager.getProfileInSession(session);
	String sSubGrpName = (String)ARJspCurr.getInput("subGroupName","");
	String sGrpName = ARJspCurr.getCurrentGroup();
	String sPopUpExceptionWindow = (String)ARJspCurr.getInput(sGrpName+".PopUpExceptionWindow" ,"false");
	String sReferralMode = (String)ARJspCurr.getInput("refSubMode" ,"");
	ARJspCurr.setInput(sGrpName+".PopUpExceptionWindow","false");
	String funcCode=request.getParameter("cbwyorm.funcCode")!=null ?request.getParameter("cbwyorm.funcCode"):"";
	String srlNum = request.getParameter("cbwyorm.srlNum")!=null ?request.getParameter("cbwyorm.srlNum"):"";
	
%>
<script>
	var sPopUpExceptionWindow = '<%=sPopUpExceptionWindow%>';
	var sReferralMode = '<%=sReferralMode%>' ;
	
	var subGroupName = '<%=ParseValue.checkString(ARJspCurr.getInput("subGroupName",""))%>';
	var funcCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".funcCode",""))%>';
	var tsrlNum = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".srlNum",""))%>';
	var treqId = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".ormreqId",""))%>';
	var toperActId = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".operAcct",""))%>';
	var tcrncy = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".Currency",""))%>';
	var toperChrgActId = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".operChrgAcct",""))%>';
	var tvalueDate = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".valueDate",""))%>';
	var tamount = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".amount",""))%>';
	var tdrCustAddr1 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".drCustAddr1",""))%>';
	var tdrCustName = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".drCustName",""))%>';
	var tdrCustAddr2 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".drCustAddr2",""))%>';
	var tdrCustAddr3 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".drCustAddr3",""))%>';
	var tdrCustCntry = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".drCustCntry",""))%>';
	var tcrCustName = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".crCustName",""))%>';
	var tcrCustAddr1 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".crCustAddr1",""))%>';
	var tcrCustAddr2 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".crCustAddr2",""))%>';
	var tcrCustAddr3 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".crCustAddr3",""))%>';
	var tcrCustCntry = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".crCustCntry",""))%>';
	var tbeneBankBic = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".beneBankBic",""))%>';
	var tpayeeCor = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".payeeCor",""))%>';
	var tlodgeBillId = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".lodgeBillId",""))%>';
	var tbillRelDate = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".billRelDate",""))%>';
	var tstatus = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".status",""))%>';
</script>

<script language="javascript" src="../Renderer/javascripts/lists/showAccountIdList.js" > </script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("cust_evt.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("core_banking.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("resource_functions.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showCurrency.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showCustId.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showSchmCodes.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showSolId.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showSearcher.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showRefCode.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/custom/javascripts/cust_fetch_list.js"></script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("cust_pre_evt.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("cust_evt.js",sProfileId)%>" > </script>

<script language="JavaScript">
	printBlock();
	printFooterBlock();
</script>

