#!/bin/bash

# ==================================================================================================
# SCRIPT: check-modified-files-sit.sh
#
# PURPOSE:
#   Detects J2EE file changes (NEW, MODIFIED, DELETED) from Git and prepares deployment artifacts
#   for the SIT environment.
#
# USAGE:
#   check-modified-files-sit.sh --app <fincore|crm>
#
#   --app fincore : only process files under fincore/custom/group/**
#   --app crm     : only process files under crm/customization/group/**
#
#   Each CI pipeline passes its own app so a commit touching both does not cause redundant deployments.
#
# SCOPE (filtered by --app):
#   - fincore/custom/group/**
#   - crm/customization/group/**
#
# SIT TOPOLOGY:
#   All banks (11, 43, 50, 54, 55, 56, 99) share one Group server.
#   A single routing tag (J2EE-group) is emitted when any J2EE file changes.
#
# OUTPUT:
#   - newFiles/ | modifiedFiles/ | deletedFiles/
#   - deployment-manifest.txt
#   - deployment-audit.txt
#   - metadata.json  (includes deploy_group flag)
#
# NOTE:
#   Used in CI phase only. Deployment handled separately by deploy-j2ee-sit.sh.
#
# AUTHOR: Kennedy Gatimu
# ==================================================================================================

# ---------------------------------------------------------------------------------------------------------------------
# STARTUP
# Print the program banner and capture the working directory used throughout the script.
# ---------------------------------------------------------------------------------------------------------------------
echo
echo "------------------------------- J2EE SIT CHANGE DETECTION PROGRAM STARTING -------------------------------"
echo "START TIME: $(date)"
echo

AZURE_WORKING_DIR=$(pwd)
echo "AZURE WORKING DIRECTORY: $AZURE_WORKING_DIR"
echo

# ---------------------------------------------------------------------------------------------------------------------
# ARTIFACT DIRECTORIES
# Staging directories where changed files are copied before being packaged into the build artifact.
# Recreated fresh on every CI run to avoid stale files from a previous build.
# ---------------------------------------------------------------------------------------------------------------------
NEW_FILES_DIR="$AZURE_WORKING_DIR/newFiles"
MODIFIED_FILES_DIR="$AZURE_WORKING_DIR/modifiedFiles"
DELETED_FILES_DIR="$AZURE_WORKING_DIR/deletedFiles"

# ---------------------------------------------------------------------------------------------------------------------
# OUTPUT FILES
# Files generated by this script and consumed by downstream pipeline stages.
# ---------------------------------------------------------------------------------------------------------------------
NEW_FILES_LIST=newFilesPath.txt           # lists all new file paths
MODIFIED_FILES_LIST=modifiedFilesPath.txt # lists all modified file paths
DELETED_FILES_LIST=deletedFilesPath.txt   # lists all deleted file paths
MANIFEST_FILE=deployment-manifest.txt     # one entry per changed file: CHANGE_TYPE|FILE_PATH
AUDIT_FILE=deployment-audit.txt           # full audit trail: CHANGE_TYPE|FILE_PATH|AUTHOR|COMMIT
METADATA_FILE=metadata.json               # JSON summary consumed by Azure pipeline routing logic
TEMP_DETAILS_FILE=fileDetails.tmp         # temporary file used to build the metadata files array

# ---------------------------------------------------------------------------------------------------------------------
# CONTROL FLAGS
# APP_FILTER   : set from the --app argument; controls which files is_j2ee_file() accepts.
#                fincore → fincore/custom/group/**   |   crm → crm/customization/group/**
# DEPLOY_GROUP : set true by detect_deployment_targets() when any J2EE file is detected;
#                written to metadata.json and used by the Azure pipeline routing logic.
# ---------------------------------------------------------------------------------------------------------------------
APP_FILTER=""
DEPLOY_GROUP=false

# ---------------------------------------------------------------------------------------------------------------------
# LOGGING UTILITIES
# log()        : prints an informational message with [INFO] prefix
# error_exit() : prints an [ERROR] message and immediately exits the script
# ---------------------------------------------------------------------------------------------------------------------
log() {
    echo "[INFO] $1"
}

error_exit() {
    echo "[ERROR] $1"
    echo "[ERROR] Script stopped at: $(date)"
    exit 1
}

# ---------------------------------------------------------------------------------------------------------------------
# FUNCTION: create_directory
#
# Ensures a clean directory exists at the given path.
# If it already exists, it is deleted and recreated — no stale files from a previous run.
#
# Arguments:
#   $1 dir_path : full path of the directory to create
# ---------------------------------------------------------------------------------------------------------------------
create_directory() {
    local dir_path=$1

    echo "------------------------------------------------------------"
    log "Creating directory: $dir_path"

    if [ -d "$dir_path" ]; then
        log "Directory already exists — recreating to ensure a clean state..."
        rm -rvf "$dir_path" || true
        mkdir -vp "$dir_path"
        log "Directory recreated: $dir_path"
    else
        mkdir -vp "$dir_path"
        log "Directory created: $dir_path"
    fi
    echo
}

# ---------------------------------------------------------------------------------------------------------------------
# FUNCTION: create_file
#
# Ensures a clean empty file exists at the given path.
# If it already exists, it is deleted and recreated — no stale content from a previous run.
#
# Arguments:
#   $1 file_path : full path of the file to create
# ---------------------------------------------------------------------------------------------------------------------
create_file() {
    local file_path=$1

    echo "------------------------------------------------------------"
    log "Creating file: $file_path"

    if [ -f "$file_path" ]; then
        log "File already exists — recreating to ensure a clean state..."
        rm -vf "$file_path" || true
        touch "$file_path"
        log "File recreated: $file_path"
    else
        touch "$file_path"
        log "File created: $file_path"
    fi
    echo
}

# ---------------------------------------------------------------------------------------------------------------------
# FUNCTION: is_j2ee_file
#
# Returns 0 (true) if the file belongs to this pipeline's J2EE SIT scope; 1 (false) otherwise.
# APP_FILTER (set from --app) ensures each CI pipeline only accepts its own app's files,
# preventing a mixed commit from causing both pipelines to deploy all files redundantly.
#
# Arguments:
#   $1 file_path : file path from git diff
# ---------------------------------------------------------------------------------------------------------------------
is_j2ee_file() {
    local file_path=$1

    [ -z "$file_path" ] && return 1  # silently skip blank lines produced by git diff output

    case "$APP_FILTER" in
        fincore) [[ "$file_path" == fincore/custom/group/* ]]      && return 0 ;;
        crm)     [[ "$file_path" == crm/customization/group/* ]]   && return 0 ;;
    esac

    log "  Skipping: $file_path — outside $APP_FILTER scope"
    return 1
}

# ---------------------------------------------------------------------------------------------------------------------
# FUNCTION: get_finacle_app
#
# Returns which Finacle app a file belongs to, based on its path prefix.
# The return value is echoed so it can be captured with $(...).
#
# Arguments:
#   $1 file_path : the file path to inspect
# ---------------------------------------------------------------------------------------------------------------------
get_finacle_app() {
    local file_path=$1

    if [[ "$file_path" == fincore/* ]]; then
        echo "fincore"
    elif [[ "$file_path" == crm/* ]]; then
        echo "crm"
    else
        echo "unknown"
    fi
}

# ---------------------------------------------------------------------------------------------------------------------
# FUNCTION: check_new_files
#
# Copies newly added files into the newFiles/ staging directory.
# Records each file in the manifest, audit log, and temp details file.
#
# Arguments:
#   $1 : newline-separated list of new file paths from git diff
# ---------------------------------------------------------------------------------------------------------------------
check_new_files() {
    local files_array
    local file_path
    local finacle_app

    echo "============================================================"
    echo "                 COPYING NEW FILES"
    echo "============================================================"

    log "New file(s) detected. Preparing staging directory: $NEW_FILES_DIR"

    [ ! -d "$NEW_FILES_DIR" ]   && create_directory "$NEW_FILES_DIR"
    [ ! -f "$NEW_FILES_LIST" ]  && create_file "$NEW_FILES_LIST"

    readarray -t files_array <<< "$1"

    for file_path in "${files_array[@]}"; do
        if is_j2ee_file "$file_path"; then
            if [ -f "$file_path" ]; then
                log "Copying NEW file : $file_path : $NEW_FILES_DIR"
                cp --parents "$file_path" "$NEW_FILES_DIR"

                echo "$file_path"                                       >> "$NEW_FILES_LIST"
                echo "NEW|$file_path"                                   >> "$MANIFEST_FILE"
                echo "NEW|$file_path|AUTHOR=$AUTHOR|COMMIT=$COMMIT_ID" >> "$AUDIT_FILE"

                finacle_app=$(get_finacle_app "$file_path")
                echo "$file_path|$finacle_app|NEW"                     >> "$TEMP_DETAILS_FILE"
            else
                log "WARNING: File listed in git diff but not found on disk — skipping: $file_path"
            fi
        fi
    done

    cp "$NEW_FILES_LIST" "$NEW_FILES_DIR"
    echo
}

# ---------------------------------------------------------------------------------------------------------------------
# FUNCTION: check_modified_files
#
# Copies modified files into the modifiedFiles/ staging directory.
# Records each file in the manifest, audit log, and temp details file.
#
# Arguments:
#   $1 : newline-separated list of modified file paths from git diff
# ---------------------------------------------------------------------------------------------------------------------
check_modified_files() {
    local files_array
    local file_path
    local finacle_app

    echo "============================================================"
    echo "                 COPYING MODIFIED FILES"
    echo "============================================================"

    log "Modified file(s) detected. Preparing staging directory: $MODIFIED_FILES_DIR"

    [ ! -d "$MODIFIED_FILES_DIR" ]   && create_directory "$MODIFIED_FILES_DIR"
    [ ! -f "$MODIFIED_FILES_LIST" ]  && create_file "$MODIFIED_FILES_LIST"

    readarray -t files_array <<< "$1"

    for file_path in "${files_array[@]}"; do
        if is_j2ee_file "$file_path"; then
            if [ -f "$file_path" ]; then
                log "Copying MODIFIED file : $file_path : $MODIFIED_FILES_DIR"
                cp --parents "$file_path" "$MODIFIED_FILES_DIR"

                echo "$file_path"                                            >> "$MODIFIED_FILES_LIST"
                echo "MODIFIED|$file_path"                                   >> "$MANIFEST_FILE"
                echo "MODIFIED|$file_path|AUTHOR=$AUTHOR|COMMIT=$COMMIT_ID" >> "$AUDIT_FILE"

                finacle_app=$(get_finacle_app "$file_path")
                echo "$file_path|$finacle_app|MODIFIED"                     >> "$TEMP_DETAILS_FILE"
            else
                log "WARNING: File listed in git diff but not found on disk — skipping: $file_path"
            fi
        fi
    done

    cp "$MODIFIED_FILES_LIST" "$MODIFIED_FILES_DIR"
    echo
}

# ---------------------------------------------------------------------------------------------------------------------
# FUNCTION: check_deleted_files
#
# Records deleted files in the manifest, audit log, and temp details.
# Deleted files no longer exist on disk — we only track their paths for the deploy script.
#
# Arguments:
#   $1 : newline-separated list of deleted file paths from git diff
# ---------------------------------------------------------------------------------------------------------------------
check_deleted_files() {
    local files_array
    local file_path
    local finacle_app

    echo "============================================================"
    echo "                 TRACKING DELETED FILES"
    echo "============================================================"

    log "Deleted file(s) detected. Preparing tracking directory: $DELETED_FILES_DIR"

    [ ! -d "$DELETED_FILES_DIR" ]   && create_directory "$DELETED_FILES_DIR"
    [ ! -f "$DELETED_FILES_LIST" ]  && create_file "$DELETED_FILES_LIST"

    readarray -t files_array <<< "$1"

    for file_path in "${files_array[@]}"; do
        if is_j2ee_file "$file_path"; then
            log "Tracking deleted file: $file_path"

            echo "$file_path"                                            >> "$DELETED_FILES_LIST"
            echo "DELETED|$file_path"                                    >> "$MANIFEST_FILE"
            echo "DELETED|$file_path|AUTHOR=$AUTHOR|COMMIT=$COMMIT_ID"  >> "$AUDIT_FILE"

            finacle_app=$(get_finacle_app "$file_path")
            echo "$file_path|$finacle_app|DELETED"                      >> "$TEMP_DETAILS_FILE"
        fi
    done

    cp "$DELETED_FILES_LIST" "$DELETED_FILES_DIR"
    echo
}

# ---------------------------------------------------------------------------------------------------------------------
# FUNCTION: detect_deployment_targets
#
# Scans the completed manifest and sets DEPLOY_GROUP=true if any J2EE file changed.
# In SIT all banks share one server — no per-bank routing is needed.
# Must be called AFTER all file change functions so the manifest is fully populated.
# ---------------------------------------------------------------------------------------------------------------------
detect_deployment_targets() {
    echo "============================================================"
    echo "         DETECTING DEPLOYMENT TARGET SERVER GROUPS"
    echo "============================================================"

    if [ ! -f "$MANIFEST_FILE" ]; then
        log "No manifest file found — skipping target detection."
        return
    fi

    if [ ! -s "$MANIFEST_FILE" ]; then
        log "Manifest file is empty — no $APP_FILTER J2EE files detected in this commit."
        return
    fi

    DEPLOY_GROUP=true
    log "J2EE files detected in manifest — Group server will be targeted."

    echo
    echo "------------------------------------------------------------"
    echo "DEPLOYMENT TARGET DETECTION RESULT"
    echo "------------------------------------------------------------"
    echo "  DEPLOY_GROUP : $DEPLOY_GROUP"
    echo "------------------------------------------------------------"
    echo

    echo "DEPLOY_GROUP=$DEPLOY_GROUP" >> "$AUDIT_FILE"
}

# =====================================================================================================================
# SCRIPT BODY — all functions are defined above; execution starts here
# =====================================================================================================================

# ---------------------------------------------------------------------------------------------------------------------
# STEP 0: PARSE AND VALIDATE ARGUMENTS
#
# --app fincore|crm  (required) — tells the script which app this CI pipeline is building.
# Argument parsing runs here (after function definitions) so log() and error_exit() are available.
# ---------------------------------------------------------------------------------------------------------------------
log "Parsing script arguments..."

while [ "$#" -gt 0 ]; do
    case "$1" in
        --app)
            APP_FILTER="$2"
            log "  --app : '$APP_FILTER'"
            shift 2 ;;
        *)
            error_exit "Unknown argument: '$1'. Usage: check-modified-files-sit.sh --app <fincore|crm>" ;;
    esac
done

if [ "$APP_FILTER" != "fincore" ] && [ "$APP_FILTER" != "crm" ]; then
    error_exit "Missing or invalid --app argument: '$APP_FILTER'. Expected: fincore | crm"
fi

log "  --app '$APP_FILTER' : valid — only '$APP_FILTER' files will be processed"
echo "APP FILTER   : $APP_FILTER"
echo

# ---------------------------------------------------------------------------------------------------------------------
# STEP 1: INITIALISE OUTPUT FILES
# Create manifest and audit files fresh on every run; clear any leftover temp data.
# ---------------------------------------------------------------------------------------------------------------------
create_file "$MANIFEST_FILE"
create_file "$AUDIT_FILE"
rm -f "$TEMP_DETAILS_FILE"              # clear any leftover temp data from a previous run

# ---------------------------------------------------------------------------------------------------------------------
# STEP 2: GATHER COMMIT INFORMATION
# git log -2 | tail -1 targets the developer's commit rather than the PR merge commit,
# which is always the most recent entry when merging into develop.
# ---------------------------------------------------------------------------------------------------------------------
COMMIT_ID=$(git log -2 --format=format:%h | tail -1)
BRANCH=${BUILD_SOURCEBRANCHNAME:-$(git rev-parse --abbrev-ref HEAD)}

# SIT always runs on the develop branch
if [[ "$BRANCH" == "develop" ]]; then ENV="SIT"
else                                  ENV="SIT (branch: $BRANCH)"
fi

AUTHOR=$(git show --pretty=format:"%an" "$COMMIT_ID" | head -1)
EMAIL=$(git show --pretty=format:"%ae" "$COMMIT_ID" | head -1)
COMMIT_MSG=$(git show --pretty=format:"%s"  "$COMMIT_ID" | head -1)
COMMIT_DATE=$(git show --pretty=format:"%cd" "$COMMIT_ID" | head -1)

echo "ENVIRONMENT  : $ENV"
echo "BRANCH       : $BRANCH"
echo "COMMIT       : $COMMIT_ID"
echo "AUTHOR       : $AUTHOR"
echo "AUTHOR EMAIL : $EMAIL"
echo "COMMIT MSG   : $COMMIT_MSG"
echo "COMMIT DATE  : $COMMIT_DATE"
echo

echo "ENV=$ENV"              >> "$AUDIT_FILE"
echo "COMMIT_ID=$COMMIT_ID"  >> "$AUDIT_FILE"
echo "AUTHOR=$AUTHOR"        >> "$AUDIT_FILE"

# ---------------------------------------------------------------------------------------------------------------------
# STEP 3: DETECT FILE CHANGES
# Queries git for each category of change in the developer's commit.
#   A = Added (new files)        C = Copied (new at destination — treated as NEW)
#   M = Modified                 D = Deleted
#   T = Type changed (e.g. symlink → regular file — treated as MODIFIED)
# ---------------------------------------------------------------------------------------------------------------------
NEW_FILES=$(git show --diff-filter=A --name-only --format="" "$COMMIT_ID")
COPY_FILES=$(git show --diff-filter=C --name-only --format="" "$COMMIT_ID")
MODIFIED_FILES=$(git show --diff-filter=M --name-only --format="" "$COMMIT_ID")
DELETED_FILES=$(git show --diff-filter=D --name-only --format="" "$COMMIT_ID")
TYPE_FILES=$(git show --diff-filter=T --name-only --format="" "$COMMIT_ID")

[ -n "$NEW_FILES" ]      && check_new_files      "$NEW_FILES"
[ -n "$COPY_FILES" ]     && check_new_files      "$COPY_FILES"      # copied = new file at destination
[ -n "$MODIFIED_FILES" ] && check_modified_files "$MODIFIED_FILES"
[ -n "$DELETED_FILES" ]  && check_deleted_files  "$DELETED_FILES"
[ -n "$TYPE_FILES" ]     && check_modified_files "$TYPE_FILES"

# ---------------------------------------------------------------------------------------------------------------------
# STEP 4: DETECT DEPLOYMENT TARGETS
# Must run AFTER all change detection so the manifest is fully populated.
# ---------------------------------------------------------------------------------------------------------------------
detect_deployment_targets

# ---------------------------------------------------------------------------------------------------------------------
# STEP 5: CREATE METADATA FILE
# Produces a JSON file consumed by the Azure pipeline routing logic to decide which
# CD release pipelines to trigger based on which server groups were affected.
# ---------------------------------------------------------------------------------------------------------------------
echo "============================================================"
echo "                 CREATING METADATA FILE"
echo "============================================================"

if [ -f "$NEW_FILES_LIST" ];      then NEW_COUNT=$(wc -l < "$NEW_FILES_LIST");           else NEW_COUNT=0;      fi
if [ -f "$MODIFIED_FILES_LIST" ]; then MODIFIED_COUNT=$(wc -l < "$MODIFIED_FILES_LIST"); else MODIFIED_COUNT=0; fi
if [ -f "$DELETED_FILES_LIST" ];  then DELETED_COUNT=$(wc -l < "$DELETED_FILES_LIST");   else DELETED_COUNT=0;  fi

log "New files      : $NEW_COUNT"
log "Modified files : $MODIFIED_COUNT"
log "Deleted files  : $DELETED_COUNT"
echo

{
echo "{"
echo "  \"application\": \"J2EE\","
echo "  \"buildTime\": \"$(date)\","
echo "  \"environment\": \"SIT\","
echo "  \"branch\": \"$BRANCH\","
echo "  \"commitId\": \"$COMMIT_ID\","
echo "  \"author\": \"$AUTHOR\","
echo "  \"email\": \"$EMAIL\","
echo "  \"message\": \"$COMMIT_MSG\","
echo "  \"commitDate\": \"$COMMIT_DATE\","
echo "  \"newFilesCount\": $NEW_COUNT,"
echo "  \"modifiedFilesCount\": $MODIFIED_COUNT,"
echo "  \"deletedFilesCount\": $DELETED_COUNT,"
echo "  \"deploy_group\": $DEPLOY_GROUP,"
echo "  \"files\": ["

if [ -f "$TEMP_DETAILS_FILE" ]; then
    awk -F'|' '{
        printf "    {\"path\":\"%s\",\"app\":\"%s\",\"type\":\"%s\"}", $1,$2,$3
        if (NR != total) printf ","
        printf "\n"
    }' total=$(wc -l < "$TEMP_DETAILS_FILE") "$TEMP_DETAILS_FILE"
fi

echo "  ]"
echo "}"
} > "$METADATA_FILE"

log "Metadata file created: $METADATA_FILE"
cat "$METADATA_FILE"
echo

# ---------------------------------------------------------------------------------------------------------------------
# EXECUTION SUMMARY
# ---------------------------------------------------------------------------------------------------------------------
echo
echo "============================================================"
echo "                     EXECUTION SUMMARY"
echo "============================================================"
echo "ENVIRONMENT : SIT"
echo "BRANCH      : $BRANCH"
echo "COMMIT ID   : $COMMIT_ID"
echo "AUTHOR      : $AUTHOR"
echo "DATE        : $COMMIT_DATE"
echo
echo "-------------------- FILE CHANGE COUNTS --------------------"
echo "NEW FILES      : $NEW_COUNT"
echo "MODIFIED FILES : $MODIFIED_COUNT"
echo "DELETED FILES  : $DELETED_COUNT"
echo
echo "-------------------- DEPLOYMENT TARGETS --------------------"
echo "DEPLOY GROUP   : $DEPLOY_GROUP"
echo "(SIT topology : all banks share one Group server)"
echo
echo "-------------------- FILE CHANGE DETAILS -------------------"
if [ -s "$MANIFEST_FILE" ]; then
    while IFS= read -r line; do
        FILE_CHANGE_TYPE=$(echo "$line" | cut -d'|' -f1)
        FILE_PATH=$(echo "$line" | cut -d'|' -f2)
        printf "[%-9s] %s\n" "$FILE_CHANGE_TYPE" "$FILE_PATH"
    done < "$MANIFEST_FILE"
else
    echo "No changes detected."
fi

echo
echo "============================================================"
echo "END TIME: $(date)"
echo "============================================================"
echo
