<%--
//Generated by Customization WB Generator
//Do not edit this file directly.
//Instead, modify the properties in the tool and regenerate.
--%>

<%@ page import="applcommon.ParseValue" %>
<%@ page import="com.infy.bbu.jsputil.*"%>
<%@ page import="java.util.Vector"%>
<%@ taglib uri="taglib.tld" prefix="arjsp" %>
<arjsp:init groupName="Customize" isEntryPoint="false" />

<%
	String sProfileId = ProfilesManager.getProfileInSession(session);
	String sSubGrpName = (String)ARJspCurr.getInput("subGroupName","");
	String sGrpName = ARJspCurr.getCurrentGroup();
	String pageName = (String)ARJspCurr.getInput("jspName","");
	String sPopUpExceptionWindow = (String)ARJspCurr.getInput(sGrpName+".PopUpExceptionWindow" ,"false");
	String sReferralMode = (String)ARJspCurr.getInput("refSubMode" ,"");
	ARJspCurr.setInput(sGrpName+".PopUpExceptionWindow","false");

%>
<script>

	var sPopUpExceptionWindow = '<%=ParseValue.checkString(sPopUpExceptionWindow)%>';
	var sReferralMode = '<%=ParseValue.checkString(sReferralMode)%>';
	var subGroupName = '<%=ParseValue.checkString(ARJspCurr.getInput("subGroupName",""))%>';
	var finIntDate = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".finIntDate",""))%>';
	var finInt = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".finInt",""))%>';
	var totLegInt = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".totLegInt",""))%>';
	var alreadyAdjAmt = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".alreadyAdjAmt",""))%>';
	var currentAdjAmt = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".currentAdjAmt",""))%>';
var crncyCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".crncyCode",""))%>';
	var loanOpAcct = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".loanOpAcct",""))%>';
	var rateCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".rateCode",""))%>';
	var funcCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".funcCode",""))%>';
	var lAcctId = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".lAcctId",""))%>';

</script>



<script language="javascript" src="../Renderer/javascripts/lists/showSearcher.js" > </script>
<script language="javascript" src="../Renderer/javascripts/custom_functions.js"></script>
<script language="javascript" src="../Renderer/javascripts/common_functions.js"></script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("cust_pre_evt.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("cust_evt.js",sProfileId)%>" > </script>

<script language="JavaScript">
</script>

<script language="JavaScript">
	printBlock();
	printFooterBlock();
</script>

