#!/bin/bash

# Export the Jasypt secret key as an environment variable
export CD_SPRING_DATASOURCE_URL="#{CD-SPRING-DATASOURCE-URL}#"
export CD_SPRING_DATASOURCE_USERNAME="#{CD-SPRING-DATASOURCE-USERNAME}#"
export CD_SPRING_DATASOURCE_PASSWORD="#{CD-SPRING-DATASOURCE-PASSWORD}#"
export CD_SSL_KEYSTORE_LOCATION="#{CD-SSL-KEYSTORE-LOCATION}#"
export CD_SSL_KEYSTORE_PASSWORD="#{CD-SSL-KEYSTORE-PASSWORD}#"
export CD_SSL_KEYSTORE_ALIAS="#{CD-SSL-KEYSTORE-ALIAS}#"

export CD_SECURITY_JWT_SECRET_KEY="#{CD-SECURITY-JWT-SECRET-KEY}#"
export CD_SECURITY_JWT_USERNAME="#{CD-SECURITY-JWT-USERNAME}#"
export CD_SECURITY_JWT_PASSWORD="#{CD-SECURITY-JWT-PASSWORD}#"
export CD_SECURITY_CHANNELS_CERTIFICATE_FOLDER="#{CD-SECURITY-CHANNELS-CERTIFICATE-FOLDER}#"
export CD_FINACLE_FI_ENDPOINT="#{CD-FINACLE-FI-ENDPOINT}#"

# Float dealer accounts for finacle over the counter float purchase
export UG_AIRTEL_F102="#{UG-AIRTEL-F102}#"
export TMT_WARID_FINACLE_F123="#{TMT-WARID-FINACLE-F123}#"
export KE_AIRTEL_TRUST_ACCOUNT="#{KE-AIRTEL-TRUST-ACCOUNT}#"
export RW_AIRTEL_TRUST_ACCOUNT="#{RW-AIRTEL-TRUST-ACCOUNT}#"
export SS_MTN_TRUST_ACCOUNT_SSP="#{SS-MTN-TRUST-ACCOUNT-SSP}#"
export CD_AIRTEL_TRUST_ACCOUNT_USD="#{CD-AIRTEL-TRUST-ACCOUNT-USD}#"
export CD_AIRTEL_TRUST_ACCOUNT_CDF="#{CD-AIRTEL-TRUST-ACCOUNT-CDF}#"
export CD_VODACOM_TRUST_ACCOUNT_USD="#{CD-VODACOM-TRUST-ACCOUNT-USD}#"
export CD_VODACOM_TRUST_ACCOUNT_CDF="#{CD-VODACOM-TRUST-ACCOUNT-CDF}#"
export KE_AIRTEL_TRUST_ACCOUNT_MSISDN="#{KE-AIRTEL-TRUST-ACCOUNT-MSISDN}#"

# Activate this once configured in vault
export CD_VODACOM_FLOAT_PURCHASE_CREDIT_USD_GL="#{CD-VODACOM-FLOAT-PURCHASE-CREDIT-USD-GL}#"
export CD_VODACOM_FLOAT_PURCHASE_CREDIT_CDF_GL="#{CD-VODACOM-FLOAT-PURCHASE-CREDIT-CDF-GL}#"
export CD_AIRTEL_FLOAT_PURCHASE_CREDIT_USD_GL="#{CD-AIRTEL-FLOAT-PURCHASE-CREDIT-USD-GL}#"
export CD_AIRTEL_FLOAT_PURCHASE_CREDIT_CDF_GL="#{CD-AIRTEL-FLOAT-PURCHASE-CREDIT-CDF-GL}#"
export KE_SAFARICOM_FLOAT_PURCHASE_CREDIT_KES_GL="#{KE-SAFARICOM-FLOAT-PURCHASE-CREDIT-KES-GL}#"
export KE_AIRTEL_FLOAT_PURCHASE_CREDIT_KES_GL="#{KE-AIRTEL-FLOAT-PURCHASE-CREDIT-KES-GL}#"
export SS_MTN_FLOAT_PURCHASE_CREDIT_SSP_GL="#{SS-MTN-FLOAT-PURCHASE-CREDIT-SSP-GL}#"
export CD_IMT_MONEYGRAM_GL="#{CD-IMT-MONEYGRAM-GL}#"

# Print a confirmation message
echo "Environment variables have been set."