package com.equitybank.drplatform.entity;

import com.equitybank.drplatform.enums.ChecklistItemStatus;
import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;
import java.util.UUID;

@Entity
@Table(name = "checklist_items", indexes = {
    @Index(name = "idx_checklist_campaign_app", columnList = "campaign_application_id"),
    @Index(name = "idx_checklist_status",       columnList = "status"),
    @Index(name = "idx_checklist_carried",      columnList = "carried_forward_from_id")
})
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ChecklistItemEntity extends AuditableEntity {

    @Column(name = "campaign_application_id", nullable = false)
    private UUID campaignApplicationId;

    @Column(name = "title", nullable = false, length = 300)
    private String title;

    @Enumerated(EnumType.STRING)
    @Column(name = "status", length = 30)
    @Builder.Default
    private ChecklistItemStatus status = ChecklistItemStatus.PENDING;

    @Column(name = "notes", columnDefinition = "TEXT")
    private String notes;

    // Self-reference stored as plain UUID — avoids circular JPA mapping
    @Column(name = "carried_forward_from_id")
    private UUID carriedForwardFromId;

    @Column(name = "carried_forward_at")
    private LocalDateTime carriedForwardAt;

    @Column(name = "acknowledged_by_id")
    private UUID acknowledgedById;

    @Column(name = "acknowledged_at")
    private LocalDateTime acknowledgedAt;

    @Column(name = "completed_by_id")
    private UUID completedById;

    @Column(name = "completed_at")
    private LocalDateTime completedAt;

    @Column(name = "is_auto_generated")
    @Builder.Default
    private Boolean isAutoGenerated = false;

    @Column(name = "sort_order")
    @Builder.Default
    private int sortOrder = 0;
}
