#SPRING JPA
#spring.jpa.database=mysql
spring.jpa.properties.hibernate.hbm2ddl.auto=update
spring.jpa.properties.hibernate.jdbc.batch_size = 50
spring.jpa.properties.hibernate.order_inserts = true
##Show SQL
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.format_sql=true
#
###SPRING DATA SOURCE
spring.datasource.url=${CD_SPRING_DATASOURCE_URL}
spring.datasource.username=${CD_SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${CD_SPRING_DATASOURCE_PASSWORD}
spring.datasource.driverClassName=oracle.jdbc.OracleDriver
spring.datasource.testOnBorrow=true
spring.datasource.validationQuery=SELECT 1 FROM DUAL
spring.hikari.poolName=Hikari
spring.hikari.auto-commit=false

vodacom.cd.b2c.loginUsername=${CD_VODACOM_B2C_LOGIN_USERNAME}
vodacom.cd.b2c.loginPassword=${CD_VODACOM_B2C_LOGIN_PASSWORD}
vodacom.cd.b2c.serviceProviderName=${CD_VODACOM_B2C_LOGIN_SERVICEPROVIDERNAME}
vodacom.cd.b2c.shortCode=${CD_VODACOM_B2C_SHORTCODE}
vodacom.cd.b2c.mock.scenario.login=success
vodacom.cd.b2c.mock.scenario.disbursement=success
vodacom.cd.b2c.callbackWaitingTime=20
vodacom.cd.b2c.loginURL=${CD_VODACOM_B2C_LOGIN_URL}
vodacom.cd.b2c.disbursementURL=${CD_VODACOM_B2C_DISBURSEMENT_URL}
vodacom.cd.b2c.callBackDestination=${CD_VODACOM_B2C_CALLBACK_URL}

vodacom.cd.b2b.loginUsername=${CD_VODACOM_B2B_LOGIN_USERNAME}
vodacom.cd.b2b.loginPassword=${CD_VODACOM_B2B_LOGIN_PASSWORD}
vodacom.cd.b2b.shortCode=${CD_VODACOM_B2B_SHORTCODE}
vodacom.cd.b2b.bankShortcode=${CD_VODACOM_B2B_BANKSHORTCODE}
vodacom.cd.b2b.callBackDestination=${CD_VODACOM_B2B_CALLBACK_URL}
vodacom.cd.b2b.callbackWaitingTime=20
vodacom.cd.b2b.loginURL=${CD_VODACOM_B2B_LOGIN_URL}
vodacom.cd.b2b.disbursementURL=${CD_VODACOM_B2B_DISBURSEMENT_URL}

vodacom.cd.airtime.pOSDeviceIDKey=${CD_VODACOM_AIRTIME_POS_DEVICE_ID_KEY}
vodacom.cd.airtime.pOSDeviceIDValue=${CD_VODACOM_AIRTIME_POS_DEVICE_ID_VALUE}
vodacom.cd.airtime.thirdPartId=${CD_VODACOM_AIRTIME_THIRDPARTYID}
vodacom.cd.airtime.password=${CD_VODACOM_AIRTIME_PASSWORD}
vodacom.cd.airtime.identifier=${CD_VODACOM_AIRTIME_IDENTIFIER}
vodacom.cd.airtime.shortCode=${CD_VODACOM_AIRTIME_SHORTCODE}
vodacom.cd.airtime.securityCredential=${CD_VODACOM_AIRTIME_SECURITYCREDENTIAL}
vodacom.cd.airtime.receiverPartyIdentifier=${CD_VODACOM_AIRTIME_RECEIVER_PARTY_IDENTIFIER}
vodacom.cd.airtime.callbackWaitingTime=10
vodacom.cd.airtime.mock.scenario.buy=success
vodacom.cd.airtime.whiteList=0986676678,243700000000
vodacom.cd.airtime.limit.USD=1.5
vodacom.cd.airtime.limit.CDF=3000
vodacom.cd.airtime.resultURL=${CD_VODACOM_AIRTIME_RESULT_URL}
vodacom.cd.airtime.requestURL=${CD_VODACOM_AIRTIME_REQUEST_URL}

cors.allowed.origin=http://localhost:5173

#EUREKA
eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=http://localhost:8581/eureka/

vodacom.cd.namecheck.tokenUsername=${CD_VODACOM_NAMECHECK_LOGIN_USERNAME}
vodacom.cd.namecheck.tokenPassword=${CD_VODACOM_NAMECHECK_LOGIN_PASSWORD}
vodacom.cd.namecheck.tokenUrl=${CD_VODACOM_NAMECHECK_TOKEN_URL}
vodacom.cd.namecheck.url=${CD_VODACOM_NAMECHECK_URL}
vodacom.cd.business.service.callbackURL=${CD_VODACOM_BUSINESS_SERVICE_CALLBACK_URL}

vodacom.cd.b2b.mock.loginURL=${CD_VODACOM_B2C_MOCK_LOGIN_URL}
vodacom.cd.b2b.mock.disbursementURL=${CD_VODACOM_B2C_MOCK_DISBURSEMENT_URL}
vodacom.cd.b2b.mock.callBackDestination=${CD_VODACOM_B2C_MOCK_CALLBACK_URL}
vodacom.cd.b2b.mock.testNumber=243800000000