#SPRING JPA
#spring.jpa.database=mysql
spring.jpa.properties.hibernate.hbm2ddl.auto=update
spring.jpa.properties.hibernate.jdbc.batch_size = 50
spring.jpa.properties.hibernate.order_inserts = true
##Show SQL
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.format_sql=true
#
###SPRING DATA SOURCE
spring.datasource.url=jdbc:mysql://localhost:3306/c4testdb?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.testOnBorrow=true
spring.datasource.validationQuery=SELECT 1 FROM DUAL
spring.hikari.poolName=Hikari
spring.hikari.auto-commit=false

vodacom.cd.b2c.loginUsername=test
vodacom.cd.b2c.loginPassword=test
vodacom.cd.b2c.serviceProviderName=Equity
vodacom.cd.b2c.shortCode=245245
vodacom.cd.b2c.mock.scenario.login=success
vodacom.cd.b2c.mock.scenario.disbursement=success
vodacom.cd.b2c.callbackWaitingTime=5
vodacom.cd.b2c.loginURL=http://localhost:8085/insight/SOAPIn
vodacom.cd.b2c.disbursementURL=http://localhost:8085/iPG/B2C
vodacom.cd.b2c.callBackDestination=http://localhost:8085/api/v1/vodacom/b2c/callback

vodacom.cd.b2b.loginUsername=test
vodacom.cd.b2b.loginPassword=test
vodacom.cd.b2b.shortCode=245245
vodacom.cd.b2b.bankShortcode=245245
vodacom.cd.b2b.callBackDestination=http://localhost:8085/api/v1/vodacom/b2b/callback"
vodacom.cd.b2b.callbackWaitingTime=20
vodacom.cd.b2b.loginURL=http://localhost:8085/insight/B2BLogin
vodacom.cd.b2b.disbursementURL=http://localhost:8085/insight/B2B

vodacom.cd.airtime.pOSDeviceIDKey=POSDeviceID
vodacom.cd.airtime.pOSDeviceIDValue=POS234789
vodacom.cd.airtime.thirdPartId=10086
vodacom.cd.airtime.password=test
vodacom.cd.airtime.identifier=345345
vodacom.cd.airtime.shortCode=345345
vodacom.cd.airtime.securityCredential=57668779988989
vodacom.cd.airtime.receiverPartyIdentifier=10086
vodacom.cd.airtime.callbackWaitingTime=10
vodacom.cd.airtime.mock.scenario.buy=success
vodacom.cd.airtime.whiteList=0986676678,243700000000
vodacom.cd.airtime.limit.USD=1.5
vodacom.cd.airtime.limit.CDF=3000
vodacom.cd.airtime.resultURL=http://localhost:8085/api/vodacom/airtimetopupcallback"
vodacom.cd.airtime.requestURL=http://localhost:8085/external/airtime/buy

cors.allowed.origin=http://localhost:5173

#EUREKA
eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=http://localhost:8762/eureka/

#vodacom.cd.namecheck.tokenUsername=uat
#vodacom.cd.namecheck.tokenPassword=R7$wY9xt*bdQ%26z5w

vodacom.cd.namecheck.tokenUsername=test
vodacom.cd.namecheck.tokenPassword=test
vodacom.cd.namecheck.tokenUrl=http://localhost:8085/oauth/v1
vodacom.cd.namecheck.url=http://localhost:8085/api/v1
vodacom.cd.business.service.callbackURL=https://10.11.6.110:8443/api/v1/b2c/callback

vodacom.cd.b2b.mock.loginURL=http://localhost:8085/insight/SOAPIn
vodacom.cd.b2b.mock.disbursementURL=http://localhost:8085/iPG/B2C
vodacom.cd.b2b.mock.callBackDestination=http://localhost:8085/api/v1/vodacom/b2c/callback
vodacom.cd.b2b.mock.testNumber=0811000000


safaricom.ke.b2b.checkSum=CheckSum0
safaricom.ke.b2b.shortCode=100001
safaricom.ke.b2b.password=Password0
safaricom.ke.b2b.queueTimeoutURL=http://localhost:8085/api/v1/safaricom/b2b/queuetimeout/callback
safaricom.ke.b2b.resultURL=http://localhost:8085/api/v1/safaricom/b2b/callback
safaricom.ke.b2b.securityCredentialPublicKey=-----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA8rM5lxew7fQsdEsQWhwI0iwE45YioA/2BGvURO2+I5sB/q7EYrBWypmkmuX/dkx5yKh2m6sLDIDV/4LH7IHzGpKDiNxyA2Y2hRNsYtYYNiVmMZdyDd89r4fY+MuwLs5UK4o0Cd7nInMgUlCXSMTiEGtGYOTGW81gH6ZVWTL83HKu/F3VKHLSG1qcVGuXQiBlm1s4JxWkaSrN8DOPs2HnlcOJP37VE+2Evb1ewRaO4/qEbrYaV+6B0CySNwkYoRnnfDjOosQD+ewVik3aBqVnwVqX+0MrPhlRoa3VNGWSYreuM2xpQagpqol5EJB23GIIXG7QQbwQVHrt5J4u9S3Z7wIDAQAB-----END PUBLIC KEY-----
safaricom.ke.b2b.serviceId=107031000
safaricom.ke.b2b.spId=107031
safaricom.ke.b2b.spPassword=Safaricom123!
safaricom.ke.b2b.thirdPartyID=broker_4
safaricom.ke.b2b.username=username
safaricom.ke.b2b.debitPartyShortCode=100001
safaricom.ke.b2b.requestURL=http://localhost:8085/mminterface/request
safaricom.ke.b2b.callbackWaitingTime=10
safaricom.ke.b2b.mock.scenario.disbursement=success