#SPRING JPA
#spring.jpa.database=mysql
spring.jpa.properties.hibernate.hbm2ddl.auto=update
spring.jpa.properties.hibernate.jdbc.batch_size = 50
spring.jpa.properties.hibernate.order_inserts = true
##Show SQL
spring.jpa.properties.hibernate.show_sql=false
spring.jpa.properties.hibernate.use_sql_comments=false
spring.jpa.properties.hibernate.format_sql=false
#
###SPRING DATA SOURCE
spring.datasource.url=${CD_SPRING_DATASOURCE_URL}
spring.datasource.username=${CD_SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${CD_SPRING_DATASOURCE_PASSWORD}
spring.datasource.driverClassName=oracle.jdbc.OracleDriver
spring.datasource.testOnBorrow=true
spring.datasource.validationQuery=SELECT 1 FROM DUAL
spring.hikari.poolName=Hikari
spring.hikari.auto-commit=false



africell.cd.disbursement.url=${CD_AFRICELL_B2C_DISBURSEMENT_URL}
africell.cd.token.url=${CD_AFRICELL_B2C_TOKEN_URL}
africell.cd.token.registrationURL=${CD_AFRICELL_B2C_REGISTRATION_URL}

africell.cd.token.consumerKey=${CD_AFRICELL_B2C_CONSUMERKEY}
africell.cd.token.consumerSecret=${CD_AFRICELL_B2C_CONSUMERSECRET}

africell.cd.registration.token.consumerKey=${CD_AFRICELL_B2C_REGISTRATION_CONSUMERKEY}
africell.cd.registration.token.consumerSecret=${CD_AFRICELL_B2C_REGISTRATION_CONSUMERSECRET}
africell.cd.registration.token.url=${CD_AFRICELL_B2C_REGISTRATION_TOKEN_URL}

africell.cd.airtime.url=${CD_AFRICELL_AIRTIME_URL}
africell.cd.userID=${CD_AFRICELL_AIRTIME_USERID}
africell.cd.username=${CD_AFRICELL_AIRTIME_USERNAME}
africell.cd.password=${CD_AFRICELL_AIRTIME_PASSWORD}
africell.cd.airtime.bankId=${CD_AFRICELL_AIRTIME_BANKID}
africell.cd.b2c.bankAccounNumber=060107658120076
africell.cd.b2c.registrationEnabled=true

africell.cd.mock.token=false

#EUREKA
eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=http://localhost:8581/eureka/

#logging.level.ROOT=DEBUG
#logging.level.org.apache.http=DEBUG
#logging.level.com.equitybankgroup.payments.b2c.tech_b2c_africell_cd_ms.service.business=DEBUG
#logging.level.com.netflix.discovery.DiscoveryClient=INFO



