trigger:
  - release
  - main

variables:
  tag: '$(Build.BuildId)'
  #  vmImageName: 'ubuntu-latest'
  vmImageName: 'mngd-devops-pool'
  azureSubscription: 'Enterprise Core'
  uatKeyVaultName: 'kv-uat-omnichannel'
  prodKeyVaultName: 'kv-preprod-omnichannel'

  # Change these values as required
  JAVA_VERSION: '1.25'
  APP_NAME: 'papss-outbound-technical-service-ms-0.0.1-SNAPSHOT.jar'

stages:
  - stage: BuildUAT
    condition: and(always(), contains(variables['Build.SourceBranch'], 'refs/heads/release'))
    displayName: UAT
    variables:
      ENVIRONMENT: 'uat'
    jobs:
      - job: Build
        displayName: Build
        pool:
          # vmImage: $(vmImageName)
          name: $(vmImageName)
        steps:
          - task: AzureKeyVault@2
            displayName: 'Connect To Azure UAT KeyVault'
            inputs:
              azureSubscription: $(azureSubscription)
              KeyVaultName: $(uatKeyVaultName)
              SecretsFilter: '*'
              RunAsPreJob: false

          - task: replacetokens@5
            displayName: 'Replace Azure KeyVault Tokens'
            inputs:
              folderPath: '$(System.DefaultWorkingDirectory)'
              targetFiles: |
                # **/*uat.yml
                # **/*uat.properties
                # **/*dev.yml
                # **/*dev.properties
                pipelines/java_env/uat/*.sh
              encoding: 'auto'
              writeBOM: true
              actionOnMissing: 'warn'
              keepToken: false
              tokenPrefix: '#{'
              tokenSuffix: '}#'
              useLegacyPattern: false
              enableTransforms: false
              enableTelemetry: true

          - script: |
              echo "Downloading Temurin JDK 25..."
              
              # Create a destination folder inside the pipeline workspace
              mkdir -p $(Pipeline.Workspace)/jvm/temurin-25-jdk-amd64
              
              # Download JDK 25 tarball from Adoptium
              wget -q https://github.com/adoptium/temurin25-binaries/releases/download/jdk-25.0.1%2B8/OpenJDK25U-jdk_x64_linux_hotspot_25.0.1_8.tar.gz -O jdk25.tar.gz
              
              # Extract it into the destination folder
              tar -xzf jdk25.tar.gz -C $(Pipeline.Workspace)/jvm/temurin-25-jdk-amd64 --strip-components=1
              
              # Verify the installation
              $(Pipeline.Workspace)/jvm/temurin-25-jdk-amd64/bin/java -version
              
              # Export JDK25_DIR as a pipeline variable so other tasks can use it
              echo "##vso[task.setvariable variable=JDK25_DIR]$(Pipeline.Workspace)/jvm/temurin-25-jdk-amd64"
            displayName: "Install Java 25"

          - script: 'rm -rf ~/.m2/repository'
            displayName: 'Delete Maven Local Repository'

          # This task is optional. Comment if not needed
          - task: Maven@4
            displayName: 'Maven Install ojdbc dependency'
            inputs:
              mavenPomFile: 'pom.xml'
              mavenOptions: '-Xmx3072m'
              goals: 'install:install-file'
              # options: '-Dfile="ojdbc6-11.2.0.3.jar" -DgroupId="com.oracle" -DartifactId="ojdbc6" -Dversion="11.2.0.3" -Dpackaging=jar'
              options: '-Dfile="ojdbc11-23.9.0.25.07.jar" -DgroupId="com.oracle.database.jdbc" -DartifactId="ojdbc11" -Dversion="23.9.0.25.07" -Dpackaging=jar'
              javaHomeOption: 'Path'
              jdkDirectory: '$(JDK25_DIR)'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false

          - task: Maven@4
            displayName: 'Maven Clean Install'
            inputs:
              mavenPomFile: 'pom.xml'
              options: '-Dspring.profiles.active=uat -DskipTests'
              javaHomeOption: 'Path'
              jdkDirectory: '$(JDK25_DIR)'
              mavenVersionOption: 'Default'
              publishJUnitResults: false
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false
              goals: clean install

          - task: Bash@3
            displayName: Running Azure-Pipelines-Helper Script
            inputs:
              targetType: 'filePath'
              filePath: 'pipelines/scripts/azure-pipelines-helper.sh'
            env:
              APP_NAME: $(APP_NAME)
              ENVIRONMENT: $(ENVIRONMENT)
              BUILD_ARTIFACTS_STAGING_DIR: $(Build.ArtifactStagingDirectory)

          - task: CopyFiles@2
            displayName: Copy application-deployment.sh To Staging Directory
            inputs:
              SourceFolder: '$(System.DefaultWorkingDirectory)/pipelines/scripts'
              Contents: |
                application-deployment.sh
              TargetFolder: '$(Build.ArtifactStagingDirectory)'

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'uat_drop'
              publishLocation: 'Container'

  - stage: BuildPROD
    condition: and(always(), contains(variables['Build.SourceBranch'], 'refs/heads/main'))
    displayName: PROD
    variables:
      ENVIRONMENT: 'prod'
    jobs:
      - job: Build
        displayName: Build
        pool:
          # vmImage: $(vmImageName)
          name: $(vmImageName)
        steps:
          - task: AzureKeyVault@2
            displayName: 'Connect To Azure Prod KeyVault'
            inputs:
              azureSubscription: $(azureSubscription)
              KeyVaultName: $(prodKeyVaultName)
              SecretsFilter: '*'
              RunAsPreJob: false

          - task: replacetokens@5
            displayName: 'Replace Azure KeyVault Tokens'
            inputs:
              folderPath: '$(System.DefaultWorkingDirectory)'
              targetFiles: |
                # **/*uat.yml
                # **/*uat.properties
                # **/*dev.yml
                # **/*dev.properties
                pipelines/java_env/prod/*.sh
              encoding: 'auto'
              writeBOM: true
              actionOnMissing: 'warn'
              keepToken: false
              tokenPrefix: '#{'
              tokenSuffix: '}#'
              useLegacyPattern: false
              enableTransforms: false
              enableTelemetry: true

          - script: |
              echo "Downloading Temurin JDK 25..."
              
              # Create a destination folder inside the pipeline workspace
              mkdir -p $(Pipeline.Workspace)/jvm/temurin-25-jdk-amd64
              
              # Download JDK 25 tarball from Adoptium
              wget -q https://github.com/adoptium/temurin25-binaries/releases/download/jdk-25.0.1%2B8/OpenJDK25U-jdk_x64_linux_hotspot_25.0.1_8.tar.gz -O jdk25.tar.gz
              
              # Extract it into the destination folder
              tar -xzf jdk25.tar.gz -C $(Pipeline.Workspace)/jvm/temurin-25-jdk-amd64 --strip-components=1
              
              # Verify the installation
              $(Pipeline.Workspace)/jvm/temurin-25-jdk-amd64/bin/java -version
              
              # Export JDK25_DIR as a pipeline variable so other tasks can use it
              echo "##vso[task.setvariable variable=JDK25_DIR]$(Pipeline.Workspace)/jvm/temurin-25-jdk-amd64"
            displayName: "Install Java 25"

          - script: 'rm -rf ~/.m2/repository'
            displayName: 'Delete Maven Local Repository'

          # This task is optional. Comment if not needed
          - task: Maven@4
            displayName: 'Maven Install ojdbc dependency'
            inputs:
              mavenPomFile: 'pom.xml'
              mavenOptions: '-Xmx8192m'
              goals: 'install:install-file'
              # options: '-Dfile="ojdbc6-11.2.0.3.jar" -DgroupId="com.oracle" -DartifactId="ojdbc6" -Dversion="11.2.0.3" -Dpackaging=jar'
              options: '-Dfile="ojdbc11-23.9.0.25.07.jar" -DgroupId="com.oracle.database.jdbc" -DartifactId="ojdbc11" -Dversion="23.9.0.25.07" -Dpackaging=jar'
              javaHomeOption: 'Path'
              jdkDirectory: '$(JDK25_DIR)'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false

          - task: Maven@4
            displayName: 'Maven Clean Install'
            inputs:
              mavenPomFile: 'pom.xml'
              options: '-Dspring.profiles.active=prod -DskipTests'
              javaHomeOption: 'Path'
              jdkDirectory: '$(JDK25_DIR)'
              mavenVersionOption: 'Default'
              publishJUnitResults: false
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false
              goals: clean install

          - task: Bash@3
            displayName: Running Azure-Pipelines-Helper Script
            inputs:
              targetType: 'filePath'
              filePath: 'pipelines/scripts/azure-pipelines-helper.sh'
            env:
              APP_NAME: $(APP_NAME)
              ENVIRONMENT: $(ENVIRONMENT)
              BUILD_ARTIFACTS_STAGING_DIR: $(Build.ArtifactStagingDirectory)

          - task: CopyFiles@2
            displayName: Copy application-deployment.sh To Staging Directory
            inputs:
              SourceFolder: '$(System.DefaultWorkingDirectory)/pipelines/scripts'
              Contents: |
                application-deployment.sh
              TargetFolder: '$(Build.ArtifactStagingDirectory)'

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'prod_drop'
              publishLocation: 'Container'
