version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: papss-postgres
    restart: always
    environment:
      POSTGRES_USER: papss_user
      POSTGRES_PASSWORD: papss_pass
      POSTGRES_DB: papss_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - papss-net

  papss-app:
    image: kengatimu/papss-outbound-technical-service:latest
    container_name: papss-outbound-technical-service-ms
    restart: always
    depends_on:
      - postgres
    ports:
      - "10443:10443"
    environment:
      SPRING_PROFILE: uat
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/papss_db
      SPRING_DATASOURCE_USERNAME: papss_user
      SPRING_DATASOURCE_PASSWORD: papss_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - papss-net

volumes:
  postgres_data:

networks:
  papss-net:
    driver: bridge
