SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[banks](
	[id] [numeric](19, 0) NOT NULL,
	[bank_id] [varchar](255) NULL,
	[bank_name] [varchar](255) NULL,
	[bank_status] [varchar](255) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[banks] ADD PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
