1. Table: banks

insert into [dbo].[banks] (bank_id, bank_name, bank_status) values ('0001', 'KCB', 'ONLINE');
insert into [dbo].[banks] (bank_id, bank_name, bank_status) values ('0002', 'Stanchart', 'ONLINE'); 
insert into [dbo].[banks] (bank_id, bank_name, bank_status) values ('0003', 'ABSA', 'ONLINE'); 
insert into [dbo].[banks] (bank_id, bank_name, bank_status) values ('0005', 'Bank of India', 'OFFLINE'); 
insert into [dbo].[banks] (bank_id, bank_name, bank_status) values ('0006', 'Bank of Baroda', 'OFFLINE'); 
insert into [dbo].[banks] (bank_id, bank_name, bank_status) values ('0007', 'NCBA', 'ONLINE'); 
insert into [dbo].[banks] (bank_id, bank_name, bank_status) values ('0010', 'Prime Bank', 'ONLINE'); 
insert into [dbo].[banks] (bank_id, bank_name, bank_status) values ('0011', 'Coop Bank', 'ONLINE'); 
insert into [dbo].[banks] (bank_id, bank_name, bank_status) values ('0012', 'NBK', 'ONLINE');
insert into [dbo].[banks] (bank_id, bank_name, bank_status) values ('0014', 'M-Oriental', 'ONLINE'); 
insert into [dbo].[banks] (bank_id, bank_name, bank_status) values ('0016', 'Citi Bank', 'ONLINE'); 
insert into [dbo].[banks] (bank_id, bank_name, bank_status) values ('0017', 'Habib Bank AG Zurich', 'OFFLINE'); 
insert into [dbo].[banks] (bank_id, bank_name, bank_status) values ('0018', 'Middle East Bank', 'ONLINE'); 
insert into [dbo].[banks] (bank_id, bank_name, bank_status) values ('0019', 'Bank of Africa', 'ONLINE'); 
insert into [dbo].[banks] (bank_id, bank_name, bank_status) values ('0023', 'Consolidated', 'ONLINE'); 
insert into [dbo].[banks] (bank_id, bank_name, bank_status) values ('0025', 'Credit Bank', 'ONLINE'); 
insert into [dbo].[banks] (bank_id, bank_name, bank_status) values ('0026', 'Access Bank', 'OFFLINE'); 
insert into [dbo].[banks] (bank_id, bank_name, bank_status) values ('0031', 'Stanbic Bank', 'ONLINE'); 
insert into [dbo].[banks] (bank_id, bank_name, bank_status) values ('0035', 'ABC Bank', 'ONLINE'); 
insert into [dbo].[banks] (bank_id, bank_name, bank_status) values ('0043', 'Eco Bank', 'OFFLINE'); 
insert into [dbo].[banks] (bank_id, bank_name, bank_status) values ('0049', 'SPIRE Bank', 'OFFLINE'); 
insert into [dbo].[banks] (bank_id, bank_name, bank_status) values ('0050', 'Paramount', 'ONLINE'); 
insert into [dbo].[banks] (bank_id, bank_name, bank_status) values ('0051', 'Kingdom Bank', 'ONLINE'); 
insert into [dbo].[banks] (bank_id, bank_name, bank_status) values ('0053', 'Gt Bank', 'ONLINE');
insert into [dbo].[banks] (bank_id, bank_name, bank_status) values ('0054', 'Victoria Bank', 'ONLINE'); 
insert into [dbo].[banks] (bank_id, bank_name, bank_status) values ('0055', 'Guardian Bank', 'ONLINE'); 
insert into [dbo].[banks] (bank_id, bank_name, bank_status) values ('0057', 'I&M Bank', 'ONLINE'); 
insert into [dbo].[banks] (bank_id, bank_name, bank_status) values ('0059', 'Development Bank', 'OFFLINE'); 
insert into [dbo].[banks] (bank_id, bank_name, bank_status) values ('0060', 'SBM', 'OFFLINE'); 
insert into [dbo].[banks] (bank_id, bank_name, bank_status) values ('0061', 'Housing finance', 'ONLINE'); 
insert into [dbo].[banks] (bank_id, bank_name, bank_status) values ('0063', 'DTB', 'ONLINE'); 
insert into [dbo].[banks] (bank_id, bank_name, bank_status) values ('0065', 'Mayfair Bank', 'ONLINE'); 
insert into [dbo].[banks] (bank_id, bank_name, bank_status) values ('0066', 'Sidian Bank', 'ONLINE'); 
insert into [dbo].[banks] (bank_id, bank_name, bank_status) values ('0068', 'Equity Bank', 'ONLINE'); 
insert into [dbo].[banks] (bank_id, bank_name, bank_status) values ('0070', 'Family Bank', 'ONLINE'); 
insert into [dbo].[banks] (bank_id, bank_name, bank_status) values ('0072', 'Gulf African Bank', 'ONLINE'); 
insert into [dbo].[banks] (bank_id, bank_name, bank_status) values ('0074', 'First Community Bank', 'ONLINE'); 
insert into [dbo].[banks] (bank_id, bank_name, bank_status) values ('0075', 'DIB Bank', 'ONLINE'); 
insert into [dbo].[banks] (bank_id, bank_name, bank_status) values ('0076', 'UBA', 'OFFLINE');
insert into [dbo].[banks] (bank_id, bank_name, bank_status) values ('0078', 'KWFT', 'ONLINE'); 
insert into [dbo].[banks] (bank_id, bank_name, bank_status) values ('0079', 'Faulu Bank', 'OFFLINE'); 
insert into [dbo].[banks] (bank_id, bank_name, bank_status) values ('0099', 'Post Bank', 'OFFLINE'); 
insert into [dbo].[banks] (bank_id, bank_name, bank_status) values ('9999', 'IPS (Instant Payment Switch)', 'ONLINE'); 
insert into [dbo].[banks] (bank_id, bank_name, bank_status) values ('0086', 'Vooma', 'OFFLINE'); 
insert into [dbo].[banks] (bank_id, bank_name, bank_status) values ('0087', 'Pesapal', 'OFFLINE'); 
insert into [dbo].[banks] (bank_id, bank_name, bank_status) values ('0088', 'Interswitch', 'OFFLINE'); 
insert into [dbo].[banks] (bank_id, bank_name, bank_status) values ('0089', 'Stima Sacco', 'ONLINE'); 
insert into [dbo].[banks] (bank_id, bank_name, bank_status) values ('0091', 'Flutterwave', 'OFFLINE'); 
insert into [dbo].[banks] (bank_id, bank_name, bank_status) values ('0092', 'iPay', 'OFFLINE'); 
insert into [dbo].[banks] (bank_id, bank_name, bank_status) values ('0093', 'KCBbulk', 'OFFLINE'); 
insert into [dbo].[banks] (bank_id, bank_name, bank_status) values ('0095', 'MFS', 'OFFLINE'); 
insert into [dbo].[banks] (bank_id, bank_name, bank_status) values ('0097', 'Telkom Kenya', 'ONLINE'); 
insert into [dbo].[banks] (bank_id, bank_name, bank_status) values ('0037', 'Cellulant', 'OFFLINE');