######################################################################
# KYC_RECERT_APPROACH   - DAYS for KYC Recertification Approaching Status
# KYC_RECERT_RETAIL     - Default recertification period (MONTHS) - Retail
# KYC_RECERT_CORP       - Default recertification period (MONTHS) - Corporate
# Variables can have any natural number.
# KYC_RECERT_RETAIL  and KYC_RECERT_CORP should be greater than KYC_RECERT_APPROACH (when converted to days) .
# DAYS_FOR_NOTICE_EFFECTIVE - No of Days for Calculation of Effective Date from Received Date for Tax 
# OPTIN_WITEM_ASSIGNEE  - The corresponding agent id to whom the workitem needs to be assignes should be specified
# OPTIN_PREF_AFFILIATES_EXPIRY_PERIOD - The number of DAYS in which CIF’s opt in preference for affiliates is about to expire.
# KYC_RECERT_EXPIRY_PERIOD - No of DAYS in which CIF’s KYC recertification is about to expire.


###################################################################### 
# Values HIGH,MODERATE,LOW are in monthe and are related to risk rating which is used to get the KYCReviewDate
#INC0141064 CHANGING TO 12,36,AND 60 FROM 6,3 AND 1 BY SILVESTER.M.KISALU
HIGH=12
MODERATE=36
LOW=60
KYC_RECERT_APPROACH = 30
KYC_RECERT_RETAIL = 36  
KYC_RECERT_CORP = 36  
DAYS_FOR_NOTICE_EFFECTIVE = 50
OPTIN_WITEM_DUE_DAYS= 30  
OPTIN_WITEM_ASSIGNEE= srmBOObj:AgentBO/AgentBO.agentID:1 
OPTIN_WITEM_REMARKS= Work Item For Privacy Details 
OPTIN_PREF_AFFILIATES_EXPIRY_PERIOD = 30 
KYC_RECERT_EXPIRY_PERIOD = 30 

###################################################################### 
# Changes in .jrxml file for RI Reports 
# The values set for OPTIN_PREF_AFFILIATES_EXPIRY_PERIOD and KYC_RECERT_EXPIRY_PERIOD in this properties file should also be updated 
# in .jrxml file for RI Reports. The clause in which the value needs to be modified is also specified(Instead of variable name specified in [ ], 
# specify its corresponding value from this properties file). 
# Variable Name                                                                 .jrxml File Name 
# KYC_RECERT_EXPIRY_PERIOD                                                      Corp_Prospect_KYC_Exp_Report 
#                                                                               Corp_Customer_KYC_Exp_Report 
#                                                                               Retail_Prospect_KYC_Exp_Report 
#                                                                               Retail_Customer_KYC_Exp_Report 
#                                                                               Retail_Contact_KYC_Exp_Report 
# WHERE clause: 
# ((aml.kyc_recertdate - SYSDATE) < [KYC_RECERT_EXPIRY_PERIOD]) 
# 
# OPTIN_PREF_AFFILIATES_EXPIRY_PERIOD                                           RetCust_OptIn_Expiring_Report 
# 
# WHERE clause: 
# (ADD_MONTHS (aml.date_pref_affiliates, srm.jndi_value) <(SYSDATE + [OPTIN_PREF_AFFILIATES_EXPIRY_PERIOD])) 
###################################################################### 
