<!---------------------------------------------------------------------------------------------------------------->
<!--Name              : cicrm_det_ginc.jsp
<!--Description       : This jsp will get few field values from criteria page of CICRM menu,
<!--Date              : 20-02-2013
<!--Author            : Shishira
<!--Called By         : None
<!--Calling jsp       : None
<!--Menu Option       : CICRM.
<!--Modification History:
<!--    Version No.              Date           Author                       Description
<!--    ---------               ----------      ---------------              --------------------
<!--     0.1                    20-02-2012      Shilpa                    Original version
<!---------------------------------------------------------------------------------------------------------------->

<%--
//Generated by Customization WB Generator
//Do not edit this file directly.
//Instead, modify the properties in the tool and regenerate.
--%>

<%@ page import="applcommon.ParseValue" %>
<%@ page import="com.infy.bbu.jsputil.*"%>
<%@ taglib uri="taglib.tld" prefix="arjsp" %>
<arjsp:init groupName="Customize" isEntryPoint="false" />

<%
	String sProfileId = ProfilesManager.getProfileInSession(session);
	String sSubGrpName = (String)ARJspCurr.getInput("subGroupName","");
	String sGrpName = ARJspCurr.getCurrentGroup();
	String sPopUpExceptionWindow = (String)ARJspCurr.getInput(sGrpName+".PopUpExceptionWindow" ,"false");
	String sReferralMode = (String)ARJspCurr.getInput("refSubMode" ,"");
	ARJspCurr.setInput(sGrpName+".PopUpExceptionWindow","false");

        



%>



<script>

	var sPopUpExceptionWindow = '<%=sPopUpExceptionWindow%>';
	var sReferralMode = '<%=sReferralMode%>' ;

	var subGroupName = '<%=ParseValue.checkString(ARJspCurr.getInput("subGroupName",""))%>';
	var fileName = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".fileName",""))%>';
	var filePath = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".filePath",""))%>';
       var Function= '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".Function",""))%>';
	var Originator= '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".Originator",""))%>';
       var FileName= '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".FileName",""))%>';
       var Dracno= '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".Dracno",""))%>';
       var Test = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".Test",""))%>';
       var ChargeCode= '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".ChargeCode",""))%>';
      var funcCode = 'R';


      

</script>

<script language="javascript" src="../Renderer/javascripts/lists/showAccountIdList.js" > </script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("cust_evt.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("core_banking.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("resource_functions.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("common_functions.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showCurrency.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showCustId.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showSchmCodes.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showSolId.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showSearcher.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showRefCode.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/custom/javascripts/custom_functions.js"></script>
<script language="javascript" src="../javascripts/custom_common_functions.js"></script>
<script language="javascript" src="../Renderer/custom/javascripts/cust_fetch_list.js"></script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("cust_pre_evt.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("cust_evt.js",sProfileId)%>" > </script>
<script language="Javascript" src="../custom/javascripts/custom_common_functions.js" > </script>

<script language="JavaScript">
	printBlock();
	printFooterBlock();
</script>


