SET DEFINE OFF;
Insert into CUSTOM.C_CPARAM_VALUE_TABLE
   (PARAMETER_ID,LEVELCODE_1, PARAMETER_VALUE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID, MODULE_NAME)
 Values
    ('CONBACID','ALL', '01110', 'Y', 'N', 'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE, '56', 'ISLM');

Insert into CUSTOM.C_CPARAM_VALUE_TABLE
   (PARAMETER_ID,LEVELCODE_1, PARAMETER_VALUE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID, MODULE_NAME)
 Values
    ('ISLBACID','ALL', '01120', 'Y', 'N', 'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE, '56', 'ISLM');

Insert into CUSTOM.C_CPARAM_VALUE_TABLE
   (PARAMETER_ID,LEVELCODE_1, PARAMETER_VALUE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID, MODULE_NAME)
 Values
    ('ISLM_ERROR_01','ALL', 'Cursor opening failed', 'Y', 'N', 'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE, '56', 'ISLM');

Insert into CUSTOM.C_CPARAM_VALUE_TABLE
   (PARAMETER_ID, LEVELCODE_1,PARAMETER_VALUE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID, MODULE_NAME)
 Values
    ('ISLM_ERROR_02','ALL', 'Fetching sol id,ccy and gl sub head code from GSH table failed', 'Y', 'N', 'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE, '56', 'ISLM');

Insert into CUSTOM.C_CPARAM_VALUE_TABLE
   (PARAMETER_ID,LEVELCODE_1, PARAMETER_VALUE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID, MODULE_NAME)
 Values
    ('ISLM_ERROR_03','ALL', 'CONBACID - Conventional Contra Placeholder not setup in CPARAM', 'Y', 'N', 'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE, '56', 'ISLM');

Insert into CUSTOM.C_CPARAM_VALUE_TABLE
   (PARAMETER_ID,LEVELCODE_1, PARAMETER_VALUE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID, MODULE_NAME)
 Values
    ('ISLM_ERROR_04', 'ALL','ISLBACID - Islamic Contra Placeholder not setup in CPARAM', 'Y', 'N', 'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE, '56', 'ISLM');

Insert into CUSTOM.C_CPARAM_VALUE_TABLE
   (PARAMETER_ID, LEVELCODE_1,PARAMETER_VALUE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID, MODULE_NAME)
 Values
    ('ISLM_ERROR_05', 'ALL','Could not fetch Conventional GL account Id for Bacid', 'Y', 'N', 'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE, '56', 'ISLM');

Insert into CUSTOM.C_CPARAM_VALUE_TABLE
   (PARAMETER_ID, LEVELCODE_1,PARAMETER_VALUE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID, MODULE_NAME)
 Values
    ('ISLM_ERROR_06','ALL', 'Could not fetch Islamic GL account Id for Bacid', 'Y', 'N', 'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE, '56', 'ISLM');

Insert into CUSTOM.C_CPARAM_VALUE_TABLE
   (PARAMETER_ID, LEVELCODE_1,PARAMETER_VALUE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID, MODULE_NAME)
 Values
    ('ISLM_ERROR_07', 'Could not fetch total credit transaction amount from DTD table', 'Y', 'N', 'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE, '56', 'ISLM');

Insert into CUSTOM.C_CPARAM_VALUE_TABLE
   (PARAMETER_ID,LEVELCODE_1, PARAMETER_VALUE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID, MODULE_NAME)
 Values
    ('ISLM_ERROR_08','ALL', 'Could not fetch total debit transaction amount from DTD table', 'Y', 'N', 'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE, '56', 'ISLM');

Insert into CUSTOM.C_CPARAM_VALUE_TABLE
   (PARAMETER_ID,LEVELCODE_1, PARAMETER_VALUE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID, MODULE_NAME)
 Values
    ('ISLM_ERROR_09','ALL', 'Could not insert data in custom table', 'Y', 'N', 'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE, '56', 'ISLM');

COMMIT;
