CREATE TABLE CUSTOM.C_UPLD_EQT_TBL
(
  UPLD_FILE_NAME  VARCHAR2(50 BYTE),
  UPLD_SRL_NUM    NUMBER,
  STATUS          CHAR(1 BYTE),
  STATUS_DESC     VARCHAR2(100 BYTE),
  TRAN_ID         VARCHAR2(15 BYTE),
  BANK_ID         VARCHAR2(10 BYTE),
  RCRE_TIME       DATE,
  RCRE_USER_ID    VARCHAR2(20 BYTE),
  DEL_FLG         CHAR(1 BYTE),
  PROCESS_ID      VARCHAR2(50 BYTE)
);


CREATE UNIQUE INDEX CUSTOM.C_UPLD_EQT_TBL_IDX ON CUSTOM.C_UPLD_EQT_TBL
(UPLD_FILE_NAME, UPLD_SRL_NUM, PROCESS_ID);


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON CUSTOM.C_UPLD_EQT_TBL TO TBAADM;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON CUSTOM.C_UPLD_EQT_TBL TO TBAGEN;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON CUSTOM.C_UPLD_EQT_TBL TO TBAUTIL;
