DROP TABLE CUSTOM.CUBP_REMOTE_TEMPLATE_TBL CASCADE CONSTRAINTS;

CREATE TABLE CUSTOM.CUBP_REMOTE_TEMPLATE_TBL
(
  TEMPLATE_ID  VARCHAR2(30 CHAR),
  REQ_XML      CLOB,
  RES_XML      CLOB
)
/
CREATE UNIQUE INDEX CUSTOM.CUBP_REMOTE_TEMPLATE_TBL_PK ON CUSTOM.CUBP_REMOTE_TEMPLATE_TBL
(TEMPLATE_ID)
/

DROP SYNONYM CUSTOM.C_CUBPR;

CREATE SYNONYM CUSTOM.C_CUBPR FOR CUSTOM.CUBP_REMOTE_TEMPLATE_TBL;


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON CUSTOM.CUBP_REMOTE_TEMPLATE_TBL TO TBAADM;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON CUSTOM.CUBP_REMOTE_TEMPLATE_TBL TO TBAGEN;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON CUSTOM.CUBP_REMOTE_TEMPLATE_TBL TO TBAUTIL;
