<%--
//Generated by Customization WB Generator
//Do not edit this file directly.
//Instead, modify the properties in the tool and regenerate.
--%>
<%@ page import="finbranchUtil.*" %>
<%@ page import="applcommon.ParseValue" %>
<%@ page import="com.infy.bbu.jsputil.*"%>
<%@ page import="FABCommon.SecurityInfo70"%>
<%@ taglib uri="taglib.tld" prefix="arjsp" %>
<arjsp:init groupName="Customize" isEntryPoint="false" />

<%
	String sProfileId = ProfilesManager.getProfileInSession(session);
	String sSubGrpName = (String)ARJspCurr.getInput("subGroupName","");
	String sGrpName = ARJspCurr.getCurrentGroup();
	String sPopUpExceptionWindow = (String)ARJspCurr.getInput(sGrpName+".PopUpExceptionWindow" ,"false");
	String sReferralMode = (String)ARJspCurr.getInput("refSubMode" ,"");
	ARJspCurr.setInput(sGrpName+".PopUpExceptionWindow","false");
	SecurityInfo70 securityInfo = (SecurityInfo70)session.getAttribute("FinUserInfo");



String refNum = "";

if(("V".equals(ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".funcCode",""))))||("X".equals(ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".funcCode","")))))
{
finbranchUtil.MenuMiscInfo menuMiscInfo = (finbranchUtil.MenuMiscInfo)ARJspCurr.getInput(finbranchUtil.MenuMiscInfo.getObjectName(), null);
        if (menuMiscInfo != null)
                                {
 refNum = ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".refNum",""));
menuMiscInfo.setRefNum(refNum);
                                }
}


%>
<script>

	var sPopUpExceptionWindow = '<%=sPopUpExceptionWindow%>';
	var sReferralMode = '<%=sReferralMode%>' ;

	var subGroupName = '<%=ParseValue.checkString(ARJspCurr.getInput("subGroupName",""))%>';
	var BODDate= "<%=(securityInfo.bodDate).substring(0,10)%>";
	var contextSolId = '<%=ParseValue.checkString(securityInfo.contextSolId)%>';
	var funcCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".funcCode",""))%>';
	var zoneCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".zoneCode",""))%>';
	var zoneCcy = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".zoneCcy",""))%>';
	var zoneDate = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".zoneDate",""))%>';
	var setNum = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".setNum",""))%>';
	var status = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".status",""))%>';
	var creditEntity = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".creditEntity",""))%>';
	var creditEntityDesc = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".creditEntityDesc",""))%>';
	var crAcctNum = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".crAcctNum",""))%>';
	var crAcctNumEntityId = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".crAcctNumEntityId",""))%>';
	var crAcctNumSolId = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".crAcctNumSolId",""))%>';
	var crAcctNumCcy = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".crAcctNumCcy",""))%>';
	var crAcctName = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".crAcctName",""))%>';
	var chargeEventId = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".chargeEventId",""))%>';
	var chargeAmt = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".chargeAmt",""))%>';
	var chargeAmtCcy = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".chargeAmtCcy",""))%>';
	var nostroAcct = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".nostroAcct",""))%>';
	var vostroAcct = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".vostroAcct",""))%>';
	var valueDate = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".valueDate",""))%>';
        var payingAcct = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".payingAcct",""))%>';
        var targetZoneCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".targetZoneCode",""))%>';
	var targetZoneDate = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".targetZoneDate",""))%>';
        var targetSolId = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".targetSolId",""))%>';
	var targetSetNum = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".targetSetNum",""))%>';
        var tranParticular = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".tranParticular",""))%>';
        var tranRmks = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".tranRmks",""))%>';
	var instrumentEntity = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".instrumentEntity",""))%>';
        var instrumentEntityDesc = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".instrumentEntityDesc",""))%>';
	var instrumentAlpha = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".instrumentAlpha",""))%>';
        var instrumentDate = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".instrumentDate",""))%>';
        var instrumentNum = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".instrumentNum",""))%>';
	var instrumentAmt = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".instrumentAmt",""))%>';
	var instrumentAmtCcy = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".instrumentAmtCcy",""))%>';
	var instrumentBankCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".instrumentBankCode",""))%>';
        var instrumentBranchCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".instrumentBranchCode",""))%>';
        var instrumentSortCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".instrumentSortCode",""))%>';
	var instrumentBankName = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".instrumentBankName",""))%>';
        var instrumentBranchName = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".instrumentBranchName",""))%>';

	var entity1TranId = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".entity1TranId",""))%>';
	var entity1TranDate = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".entity1TranDate",""))%>';
	var entity2TranId = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".entity2TranId",""))%>';
        var entity2TranDate = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".entity2TranDate",""))%>';
	var chargeTranId = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".chargeTranId",""))%>';
        var chargeTranDate = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".chargeTranDate",""))%>';
	var rejectReasonCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".rejectReasonCode",""))%>';
	
	var valType = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".valType",""))%>';
	var billPayYes = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".billPayYes",""))%>';
	var billerCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".billerCode",""))%>';
	var billerId = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".billerId",""))%>';
	var billRefNum = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".billRefNum",""))%>';
	var typOfServ = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".typOfServ",""))%>';
	var critCrAcctNum = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".critCrAcctNum",""))%>';
	var critCrAcctBnkId = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".critCrAcctBnkId",""))%>';
	var name = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".name",""))%>';
	//var tranPart = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".tranPart",""))%>';
	//var tranRem = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".tranRem",""))%>';
	var refNumHidden = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".refNumHidden",""))%>';
	var retStrngValHid = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".retStrngValHid",""))%>';
	var appCatgry = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".appCatgry",""))%>';
	var freetext1 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".freetext1",""))%>';
	var freetext2 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".freetext2",""))%>';
	var freetext3 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".freetext3",""))%>';
	var freetext4 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".freetext4",""))%>';
	var freetext5 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".freetext5",""))%>';
	var freetext6 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".freetext6",""))%>';
	var freetext7 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".freetext7",""))%>';
	var refDesc = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".refDesc",""))%>';
	var riskNote = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".riskNote",""))%>';
	
	
	if(funcCode=='V' || funcCode =='X'){
        	isAuditEnabled="true";
        }


</script>

<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showAccountIdList.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("getRefCodeList.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showRateCodes.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showRefCode.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("getInstrTypeList.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showZoneCode.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showRejReasonList.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("common_functions.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/custom/javascripts/<%=VRPKeys.getFile("custom_functions.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/custom/javascripts/uieclg/<%=VRPKeys.getFile("getBillDetailSectionIECLG.js",sProfileId)%>"></script>



<script language="JavaScript">
	printBlock();
	printFooterBlock();
</script>

