<%--
//Generated by Customization WB Generator
//Do not edit this file directly.
//Instead, modify the properties in the tool and regenerate.
--%>

<%@ page import="applcommon.ParseValue" %>
<%@ page import="com.infy.bbu.jsputil.*"%>
<%@ taglib uri="taglib.tld" prefix="arjsp" %>
<arjsp:init groupName="Customize" isEntryPoint="false" />

<%
	String sProfileId = ProfilesManager.getProfileInSession(session);
	String sSubGrpName = (String)ARJspCurr.getInput("subGroupName","");
%>
<script>

	var Message = '<%=ParseValue.checkString(ARJspCurr.getInputWithGroup("RESULT_MSG",""))%>';

	var token = Message.split("!");
        if(token != undefined){
		var i = 0;
                Message = token[i];
		var funcCode = token[i+=1];
                var zoneCode = token[i+=1];
                var zoneDate = token[i+=1];
                var solId = token[i+=1];
                var setNum = token[i+=1];
		var targetZoneCode = token[i+=1];
		var targetZoneDate = token[i+=1];
		var targetSolId = token[i+=1];
		var targetSetNum = token[i+=1];
		if(funcCode == "R"){
			var entity1TranId = token[i+=1];
			var entity1TranDate = token[i+=1];
			var entity2TranId = token[i+=1];
			var entity2TranDate = token[i+=1]; 
		}
		if(funcCode == "V"){
			var chargeTranId = token[i+=1];
			var chargeTranDate = token[i+=1];
		}
        }

</script>



<script language="JavaScript">
	printBlock();
	printFooterBlock();
</script>

