<%--
//Generated by Customization WB Generator
//Do not edit this file directly.
//Instead, modify the properties in the tool and regenerate.
--%>

<%@ page import="applcommon.ParseValue" %>
<%@ page import="com.infy.bbu.jsputil.*"%>
<%@ page import="java.util.Vector"%>
<%@ taglib uri="taglib.tld" prefix="arjsp" %>
<arjsp:init groupName="Customize" isEntryPoint="false" />

<%
	String sProfileId = ProfilesManager.getProfileInSession(session);
	String sSubGrpName = (String)ARJspCurr.getInput("subGroupName","");
	String sGrpName = ARJspCurr.getCurrentGroup();
	String pageName = (String)ARJspCurr.getInput("jspName","");
	String sPopUpExceptionWindow = (String)ARJspCurr.getInput(sGrpName+".PopUpExceptionWindow" ,"false");
	String sReferralMode = (String)ARJspCurr.getInput("refSubMode" ,"");
	ARJspCurr.setInput(sGrpName+".PopUpExceptionWindow","false");

%>
<script>

	var sPopUpExceptionWindow = '<%=sPopUpExceptionWindow%>';
	var sReferralMode = '<%=sReferralMode%>' ;

	var subGroupName = '<%=ParseValue.checkString(ARJspCurr.getInput("subGroupName",""))%>';
	var noteDenom01 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".noteDenom01",""))%>';
	var coinDenom01 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".coinDenom01",""))%>';
	var noteDenom02 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".noteDenom02",""))%>';
	var coinDenom02 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".coinDenom02",""))%>';
	var noteDenom03 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".noteDenom03",""))%>';
	var coinDenom03 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".coinDenom03",""))%>';
	var noteDenom04 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".noteDenom04",""))%>';
	var coinDenom04 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".coinDenom04",""))%>';
	var noteDenom05 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".noteDenom05",""))%>';
	var coinDenom05 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".coinDenom05",""))%>';
	var noteDenom06 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".noteDenom06",""))%>';
	var coinDenom06 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".coinDenom06",""))%>';
	var noteDenom07 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".noteDenom07",""))%>';
	var coinDenom07 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".coinDenom07",""))%>';
	var noteDenom08 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".noteDenom08",""))%>';
	var coinDenom08 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".coinDenom08",""))%>';
	var noteDenom09 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".noteDenom09",""))%>';
	var coinDenom09 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".coinDenom09",""))%>';
	var noteDenom10 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".noteDenom10",""))%>';
	var coinDenom10 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".coinDenom10",""))%>';
	var noteDenom11 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".noteDenom11",""))%>';
	var coinDenom11 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".coinDenom11",""))%>';
	var noteDenom12 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".noteDenom12",""))%>';
	var coinDenom12 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".coinDenom12",""))%>';
	var noteDenom13 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".noteDenom13",""))%>';
	var coinDenom13 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".coinDenom13",""))%>';
	var noteDenom14 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".noteDenom14",""))%>';
	var coinDenom14 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".coinDenom14",""))%>';
	var noteDenom15 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".noteDenom15",""))%>';
	var coinDenom15 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".coinDenom15",""))%>';
	var funcCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".funcCode",""))%>';
	var crncyCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".crncyCode",""))%>';
	var crncyName = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".crncyName",""))%>';
	var decimalPointAllow = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".decimalPointAllow",""))%>';

</script>


<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("cust_pre_evt.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("cust_post_evt.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("common_functions.js",sProfileId)%>"></script>

<script language="JavaScript">
	printBlock();
	printFooterBlock();
</script>

