#!/bin/bash

# Database configs
export CD_SPRING_DATASOURCE_URL="#{CD-SPRING-DATASOURCE-URL}#"
export CD_SPRING_DATASOURCE_USERNAME="#{CD-SPRING-DATASOURCE-USERNAME}#"
export CD_SPRING_DATASOURCE_PASSWORD="#{SPRING-DATASOURCE-PASSWORD}#"

# SSL configs
export CD_SSL_KEYSTORE_LOCATION="#{CD-SSL-KEYSTORE-LOCATION}#"
export CD_SSL_KEYSTORE_PASSWORD="#{CD-SSL-KEYSTORE-PASSWORD}#"
export CD_SSL_KEYSTORE_ALIAS="#{CD-SSL-KEYSTORE-ALIAS}#"

# Security configs
export CD_SECURITY_JWT_SECRET_KEY="#{CD-SECURITY-JWT-SECRET-KEY}#"
export CD_SECURITY_JWT_USERNAME="#{CD-SECURITY-JWT-USERNAME}#"
export CD_SECURITY_JWT_PASSWORD="#{CD-SECURITY-JWT-PASSWORD}#"
export CD_SECURITY_CHANNELS_CERTIFICATE_FOLDER="#{CD-SECURITY-CHANNELS-CERTIFICATE-FOLDER}#"
#export CD_FINACLE_FI_ENDPOINT="#{CD-FINACLE-FI-ENDPOINT}#"
#export CD_FINACLE_FI_ENDPOINT='https://finacledevdrc.ebsafrica.com:11500/FIWEBSERVICE/services/FIUsbWebService'
export CD_FINACLE_FI_ENDPOINT='https://finaclepreprodweb.ebsafrica.com:11500/FISERVLET/fihttp'

# TODO - Activate this after vault update: Float dealer accounts for finacle over the counter float purchase
#export UG_AIRTEL_F102="#{UG-AIRTEL-F102}#"
#export TMT_WARID_FINACLE_F123="#{TMT-WARID-FINACLE-F123}#"
#export KE_AIRTEL_TRUST_ACCOUNT="#{KE-AIRTEL-TRUST-ACCOUNT}#"
#export RW_AIRTEL_TRUST_ACCOUNT="#{RW-AIRTEL-TRUST-ACCOUNT}#"
#export SS_MTN_TRUST_ACCOUNT_SSP="#{SS-MTN-TRUST-ACCOUNT-SSP}#"
#export CD_AIRTEL_TRUST_ACCOUNT_USD="#{CD-AIRTEL-TRUST-ACCOUNT-USD}#"
#export CD_AIRTEL_TRUST_ACCOUNT_CDF="#{CD-AIRTEL-TRUST-ACCOUNT-CDF}#"
#export CD_VODACOM_TRUST_ACCOUNT_USD="#{CD-VODACOM-TRUST-ACCOUNT-USD}#"
#export CD_VODACOM_TRUST_ACCOUNT_CDF="#{CD-VODACOM-TRUST-ACCOUNT-CDF}#"
#export KE_AIRTEL_TRUST_ACCOUNT_MSISDN="#{KE-AIRTEL-TRUST-ACCOUNT-MSISDN}#"

# TODO - Deactivate this after vault update: Float dealer accounts for finacle over the counter float purchase
export UG_AIRTEL_F102="1000650050512"
export TMT_WARID_FINACLE_F123="1003100652439"
export KE_AIRTEL_TRUST_ACCOUNT="0810262907103"
export RW_AIRTEL_TRUST_ACCOUNT="4012200414004"
export SS_MTN_TRUST_ACCOUNT_SSP="2011211330816"
export CD_AIRTEL_TRUST_ACCOUNT_USD="010184069120050"
export CD_AIRTEL_TRUST_ACCOUNT_CDF="010184069110156"
export CD_VODACOM_TRUST_ACCOUNT_USD="010183946120267"
export CD_VODACOM_TRUST_ACCOUNT_CDF="010183946110276"
export KE_AIRTEL_TRUST_ACCOUNT_MSISDN="254788723486"

# TODO Float purchase GLs -- Activate this once configured in vault
#export CD_VODACOM_FLOAT_PURCHASE_CREDIT_USD_GL="#{CD-VODACOM-FLOAT-PURCHASE-CREDIT-USD-GL}#"
#export CD_VODACOM_FLOAT_PURCHASE_CREDIT_CDF_GL="#{CD-VODACOM-FLOAT-PURCHASE-CREDIT-CDF-GL}#"
#export CD_AIRTEL_FLOAT_PURCHASE_CREDIT_USD_GL="#{CD-AIRTEL-FLOAT-PURCHASE-CREDIT-USD-GL}#"
#export CD_AIRTEL_FLOAT_PURCHASE_CREDIT_CDF_GL="#{CD-AIRTEL-FLOAT-PURCHASE-CREDIT-CDF-GL}#"
#export KE_SAFARICOM_FLOAT_PURCHASE_CREDIT_KES_GL="#{KE-SAFARICOM-FLOAT-PURCHASE-CREDIT-KES-GL}#"
#export KE_AIRTEL_FLOAT_PURCHASE_CREDIT_KES_GL="#{KE-AIRTEL-FLOAT-PURCHASE-CREDIT-KES-GL}#"
#export SS_MTN_FLOAT_PURCHASE_CREDIT_SSP_GL="#{SS-MTN-FLOAT-PURCHASE-CREDIT-SSP-GL}#"

# TODO Remove this once records are updated in the vault
export CD_VODACOM_FLOAT_PURCHASE_CREDIT_USD_GL="010183946120267"
export CD_VODACOM_FLOAT_PURCHASE_CREDIT_CDF_GL="010183946110276"
export CD_AIRTEL_FLOAT_PURCHASE_CREDIT_USD_GL="010184069120050"
export CD_AIRTEL_FLOAT_PURCHASE_CREDIT_CDF_GL="010184069110156"
export KE_SAFARICOM_FLOAT_PURCHASE_CREDIT_KES_GL="0810262907103"
export KE_AIRTEL_FLOAT_PURCHASE_CREDIT_KES_GL="0810262907103"
export SS_MTN_FLOAT_PURCHASE_CREDIT_SSP_GL="2011211330816"

# Print a confirmation message
echo "Environment variables have been set."