spring:
  application:
    name: mtn-money-b2c-ms
  profiles:
    active: uat

eureka:
  instance:
    hostname: mtn-money-b2c-ms
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8581/eureka/

#actuator configs
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true #for gracefully shutting down the app - http://localhost:<PortNumber>/actuator/shutdown
    health:
      show-details: when_authorized
  info:
    env:
      enabled: true