logging:
  level:
    ROOT: INFO
    org.hibernate: INFO
    com.equitybank.gag.telco_b2c: INFO
    com.netflix.discovery.DiscoveryClient: INFO

server:
  port: 8501
  ssl:
    key-store: ${SS_MTN_SSL_KEYSTORE_LOCATION}
    key-store-password: ${SS_MTN_SSL_KEYSTORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: ${SS_MTN_SSL_KEYSTORE_ALIAS}

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: ${CD_SPRING_DATASOURCE_URL}
    username: ${CD_SPRING_DATASOURCE_USERNAME}
    password: ${CD_SPRING_DATASOURCE_PASSWORD}
    hikari:
      poolName: Hikari
      auto-commit: false
      maximum-pool-size: 30
      minimum-idle: 10
      idle-timeout: 30000  # Close idle connections after 30s
      connection-timeout: 20000  # Wait max 20s for a connection
      max-lifetime: 1800000  # Recycle connections every 30 mins
      # leak-detection-threshold: 15000  # Detect leaked connections after 15s
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 500
        prepStmtCacheSqlLimit: 4096
        useServerPrepStmts: true
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.Oracle12cDialect
      ddl-auto: update
    show-sql: false

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

mtn:
  ss:
    credentials:
      username: ${SS_MTN_AUTH_USERNAME}
      password: ${SS_MTN_AUTH_PASSWORD}
    float:
      buy:
        url: ${SS_MTN_BUY_FLOAT_URL}
      status:
        url: ${SS_MTN_FLOAT_STATUS_URL}
    namecheck:
      url: ${SS_MTN_FLOAT_NAMECHECK_URL}