<%--
//Generated by Customization WB Generator
//Do not edit this file directly.
//Instead, modify the properties in the tool and regenerate.
--%>

<%@ page import="applcommon.ParseValue" %>
<%@ page import="com.infy.bbu.jsputil.*"%>
<%@ taglib uri="taglib.tld" prefix="arjsp" %>

<%!
        public static final String _ARJSP_JSP_NAME = "cdpsp/cdpsp_det_ginc.jsp";
%>

<%@ include file="../../finbranch_common.jsp" %>
<arjsp:init groupName="Customize" isEntryPoint="false" />

<%
	String sProfileId = ProfilesManager.getProfileInSession(session);
	String sSubGrpName = (String)ARJspCurr.getInput("subGroupName","");
	String sGrpName = ARJspCurr.getCurrentGroup();
	String sPopUpExceptionWindow = (String)ARJspCurr.getInput(sGrpName+".PopUpExceptionWindow" ,"false");
	String sReferralMode = (String)ARJspCurr.getInput("refSubMode" ,"");
	ARJspCurr.setInput(sGrpName+".PopUpExceptionWindow","false");
	FABCommon.SecurityInfo70        securityInfo    = (FABCommon.SecurityInfo70)session.getAttribute("FinUserInfo");

%>
<script>

	var sPopUpExceptionWindow = '<%=sPopUpExceptionWindow%>';
	var sReferralMode = '<%=sReferralMode%>' ;
	var subGroupName = '<%=ParseValue.checkString(ARJspCurr.getInput("subGroupName",""))%>';
	var acctNum= '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".acctNum",""))%>';
	var frmdate_ui = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".frmdate_ui",""))%>';
	var todate = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".todate_ui",""))%>';
	//var noOfPages = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".noOfPages",""))%>';
	var BODDate = '<%=(securityInfo.bodDate).substring(0,10)%>';
</script>

<%@include file='../../javascripts/core_signature.js'%>

<script language="javascript" src="../Renderer/javascripts/lists/showAccountIdList.js" > </script>
<script language="javascript" src="../Renderer/custom/javascripts/custom_functions.js"></script>
<script language="javascript" src="../Renderer/custom/javascripts/common_functions.js"></script>
<script language="javascript" src="../Renderer/custom/javascripts/custom_common_functions.js"></script>
<script language="javascript" src="../Renderer/custom/javascripts/cust_fetch_list.js"></script>

<script language="JavaScript">
	printBlock();
	printFooterBlock();
</script>
