var cngentrnLocObj ={
	Validate_MANDATORY:"N", 
	Validate_ENABLED:"enabled", 
	Ok_MANDATORY:"N", 
	Ok_ENABLED:"enabled", 
	Go_MANDATORY:"N", 
	Go_ENABLED:"enabled", 
	funcCode_MANDATORY:"N", 
	funcCode_ENABLED:"enabled", 
	drAccount_MANDATORY:"N", 
	drAccount_ENABLED:"enabled", 
	Cancel_MANDATORY:"N", 
	Cancel_ENABLED:"enabled", 
	acctName_MANDATORY:"N",
	acctName_ENABLED:"enabled", 
	solId_MANDATORY:"N",
	solId_ENABLED:"enabled", 
	crncyCode_MANDATORY:"N",
	crncyCode_ENABLED:"enabled", 
	
	crAcctName_MANDATORY:"N",
	crAcctName_ENABLED:"enabled", 
	crSolId_MANDATORY:"N",
	crSolId_ENABLED:"enabled", 
	crCrncyCode_MANDATORY:"N",
	crCrncyCode_ENABLED:"enabled", 
	
	maxApproverLmtAmt_MANDATORY:"N", 
	maxApproverLmtAmt_ENABLED:"enabled", 
	tempMaxApproverLmtAmt_MANDATORY:"N", 
	tempMaxApproverLmtAmt_ENABLED:"enabled", 
	effectiveDate_MANDATORY:"N", 
	effectiveDate_ENABLED:"enabled",  
	effectiveDate_ui_MANDATORY:"N", 
	effectiveDate_ui_ENABLED:"enabled", 
	Clear_ENABLED:"enabled", 
	Clear_MANDATORY:"N", 
	Submit_MANDATORY:"N", 
	Submit_ENABLED:"enabled" 
	};
var cngentrnProps =  new Properties(cngentrnLocObj);
