<%--
//Generated by Customization WB Generator
//Do not edit this file directly.
//Instead, modify the properties in the tool and regenerate.
--%>

<%@ page import="applcommon.ParseValue" %>
<%@ page import="com.infy.bbu.jsputil.*"%>
<%@ page import="java.util.Vector"%>
<%@ taglib uri="taglib.tld" prefix="arjsp" %>
<arjsp:init groupName="Customize" isEntryPoint="false" />

<%
	String sProfileId = ProfilesManager.getProfileInSession(session);
	String sSubGrpName = (String)ARJspCurr.getInput("subGroupName","");
	String sGrpName = ARJspCurr.getCurrentGroup();
	String pageName = (String)ARJspCurr.getInput("jspName","");
	String sPopUpExceptionWindow = (String)ARJspCurr.getInput(sGrpName+".PopUpExceptionWindow" ,"false");
	String sReferralMode = (String)ARJspCurr.getInput("refSubMode" ,"");
	ARJspCurr.setInput(sGrpName+".PopUpExceptionWindow","false");

%>
<script>

	var sPopUpExceptionWindow = '<%=sPopUpExceptionWindow%>';
	var sReferralMode = '<%=sReferralMode%>' ;

	var subGroupName = '<%=ParseValue.checkString(ARJspCurr.getInput("subGroupName",""))%>';
	var userId = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".userId",""))%>';
	var funcCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".funcCode",""))%>';

</script>

<SCRIPT language="javascript" src="../../javascripts/common_functions.js"></SCRIPT>
<SCRIPT language="javascript" src="../../javascripts/cust_post_evt.js"></SCRIPT>
<SCRIPT language="javascript" src="../../javascripts/cust_pre_evt.js"></SCRIPT>
<script language="javascript" src="../Renderer/custom/javascripts/custom_functions.js"></script>
<script language="javascript" src="../Renderer/custom/javascripts/hotkeyprocessor_link.js"></script>
<script language="javascript" src="../Renderer/javascripts/lists/showRoleList.js"> </script>
<script language="javascript" src="../Renderer/javascripts/lists/showUserIdList.js"> </script>


<script language="JavaScript">
	printBlock();
	printFooterBlock();
</script>

