#!/bin/bash

# Export the Jasypt secret key as an environment variable
export CD_SPRING_DATASOURCE_URL="#{CD-SPRING-DATASOURCE-URL}#"
export CD_SPRING_DATASOURCE_USERNAME="#{CD-SPRING-DATASOURCE-USERNAME}#"
export CD_SPRING_DATASOURCE_PASSWORD="#{SPRING-DATASOURCE-PASSWORD}#"

export CD_ORANGE_B2C_NONEXPIRETOKEN="#{CD-ORANGE-B2C-NONEXPIRETOKEN}#"
export CD_ORANGE_B2C_TRANSACTIONS_BASE_URL=""
export CD_ORANGE_B2C_STATUS_BASE_URL=""

export CD_ORANGE_AIRTIME_PURCHASE_PIN="#{CD-ORANGE-AIRTIME-PURCHASE-PIN}#"
export CD_ORANGE_AIRTIME_PURCHASE_CHANNEL_MSISDN="#{CD-ORANGE-AIRTIME-PURCHASE-CHANNEL-MSISDN}#"
export CD_ORANGE_AIRTIME_PURCHASE_PASSWORD="#{CD-ORANGE-AIRTIME-PURCHASE-PASSWORD}#"
export CD_ORANGE_AIRTIME_PURCHASE_EXTCODE="#{CD-ORANGE-AIRTIME-PURCHASE-EXTCODE}#"
export CD_ORANGE_AIRTIME_PURCHASE_LOGINID="#{CD-ORANGE-AIRTIME-PURCHASE-LOGINID}#"
export CD_ORANGE_AIRTIME_BASE_URL="http://10.59.1.127:5000/pretups/C2SReceiver"

export CD_ORANGE_AIRTIME_REQUEST_GATEWAY_CODE="#{CD-ORANGE-AIRTIME-REQUEST-GATEWAY-CODE}#"
export CD_ORANGE_AIRTIME_SERVICE_PORT="190"
export CD_ORANGE_AIRTIME_REQUEST_GATEWAY_TYPE="EXTGW"
export CD_ORANGE_AIRTIME_LOGIN="#{CD-ORANGE-AIRTIME-LOGIN}#"
export CD_ORANGE_AIRTIME_SOURCE_TYPE="EBANK"
export CD_ORANGE_AIRTIME_PASSWORD="#{CD-ORANGE-AIRTIME-PASSWORD}#"

# Print a confirmation message
echo "Environment variables have been set."