<%--
//Generated by Customization WB Generator
//Do not edit this file directly.
//Instead, modify the properties in the tool and regenerate.
--%>

<%@ page import="applcommon.ParseValue" %>
<%@ page import="com.infy.bbu.jsputil.*"%>
<%@ page import="java.util.Vector"%>
<%@ taglib uri="taglib.tld" prefix="arjsp" %>
<arjsp:init groupName="Customize" isEntryPoint="false" />

<%
	String sProfileId = ProfilesManager.getProfileInSession(session);
	String sSubGrpName = (String)ARJspCurr.getInput("subGroupName","");
	String sGrpName = ARJspCurr.getCurrentGroup();
	String pageName = (String)ARJspCurr.getInput("jspName","");
	String sPopUpExceptionWindow = (String)ARJspCurr.getInput(sGrpName+".PopUpExceptionWindow" ,"false");
	String sReferralMode = (String)ARJspCurr.getInput("refSubMode" ,"");
	ARJspCurr.setInput(sGrpName+".PopUpExceptionWindow","false");

%>
<script>

	var sPopUpExceptionWindow = '<%=ParseValue.checkString(sPopUpExceptionWindow)%>';
	var sReferralMode = '<%=ParseValue.checkString(sReferralMode)%>';
	var subGroupName = '<%=ParseValue.checkString(ARJspCurr.getInput("subGroupName",""))%>';
	var funcCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".funcCode",""))%>';
	var trantype = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".trantype",""))%>';
	var Ecstranrefnum = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".Ecstranrefnum",""))%>';
	var solid = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".solid",""))%>';
	var paysysid = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".paysysid",""))%>';

	var currency = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".currency",""))%>';
//	var InOutIndctr = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".InOutIndctr",""))%>';
//	var pymntIndctr = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".pymntIndctr",""))%>';

</script>

<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showCurrency.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showEcsTranRefno.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showRefCode.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showSolId.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("listBankCodes.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showAccountIdList.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showBranchCodes.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showRefCode.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showEcsTranRefno.js",sProfileId)%>" > </script>


<script language="JavaScript">
</script>

<script language="JavaScript">
	printBlock();
	printFooterBlock();
</script>

