SET DEFINE OFF;
Insert into CUSTOM.C_CPMASTER
   (MODULE_NAME, PARAMETER_LEVEL, PARAMETER_ID, PARAMETER_DESC, PARAMETER_TYPE, LIST_TYPE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID)
 Values
   ('CATODSCORE', 'BNKL', 'INQCLS', 'Work Class', 'AN', 'FT', 'Y', 'N', 'SYSTEM', TO_DATE('06/14/2013 16:17:43', 'MM/DD/YYYY HH24:MI:SS'), 'SYSTEM', TO_DATE('06/14/2013 16:17:43', 'MM/DD/YYYY HH24:MI:SS'), '11');
Insert into CUSTOM.C_CPMASTER
   (MODULE_NAME, PARAMETER_LEVEL, PARAMETER_ID, PARAMETER_DESC, PARAMETER_TYPE, LIST_TYPE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID)
 Values
   ('CATODSCORE', 'BNKL', 'INQCLS', 'Work Class', 'AN', 'FT', 'Y', 'N', 'SYSTEM', TO_DATE('06/14/2013 16:17:43', 'MM/DD/YYYY HH24:MI:SS'), 'SYSTEM', TO_DATE('06/14/2013 16:17:43', 'MM/DD/YYYY HH24:MI:SS'), '50');
Insert into CUSTOM.C_CPMASTER
   (MODULE_NAME, PARAMETER_LEVEL, PARAMETER_ID, PARAMETER_DESC, PARAMETER_TYPE, LIST_TYPE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID)
 Values
   ('CATODSCORE', 'BNKL', 'INQCLS', 'Work Class', 'AN', 'FT', 'Y', 'N', 'SYSTEM', TO_DATE('06/14/2013 16:17:43', 'MM/DD/YYYY HH24:MI:SS'), 'SYSTEM', TO_DATE('06/14/2013 16:17:43', 'MM/DD/YYYY HH24:MI:SS'), '54');
Insert into CUSTOM.C_CPMASTER
   (MODULE_NAME, PARAMETER_LEVEL, PARAMETER_ID, PARAMETER_DESC, PARAMETER_TYPE, LIST_TYPE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID)
 Values
   ('CATODSCORE', 'BNKL', 'INQCLS', 'Work Class', 'AN', 'FT', 'Y', 'N', 'SYSTEM', TO_DATE('06/14/2013 16:17:43', 'MM/DD/YYYY HH24:MI:SS'), 'SYSTEM', TO_DATE('06/14/2013 16:17:43', 'MM/DD/YYYY HH24:MI:SS'), '55');
Insert into CUSTOM.C_CPMASTER
   (MODULE_NAME, PARAMETER_LEVEL, PARAMETER_ID, PARAMETER_DESC, PARAMETER_TYPE, LIST_TYPE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID)
 Values
   ('CATODSCORE', 'BNKL', 'INQCLS', 'Work Class', 'AN', 'FT', 'Y', 'N', 'SYSTEM', TO_DATE('06/14/2013 16:17:43', 'MM/DD/YYYY HH24:MI:SS'), 'SYSTEM', TO_DATE('06/14/2013 16:17:43', 'MM/DD/YYYY HH24:MI:SS'), '56');
Insert into CUSTOM.C_CPMASTER
   (MODULE_NAME, PARAMETER_LEVEL, PARAMETER_ID, PARAMETER_DESC, PARAMETER_TYPE, LIST_TYPE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID)
 Values
   ('CATODSCORE', 'BNKL', 'WRKCLS', 'Work Class', 'AN', 'FT', 'Y', 'N', 'SYSTEM', TO_DATE('06/14/2013 16:17:43', 'MM/DD/YYYY HH24:MI:SS'), 'SYSTEM', TO_DATE('06/14/2013 16:17:43', 'MM/DD/YYYY HH24:MI:SS'), '11');
Insert into CUSTOM.C_CPMASTER
   (MODULE_NAME, PARAMETER_LEVEL, PARAMETER_ID, PARAMETER_DESC, PARAMETER_TYPE, LIST_TYPE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID)
 Values
   ('CATODSCORE', 'BNKL', 'WRKCLS', 'Work Class', 'AN', 'FT', 'Y', 'N', 'SYSTEM', TO_DATE('06/14/2013 16:17:43', 'MM/DD/YYYY HH24:MI:SS'), 'SYSTEM', TO_DATE('06/14/2013 16:17:43', 'MM/DD/YYYY HH24:MI:SS'), '50');
Insert into CUSTOM.C_CPMASTER
   (MODULE_NAME, PARAMETER_LEVEL, PARAMETER_ID, PARAMETER_DESC, PARAMETER_TYPE, LIST_TYPE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID)
 Values
   ('CATODSCORE', 'BNKL', 'WRKCLS', 'Work Class', 'AN', 'FT', 'Y', 'N', 'SYSTEM', TO_DATE('06/14/2013 16:17:43', 'MM/DD/YYYY HH24:MI:SS'), 'SYSTEM', TO_DATE('06/14/2013 16:17:43', 'MM/DD/YYYY HH24:MI:SS'), '54');
Insert into CUSTOM.C_CPMASTER
   (MODULE_NAME, PARAMETER_LEVEL, PARAMETER_ID, PARAMETER_DESC, PARAMETER_TYPE, LIST_TYPE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID)
 Values
   ('CATODSCORE', 'BNKL', 'WRKCLS', 'Work Class', 'AN', 'FT', 'Y', 'N', 'SYSTEM', TO_DATE('06/14/2013 16:17:43', 'MM/DD/YYYY HH24:MI:SS'), 'SYSTEM', TO_DATE('06/14/2013 16:17:43', 'MM/DD/YYYY HH24:MI:SS'), '55');
Insert into CUSTOM.C_CPMASTER
   (MODULE_NAME, PARAMETER_LEVEL, PARAMETER_ID, PARAMETER_DESC, PARAMETER_TYPE, LIST_TYPE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID)
 Values
   ('CATODSCORE', 'BNKL', 'WRKCLS', 'Work Class', 'AN', 'FT', 'Y', 'N', 'SYSTEM', TO_DATE('06/14/2013 16:17:43', 'MM/DD/YYYY HH24:MI:SS'), 'SYSTEM', TO_DATE('06/14/2013 16:17:43', 'MM/DD/YYYY HH24:MI:SS'), '56');
COMMIT;
