DROP TABLE CUSTOM.ACCT_EXEMPTION_TABLE CASCADE CONSTRAINTS;

CREATE TABLE CUSTOM.ACCT_EXEMPTION_TABLE
(
  FORACID      VARCHAR2(16 CHAR),
  EXEMPT_CODE  VARCHAR2(10 CHAR),
  BANK_ID      VARCHAR2(8 CHAR),
  DEL_FLG      CHAR(1 BYTE)
);

CREATE INDEX CUSTOM.INDEX_ACCT_EXEMPTION_TABLE ON CUSTOM.ACCT_EXEMPTION_TABLE
(FORACID, EXEMPT_CODE, BANK_ID);

GRANT SELECT ON CUSTOM.ACCT_EXEMPTION_TABLE TO SMBOGORI;

GRANT SELECT ON CUSTOM.ACCT_EXEMPTION_TABLE TO STMNT_USER;

GRANT INSERT, SELECT, UPDATE ON CUSTOM.ACCT_EXEMPTION_TABLE TO TBAADM;

GRANT INSERT, SELECT, UPDATE ON CUSTOM.ACCT_EXEMPTION_TABLE TO TBAGEN;
