DROP TABLE CUSTOM.C_WTH_ACCT_OPEN_ACCT_INFO CASCADE CONSTRAINTS;

CREATE TABLE CUSTOM.C_WTH_ACCT_OPEN_ACCT_INFO
(
  TAX_TO_BE_RECOVERED  NUMBER(20,4),
  FORACID              VARCHAR2(16 CHAR),
  LCHG_USER_ID         VARCHAR2(15 CHAR),
  LCHG_TIME            DATE,
  RCRE_USER_ID         VARCHAR2(15 CHAR),
  RCRE_TIME            DATE,
  DEL_FLG              CHAR(1 BYTE),
  ENTITY_CRE_FLG       CHAR(1 BYTE),
  BANK_ID              VARCHAR2(8 CHAR)
);

CREATE UNIQUE INDEX CUSTOM.IDX_C_WTH_ACCT_OPEN_ACCT_INFO ON CUSTOM.C_WTH_ACCT_OPEN_ACCT_INFO
(FORACID, BANK_ID);
 
DROP SYNONYM CUSTOM.C_WTHAOO;

CREATE SYNONYM CUSTOM.C_WTHAOO FOR CUSTOM.C_WTH_ACCT_OPEN_ACCT_INFO;

GRANT SELECT ON CUSTOM.C_WTH_ACCT_OPEN_ACCT_INFO TO ALLTAB;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.C_WTH_ACCT_OPEN_ACCT_INFO TO TBAADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.C_WTH_ACCT_OPEN_ACCT_INFO TO TBAGEN;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.C_WTH_ACCT_OPEN_ACCT_INFO TO TBAUTIL;
