DROP TABLE CUSTOM.UNIV_DATA CASCADE CONSTRAINTS;

CREATE TABLE CUSTOM.UNIV_DATA
(
  ACCTNUM         VARCHAR2(15 BYTE),
  REFNUM          VARCHAR2(50 BYTE),
  NAME            VARCHAR2(300 BYTE),
  ENTERER_ID      VARCHAR2(15 BYTE),
  AUDIT_DATE      DATE,
  AUDIT_BOD_DATE  TIMESTAMP(6) WITH LOCAL TIME ZONE,
  FUNC            VARCHAR2(1 BYTE),
  BANK_ID         VARCHAR2(8 CHAR)
);


DROP SYNONYM CUSTOM.C_UNIV;

CREATE SYNONYM CUSTOM.C_UNIV FOR CUSTOM.UNIV_DATA;

GRANT SELECT ON CUSTOM.UNIV_DATA TO ALLTAB;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.UNIV_DATA TO TBAADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.UNIV_DATA TO TBAGEN;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.UNIV_DATA TO TBAUTIL;
