--ALTER TABLE CUSTOM.INT_USER_PROF_MAS DROP PRIMARY KEY CASCADE
--/
--DROP TABLE CUSTOM.INT_USER_PROF_MAS CASCADE CONSTRAINTS
--/

CREATE TABLE CUSTOM.INT_USER_PROF_MAS ( IC_USER_ID VARCHAR2(15 BYTE) NOT NULL, IC_APPL_ID VARCHAR2(6 BYTE), IC_USER_DESC VARCHAR2(50 BYTE), IC_USER_TYPE VARCHAR2(2 BYTE), IC_USER_PW VARCHAR2(100 BYTE), IC_USER_STATUS CHAR(1 BYTE), IC_STATUS VARCHAR2(3 BYTE), IC_USER_EXPRY_DATE DATE, IC_USER_PWD_EXPRY_DATE DATE, IC_BRANCH_ID VARCHAR2(15 BYTE), IC_EMAIL_ID VARCHAR2(80 BYTE), IC_DEL_FLG CHAR(1 BYTE), IC_REJ_FLG CHAR(1 BYTE), IC_ENTITY_CRE_FLG CHAR(1 BYTE), IC_RCRE_TIME DATE, IC_RCRE_ID VARCHAR2(20 BYTE), IC_AUTH_TIME DATE, IC_AUTH_ID VARCHAR2(20 BYTE), IC_LCHG_TIME DATE, IC_LCHG_ID VARCHAR2(20 BYTE), IC_DISB_FROM DATE, IC_DISB_TO DATE, IC_LOGGED_STATUS CHAR(1 BYTE) DEFAULT 'O', IC_SESSION_ID VARCHAR2(100 BYTE),BANK_ID VARCHAR2(8 CHAR) ) TABLESPACE CUSTOM_TBLS PCTUSED 40 PCTFREE 10 INITRANS 1 MAXTRANS 255 STORAGE ( INITIAL 64K MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT ) LOGGING NOCOMPRESS NOCACHE NOPARALLEL NOMONITORING
/


CREATE INDEX CUSTOM.IC_IDX_USER_PROF_MAS_1 ON CUSTOM.INT_USER_PROF_MAS (IC_USER_ID, IC_APPL_ID, IC_USER_TYPE, BANK_ID) LOGGING TABLESPACE CUSTOM_IDXSPACE PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT ) NOPARALLEL
/


CREATE INDEX CUSTOM.IC_IDX_USER_PROF_MAS_2 ON CUSTOM.INT_USER_PROF_MAS (IC_USER_TYPE, IC_BRANCH_ID, BANK_ID) LOGGING TABLESPACE CUSTOM_IDXSPACE PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT ) NOPARALLEL
/


DROP SYNONYM CUSTOM.IUPM
/

CREATE SYNONYM CUSTOM.IUPM FOR CUSTOM.INT_USER_PROF_MAS
/


ALTER TABLE CUSTOM.INT_USER_PROF_MAS ADD ( CONSTRAINT CPK_INT_USER_PROF_MAS PRIMARY KEY (IC_USER_ID, IC_APPL_ID, BANK_ID))
/
