DROP TABLE CUSTOM.TRADING_TRAN_TABLE CASCADE CONSTRAINTS;

CREATE TABLE CUSTOM.TRADING_TRAN_TABLE
(
  CUSTODIKNOWCODE    NUMBER(10),
  CLIENTCDSNO        VARCHAR2(100 BYTE),
  CONTRACTNUMBER     NUMBER(10,2),
  CONTRACTDATE       DATE,
  CDSREF             VARCHAR2(100 BYTE),
  BRANCHCODE         VARCHAR2(5 BYTE),
  DRCRACCOUNT        VARCHAR2(16 BYTE),
  AMOUNT             NUMBER(20,4),
  DRCRIND            VARCHAR2(1 BYTE),
  REMARKS            VARCHAR2(100 BYTE),
  STATUS             VARCHAR2(1 BYTE),
  ORDERTYPE          VARCHAR2(100 BYTE),
  SETTLEMENT_DATE    DATE,
  SETTLEMENT_STATUS  VARCHAR2(10 BYTE),
  BANK_ID            VARCHAR2(8 CHAR)
)
TABLESPACE CUSTOM_TBLS
PCTUSED    0
PCTFREE    10
INITRANS   50
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX CUSTOM.DRCRACCOUNT ON CUSTOM.TRADING_TRAN_TABLE
(DRCRACCOUNT, BANK_ID)
LOGGING
TABLESPACE CUSTOM_IDXSPACE
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX CUSTOM.DRCRIND ON CUSTOM.TRADING_TRAN_TABLE
(DRCRIND, BANK_ID)
LOGGING
TABLESPACE CUSTOM_IDXSPACE
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX CUSTOM.IDX_TRANCONTRACTNUMBER ON CUSTOM.TRADING_TRAN_TABLE
(CONTRACTNUMBER, BANK_ID)
LOGGING
TABLESPACE CUSTOM_IDXSPACE
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE UNIQUE INDEX CUSTOM.IDX_TRANCONTRACTNUMBER_TEST ON CUSTOM.TRADING_TRAN_TABLE
(CUSTODIKNOWCODE, CLIENTCDSNO, CONTRACTNUMBER, CONTRACTDATE, CDSREF, BRANCHCODE, DRCRACCOUNT, AMOUNT, DRCRIND, REMARKS, ORDERTYPE, SETTLEMENT_DATE, SETTLEMENT_STATUS, BANK_ID)
LOGGING
TABLESPACE CUSTOM_IDXSPACE
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

DROP SYNONYM CUSTOM.C_TRADINGTRAN;

CREATE SYNONYM CUSTOM.C_TRADINGTRAN FOR CUSTOM.TRADING_TRAN_TABLE;


GRANT INSERT, SELECT, UPDATE ON CUSTOM.TRADING_TRAN_TABLE TO INFYCUST;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.TRADING_TRAN_TABLE TO TBAADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.TRADING_TRAN_TABLE TO TBAGEN;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.TRADING_TRAN_TABLE TO TBAUTIL;
