SET DEFINE OFF;
Insert into CUSTOM.C_CPMASTER
   (MODULE_NAME, PARAMETER_LEVEL, PARAMETER_ID, PARAMETER_DESC, PARAMETER_TYPE, QUERY_ID, LIST_TYPE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID)
 Values
   ('BIOM', 'BNKL', 'STAFF_MENU', 'STAFF VAL BIOMETRIC VALIDATION FOR 11', 'AN', ' ', 'FT', 'Y', 'N', 'SYSTEM', TO_DATE('08/13/2013 12:42:01', 'MM/DD/YYYY HH24:MI:SS'), 'SYSTEM', TO_DATE('08/13/2013 12:42:01', 'MM/DD/YYYY HH24:MI:SS'), '11');
Insert into CUSTOM.C_CPMASTER
   (MODULE_NAME, PARAMETER_LEVEL, PARAMETER_ID, PARAMETER_DESC, PARAMETER_TYPE, QUERY_ID, LIST_TYPE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID)
 Values
   ('BIOM', 'BNKL', 'STAFF_MENU', 'STAFF VAL BIOMETRIC VALIDATION FOR 50', 'AN', ' ', 'FT', 'Y', 'N', 'SYSTEM', TO_DATE('08/13/2013 12:42:18', 'MM/DD/YYYY HH24:MI:SS'), 'SYSTEM', TO_DATE('08/13/2013 12:42:18', 'MM/DD/YYYY HH24:MI:SS'), '50');
Insert into CUSTOM.C_CPMASTER
   (MODULE_NAME, PARAMETER_LEVEL, PARAMETER_ID, PARAMETER_DESC, PARAMETER_TYPE, QUERY_ID, LIST_TYPE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID)
 Values
   ('BIOM', 'BNKL', 'STAFF_MENU', 'STAFF VAL BIOMETRIC VALIDATION FOR 54', 'AN', ' ', 'FT', 'Y', 'N', 'SYSTEM', TO_DATE('08/13/2013 12:42:24', 'MM/DD/YYYY HH24:MI:SS'), 'SYSTEM', TO_DATE('08/13/2013 12:42:24', 'MM/DD/YYYY HH24:MI:SS'), '54');
Insert into CUSTOM.C_CPMASTER
   (MODULE_NAME, PARAMETER_LEVEL, PARAMETER_ID, PARAMETER_DESC, PARAMETER_TYPE, QUERY_ID, LIST_TYPE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID)
 Values
   ('BIOM', 'BNKL', 'STAFF_MENU', 'STAFF VAL BIOMETRIC VALIDATION FOR 55', 'AN', ' ', 'FT', 'Y', 'N', 'SYSTEM', TO_DATE('08/13/2013 12:42:30', 'MM/DD/YYYY HH24:MI:SS'), 'SYSTEM', TO_DATE('08/13/2013 12:42:30', 'MM/DD/YYYY HH24:MI:SS'), '55');
Insert into CUSTOM.C_CPMASTER
   (MODULE_NAME, PARAMETER_LEVEL, PARAMETER_ID, PARAMETER_DESC, PARAMETER_TYPE, QUERY_ID, LIST_TYPE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID)
 Values
   ('BIOM', 'BNKL', 'STAFF_MENU', 'STAFF VAL BIOMETRIC VALIDATION FOR 56', 'AN', ' ', 'FT', 'Y', 'N', 'SYSTEM', TO_DATE('08/13/2013 12:42:36', 'MM/DD/YYYY HH24:MI:SS'), 'SYSTEM', TO_DATE('08/13/2013 12:42:36', 'MM/DD/YYYY HH24:MI:SS'), '56');

Insert into CUSTOM.C_CPVALUE
   (PARAMETER_ID, PARAMETER_VALUE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID, MODULE_NAME)
 Values
   ('STAFF_MENU', 'HDDMI,HDDC,HLADISB,HORM,HIRM,HRINBX,', 'Y', 'N', 'SYSTEM', TO_DATE('08/13/2013 12:45:22', 'MM/DD/YYYY HH24:MI:SS'), 'SYSTEM', TO_DATE('08/13/2013 12:45:22', 'MM/DD/YYYY HH24:MI:SS'), '11', 'BIOM');
Insert into CUSTOM.C_CPVALUE
   (PARAMETER_ID, PARAMETER_VALUE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID, MODULE_NAME)
 Values
   ('STAFF_MENU', 'HDDMI,HDDC,HLADISB,HORM,HIRM,HRINBX,', 'Y', 'N', 'SYSTEM', TO_DATE('08/13/2013 12:45:36', 'MM/DD/YYYY HH24:MI:SS'), 'SYSTEM', TO_DATE('08/13/2013 12:45:36', 'MM/DD/YYYY HH24:MI:SS'), '50', 'BIOM');
Insert into CUSTOM.C_CPVALUE
   (PARAMETER_ID, PARAMETER_VALUE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID, MODULE_NAME)
 Values
   ('STAFF_MENU', 'HDDMI,HDDC,HLADISB,HORM,HIRM,HRINBX,', 'Y', 'N', 'SYSTEM', TO_DATE('08/13/2013 12:45:26', 'MM/DD/YYYY HH24:MI:SS'), 'SYSTEM', TO_DATE('08/13/2013 12:45:26', 'MM/DD/YYYY HH24:MI:SS'), '54', 'BIOM');
Insert into CUSTOM.C_CPVALUE
   (PARAMETER_ID, PARAMETER_VALUE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID, MODULE_NAME)
 Values
   ('STAFF_MENU', 'HDDMI,HDDC,HLADISB,HORM,HIRM,HRINBX,', 'Y', 'N', 'SYSTEM', TO_DATE('08/13/2013 12:45:28', 'MM/DD/YYYY HH24:MI:SS'), 'SYSTEM', TO_DATE('08/13/2013 12:45:28', 'MM/DD/YYYY HH24:MI:SS'), '55', 'BIOM');
Insert into CUSTOM.C_CPVALUE
   (PARAMETER_ID, PARAMETER_VALUE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID, MODULE_NAME)
 Values
   ('STAFF_MENU', 'HDDMI,HDDC,HLADISB,HORM,HIRM,HRINBX,', 'Y', 'N', 'SYSTEM', TO_DATE('08/13/2013 12:45:32', 'MM/DD/YYYY HH24:MI:SS'), 'SYSTEM', TO_DATE('08/13/2013 12:45:32', 'MM/DD/YYYY HH24:MI:SS'), '56', 'BIOM');


Insert into CUSTOM.C_CPMASTER
   (MODULE_NAME, PARAMETER_LEVEL, PARAMETER_ID, PARAMETER_DESC, PARAMETER_TYPE, QUERY_ID, LIST_TYPE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID)
 Values
   ('BIOM', 'BNKL', 'ENROL_VAL_MENU', 'ENROLL VAL BIOMETRIC VALIDATION FOR 11', 'AN', ' ', 'FT', 'Y', 'N', 'SYSTEM', TO_DATE('08/13/2013 12:42:01', 'MM/DD/YYYY HH24:MI:SS'), 'SYSTEM', TO_DATE('08/13/2013 12:42:01', 'MM/DD/YYYY HH24:MI:SS'), '11');
Insert into CUSTOM.C_CPMASTER
   (MODULE_NAME, PARAMETER_LEVEL, PARAMETER_ID, PARAMETER_DESC, PARAMETER_TYPE, QUERY_ID, LIST_TYPE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID)
 Values
   ('BIOM', 'BNKL', 'ENROL_VAL_MENU', 'ENROLL VAL BIOMETRIC VALIDATION FOR 50', 'AN', ' ', 'FT', 'Y', 'N', 'SYSTEM', TO_DATE('08/13/2013 12:42:18', 'MM/DD/YYYY HH24:MI:SS'), 'SYSTEM', TO_DATE('08/13/2013 12:42:18', 'MM/DD/YYYY HH24:MI:SS'), '50');
Insert into CUSTOM.C_CPMASTER
   (MODULE_NAME, PARAMETER_LEVEL, PARAMETER_ID, PARAMETER_DESC, PARAMETER_TYPE, QUERY_ID, LIST_TYPE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID)
 Values
   ('BIOM', 'BNKL', 'ENROL_VAL_MENU', 'ENROLL VAL BIOMETRIC VALIDATION FOR 54', 'AN', ' ', 'FT', 'Y', 'N', 'SYSTEM', TO_DATE('08/13/2013 12:42:24', 'MM/DD/YYYY HH24:MI:SS'), 'SYSTEM', TO_DATE('08/13/2013 12:42:24', 'MM/DD/YYYY HH24:MI:SS'), '54');
Insert into CUSTOM.C_CPMASTER
   (MODULE_NAME, PARAMETER_LEVEL, PARAMETER_ID, PARAMETER_DESC, PARAMETER_TYPE, QUERY_ID, LIST_TYPE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID)
 Values
   ('BIOM', 'BNKL', 'ENROL_VAL_MENU', 'ENROLL VAL BIOMETRIC VALIDATION FOR 55', 'AN', ' ', 'FT', 'Y', 'N', 'SYSTEM', TO_DATE('08/13/2013 12:42:30', 'MM/DD/YYYY HH24:MI:SS'), 'SYSTEM', TO_DATE('08/13/2013 12:42:30', 'MM/DD/YYYY HH24:MI:SS'), '55');
Insert into CUSTOM.C_CPMASTER
   (MODULE_NAME, PARAMETER_LEVEL, PARAMETER_ID, PARAMETER_DESC, PARAMETER_TYPE, QUERY_ID, LIST_TYPE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID)
 Values
   ('BIOM', 'BNKL', 'ENROL_VAL_MENU', 'ENROLL VAL BIOMETRIC VALIDATION FOR 56', 'AN', ' ', 'FT', 'Y', 'N', 'SYSTEM', TO_DATE('08/13/2013 12:42:36', 'MM/DD/YYYY HH24:MI:SS'), 'SYSTEM', TO_DATE('08/13/2013 12:42:36', 'MM/DD/YYYY HH24:MI:SS'), '56');

Insert into CUSTOM.C_CPVALUE
   (PARAMETER_ID, PARAMETER_VALUE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID, MODULE_NAME)
 Values
   ('ENROL_VAL_MENU', 'HOAACCA,HOAACSB,HOAACOD,HOAACCC,HOAACLA,HOAACCL,', 'Y', 'N', 'SYSTEM', TO_DATE('08/13/2013 12:45:22', 'MM/DD/YYYY HH24:MI:SS'), 'SYSTEM', TO_DATE('08/13/2013 12:45:22', 'MM/DD/YYYY HH24:MI:SS'), '11', 'BIOM');
Insert into CUSTOM.C_CPVALUE
   (PARAMETER_ID, PARAMETER_VALUE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID, MODULE_NAME)
 Values
   ('ENROL_VAL_MENU', 'HOAACCA,HOAACSB,HOAACOD,HOAACCC,HOAACLA,HOAACCL,', 'Y', 'N', 'SYSTEM', TO_DATE('08/13/2013 12:45:36', 'MM/DD/YYYY HH24:MI:SS'), 'SYSTEM', TO_DATE('08/13/2013 12:45:36', 'MM/DD/YYYY HH24:MI:SS'), '50', 'BIOM');
Insert into CUSTOM.C_CPVALUE
   (PARAMETER_ID, PARAMETER_VALUE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID, MODULE_NAME)
 Values
   ('ENROL_VAL_MENU', 'HOAACCA,HOAACSB,HOAACOD,HOAACCC,HOAACLA,HOAACCL,', 'Y', 'N', 'SYSTEM', TO_DATE('08/13/2013 12:45:26', 'MM/DD/YYYY HH24:MI:SS'), 'SYSTEM', TO_DATE('08/13/2013 12:45:26', 'MM/DD/YYYY HH24:MI:SS'), '54', 'BIOM');
Insert into CUSTOM.C_CPVALUE
   (PARAMETER_ID, PARAMETER_VALUE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID, MODULE_NAME)
 Values
   ('ENROL_VAL_MENU', 'HOAACCA,HOAACSB,HOAACOD,HOAACCC,HOAACLA,HOAACCL,', 'Y', 'N', 'SYSTEM', TO_DATE('08/13/2013 12:45:28', 'MM/DD/YYYY HH24:MI:SS'), 'SYSTEM', TO_DATE('08/13/2013 12:45:28', 'MM/DD/YYYY HH24:MI:SS'), '55', 'BIOM');
Insert into CUSTOM.C_CPVALUE
   (PARAMETER_ID, PARAMETER_VALUE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID, MODULE_NAME)
 Values
   ('ENROL_VAL_MENU', 'HOAACCA,HOAACSB,HOAACOD,HOAACCC,HOAACLA,HOAACCL,', 'Y', 'N', 'SYSTEM', TO_DATE('08/13/2013 12:45:32', 'MM/DD/YYYY HH24:MI:SS'), 'SYSTEM', TO_DATE('08/13/2013 12:45:32', 'MM/DD/YYYY HH24:MI:SS'), '56', 'BIOM');





