--====================================================================================================
-- Table Name                   : CUST_EIT_TABLE
-- Synonym Name                 : C_EIT
-- Index Name                   :
-- Unique Index On              :
-- Date                         :
-- Description                  : This sql script is used to create a customized CUST_EIT_TABLE table
-- Author                       :
-- Bank                         : EQUITY BANK
-- Modification History :
-- <Version No.>    <Date>        <Author Name>         <Description>
--	0.1	  21-10-2012	   Parikshith
--====================================================================================================

Rem TABLE NAME: CUST_EIT_TABLE

DROP TABLE CUST_EIT_TABLE
/

CREATE TABLE CUST_EIT_TABLE
(
  TRAN_DATE             DATE,
  BACID                 VARCHAR2(16 CHAR),
  GL_ACCT_NO            VARCHAR2(16 CHAR),
  TRAN_ID               VARCHAR2(9 CHAR),
  PART_TRAN_SRL_NUM     VARCHAR2(4 CHAR),
  TRAN_AMT              NUMBER(20,4),
  TRAN_CRNCY            VARCHAR2(3 CHAR),
  PART_TRAN_TYPE        CHAR(1 BYTE),
  TRAN_PARTICULAR       VARCHAR2(50 CHAR),
  TRAN_PARTICULAR_2     VARCHAR2(50 CHAR),
  TRAN_REMARKS          VARCHAR2(30 CHAR),
  CUSTOMER_ACCOUNT_NO   VARCHAR2(16 CHAR),
  SOL_ID                VARCHAR2(8 CHAR),
  SCHM_TYPE             VARCHAR2(3 CHAR),
  SCHM_CODE             VARCHAR2(5 CHAR),
  EOD_CLOSING_BALANCE   NUMBER(20,4),
  EOD_UN_CLR_BAL_AMT    NUMBER(20,4),
  EOD_FUTURE_BAL_AMT    NUMBER(20,4),
  EOD_LIEN_AMT          NUMBER(20,4),
  GL_SUB_HEAD_CODE      VARCHAR2(5 CHAR),
  INT_COLL_FLAG         CHAR(1 BYTE),
  INT_PAID_FLAG         CHAR(1 BYTE),
  DEBIT_CREDIT_IND      CHAR(1 BYTE),
  INTEREST_RATE         NUMBER(21,10),
  INT_APPL_FLG          CHAR(1 BYTE),
  ACCRUED_UPTO_DATE     DATE,
  ACCRUED_UPTO_AMOUNT   NUMBER(20,4),
  ACCRUED_AMOUNT_TODAY  NUMBER(20,4),
  BOOKED_UPTO_DATE      DATE,
  BOOKED_UPTO_AMOUNT    NUMBER(20,4),
  BOOKED_AMOUNT_TODAY   NUMBER(20,4),
  APPLIED_UPTO_DATE     DATE,
  APPLIED_UPTO_AMOUNT   NUMBER(20,4),
  APPLIED_AMOUNT_TODAY  NUMBER(20,4),
  SEGMENT               VARCHAR2(100 CHAR),
  SUB_SEGMENT           VARCHAR2(100 CHAR),
  FREE_CODE_7           VARCHAR2(100 CHAR),
  RCRE_USER_ID          VARCHAR2(15 CHAR),
  RCRE_TIME             DATE,
  LCHG_USER_ID          VARCHAR2(15 CHAR),
  LCHG_TIME             DATE,
  BANK_ID               VARCHAR2(2 CHAR),
  UNQ_IDENTIFIER	VARCHAR2(40)
)
TABLESPACE CUSTOM_TBLS
/

CREATE INDEX CUSTOM.IDX_CUST_EIT_1 ON CUSTOM.CUST_EIT_TABLE
(GL_ACCT_NO, TRAN_ID,TRAN_DATE, BANK_ID)
/

CREATE INDEX CUSTOM.IDX_CUST_EIT_2 ON CUSTOM.CUST_EIT_TABLE
(BACID)
/

CREATE INDEX CUSTOM.IDX_CUST_EIT_3 ON CUSTOM.CUST_EIT_TABLE
(CUSTOMER_ACCOUNT_NO)
/

CREATE INDEX CUSTOM.IDX_CUST_EIT_4 ON CUSTOM.CUST_EIT_TABLE
(SOL_ID)
/

CREATE SYNONYM CUSTOM.C_EIT FOR CUSTOM.CUST_EIT_TABLE
/

CREATE SYNONYM TBAADM.C_EIT FOR CUSTOM.CUST_EIT_TABLE
/

CREATE SYNONYM TBAGEN.C_EIT FOR CUSTOM.CUST_EIT_TABLE
/

CREATE SYNONYM TBAUTIL.C_EIT FOR CUSTOM.CUST_EIT_TABLE
/

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.CUST_EIT_TABLE TO TBAADM
/

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.CUST_EIT_TABLE TO TBAGEN
/

GRANT SELECT ON CUSTOM.CUST_EIT_TABLE TO TBAUTIL
/
