DROP TABLE CUSTOM.C_DDS CASCADE CONSTRAINTS;

CREATE TABLE CUSTOM.C_DDS
(
  RECTYPE           VARCHAR2(10 BYTE),
  CLIENTREF         VARCHAR2(20 BYTE),
  CLIENTNAME        VARCHAR2(100 BYTE),
  BANKCODE          VARCHAR2(10 BYTE),
  BRANCHCODE        VARCHAR2(30 BYTE),
  CLIENTACNO        VARCHAR2(20 BYTE),
  CLIENTBANKBRANCH  VARCHAR2(100 BYTE),
  CLIENTBANKNAME    VARCHAR2(100 BYTE),
  AMOUNT            VARCHAR2(30 BYTE),
  POLICYNO          VARCHAR2(30 BYTE),
  DUEDATE           DATE,
  STATUS            VARCHAR2(10 BYTE),
  UPL_STATUS        VARCHAR2(10 BYTE),
  ORIGINATOR_CODE   VARCHAR2(50 BYTE),
  RCRE_USER_ID      VARCHAR2(20 BYTE),
  DEL_FLG           CHAR(1 BYTE),
  BANK_ID           VARCHAR2(10 BYTE),
  REMARKS           VARCHAR2(50 BYTE),
  SOL_ID            VARCHAR2(20 BYTE)
);


GRANT SELECT ON CUSTOM.C_DDS TO ALLTAB;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.C_DDS TO TBAADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.C_DDS TO TBAGEN;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.C_DDS TO TBAUTIL;
