CREATE TABLE CUSTOM.CUST_INSTITUTE_CUSTOMERS_BILLS
(
  SOL_ID   VARCHAR2(3 BYTE),
  ACCTNUM  VARCHAR2(15 BYTE),
  REFNUM   VARCHAR2(30 BYTE),
  NAME     VARCHAR2(400 BYTE),
  DEL_FLG  VARCHAR2(1 BYTE)                     DEFAULT 'N',
  BANK_ID  VARCHAR2(10 BYTE)
);


CREATE SYNONYM CUSTOM.C_CIC_BILLS FOR CUSTOM.CUST_INSTITUTE_CUSTOMERS_BILLS;


CREATE SYNONYM TBAADM.C_CIC_BILLS FOR CUSTOM.CUST_INSTITUTE_CUSTOMERS_BILLS;


CREATE SYNONYM TBAGEN.C_CIC_BILLS FOR CUSTOM.CUST_INSTITUTE_CUSTOMERS_BILLS;


CREATE SYNONYM TBAUTIL.C_CIC_BILLS FOR CUSTOM.CUST_INSTITUTE_CUSTOMERS_BILLS;


GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.CUST_INSTITUTE_CUSTOMERS_BILLS TO TBAADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.CUST_INSTITUTE_CUSTOMERS_BILLS TO TBAGEN;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.CUST_INSTITUTE_CUSTOMERS_BILLS TO TBAUTIL;
