ALTER TABLE CUSTOM.SUPPLIER_PRICE_LIST
 DROP PRIMARY KEY CASCADE;
DROP TABLE CUSTOM.SUPPLIER_PRICE_LIST CASCADE CONSTRAINTS;

CREATE TABLE CUSTOM.SUPPLIER_PRICE_LIST
(
  SUP_EFFECTIVE_DATE    DATE                    NOT NULL,
  SUP_MIS_CODE          VARCHAR2(10 BYTE)       NOT NULL,
  SUP_ITEM_CODE         VARCHAR2(50 BYTE)       NOT NULL,
  SUP_ITEM_DESCRIPTION  VARCHAR2(100 BYTE)      NOT NULL,
  SUP_BASE_PRICE        NUMBER(12,2)            NOT NULL,
  BANK_ID               VARCHAR2(2 BYTE)
);



ALTER TABLE CUSTOM.SUPPLIER_PRICE_LIST ADD (
  PRIMARY KEY
 (SUP_EFFECTIVE_DATE, SUP_MIS_CODE, SUP_ITEM_CODE)
    USING INDEX
);

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.SUPPLIER_PRICE_LIST TO TBAADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.SUPPLIER_PRICE_LIST TO TBAGEN;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.SUPPLIER_PRICE_LIST TO TBAUTIL;

GRANT SELECT ON CUSTOM.SUPPLIER_PRICE_LIST TO ALLTAB;
