DROP TABLE CUSTOM.YUCASH_RFI_TABLE CASCADE CONSTRAINTS;

CREATE TABLE CUSTOM.YUCASH_RFI_TABLE
(
  MOBILENUMBER    VARCHAR2(16 BYTE),
  CASHINOUTFLG    VARCHAR2(1 BYTE),
  OBOPAY_TXN_ID   VARCHAR2(20 BYTE),
  AMOUNT          NUMBER(20),
  CUSTOMER_NAME   VARCHAR2(100 BYTE),
  CUSTOMER_ID     VARCHAR2(20 BYTE),
  STATUS          VARCHAR2(1 BYTE),
  REMARKS         VARCHAR2(100 BYTE),
  BRANCH_CODE     VARCHAR2(8 BYTE),
  ID              NUMBER(12),
  REQUESTAPP      VARCHAR2(50 BYTE),
  PAYMENT_METHOD  VARCHAR2(20 BYTE),
  STATUS_CODE     VARCHAR2(5 BYTE),
  BANK_ID         VARCHAR2(3 BYTE)
);

GRANT SELECT ON CUSTOM.YUCASH_RFI_TABLE TO ALLTAB;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.YUCASH_RFI_TABLE TO TBAADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.YUCASH_RFI_TABLE TO TBAGEN;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.YUCASH_RFI_TABLE TO TBAUTIL;
