ALTER TABLE CUSTOM.SHARE_PURCHASE_MASTER
 DROP PRIMARY KEY CASCADE;
DROP TABLE CUSTOM.SHARE_PURCHASE_MASTER CASCADE CONSTRAINTS;

CREATE TABLE CUSTOM.SHARE_PURCHASE_MASTER
(
  ID_KEY                  INTEGER               NOT NULL,
  TRAN_ID                 VARCHAR2(20 CHAR)     NOT NULL,
  TRAN_AMOUNT             VARCHAR2(100 BYTE),
  TRAN_DATE               VARCHAR2(100 BYTE),
  TRAN_BANK_ID            VARCHAR2(100 BYTE),
  TRAN_SOL_ID             VARCHAR2(100 BYTE),
  TRAN_ORDER_NUMBER       VARCHAR2(100 BYTE),
  CREATED_BY_ID           VARCHAR2(100 BYTE),
  VERIFIED_BY_ID          VARCHAR2(100 BYTE),
  VERIFIED_ON_DATE        VARCHAR2(100 BYTE),
  IS_VERIFIED             INTEGER               DEFAULT 0,
  CDSC_NUMBER             VARCHAR2(100 BYTE),
  ACCOUNT_NUMBER          VARCHAR2(100 BYTE),
  SENT_TO_EXT             INTEGER               DEFAULT 0,
  TRAN_STATUS             VARCHAR2(1 BYTE),
  CDSC_CLIENT_NAMES       VARCHAR2(100 BYTE),
  CDSC_ACCOUNT_IS_FUNDED  VARCHAR2(10 BYTE)     DEFAULT 0,
  TRAN_STATUS_O           VARCHAR2(20 BYTE)     DEFAULT 'E',
  CANCELLED_DATE          DATE,
  REVERSED_BY_USER_ID     VARCHAR2(100 BYTE),
  REVERSAL_DATE           DATE,
  CANCELLED_BY_USER_ID    VARCHAR2(100 BYTE),
  SUSPENDED_BY_ID         VARCHAR2(100 BYTE),
  SUSPENDED_BY_DATE       VARCHAR2(100 BYTE)
);

CREATE OR REPLACE TRIGGER CUSTOM.share_purchase_master_trigger

   before insert ON CUSTOM.SHARE_PURCHASE_MASTER    for each row
begin

    select custom.share_purchase_master_key.nextval into :new.id_key from dual;

   end;
/

ALTER TABLE CUSTOM.SHARE_PURCHASE_MASTER ADD (
  PRIMARY KEY
 (ID_KEY)
    USING INDEX 
);

GRANT SELECT ON CUSTOM.SHARE_PURCHASE_MASTER TO ALLTAB;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.SHARE_PURCHASE_MASTER TO TBAGEN;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.SHARE_PURCHASE_MASTER TO TBAADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.SHARE_PURCHASE_MASTER TO TBAUTIL;
