<%--
//Generated by Customization WB Generator
//Do not edit this file directly.
//Instead, modify the properties in the tool and regenerate.
--%>

<%@ page import="applcommon.ParseValue" %>
<%@ page import="com.infy.bbu.jsputil.*"%>
<%@ page import="java.util.Vector"%>
<%@ taglib uri="taglib.tld" prefix="arjsp" %>
<arjsp:init groupName="Customize" isEntryPoint="false" />

<%
	String sProfileId = ProfilesManager.getProfileInSession(session);
	String sSubGrpName = (String)ARJspCurr.getInput("subGroupName","");
	String sGrpName = ARJspCurr.getCurrentGroup();
	String pageName = (String)ARJspCurr.getInput("jspName","");
	String sPopUpExceptionWindow = (String)ARJspCurr.getInput(sGrpName+".PopUpExceptionWindow" ,"false");
	String sReferralMode = (String)ARJspCurr.getInput("refSubMode" ,"");
	ARJspCurr.setInput(sGrpName+".PopUpExceptionWindow","false");


	int iCurrentSetSize = Integer.parseInt((String)ARJspCurr.getInput(sSubGrpName+"_"+pageName+".setSize","0"));
	int iListMaxDisplay = Integer.parseInt((String)ARJspCurr.getInput(sSubGrpName+"_"+pageName+".MaxRecsPerPage","0"));
	int iCurrentPage = Integer.parseInt((String)ARJspCurr.getInput(sSubGrpName+"_"+pageName+".currentPage","0"));
	int startRecord = (iCurrentPage-1)*iListMaxDisplay;
	int iMaxPage=Integer.parseInt((String)ARJspCurr.getInput(sSubGrpName+"_"+pageName+".maxPage","0"));
	int dispNum = startRecord + iListMaxDisplay;
	int iCounter;
		


	

	
	Vector vctMRMField = new Vector();
	vctMRMField.add("selname");
	vctMRMField.add("reject");
	vctMRMField.add("poNumber");
	vctMRMField.add("poDate");
	vctMRMField.add("beneficiaryAccount");
	vctMRMField.add("correctedAccount");
	vctMRMField.add("accountName");
	vctMRMField.add("acctName");
	vctMRMField.add("amountCurrency");
	vctMRMField.add("rateCode");
	vctMRMField.add("rate");
	vctMRMField.add("reasonForFailure");
	vctMRMField.add("reasonCode");
	vctMRMField.add("expDate");
	vctMRMField.add("newRate");
	ARJspCurr.setInput(sSubGrpName+"_"+pageName+".mrmFields", vctMRMField);
%>
<script>

	var sPopUpExceptionWindow = '<%=ParseValue.checkString(sPopUpExceptionWindow)%>';
	var sReferralMode = '<%=ParseValue.checkString(sReferralMode)%>';
	var subGroupName = '<%=ParseValue.checkString(ARJspCurr.getInput("subGroupName",""))%>';
	var chkselname = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".chkselname",""))%>';
	var chkreject = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".chkreject",""))%>';
	var funcCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".funcCode",""))%>';
	var funcCodeD = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".funcCodeD",""))%>';
	var paysysId = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".paysysId",""))%>';
	var msgType = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".msgType ",""))%>';
	var totalRecords = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".totalRecords",""))%>';
	
	

	

	var CurrentPage = '<%=iCurrentPage%>';
	var MaxPage = '<%=iMaxPage%>';
	var startRecord = '<%=startRecord%>';
	var ListMaxDisplay = '<%=iListMaxDisplay%>';
	var CurrentSetSize = '<%=iCurrentSetSize%>';
	
	
	
	
	

	var iListMaxDisplay='<%=iListMaxDisplay%>';
	var selname = new Array(iListMaxDisplay);
	var reject = new Array(iListMaxDisplay);
	var poNumber = new Array(iListMaxDisplay);
	var poDate = new Array(iListMaxDisplay);
	var beneficiaryAccount = new Array(iListMaxDisplay);
	var correctedAccount = new Array(iListMaxDisplay);
	var accountName = new Array(iListMaxDisplay);
	var amountCurrency = new Array(iListMaxDisplay);
	var rateCode = new Array(iListMaxDisplay);
	var rate = new Array(iListMaxDisplay);
	var reasonForFailure = new Array(iListMaxDisplay);
	var reasonCode = new Array(iListMaxDisplay);
	var expDate = new Array(iListMaxDisplay);
	var newRate = new Array(iListMaxDisplay);
	var acctName = new Array(iListMaxDisplay);
</script>


<%
	for(int i=0;i<iListMaxDisplay;i++)
	{
		iCounter= startRecord + i;
	%>
	<script language="JavaScript">
		selname['<%=i%>']= '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+"_"+pageName+".selname_"+iCounter,""))%>';
		reject['<%=i%>']= '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+"_"+pageName+".reject_"+iCounter,""))%>';
		poNumber['<%=i%>']= '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+"_"+pageName+".poNumber_"+iCounter,""))%>';
		poDate['<%=i%>']= '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+"_"+pageName+".poDate_"+iCounter,""))%>';
		beneficiaryAccount['<%=i%>']= '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+"_"+pageName+".beneficiaryAccount_"+iCounter,""))%>';
		correctedAccount['<%=i%>']= '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+"_"+pageName+".correctedAccount_"+iCounter,""))%>';
				accountName['<%=i%>']= '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+"_"+pageName+".accountName_"+iCounter,""))%>';
						acctName['<%=i%>']= '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+"_"+pageName+".acctName_"+iCounter,""))%>';

		amountCurrency['<%=i%>']= '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+"_"+pageName+".amountCurrency_"+iCounter,""))%>';
		rateCode['<%=i%>']= '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+"_"+pageName+".rateCode_"+iCounter,""))%>';
		rate['<%=i%>']= '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+"_"+pageName+".rate_"+iCounter,""))%>';
		reasonForFailure['<%=i%>']= '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+"_"+pageName+".reasonForFailure_"+iCounter,""))%>';
		reasonCode['<%=i%>']= '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+"_"+pageName+".reasonCode_"+iCounter,""))%>';
		expDate['<%=i%>']= '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+"_"+pageName+".expDate_"+iCounter,""))%>';
		newRate['<%=i%>']= '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+"_"+pageName+".newRate_"+iCounter,""))%>';
		var funcCodeD = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".funcCodeD",""))%>';
		var paysysId = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".paysysId",""))%>';
		var msgType = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".msgType",""))%>';
		
	</script>
	<%
	}
%>

<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showAccountIdList.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showRefCode.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showListCode.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showSearcher.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("common_functions.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("resource_functions.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/custom/javascripts/<%=VRPKeys.getFile("custom_functions.js",sProfileId)%>"> </script>
<SCRIPT language="javascript" src="../../custom/jsp/cust_frm_fetch.jsp" ></SCRIPT>

<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("cust_evt.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("loc_evt.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("core_banking.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("resource_functions.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("login_common_functions.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("common_functions.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("common_constants.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("hotkeyprocessor_link.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("hotkeydata_link.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showSearcher.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("explode_functions.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("cust_functions.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("expldhndl.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/custom/javascripts/<%=VRPKeys.getFile("custom_functions.js",sProfileId)%>"> </script>
<script language="javascript" src="../Renderer/custom/javascripts/<%=VRPKeys.getFile("cd_atf_functions.js",sProfileId)%>"> </script>
<script language="javascript" src="../Renderer/custom/javascripts/jspjs/INFENG/<%=VRPKeys.getFile("DFCU_INFENG.js",sProfileId)%>"> </script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showSolId.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showSearcher.js",sProfileId)%>" > </script>

<script language="JavaScript">
</script>

<script language="JavaScript">
	printBlock();
	printFooterBlock();
</script>

