#SPRING JPA
spring.jpa.properties.hibernate.hbm2ddl.auto=update
spring.jpa.properties.hibernate.jdbc.batch_size = 50
spring.jpa.properties.hibernate.order_inserts = true
##Show SQL
spring.jpa.properties.hibernate.show_sql=false
spring.jpa.properties.hibernate.use_sql_comments=false
spring.jpa.properties.hibernate.format_sql=false
#
###SPRING DATA SOURCE
spring.datasource.url=${CD_SPRING_DATASOURCE_URL}
spring.datasource.username=${CD_SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${CD_SPRING_DATASOURCE_PASSWORD}
spring.datasource.driverClassName=oracle.jdbc.OracleDriver
spring.datasource.testOnBorrow=true
spring.datasource.validationQuery=SELECT 1 FROM DUAL
spring.hikari.poolName=Hikari
spring.hikari.auto-commit=false

moneygram.cd.mock.token=true

moneygram.params.agentSequence=$(CD_MONEYGRAM_PARAMS_AGENTSEQUENCE)
moneygram.params.agentSequence.reversal=${CD_MONEYGRAM_PARAMS_AGENTSEQUENCE_REVERSAL}
moneygram.params.token=${CD_MONEYGRAM_PARAMS_TOKEN}
moneygram.params.agentId=${CD_MONEYGRAM_PARAMS_AGENTID}
moneygram.params.apiVersion=${CD_MONEYGRAM_PARAMS_API_VERSION}
moneygram.params.apiVersion.gffp=${CD_MONEYGRAM_PARAMS_API_VERSION_GFFP}
moneygram.params.clientSoftwareVersion=${CD_MONEYGRAM_PARAMS_CLIENT_SOFTWARE_VERSION}
moneygram.params.clientSoftwareVersion.feeLookup=${CD_MONEYGRAM_PARAMS_CLIENT_SOFTWARE_VERSION}

#EUREKA
eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=http://localhost:8581/eureka/
eureka.client.enabled=true

config.async.corePoolSize=50
config.async.maxPoolSize=150
config.async.queueCapacity=10000

logging.level.ROOT=INFO
logging.level.com.equitybankgroup.payments.imt.tech_imt_moneygram_cd_ms=INFO
logging.level.org.apache.cx=INFO
