#SPRING JPA
spring.jpa.database=mysql
spring.jpa.properties.hibernate.hbm2ddl.auto=update
spring.jpa.properties.hibernate.jdbc.batch_size = 50
spring.jpa.properties.hibernate.order_inserts = true
#Show SQL
#spring.jpa.properties.hibernate.show_sql=true
#spring.jpa.properties.hibernate.use_sql_comments=true
#spring.jpa.properties.hibernate.format_sql=true
spring.main.allow-bean-definition-overriding=true
#
###SPRING DATA SOURCE
spring.datasource.url=jdbc:mysql://localhost:3306/c4testdb?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=root

moneygram.cd.mock.token=true

#EUREKA
eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=http://localhost:8581/eureka/
eureka.client.enabled=false

javax.net.ssl.keyStore=/Users/ronaldcheruiyot/Documents/java-projects/DRC-PROJECTS/imt/tech-imt-moneygram-cd-ms/src/main/resources/airtimeservice.p12
javax.net.ssl.keyStorePassword=airtimeservice

#Logging
logging.level.root=INFO

config.async.corePoolSize=50
config.async.maxPoolSize=150
config.async.queueCapacity=10000
 