<%--
//Generated by Customization WB Generator
//Do not edit this file directly.
//Instead, modify the properties in the tool and regenerate.
--%>

<%@ page import="applcommon.ParseValue" %>
<%@ page import="com.infy.bbu.jsputil.*"%>
<%@ page import="FABCommon.SecurityInfo70"%>
<%@ taglib uri="taglib.tld" prefix="arjsp" %>
<arjsp:init groupName="Customize" isEntryPoint="false" />

<%
	String sProfileId = ProfilesManager.getProfileInSession(session);
	String sSubGrpName = (String)ARJspCurr.getInput("subGroupName","");
	String sGrpName = ARJspCurr.getCurrentGroup();
	String sPopUpExceptionWindow = (String)ARJspCurr.getInput(sGrpName+".PopUpExceptionWindow" ,"false");
	String sReferralMode = (String)ARJspCurr.getInput("refSubMode" ,"");
	ARJspCurr.setInput(sGrpName+".PopUpExceptionWindow","false");
	SecurityInfo70 securityInfo = (SecurityInfo70)session.getAttribute("FinUserInfo");
	String funcCode=request.getParameter("cmpad.funcCode")!=null ?request.getParameter("cmpad.funcCode"):"";
	String custID=request.getParameter("cmpad.custID")!=null ?request.getParameter("cmpad.custID"):"";
	String foracid=request.getParameter("cmpad.foracid")!=null ?request.getParameter("cmpad.foracid"):"";
%>
<script>

	var sPopUpExceptionWindow = '<%=sPopUpExceptionWindow%>';
	var sReferralMode = '<%=sReferralMode%>' ;

	var subGroupName = '<%=ParseValue.checkString(ARJspCurr.getInput("subGroupName",""))%>';
	var funcCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".funcCode",""))%>';
	var custID = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".custID",""))%>';
	var foracid = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".foracid",""))%>';
	var msg1 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".msg1",""))%>';
	var msg2 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".msg2",""))%>';
	var msg3 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".msg3",""))%>';
	var msg4 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".msg4",""))%>';
	var msg5 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".msg5",""))%>';
	var msg6 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".msg6",""))%>';
	var msg7 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".msg7",""))%>';
	var commChange = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".commChange",""))%>';
	var BODDate= "<%=(securityInfo.bodDate).substring(0,10)%>";
	var accntName = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".accntName",""))%>';
	var enterer = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".enterer",""))%>';
	var auditDate = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".auditDate",""))%>';
</script>

<script language="javascript" src="../Renderer/javascripts/custom_functions.js"></script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("cust_pre_evt.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("cust_evt.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showSolId.js",sProfileId)%>" > </script>

<script language="JavaScript">
	printBlock();
	printFooterBlock();
</script>

