<%--
//Generated by Customization WB Generator
//Do not edit this file directly.
//Instead, modify the properties in the tool and regenerate.
--%>

<%@ page import="applcommon.ParseValue" %>
<%@ page import="com.infy.bbu.jsputil.*"%>
<%@ page import="java.util.Vector"%>
<%@ page import="FABCommon.SecurityInfo70"%>
<%@ taglib uri="taglib.tld" prefix="arjsp" %>
<arjsp:init groupName="Customize" isEntryPoint="false" />

<%
	String sProfileId = ProfilesManager.getProfileInSession(session);
	String sSubGrpName = (String)ARJspCurr.getInput("subGroupName","");
	String sGrpName = ARJspCurr.getCurrentGroup();
	String pageName = (String)ARJspCurr.getInput("jspName","");
	String sPopUpExceptionWindow = (String)ARJspCurr.getInput(sGrpName+".PopUpExceptionWindow" ,"false");
	String sReferralMode = (String)ARJspCurr.getInput("refSubMode" ,"");
	ARJspCurr.setInput(sGrpName+".PopUpExceptionWindow","false");
	SecurityInfo70 securityInfo = (SecurityInfo70)session.getAttribute("FinUserInfo");


%>
<script>
	var sPopUpExceptionWindow = '<%=ParseValue.checkString(sPopUpExceptionWindow)%>';
	var sReferralMode = '<%=ParseValue.checkString(sReferralMode)%>';
	var subGroupName = '<%=ParseValue.checkString(ARJspCurr.getInput("subGroupName",""))%>';
	var funcCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".funcCode",""))%>';
	var JoinDate = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".JoinDate",""))%>';
	var JoinDate_ui = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".JoinDate_ui",""))%>';
	var BODDate= "<%=(securityInfo.bodDate).substring(0,10)%>";
	var fileName= '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".fileName",""))%>';
	var batchId ='<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".batchId",""))%>';
</script>

<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("cust_evt.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("core_banking.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("resource_functions.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("common_functions.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/custom/javascripts/custom_functions.js"></script>
<script language="javascript" src="../javascripts/custom_common_functions.js"></script>
<script language="javascript" src="../Renderer/custom/javascripts/cust_fetch_list.js"></script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("cust_pre_evt.js",sProfileId)%>" > </script>
<script language="Javascript" src="../custom/javascripts/custom_common_functions.js" > </script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showSearcher.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("cust_post_evt.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("common_functions.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showAccountIdList.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/custom/javascripts/<%=VRPKeys.getCustomFile("custom_functions.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showAccountIdList.js",sProfileId)%>" > </script>
<script language="JavaScript">
</script>

<script language="JavaScript">
	printBlock();
	printFooterBlock();
</script>
