<%--
//Generated by Customization WB Generator
//Do not edit this file directly.
//Instead, modify the properties in the tool and regenerate.
--%>

<%@ page import="applcommon.ParseValue" %>
<%@ page import="com.infy.bbu.jsputil.*"%>
<%@ taglib uri="taglib.tld" prefix="arjsp" %>
<arjsp:init groupName="Customize" isEntryPoint="false" />

<%
	String sSubGrpName = (String)ARJspCurr.getInput("subGroupName","");
	String sGrpName = ARJspCurr.getCurrentGroup();
	String sPopUpExceptionWindow = (String)ARJspCurr.getInput(sGrpName+".PopUpExceptionWindow" ,"false");
	String sReferralMode = (String)ARJspCurr.getInput("refSubMode" ,"");
	ARJspCurr.setInput(sGrpName+".PopUpExceptionWindow","false");
	String currncy = request.getParameter("currncy");
	if( currncy == null) currncy = "";
	String sysCalAmt = request.getParameter("sysCalAmt");
	if( sysCalAmt == null) sysCalAmt = "";
	String usrEntAmt = request.getParameter("usrEntAmt");
	if( usrEntAmt == null) usrEntAmt = "";
	String chrgPart = request.getParameter("chrgPart");
	if( chrgPart == null) chrgPart = "";
	String isMod = request.getParameter("isMod");
	if( isMod == null) isMod = "";

%>
<script>

	var sPopUpExceptionWindow = '<%=sPopUpExceptionWindow%>';
	var sReferralMode = '<%=sReferralMode%>' ;

	var subGroupName = '<%=ParseValue.checkString(ARJspCurr.getInput("subGroupName",""))%>';
	var currncy = '<%=currncy%>';
	var sysCalAmt = '<%=sysCalAmt%>';
	var usrEntAmt = '<%=usrEntAmt%>';
	var chrgPart = '<%=chrgPart%>';
	var isMod = '<%=isMod%>';

</script>



<script language="JavaScript">
	printBlock();
	printFooterBlock();
</script>

