<%--
//Generated by Customization WB Generator
//Do not edit this file directly.
//Instead, modify the properties in the tool and regenerate.
--%>



<%@ page import="applcommon.ParseValue" %>
<%@ page import="com.infy.bbu.jsputil.*,FABProcess.*,FABCommon.*"%>
<%@ page import="FABCommon.SecurityInfo70"%>
<%@ page import="java.util.*"%>
<%@ taglib uri="taglib.tld" prefix="arjsp" %>
<arjsp:init groupName="Customize" isEntryPoint="false" />


<%
        String sProfileId = ProfilesManager.getProfileInSession(session);
        String sSubGrpName = (String)ARJspCurr.getInput("subGroupName","");
        String sGrpName = ARJspCurr.getCurrentGroup();
        String sPopUpExceptionWindow = (String)ARJspCurr.getInput(sGrpName+".PopUpExceptionWindow" ,"false");
        String sReferralMode = (String)ARJspCurr.getInput("refSubMode" ,"");
        ARJspCurr.setInput(sGrpName+".PopUpExceptionWindow","false");
        SecurityInfo70 securityInfo = (SecurityInfo70)session.getAttribute("FinUserInfo");

%>
<script>

        var sPopUpExceptionWindow = '<%=sPopUpExceptionWindow%>';
        var sReferralMode = '<%=sReferralMode%>' ;

        var subGroupName = '<%=ParseValue.checkString(ARJspCurr.getInput("subGroupName",""))%>';
        var acctCrncy = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".acctCrncy",""))%>';
        var refCrncy = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".refCrncy",""))%>';
        var receivedAmt = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".receivedAmt",""))%>';
        var amtFrmCcy = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".amtFrmCcy",""))%>';
        var acctCrncyAmt = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".acctCrncyAmt",""))%>';
        var rateCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".rateCode",""))%>';
        var rate = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".rate",""))%>';
        var chrgEvntId = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".chrgEvntId",""))%>';
        var chrgAmt = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".chrgAmt",""))%>';
        var treaRefNum = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".treaRefNum",""))%>';
        var treaRate = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".treaRate",""))%>';
        var funcCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".funcCode",""))%>';
        var retValue = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".retValue",""))%>';
        var custName = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".custName",""))%>';
        var idNum = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".idNum",""))%>';
        var phoneNo = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".phoneNo",""))%>';
        var docDetails = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".docDetails",""))%>';
        var nationDet = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".nationDet",""))%>';
        var tranParticularsCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".tranParticularsCode",""))%>';
         var MiddleName = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".MiddleName",""))%>';
        var LastName = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".LastName",""))%>';

</script>
<LINK href="/finbranch/stylesheets/services.css" rel=STYLESHEET  title="Finacle Stylesheet" type=text/css />
<script language="javascript" src='../Renderer/javascripts/<%=VRPKeys.getFile("core_banking.js",sProfileId)%>' > </script>
<script language="javascript" src='../Renderer/javascripts/lists/<%=VRPKeys.getFile("showRefCode.js",sProfileId)%>' > </script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("resource_functions.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/custom/javascripts/<%=VRPKeys.getFile("array.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/custom/javascripts/<%=VRPKeys.getFile("custom_functions.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/custom/javascripts/<%=VRPKeys.getFile("cust_denom_functions.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/custom/javascripts/<%=VRPKeys.getFile("cust_advicePrint.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/custom/javascripts/<%=VRPKeys.getCustomFile("btextrndp001.js",sProfileId)%>"> </script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("getEvtIdList.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("cust_evt.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("loc_evt.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("cust_pre_evt.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("cust_post_evt.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("common_functions.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showCurrency.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showSearcher.js",sProfileId)%>"></script>

<script language="JavaScript">
        printBlock();
        printFooterBlock();
</script>

