package com.equitybank.drplatform.service;

import com.equitybank.drplatform.audit.Auditable;
import com.equitybank.drplatform.dto.response.ChecklistItemDto;
import com.equitybank.drplatform.entity.ChecklistItemEntity;
import com.equitybank.drplatform.enums.ChecklistItemStatus;
import com.equitybank.drplatform.exception.ResourceNotFoundException;
import com.equitybank.drplatform.exception.ValidationException;
import com.equitybank.drplatform.repository.ChecklistItemRepository;
import com.equitybank.drplatform.security.DrPlatformUserDetails;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

@Slf4j
@Service
@RequiredArgsConstructor
public class CarryForwardService {

    private final ChecklistItemRepository checklistItemRepository;

    /**
     * Carries forward all BLOCKED or PENDING items from a source campaign application
     * into a target campaign application. Used when an application's DR is rescheduled.
     *
     * @param sourceCampaignApplicationId source (completed/cancelled) campaign application
     * @param targetCampaignApplicationId target (new) campaign application
     * @return list of newly created carry-forward checklist items
     */
    @Auditable(action = "CHECKLIST_ITEMS_CARRIED_FORWARD", resourceType = "ChecklistItem")
    @Transactional
    public List<ChecklistItemDto> carryForwardBlockers(UUID sourceCampaignApplicationId,
                                                        UUID targetCampaignApplicationId) {
        List<ChecklistItemEntity> sourceItems = checklistItemRepository
                .findByCampaignApplicationIdOrderBySortOrder(sourceCampaignApplicationId);

        List<ChecklistItemEntity> itemsToCarry = sourceItems.stream()
                .filter(i -> i.getStatus() == ChecklistItemStatus.BLOCKED
                        || i.getStatus() == ChecklistItemStatus.PENDING
                        || i.getStatus() == ChecklistItemStatus.IN_PROGRESS)
                .toList();

        if (itemsToCarry.isEmpty()) {
            log.info("No items to carry forward from campaignApplication {}", sourceCampaignApplicationId);
            return List.of();
        }

        // Determine base sort order for new items
        int maxExistingSort = checklistItemRepository
                .findByCampaignApplicationIdOrderBySortOrder(targetCampaignApplicationId)
                .stream()
                .mapToInt(ChecklistItemEntity::getSortOrder)
                .max()
                .orElse(0);

        List<ChecklistItemEntity> created = new ArrayList<>();
        for (int i = 0; i < itemsToCarry.size(); i++) {
            ChecklistItemEntity source = itemsToCarry.get(i);
            ChecklistItemEntity carried = new ChecklistItemEntity();
            carried.setCampaignApplicationId(targetCampaignApplicationId);
            carried.setTitle("[CARRIED FORWARD] " + source.getTitle());
            carried.setNotes(source.getNotes());
            carried.setStatus(ChecklistItemStatus.CARRIED_FORWARD);
            carried.setSortOrder(maxExistingSort + i + 1);
            carried.setIsAutoGenerated(false);
            carried.setCarriedForwardFromId(source.getId());
            carried.setCarriedForwardAt(java.time.LocalDateTime.now());
            created.add(checklistItemRepository.save(carried));
        }

        // Mark source items as carried forward
        for (ChecklistItemEntity source : itemsToCarry) {
            source.setStatus(ChecklistItemStatus.CARRIED_FORWARD);
            checklistItemRepository.save(source);
        }

        log.info("Carried forward {} checklist items from {} to {}",
                created.size(), sourceCampaignApplicationId, targetCampaignApplicationId);

        return created.stream().map(ChecklistItemDto::fromEntity).toList();
    }

    @Transactional(readOnly = true)
    public List<ChecklistItemDto> getCarriedForwardItems(UUID campaignApplicationId) {
        return checklistItemRepository
                .findByCampaignApplicationIdAndCarriedForwardFromIdIsNotNull(campaignApplicationId)
                .stream()
                .map(ChecklistItemDto::fromEntity)
                .toList();
    }

    @Auditable(action = "CARRIED_FORWARD_ITEM_ACKNOWLEDGED", resourceType = "ChecklistItem")
    @Transactional
    public ChecklistItemDto acknowledgeCarriedItem(UUID itemId) {
        ChecklistItemEntity item = checklistItemRepository.findById(itemId)
                .orElseThrow(() -> new ResourceNotFoundException("ChecklistItem", itemId));

        if (item.getCarriedForwardFromId() == null) {
            throw new ValidationException("Item " + itemId + " is not a carried-forward item");
        }

        if (item.getStatus() != ChecklistItemStatus.CARRIED_FORWARD) {
            throw new ValidationException("Item is not in CARRIED_FORWARD status");
        }

        item.setStatus(ChecklistItemStatus.IN_PROGRESS);
        item.setAcknowledgedById(currentUserId());
        item.setAcknowledgedAt(java.time.LocalDateTime.now());
        return ChecklistItemDto.fromEntity(checklistItemRepository.save(item));
    }

    private UUID currentUserId() {
        var auth = SecurityContextHolder.getContext().getAuthentication();
        if (auth != null && auth.getPrincipal() instanceof DrPlatformUserDetails ud) {
            return ud.getUser().getId();
        }
        throw new ValidationException("No authenticated user found");
    }
}
