package com.equitybank.drplatform.service;

import com.equitybank.drplatform.audit.Auditable;
import com.equitybank.drplatform.dto.request.RaiseBlockerRequest;
import com.equitybank.drplatform.dto.request.UpdateChecklistItemStatusRequest;
import com.equitybank.drplatform.dto.response.ChecklistItemDto;
import com.equitybank.drplatform.dto.response.ChecklistSummaryDto;
import com.equitybank.drplatform.entity.ChecklistBlockerEntity;
import com.equitybank.drplatform.entity.ChecklistItemEntity;
import com.equitybank.drplatform.entity.PreDrSignoffEntity;
import com.equitybank.drplatform.enums.ChecklistItemStatus;
import com.equitybank.drplatform.exception.ResourceNotFoundException;
import com.equitybank.drplatform.exception.ValidationException;
import com.equitybank.drplatform.repository.CampaignApplicationRepository;
import com.equitybank.drplatform.repository.ChecklistBlockerRepository;
import com.equitybank.drplatform.repository.ChecklistItemRepository;
import com.equitybank.drplatform.repository.PreDrSignoffRepository;
import com.equitybank.drplatform.security.DrPlatformUserDetails;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.List;
import java.util.UUID;

@Slf4j
@Service
@RequiredArgsConstructor
public class ChecklistService {

    private final ChecklistItemRepository checklistItemRepository;
    private final ChecklistBlockerRepository checklistBlockerRepository;
    private final PreDrSignoffRepository preDrSignoffRepository;
    private final CampaignApplicationRepository campaignApplicationRepository;

    private static final List<String> DEFAULT_RUNBOOK_ITEMS = List.of(
            "Runbook document uploaded and version-controlled",
            "Failover steps documented (step-by-step)",
            "Rollback procedure documented",
            "Recovery Time Objective (RTO) confirmed and documented",
            "Recovery Point Objective (RPO) confirmed and documented",
            "Contact list (primary + backup) confirmed",
            "War room bridge details communicated",
            "Pre-DR environment health check passed",
            "Database backup verified before DR",
            "Network connectivity to DR site confirmed",
            "DNS/load-balancer failover procedure documented",
            "Downstream system owners notified",
            "Upstream dependency owners notified",
            "ITSCM approval obtained",
            "Peer review completed and signed off",
            "Smoke test plan documented",
            "Post-DR validation checklist prepared"
    );

    @Transactional
    public void generateDefaultItems(UUID campaignApplicationId) {
        // Avoid duplicate generation
        long existing = checklistItemRepository.countByCampaignApplicationId(campaignApplicationId);
        if (existing > 0) {
            log.debug("Checklist items already exist for campaignApplication {}", campaignApplicationId);
            return;
        }

        for (int i = 0; i < DEFAULT_RUNBOOK_ITEMS.size(); i++) {
            ChecklistItemEntity item = new ChecklistItemEntity();
            item.setCampaignApplicationId(campaignApplicationId);
            item.setTitle(DEFAULT_RUNBOOK_ITEMS.get(i));
            item.setStatus(ChecklistItemStatus.PENDING);
            item.setSortOrder(i + 1);
            item.setIsAutoGenerated(true);
            checklistItemRepository.save(item);
        }
        log.info("Generated {} default checklist items for campaignApplication {}",
                DEFAULT_RUNBOOK_ITEMS.size(), campaignApplicationId);
    }

    @Transactional(readOnly = true)
    public List<ChecklistItemDto> getChecklistForOwner(UUID campaignApplicationId) {
        return checklistItemRepository.findByCampaignApplicationIdOrderBySortOrder(campaignApplicationId)
                .stream()
                .map(ChecklistItemDto::fromEntity)
                .toList();
    }

    @Transactional(readOnly = true)
    public ChecklistSummaryDto getChecklistSummary(UUID campaignApplicationId) {
        var raw = checklistItemRepository.getChecklistSummary(campaignApplicationId);
        return ChecklistSummaryDto.fromRaw(raw);
    }

    @Auditable(action = "CHECKLIST_ITEM_STATUS_UPDATED", resourceType = "ChecklistItem")
    @Transactional
    public ChecklistItemDto updateItemStatus(UUID itemId, UpdateChecklistItemStatusRequest req) {
        ChecklistItemEntity item = checklistItemRepository.findById(itemId)
                .orElseThrow(() -> new ResourceNotFoundException("ChecklistItem", itemId));

        if (item.getStatus() == ChecklistItemStatus.VERIFIED) {
            throw new ValidationException("Cannot change status of a VERIFIED checklist item");
        }

        item.setStatus(req.getStatus());
        if (req.getNotes() != null) {
            item.setNotes(req.getNotes());
        }
        if (req.getStatus() == ChecklistItemStatus.DONE) {
            item.setCompletedAt(LocalDateTime.now());
            item.setCompletedById(currentUserId());
        }
        return ChecklistItemDto.fromEntity(checklistItemRepository.save(item));
    }

    @Auditable(action = "CHECKLIST_BLOCKER_RAISED", resourceType = "ChecklistBlocker")
    @Transactional
    public ChecklistItemDto blockItem(UUID itemId, RaiseBlockerRequest req) {
        ChecklistItemEntity item = checklistItemRepository.findById(itemId)
                .orElseThrow(() -> new ResourceNotFoundException("ChecklistItem", itemId));

        item.setStatus(ChecklistItemStatus.BLOCKED);
        checklistItemRepository.save(item);

        ChecklistBlockerEntity blocker = new ChecklistBlockerEntity();
        blocker.setChecklistItemId(itemId);
        blocker.setDescription(req.getDescription());
        blocker.setRaisedById(currentUserId());
        blocker.setSeverity(req.getSeverity());
        blocker.setEscalatedTo(req.getEscalateTo());
        checklistBlockerRepository.save(blocker);

        return ChecklistItemDto.fromEntity(item);
    }

    @Auditable(action = "CHECKLIST_BLOCKER_RESOLVED", resourceType = "ChecklistBlocker")
    @Transactional
    public ChecklistItemDto resolveBlocker(UUID blockerId, String resolutionNotes) {
        ChecklistBlockerEntity blocker = checklistBlockerRepository.findById(blockerId)
                .orElseThrow(() -> new ResourceNotFoundException("ChecklistBlocker", blockerId));

        if (blocker.getResolvedAt() != null) {
            throw new ValidationException("Blocker is already resolved");
        }

        blocker.setResolvedById(currentUserId());
        blocker.setResolvedAt(LocalDateTime.now());
        blocker.setResolutionNotes(resolutionNotes);
        checklistBlockerRepository.save(blocker);

        // Move item back to IN_PROGRESS
        ChecklistItemEntity item = checklistItemRepository.findById(blocker.getChecklistItemId())
                .orElseThrow(() -> new ResourceNotFoundException("ChecklistItem", blocker.getChecklistItemId()));
        item.setStatus(ChecklistItemStatus.IN_PROGRESS);
        return ChecklistItemDto.fromEntity(checklistItemRepository.save(item));
    }

    @Auditable(action = "PRE_DR_SIGNOFF_SUBMITTED", resourceType = "PreDrSignoff")
    @Transactional
    public void submitSignOff(UUID campaignApplicationId) {
        // Verify all mandatory items are DONE or VERIFIED
        List<ChecklistItemEntity> items = checklistItemRepository
                .findByCampaignApplicationIdOrderBySortOrder(campaignApplicationId);

        List<String> incomplete = items.stream()
                .filter(i -> i.getIsAutoGenerated() &&
                        i.getStatus() != ChecklistItemStatus.DONE &&
                        i.getStatus() != ChecklistItemStatus.VERIFIED &&
                        i.getStatus() != ChecklistItemStatus.CARRIED_FORWARD)
                .map(ChecklistItemEntity::getTitle)
                .toList();

        if (!incomplete.isEmpty()) {
            throw new ValidationException("Cannot submit sign-off: " + incomplete.size()
                    + " mandatory checklist item(s) not completed: " + incomplete.get(0)
                    + (incomplete.size() > 1 ? " (and " + (incomplete.size() - 1) + " more)" : ""));
        }

        boolean alreadySubmitted = preDrSignoffRepository.existsByCampaignApplicationId(campaignApplicationId);
        if (alreadySubmitted) {
            throw new ValidationException("Pre-DR sign-off already submitted for this application");
        }

        PreDrSignoffEntity signoff = new PreDrSignoffEntity();
        signoff.setCampaignApplicationId(campaignApplicationId);
        signoff.setSubmittedById(currentUserId());
        signoff.setSubmittedAt(LocalDateTime.now());
        preDrSignoffRepository.save(signoff);
    }

    @Auditable(action = "PRE_DR_SIGNOFF_ACKNOWLEDGED", resourceType = "PreDrSignoff")
    @Transactional
    public void acknowledgeSignOff(UUID campaignApplicationId) {
        PreDrSignoffEntity signoff = preDrSignoffRepository
                .findByCampaignApplicationId(campaignApplicationId)
                .orElseThrow(() -> new ValidationException("No pre-DR sign-off found for this application"));

        if (signoff.getCoordinatorAcknowledgedAt() != null) {
            throw new ValidationException("Sign-off already acknowledged");
        }

        signoff.setCoordinatorAcknowledgedById(currentUserId());
        signoff.setCoordinatorAcknowledgedAt(LocalDateTime.now());
        preDrSignoffRepository.save(signoff);
    }

    @Transactional
    public ChecklistItemDto addCustomItem(UUID campaignApplicationId, String title, String notes, int sortOrder) {
        ChecklistItemEntity item = new ChecklistItemEntity();
        item.setCampaignApplicationId(campaignApplicationId);
        item.setTitle(title);
        item.setNotes(notes);
        item.setStatus(ChecklistItemStatus.PENDING);
        item.setSortOrder(sortOrder);
        item.setIsAutoGenerated(false);
        return ChecklistItemDto.fromEntity(checklistItemRepository.save(item));
    }

    private UUID currentUserId() {
        var auth = SecurityContextHolder.getContext().getAuthentication();
        if (auth != null && auth.getPrincipal() instanceof DrPlatformUserDetails ud) {
            return ud.getUser().getId();
        }
        throw new ValidationException("No authenticated user found");
    }
}
