1. Table: banks

insert into [dbo].[banks] (id, bank_id, bank_name, bank_status) values (1, '0001', 'KCB', 'ONLINE');
insert into [dbo].[banks] (id, bank_id, bank_name, bank_status) values (2, '0002', 'Stanchart', 'ONLINE'); 
insert into [dbo].[banks] (id, bank_id, bank_name, bank_status) values (3, '0003', 'ABSA', 'ONLINE'); 
insert into [dbo].[banks] (id, bank_id, bank_name, bank_status) values (4, '0005', 'Bank of India', 'OFFLINE'); 
insert into [dbo].[banks] (id, bank_id, bank_name, bank_status) values (5, '0006', 'Bank of Baroda', 'OFFLINE'); 
insert into [dbo].[banks] (id, bank_id, bank_name, bank_status) values (6, '0007', 'NCBA', 'ONLINE'); 
insert into [dbo].[banks] (id, bank_id, bank_name, bank_status) values (7, '0010', 'Prime Bank', 'ONLINE'); 
insert into [dbo].[banks] (id, bank_id, bank_name, bank_status) values (8, '0011', 'Coop Bank', 'ONLINE'); 
insert into [dbo].[banks] (id, bank_id, bank_name, bank_status) values (9, '0012', 'NBK', 'ONLINE');
insert into [dbo].[banks] (id, bank_id, bank_name, bank_status) values (10, '0014', 'M-Oriental', 'ONLINE'); 
insert into [dbo].[banks] (id, bank_id, bank_name, bank_status) values (11, '0016', 'Citi Bank', 'ONLINE'); 
insert into [dbo].[banks] (id, bank_id, bank_name, bank_status) values (12, '0017', 'Habib Bank AG Zurich', 'OFFLINE'); 
insert into [dbo].[banks] (id, bank_id, bank_name, bank_status) values (13, '0018', 'Middle East Bank', 'ONLINE'); 
insert into [dbo].[banks] (id, bank_id, bank_name, bank_status) values (14, '0019', 'Bank of Africa', 'ONLINE'); 
insert into [dbo].[banks] (id, bank_id, bank_name, bank_status) values (15, '0023', 'Consolidated', 'ONLINE'); 
insert into [dbo].[banks] (id, bank_id, bank_name, bank_status) values (16, '0025', 'Credit Bank', 'ONLINE'); 
insert into [dbo].[banks] (id, bank_id, bank_name, bank_status) values (16, '0026', 'Access Bank', 'OFFLINE'); 
insert into [dbo].[banks] (id, bank_id, bank_name, bank_status) values (17, '0031', 'Stanbic Bank', 'ONLINE'); 
insert into [dbo].[banks] (id, bank_id, bank_name, bank_status) values (18, '0035', 'ABC Bank', 'ONLINE'); 
insert into [dbo].[banks] (id, bank_id, bank_name, bank_status) values (19, '0043', 'Eco Bank', 'OFFLINE'); 
insert into [dbo].[banks] (id, bank_id, bank_name, bank_status) values (20, '0049', 'SPIRE Bank', 'OFFLINE'); 
insert into [dbo].[banks] (id, bank_id, bank_name, bank_status) values (21, '0050', 'Paramount', 'ONLINE'); 
insert into [dbo].[banks] (id, bank_id, bank_name, bank_status) values (22, '0051', 'Kingdom Bank', 'ONLINE'); 
insert into [dbo].[banks] (id, bank_id, bank_name, bank_status) values (23, '0053', 'Gt Bank', 'ONLINE');
insert into [dbo].[banks] (id, bank_id, bank_name, bank_status) values (24, '0054', 'Victoria Bank', 'ONLINE'); 
insert into [dbo].[banks] (id, bank_id, bank_name, bank_status) values (25, '0055', 'Guardian Bank', 'ONLINE'); 
insert into [dbo].[banks] (id, bank_id, bank_name, bank_status) values (26, '0057', 'I&M Bank', 'ONLINE'); 
insert into [dbo].[banks] (id, bank_id, bank_name, bank_status) values (27, '0059', 'Development Bank', 'OFFLINE'); 
insert into [dbo].[banks] (id, bank_id, bank_name, bank_status) values (28, '0060', 'SBM', 'OFFLINE'); 
insert into [dbo].[banks] (id, bank_id, bank_name, bank_status) values (29, '0061', 'Housing finance', 'ONLINE'); 
insert into [dbo].[banks] (id, bank_id, bank_name, bank_status) values (30, '0063', 'DTB', 'ONLINE'); 
insert into [dbo].[banks] (id, bank_id, bank_name, bank_status) values (31, '0065', 'Mayfair Bank', 'ONLINE'); 
insert into [dbo].[banks] (id, bank_id, bank_name, bank_status) values (32, '0066', 'Sidian Bank', 'ONLINE'); 
insert into [dbo].[banks] (id, bank_id, bank_name, bank_status) values (33, '0068', 'Equity Bank', 'ONLINE'); 
insert into [dbo].[banks] (id, bank_id, bank_name, bank_status) values (34, '0070', 'Family Bank', 'ONLINE'); 
insert into [dbo].[banks] (id, bank_id, bank_name, bank_status) values (35, '0072', 'Gulf African Bank', 'ONLINE'); 
insert into [dbo].[banks] (id, bank_id, bank_name, bank_status) values (36, '0074', 'First Community Bank', 'ONLINE'); 
insert into [dbo].[banks] (id, bank_id, bank_name, bank_status) values (37, '0075', 'DIB Bank', 'ONLINE'); 
insert into [dbo].[banks] (id, bank_id, bank_name, bank_status) values (38, '0076', 'UBA', 'OFFLINE');
insert into [dbo].[banks] (id, bank_id, bank_name, bank_status) values (39, '0078', 'KWFT', 'ONLINE'); 
insert into [dbo].[banks] (id, bank_id, bank_name, bank_status) values (40, '0079', 'Faulu Bank', 'OFFLINE'); 
insert into [dbo].[banks] (id, bank_id, bank_name, bank_status) values (41, '0099', 'Post Bank', 'OFFLINE'); 
insert into [dbo].[banks] (id, bank_id, bank_name, bank_status) values (42, '9999', 'IPS (Instant Payment Switch)', 'ONLINE'); 
insert into [dbo].[banks] (id, bank_id, bank_name, bank_status) values (43, '0086', 'Vooma', 'OFFLINE'); 
insert into [dbo].[banks] (id, bank_id, bank_name, bank_status) values (44, '0087', 'Pesapal', 'OFFLINE'); 
insert into [dbo].[banks] (id, bank_id, bank_name, bank_status) values (45, '0088', 'Interswitch', 'OFFLINE'); 
insert into [dbo].[banks] (id, bank_id, bank_name, bank_status) values (46, '0089', 'Stima Sacco', 'ONLINE'); 
insert into [dbo].[banks] (id, bank_id, bank_name, bank_status) values (47, '0091', 'Flutterwave', 'OFFLINE'); 
insert into [dbo].[banks] (id, bank_id, bank_name, bank_status) values (48, '0092', 'iPay', 'OFFLINE'); 
insert into [dbo].[banks] (id, bank_id, bank_name, bank_status) values (49, '0093', 'KCBbulk', 'OFFLINE'); 
insert into [dbo].[banks] (id, bank_id, bank_name, bank_status) values (50, '0095', 'MFS', 'OFFLINE'); 
insert into [dbo].[banks] (id, bank_id, bank_name, bank_status) values (51, '0097', 'Telkom Kenya', 'ONLINE'); 
insert into [dbo].[banks] (id, bank_id, bank_name, bank_status) values (52, '0037', 'Cellulant', 'OFFLINE');