CREATE TABLE CUSTOM.MOBEE_PUSH_SMS
(
  REF_NO                   VARCHAR2(100 BYTE),
  LANGUAGE                 VARCHAR2(100 BYTE),
  INSTITUTION_CODE         VARCHAR2(100 BYTE),
  MOBILE_NUMBER            VARCHAR2(100 BYTE),
  MESSAGE_ARRIEVED_DATE    VARCHAR2(100 BYTE),
  MESSAGE_PRIORITY         VARCHAR2(100 BYTE),
  MESSAGE_STATUS           VARCHAR2(100 BYTE),
  MESSAGE_VALIDITY_PERIOD  VARCHAR2(100 BYTE),
  DEPARTMENT               VARCHAR2(100 BYTE),
  MESSAGE_TEXT             VARCHAR2(1000 BYTE),
  RETRY_COUNT              VARCHAR2(100 BYTE),
  BANK_ID                  VARCHAR2(100 BYTE)
);


CREATE PUBLIC SYNONYM CUSTOM.MOBEE_PUSH_SMS_SYN FOR MOBEE_PUSH_SMS;

