DROP TABLE CUSTOM.C_UBP_HOCCMMOD CASCADE CONSTRAINTS;

CREATE TABLE CUSTOM.C_UBP_HOCCMMOD
(
  SRL_NO            VARCHAR2(6 CHAR),
  BILLER_ID         VARCHAR2(10 CHAR),
  NAME              VARCHAR2(80 CHAR),
  BILL_AMT          NUMBER(20,4),
  BILLER_REF_NUM    VARCHAR2(50 CHAR),
  TRAN_PARTICULARS  VARCHAR2(50 CHAR),
  TRAN_RMKS         VARCHAR2(30 CHAR),
  APP_CATEGORY      VARCHAR2(16 CHAR),
  FREETEXT1         VARCHAR2(80 CHAR),
  FREETEXT2         VARCHAR2(80 CHAR),
  FREETEXT3         VARCHAR2(80 CHAR),
  FREETEXT4         VARCHAR2(80 CHAR),
  FREETEXT5         VARCHAR2(80 CHAR),
  FREETEXT6         VARCHAR2(80 CHAR),
  FREETEXT7         VARCHAR2(80 CHAR),
  RISK_NOTE         CHAR(1 CHAR),
  REM_DYN_FLD       CLOB
);


DROP SYNONYM CUSTOM.HOCCM_MOD;

CREATE SYNONYM CUSTOM.HOCCM_MOD FOR CUSTOM.C_UBP_HOCCMMOD;

GRANT SELECT ON CUSTOM.C_UBP_HOCCMMOD TO ALLTAB;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.C_UBP_HOCCMMOD TO TBAADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.C_UBP_HOCCMMOD TO TBAGEN;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.C_UBP_HOCCMMOD TO TBAUTIL;
