DROP PROCEDURE CUSTOM.INSERT_INTO_STAGING;

CREATE OR REPLACE PROCEDURE CUSTOM.INSERT_INTO_STAGING(vBankId VARCHAR2)  IS
vAcctDate date;
vUserID varchar2(50);
net_diff number;
written_off_diff number;
diff_amount number;
cust_written_off_diff number;
a_amount number;
errorCode varchar2(150 byte);

--OFFICE
cursor cu1 is
select 
'FINACLE'SOURCE,TO_CHAR(TRAN_date,'DD-MON-YYYY')TRAN_DATE,'EBFIN'COMPANY,branch,decode(BRANCH,'000',decode(DEPARTMENT,'','DEFAULT',department),'DEFAULT')DEPARTMENT,
DECODE(gl_sub_head_code,'30011','30011','30013','30013','30012','30012',account1)ACCOUNT,
DECODE(gl_sub_head_code,'80001',ACCOUNT1,'80002',ACCOUNT1,'80003',ACCOUNT1,'60001',ACCOUNT1,
'60002',ACCOUNT1,'60003',ACCOUNT1,'60004',ACCOUNT1,'60005',ACCOUNT1,'60006',ACCOUNT1,'DEFAULT')product,
DECODE(CHANNEL,NULL,'DEFAULT',CHANNEL)CHANNEL,'DEFAULT' INTERCOMPANY,' 'SEGMENT8,''SEGMENT9,''SEGMENT10,''SEGMENT11,''SEGMENT12,
TRAN_CRNCY_CODE ACCT_CRNCY,''EXCHANGE_RATE,DECODE(TRAN_CRNCY_CODE,'KES','','Corporate')EXCHANGE_RATE_TYPE,
''JOURNAL_SOURCE, ''JOURNAL_TYPE,
DECODE(SUBSTR(SUM(AMOUNT),1,1),'-',SUM(AMOUNT)*-1,0)DR,DECODE(SUBSTR(SUM(AMOUNT),1,1),'-',0,SUM(AMOUNT))CR,
 ''MESSAGE,'N'STATUS,''ERROR_CODE,CREATED_BY,
LAST_UPDATED_BY,''LEDGER_NAME, CHARGED_OFF
 from CUSTOM.daily_movements
WHERE ACCOUNT2 NOT IN ('CAA','SBA','LAA','FBA','TDA') 
AND NVL(BACID,'X') <>'ISO'
GROUP BY TO_CHAR(TRAN_date,'DD-MON-YYYY'),branch,decode(BRANCH,'000',decode(DEPARTMENT,'','DEFAULT',department),'DEFAULT'),
DECODE(gl_sub_head_code,'30011','30011','30013','30013','30012','30012',account1),
CHANNEL,TRAN_CRNCY_CODE,DECODE(gl_sub_head_code,'80001',ACCOUNT1,'80002',ACCOUNT1,'80003',ACCOUNT1,'60001',ACCOUNT1,
'60002',ACCOUNT1,'60003',ACCOUNT1,'60004',ACCOUNT1,'60005',ACCOUNT1,'60006',ACCOUNT1,'DEFAULT'),CREATED_BY,LAST_UPDATED_BY,CHARGED_OFF
UNION all
-- CUSTOMER
select 'FINACLE'SOURCE,TO_CHAR(TRAN_date,'DD-MON-YYYY')TRAN_DATE,'EBFIN'COMPANY,branch,decode(BRANCH,'000',decode(DEPARTMENT,'','DEFAULT',department),'DEFAULT') DEPARTMENT,account2 ACCOUNT,product,
DECODE(CHANNEL,NULL,'FAB',CHANNEL)CHANNEL,'DEFAULT' INTERCOMPANY,' 'SEGMENT8,''SEGMENT9,''SEGMENT10,''SEGMENT11,''SEGMENT12
,TRAN_CRNCY_CODE ACCT_CRNCY,
''EXCHANGE_RATE,DECODE(TRAN_CRNCY_CODE,'KES','','Corporate ')EXCHANGE_RATE_TYPE,
''JOURNAL_SOURCE, ''JOURNAL_TYPE,
DECODE(SUBSTR(SUM(AMOUNT),1,1),'-',SUM(AMOUNT)*-1,0)DR,DECODE(SUBSTR(SUM(AMOUNT),1,1),'-',0,SUM(AMOUNT))CR,
 ''MESSAGE,'N'STATUS,''ERROR_CODE,CREATED_BY,
LAST_UPDATED_BY,''LEDGER_NAME, CHARGED_OFF
 from CUSTOM.daily_movements
WHERE ACCOUNT2 IN ('CAA','SBA','LAA','FBA','TDA')
GROUP BY TO_CHAR(TRAN_date,'DD-MON-YYYY'),branch,decode(BRANCH,'000',decode(DEPARTMENT,'','DEFAULT',department),'DEFAULT'),
account2,PRODUCT,CHANNEL,TRAN_CRNCY_CODE,CREATED_BY,LAST_UPDATED_BY,CHARGED_OFF
union all
-- overdrwan accounts
select 'FINACLE'SOURCE,TO_CHAR(TRAN_date,'DD-MON-YYYY')TRAN_DATE,'EBFIN'COMPANY,branch,decode(BRANCH,'000',decode(DEPARTMENT,'','DEFAULT',department),'DEFAULT') DEPARTMENT,account2 ACCOUNT,product,
DECODE(CHANNEL,NULL,'FAB',CHANNEL)CHANNEL,'DEFAULT' INTERCOMPANY,' 'SEGMENT8,''SEGMENT9,''SEGMENT10,''SEGMENT11,''SEGMENT12
,TRAN_CRNCY_CODE ACCT_CRNCY,
''EXCHANGE_RATE,DECODE(TRAN_CRNCY_CODE,'KES','','Corporate ')EXCHANGE_RATE_TYPE,
''JOURNAL_SOURCE, ''JOURNAL_TYPE,
DECODE(SUBSTR(SUM(AMOUNT),1,1),'-',SUM(AMOUNT)*-1,0)DR,DECODE(SUBSTR(SUM(AMOUNT),1,1),'-',0,SUM(AMOUNT))CR,
 ''MESSAGE,'N'STATUS,''ERROR_CODE,CREATED_BY,
LAST_UPDATED_BY,''LEDGER_NAME, CHARGED_OFF
 from CUSTOM.daily_movements
WHERE ACCOUNT2 IN ('CAA','SBA')
and tran_date=vAcctDate
GROUP BY TO_CHAR(TRAN_date,'DD-MON-YYYY'),branch,decode(BRANCH,'000',decode(DEPARTMENT,'','DEFAULT',department),'DEFAULT'),
account2,PRODUCT,CHANNEL,TRAN_CRNCY_CODE,CREATED_BY,LAST_UPDATED_BY,CHARGED_OFF
UNION all
-- CHARGEOFFS
select 'FINACLE'SOURCE,TO_CHAR(a.TRAN_date,'DD-MON-YYYY')TRAN_DATE ,'EBFIN'COMPANY,a.sol_id BRANCH,decode(A.SOL_ID,'000',decode(REF_NUM,'','DEFAULT',ref_num),'DEFAULT') DEPARTMENT,B.SCHM_TYPE ACCOUNT,
B.SCHM_CODE PRODUCT,DECODE(C.DELIVERY_CHANNEL_ID,NULL,'FAB',C.DELIVERY_CHANNEL_ID) CHANNEL,
'DEFAULT' INTERCOMPANY,' 'SEGMENT8,''SEGMENT9,''SEGMENT10,''SEGMENT11,''SEGMENT12,
a.tran_crncy_code ACCT_CRNCY,''EXCHANGE_RATE,DECODE(TRAN_CRNCY_CODE,'KES','','Corporate')EXCHANGE_RATE_TYPE,
''JOURNAL_SOURCE, ''JOURNAL_TYPE,
SUM(DECODE(PART_TRAN_TYPE,'C',A.TRAN_AMT,0))DR,
SUM(DECODE(PART_TRAN_TYPE,'D',A.TRAN_AMT,0))CR,
''MESSAGE,'N'STATUS,''ERROR_CODE,vUserID,
vUserID,
''LEDGER_NAME,'Y' CHARGED_OFF
from tbaadm.dtd A,tbaadm.GAM B,tbaadm.dTH C where 
A.ACID=B.ACID AND A.BANK_ID = vBankId AND B.BANK_ID = vBankId AND C.BANK_ID = vBankId AND A.TRAN_DATE=C.TRAN_DATE AND A.TRAN_ID=C.TRAN_ID AND A.tran_date=vAcctDate
and A.del_flg='N' AND (A.ACID,A.BANK_ID) IN (SELECT ACID,BANK_ID FROM tbaadm.COT WHERE CHRGE_OFF_DATE IS NOT NULL AND cot.BANK_ID = vBankId)
GROUP BY TO_CHAR(a.TRAN_date,'DD-MON-YYYY'),a.sol_id,a.ref_num,B.SCHM_TYPE,B.SCHM_CODE,C.DELIVERY_CHANNEL_ID,a.tran_crncy_code;

BEGIN

select  db_stat_date 
into    vAcctDate
from    tbaadm.gct where BANK_ID = vBankId;

select  sys_context('USERENV','SESSION_USER') 
INTO    vUserID
from    dual;

vAcctDate :='18-JAN-2010';

for j in cu1 loop
INSERT  INTO CUSTOM.FIN_ORACLE_STAGING
        (SOURCE, ACCT_DATE, COMPANY, SOL_ID, DEPARTMENT, FORACID, PRODUCT, CHANNEL, INTERCOMPANY, SEGMENT8, 
        SEGMENT9, SEGMENT10, SEGMENT11, SEGMENT12,ACCT_CURNCY, EXCHANGE_RATE, EXCHANGE_RATE_TYPE,
        JOURNAL_SOURCE, JOURNAL_TYPE, DEBIT, CREDIT, MESSAGE, STATUS, ERROR_CODE, CREATION_DATE, CREATED_BY, 
        LAST_UPDATE_DATE, LAST_UPDATED_BY, LEDGER_NAME,CHARGED_OFF)
VALUES  (j.SOURCE,J.TRAN_DATE,J.COMPANY, J.BRANCH,J.DEPARTMENT, J.ACCOUNT, J.PRODUCT, J.CHANNEL, J.INTERCOMPANY, J.SEGMENT8, J.SEGMENT9, J.SEGMENT10,
        J.SEGMENT11, J.SEGMENT12, J.ACCT_CRNCY, J.EXCHANGE_RATE, J.EXCHANGE_RATE_TYPE, J.JOURNAL_SOURCE, J.JOURNAL_TYPE, J.DR, J.CR, J.MESSAGE, 
        J.STATUS, J.ERROR_CODE, SYSDATE, vUserID, SYSDATE,11, J.LEDGER_NAME ,J.CHARGED_OFF );    

COMMIT;
END LOOP;

update DAILY_MOVEMENTS 
set status='P';
commit;

net_diff :=0;
written_off_diff :=0;
diff_amount :=0;
cust_written_off_diff :=0;
a_amount :=0;

select nvl(sum(credit)-sum(debit),0)
into net_diff
from FIN_ORACLE_STAGING
where ACCT_DATE =vAcctDate
and charged_off!='O';

select nvl(sum(credit)-sum(debit),0)
into written_off_diff
from FIN_ORACLE_STAGING
where ACCT_DATE =vAcctDate
and charged_off='Y'
and foracid='0000100920';

select net_diff-written_off_diff 
into diff_amount
from dual;


select nvl(sum(credit)-sum(debit),0)
into cust_written_off_diff
from FIN_ORACLE_STAGING
where ACCT_DATE =vAcctDate
and charged_off='Y'
and foracid!='0000100920';

select net_diff - cust_written_off_diff 
into a_amount
from dual;

------
if net_diff=0 OR a_amount=0 then

         -- insert into gl 
       /* TIMO PLEASE DONT UNCOMENT THIS
        insert  into feeder_data
         select SOURCE, ACCT_DATE, COMPANY, SOL_ID, DEPARTMENT, FORACID, PRODUCT, CHANNEL, INTERCOMPANY, SEGMENT8, SEGMENT9, SEGMENT10, SEGMENT11, 
          SEGMENT12, ACCT_CURNCY, EXCHANGE_RATE, EXCHANGE_RATE_TYPE, JOURNAL_SOURCE, JOURNAL_TYPE, DEBIT, CREDIT, MESSAGE, STATUS, errorCode, 
           CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, PROCESS_ID, LEDGER_NAME 
              from FIN_ORACLE_STAGING
        where ACCT_DATE =vAcctDate;
             commit;
             */
             
        update  CUSTOM.FIN_ORACLE_STAGING
              set status='P', message='PROCESSED';
  else 
        update  FIN_ORACLE_STAGING 
        set     status='Error',message='DR AND CR IMBALANCE', error_code=a_amount;
END IF;
------
if diff_amount!=0 then
           update  FIN_ORACLE_STAGING 
           set     status='Error',message='DR AND CR IMBALANCE', error_code=diff_amount;
 ELSE 
           update  CUSTOM.FIN_ORACLE_STAGING
           set status='P', message='PROCESSED';
    END IF;

  commit;
END INSERT_INTO_STAGING;

---
/
