#!/bin/bash

# Export the Jasypt secret key as an environment variable
export CD_SPRING_DATASOURCE_URL="#{CD-SPRING-DATASOURCE-URL}#"
export CD_SPRING_DATASOURCE_USERNAME="#{CD-SPRING-DATASOURCE-USERNAME}#"
export CD_SPRING_DATASOURCE_PASSWORD="#{CD-SPRING-DATASOURCE-PASSWORD}#"

export JASYPT_ENCRYPTOR_PASSWORD="#{JASYPT-ENCRYPTOR-PASSWORD}#"

export CD_MONEYGRAM_PARAMS_AGENTSEQUENCE="11"
export CD_MONEYGRAM_PARAMS_AGENTSEQUENCE_REVERSAL="1"
export CD_MONEYGRAM_PARAMS_TOKEN="TEST"
export CD_MONEYGRAM_PARAMS_AGENTID="43293913"
export CD_MONEYGRAM_PARAMS_API_VERSION="11"
export CD_MONEYGRAM_PARAMS_API_VERSION_GFFP="1512"
export CD_MONEYGRAM_PARAMS_CLIENT_SOFTWARE_VERSION="1"
export CD_MONEYGRAM_PARAMS_CLIENT_SOFTWARE_VERSION=_FEE_LOOKUP"1.1"

# Print a confirmation message
echo "Environment variables have been set."