<%--
//Generated by Customization WB Generator
//Do not edit this file directly.
//Instead, modify the properties in the tool and regenerate.
--%>

<%@ page import="applcommon.ParseValue" %>
<%@ page import="com.infy.bbu.jsputil.*"%>
<%@ page import="java.util.Vector"%>

<%@ page import="FABCommon.SecurityInfo70"%>

<%@ taglib uri="taglib.tld" prefix="arjsp" %>
<arjsp:init groupName="Customize" isEntryPoint="false" />

<%
	String sProfileId = ProfilesManager.getProfileInSession(session);
	String sSubGrpName = (String)ARJspCurr.getInput("subGroupName","");
	String sGrpName = ARJspCurr.getCurrentGroup();
	String pageName = (String)ARJspCurr.getInput("jspName","");
	String sPopUpExceptionWindow = (String)ARJspCurr.getInput(sGrpName+".PopUpExceptionWindow" ,"false");
	String sReferralMode = (String)ARJspCurr.getInput("refSubMode" ,"");

SecurityInfo70 securityInfo = (SecurityInfo70)session.getAttribute("FinUserInfo");

	ARJspCurr.setInput(sGrpName+".PopUpExceptionWindow","false");

%>
<script>

	var BODDate= '<%= ParseValue.checkString((securityInfo.bodDate).substring(0,10))%>';

	var sPopUpExceptionWindow = '<%=ParseValue.checkString(sPopUpExceptionWindow)%>';
	var sReferralMode = '<%=ParseValue.checkString(sReferralMode)%>';
	var subGroupName = '<%=ParseValue.checkString(ARJspCurr.getInput("subGroupName",""))%>';
	var pymntType = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".pymntType",""))%>';
	var freeTxt1 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".freeTxt1",""))%>';
	var freeTxt2 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".freeTxt2",""))%>';
	var freeTxt3 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".freeTxt3",""))%>';
	var freeTxt4 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".freeTxt4",""))%>';
	var freeTxt5 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".freeTxt5",""))%>';
	var freeCode1 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".freeCode1",""))%>';
	var freeCode2 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".freeCode2",""))%>';
	var freeCode3 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".freeCode3",""))%>';
	var freeCode4 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".freeCode4",""))%>';
	var freeCode5 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".freeCode5",""))%>';
	var funcCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".funcCode",""))%>';

var Ecstranrefnum  = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".Ecstranrefnum",""))%>';
var paysysid  = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".paysysid",""))%>';
var solid  = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".solid",""))%>';
var trantype  = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".trantype",""))%>';

var addline1 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".addline1",""))%>';
var addline2 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".addline2",""))%>';
var addline3 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".addline3",""))%>';
var addline4 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".addline4",""))%>';
var custname = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".custname",""))%>';
var custdestaccIban = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".custdestaccIban",""))%>';
var custaccIban = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".custaccIban",""))%>';
var chrgibanacc = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".chrgibanacc",""))%>';

var trearefcode  = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".trearefcode",""))%>';

var receiveraccname = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".receiveraccname",""))%>';
var receiveracc = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".receiveracc",""))%>';
var bankcode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".bankcode",""))%>';
var branchcode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".branchcode",""))%>';
var citycode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".citycode",""))%>';
var tranrmks = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".tranrmks",""))%>';
var suspacc = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".suspacc",""))%>';
var chrgacc = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".chrgacc",""))%>';
var chrgeventid = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".chrgeventid",""))%>';
var tranccy = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".tranccy",""))%>';

var remitamt= '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".remitamt",""))%>';

var treaRefNum = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".treaRefNum",""))%>';
var treaRate = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".treaRate",""))%>';
var ecsref = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".ecsref",""))%>';
var pymntType = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".pymntType",""))%>';
var settldate = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".settldate",""))%>';
var ecstrancode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".ecstrancode",""))%>';
var ecsmebid = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".ecsmebid",""))%>';
var custacc = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".custacc",""))%>';



</script>

<script language="javascript" src="../Renderer/javascripts/lists/showAccountIdList.js"></script>
<script language="javascript" src="../Renderer/custom/javascripts/cd_atf_functions.js"></script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showBICCodes.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("getEvtIdList.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showEcsTranRefno.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showRefCode.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showSolId.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showCurrency.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showEcsTranRefno.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showRefCode.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showSolId.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("listBankCodes.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showAccountIdList.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showBranchCodes.js",sProfileId)%>" > </script>

<script language="javascript" src="../Renderer/custom/javascripts/custom_functions.js"></script>
<script language="javascript" src="../Renderer/custom/javascripts/custom_common_functions.js"></script>
<script language="javascript" src="../Renderer/custom/javascripts/cust_fetch_list.js"></script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("cust_pre_evt.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("cust_evt.js",sProfileId)%>" > </script>


<script language="JavaScript">
</script>

<script language="JavaScript">
	printBlock();
	printFooterBlock();
</script>

