//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT031309:"AutoTOD Contract Maintenance",FAT000703:"Function",FLT031310:"Account Number",FLT024006:"Contract ID",FAT005177:"--Select--",FDEMO0005:"A-Add",FDEMO0006:"M-Modify",FLT031311:"X-Cancel",FLT031312:"T-Terminate",FDEMO0002:"V-Verify",FLT031313:"I-Inquire",FLT031314:"E-Enhance Extend",FLT031315:"Z-ModifyEnhancement"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY 
var jspErr={};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);
