// GENERATED BY TABGEN. DO NOT MODIFY.
var applangcode="INFENG";
var jstabRes={FTT000123:"General",FHK000007:"G",FTT000346:"Link Collaterals",FHK000011:"K",FTT000027:"A/C Interest",FHK000003:"C",FTT000154:"Loan Details",FHK000019:"S",FTT000144:"LA Interest",FHK000001:"A",FTT000193:"Payment Schedule",FHK000025:"Y",FTT000210:"Refinance And Subsidy",FHK000021:"U",FTT000215:"Related Party",FHK000016:"P",FTT000170:"Multi Source Instruction",FHK000014:"N",FTT000168:"MIS Codes",FHK000013:"M",FTT000099:"Error Details",FHK000018:"R",FTT000230:"Savings Home",FHK000008:"H",FTT000091:"Document",FHK000004:"D",FTT000142:"Internal Notes",FHK000020:"T",FTT000116:"Fees",FHK000006:"F",FTT000208:"Rebates & Clawback",FHK000023:"W",FTT000088:"Disbursement Schedule",FHK000002:"B",FTT000181:"Others",FHK000015:"O",FTT000013:"Addl. Info.",FHK000009:"I",FTT000042:"Builder Details",FHK000005:"E",FTT000295:"Contract Details",FHK000010:"J",	FLT028908:"Rescheduling Details",FLT028918:"L", FLT028909:"OverDue Details",FLT028919:"O"};

var jstabResALT = {
};

var arrtabJspArr = new Array (jstabRes, jstabResALT);
var jstabResArr = new litMap(arrtabJspArr);
