// GENERATED BY JSGEN. DO NOT MODIFY.
var applangcode="INFENG";
var jspRes={FLT000160:"Related Party Details",FLT000450:"Name",FLT000162:"Relation Code",FLT000163:"Designation Code",FLT014293:"Address Line 1",FLT014294:"Address Line 2",FLT014295:"Address Line 3",FLT000089:"City",FLT000090:"State",FLT000092:"Country",FLT000091:"Postal Code",FLT000496:"Phone No. 1",FLT000497:"Phone No. 2",FLT000166:"Fax No.",FLT000167:"Email ID",FLT004652:"Tax ID No.",FLT000536:"Del.",FLT000144:"Free Text",FLT000145:"CIF ID",FLT000146:"Free Text 2",FLT000147:"Free Text 3",FLT000148:"Free Text 4",FLT000193:"Submit",FLT000192:"Cancel",FLT001166:"OK",FLT000194:"Validate",FLT001439:"Clear"};

var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);
