//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT004977:"Go",FLT003425:"Transaction Inquiry",FLT031293:"A/c.ID",FLT023162:"CCY/SOL ID",FLT031294:"A/c.Name",FLT028540:"General Ledger Subhead Code",FLT023367:"Balance",FLT021458:"Opening Balance",FLT021455:"Closing Balance",FLT019672:"Float Balance",FLT011531:"Funds in Clearing",FLT009564:"Available Amt.",FLT023060:"Effective Available Amt.",FLT025099:"Customer Status",FLT019062:"A/c. Opening Date",FLT014475:"A/c. Status",FLT014298:"A/c. Status Date",FLT005157:"Purge Date",FLT006227:"Address",FLT006216:"City",FLT006217:"State",FLT006459:"Country",FLT018571:"Postal Code",FLT024765:"Phone Type",FLT000165:"Telex No.",FLT008279:"Phone No.",FLT024764:"Email ID Type",FLT008417:"Email ID",FLT030726:"Ok",FLT026526:"OK"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY 
var jspErr={};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);
