//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT004977:"Go",FLT003425:"Transaction Inquiry",FLT028446:"A/c. ID",FLT007733:"From Date",FLT007734:"To Date",FLT017515:"From Amt.",FLT017516:"To Amt.",FLT025010:"From Instrument No.",FLT025011:"To Instrument No.",FLT014303:"Order By",FLT014287:"Last 'n' Transactions",FLT004977:"Go",FLT001439:"Clear"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY 
var jspErr={};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);
