//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT004977:"Go",FLT033359:"Custom Account Mapping Inquiry Menu",FLT033395:"CIF Id :",FLT033452:"RIB No.  :",FLT033448:"Account Number :",FLT033396:"Account Name :",FLT033453:"Sol Id  :",FLT033454:"Account Currency :",FLT000193:"Submit",FLT000194:"Validate",FLT001721:"Cancel",FLT026526:"OK"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY 
var jspErr={};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);
