//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT004977:"Go",FLT031877:"ALCO Rate Maintenance",FLT006657:"Function",FLT031874:"Currency Code",FLT031859:"Effective Date",FLT031878:"ALCO Deposit Range & Rate Details",FLT000193:"Submit",FLT000194:"Validate",FLT001721:"Cancel",FLT026526:"OK",FLT014902:"Range1",FLT131874:"Rate1",FLT014912:"Range2",FLT131875:"Rate2",FLT014913:"Range3",FLT131876:"Rate3",FLT014914:"Range4",FLT131877:"Rate4",FLT014915:"Range5",FLT131878:"Rate5",FLT014916:"Range6",FLT131879:"Rate6"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY 
var jspErr={};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);
