//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT004977:"Go",FLT031877:"Alerts ",FLT006657:"Function",FLT031874:"CIF ID",FLT031859:"Account Number",FLT004977:"Go",FLT001439:"Clear",FLT031311:"--Select--",FLT012900:"R - Register",FLT012350:"M - Modify",FLT013170:"V - Verify",FLT033219:"X - Cancel",FLT034011:"I - Inquire"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY 
var jspErr={};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);
