//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes = {
  FLT006657: "Function",
  FLT031874: "Employee ID",
  FLT021699: "Upload File Name",
  FLT004977: "Go",
  FLT001439: "Clear",
  FLT031311: "--Select--",
  FLT012906: "LI - Inquire Lien Marked ",
  FLT012900: "UL - Upload Lien Lift ",
  FLT012924: "VL - Verify Lien Lift ",
  FLT012901: "LR - Lien Lift Report ",
  FLT012907: "OA - Loan Operative Accounts ",
  FLT012902: "UD - Upload Dormant Acctivation ",
  FLT012903: "DR - Dormant Acctivation Report ",
  FLT012904: "UC - Upload Acct Closure ",
  FLT012908: "US - Upload Scheme Change ",
  FLT012909: "SR - Acct Scheme Chg Report ",
  FLT012910: "UA - Upload Acct Mgr Change ",
  FLT012911: "AR - Acct Mgr Chg Report ",
  FLT012905: "CR - Acct Closure Report ",
  FLT012913: "UB - Upload Reverse Balance Chgoff ",
  FLT012914: "BR - Reverse Balance Chgoff Report ",
  FLT012915: "VA - Virtual Account Upload ",
  FLT012917: "VV - Virtual Account Verification ",
  FLT012916: "VR - Virtual Account Opening Report ",
  FLT012918: "B2C - B2C Recon ",
  FLT012919: "LO - Bulk Loan Account Opening Upload ",
  FLT012920: "LV - Bulk Loan Account Opening Verification ",
  FLT012921: "LD - Bulk Loan Account Disbursement ",
  FLT012922: "SC - Upload Bulk CIF Suspension ",
  FLT012923: "VC - Verify Bulk CIF Suspension ",
  FLT012928: "UF - Upload Unfreeze Bulk Account ",
  FLT012925: "FR - Unfreeze Bulk Account report ",
  FLT012926: "DD - Upload Deactivate Bulk Account ",
  FLT012927: "RD - Deactivate Bulk Account report "

};
var jspResALT = {};

var arrJspArr = new Array(jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY
var jspErr = {};
var jspErrALT = {};

var arrJspErr = new Array(jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);
