//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT026332:"Function Code ",FLT026333:"Sol ID ",FLT026334:"Test?(Y/N)",FLT026335:"Remarks",FLT026341:"Select",FLT026342:"P-Process"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);
