//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT004977:"Go",FLT031877:"Finacle Blacklist/Watchlist Framework",FLT006657:"Function",FLT131874:"ID.Type",FLT131859:"Unique Identification Number",FLT031878:"Customer Deatils",FLT031874:"Customer Id",FLT147999:"Customer Name",FLT031879:"Customer Branch",FLT003837:"Customer Constitution",FLT131879:"Date of Birth",FLT103837:"Country of Origin",FLT031942:"Blacklist And Watchlist Details",FLT031945:"BlackList/WatchList Reason",FLT031946:"Evidence",FLT531946:"WC - World Check",FLT551946:"GP - Government Policy",FLT651946:"CO - Court Order",FLT651846:"BI - Bank Investigation",FLT651849:"OS - Other Sources",FLT000193:"Submit",FLT000194:"Validate",FLT001721:"Cancel",FLT031311:"--Select--",FLT012405:"FR - FRAUD",FLT013286:"TE - TAX EVASION",FLT013287:"CO - CORRUPTION",FLT013288:"ML - MONEY LOUNDERING",FLT013289:"TR - TERRORIST",FLT013290:"TF - TERRORISM FINANCING",FLT013291:"GG - GAMING AND GAMBLING",FLT013292:"PR - PROLIFERATION",FLT013293:"OC - ORGANIZED CRIME",FLT613293:"VC - Virtual Currency",FLT713293:"OP - Other Prohibited Business",FLT713243:"UL - UNLICENSED MONEY CHANGER",FLT793243:"PS - PYRAMID SCHEMES DEALINGS",FLT013294:"Sanction Type",FLT013295:"B - BlackList",FLT013296:"W - WatchList",FLT013297:"Remarks",FLT013298:"--Select--",FLT026526:"OK"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY 
var jspErr={};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);
