//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT004977:"Go",FLT033494:"Custom Commission Payment",FLT033107:"Function:",FLT033495:"Type of Payment:",FLT033493:"Commission Code:",FLT033526:"Commission CCY/Amt:",FLT033527:"Rate Code:",FLT033528:"VAT Deductable CCY/Amt:",FLT033544:"Debit Account Id:",FLT033545:"Commission Account Id:",FLT026527:"TAX Account Id:",FLT033546:"Payment Purpose:",FLT000193:"Submit",FLT000194:"Validate",FLT001721:"Cancel",FLT026526:"OK",FLT026528:"Tranx Id: ",FLT026529:"Transaction Date: ",FLT033518:"Transaction ID: ",FLT033519:"Transaction Date: ",FLT033520:"Reversal Transaction Details"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY 
var jspErr={};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);
