//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT004977:"Go",FLT032043:"Cheque Book Charges Maintainance",FLT006657:"Function",FLT004977:"Go",FLT001439:"Clear",FLT031874:"A-ADD",FLT031882:"M-MODIFY",FLT031876:"V-VERIFY",FLT031877:"I-INQUIRE",FLT031883:"X-CANCEL",FLT032031:"D-DELETE",FLT032045:"ChequeBook",FLT003336:"Commission"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY 
var jspErr={};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);

