//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT000002:"Currency Code",FLT000003:"Function",FLT000004:"Select ",FLT000005:"Add ",FLT000006:"Modify ",FLT000007:"Inquire ",FLT000008:"Delete "};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);
