//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT026332:"Function",FLT026333:"Currency Code",FLT026334:"Rate Code",FLT026335:"PnL Account",FLT026336:"Home Cy Account",FLT026337:"Foreign Cy Account",FLT026338:"--Select--",FLT026339:"ADD",FLT026340:"MODIFY",FLT026341:"INQUIRE",FLT026342:"DELETE"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);
