//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT026332:"START DATE ",FLT026333:"END DATE", FLT026334:"DUPLICATE",FLT026335:"DOWNLOAD ID"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);
