//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT11000228:"Account Number",FLT11000028:"No Of chqbooks",FLT11000039:"Leaves(25/50/100)",FLT019668:"ChqStart SerialNo",FLT11000029:"ChqEnd SerialNo",FLT11000129:"Request Status",FLT11000130:"Instr Type"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);
