//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT026332:"Function",FLT026333:"Account Number ",FLT026334:"Instr Type",FLT026335:"Begin ChqNO",FLT026336:"No Of Leaves",FLT000005:"SELECT",FLT000006:"D-DESTORY",FLT000009:"S-STOP",FLT000010:"I-INQUIRE",FLT000011:"V-Verify",FLT000012:"X-CANCEL"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);
