//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT026332:"Sol ID ",FLT026333:"Account Number ",FLT026334:"Status",FLT000005:"SELECT",FLT000006:"E-Request",FLT000007:"A-Authorised",FLT000008:"D-Deleted",FLT000009:"S-Processed"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);
