//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT026332:"Function",FLT000032:"SOL ID",FLT000001:"Account Number ",FLT000002:"Instrument Number",FLT000004:"Instrument Amount",FLT000003:"Rejection Code",FLT000006:"Zone Code",FLT000005:"Zone Date",FLT000008:"Drawee Bank Code",FLT000007:"Value Date",FLT000009:"Drawee Branch Code",FLT000010:"Drawee Sort Code",FLT000011:"Pres Bank Code",FLT000012:"Pres Branch Code",FLT000013:"Issue Bank code",FLT000014:"Issue Branch code",FLT000015:"Tran Remarks",FLT000038:"Pres Sort code"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

