//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT021242:"Function",FLT021243:"Zone Date",FLT021244:"Zone Code", FLT021245:"Set No.",FLT021247:"--Select--",FLT021248:"A - Add",FLT021249:"D - Delete",FLT021250:"G - Regularize",FLT021251:"I - Inquiry",FLT021252:"M - Modify",FLT021253:"R - Release",FLT021254:"V - Verify",FLT021255:"O - Outward Reject",FLT007661:"Bill Payment",FLT007530:"Biller ID",FLT031859:"Type of Service"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY 
var jspErr={};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);
