//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT000700:"Function",FLT000701:"Transaction Type",FLT000702:"Credit Account ID",FLT000703:"Ref. CCY/Amt.",FLT000704:"Rate Code/Rate",FLT000711:"Instrument Type",FLT000712:"Instrument Alpha/Srl. No.",FLT000713:"Remarks 1",FLT000714:"Remarks 2",FLT000709:"Transaction Particulars Code",FLT000710:"Transaction Particulars",FLT000705:"Amt. in A/c. CCY",FLT000706:"Charge Amount",FLT000707:"Ref. No.",FLT000708:"Nostro Account ID",FLT000715:"Debit Account ID",FLT000716:"Get Signature",FLT000717:"Instrument Date",FLT000718:"Debit A/c. Entity ID",FLT000719:"Credit A/c. Entity ID",FLT000720:"NI - Numeric Integer",FLT000721:"NF - Numeric Float",FLT000722:"CH - Char",FLT000723:"AN - Alpha Numeric",FLT000724:"AC - Account",FLT000725:"PL - Place Holder",FLT000726:"GL - GL Sub Head Code",FLT000727:"CF - CIF Id",FLT000728:"SC - Scheme Code"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY 
var jspErr={};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);
