//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT004977:"Go",FLT648092:"Legacy Loan Interest Adjustment",FLT648093:"Loan Account Id",FLT648094:"Interest Calculated Till",FLT030604:"Currency",FLT648095:"Interest  in Finacle",FLT648096:"Interest in Legacy",FLT648097:"Already Adjusted Interest",FLT648098:"Current Interest Adjustment",FLT648099:"Operative Account",FLT648100:"Conversion Rate Code",FLT003129:"Create Transaction",FLT001721:"Cancel",FLT026526:"OK"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY 
var jspErr={};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);
