//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT004977:"Go",FLT032011:"LOAN CHARGE FIELD MAINTANANCE",FLT006657:"Function",FLT007206:"Type",FLT012932:"Scheme Code",FLT015774:"Customer ID",FLT000193:"Submit",FLT000194:"Validate",FLT001721:"Cancel",FLT026526:"OK"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY 
var jspErr={};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);
