//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT004977:"Go",FLT031701:"MERCHANTS MAITENANCE SCREEN",FLT006657:"Function",FLT004977:"Go",FLT001439:"Clear",FLT031340:"- Select -",FLT034011:"I - Inquire",FLT014584:"A - Add",FLT012350:"M - Modify",FLT013170:"V - Verify",FLT034012:"D - Delete"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY 
var jspErr={};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);
