//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT000003:"CIF ID",FLT000004:"Function",FLT000005:"Select ",FLT000006:"Add ",FLT000007:"Modify ",FLT000008:"Inquire ",FLT000009: "Delete"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);
