//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT004977:"Go",FLT031812:"Loan Order Capture Screen",FLT020166:"Function Code",FLT034257:"Loan Account",FLT031813:"Loan Account Name",FLT031814:"Cust ID",FLT031815:"Loan Acid",FLT012932:"Scheme Code",FLT031816:"MIS Code",FLT031817:"Loan Date",FLT031818:"Operative Account",FLT031819:"Loan Amount",FLT002671:"Status",FLT022552:"Order No.",FLT031820:"Own Contrib Amount",FLT031821:"Contribution Account",FLT031822:"Recover Charges From?",FLT004977:"Go",FLT001439:"Clear",FLT031340:"- Select -",FLT014584:"A - Add",FLT012350:"M - Modify",FLT013170:"V - Verify",FLT010527:"New",FLT024001:"Verified",FLT009834:"Pending"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY 
var jspErr={};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);
