//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT004977:"Go",FLT031826:"Loan Order Capture  Details Screen",FLT020166:"Function Code",FLT034257:"Loan Account",FLT031813:"Loan Account Name",FLT031814:"Cust ID",FLT031815:"Loan Acid",FLT012932:"Scheme Code",FLT031816:"MIS Code",FLT031817:"Loan Date",FLT031818:"Operative Account",FLT031819:"Loan Amount",FLT002671:"Status",FLT022552:"Order No.",FLT031820:"Own Contrib Amount",FLT031821:"Contribution Account",FLT031822:"Recover Charges From?",FLT031827:"Ref Code",FLT031828:"Item Code",FLT031829:"Item Description",FLT016300:"Unit Price",FLT031831:"Delete Flag",FLT034118:"Total Amount",FLT000193:"Submit",FLT000194:"Validate",FLT001721:"Cancel",FLT026526:"OK"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY 
var jspErr={};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);
