//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT004977:"Go",FLT032015:"Custom Mapping of Rate Codes",FLT006657:"Function",FLT004977:"Go",FLT001439:"Clear",FLT032016:"---Select---",FLT031874:"A - ADD",FLT031882:"M - MODIFY",FLT031876:"V - VERIFY",FLT031877:"I - INQUIRE",FLT031883:"X - CANCEL",FLT032031:"D - DELETE"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY 
var jspErr={};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);
