//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT026332:"Function",FLT026333:"SET ID",FLT026334:"ZONE DATE",FLT026335:"ACCOUNT NO",FLT026336:"--SELECT--"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);
