//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT006657:"Function",
			FLT031874:"Debit Account",
			FLT031875:"Credit Account",
			FLT031859:"Effective Date",
			FLT004977:"Go",
			FLT001439:"Clear",
			FLT031311:"--Select--",
			//FLT012900:"R - Revert to Original limit",
			FLT012350:"A - Add transaction limit for Trxn",
			FLT013170:"V - Verify",
			FLT033219:"X - Cancel",
			FLT034011:"I - Inquire"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY 
var jspErr={};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);
