//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT000003:"Customer ID",FLT000004:"Function",FLT000005:"Select",FLT000006:"Add ",FLT000007:"Delete "};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);
