//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT026332:"Function Code ",FLT026333:"Account Number",FLT026341:"G-Generate Schedule Report",FLT026342:"R-Loan Rescheduling",FLT031859:"Rescheduling Date",FLT026343:"D-Delete Demands",FLT026344:"N-Create New Demands" };
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

