//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT026331:"File Name ",FLT004977:"Go",FLT031869:"Corporate SIG",FLT031872:"CORPSIG menu for SVS",FLT000193:"Submit",FLT001721:"Cancel"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY 
var jspErr={};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);
