//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT026331:"File Name ",FLT026332:"Function Code ",FLT046347:"R-Generate Reconciled Report",FLT026341:"-- Select--",FLT026347:"U-Upload ",FLT026335:"Y-Yes",FLT026336:"N-No",FLT031945:"Upload Module",FLT012405:"FIN-Finacle File",FLT013286:"MFS-MFS File",FLT713286:"SAF-Safaricom File",FLT713283:"AML43-World Check Data",FLT713293:"BL43-BlackList Data",FLT783293:"MCGL-Master Card GL",FLT787293:"MCDD-Master Card Direct Debit",FLT717293:"MCFA-Master Card Acknowledge File",FLT031875:"Tran.Remarks",FLT719293:"OFAC-SDN- SDN List",FLT715293:"OFAC-ADD- Address List",FLT714293:"OFAC-ALT- Alternate Details",FLT716293:"RM-UPLOAD - CIF RM Batch Update"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

