//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT021242:"Function",FLT021243:"Parameter Level",FLT021244:"Module Name", FLT021245:"Parameter Id",FLT021246:"Sol Id",FLT021247:"--Select--",FLT021248:"A - Add New Parameter",FLT021249:"M - Modify Parameter",FLT021250:"C - Cancel Parameter",FLT021251:"V - Verify Parameter",FLT021252:"MV - Modify Parameter Value",FLT021253:"VV - Verify Parameter Value",FLT021254:"I - Inquire Parameter Value",FLT021255:"CV - Cancel Parameter Value",FLT021256:"DV - Delete Parameter Value",FLT021257:"VDV - Verify Deleted Parameter Value",FLT021258:"BNKL - Bank Level",FLT021259:"SOLL - Sol Level",FLT021260:"SCHM - Scheme Code Level",FLT021261:"CURL - Currency Level",FLT021262:"SHCR - Scheme Code Currency Level",FLT021263:"GENL - Generic Level",FLT021264:"Scheme Code",FLT021265:"Currency Code",FLT021266:"Generic Level Code",FLT021267:"Generic Level Id",FLT021268:"Sol Id"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY 
var jspErr={};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);
