//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY
var jspRes={
FLT200000:"Preferential Charges Maintenance",
FLT200001:"Function",
FLT000003:"A - Add",
FLT000004:"M - Modify",
FLT000005:"V - Verify",
FLT000006:"X - Cancel",
FLT000007:"I - Inquire",
FLT000011:"Preferential level",
FLT000013:"A - Account Level",
FLT000014:"C - CIF Level",
FLT000015:"AG - Agreement Level",
FLT000016:"S - Segmentation Level",
FLT000017:"Customer Type",
FLT100017:"Segmentation Class",
FLT000008:"Account ID",
FLT000009:"Customer ID",
FLT000010:"Agreement Code",
FLT200117:"Event Type",
FLT200118:"Event ID",
FLT200119:"Start Date",
FLT200120:"End Date",
FLT200121:"Percent/Amount",
FLT200123:"-Select-",
FLT200124:"P - Percent",
FLT200125:"A - Amount",
FLT200126:"Value",
FLT200122:"Value",
FLT200128:"Min Charge Amt-LCY",
FLT200129:"Max Charge Amt-LCY",

FLT000018:"Customer Type",
FLT000019:"--Select--",
FLT000020:"R - Retail",
FLT000021:"C - Corporate",
FLT000193:"Submit",
FLT001721:"Cancel",
FLT004977:"Go",
FLT026526:"OK"
};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY 
var jspErr={};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);
