//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT004977:"Go",FLT648046:"Penalty Charge Maintenance",FLT006657:"Function",FLT030172:"Account ID",FLT004977:"Go",FLT001439:"Clear",FLT648047:"--Select--",FLT648032:"I-Inquire",FLT648048:"W-Waiving"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY 
var jspErr={};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);
