//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT004977:"Go",FLT032047:"Maintainace Of Preferential Interest",FLT006657:"Function",FLT031943:"Role Id",FLT032090:"Preferential Interest(%)",FLT000193:"Submit",FLT000194:"Validate",FLT001721:"Cancel",FLT026526:"OK"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY 
var jspErr={};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);
