//GENERATED BY CMM Framework.DO NOT MODIFY

var jspRes={
    FSC909815:"Customer Profile Manual Release",
    FLT026526:"OK",
    FLT004705:"View / Print Report"
};

var jspResALT={};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

var jspErr={};
var jspErrALT = {};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);
