//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT026332:"Function",FLT026344:"--SELECT--",FLT026333:"Upload Ref",FLT026334:"Upload File",FLT026339:"Upload File",FLT026342:"Upload File",FLT026346:"Modify Account Manager",FLT026343:"Verify Relationship Manager"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);
