//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT026332:"Function",FLT026344:"--SELECT--",FLT026333:"Employer ID",FLT026334:"File Name",FLT026335:"Name Mismatch",FLT026336:"Dr.A/c.ID",FLT026337:"Upload Type",FLT026338:"Place Lien",FLT026339:"Test Mode",FLT026340:"Rename File",FLT026341:"Charge Code",FLT026342:"Process",FLT026343:"Upload"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);
