//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT022001:"Report To",FLT022002:"Tran Sub Type",FLT022003:"Upload File Name",FLT022004:"Test? (Y/N)",FLT022005:"Tran Remarks",FLT022006:"Rename Input File",FLT022007:"S-Statement P-Postage "};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);
