//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT0320451:"ID Number",FLT004977:"Go",FLT031839:"Share Purchase Page",FLT006657:"Function",FLT031347:"Tran Type",FLT032045:"CDSC Number",FLT031841:"Order Number",FLT031846:"Account Number",FLT004977:"Go",FLT001439:"Clear",FLT031507:"--Select--",FLT031836:"A--Add",FLT03183661:"H--Hold",FLT031837:"I--Inquire",FLT031838:"V--Verify",FLT031844:"--Transfer--",FLT031845:"--Cash--",FLT03184611:"Transaction Id"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY 
var jspErr={};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);
