//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT004977:"Go",FLT031590:"Manual TOD Availment",FLT112254:"Function",FLT112259:"Account Id",FLT031592:"Availment Request ID",FLT004977:"Go",FLT001439:"Clear",FLT700022:"--Select--",FLT031595:"A - Add",FLT034011:"I - Inquire",FLT031596:"M - Modify",FLT031297:"V - Verify",FLT033219:"X - Cancel"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY
var jspErr={FAT000924:"Enter a value in the field."};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);
