//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT006657:"Function",
			FLT031874:"Employee ID",
			FLT021699:"Upload File Name",
			FLT004977:"Go",
			FLT001439:"Clear",
			FLT031311:"--Select--",
			FLT031312:"Batch ID",
			FLT012901:"I - Inquire ",
			FLT012902:"V - Verify ",
			FLT012900:"U - Upload "};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY 
var jspErr={};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);
