//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT004977:"Go",FLT648026:"Cheque Certification Status",FLT006657:"Function",FLT648034:"Account Number",FLT648035:"Cheque Number",FLT002671:"Status",FLT648036:"Cheque Amount",FLT648037:"Paid Amount",FLT000193:"Submit",FLT000194:"Validate",FLT001721:"Cancel",FLT648038:"Y-Certified Cheque",FLT648039:"Z-Certified Cheque released",FLT648040:"P-Paid",FLT026526:"OK"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY 
var jspErr={};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);
