//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT026333:"Select ",FLT026334:"R-Reject ",FLT026335:"X-Cancle ",FLT026337:"Originator Code",FLT026338:"File Name",FLT026339:"Cr.A/c ID",FLT026340:"Test Mode(Y/N)",FLT026341:"Charge Code"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);





