//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT000003:"Account Number",FLT000004:"Function",FLT000005:"--SELECT-- ",FLT000009: "M - Modify",FLT000010:"I - Inquire",FLT000011: "Inst Type",FLT000012: "Inst Number"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);
