//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT004977:"Go",FLT648023:"Equity Bank Report Maintenance",FLT648024:"Report Module",FLT648107:"Report Division",FLT004630:"Report Name",FLT004977:"Go",FLT001439:"Clear",FLT648027:"S - SELECT",FLT648108:"L - Liabilities ",FLT548108:"T - Tax"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY 
var jspErr={};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);
