//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT004977:"Go",FLT648024:"Report Module",FLT648107:"Report Division",FLT004630:"Report Code",FLT648112:"Report Title",FLT648037:"As On Date",FLT721001:"Foracid",FLT648038:"Sol Id / Set Id",FLT000193:"Submit",FLT000194:"Validate",FLT001721:"Cancel",FLT026526:"OK"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY 
var jspErr={};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);
