//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY



var jspRes={FTT000072:"Currency",FLT031297:"System Calculated Amount",FLT031309:"User Enterd Amount",FLT031310:"Charge Particular"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY 
var jspErr={};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);
