//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT026332:"Function",FLT026333:"Account Number",FLT026334:"CIF ID",FLT026335:"Y-Yes",FLT026336:"N-No",FLT026341:"--Select--",FLT026342:"A-Add",FLT026343:"I-Inquiry",FLT026344:"D-Delete"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

