//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT004977:"Go",FLT031836:"Charge Account Maintenance",FLT027516:"Function Code",FLT007514:"Level",FLT031945:"A/C No",FLT031946:"Cid Id",FLT031947:"Agreement",
			FLT031838:"Charge Ac/No",
			FLT031861:"Start Date",
			FLT031862:"End Date",
			FLT200117:"Event Type",
			FLT200118:"Event Id",
			FLT000193:"Submit",
			FLT001721:"Cancel",
			FLT026526:"Back"
			};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY 
var jspErr={};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);
