//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

//var jspRes={FLT004977:"Go",FLT031836:"Bill Payments Menu",FLT004977:"Go",FLT001439:"Clear"};
var jspRes={FLT004977:"Ok",FLT031836:"Charge Account Maintenance",FLT001439:"Print Receipt"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY 
var jspErr={};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);
