//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY
var jspRes={FLT000885:"Go",FLT000572:"Customer Interest Report",FLT111600:"Type",FLT111601:"Criteria 1",FLT111602:"Criteria 2",FLT111603:"Account Placeholder",FLT111604:"Set ID",FLT111605:"Currency",FLT111606:"Start Tran Date",FLT111607:"End Tran Date",FLT111608:"GL Account No.",FLT111609:"Tran ID",FLT111610:"Tran Date",FLT111611:"To Set ID",FLT000193:"Submit",FLT000194:"Validate",FLT000192:"Clear",FLT001166:"OK"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY 
var jspErr={};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);
