//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT11000033:"Account Number",FLT11000034:"Loan OutStanding",FLT11000035:"No. of Instalments",FLT11000036:"Int. Rate",FLT11000037:"Instalment Amount",FLT11000038:"Prepayment Amount",FLT11000039:"Prepayment Amount",FLT11000040:"EI Payment Frequency",FLT11000041:"Compounding Frequency",FLT11000042:"EI Formula Flg",FLT11000043:"Capitalise Int. ?",FLT11000044:"Carry Overdue demands?",FLT11000045:"Int. Base Method",FLT11000046:"No. of Days in a Year",FLT11000047:"Leap Year Adjustment"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);
