	//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT004977:"Go",FLT031840:"Outward Clearing Detail page",FLT112254:"Function",FLT000637:"Zone Date",FLT007523:"Zone Code",FLT009829:"Zone CCY Code",FLT007530:"Biller ID",FLT031859:"Type of Service",FLT031841:"Outbound call",FLT003971:"A/c. Details",FLT031831:"Cr. A/C Number",FLT031847:"Cr. Amount",FLT031848:"A/C Free Text-1",FLT031849:"A/C Free Text-2",FLT031847:"Cr. Amount",FLT031848:"A/C Free Text-1",FLT031849:"A/C Free Text-2",FLT000916:"Instrument Details",FLT031850:"Instrument Amount",FLT021766:"Instrument No.",FLT031858:"Image",FLT007745:"Instrument Date",FLT031851:"Paying Account No.",FLT007794:"Bank Code",FLT031027:"Transaction Code",FLT031835:"Batch Num",FLT031836:"Tran Id",FLT031857:"Paying A/c. Name",FLT009907:"Branch Code",FLT000193:"Submit",FLT021284:"Validate",FLT027575:"Cancel",FLT026526:"OK"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY 
var jspErr={};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);
