//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY
var jspRes={
FLT004977:"Go",
FLT648012:"Package Maintenance Menu",
FLT648230:"Function",
FLT648014:"A-Add",
FLT648181:"V-Verify",
FLT648017:"M-Modify",
FLT648183:"I-Inqiure",
FLT648182:"X-Cancel",
FLT648007:"Package Code",
FLT000600:"Package Desc",
FLT000001:"Product 1",
FLT000002:"Product 2",
FLT000003:"Product 3",
FLT000004:"Product 4",
FLT000005:"Product 5",
FLT000006:"Product 6",
FLT000007:"Product 7",
FLT000008:"Product 8",
FLT000009:"Product 9",
FLT0000010:"Product 10",
FLT000011:"-Select-",
FLT000012:"LAA",
FLT000013:"CAA",
FLT000014:"TDA",
FLT000015:"SBA",
FLT000016:"ODA",
FLT000017:"Bills",
FLT000018:"Documentary Credits",
FLT000019:"Guarantee",
FLT000020:"Remittance",
FLT000620:"Package Prising",
FLT200123:"-Select-",
FLT200124:"P - Percent",
FLT200125:"A - Amount",
FLT200122:"Value",
FLT200126:"Value",
FLT000193:"Submit",
FLT001721:"Cancel",
FLT026526:"OK"
};
var jspResALT = {
};
var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

