//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY
var jspRes={FLT004977:"Go",FLT648012:"Package Maintenance Menu",FLT006657:"Function",FLT004977:"Go",FLT001439:"Clear",
FLT000620:"Package Code",
FLT648230:"--Select--",
FLT648014:"A-Add",
FLT648181:"V-Verify",
FLT648017:"M-Modify",
FLT648183:"I-Inquire",
FLT648182:"X-Cancel"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY
var jspErr={};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);






