//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT004977:"Go",FLT031834:"Payment Maintenance",FLT030604:"Currency",FLT009568:"Inward Outward Indicator",FLT027516:"Payment Type",FLT031838:"CUG Identifier",FLT031839:"Nostro A/C",FLT031840:"Central Bank BIC",FLT031841:"Suspense A/C",FLT031842:"Threshold Limit Cr",FLT031843:"Threshold Limit Dr",FLT031844:"Cut off Time MT103",FLT031845:"Cut off Time MT202",FLT031848:"Outward Event ID",FLT031849:"Inward Event ID",FLT031829:"Free Text 1",FLT031830:"Free Text 2",FLT031831:"Free Text 3",FLT031846:"Free Text 4",FLT031847:"Free Text 5",FLT000134:"Free Code 1",FLT000135:"Free Code 2",FLT000136:"Free Code 3",FLT000137:"Free Code 4",FLT000138:"Free Code 5",FLT000139:"Parameter Details",FLT000140:"Threshold Limits",FLT000141:"Cut off Time",FLT000142:"Charges",FLT000143:"Free Fields",FLT000144:"Yes",FLT000145:"No",FLT000193:"Submit",FLT000194:"Validate",FLT001721:"Cancel",FLT026526:"OK"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY 
var jspErr={FATC00766:"Please enter time in HH24:MM format",FATC00767:"Please enter a valid time in HH24:MM format",FATC00768:"Please enter a valid Amount"};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);
