//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

//var jspRes={FLT1000101:"Function",FLT1000102:"Field Path",FLT1000103:"Option"};
var jspRes={FLT000611:"Function",FLT001439:"Clear",
FLT000612:"--SELECT--",
FLT000613:"A-Add",
FLT000621:"V-Verify",
FLT000622:"I-Inquire",
FLT000631:"X-Cancel",
FLT000633:"D-Delete",
FLT100620:"Package Code",
FLT100621:"CIF Id"
};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY 
var jspErr={};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);
