// GENERATED BY JSGEN. DO NOT MODIFY.
var applangcode = "INFENG";
var jspRes = {
    FLT003334: "Rate Code and Rate",
    FLT001501: "Del.",
    FLT048476: "Adjust Margin Event",
    FLT001166: "OK",
    FLT001830: "Event",
    FLT000233: "Operative A/c. ID",
    FLT000928: "Summary",
    FLT001393: "Clear",
    FLT000995: "Treasury Rate",
    FLT021394: "Collect",
    FLT021985: "Cash Margin",
    FLT045890: "Adjust Margin",
    FLT021984: "Total Margin",
    FLT021986: "Lien Margin",
    FLT022251: "Min. Margin Amt.",
    FLT050428: "Collect/Release",
    FLT022250: "Min. Margin Pcnt.",
    FLT021311: "Transfer",
    FLT012410: "Select",
    FLT000193: "Submit",
    FLT000192: "Cancel",
    FLT006367: "Sale",
    FLT001926: "Transfer A/c. ID",
    FLT000194: "Validate",
    FLT014666: "L - Lien",
    FLT022720: "Margin A/c. ID",
    FLT002965: "No",
    FLT004045: "CD Denomination",
    FLT004046: "Release Amt.",
    FLT004203: "CCY",
    FLT002964: "Yes",
    FLT001574: "Del.",
    FLT023990: "Treasury Ref. No.",
    FLT004389: "Release",
    FLT012038: "C - Cash",
    FLT022079: "Margin Amt.",
    FLT050315: "Margin Action",
    FLT004977: "Go",
    FLT001384: "Remarks",
    FLT009158: "Purchase"
};

var jspResALT = {};

var arrJspArr = new Array(jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);
