################################################################################################################################
#Source Name           : parse_xml.scl
# Date                  : 10-08-2022
# Description           : This scl contains several API calls
# Author                : SUNDAR
# Menu Option           :
# Calling Script        :
# Called Script         :
# Modification History  :
# <Serial No.>  <Date>        <Author Name>              <Reviewer Name>     <Description>
# ------------  -----------   -----------------         --------------       --------------
#      1        10-08-2022     Sundar                                                  Base Version
################################################################################################################################
#----------------------------------------------------------------------------------#
# FUNCTION TO PARSE THE XML TAGS IN API RESPONSE                                   #
#----------------------------------------------------------------------------------#
FUNCTION xmlParseFunc(fv_repos,fv_class,fv_fieldname,fv_xml)
#{
        fv_e = ""
        fv_r = fv_repos
        fv_c = fv_class
        fv_x = fv_xml
        fv_f = fv_fieldname

        print(fv_f)
        print(fv_x)

        fv_s = GETPOSITION(fv_x,fv_f)
        PRINT(fv_s)
        IF(fv_s == 0) THEN
        #{
                RETURN 1
        #}
        ELSE
        #{
                fv_a = "<"+fv_f+">"
                fv_b = STRLEN(fv_a)
                fv_s = GETPOSITION(fv_x,"<"+fv_f+">") +fv_b
                fv_s = fv_s-1
                PRINT(fv_s)
                fv_e = GETPOSITION(fv_x,"</"+fv_f+">")-1
                PRINT(fv_e)
                (fv_r).(fv_c).(fv_f) = MID$(fv_x,fv_s,(fv_e-fv_s))
                (fv_r).(fv_c).(fv_f) = TRIM((fv_r).(fv_c).(fv_f))
                PRINT((fv_r).(fv_c).(fv_f))

        #}
        ENDIF

        RETURN 0
#}
ENDFUNCTION
