
<%--
//Generated by Customization WB Generator
//Do not edit this file directly.
//Instead, modify the properties in the tool and regenerate.
--%>

<%@ page import="applcommon.ParseValue" %>
<%@ page import="com.infy.bbu.jsputil.*"%>
<%@ taglib uri="taglib.tld" prefix="arjsp" %>
<arjsp:init groupName="Customize" isEntryPoint="false" />

<%
        String sProfileId = ProfilesManager.getProfileInSession(session);
        String sSubGrpName = (String)ARJspCurr.getInput("subGroupName","");
%>

<script language="JavaScript">

                var inputNameValues    = "";
                var outputNames        = "bankId";
                var scrName            = "oclgirptmn003.scr";
                var retVal             = appFnExecuteScript(inputNameValues, outputNames, scrName, false);
                var ret = retVal.split("|");
                var bankId = ret[1];
</script>

<script>

        var Message = '<%=ParseValue.checkString(ARJspCurr.getInputWithGroup("RESULT_MSG",""))%>';

</script>



<script language="JavaScript">
        printBlock();
        printFooterBlock();
</script>

