<%--
//Generated by Customization WB Generator
//Do not edit this file directly.
//Instead, modify the properties in the tool and regenerate.
--%>

<%@ page import="applcommon.ParseValue" %>
<%@ page import="com.infy.bbu.jsputil.*"%>
<%@ taglib uri="taglib.tld" prefix="arjsp" %>
<arjsp:init groupName="Customize" isEntryPoint="false" />

<%
	String sProfileId = ProfilesManager.getProfileInSession(session);
	String sSubGrpName = (String)ARJspCurr.getInput("subGroupName","");
	String sGrpName = ARJspCurr.getCurrentGroup();
	String sPopUpExceptionWindow = (String)ARJspCurr.getInput(sGrpName+".PopUpExceptionWindow" ,"false");
	String sReferralMode = (String)ARJspCurr.getInput("refSubMode" ,"");
	ARJspCurr.setInput(sGrpName+".PopUpExceptionWindow","false");
	FABCommon.SecurityInfo70        securityInfo    = (FABCommon.SecurityInfo70)session.getAttribute("FinUserInfo");
	String homeSol  = (String)((securityInfo.homeSolId));
%>
<script language="JavaScript">

		var inputNameValues    = "";
		var outputNames        = "bankId";
		var scrName            = "oclgirptmn003.scr";
		var retVal             = appFnExecuteScript(inputNameValues, outputNames, scrName, false);
		var ret = retVal.split("|");
		var bankId = ret[1];
</script>

<script>

	var sPopUpExceptionWindow = '<%=sPopUpExceptionWindow%>';
	var sReferralMode = '<%=sReferralMode%>' ;
	var homeSol = <%=homeSol%>;
	var subGroupName = '<%=ParseValue.checkString(ARJspCurr.getInput("subGroupName",""))%>';
	var setId = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".setId",""))%>';
	var zoneCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".zoneCode",""))%>';
	var date_ui = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".date_ui",""))%>';
    var funcCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".funcCode",""))%>';
	var BODDate = '<%=(securityInfo.bodDate).substring(0,10)%>';
	var printio = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".printio",""))%>';
</script>

<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showClgZoneCode.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/lists/showAccountIdList.js" > </script>
<script language="javascript" src="../Renderer/custom/javascripts/custom_functions.js"></script>
<script language="javascript" src="../Renderer/custom/javascripts/custom_common_functions.js"></script>
<script language="javascript" src="../Renderer/custom/javascripts/cust_fetch_list.js"></script>
<script language="javascript" src="../Renderer/custom/javascripts/cust_fetch_list.js"></script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showSolId.js",sProfileId)%>" > </script>

<script language="JavaScript">
	printBlock();
	printFooterBlock();
</script>
