#!/bin/bash

# Export the Jasypt secret key as an environment variable
export JASYPT_ENCRYPTOR_PASSWORD="#{JASYPT-ENCRYPTOR-PASSWORD}#"
export CD_SPRING_DATASOURCE_URL="#{CD-SPRING-DATASOURCE-URL}#"
export CD_SPRING_DATASOURCE_USERNAME="#{CD-SPRING-DATASOURCE-USERNAME}#"
export CD_SPRING_DATASOURCE_PASSWORD="#{CD-SPRING-DATASOURCE-PASSWORD}#"

export CD_AIRTEL_B2C_CONSUMERKEY="#{CD-AIRTEL-B2C-CONSUMERKEY}#"
export CD_AIRTEL_B2C_CONSUMERSECRET="#{CD-AIRTEL-B2C-CONSUMERSECRET}#"
export CD_AIRTEL_B2C_KYC_URL="https://openapi.airtel.africa/standard/v1/users"
export CD_AIRTEL_B2C_DISBURSEMENT_URL="https://openapi.airtel.africa/bank-to-wallet/v1/payments/"
export CD_AIRTEL_B2C_TOKEN_URL="https://openapi.airtel.africa/auth/oauth2/token"
export CD_AIRTEL_B2C_STATUS_CHECK_URL="https://openapi.airtel.africa/bank-to-wallet/v1/payments"
export CD_AIRTEL_B2C_HOST_HEADER="openapi.airtel.africa"

export CD_AIRTEL_FLOAT_PURCHASE_CONSUMERKEY="#{CD-AIRTEL-FLOAT-PURCHASE-CONSUMERKEY}#"
export CD_AIRTEL_FLOAT_PURCHASE_CONSUMERSECRET="#{CD-AIRTEL-FLOAT-PURCHASE-CONSUMERSECRET}#"
export CD_AIRTEL_FLOAT_PURCHASE_KYC_URL="https://openapi.airtel.africa/standard/v1/users"
export CD_AIRTEL_FLOAT_PURCHASE_DISBURSEMENT_URL="https://openapi.airtel.africa/allocation"
export CD_AIRTEL_FLOAT_PURCHASE_TOKEN_URL="https://openapi.airtel.africa/auth/oauth2/token"
export CD_AIRTEL_FLOAT_PURCHASE_STATUS_CHECK_URL="https://openapi.airtel.africa/allocation/txn/status"

export CD_AIRTEL_AIRTIME_PURCHASE_REQUEST_URL="https://172.26.40.136:8093/pretups/C2SReceiver"
export CD_AIRTEL_AIRTIME_PURCHASE_PIN="#{CD-AIRTEL-AIRTIME-PURCHASE-PIN}#"
export CD_AIRTEL_AIRTIME_PURCHASE_CHANNEL_MSISDN="#{CD-AIRTEL-AIRTIME-PURCHASE-CHANNEL-MSISDN}#"
export CD_AIRTEL_AIRTIME_PURCHASE_PASSWORD="#{CD-AIRTEL-AIRTIME-PURCHASE-PASSWORD}#"
export CD_AIRTEL_AIRTIME_PURCHASE_EXTCODE="#{CD-AIRTEL-AIRTIME-PURCHASE-EXTCODE}#"
export CD_AIRTEL_AIRTIME_PURCHASE_LOGINID="#{CD-AIRTEL-AIRTIME-PURCHASE-LOGINID}#"

export CD_AIRTEL_AIRTIME_PURCHASE_URL_LOGIN="#{CD-AIRTEL-AIRTIME-PURCHASE-URL-LOGIN}#"
export CD_AIRTEL_AIRTIME_PURCHASE_URL_PASSWORD="#{CD-AIRTEL-AIRTIME-PURCHASE-URL-PASSWORD}#"
export CD_AIRTEL_AIRTIME_PURCHASE_REQUEST_GATEWAY_CODE="#{CD-AIRTEL-AIRTIME-PURCHASE-REQUEST-GATEWAY_CODE}#"
export CD_AIRTEL_AIRTIME_PURCHASE_URL_REQUEST_GATEWAY_TYPE="#{CD-AIRTEL-AIRTIME-PURCHASE-URL-REQUEST-GATEWAY-TYPE}#"
export CD_AIRTEL_AIRTIME_PURCHASE_URL_SOURCE_TYPE="#{CD-AIRTEL-AIRTIME-PURCHASE-URL-SOURCE-TYPE}#"
export CD_AIRTEL_AIRTIME_PURCHASE_URL_SERVICE_PORT="#{CD-AIRTEL-AIRTIME-PURCHASE-URL-SERVICE-PORT}#"


export CD_AIRTEL_OPENAPI_ENCRYPTION_KEY="#{CD-AIRTEL-OPENAPI-ENCRYPTION-KEY}#"

export KE_AIRTEL_FLOAT_PURCHASE_CONSUMERKEY="#{KE-AIRTEL-FLOAT-PURCHASE-CONSUMERKEY}#"
export KE_AIRTEL_FLOAT_PURCHASE_CONSUMERSECRET="#{KE-AIRTEL-FLOAT-PURCHASE-CONSUMERKEY}#"
export KE_AIRTEL_FLOAT_PURCHASE_KYC_URL="https://openapi.airtel.africa/standard/v1/users"
export KE_AIRTEL_FLOAT_PURCHASE_DISBURSEMENT_URL="https://openapi.airtel.africa/allocation"
export KE_AIRTEL_FLOAT_PURCHASE_TOKEN_URL="https://openapi.airtel.africa/auth/oauth2/token"
export KE_AIRTEL_FLOAT_PURCHASE_STATUS_CHECK_URL="https://openapi.airtel.africa/allocation/txn/status"
export KE_AIRTEL_B2C_HOST_HEADER="openapi.airtel.africa"
export KE_AIRTEL_OPENAPI_ENCRYPTION_KEY="#{KE-AIRTEL-FLOAT-PURCHASE-ENCRYPTION-KEY}#"

# Print a confirmation message
echo "Environment variables have been set."