package com.equitybank.gag.dummy_telco_b2c_ms.service.impl;

import com.equitybank.gag.dummy_telco_b2c_ms.service.ImtTransactionProcessService;
import com.equitybank.gag.dummy_telco_b2c_ms.service.TelcoTransactionProcessService;
import org.springframework.stereotype.Service;

@Service
public class ImtTransactionProcessServiceImpl implements ImtTransactionProcessService {

    @Override
    public String imtFailureResponse() {
        return "<soapenv:Envelope\n" +
                "    xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\"\n" +
                "    xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n" +
                "    xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\n" +
                "    <soapenv:Body>\n" +
                "        <soapenv:Fault>\n" +
                "            <faultcode>soapenv:Client</faultcode>\n" +
                "            <faultstring>This device has been deauthorized. Please contact Servicing via chat or email.</faultstring>\n" +
                "            <detail>\n" +
                "                <ac:errors\n" +
                "                    xmlns:ac=\"http://www.moneygram.com/AgentConnect1512\">\n" +
                "                    <ac:error>\n" +
                "                        <ac:errorCode>403</ac:errorCode>\n" +
                "                        <ac:errorString>This device has been deauthorized. Please contact Servicing via chat or email.</ac:errorString>\n" +
                "                        <ac:timeStamp>2024-08-29T03:54:40.489-05:00</ac:timeStamp>\n" +
                "                    </ac:error>\n" +
                "                </ac:errors>\n" +
                "                <ns1:exceptionName\n" +
                "                    xmlns:ns1=\"http://xml.apache.org/axis/\">com.moneygram.agentconnect.soap.ACException\n" +
                "                </ns1:exceptionName>\n" +
                "            </detail>\n" +
                "        </soapenv:Fault>\n" +
                "    </soapenv:Body>\n" +
                "</soapenv:Envelope>";
    }

    @Override
    public String commitRequestSuccess() {
        return "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
                "<soapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:SOAP-ENV=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\n" +
                "\t<SOAP-ENV:Header/>\n" +
                "\t<soapenv:Body xmlns:ac=\"http://www.moneygram.com/AgentConnect1512\">\n" +
                "\t\t<ac:commitTransactionResponse>\n" +
                "\t\t\t<ac:doCheckIn>false</ac:doCheckIn>\n" +
                "\t\t\t<ac:timeStamp>2023-02-13T11:17:02.140-06:00</ac:timeStamp>\n" +
                "\t\t\t<ac:flags>0</ac:flags>\n" +
                "\t\t\t<ac:referenceNumber>47795973</ac:referenceNumber>\n" +
                "\t\t\t<ac:expectedDateOfDelivery>2023-02-10</ac:expectedDateOfDelivery>\n" +
                "\t\t\t<ac:transactionDateTime>2023-02-13T11:17:02.140-06:00</ac:transactionDateTime>\n" +
                "\t\t</ac:commitTransactionResponse>\n" +
                "\t</soapenv:Body>\n" +
                "</soapenv:Envelope>";
    }

    @Override
    public String commitRequestFailure() {
        return null;
    }

    @Override
    public String feeLookupSuccess() {
        return "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
                "<soapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:SOAP-ENV=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\n" +
                "\t<SOAP-ENV:Header/>\n" +
                "\t<soapenv:Body xmlns:ac=\"http://www.moneygram.com/AgentConnect1512\">\n" +
                "\t\t<ac:feeLookupResponse>\n" +
                "\t\t\t<ac:doCheckIn>false</ac:doCheckIn>\n" +
                "\t\t\t<ac:timeStamp>2023-02-13T02:13:19.114-06:00</ac:timeStamp>\n" +
                "\t\t\t<ac:flags>0</ac:flags>\n" +
                "\t\t\t<ac:feeInfo>\n" +
                "\t\t\t\t<ac:validReceiveAmount>320.00</ac:validReceiveAmount>\n" +
                "\t\t\t\t<ac:validReceiveCurrency>USD</ac:validReceiveCurrency>\n" +
                "\t\t\t\t<ac:validExchangeRate>1.000000</ac:validExchangeRate>\n" +
                "\t\t\t\t<ac:estimatedReceiveAmount>0</ac:estimatedReceiveAmount>\n" +
                "\t\t\t\t<ac:estimatedExchangeRate>0.000000</ac:estimatedExchangeRate>\n" +
                "\t\t\t\t<ac:totalAmount>325.81</ac:totalAmount>\n" +
                "\t\t\t\t<ac:receiveCountry>POL</ac:receiveCountry>\n" +
                "\t\t\t\t<ac:deliveryOption>WILL_CALL</ac:deliveryOption>\n" +
                "\t\t\t\t<ac:receiveAmountAltered>false</ac:receiveAmountAltered>\n" +
                "\t\t\t\t<ac:revisedInformationalFee>false</ac:revisedInformationalFee>\n" +
                "\t\t\t\t<ac:deliveryOptId>0</ac:deliveryOptId>\n" +
                "\t\t\t\t<ac:deliveryOptDisplayName>10 Minute Service</ac:deliveryOptDisplayName>\n" +
                "\t\t\t\t<ac:mgiTransactionSessionID>1677371E1676275999270844798473NN</ac:mgiTransactionSessionID>\n" +
                "\t\t\t\t<ac:sendAmountAltered>false</ac:sendAmountAltered>\n" +
                "\t\t\t\t<ac:sendAmounts>\n" +
                "\t\t\t\t\t<ac:sendAmount>320.00</ac:sendAmount>\n" +
                "\t\t\t\t\t<ac:sendCurrency>USD</ac:sendCurrency>\n" +
                "\t\t\t\t\t<ac:totalSendFees>5.00</ac:totalSendFees>\n" +
                "\t\t\t\t\t<ac:totalDiscountAmount>0.00</ac:totalDiscountAmount>\n" +
                "\t\t\t\t\t<ac:totalSendTaxes>0.81</ac:totalSendTaxes>\n" +
                "\t\t\t\t\t<ac:totalAmountToCollect>325.81</ac:totalAmountToCollect>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiNonDiscountedSendFee</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>discountedMgiSendFee</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>totalMgiCollectedFeesAndTaxes</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>totalNonDiscountedFees</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>totalAmountToMgi</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>325.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>totalSendFeesAndTaxes</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.81</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>originalMgiSendFeeInclTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiCountrySendFeeTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiStateSendFeeTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiCountyCitySendFeeTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiTotalSendFeeTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>totalNonMgiSendFeesAndTaxes</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.81</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiSendFaceTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiSendTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>nonMgiSendTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.81</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>nonMgiSendFee</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t</ac:sendAmounts>\n" +
                "\t\t\t\t<ac:receiveAmounts>\n" +
                "\t\t\t\t\t<ac:receiveAmount>320.00</ac:receiveAmount>\n" +
                "\t\t\t\t\t<ac:receiveCurrency>USD</ac:receiveCurrency>\n" +
                "\t\t\t\t\t<ac:validCurrencyIndicator>true</ac:validCurrencyIndicator>\n" +
                "\t\t\t\t\t<ac:payoutCurrency>USD</ac:payoutCurrency>\n" +
                "\t\t\t\t\t<ac:totalReceiveFees>0.00</ac:totalReceiveFees>\n" +
                "\t\t\t\t\t<ac:totalReceiveTaxes>0.00</ac:totalReceiveTaxes>\n" +
                "\t\t\t\t\t<ac:totalReceiveAmount>320.00</ac:totalReceiveAmount>\n" +
                "\t\t\t\t\t<ac:receiveFeesAreEstimated>false</ac:receiveFeesAreEstimated>\n" +
                "\t\t\t\t\t<ac:receiveTaxesAreEstimated>false</ac:receiveTaxesAreEstimated>\n" +
                "\t\t\t\t\t<ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiReceiveFee</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t<ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>nonMgiReceiveFee</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t<ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiReceiveTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t<ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>nonMgiReceiveTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t</ac:receiveAmounts>\n" +
                "\t\t\t</ac:feeInfo>\n" +
                "\t\t\t<ac:feeInfo>\n" +
                "\t\t\t\t<ac:validReceiveAmount>1410.81</ac:validReceiveAmount>\n" +
                "\t\t\t\t<ac:validReceiveCurrency>PLN</ac:validReceiveCurrency>\n" +
                "\t\t\t\t<ac:validExchangeRate>4.408767</ac:validExchangeRate>\n" +
                "\t\t\t\t<ac:estimatedReceiveAmount>0</ac:estimatedReceiveAmount>\n" +
                "\t\t\t\t<ac:estimatedExchangeRate>0.000000</ac:estimatedExchangeRate>\n" +
                "\t\t\t\t<ac:totalAmount>325.81</ac:totalAmount>\n" +
                "\t\t\t\t<ac:receiveCountry>POL</ac:receiveCountry>\n" +
                "\t\t\t\t<ac:deliveryOption>WILL_CALL</ac:deliveryOption>\n" +
                "\t\t\t\t<ac:receiveAmountAltered>false</ac:receiveAmountAltered>\n" +
                "\t\t\t\t<ac:revisedInformationalFee>false</ac:revisedInformationalFee>\n" +
                "\t\t\t\t<ac:deliveryOptId>0</ac:deliveryOptId>\n" +
                "\t\t\t\t<ac:deliveryOptDisplayName>10 Minute Service</ac:deliveryOptDisplayName>\n" +
                "\t\t\t\t<ac:mgiTransactionSessionID>1677371E1676275999270400787383NN</ac:mgiTransactionSessionID>\n" +
                "\t\t\t\t<ac:sendAmountAltered>false</ac:sendAmountAltered>\n" +
                "\t\t\t\t<ac:sendAmounts>\n" +
                "\t\t\t\t\t<ac:sendAmount>320.00</ac:sendAmount>\n" +
                "\t\t\t\t\t<ac:sendCurrency>USD</ac:sendCurrency>\n" +
                "\t\t\t\t\t<ac:totalSendFees>5.00</ac:totalSendFees>\n" +
                "\t\t\t\t\t<ac:totalDiscountAmount>0.00</ac:totalDiscountAmount>\n" +
                "\t\t\t\t\t<ac:totalSendTaxes>0.81</ac:totalSendTaxes>\n" +
                "\t\t\t\t\t<ac:totalAmountToCollect>325.81</ac:totalAmountToCollect>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiNonDiscountedSendFee</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>discountedMgiSendFee</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>totalMgiCollectedFeesAndTaxes</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>totalNonDiscountedFees</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>totalAmountToMgi</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>325.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>totalSendFeesAndTaxes</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.81</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>originalMgiSendFeeInclTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiCountrySendFeeTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiStateSendFeeTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiCountyCitySendFeeTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiTotalSendFeeTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>totalNonMgiSendFeesAndTaxes</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.81</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiSendFaceTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiSendTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>nonMgiSendTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.81</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>nonMgiSendFee</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t</ac:sendAmounts>\n" +
                "\t\t\t\t<ac:receiveAmounts>\n" +
                "\t\t\t\t\t<ac:receiveAmount>1410.81</ac:receiveAmount>\n" +
                "\t\t\t\t\t<ac:receiveCurrency>PLN</ac:receiveCurrency>\n" +
                "\t\t\t\t\t<ac:validCurrencyIndicator>true</ac:validCurrencyIndicator>\n" +
                "\t\t\t\t\t<ac:payoutCurrency>PLN</ac:payoutCurrency>\n" +
                "\t\t\t\t\t<ac:totalReceiveFees>0.00</ac:totalReceiveFees>\n" +
                "\t\t\t\t\t<ac:totalReceiveTaxes>0.00</ac:totalReceiveTaxes>\n" +
                "\t\t\t\t\t<ac:totalReceiveAmount>1410.81</ac:totalReceiveAmount>\n" +
                "\t\t\t\t\t<ac:receiveFeesAreEstimated>false</ac:receiveFeesAreEstimated>\n" +
                "\t\t\t\t\t<ac:receiveTaxesAreEstimated>false</ac:receiveTaxesAreEstimated>\n" +
                "\t\t\t\t\t<ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiReceiveFee</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>PLN</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t<ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>nonMgiReceiveFee</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>PLN</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t<ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiReceiveTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>PLN</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t<ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>nonMgiReceiveTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>PLN</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t</ac:receiveAmounts>\n" +
                "\t\t\t</ac:feeInfo>\n" +
                "\t\t\t<ac:feeInfo>\n" +
                "\t\t\t\t<ac:validReceiveAmount>295.94</ac:validReceiveAmount>\n" +
                "\t\t\t\t<ac:validReceiveCurrency>EUR</ac:validReceiveCurrency>\n" +
                "\t\t\t\t<ac:validExchangeRate>0.924801</ac:validExchangeRate>\n" +
                "\t\t\t\t<ac:estimatedReceiveAmount>0</ac:estimatedReceiveAmount>\n" +
                "\t\t\t\t<ac:estimatedExchangeRate>0.000000</ac:estimatedExchangeRate>\n" +
                "\t\t\t\t<ac:totalAmount>325.81</ac:totalAmount>\n" +
                "\t\t\t\t<ac:receiveCountry>POL</ac:receiveCountry>\n" +
                "\t\t\t\t<ac:deliveryOption>WILL_CALL</ac:deliveryOption>\n" +
                "\t\t\t\t<ac:receiveAmountAltered>false</ac:receiveAmountAltered>\n" +
                "\t\t\t\t<ac:revisedInformationalFee>false</ac:revisedInformationalFee>\n" +
                "\t\t\t\t<ac:deliveryOptId>0</ac:deliveryOptId>\n" +
                "\t\t\t\t<ac:deliveryOptDisplayName>10 Minute Service</ac:deliveryOptDisplayName>\n" +
                "\t\t\t\t<ac:mgiTransactionSessionID>1677371E1676275999270501203694NN</ac:mgiTransactionSessionID>\n" +
                "\t\t\t\t<ac:sendAmountAltered>false</ac:sendAmountAltered>\n" +
                "\t\t\t\t<ac:sendAmounts>\n" +
                "\t\t\t\t\t<ac:sendAmount>320.00</ac:sendAmount>\n" +
                "\t\t\t\t\t<ac:sendCurrency>USD</ac:sendCurrency>\n" +
                "\t\t\t\t\t<ac:totalSendFees>5.00</ac:totalSendFees>\n" +
                "\t\t\t\t\t<ac:totalDiscountAmount>0.00</ac:totalDiscountAmount>\n" +
                "\t\t\t\t\t<ac:totalSendTaxes>0.81</ac:totalSendTaxes>\n" +
                "\t\t\t\t\t<ac:totalAmountToCollect>325.81</ac:totalAmountToCollect>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiNonDiscountedSendFee</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>discountedMgiSendFee</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>totalMgiCollectedFeesAndTaxes</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>totalNonDiscountedFees</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>totalAmountToMgi</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>325.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>totalSendFeesAndTaxes</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.81</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>originalMgiSendFeeInclTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiCountrySendFeeTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiStateSendFeeTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiCountyCitySendFeeTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiTotalSendFeeTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>totalNonMgiSendFeesAndTaxes</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.81</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiSendFaceTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiSendTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>nonMgiSendTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.81</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>nonMgiSendFee</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t</ac:sendAmounts>\n" +
                "\t\t\t\t<ac:receiveAmounts>\n" +
                "\t\t\t\t\t<ac:receiveAmount>295.94</ac:receiveAmount>\n" +
                "\t\t\t\t\t<ac:receiveCurrency>EUR</ac:receiveCurrency>\n" +
                "\t\t\t\t\t<ac:validCurrencyIndicator>true</ac:validCurrencyIndicator>\n" +
                "\t\t\t\t\t<ac:payoutCurrency>EUR</ac:payoutCurrency>\n" +
                "\t\t\t\t\t<ac:totalReceiveFees>0.00</ac:totalReceiveFees>\n" +
                "\t\t\t\t\t<ac:totalReceiveTaxes>0.00</ac:totalReceiveTaxes>\n" +
                "\t\t\t\t\t<ac:totalReceiveAmount>295.94</ac:totalReceiveAmount>\n" +
                "\t\t\t\t\t<ac:receiveFeesAreEstimated>false</ac:receiveFeesAreEstimated>\n" +
                "\t\t\t\t\t<ac:receiveTaxesAreEstimated>false</ac:receiveTaxesAreEstimated>\n" +
                "\t\t\t\t\t<ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiReceiveFee</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>EUR</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t<ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>nonMgiReceiveFee</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>EUR</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t<ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiReceiveTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>EUR</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t<ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>nonMgiReceiveTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>EUR</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t</ac:receiveAmounts>\n" +
                "\t\t\t</ac:feeInfo>\n" +
                "\t\t\t<ac:feeInfo>\n" +
                "\t\t\t\t<ac:validReceiveAmount>1410.81</ac:validReceiveAmount>\n" +
                "\t\t\t\t<ac:validReceiveCurrency>PLN</ac:validReceiveCurrency>\n" +
                "\t\t\t\t<ac:validExchangeRate>4.408767</ac:validExchangeRate>\n" +
                "\t\t\t\t<ac:estimatedReceiveAmount>0</ac:estimatedReceiveAmount>\n" +
                "\t\t\t\t<ac:estimatedExchangeRate>0.000000</ac:estimatedExchangeRate>\n" +
                "\t\t\t\t<ac:totalAmount>325.81</ac:totalAmount>\n" +
                "\t\t\t\t<ac:receiveCountry>POL</ac:receiveCountry>\n" +
                "\t\t\t\t<ac:deliveryOption>BANK_DEPOSIT</ac:deliveryOption>\n" +
                "\t\t\t\t<ac:receiveAmountAltered>false</ac:receiveAmountAltered>\n" +
                "\t\t\t\t<ac:revisedInformationalFee>false</ac:revisedInformationalFee>\n" +
                "\t\t\t\t<ac:deliveryOptId>10</ac:deliveryOptId>\n" +
                "\t\t\t\t<ac:deliveryOptDisplayName>Account Deposit</ac:deliveryOptDisplayName>\n" +
                "\t\t\t\t<ac:receiveAgentID>70276929</ac:receiveAgentID>\n" +
                "\t\t\t\t<ac:receiveAgentName>BLUE MEDIA  EXPRESS</ac:receiveAgentName>\n" +
                "\t\t\t\t<ac:receiveAgentAbbreviation>EXPRESS</ac:receiveAgentAbbreviation>\n" +
                "\t\t\t\t<ac:mgManaged>required</ac:mgManaged>\n" +
                "\t\t\t\t<ac:mgiTransactionSessionID>1677371E1676275999270181151087NN</ac:mgiTransactionSessionID>\n" +
                "\t\t\t\t<ac:sendAmountAltered>false</ac:sendAmountAltered>\n" +
                "\t\t\t\t<ac:sendAmounts>\n" +
                "\t\t\t\t\t<ac:sendAmount>320.00</ac:sendAmount>\n" +
                "\t\t\t\t\t<ac:sendCurrency>USD</ac:sendCurrency>\n" +
                "\t\t\t\t\t<ac:totalSendFees>5.00</ac:totalSendFees>\n" +
                "\t\t\t\t\t<ac:totalDiscountAmount>0.00</ac:totalDiscountAmount>\n" +
                "\t\t\t\t\t<ac:totalSendTaxes>0.81</ac:totalSendTaxes>\n" +
                "\t\t\t\t\t<ac:totalAmountToCollect>325.81</ac:totalAmountToCollect>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiNonDiscountedSendFee</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>discountedMgiSendFee</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>totalMgiCollectedFeesAndTaxes</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>totalNonDiscountedFees</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>totalAmountToMgi</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>325.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>totalSendFeesAndTaxes</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.81</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>originalMgiSendFeeInclTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiCountrySendFeeTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiStateSendFeeTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiCountyCitySendFeeTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiTotalSendFeeTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>totalNonMgiSendFeesAndTaxes</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.81</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiSendFaceTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiSendTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>nonMgiSendTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.81</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>nonMgiSendFee</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t</ac:sendAmounts>\n" +
                "\t\t\t\t<ac:receiveAmounts>\n" +
                "\t\t\t\t\t<ac:receiveAmount>1410.81</ac:receiveAmount>\n" +
                "\t\t\t\t\t<ac:receiveCurrency>PLN</ac:receiveCurrency>\n" +
                "\t\t\t\t\t<ac:validCurrencyIndicator>true</ac:validCurrencyIndicator>\n" +
                "\t\t\t\t\t<ac:payoutCurrency>PLN</ac:payoutCurrency>\n" +
                "\t\t\t\t\t<ac:totalReceiveFees>0.00</ac:totalReceiveFees>\n" +
                "\t\t\t\t\t<ac:totalReceiveTaxes>0.00</ac:totalReceiveTaxes>\n" +
                "\t\t\t\t\t<ac:totalReceiveAmount>1410.81</ac:totalReceiveAmount>\n" +
                "\t\t\t\t\t<ac:receiveFeesAreEstimated>false</ac:receiveFeesAreEstimated>\n" +
                "\t\t\t\t\t<ac:receiveTaxesAreEstimated>false</ac:receiveTaxesAreEstimated>\n" +
                "\t\t\t\t\t<ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiReceiveFee</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>PLN</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t<ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>nonMgiReceiveFee</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>PLN</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t<ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiReceiveTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>PLN</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t<ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>nonMgiReceiveTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>PLN</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t</ac:receiveAmounts>\n" +
                "\t\t\t</ac:feeInfo>\n" +
                "\t\t\t<ac:feeInfo>\n" +
                "\t\t\t\t<ac:validReceiveAmount>1410.81</ac:validReceiveAmount>\n" +
                "\t\t\t\t<ac:validReceiveCurrency>PLN</ac:validReceiveCurrency>\n" +
                "\t\t\t\t<ac:validExchangeRate>4.408767</ac:validExchangeRate>\n" +
                "\t\t\t\t<ac:estimatedReceiveAmount>0</ac:estimatedReceiveAmount>\n" +
                "\t\t\t\t<ac:estimatedExchangeRate>0.000000</ac:estimatedExchangeRate>\n" +
                "\t\t\t\t<ac:totalAmount>325.81</ac:totalAmount>\n" +
                "\t\t\t\t<ac:receiveCountry>POL</ac:receiveCountry>\n" +
                "\t\t\t\t<ac:deliveryOption>BANK_DEPOSIT</ac:deliveryOption>\n" +
                "\t\t\t\t<ac:receiveAmountAltered>false</ac:receiveAmountAltered>\n" +
                "\t\t\t\t<ac:revisedInformationalFee>false</ac:revisedInformationalFee>\n" +
                "\t\t\t\t<ac:deliveryOptId>10</ac:deliveryOptId>\n" +
                "\t\t\t\t<ac:deliveryOptDisplayName>Account Deposit</ac:deliveryOptDisplayName>\n" +
                "\t\t\t\t<ac:receiveAgentID>70276932</ac:receiveAgentID>\n" +
                "\t\t\t\t<ac:receiveAgentName>BLUE MEDIA STANDARD</ac:receiveAgentName>\n" +
                "\t\t\t\t<ac:receiveAgentAbbreviation>STANDARD</ac:receiveAgentAbbreviation>\n" +
                "\t\t\t\t<ac:mgManaged>required</ac:mgManaged>\n" +
                "\t\t\t\t<ac:mgiTransactionSessionID>1677371E1676275999270901506117NN</ac:mgiTransactionSessionID>\n" +
                "\t\t\t\t<ac:sendAmountAltered>false</ac:sendAmountAltered>\n" +
                "\t\t\t\t<ac:sendAmounts>\n" +
                "\t\t\t\t\t<ac:sendAmount>320.00</ac:sendAmount>\n" +
                "\t\t\t\t\t<ac:sendCurrency>USD</ac:sendCurrency>\n" +
                "\t\t\t\t\t<ac:totalSendFees>5.00</ac:totalSendFees>\n" +
                "\t\t\t\t\t<ac:totalDiscountAmount>0.00</ac:totalDiscountAmount>\n" +
                "\t\t\t\t\t<ac:totalSendTaxes>0.81</ac:totalSendTaxes>\n" +
                "\t\t\t\t\t<ac:totalAmountToCollect>325.81</ac:totalAmountToCollect>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiNonDiscountedSendFee</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>discountedMgiSendFee</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>totalMgiCollectedFeesAndTaxes</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>totalNonDiscountedFees</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>totalAmountToMgi</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>325.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>totalSendFeesAndTaxes</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.81</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>originalMgiSendFeeInclTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiCountrySendFeeTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiStateSendFeeTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiCountyCitySendFeeTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiTotalSendFeeTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>totalNonMgiSendFeesAndTaxes</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.81</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiSendFaceTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiSendTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>nonMgiSendTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.81</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>nonMgiSendFee</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t</ac:sendAmounts>\n" +
                "\t\t\t\t<ac:receiveAmounts>\n" +
                "\t\t\t\t\t<ac:receiveAmount>1410.81</ac:receiveAmount>\n" +
                "\t\t\t\t\t<ac:receiveCurrency>PLN</ac:receiveCurrency>\n" +
                "\t\t\t\t\t<ac:validCurrencyIndicator>true</ac:validCurrencyIndicator>\n" +
                "\t\t\t\t\t<ac:payoutCurrency>PLN</ac:payoutCurrency>\n" +
                "\t\t\t\t\t<ac:totalReceiveFees>0.00</ac:totalReceiveFees>\n" +
                "\t\t\t\t\t<ac:totalReceiveTaxes>0.00</ac:totalReceiveTaxes>\n" +
                "\t\t\t\t\t<ac:totalReceiveAmount>1410.81</ac:totalReceiveAmount>\n" +
                "\t\t\t\t\t<ac:receiveFeesAreEstimated>false</ac:receiveFeesAreEstimated>\n" +
                "\t\t\t\t\t<ac:receiveTaxesAreEstimated>false</ac:receiveTaxesAreEstimated>\n" +
                "\t\t\t\t\t<ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiReceiveFee</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>PLN</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t<ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>nonMgiReceiveFee</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>PLN</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t<ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiReceiveTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>PLN</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t<ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>nonMgiReceiveTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>PLN</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t</ac:receiveAmounts>\n" +
                "\t\t\t</ac:feeInfo>\n" +
                "\t\t\t<ac:feeInfo>\n" +
                "\t\t\t\t<ac:validReceiveAmount>295.94</ac:validReceiveAmount>\n" +
                "\t\t\t\t<ac:validReceiveCurrency>EUR</ac:validReceiveCurrency>\n" +
                "\t\t\t\t<ac:validExchangeRate>0.924801</ac:validExchangeRate>\n" +
                "\t\t\t\t<ac:estimatedReceiveAmount>0</ac:estimatedReceiveAmount>\n" +
                "\t\t\t\t<ac:estimatedExchangeRate>0.000000</ac:estimatedExchangeRate>\n" +
                "\t\t\t\t<ac:totalAmount>325.81</ac:totalAmount>\n" +
                "\t\t\t\t<ac:receiveCountry>POL</ac:receiveCountry>\n" +
                "\t\t\t\t<ac:deliveryOption>BANK_DEPOSIT</ac:deliveryOption>\n" +
                "\t\t\t\t<ac:receiveAmountAltered>false</ac:receiveAmountAltered>\n" +
                "\t\t\t\t<ac:revisedInformationalFee>false</ac:revisedInformationalFee>\n" +
                "\t\t\t\t<ac:deliveryOptId>10</ac:deliveryOptId>\n" +
                "\t\t\t\t<ac:deliveryOptDisplayName>Account Deposit</ac:deliveryOptDisplayName>\n" +
                "\t\t\t\t<ac:receiveAgentID>70552740</ac:receiveAgentID>\n" +
                "\t\t\t\t<ac:receiveAgentName>WORLDPAY</ac:receiveAgentName>\n" +
                "\t\t\t\t<ac:receiveAgentAbbreviation>STANDARD</ac:receiveAgentAbbreviation>\n" +
                "\t\t\t\t<ac:mgManaged>required</ac:mgManaged>\n" +
                "\t\t\t\t<ac:mgiTransactionSessionID>1677371E1676275999270142658743NN</ac:mgiTransactionSessionID>\n" +
                "\t\t\t\t<ac:sendAmountAltered>false</ac:sendAmountAltered>\n" +
                "\t\t\t\t<ac:sendAmounts>\n" +
                "\t\t\t\t\t<ac:sendAmount>320.00</ac:sendAmount>\n" +
                "\t\t\t\t\t<ac:sendCurrency>USD</ac:sendCurrency>\n" +
                "\t\t\t\t\t<ac:totalSendFees>5.00</ac:totalSendFees>\n" +
                "\t\t\t\t\t<ac:totalDiscountAmount>0.00</ac:totalDiscountAmount>\n" +
                "\t\t\t\t\t<ac:totalSendTaxes>0.81</ac:totalSendTaxes>\n" +
                "\t\t\t\t\t<ac:totalAmountToCollect>325.81</ac:totalAmountToCollect>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiNonDiscountedSendFee</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>discountedMgiSendFee</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>totalMgiCollectedFeesAndTaxes</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>totalNonDiscountedFees</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>totalAmountToMgi</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>325.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>totalSendFeesAndTaxes</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.81</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>originalMgiSendFeeInclTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiCountrySendFeeTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiStateSendFeeTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiCountyCitySendFeeTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiTotalSendFeeTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>totalNonMgiSendFeesAndTaxes</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.81</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiSendFaceTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiSendTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>nonMgiSendTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.81</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>nonMgiSendFee</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t</ac:sendAmounts>\n" +
                "\t\t\t\t<ac:receiveAmounts>\n" +
                "\t\t\t\t\t<ac:receiveAmount>295.94</ac:receiveAmount>\n" +
                "\t\t\t\t\t<ac:receiveCurrency>EUR</ac:receiveCurrency>\n" +
                "\t\t\t\t\t<ac:validCurrencyIndicator>true</ac:validCurrencyIndicator>\n" +
                "\t\t\t\t\t<ac:payoutCurrency>EUR</ac:payoutCurrency>\n" +
                "\t\t\t\t\t<ac:totalReceiveFees>0.00</ac:totalReceiveFees>\n" +
                "\t\t\t\t\t<ac:totalReceiveTaxes>0.00</ac:totalReceiveTaxes>\n" +
                "\t\t\t\t\t<ac:totalReceiveAmount>295.94</ac:totalReceiveAmount>\n" +
                "\t\t\t\t\t<ac:receiveFeesAreEstimated>false</ac:receiveFeesAreEstimated>\n" +
                "\t\t\t\t\t<ac:receiveTaxesAreEstimated>false</ac:receiveTaxesAreEstimated>\n" +
                "\t\t\t\t\t<ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiReceiveFee</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>EUR</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t<ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>nonMgiReceiveFee</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>EUR</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t<ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiReceiveTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>EUR</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t<ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>nonMgiReceiveTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>EUR</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t</ac:receiveAmounts>\n" +
                "\t\t\t</ac:feeInfo>\n" +
                "\t\t</ac:feeLookupResponse>\n" +
                "\t</soapenv:Body>\n" +
                "</soapenv:Envelope>";
    }

    @Override
    public String referenceNumberRequestSuccess() {
        return "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
                "<soapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:SOAP-ENV=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\n" +
                "\t<SOAP-ENV:Header/>\n" +
                "\t<soapenv:Body xmlns:ac=\"http://www.moneygram.com/AgentConnect1512\">\n" +
                "\t\t<ac:referenceNumberResponse>\n" +
                "\t\t\t<ac:doCheckIn>false</ac:doCheckIn>\n" +
                "\t\t\t<ac:timeStamp>2023-02-13T11:10:51.734-06:00</ac:timeStamp>\n" +
                "\t\t\t<ac:flags>0</ac:flags>\n" +
                "\t\t\t<ac:mgiTransactionSessionID>432939131E1676306273485</ac:mgiTransactionSessionID>\n" +
                "\t\t\t<ac:senderFirstName>SUMIT</ac:senderFirstName>\n" +
                "\t\t\t<ac:senderMiddleName>RAVI</ac:senderMiddleName>\n" +
                "\t\t\t<ac:senderLastName>SHETTY</ac:senderLastName>\n" +
                "\t\t\t<ac:senderHomePhone>13701708804</ac:senderHomePhone>\n" +
                "\t\t\t<ac:receiverFirstName>BEATRICE</ac:receiverFirstName>\n" +
                "\t\t\t<ac:receiverMiddleName>A</ac:receiverMiddleName>\n" +
                "\t\t\t<ac:receiverLastName>EVELYN</ac:receiverLastName>\n" +
                "\t\t\t<ac:agentCheckNumber>0000000000</ac:agentCheckNumber>\n" +
                "\t\t\t<ac:agentCheckAmount>100.000</ac:agentCheckAmount>\n" +
                "\t\t\t<ac:agentCheckAuthorizationNumber>00000</ac:agentCheckAuthorizationNumber>\n" +
                "\t\t\t<ac:customerCheckNumber>0000000000</ac:customerCheckNumber>\n" +
                "\t\t\t<ac:customerCheckAmount>0.000</ac:customerCheckAmount>\n" +
                "\t\t\t<ac:okForAgent>true</ac:okForAgent>\n" +
                "\t\t\t<ac:deliveryOption>WILL_CALL</ac:deliveryOption>\n" +
                "\t\t\t<ac:transactionStatus>AVAIL</ac:transactionStatus>\n" +
                "\t\t\t<ac:dateTimeSent>2023-02-10T03:46:38.637-06:00</ac:dateTimeSent>\n" +
                "\t\t\t<ac:receiveCurrency>USD</ac:receiveCurrency>\n" +
                "\t\t\t<ac:receiveAmount>100.00</ac:receiveAmount>\n" +
                "\t\t\t<ac:referenceNumber>47795973</ac:referenceNumber>\n" +
                "\t\t\t<ac:originatingCountry>USA</ac:originatingCountry>\n" +
                "\t\t\t<ac:validIndicator>false</ac:validIndicator>\n" +
                "\t\t\t<ac:indicativeReceiveAmount>0</ac:indicativeReceiveAmount>\n" +
                "\t\t\t<ac:indicativeExchangeRate>0.000000</ac:indicativeExchangeRate>\n" +
                "\t\t\t<ac:expectedDateOfDelivery>2023-02-10</ac:expectedDateOfDelivery>\n" +
                "\t\t\t<ac:originalSendAmount>100.00</ac:originalSendAmount>\n" +
                "\t\t\t<ac:originalSendCurrency>USD</ac:originalSendCurrency>\n" +
                "\t\t\t<ac:originalSendFee>4.00</ac:originalSendFee>\n" +
                "\t\t\t<ac:originalExchangeRate>1.000000</ac:originalExchangeRate>\n" +
                "\t\t\t<ac:redirectIndicator>false</ac:redirectIndicator>\n" +
                "\t\t\t<ac:okForPickup>true</ac:okForPickup>\n" +
                "\t\t\t<ac:notOkForPickupReasonCode>0</ac:notOkForPickupReasonCode>\n" +
                "\t\t\t<ac:minutesUntilOkForPickup>0</ac:minutesUntilOkForPickup>\n" +
                "\t\t</ac:referenceNumberResponse>\n" +
                "\t</soapenv:Body>\n" +
                "</soapenv:Envelope>";
    }

    @Override
    public String receiveGFFPSuccess() {
        return "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
                "<soapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:SOAP-ENV=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\n" +
                "\t<SOAP-ENV:Header/>\n" +
                "\t<soapenv:Body xmlns:ac=\"http://www.moneygram.com/AgentConnect1512\">\n" +
                "\t\t<ac:getFieldsForProductResponse>\n" +
                "\t\t\t<ac:doCheckIn>false</ac:doCheckIn>\n" +
                "\t\t\t<ac:timeStamp>2023-02-13T11:11:16.443-06:00</ac:timeStamp>\n" +
                "\t\t\t<ac:flags>0</ac:flags>\n" +
                "\t\t\t<ac:fqdoInfo>\n" +
                "\t\t\t\t<ac:receiveCountry>COD</ac:receiveCountry>\n" +
                "\t\t\t\t<ac:deliveryOption>WILL_CALL</ac:deliveryOption>\n" +
                "\t\t\t\t<ac:receiveCurrency>USD</ac:receiveCurrency>\n" +
                "\t\t\t</ac:fqdoInfo>\n" +
                "\t\t\t<ac:productFieldInfo>\n" +
                "\t\t\t\t<ac:xmlTag>thirdPartyState</ac:xmlTag>\n" +
                "\t\t\t\t<ac:visibility>SUP_OPT</ac:visibility>\n" +
                "\t\t\t\t<ac:fieldLabel>Third Party State</ac:fieldLabel>\n" +
                "\t\t\t\t<ac:displayOrder>9</ac:displayOrder>\n" +
                "\t\t\t\t<ac:fieldCategory>receiveThirdPartyReceiverInformationSet</ac:fieldCategory>\n" +
                "\t\t\t\t<ac:dynamic>false</ac:dynamic>\n" +
                "\t\t\t\t<ac:fieldMax>2</ac:fieldMax>\n" +
                "\t\t\t\t<ac:fieldMin>0</ac:fieldMin>\n" +
                "\t\t\t\t<ac:dataType>string</ac:dataType>\n" +
                "\t\t\t\t<ac:enumerated>false</ac:enumerated>\n" +
                "\t\t\t\t<ac:defaultValue/>\n" +
                "\t\t\t\t<ac:validationRegEx/>\n" +
                "\t\t\t\t<ac:arrayName/>\n" +
                "\t\t\t\t<ac:arrayLength>0</ac:arrayLength>\n" +
                "\t\t\t\t<ac:exampleFormat/>\n" +
                "\t\t\t\t<ac:enumeratedValues/>\n" +
                "\t\t\t</ac:productFieldInfo>\n" +
                "\t\t\t<ac:productFieldInfo>\n" +
                "\t\t\t\t<ac:xmlTag>receiverCity</ac:xmlTag>\n" +
                "\t\t\t\t<ac:visibility>REQ</ac:visibility>\n" +
                "\t\t\t\t<ac:fieldLabel>Receiver City</ac:fieldLabel>\n" +
                "\t\t\t\t<ac:displayOrder>6</ac:displayOrder>\n" +
                "\t\t\t\t<ac:fieldCategory>receiveReceiverInformationSet</ac:fieldCategory>\n" +
                "\t\t\t\t<ac:dynamic>false</ac:dynamic>\n" +
                "\t\t\t\t<ac:fieldMax>40</ac:fieldMax>\n" +
                "\t\t\t\t<ac:fieldMin>0</ac:fieldMin>\n" +
                "\t\t\t\t<ac:dataType>string</ac:dataType>\n" +
                "\t\t\t\t<ac:enumerated>false</ac:enumerated>\n" +
                "\t\t\t\t<ac:defaultValue/>\n" +
                "\t\t\t\t<ac:validationRegEx>^([a-zA-Z \\u00C0-\\u017F\\#\\/\\.\\\"\\'\\,\\(\\)\\-])*$</ac:validationRegEx>\n" +
                "\t\t\t\t<ac:arrayName/>\n" +
                "\t\t\t\t<ac:arrayLength>0</ac:arrayLength>\n" +
                "\t\t\t\t<ac:exampleFormat/>\n" +
                "\t\t\t\t<ac:enumeratedValues/>\n" +
                "\t\t\t</ac:productFieldInfo>\n" +
                "\t\t\t<ac:productFieldInfo>\n" +
                "\t\t\t\t<ac:xmlTag>agentCheckNumber</ac:xmlTag>\n" +
                "\t\t\t\t<ac:visibility>NOT_ALL</ac:visibility>\n" +
                "\t\t\t\t<ac:fieldLabel>Agent Check Number</ac:fieldLabel>\n" +
                "\t\t\t\t<ac:displayOrder>15</ac:displayOrder>\n" +
                "\t\t\t\t<ac:fieldCategory>receiveReceiverPayoutSet</ac:fieldCategory>\n" +
                "\t\t\t\t<ac:dynamic>false</ac:dynamic>\n" +
                "\t\t\t\t<ac:fieldMax>12</ac:fieldMax>\n" +
                "\t\t\t\t<ac:fieldMin>0</ac:fieldMin>\n" +
                "\t\t\t\t<ac:dataType>string</ac:dataType>\n" +
                "\t\t\t\t<ac:enumerated>false</ac:enumerated>\n" +
                "\t\t\t\t<ac:defaultValue/>\n" +
                "\t\t\t\t<ac:validationRegEx>^[0-9]*$</ac:validationRegEx>\n" +
                "\t\t\t\t<ac:arrayName/>\n" +
                "\t\t\t\t<ac:arrayLength>0</ac:arrayLength>\n" +
                "\t\t\t\t<ac:exampleFormat/>\n" +
                "\t\t\t\t<ac:enumeratedValues/>\n" +
                "\t\t\t</ac:productFieldInfo>\n" +
                "\t\t\t<ac:productFieldInfo>\n" +
                "\t\t\t\t<ac:xmlTag>receiverPhotoIdIssueMonth</ac:xmlTag>\n" +
                "\t\t\t\t<ac:visibility>OPT</ac:visibility>\n" +
                "\t\t\t\t<ac:fieldLabel>Receiver ID Issue Month</ac:fieldLabel>\n" +
                "\t\t\t\t<ac:displayOrder>26</ac:displayOrder>\n" +
                "\t\t\t\t<ac:fieldCategory>receiveReceiverIdentificationPrimarySet</ac:fieldCategory>\n" +
                "\t\t\t\t<ac:dynamic>false</ac:dynamic>\n" +
                "\t\t\t\t<ac:fieldMax>2</ac:fieldMax>\n" +
                "\t\t\t\t<ac:fieldMin>0</ac:fieldMin>\n" +
                "\t\t\t\t<ac:dataType>string</ac:dataType>\n" +
                "\t\t\t\t<ac:enumerated>false</ac:enumerated>\n" +
                "\t\t\t\t<ac:defaultValue/>\n" +
                "\t\t\t\t<ac:validationRegEx>^[0-9]*$</ac:validationRegEx>\n" +
                "\t\t\t\t<ac:arrayName/>\n" +
                "\t\t\t\t<ac:arrayLength>0</ac:arrayLength>\n" +
                "\t\t\t\t<ac:exampleFormat/>\n" +
                "\t\t\t\t<ac:enumeratedValues/>\n" +
                "\t\t\t</ac:productFieldInfo>\n" +
                "\t\t\t<ac:productFieldInfo>\n" +
                "\t\t\t\t<ac:xmlTag>cardSwiped</ac:xmlTag>\n" +
                "\t\t\t\t<ac:visibility>NOT_ALL</ac:visibility>\n" +
                "\t\t\t\t<ac:fieldLabel>Card Swiped</ac:fieldLabel>\n" +
                "\t\t\t\t<ac:displayOrder>3</ac:displayOrder>\n" +
                "\t\t\t\t<ac:fieldCategory>receiveOperationalInformationSet</ac:fieldCategory>\n" +
                "\t\t\t\t<ac:dynamic>false</ac:dynamic>\n" +
                "\t\t\t\t<ac:fieldMax>5</ac:fieldMax>\n" +
                "\t\t\t\t<ac:fieldMin>0</ac:fieldMin>\n" +
                "\t\t\t\t<ac:dataType>boolean</ac:dataType>\n" +
                "\t\t\t\t<ac:enumerated>false</ac:enumerated>\n" +
                "\t\t\t\t<ac:defaultValue/>\n" +
                "\t\t\t\t<ac:validationRegEx/>\n" +
                "\t\t\t\t<ac:arrayName/>\n" +
                "\t\t\t\t<ac:arrayLength>0</ac:arrayLength>\n" +
                "\t\t\t\t<ac:exampleFormat/>\n" +
                "\t\t\t\t<ac:enumeratedValues/>\n" +
                "\t\t\t</ac:productFieldInfo>\n" +
                "\t\t\t<ac:productFieldInfo>\n" +
                "\t\t\t\t<ac:xmlTag>thirdPartyReceiverOccupationOther</ac:xmlTag>\n" +
                "\t\t\t\t<ac:visibility>NOT_ALL</ac:visibility>\n" +
                "\t\t\t\t<ac:fieldLabel>Third Party Receiver Other Occupation</ac:fieldLabel>\n" +
                "\t\t\t\t<ac:displayOrder>26</ac:displayOrder>\n" +
                "\t\t\t\t<ac:fieldCategory>receiveTPReceiverInformationSet</ac:fieldCategory>\n" +
                "\t\t\t\t<ac:dynamic>false</ac:dynamic>\n" +
                "\t\t\t\t<ac:fieldMax>30</ac:fieldMax>\n" +
                "\t\t\t\t<ac:fieldMin>2</ac:fieldMin>\n" +
                "\t\t\t\t<ac:dataType>string</ac:dataType>\n" +
                "\t\t\t\t<ac:enumerated>false</ac:enumerated>\n" +
                "\t\t\t\t<ac:defaultValue/>\n" +
                "\t\t\t\t<ac:validationRegEx>^([a-zA-Z \\u00C0-\\u017F\\/\\,\\(\\)])*$</ac:validationRegEx>\n" +
                "\t\t\t\t<ac:arrayName/>\n" +
                "\t\t\t\t<ac:arrayLength>0</ac:arrayLength>\n" +
                "\t\t\t\t<ac:exampleFormat/>\n" +
                "\t\t\t\t<ac:enumeratedValues/>\n" +
                "\t\t\t</ac:productFieldInfo>\n" +
                "\t\t\t<ac:productFieldInfo>\n" +
                "\t\t\t\t<ac:xmlTag>agentTransactionId</ac:xmlTag>\n" +
                "\t\t\t\t<ac:visibility>SUP_OPT</ac:visibility>\n" +
                "\t\t\t\t<ac:fieldLabel>Agent Transaction ID</ac:fieldLabel>\n" +
                "\t\t\t\t<ac:displayOrder>2</ac:displayOrder>\n" +
                "\t\t\t\t<ac:fieldCategory>receiveOperationalInformationSet</ac:fieldCategory>\n" +
                "\t\t\t\t<ac:dynamic>false</ac:dynamic>\n" +
                "\t\t\t\t<ac:fieldMax>20</ac:fieldMax>\n" +
                "\t\t\t\t<ac:fieldMin>0</ac:fieldMin>\n" +
                "\t\t\t\t<ac:dataType>string</ac:dataType>\n" +
                "\t\t\t\t<ac:enumerated>false</ac:enumerated>\n" +
                "\t\t\t\t<ac:defaultValue/>\n" +
                "\t\t\t\t<ac:validationRegEx/>\n" +
                "\t\t\t\t<ac:arrayName/>\n" +
                "\t\t\t\t<ac:arrayLength>0</ac:arrayLength>\n" +
                "\t\t\t\t<ac:exampleFormat/>\n" +
                "\t\t\t\t<ac:enumeratedValues/>\n" +
                "\t\t\t</ac:productFieldInfo>\n" +
                "\t\t\t<ac:productFieldInfo>\n" +
                "\t\t\t\t<ac:xmlTag>thirdPartyLegalIdIssueAuthority</ac:xmlTag>\n" +
                "\t\t\t\t<ac:visibility>NOT_ALL</ac:visibility>\n" +
                "\t\t\t\t<ac:fieldLabel>Third Party ID Issue Authority</ac:fieldLabel>\n" +
                "\t\t\t\t<ac:displayOrder>14</ac:displayOrder>\n" +
                "\t\t\t\t<ac:fieldCategory>receiveTPReceiverIdentificationPrimarySet</ac:fieldCategory>\n" +
                "\t\t\t\t<ac:dynamic>false</ac:dynamic>\n" +
                "\t\t\t\t<ac:fieldMax>0</ac:fieldMax>\n" +
                "\t\t\t\t<ac:fieldMin>0</ac:fieldMin>\n" +
                "\t\t\t\t<ac:dataType>enum</ac:dataType>\n" +
                "\t\t\t\t<ac:enumerated>true</ac:enumerated>\n" +
                "\t\t\t\t<ac:defaultValue/>\n" +
                "\t\t\t\t<ac:validationRegEx/>\n" +
                "\t\t\t\t<ac:arrayName/>\n" +
                "\t\t\t\t<ac:arrayLength>0</ac:arrayLength>\n" +
                "\t\t\t\t<ac:exampleFormat/>\n" +
                "\t\t\t\t<ac:enumeratedValues>\n" +
                "\t\t\t\t\t<ac:enumeratedValueInfo>\n" +
                "\t\t\t\t\t\t<ac:value>AB</ac:value>\n" +
                "\t\t\t\t\t\t<ac:label>Agency or Bureau</ac:label>\n" +
                "\t\t\t\t\t</ac:enumeratedValueInfo>\n" +
                "\t\t\t\t\t<ac:enumeratedValueInfo>\n" +
                "\t\t\t\t\t\t<ac:value>CO</ac:value>\n" +
                "\t\t\t\t\t\t<ac:label>Commissioners Office</ac:label>\n" +
                "\t\t\t\t\t</ac:enumeratedValueInfo>\n" +
                "\t\t\t\t\t<ac:enumeratedValueInfo>\n" +
                "\t\t\t\t\t\t<ac:value>CON</ac:value>\n" +
                "\t\t\t\t\t\t<ac:label>Consulate</ac:label>\n" +
                "\t\t\t\t\t</ac:enumeratedValueInfo>\n" +
                "\t\t\t\t\t<ac:enumeratedValueInfo>\n" +
                "\t\t\t\t\t\t<ac:value>COR</ac:value>\n" +
                "\t\t\t\t\t\t<ac:label>Corporation</ac:label>\n" +
                "\t\t\t\t\t</ac:enumeratedValueInfo>\n" +
                "\t\t\t\t\t<ac:enumeratedValueInfo>\n" +
                "\t\t\t\t\t\t<ac:value>EMB</ac:value>\n" +
                "\t\t\t\t\t\t<ac:label>Embassy</ac:label>\n" +
                "\t\t\t\t\t</ac:enumeratedValueInfo>\n" +
                "\t\t\t\t</ac:enumeratedValues>\n" +
                "\t\t\t</ac:productFieldInfo>\n" +
                "\t\t\t<ac:productFieldInfo>\n" +
                "\t\t\t\t<ac:xmlTag>receiverPhotoIdIssueYear</ac:xmlTag>\n" +
                "\t\t\t\t<ac:visibility>OPT</ac:visibility>\n" +
                "\t\t\t\t<ac:fieldLabel>Receiver ID Issue Year</ac:fieldLabel>\n" +
                "\t\t\t\t<ac:displayOrder>28</ac:displayOrder>\n" +
                "\t\t\t\t<ac:fieldCategory>receiveReceiverIdentificationPrimarySet</ac:fieldCategory>\n" +
                "\t\t\t\t<ac:dynamic>false</ac:dynamic>\n" +
                "\t\t\t\t<ac:fieldMax>4</ac:fieldMax>\n" +
                "\t\t\t\t<ac:fieldMin>4</ac:fieldMin>\n" +
                "\t\t\t\t<ac:dataType>string</ac:dataType>\n" +
                "\t\t\t\t<ac:enumerated>false</ac:enumerated>\n" +
                "\t\t\t\t<ac:defaultValue/>\n" +
                "\t\t\t\t<ac:validationRegEx>^[0-9]*$</ac:validationRegEx>\n" +
                "\t\t\t\t<ac:arrayName/>\n" +
                "\t\t\t\t<ac:arrayLength>0</ac:arrayLength>\n" +
                "\t\t\t\t<ac:exampleFormat/>\n" +
                "\t\t\t\t<ac:enumeratedValues/>\n" +
                "\t\t\t</ac:productFieldInfo>\n" +
                "\t\t</ac:getFieldsForProductResponse>\n" +
                "\t</soapenv:Body>\n" +
                "</soapenv:Envelope>";
    }

    @Override
    public String receiveValidationSuccess() {
        return "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
                "<soapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:SOAP-ENV=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\n" +
                "\t<SOAP-ENV:Header/>\n" +
                "\t<soapenv:Body xmlns:ac=\"http://www.moneygram.com/AgentConnect1512\">\n" +
                "\t\t<ac:receiveValidationResponse>\n" +
                "\t\t\t<ac:doCheckIn>false</ac:doCheckIn>\n" +
                "\t\t\t<ac:timeStamp>2023-02-13T11:16:53.144-06:00</ac:timeStamp>\n" +
                "\t\t\t<ac:flags>0</ac:flags>\n" +
                "\t\t\t<ac:mgiTransactionSessionID>432939131E1676306273485</ac:mgiTransactionSessionID>\n" +
                "\t\t\t<ac:readyForCommit>true</ac:readyForCommit>\n" +
                "\t\t</ac:receiveValidationResponse>\n" +
                "\t</soapenv:Body>\n" +
                "</soapenv:Envelope>";
    }

    @Override
    public String receiveCommitSuccess() {
        return "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
                "<soapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:SOAP-ENV=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\n" +
                "\t<SOAP-ENV:Header/>\n" +
                "\t<soapenv:Body xmlns:ac=\"http://www.moneygram.com/AgentConnect1512\">\n" +
                "\t\t<ac:commitTransactionResponse>\n" +
                "\t\t\t<ac:doCheckIn>false</ac:doCheckIn>\n" +
                "\t\t\t<ac:timeStamp>2023-02-13T11:17:02.140-06:00</ac:timeStamp>\n" +
                "\t\t\t<ac:flags>0</ac:flags>\n" +
                "\t\t\t<ac:referenceNumber>47795973</ac:referenceNumber>\n" +
                "\t\t\t<ac:expectedDateOfDelivery>2023-02-10</ac:expectedDateOfDelivery>\n" +
                "\t\t\t<ac:transactionDateTime>2023-02-13T11:17:02.140-06:00</ac:transactionDateTime>\n" +
                "\t\t</ac:commitTransactionResponse>\n" +
                "\t</soapenv:Body>\n" +
                "</soapenv:Envelope>";
    }
}
