package com.equitybank.gag.dummy_telco_b2c_ms.service.impl;

import java.math.BigDecimal;

public class Test {
    public static void main (String[] args) {
        String responseXml = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
                "<soapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:SOAP-ENV=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\n" +
                "\t<SOAP-ENV:Header/>\n" +
                "\t<soapenv:Body xmlns:ac=\"http://www.moneygram.com/AgentConnect1512\">\n" +
                "\t\t<ac:feeLookupResponse>\n" +
                "\t\t\t<ac:doCheckIn>false</ac:doCheckIn>\n" +
                "\t\t\t<ac:timeStamp>2023-02-13T02:13:19.114-06:00</ac:timeStamp>\n" +
                "\t\t\t<ac:flags>0</ac:flags>\n" +
                "\t\t\t<ac:feeInfo>\n" +
                "\t\t\t\t<ac:validReceiveAmount>320.00</ac:validReceiveAmount>\n" +
                "\t\t\t\t<ac:validReceiveCurrency>USD</ac:validReceiveCurrency>\n" +
                "\t\t\t\t<ac:validExchangeRate>1.000000</ac:validExchangeRate>\n" +
                "\t\t\t\t<ac:estimatedReceiveAmount>0</ac:estimatedReceiveAmount>\n" +
                "\t\t\t\t<ac:estimatedExchangeRate>0.000000</ac:estimatedExchangeRate>\n" +
                "\t\t\t\t<ac:totalAmount>325.81</ac:totalAmount>\n" +
                "\t\t\t\t<ac:receiveCountry>POL</ac:receiveCountry>\n" +
                "\t\t\t\t<ac:deliveryOption>WILL_CALL</ac:deliveryOption>\n" +
                "\t\t\t\t<ac:receiveAmountAltered>false</ac:receiveAmountAltered>\n" +
                "\t\t\t\t<ac:revisedInformationalFee>false</ac:revisedInformationalFee>\n" +
                "\t\t\t\t<ac:deliveryOptId>0</ac:deliveryOptId>\n" +
                "\t\t\t\t<ac:deliveryOptDisplayName>10 Minute Service</ac:deliveryOptDisplayName>\n" +
                "\t\t\t\t<ac:mgiTransactionSessionID>1677371E1676275999270844798473NN</ac:mgiTransactionSessionID>\n" +
                "\t\t\t\t<ac:sendAmountAltered>false</ac:sendAmountAltered>\n" +
                "\t\t\t\t<ac:sendAmounts>\n" +
                "\t\t\t\t\t<ac:sendAmount>320.00</ac:sendAmount>\n" +
                "\t\t\t\t\t<ac:sendCurrency>USD</ac:sendCurrency>\n" +
                "\t\t\t\t\t<ac:totalSendFees>5.00</ac:totalSendFees>\n" +
                "\t\t\t\t\t<ac:totalDiscountAmount>0.00</ac:totalDiscountAmount>\n" +
                "\t\t\t\t\t<ac:totalSendTaxes>0.81</ac:totalSendTaxes>\n" +
                "\t\t\t\t\t<ac:totalAmountToCollect>325.81</ac:totalAmountToCollect>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiNonDiscountedSendFee</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>discountedMgiSendFee</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>totalMgiCollectedFeesAndTaxes</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>totalNonDiscountedFees</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>totalAmountToMgi</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>325.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>totalSendFeesAndTaxes</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.81</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>originalMgiSendFeeInclTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiCountrySendFeeTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiStateSendFeeTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiCountyCitySendFeeTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiTotalSendFeeTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>totalNonMgiSendFeesAndTaxes</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.81</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiSendFaceTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiSendTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>nonMgiSendTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.81</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>nonMgiSendFee</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t</ac:sendAmounts>\n" +
                "\t\t\t\t<ac:receiveAmounts>\n" +
                "\t\t\t\t\t<ac:receiveAmount>320.00</ac:receiveAmount>\n" +
                "\t\t\t\t\t<ac:receiveCurrency>USD</ac:receiveCurrency>\n" +
                "\t\t\t\t\t<ac:validCurrencyIndicator>true</ac:validCurrencyIndicator>\n" +
                "\t\t\t\t\t<ac:payoutCurrency>USD</ac:payoutCurrency>\n" +
                "\t\t\t\t\t<ac:totalReceiveFees>0.00</ac:totalReceiveFees>\n" +
                "\t\t\t\t\t<ac:totalReceiveTaxes>0.00</ac:totalReceiveTaxes>\n" +
                "\t\t\t\t\t<ac:totalReceiveAmount>320.00</ac:totalReceiveAmount>\n" +
                "\t\t\t\t\t<ac:receiveFeesAreEstimated>false</ac:receiveFeesAreEstimated>\n" +
                "\t\t\t\t\t<ac:receiveTaxesAreEstimated>false</ac:receiveTaxesAreEstimated>\n" +
                "\t\t\t\t\t<ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiReceiveFee</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t<ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>nonMgiReceiveFee</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t<ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiReceiveTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t<ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>nonMgiReceiveTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t</ac:receiveAmounts>\n" +
                "\t\t\t</ac:feeInfo>\n" +
                "\t\t\t<ac:feeInfo>\n" +
                "\t\t\t\t<ac:validReceiveAmount>1410.81</ac:validReceiveAmount>\n" +
                "\t\t\t\t<ac:validReceiveCurrency>PLN</ac:validReceiveCurrency>\n" +
                "\t\t\t\t<ac:validExchangeRate>4.408767</ac:validExchangeRate>\n" +
                "\t\t\t\t<ac:estimatedReceiveAmount>0</ac:estimatedReceiveAmount>\n" +
                "\t\t\t\t<ac:estimatedExchangeRate>0.000000</ac:estimatedExchangeRate>\n" +
                "\t\t\t\t<ac:totalAmount>325.81</ac:totalAmount>\n" +
                "\t\t\t\t<ac:receiveCountry>POL</ac:receiveCountry>\n" +
                "\t\t\t\t<ac:deliveryOption>WILL_CALL</ac:deliveryOption>\n" +
                "\t\t\t\t<ac:receiveAmountAltered>false</ac:receiveAmountAltered>\n" +
                "\t\t\t\t<ac:revisedInformationalFee>false</ac:revisedInformationalFee>\n" +
                "\t\t\t\t<ac:deliveryOptId>0</ac:deliveryOptId>\n" +
                "\t\t\t\t<ac:deliveryOptDisplayName>10 Minute Service</ac:deliveryOptDisplayName>\n" +
                "\t\t\t\t<ac:mgiTransactionSessionID>1677371E1676275999270400787383NN</ac:mgiTransactionSessionID>\n" +
                "\t\t\t\t<ac:sendAmountAltered>false</ac:sendAmountAltered>\n" +
                "\t\t\t\t<ac:sendAmounts>\n" +
                "\t\t\t\t\t<ac:sendAmount>320.00</ac:sendAmount>\n" +
                "\t\t\t\t\t<ac:sendCurrency>USD</ac:sendCurrency>\n" +
                "\t\t\t\t\t<ac:totalSendFees>5.00</ac:totalSendFees>\n" +
                "\t\t\t\t\t<ac:totalDiscountAmount>0.00</ac:totalDiscountAmount>\n" +
                "\t\t\t\t\t<ac:totalSendTaxes>0.81</ac:totalSendTaxes>\n" +
                "\t\t\t\t\t<ac:totalAmountToCollect>325.81</ac:totalAmountToCollect>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiNonDiscountedSendFee</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>discountedMgiSendFee</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>totalMgiCollectedFeesAndTaxes</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>totalNonDiscountedFees</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>totalAmountToMgi</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>325.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>totalSendFeesAndTaxes</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.81</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>originalMgiSendFeeInclTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiCountrySendFeeTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiStateSendFeeTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiCountyCitySendFeeTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiTotalSendFeeTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>totalNonMgiSendFeesAndTaxes</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.81</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiSendFaceTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiSendTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>nonMgiSendTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.81</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>nonMgiSendFee</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t</ac:sendAmounts>\n" +
                "\t\t\t\t<ac:receiveAmounts>\n" +
                "\t\t\t\t\t<ac:receiveAmount>1410.81</ac:receiveAmount>\n" +
                "\t\t\t\t\t<ac:receiveCurrency>PLN</ac:receiveCurrency>\n" +
                "\t\t\t\t\t<ac:validCurrencyIndicator>true</ac:validCurrencyIndicator>\n" +
                "\t\t\t\t\t<ac:payoutCurrency>PLN</ac:payoutCurrency>\n" +
                "\t\t\t\t\t<ac:totalReceiveFees>0.00</ac:totalReceiveFees>\n" +
                "\t\t\t\t\t<ac:totalReceiveTaxes>0.00</ac:totalReceiveTaxes>\n" +
                "\t\t\t\t\t<ac:totalReceiveAmount>1410.81</ac:totalReceiveAmount>\n" +
                "\t\t\t\t\t<ac:receiveFeesAreEstimated>false</ac:receiveFeesAreEstimated>\n" +
                "\t\t\t\t\t<ac:receiveTaxesAreEstimated>false</ac:receiveTaxesAreEstimated>\n" +
                "\t\t\t\t\t<ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiReceiveFee</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>PLN</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t<ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>nonMgiReceiveFee</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>PLN</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t<ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiReceiveTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>PLN</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t<ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>nonMgiReceiveTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>PLN</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t</ac:receiveAmounts>\n" +
                "\t\t\t</ac:feeInfo>\n" +
                "\t\t\t<ac:feeInfo>\n" +
                "\t\t\t\t<ac:validReceiveAmount>295.94</ac:validReceiveAmount>\n" +
                "\t\t\t\t<ac:validReceiveCurrency>EUR</ac:validReceiveCurrency>\n" +
                "\t\t\t\t<ac:validExchangeRate>0.924801</ac:validExchangeRate>\n" +
                "\t\t\t\t<ac:estimatedReceiveAmount>0</ac:estimatedReceiveAmount>\n" +
                "\t\t\t\t<ac:estimatedExchangeRate>0.000000</ac:estimatedExchangeRate>\n" +
                "\t\t\t\t<ac:totalAmount>325.81</ac:totalAmount>\n" +
                "\t\t\t\t<ac:receiveCountry>POL</ac:receiveCountry>\n" +
                "\t\t\t\t<ac:deliveryOption>WILL_CALL</ac:deliveryOption>\n" +
                "\t\t\t\t<ac:receiveAmountAltered>false</ac:receiveAmountAltered>\n" +
                "\t\t\t\t<ac:revisedInformationalFee>false</ac:revisedInformationalFee>\n" +
                "\t\t\t\t<ac:deliveryOptId>0</ac:deliveryOptId>\n" +
                "\t\t\t\t<ac:deliveryOptDisplayName>10 Minute Service</ac:deliveryOptDisplayName>\n" +
                "\t\t\t\t<ac:mgiTransactionSessionID>1677371E1676275999270501203694NN</ac:mgiTransactionSessionID>\n" +
                "\t\t\t\t<ac:sendAmountAltered>false</ac:sendAmountAltered>\n" +
                "\t\t\t\t<ac:sendAmounts>\n" +
                "\t\t\t\t\t<ac:sendAmount>320.00</ac:sendAmount>\n" +
                "\t\t\t\t\t<ac:sendCurrency>USD</ac:sendCurrency>\n" +
                "\t\t\t\t\t<ac:totalSendFees>5.00</ac:totalSendFees>\n" +
                "\t\t\t\t\t<ac:totalDiscountAmount>0.00</ac:totalDiscountAmount>\n" +
                "\t\t\t\t\t<ac:totalSendTaxes>0.81</ac:totalSendTaxes>\n" +
                "\t\t\t\t\t<ac:totalAmountToCollect>325.81</ac:totalAmountToCollect>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiNonDiscountedSendFee</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>discountedMgiSendFee</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>totalMgiCollectedFeesAndTaxes</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>totalNonDiscountedFees</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>totalAmountToMgi</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>325.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>totalSendFeesAndTaxes</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.81</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>originalMgiSendFeeInclTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiCountrySendFeeTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiStateSendFeeTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiCountyCitySendFeeTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiTotalSendFeeTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>totalNonMgiSendFeesAndTaxes</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.81</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiSendFaceTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiSendTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>nonMgiSendTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.81</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>nonMgiSendFee</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t</ac:sendAmounts>\n" +
                "\t\t\t\t<ac:receiveAmounts>\n" +
                "\t\t\t\t\t<ac:receiveAmount>295.94</ac:receiveAmount>\n" +
                "\t\t\t\t\t<ac:receiveCurrency>EUR</ac:receiveCurrency>\n" +
                "\t\t\t\t\t<ac:validCurrencyIndicator>true</ac:validCurrencyIndicator>\n" +
                "\t\t\t\t\t<ac:payoutCurrency>EUR</ac:payoutCurrency>\n" +
                "\t\t\t\t\t<ac:totalReceiveFees>0.00</ac:totalReceiveFees>\n" +
                "\t\t\t\t\t<ac:totalReceiveTaxes>0.00</ac:totalReceiveTaxes>\n" +
                "\t\t\t\t\t<ac:totalReceiveAmount>295.94</ac:totalReceiveAmount>\n" +
                "\t\t\t\t\t<ac:receiveFeesAreEstimated>false</ac:receiveFeesAreEstimated>\n" +
                "\t\t\t\t\t<ac:receiveTaxesAreEstimated>false</ac:receiveTaxesAreEstimated>\n" +
                "\t\t\t\t\t<ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiReceiveFee</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>EUR</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t<ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>nonMgiReceiveFee</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>EUR</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t<ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiReceiveTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>EUR</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t<ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>nonMgiReceiveTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>EUR</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t</ac:receiveAmounts>\n" +
                "\t\t\t</ac:feeInfo>\n" +
                "\t\t\t<ac:feeInfo>\n" +
                "\t\t\t\t<ac:validReceiveAmount>1410.81</ac:validReceiveAmount>\n" +
                "\t\t\t\t<ac:validReceiveCurrency>PLN</ac:validReceiveCurrency>\n" +
                "\t\t\t\t<ac:validExchangeRate>4.408767</ac:validExchangeRate>\n" +
                "\t\t\t\t<ac:estimatedReceiveAmount>0</ac:estimatedReceiveAmount>\n" +
                "\t\t\t\t<ac:estimatedExchangeRate>0.000000</ac:estimatedExchangeRate>\n" +
                "\t\t\t\t<ac:totalAmount>325.81</ac:totalAmount>\n" +
                "\t\t\t\t<ac:receiveCountry>POL</ac:receiveCountry>\n" +
                "\t\t\t\t<ac:deliveryOption>BANK_DEPOSIT</ac:deliveryOption>\n" +
                "\t\t\t\t<ac:receiveAmountAltered>false</ac:receiveAmountAltered>\n" +
                "\t\t\t\t<ac:revisedInformationalFee>false</ac:revisedInformationalFee>\n" +
                "\t\t\t\t<ac:deliveryOptId>10</ac:deliveryOptId>\n" +
                "\t\t\t\t<ac:deliveryOptDisplayName>Account Deposit</ac:deliveryOptDisplayName>\n" +
                "\t\t\t\t<ac:receiveAgentID>70276929</ac:receiveAgentID>\n" +
                "\t\t\t\t<ac:receiveAgentName>BLUE MEDIA  EXPRESS</ac:receiveAgentName>\n" +
                "\t\t\t\t<ac:receiveAgentAbbreviation>EXPRESS</ac:receiveAgentAbbreviation>\n" +
                "\t\t\t\t<ac:mgManaged>required</ac:mgManaged>\n" +
                "\t\t\t\t<ac:mgiTransactionSessionID>1677371E1676275999270181151087NN</ac:mgiTransactionSessionID>\n" +
                "\t\t\t\t<ac:sendAmountAltered>false</ac:sendAmountAltered>\n" +
                "\t\t\t\t<ac:sendAmounts>\n" +
                "\t\t\t\t\t<ac:sendAmount>320.00</ac:sendAmount>\n" +
                "\t\t\t\t\t<ac:sendCurrency>USD</ac:sendCurrency>\n" +
                "\t\t\t\t\t<ac:totalSendFees>5.00</ac:totalSendFees>\n" +
                "\t\t\t\t\t<ac:totalDiscountAmount>0.00</ac:totalDiscountAmount>\n" +
                "\t\t\t\t\t<ac:totalSendTaxes>0.81</ac:totalSendTaxes>\n" +
                "\t\t\t\t\t<ac:totalAmountToCollect>325.81</ac:totalAmountToCollect>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiNonDiscountedSendFee</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>discountedMgiSendFee</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>totalMgiCollectedFeesAndTaxes</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>totalNonDiscountedFees</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>totalAmountToMgi</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>325.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>totalSendFeesAndTaxes</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.81</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>originalMgiSendFeeInclTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiCountrySendFeeTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiStateSendFeeTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiCountyCitySendFeeTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiTotalSendFeeTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>totalNonMgiSendFeesAndTaxes</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.81</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiSendFaceTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiSendTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>nonMgiSendTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.81</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>nonMgiSendFee</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t</ac:sendAmounts>\n" +
                "\t\t\t\t<ac:receiveAmounts>\n" +
                "\t\t\t\t\t<ac:receiveAmount>1410.81</ac:receiveAmount>\n" +
                "\t\t\t\t\t<ac:receiveCurrency>PLN</ac:receiveCurrency>\n" +
                "\t\t\t\t\t<ac:validCurrencyIndicator>true</ac:validCurrencyIndicator>\n" +
                "\t\t\t\t\t<ac:payoutCurrency>PLN</ac:payoutCurrency>\n" +
                "\t\t\t\t\t<ac:totalReceiveFees>0.00</ac:totalReceiveFees>\n" +
                "\t\t\t\t\t<ac:totalReceiveTaxes>0.00</ac:totalReceiveTaxes>\n" +
                "\t\t\t\t\t<ac:totalReceiveAmount>1410.81</ac:totalReceiveAmount>\n" +
                "\t\t\t\t\t<ac:receiveFeesAreEstimated>false</ac:receiveFeesAreEstimated>\n" +
                "\t\t\t\t\t<ac:receiveTaxesAreEstimated>false</ac:receiveTaxesAreEstimated>\n" +
                "\t\t\t\t\t<ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiReceiveFee</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>PLN</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t<ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>nonMgiReceiveFee</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>PLN</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t<ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiReceiveTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>PLN</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t<ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>nonMgiReceiveTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>PLN</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t</ac:receiveAmounts>\n" +
                "\t\t\t</ac:feeInfo>\n" +
                "\t\t\t<ac:feeInfo>\n" +
                "\t\t\t\t<ac:validReceiveAmount>1410.81</ac:validReceiveAmount>\n" +
                "\t\t\t\t<ac:validReceiveCurrency>PLN</ac:validReceiveCurrency>\n" +
                "\t\t\t\t<ac:validExchangeRate>4.408767</ac:validExchangeRate>\n" +
                "\t\t\t\t<ac:estimatedReceiveAmount>0</ac:estimatedReceiveAmount>\n" +
                "\t\t\t\t<ac:estimatedExchangeRate>0.000000</ac:estimatedExchangeRate>\n" +
                "\t\t\t\t<ac:totalAmount>325.81</ac:totalAmount>\n" +
                "\t\t\t\t<ac:receiveCountry>POL</ac:receiveCountry>\n" +
                "\t\t\t\t<ac:deliveryOption>BANK_DEPOSIT</ac:deliveryOption>\n" +
                "\t\t\t\t<ac:receiveAmountAltered>false</ac:receiveAmountAltered>\n" +
                "\t\t\t\t<ac:revisedInformationalFee>false</ac:revisedInformationalFee>\n" +
                "\t\t\t\t<ac:deliveryOptId>10</ac:deliveryOptId>\n" +
                "\t\t\t\t<ac:deliveryOptDisplayName>Account Deposit</ac:deliveryOptDisplayName>\n" +
                "\t\t\t\t<ac:receiveAgentID>70276932</ac:receiveAgentID>\n" +
                "\t\t\t\t<ac:receiveAgentName>BLUE MEDIA STANDARD</ac:receiveAgentName>\n" +
                "\t\t\t\t<ac:receiveAgentAbbreviation>STANDARD</ac:receiveAgentAbbreviation>\n" +
                "\t\t\t\t<ac:mgManaged>required</ac:mgManaged>\n" +
                "\t\t\t\t<ac:mgiTransactionSessionID>1677371E1676275999270901506117NN</ac:mgiTransactionSessionID>\n" +
                "\t\t\t\t<ac:sendAmountAltered>false</ac:sendAmountAltered>\n" +
                "\t\t\t\t<ac:sendAmounts>\n" +
                "\t\t\t\t\t<ac:sendAmount>320.00</ac:sendAmount>\n" +
                "\t\t\t\t\t<ac:sendCurrency>USD</ac:sendCurrency>\n" +
                "\t\t\t\t\t<ac:totalSendFees>5.00</ac:totalSendFees>\n" +
                "\t\t\t\t\t<ac:totalDiscountAmount>0.00</ac:totalDiscountAmount>\n" +
                "\t\t\t\t\t<ac:totalSendTaxes>0.81</ac:totalSendTaxes>\n" +
                "\t\t\t\t\t<ac:totalAmountToCollect>325.81</ac:totalAmountToCollect>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiNonDiscountedSendFee</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>discountedMgiSendFee</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>totalMgiCollectedFeesAndTaxes</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>totalNonDiscountedFees</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>totalAmountToMgi</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>325.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>totalSendFeesAndTaxes</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.81</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>originalMgiSendFeeInclTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiCountrySendFeeTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiStateSendFeeTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiCountyCitySendFeeTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiTotalSendFeeTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>totalNonMgiSendFeesAndTaxes</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.81</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiSendFaceTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiSendTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>nonMgiSendTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.81</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>nonMgiSendFee</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t</ac:sendAmounts>\n" +
                "\t\t\t\t<ac:receiveAmounts>\n" +
                "\t\t\t\t\t<ac:receiveAmount>1410.81</ac:receiveAmount>\n" +
                "\t\t\t\t\t<ac:receiveCurrency>PLN</ac:receiveCurrency>\n" +
                "\t\t\t\t\t<ac:validCurrencyIndicator>true</ac:validCurrencyIndicator>\n" +
                "\t\t\t\t\t<ac:payoutCurrency>PLN</ac:payoutCurrency>\n" +
                "\t\t\t\t\t<ac:totalReceiveFees>0.00</ac:totalReceiveFees>\n" +
                "\t\t\t\t\t<ac:totalReceiveTaxes>0.00</ac:totalReceiveTaxes>\n" +
                "\t\t\t\t\t<ac:totalReceiveAmount>1410.81</ac:totalReceiveAmount>\n" +
                "\t\t\t\t\t<ac:receiveFeesAreEstimated>false</ac:receiveFeesAreEstimated>\n" +
                "\t\t\t\t\t<ac:receiveTaxesAreEstimated>false</ac:receiveTaxesAreEstimated>\n" +
                "\t\t\t\t\t<ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiReceiveFee</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>PLN</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t<ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>nonMgiReceiveFee</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>PLN</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t<ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiReceiveTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>PLN</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t<ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>nonMgiReceiveTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>PLN</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t</ac:receiveAmounts>\n" +
                "\t\t\t</ac:feeInfo>\n" +
                "\t\t\t<ac:feeInfo>\n" +
                "\t\t\t\t<ac:validReceiveAmount>295.94</ac:validReceiveAmount>\n" +
                "\t\t\t\t<ac:validReceiveCurrency>EUR</ac:validReceiveCurrency>\n" +
                "\t\t\t\t<ac:validExchangeRate>0.924801</ac:validExchangeRate>\n" +
                "\t\t\t\t<ac:estimatedReceiveAmount>0</ac:estimatedReceiveAmount>\n" +
                "\t\t\t\t<ac:estimatedExchangeRate>0.000000</ac:estimatedExchangeRate>\n" +
                "\t\t\t\t<ac:totalAmount>325.81</ac:totalAmount>\n" +
                "\t\t\t\t<ac:receiveCountry>POL</ac:receiveCountry>\n" +
                "\t\t\t\t<ac:deliveryOption>BANK_DEPOSIT</ac:deliveryOption>\n" +
                "\t\t\t\t<ac:receiveAmountAltered>false</ac:receiveAmountAltered>\n" +
                "\t\t\t\t<ac:revisedInformationalFee>false</ac:revisedInformationalFee>\n" +
                "\t\t\t\t<ac:deliveryOptId>10</ac:deliveryOptId>\n" +
                "\t\t\t\t<ac:deliveryOptDisplayName>Account Deposit</ac:deliveryOptDisplayName>\n" +
                "\t\t\t\t<ac:receiveAgentID>70552740</ac:receiveAgentID>\n" +
                "\t\t\t\t<ac:receiveAgentName>WORLDPAY</ac:receiveAgentName>\n" +
                "\t\t\t\t<ac:receiveAgentAbbreviation>STANDARD</ac:receiveAgentAbbreviation>\n" +
                "\t\t\t\t<ac:mgManaged>required</ac:mgManaged>\n" +
                "\t\t\t\t<ac:mgiTransactionSessionID>1677371E1676275999270142658743NN</ac:mgiTransactionSessionID>\n" +
                "\t\t\t\t<ac:sendAmountAltered>false</ac:sendAmountAltered>\n" +
                "\t\t\t\t<ac:sendAmounts>\n" +
                "\t\t\t\t\t<ac:sendAmount>320.00</ac:sendAmount>\n" +
                "\t\t\t\t\t<ac:sendCurrency>USD</ac:sendCurrency>\n" +
                "\t\t\t\t\t<ac:totalSendFees>5.00</ac:totalSendFees>\n" +
                "\t\t\t\t\t<ac:totalDiscountAmount>0.00</ac:totalDiscountAmount>\n" +
                "\t\t\t\t\t<ac:totalSendTaxes>0.81</ac:totalSendTaxes>\n" +
                "\t\t\t\t\t<ac:totalAmountToCollect>325.81</ac:totalAmountToCollect>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiNonDiscountedSendFee</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>discountedMgiSendFee</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>totalMgiCollectedFeesAndTaxes</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>totalNonDiscountedFees</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>totalAmountToMgi</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>325.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>totalSendFeesAndTaxes</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.81</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>originalMgiSendFeeInclTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>5.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiCountrySendFeeTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiStateSendFeeTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiCountyCitySendFeeTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiTotalSendFeeTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>totalNonMgiSendFeesAndTaxes</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.81</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiSendFaceTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiSendTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>nonMgiSendTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.81</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t\t<ac:detailSendAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>nonMgiSendFee</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>USD</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailSendAmounts>\n" +
                "\t\t\t\t</ac:sendAmounts>\n" +
                "\t\t\t\t<ac:receiveAmounts>\n" +
                "\t\t\t\t\t<ac:receiveAmount>295.94</ac:receiveAmount>\n" +
                "\t\t\t\t\t<ac:receiveCurrency>EUR</ac:receiveCurrency>\n" +
                "\t\t\t\t\t<ac:validCurrencyIndicator>true</ac:validCurrencyIndicator>\n" +
                "\t\t\t\t\t<ac:payoutCurrency>EUR</ac:payoutCurrency>\n" +
                "\t\t\t\t\t<ac:totalReceiveFees>0.00</ac:totalReceiveFees>\n" +
                "\t\t\t\t\t<ac:totalReceiveTaxes>0.00</ac:totalReceiveTaxes>\n" +
                "\t\t\t\t\t<ac:totalReceiveAmount>295.94</ac:totalReceiveAmount>\n" +
                "\t\t\t\t\t<ac:receiveFeesAreEstimated>false</ac:receiveFeesAreEstimated>\n" +
                "\t\t\t\t\t<ac:receiveTaxesAreEstimated>false</ac:receiveTaxesAreEstimated>\n" +
                "\t\t\t\t\t<ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiReceiveFee</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>EUR</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t<ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>nonMgiReceiveFee</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>EUR</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t<ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>mgiReceiveTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>EUR</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t<ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t\t\t<ac:amountType>nonMgiReceiveTax</ac:amountType>\n" +
                "\t\t\t\t\t\t<ac:amount>0.00</ac:amount>\n" +
                "\t\t\t\t\t\t<ac:amountCurrency>EUR</ac:amountCurrency>\n" +
                "\t\t\t\t\t</ac:detailEstimatedReceiveAmounts>\n" +
                "\t\t\t\t</ac:receiveAmounts>\n" +
                "\t\t\t</ac:feeInfo>\n" +
                "\t\t</ac:feeLookupResponse>\n" +
                "\t</soapenv:Body>\n" +
                "</soapenv:Envelope>";

        // Get tag values
        String sendAmount = extractValue(responseXml, "<ac:sendAmount>", "</ac:sendAmount>", "<sendAmount>", "</sendAmount>");
        String sendCurrency = extractValue(responseXml, "<ac:sendCurrency>", "</ac:sendCurrency>", "<sendCurrency>", "</sendCurrency>");
        String totalAmountToCollect = extractValue(responseXml, "<ac:totalAmountToCollect>", "</ac:totalAmountToCollect>", "<totalAmountToCollect>", "</totalAmountToCollect>");

        System.out.println("sendAmount: " + sendAmount);
        System.out.println("sendCurrency: " + sendCurrency);
        System.out.println("totalAmountToCollect: " + totalAmountToCollect);
        System.out.println("totalFeeAndTaxes: " + calculateFees(sendAmount, totalAmountToCollect));
    }

    private static String calculateFees(String sendAmount, String totalAmountToCollect) {
        BigDecimal sendAmountB = new BigDecimal(sendAmount);
        BigDecimal totalAmountToCollectB = new BigDecimal(totalAmountToCollect);

        // Calculate the difference
        BigDecimal difference = totalAmountToCollectB.subtract(sendAmountB);

        // Return the difference as a string
        return difference.toString();
    }

    private static String extractValue(String xml, String startTag1, String endTag1, String startTag2, String endTag2) {
        int start = xml.indexOf(startTag1);
        int end = xml.indexOf(endTag1, start);
        int tagLength;

        // If the first tag set is not found, try the second set
        if (start == -1 || end == -1) {
            start = xml.indexOf(startTag2);
            end = xml.indexOf(endTag2, start);
            tagLength = startTag2.length();
        } else {
            tagLength = startTag1.length();
        }

        // If any of the tags are found, extract the value
        if (start != -1 && end != -1) {
            return xml.substring(start + tagLength, end).trim();
        }

        return null;
    }
}
