
#SPRING JPA
#spring.jpa.database=mysql
#spring.jpa.properties.hibernate.hbm2ddl.auto=update
spring.jpa.properties.hibernate.jdbc.batch_size = 50
spring.jpa.properties.hibernate.order_inserts = true
##Show SQL
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.format_sql=true
#
###SPRING DATA SOURCE
spring.datasource.url=${CD_SPRING_DATASOURCE_URL}
spring.datasource.username=${CD_SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${CD_SPRING_DATASOURCE_PASSWORD}
spring.datasource.driverClassName=oracle.jdbc.OracleDriver

spring.datasource.testOnBorrow=true
spring.datasource.validationQuery=SELECT 1 FROM DUAL
spring.hikari.poolName=Hikari
spring.hikari.auto-commit=false

airtel.cd.openapi.kyc.url=${CD_AIRTEL_B2C_KYC_URL}
airtel.cd.openapi.disbursement.url=${CD_AIRTEL_B2C_DISBURSEMENT_URL}
airtel.cd.openapi.token.url=${CD_AIRTEL_B2C_TOKEN_URL}
airtel.cd.openapi.statusCheck.url=${CD_AIRTEL_B2C_STATUS_CHECK_URL}
airtel.cd.openapi.token.consumerKey=${CD_AIRTEL_B2C_CONSUMERKEY}
airtel.cd.openapi.token.consumerSecret=${CD_AIRTEL_B2C_CONSUMERSECRET}
airtel.cd.openapi.hostHeader=${CD_AIRTEL_B2C_HOST_HEADER}

airtel.cd.openapi.allocation.kycURL=${CD_AIRTEL_FLOAT_PURCHASE_KYC_URL}
airtel.cd.openapi.allocation.allocation.url=${CD_AIRTEL_FLOAT_PURCHASE_DISBURSEMENT_URL}
airtel.cd.openapi.allocation.token.url=${CD_AIRTEL_FLOAT_PURCHASE_TOKEN_URL}
airtel.cd.openapi.allocation.statusCheckURL=${CD_AIRTEL_FLOAT_PURCHASE_STATUS_CHECK_URL}
airtel.cd.openapi.allocation.encConsumerKey=${CD_AIRTEL_FLOAT_PURCHASE_CONSUMERKEY}
airtel.cd.openapi.allocation.encConsumerSecret=${CD_AIRTEL_FLOAT_PURCHASE_CONSUMERSECRET}
airtel.cd.openapi.allocation.hostHeader=${CD_AIRTEL_B2C_HOST_HEADER}
airtel.cd.openapi.encryption.key=${CD_AIRTEL_OPENAPI_ENCRYPTION_KEY}

airtel.ke.openapi.allocation.kycURL=${KE_AIRTEL_FLOAT_PURCHASE_KYC_URL}
airtel.ke.openapi.allocation.allocation.url=${KE_AIRTEL_FLOAT_PURCHASE_DISBURSEMENT_URL}
airtel.ke.openapi.allocation.token.url=${KE_AIRTEL_FLOAT_PURCHASE_TOKEN_URL}
airtel.ke.openapi.allocation.statusCheckURL=${KE_AIRTEL_FLOAT_PURCHASE_STATUS_CHECK_URL}
airtel.ke.openapi.allocation.encConsumerKey=${KE_AIRTEL_FLOAT_PURCHASE_CONSUMERKEY}
airtel.ke.openapi.allocation.encConsumerSecret=${KE_AIRTEL_FLOAT_PURCHASE_CONSUMERSECRET}
airtel.ke.openapi.allocation.hostHeader=${KE_AIRTEL_B2C_HOST_HEADER}
airtel.ke.openapi.encryption.key=${KE_AIRTEL_OPENAPI_ENCRYPTION_KEY}


airtel.cd.airtime.pin=${CD_AIRTEL_AIRTIME_PURCHASE_PIN}
airtel.cd.airtime.channelMsisdn=${CD_AIRTEL_AIRTIME_PURCHASE_CHANNEL_MSISDN}
airtel.cd.airtime.password=${CD_AIRTEL_AIRTIME_PURCHASE_PASSWORD}
airtel.cd.airtime.extCode=${CD_AIRTEL_AIRTIME_PURCHASE_EXTCODE}
airtel.cd.airtime.loginId=${CD_AIRTEL_AIRTIME_PURCHASE_LOGINID}
airtel.cd.airtime.requestURL=${CD_AIRTEL_AIRTIME_PURCHASE_REQUEST_URL}
airtel.cd.airtime.whiteList=0986676678,2437000000
airtel.cd.airtime.limit.USD=1.5
airtel.cd.airtime.limit.CDF=3000

airtel.cd.airtime.LOGIN=${CD_AIRTEL_AIRTIME_PURCHASE_URL_LOGIN}
airtel.cd.airtime.PASSWORD=${CD_AIRTEL_AIRTIME_PURCHASE_URL_PASSWORD}
airtel.cd.airtime.REQUEST_GATEWAY_CODE=${CD_AIRTEL_AIRTIME_PURCHASE_REQUEST_GATEWAY_CODE}
airtel.cd.airtime.REQUEST_GATEWAY_TYPE=${CD_AIRTEL_AIRTIME_PURCHASE_URL_REQUEST_GATEWAY_TYPE}
airtel.cd.airtime.SOURCE_TYPE=${CD_AIRTEL_AIRTIME_PURCHASE_URL_SOURCE_TYPE}
airtel.cd.airtime.SERVICE_PORT=${CD_AIRTEL_AIRTIME_PURCHASE_URL_SERVICE_PORT}

service.activation.airtime=true
service.activation.b2c=true

airtel.cd.b2c.mock.scenario.login=success
airtel.cd.b2c.mock.scenario.disbursement=success
airtel.cd.airtime.mock.scenario.buy=success
#EUREKA
eureka.client.enabled=true
eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=http://localhost:8581/eureka/