spring:
  application:
    name: papss-middleware-service
  datasource:
    url: ${PAPSS_DB_URL:jdbc:oracle:thin:@//localhost:1521/XEPDB1}
    username: ${PAPSS_DB_USERNAME:papss}
    password: ${PAPSS_DB_PASSWORD:papss}
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      pool-name: HikariCP
      auto-commit: false
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      leak-detection-threshold: 5000
      initialization-fail-timeout: 1
      connection-test-query: SELECT 1 FROM DUAL
      data-source-properties:
        oracle.jdbc.defaultNChar: true
        oracle.jdbc.convertNcharLiterals: true
        oracle.jdbc.defaultNCharCharacterSet: AR8MSWIN1256
        oracle.jdbc.JavaCharSet: AR8MSWIN1256

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        boot.allow_jdbc_metadata_access: false
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: false
        jdbc.batch_size: 50
        order_inserts: true
        order_updates: true
        connection.provider_disables_autocommit: true
    open-in-view: false

logging:
  level:
    com.papss.middleware: INFO
    org.springframework.web.client.RestTemplate: INFO
    org.apache.http: INFO

# The rest of the configuration remains the same as in application.yml
papss:
  system:
    enableInbound: true
    enableOutbound: true
    pollingExecutorThreadDelay: 10000
    pollingExecutorThreadRate: 10000
    pollingExecutorsPerParticipant: 1
    pollingSleepTime: 5000
    toClearingSystemId: XA0001
    ipsBaseUrl: pm.test.papssnet.papss.com
    ipsPort: 443
core:
  banking:
    url: http://localhost:8082/papss-core-banking-mock-server
    path:
      credit-transfer: "/ft"
      name-inquiry: "/name-enquiry"
      recon: "/settlement-recon"
      tx-confirmation: "/txn-confirmation"