spring:
  application:
    name: papss-middleware-service
  datasource:
    url: jdbc:postgresql://localhost:5432/papssdb
    username: papss
    password: fg4rHwc7kkPQcqXv
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: HikariCP
      auto-commit: false
      maximum-pool-size: 10
      minimum-idle: 1
      initialization-fail-timeout: 1

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        boot.allow_jdbc_metadata_access: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        jdbc.batch_size: 50
        order_inserts: true
        order_updates: true
        connection.provider_disables_autocommit: true
    open-in-view: false


logging:
  level:
    com.papss.middleware: INFO
    com.papss.middleware.utils.HttpClient: INFO
    com.papss.middleware.service.KeyStoreService: INFO
    org.springframework.web.client.RestTemplate: INFO
#    org.apache.http: DEBUG
#    org.apache.hc: DEBUG
#    javax.net.ssl: DEBUG
#    sun.security.ssl: DEBUG

papss:
  participants:
    - apiKey: 706b3dac-21ca-4755-906f-841117db9eab
      country: AX
      inst_bic:
      inst_id: AX1012
      salt: supersecretsalt
      sslKeyAlias: onafriq
      keyStorePath: /Users/test/Documents/papss/papss-middleware-service/src/main/resources/keystore/ONAFRIQ.jks
      keyPass: secure
      keyStoreType: JKS
      provider: SunJCE

    - apiKey: 706b3dac-21ca-4755-906f-841117db9eab
      country: AX
      inst_bic:
      inst_id: AX1013
      salt: supersecretsalt
      sslKeyAlias: onafriq
      keyStorePath: /Users/test/Documents/papss/papss-middleware-service/src/main/resources/keystore/ONAFRIQ.jks
      keyPass: secure
      keyStoreType: JKS
      provider: SunJCE

    - apiKey: 706b3dac-21ca-4755-906f-841117db9eab
      country: AX
      inst_bic:
      inst_id: AX1016
      salt: supersecretsalt
      sslKeyAlias: onafriq
      keyStorePath: /Users/test/Documents/papss/papss-middleware-service/src/main/resources/keystore/ONAFRIQ.jks
      keyPass: secure
      keyStoreType: JKS
      provider: SunJCE

    - apiKey: 706b3dac-21ca-4755-906f-841117db9eab
      country: AX
      inst_bic:
      inst_id: AX1014
      salt: supersecretsalt
      sslKeyAlias: onafriq
      keyStorePath: /Users/test/Documents/papss/papss-middleware-service/src/main/resources/keystore/ONAFRIQ.jks
      keyPass: secure
      keyStoreType: JKS
      provider: SunJCE

  system:
    enableInbound: true
    enableOutbound: true
    pollingExecutorThreadDelay: 1000
    pollingExecutorThreadRate: 1000
    pollingExecutorsPerParticipant: 5
    toClearingSystemId: XA0001
    ipsBaseUrl: pm.test.papssnet.papss.com
#    ipsBaseUrl: 10.109.10.138
    ipsPort: 443
core:
  banking:
    url: http://localhost:8082/papss-core-banking-mock-server
    path:
      credit-transfer: "/ft"
      name-inquiry: "/name-enquiry"
      recon: "/settlement-recon"
      tx-confirmation: "/txn-confirmation"
      payment-return: "/payment-return"
