<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified"
           elementFormDefault="qualified">
    <xs:element name="participants" type="participantsType"/>
    <xs:complexType name="paymentschemasType" mixed="true">
        <xs:sequence>
            <xs:element type="xs:string" name="paymentschema" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="currenciesType" mixed="true">
        <xs:sequence>
            <xs:element type="xs:string" name="currency" maxOccurs="unbounded" minOccurs="0">
                <!--        <xs:simpleType>-->
                <!--          <xs:restriction base="xs:string">-->
                <!--            <xs:enumeration value="NGN"/>-->
                <!--            <xs:enumeration value="LRD"/>-->
                <!--            <xs:enumeration value="USD"/>-->
                <!--            <xs:enumeration value="GHS"/>-->
                <!--            <xs:enumeration value="GNF"/>-->
                <!--            <xs:enumeration value="SLE"/>-->
                <!--          </xs:restriction>-->
                <!--        </xs:simpleType>-->
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="participantType">
        <xs:sequence>
            <xs:element type="xs:string" name="bic"/>
            <xs:element type="xs:string" name="name"/>
            <xs:element type="xs:string" name="countryCode">
                <!--        <xs:simpleType>-->
                <!--          <xs:restriction base="xs:string">-->
                <!--            <xs:enumeration value="NG"/>-->
                <!--            <xs:enumeration value="LR"/>-->
                <!--            <xs:enumeration value="GH"/>-->
                <!--            <xs:enumeration value="GN"/>-->
                <!--            <xs:enumeration value="SL"/>-->
                <!--          </xs:restriction>-->
                <!--        </xs:simpleType>-->
            </xs:element>
            <xs:element type="xs:string" name="status"/>
            <xs:element type="paymentschemasType" name="paymentschemas"/>
            <xs:element type="currenciesType" name="currencies"/>
            <xs:element type="xs:string" name="online"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="papssId" use="optional"/>
    </xs:complexType>
    <xs:complexType name="participantsType">
        <xs:sequence>
            <xs:element type="participantType" name="participantInfoDto" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>
