Insert into CUSTOM.C_CPMASTER
   (MODULE_NAME, PARAMETER_LEVEL, PARAMETER_ID, PARAMETER_DESC, PARAMETER_TYPE, QUERY_ID, LIST_TYPE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID)
 Values
   ('OT', 'BNKL', 'COMM_VAT_PERCENT', 'VAT PERCENTAGE', 'AN', ' ', 'FT', 'Y', 'N', 'TBAADM', SYSDATE, 'TBAADM', SYSDATE, '43');
COMMIT;


Insert into CUSTOM.C_CPVALUE
   (PARAMETER_ID, LEVELCODE_1, PARAMETER_VALUE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID, MODULE_NAME)
 Values
   ('COMM_VAT_PERCENT', 'ALL', '16', 'Y', 'N', 'TBAADM', SYSDATE, 'TBAADM', SYSDATE, '43', 'OT');
COMMIT;

Insert into CUSTOM.C_CPMASTER
   (MODULE_NAME, PARAMETER_LEVEL, PARAMETER_ID, PARAMETER_DESC, PARAMETER_TYPE, QUERY_ID, LIST_TYPE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID)
 Values
   ('OT', 'BNKL', 'COMM_CHARGE_PERCENT', 'COMMISSION CHARGE PERCENT FOR DAMAGE NOTES', 'AN', ' ', 'FT', 'Y', 'N', 'TBAADM', SYSDATE, 'TBAADM', SYSDATE, '43');
COMMIT;


Insert into CUSTOM.C_CPVALUE
   (PARAMETER_ID, LEVELCODE_1, PARAMETER_VALUE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID, MODULE_NAME)
 Values
   ('COMM_CHARGE_PERCENT', 'ALL', '0.3', 'Y', 'N', 'TBAADM', SYSDATE, 'TBAADM', SYSDATE, '43', 'OT');
COMMIT;

Insert into CUSTOM.C_CPMASTER
   (MODULE_NAME, PARAMETER_LEVEL, PARAMETER_ID, PARAMETER_DESC, PARAMETER_TYPE, QUERY_ID, LIST_TYPE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID)
 Values
   ('OT', 'BNKL', 'COMMISSION_BACID', 'COMMISSION BACID FOR DAMAGE NOTES', 'AN', ' ', 'FT', 'Y', 'N', 'TBAADM', SYSDATE, 'TBAADM', SYSDATE, '43');
COMMIT;


Insert into CUSTOM.C_CPVALUE
   (PARAMETER_ID, LEVELCODE_1, PARAMETER_VALUE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID, MODULE_NAME)
 Values
   ('COMMISSION_BACID', 'ALL', 'SOILNOTE', 'Y', 'N', 'TBAADM', SYSDATE, 'TBAADM', SYSDATE, '43', 'OT');
COMMIT;

Insert into CUSTOM.C_CPMASTER
   (MODULE_NAME, PARAMETER_LEVEL, PARAMETER_ID, PARAMETER_DESC, PARAMETER_TYPE, QUERY_ID, LIST_TYPE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID)
 Values
   ('OT', 'BNKL', 'COMMISSION_VAT_BACID', 'VAT BACID', 'AN', ' ', 'FT', 'Y', 'N', 'TBAADM', SYSDATE, 'TBAADM', SYSDATE, '43');
COMMIT;


Insert into CUSTOM.C_CPVALUE
   (PARAMETER_ID, LEVELCODE_1, PARAMETER_VALUE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID, MODULE_NAME)
 Values
   ('COMMISSION_VAT_BACID', 'ALL', 'VAT', 'Y', 'N', 'TBAADM', SYSDATE, 'TBAADM', SYSDATE, '43', 'OT');
COMMIT;
