--====================================================================================================
-- Table Name: CUST_SOURCE_OF_FUNDS_TRAN_TBL
-- Synonym Name : C_SFTT
-- Date: 30-JAN-2019
-- Description: This table is used for maintaining Source of Funds.
-- Author: Anshul_Singh04
-- Modification History :
--<Version No.> <Date> <Author Name> <Description>
--====================================================================================================

DROP TABLE CUSTOM.CUST_SOURCE_OF_FUNDS_TRAN_TBL CASCADE CONSTRAINTS;

CREATE TABLE CUSTOM.CUST_SOURCE_OF_FUNDS_TRAN_TBL
(
	TRAN_ID					VARCHAR2(9 CHAR),
	TRAN_DATE     			DATE,
	PART_TRAN_SRL_NUM		VARCHAR2(4 CHAR),
	SOURCE_ID				VARCHAR2(9 CHAR),
	COMMENTS 			    VARCHAR2(200 CHAR),
	RCRE_USER_ID       		VARCHAR2(15 CHAR),
	RCRE_TIME          		DATE,
	LCHG_USER_ID       		VARCHAR2(15 CHAR),
	LCHG_TIME          		DATE,
	BANK_ID            		VARCHAR2(8 CHAR)
);

DROP INDEX CUSTOM.IDX_SRC_FNDS_TRAN_TBL;

CREATE UNIQUE INDEX CUSTOM.IDX_SRC_FNDS_TRAN_TBL ON CUSTOM.CUST_SOURCE_OF_FUNDS_TRAN_TBL
(TRAN_ID,TRAN_DATE,PART_TRAN_SRL_NUM,BANK_ID);

DROP SYNONYM CUSTOM.C_SFTT;

CREATE SYNONYM CUSTOM.C_SFTT FOR CUSTOM.CUST_SOURCE_OF_FUNDS_TRAN_TBL;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.CUST_SOURCE_OF_FUNDS_TRAN_TBL TO TBAADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.CUST_SOURCE_OF_FUNDS_TRAN_TBL TO TBAGEN;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.CUST_SOURCE_OF_FUNDS_TRAN_TBL TO TBAUTIL;

