--====================================================================================================
-- Table Name: COMM_TRAN_DETAIL_TBL
-- Synonym Name : C_CPTD
-- Date: 8-June-2018
-- Description: This table is used for Capturing Commission Transactions
-- Author: Anshul_Singh04
-- Modification History :
--<Version No.> <Date> <Author Name> <Description>
--====================================================================================================

DROP TABLE CUSTOM.COMM_TRAN_DETAIL_TBL CASCADE CONSTRAINTS;

CREATE TABLE CUSTOM.COMM_TRAN_DETAIL_TBL
(
	TRAN_ID			   VARCHAR2(9 CHAR),
	TRAN_DATE     	   DATE,
	PAYMENT_TYPE	   CHAR(1 BYTE),
	TRAN_TYPE		   CHAR(1 BYTE),
	TRAN_SUB_TYPE	   VARCHAR2(2 CHAR),
	INIT_SOL_ID		   VARCHAR2(8 CHAR),
	COMM_CODE          VARCHAR2(15 CHAR),
	COMM_CRNCY_CODE    VARCHAR2(3 CHAR),
	COMM_AMT		   NUMBER(20,4),
	VAT_AMT			   NUMBER(20,4),
	DR_ACCT_ID		   VARCHAR2(16 CHAR),
	COMM_ACCT_ID 	   VARCHAR2(16 CHAR),
	VAT_ACCT_ID        VARCHAR2(16 CHAR),
	RATE_CODE		   VARCHAR2(5 CHAR),
	RATE			   NUMBER(21,10),
	PAYMENT_PURPOSE    VARCHAR2(50 CHAR),
	RCRE_USER_ID       VARCHAR2(15 CHAR),
	RCRE_TIME          DATE,
	BANK_ID            VARCHAR2(8 CHAR),
	TRAN_STATUS 	   CHAR (1 BYTE),
	REVERSAL_TRAN_ID   VARCHAR2(9 CHAR),
	REVERSAL_TRAN_DATE DATE,
	LCHG_USER_ID       VARCHAR2(15 CHAR),
	LCHG_TIME          DATE
);

CREATE UNIQUE INDEX CUSTOM.IDX_COMM_TRAN ON CUSTOM.COMM_TRAN_DETAIL_TBL
(TRAN_ID,TRAN_DATE,BANK_ID);

DROP SYNONYM CUSTOM.C_CPTD;

CREATE SYNONYM CUSTOM.C_CPTD FOR CUSTOM.COMM_TRAN_DETAIL_TBL;


GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.COMM_TRAN_DETAIL_TBL TO TBAADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.COMM_TRAN_DETAIL_TBL TO TBAGEN;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.COMM_TRAN_DETAIL_TBL TO TBAUTIL;
