insert into CUSTOM.C_CPMASTER (MODULE_NAME, PARAMETER_LEVEL, PARAMETER_ID, PARAMETER_DESC, PARAMETER_TYPE, QUERY_ID, LIST_TYPE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID) values ('OT', 'BNKL', 'DOC_EXP_VAL_EXCP', 'GL', 'AN', ' ', 'FT', 'Y', 'N', 'TBAADM', TO_DATE('2018-06-13 09:47:54', 'YYYY-MM-DD HH24:MI:SS'), 'TBAADM', TO_DATE('2018-06-13 09:47:54', 'YYYY-MM-DD HH24:MI:SS'), '43'); 
commit;

