Insert into CUSTOM.C_CPMASTER
   (MODULE_NAME, PARAMETER_LEVEL, PARAMETER_ID, PARAMETER_DESC, PARAMETER_TYPE, QUERY_ID, LIST_TYPE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID)
 Values
   ('OT', 'BNKL', 'CASHWD_CHRG_EVNT_ID', 'Charge EventId for Cash Withdrawal without Inst', 'AN', ' ', 'FT', 'Y', 'N', 'TBAADM', SYSDATE, 'TBAADM', SYSDATE, '43');

Insert into CUSTOM.C_CPVALUE
   (PARAMETER_ID, LEVELCODE_1, PARAMETER_VALUE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID, MODULE_NAME)
 Values
   ('CASHWD_CHRG_EVNT_ID', 'ALL', '', 'Y', 'N', 'TBAADM', SYSDATE, 'TBAADM', SYSDATE, '43', 'OT');
COMMIT;

Insert into CUSTOM.C_CPMASTER
   (MODULE_NAME, PARAMETER_LEVEL, PARAMETER_ID, PARAMETER_DESC, PARAMETER_TYPE, QUERY_ID, LIST_TYPE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID)
 Values
   ('OT', 'BNKL', 'CASHWD_INST_CHRG_EVNT_ID', 'Charge EventId for Cash Withdrawal with Instrument', 'AN', ' ', 'FT', 'Y', 'N', 'TBAADM', SYSDATE, 'TBAADM', SYSDATE, '43');

Insert into CUSTOM.C_CPVALUE
   (PARAMETER_ID, LEVELCODE_1, PARAMETER_VALUE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID, MODULE_NAME)
 Values
   ('CASHWD_INST_CHRG_EVNT_ID', 'ALL', '', 'Y', 'N', 'TBAADM', SYSDATE, 'TBAADM', SYSDATE, '43', 'OT');
COMMIT;

Insert into CUSTOM.C_CPMASTER
   (MODULE_NAME, PARAMETER_LEVEL, PARAMETER_ID, PARAMETER_DESC, PARAMETER_TYPE, QUERY_ID, LIST_TYPE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID)
 Values
   ('OT', 'BNKL', 'XFER_CHRG_EVNT_ID', 'Charge EventId for Transfer Txn', 'AN', ' ', 'FT', 'Y', 'N', 'TBAADM', SYSDATE, 'TBAADM', SYSDATE, '43');

Insert into CUSTOM.C_CPVALUE
   (PARAMETER_ID, LEVELCODE_1, PARAMETER_VALUE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID, MODULE_NAME)
 Values
   ('XFER_CHRG_EVNT_ID', 'ALL', '', 'Y', 'N', 'TBAADM', SYSDATE, 'TBAADM', SYSDATE, '43', 'OT');
COMMIT;
