<?xml version="1.0" encoding="UTF-8"?>
<!-- Montran Corporation 2017-2019 (RP) -->
<xs:schema xmlns="urn:montran:fxrateUpdate.001"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified" targetNamespace="urn:montran:fxrateUpdate.001">
    <xs:element name="fxRateUpdate">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="MmbId" type="Max35Text"/>
                <xs:element name="MsgId" type="Max35Text"/>
                <xs:element name="CreDt" type="ISONormalisedDateTime"/>
                <xs:element name="FxRate" type="FXRate"/>
                <xs:element name="Sgntr" type="SignatureEnvelope"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="FXRate">
        <xs:attribute name="name" type="Max35Text" />
        <xs:attribute name="localCurrency" type="ActiveCurrencyCode" />
        <xs:attribute name="accountType" type="Max35Text" />
        <xs:attribute name="countryCode" type="CountryCode" />
        <xs:attribute name="buyRate" type="Rate" />
        <xs:attribute name="sellRate" type="Rate" />
    </xs:complexType>

    <xs:complexType name="SignatureEnvelope">
        <xs:sequence>
            <xs:any namespace="http://www.w3.org/2000/09/xmldsig#" processContents="lax"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="ActiveCurrencyCode">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z]{3,3}" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="Max35Text">
        <xs:restriction base="xs:string">
            <xs:minLength value="1" />
            <xs:maxLength value="35" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="Rate">
        <xs:restriction base="xs:decimal">
            <xs:fractionDigits value="4"/>
            <xs:totalDigits value="19"/>
            <xs:maxInclusive value="999999999999999.9999"/>
            <xs:pattern value="[\-]{0,1}[0-9]{0,15}([\.]([0-9]{0,4})){0,1}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="CountryCode">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z]{2,2}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="ISONormalisedDateTime">
        <xs:restriction base="xs:dateTime">
            <xs:pattern value=".*Z"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>
