<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:ca07="urn:iso:std:iso:20022:tech:xsd:camt.007.002.03"
           xmlns:ca29="urn:iso:std:iso:20022:tech:xsd:camt.029.001.07"
           xmlns:ca56="urn:iso:std:iso:20022:tech:xsd:camt.056.001.06"
           xmlns:sw2="urn:iso:std:iso:20022:tech:xsd:pacs.002.001.07"
           xmlns:sw8="urn:iso:std:iso:20022:tech:xsd:pacs.008.001.07"
           xmlns:sw4="urn:iso:std:iso:20022:tech:xsd:pacs.004.001.07"
           xmlns:sw28="urn:iso:std:iso:20022:tech:xsd:pacs.028.001.02"
           xmlns:ac22="urn:iso:std:iso:20022:tech:xsd:acmt.022.001.02"
           xmlns:ac23="urn:iso:std:iso:20022:tech:xsd:acmt.023.001.02"
           xmlns:ac24="urn:iso:std:iso:20022:tech:xsd:acmt.024.001.02"
           xmlns:pi13="urn:iso:std:iso:20022:tech:xsd:pain.013.001.07"
           xmlns:pi14="urn:iso:std:iso:20022:tech:xsd:pain.014.001.07"
           xmlns:head="urn:iso:std:iso:20022:tech:xsd:head.001.001.01"
           xmlns="urn:montran:message.01" targetNamespace="urn:montran:message.01" elementFormDefault="qualified">
    <xs:import namespace="urn:iso:std:iso:20022:tech:xsd:camt.007.002.03" schemaLocation="camt.007.002.03.xsd"/>
    <xs:import namespace="urn:iso:std:iso:20022:tech:xsd:camt.029.001.07" schemaLocation="camt.029.001.07.xsd"/>
    <xs:import namespace="urn:iso:std:iso:20022:tech:xsd:camt.056.001.06" schemaLocation="camt.056.001.06.xsd"/>
    <xs:import namespace="urn:iso:std:iso:20022:tech:xsd:pacs.002.001.07" schemaLocation="pacs.002.001.07.xsd"/>
    <xs:import namespace="urn:iso:std:iso:20022:tech:xsd:pacs.004.001.07" schemaLocation="pacs.004.001.07.xsd"/>
    <xs:import namespace="urn:iso:std:iso:20022:tech:xsd:pacs.008.001.07" schemaLocation="pacs.008.001.07.xsd"/>
    <xs:import namespace="urn:iso:std:iso:20022:tech:xsd:pacs.028.001.02" schemaLocation="pacs.028.001.02.xsd"/>
    <xs:import namespace="urn:iso:std:iso:20022:tech:xsd:acmt.022.001.02" schemaLocation="acmt.022.001.02.xsd"/>
    <xs:import namespace="urn:iso:std:iso:20022:tech:xsd:acmt.023.001.02" schemaLocation="acmt.023.001.02.xsd"/>
    <xs:import namespace="urn:iso:std:iso:20022:tech:xsd:acmt.024.001.02" schemaLocation="acmt.024.001.02.xsd"/>
    <xs:import namespace="urn:iso:std:iso:20022:tech:xsd:pain.013.001.07" schemaLocation="pain.013.001.07.xsd"/>
    <xs:import namespace="urn:iso:std:iso:20022:tech:xsd:pain.014.001.07" schemaLocation="pain.014.001.07.xsd"/>
    <xs:import namespace="urn:iso:std:iso:20022:tech:xsd:head.001.001.01" schemaLocation="head.001.001.01.xsd"/>
    <xs:element name="Message">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="AppHdr" type="head:BusinessApplicationHeaderV01"/>
                <xs:choice>
                    <xs:element name="ReqToModfyPmt" type="ca07:RequestToModifyPaymentV03"/>
                    <xs:element name="RsltnOfInvstgtn" type="ca29:ResolutionOfInvestigationV07"/>
                    <xs:element name="FIToFIPmtCxlReq" type="ca56:FIToFIPaymentCancellationRequestV06"/>
                    <xs:element name="FIToFIPmtStsRpt" type="sw2:FIToFIPaymentStatusReportV07"/>
                    <xs:element name="PmtRtr" type="sw4:PaymentReturnV07"/>
                    <xs:element name="FIToFICstmrCdtTrf" type="sw8:FIToFICustomerCreditTransferV07"/>
                    <xs:element name="FIToFIPmtStsReq" type="sw28:FIToFIPaymentStatusRequestV02"/>
                    <xs:element name="IdModAdvc" type="ac22:IdentificationModificationAdviceV02"/>
                    <xs:element name="IdVrfctnReq" type="ac23:IdentificationVerificationRequestV02"/>
                    <xs:element name="IdVrfctnRpt" type="ac24:IdentificationVerificationReportV02"/>
                    <xs:element name="CdtrPmtActvtnReq" type="pi13:CreditorPaymentActivationRequestV07"/>
                    <xs:element name="CdtrPmtActvtnReqStsRpt"
                                type="pi14:CreditorPaymentActivationRequestStatusReportV07"/>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>