<?xml version="1.0" encoding="UTF-8"?>
<!-- Montran Corporation 2017-2019 (RP) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="urn:montran:rcon.001" elementFormDefault="qualified"
           targetNamespace="urn:montran:rcon.001">
    <xs:element name="recon">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="settlement" type="SettlementInfo"/>
                <xs:element name="tran" type="Transaction" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="totalSent" type="Summary"/>
                <xs:element name="totalReceived" type="Summary"/>
                <xs:element name="total" type="Summary"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="SettlementInfo">
        <xs:attribute name="seq" type="xs:long"/>
        <xs:attribute name="ccy" type="ActiveCurrencyCode"/>
        <xs:attribute name="msgId" type="Max35Text"/>
        <xs:attribute name="instgAgtId" type="ClrSysMmbId"/>
        <xs:attribute name="processTime" type="xs:dateTime"/>
    </xs:complexType>

    <xs:complexType name="Transaction">
        <xs:attribute name="ref" type="Max35Text"/>
        <xs:attribute name="processTime" type="xs:dateTime"/>
        <xs:attribute name="amount" type="Amount_SimpleType"/>
        <xs:attribute name="tranSeq" type="xs:long"/>
        <xs:attribute name="dbtrAgtId" type="ClrSysMmbId"/>
        <xs:attribute name="cdtrAgtId" type="ClrSysMmbId"/>
    </xs:complexType>

    <xs:complexType name="Summary">
        <xs:attribute name="amount" type="Amount_SimpleType"/>
        <xs:attribute name="count" type="xs:integer"/>
    </xs:complexType>

    <!--  Supporting simple Types -->
    <xs:simpleType name="Amount_SimpleType">
        <xs:restriction base="xs:decimal">
            <xs:fractionDigits value="2"/>
            <xs:totalDigits value="17"/>
            <xs:pattern value="(\-){0,1}[0-9]{0,15}([\.]([0-9]{0,2})){0,1}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="ActiveCurrencyCode">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z]{3,3}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="ClrSysMmbId">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z]{2,2}[A-Z1-9]{1,4}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="Max35Text">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="35"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>