<%--
//Generated by Customization WB Generator
//Do not edit this file directly.
//Instead, modify the properties in the tool and regenerate.
--%>

<%@ page import="applcommon.ParseValue" %>
<%@ page import="com.infy.bbu.jsputil.*"%>
<%@ page import="FABCommon.SecurityInfo70"%>
<%@ taglib uri="taglib.tld" prefix="arjsp" %>
<arjsp:init groupName="Customize" isEntryPoint="false" />

<%
	String sProfileId = ProfilesManager.getProfileInSession(session);
	String sSubGrpName = (String)ARJspCurr.getInput("subGroupName","");
	String sGrpName = ARJspCurr.getCurrentGroup();
	String sPopUpExceptionWindow = (String)ARJspCurr.getInput(sGrpName+".PopUpExceptionWindow" ,"false");
	String sReferralMode = (String)ARJspCurr.getInput("refSubMode" ,"");
	ARJspCurr.setInput(sGrpName+".PopUpExceptionWindow","false");
	SecurityInfo70 securityInfo = (SecurityInfo70)session.getAttribute("FinUserInfo");	
%>
<script>

	var sPopUpExceptionWindow = '<%=sPopUpExceptionWindow%>';
	var sReferralMode = '<%=sReferralMode%>' ;

	var subGroupName = '<%=ParseValue.checkString(ARJspCurr.getInput("subGroupName",""))%>';
	var solId = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".solId",""))%>';
	var BODDate= "<%=(securityInfo.bodDate).substring(0,10)%>";
	var frmDate_ui = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".frmDate_ui",""))%>';
	var toDate_ui = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".toDate_ui",""))%>';
	var frmDate = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".frmDate",""))%>';
	var toDate = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".toDate",""))%>';
	var funcCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".funcCode",""))%>'; 

</script>

<script language="javascript" src="../Renderer/custom/javascripts/custom_functions.js"></script>
<script language="javascript" src="../Renderer/custom/javascripts/custom_common_functions.js"></script>
<script language="javascript" src="../Renderer/custom/javascripts/cust_fetch_list.js"></script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("cust_pre_evt.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("cust_evt.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showSolId.js",sProfileId)%>" > </script>

<script language="JavaScript">
	printBlock();
	printFooterBlock();
</script>


