<%--
//Generated by Customization WB Generator
//Do not edit this file directly.
//Instead, modify the properties in the tool and regenerate.
--%>

<%@ page import="applcommon.ParseValue" %>
<%@ page import="com.infy.bbu.jsputil.*"%>
<%@ taglib uri="taglib.tld" prefix="arjsp" %>
<arjsp:init groupName="Customize" isEntryPoint="false" />

<%
	String sProfileId = ProfilesManager.getProfileInSession(session);
	String sSubGrpName = (String)ARJspCurr.getInput("subGroupName","");
	String sGrpName = ARJspCurr.getCurrentGroup();
	String sPopUpExceptionWindow = (String)ARJspCurr.getInput(sGrpName+".PopUpExceptionWindow" ,"false");
	String sReferralMode = (String)ARJspCurr.getInput("refSubMode" ,"");
	ARJspCurr.setInput(sGrpName+".PopUpExceptionWindow","false");
    String foracid= request.getParameter("cicrm.foracid")!=null ?request.getParameter("cicrm.foracid"):"";
    String instNo= request.getParameter("cicrm.instNo")!=null ?request.getParameter("cicrm.instNo"):"";
    String instAmt= request.getParameter("cicrm.instAmt")!=null ?request.getParameter("cicrm.instAmt"):"";
%>

<script>

	var sPopUpExceptionWindow = '<%=sPopUpExceptionWindow%>';
	var sReferralMode = '<%=sReferralMode%>' ;

	var subGroupName = '<%=ParseValue.checkString(ARJspCurr.getInput("subGroupName",""))%>';
   	var funcCode = 'R';
	var zoneCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".zoneCode",""))%>';
	var zoneDate = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".zoneDate",""))%>';
	var valueDate = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".valueDate",""))%>';
	var draweeBankCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".draweeBankCode",""))%>';
	var draweeBranchCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".draweeBranchCode",""))%>';
	var draweeSortCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".draweeSortCode",""))%>';
	var pressbankCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".pressbankCode",""))%>';
	var pressbrCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".pressbrCode",""))%>';
	var presssortCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".presssortCode",""))%>';
	var issBankCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".issBankCode",""))%>';
	var issBrCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".issBrCode",""))%>';
	var tranrmks = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".tranrmks",""))%>';
	var solId = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".solId",""))%>';
	var foracid = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".foracid",""))%>';
	var instNo = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".instNo",""))%>';
	var instAmt = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".instAmt",""))%>';
	var rejCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".rejCode",""))%>';
</script>

<script language="javascript" src="../Renderer/javascripts/lists/showAccountIdList.js" > </script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("cust_evt.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("core_banking.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("resource_functions.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("common_functions.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showCurrency.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showCustId.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showSchmCodes.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showSolId.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showSearcher.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showRejReasonList.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showRefCode.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/custom/javascripts/custom_functions.js"></script>
<script language="javascript" src="../Renderer/custom/javascripts/cust_fetch_list.js"></script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("cust_pre_evt.js",sProfileId)%>" > </script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("cust_evt.js",sProfileId)%>" > </script>
<script language="Javascript" src="../Renderer/javascripts/custom_common_functions.js" > </script>

<script language="JavaScript">
	printBlock();
	printFooterBlock();
</script>
