<%--
//Generated by Customization WB Generator
//Do not edit this file directly.
//Instead, modify the properties in the tool and regenerate.
--%>

<%@ page import="applcommon.ParseValue" %>
<%@ page import="com.infy.bbu.jsputil.*"%>
<%@ page import="java.util.Vector"%>
<%@ taglib uri="taglib.tld" prefix="arjsp" %>
<arjsp:init groupName="Customize" isEntryPoint="false" />

<%
	String sProfileId = ProfilesManager.getProfileInSession(session);
	String sSubGrpName = (String)ARJspCurr.getInput("subGroupName","");
	String sGrpName = ARJspCurr.getCurrentGroup();
	String pageName = (String)ARJspCurr.getInput("jspName","");
	String sPopUpExceptionWindow = (String)ARJspCurr.getInput(sGrpName+".PopUpExceptionWindow" ,"false");
	String sReferralMode = (String)ARJspCurr.getInput("refSubMode" ,"");
	ARJspCurr.setInput(sGrpName+".PopUpExceptionWindow","false");

%>
<script>

	var sPopUpExceptionWindow = '<%=ParseValue.checkString(sPopUpExceptionWindow)%>';
	var sReferralMode = '<%=ParseValue.checkString(sReferralMode)%>';
	var subGroupName = '<%=ParseValue.checkString(ARJspCurr.getInput("subGroupName",""))%>';
	var LowLim1 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".LowLim1",""))%>';
	var HighLim1 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".HighLim1",""))%>';
	var LowLimR1 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".LowLimR1",""))%>';
	var HighLimR1 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".HighLimR1",""))%>';
	var LowLim2 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".LowLim2",""))%>';
	var HighLim2 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".HighLim2",""))%>';
	var LowLimR2 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".LowLimR2",""))%>';
	var HighLimR2 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".HighLimR2",""))%>';
	var LowLim3 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".LowLim3",""))%>';
	var HighLim3 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".HighLim3",""))%>';
	var LowLimR3 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".LowLimR3",""))%>';
	var HighLimR3 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".HighLimR3",""))%>';
	var LowLim4 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".LowLim4",""))%>';
	var HighLim4 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".HighLim4",""))%>';
	var LowLimR4 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".LowLimR4",""))%>';
	var HighLimR4 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".HighLimR4",""))%>';
	var LowLim5 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".LowLim5",""))%>';
	var HighLim5 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".HighLim5",""))%>';
	var LowLimR5 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".LowLimR5",""))%>';
	var HighLimR5 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".HighLimR5",""))%>';
	var LowLim6 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".LowLim6",""))%>';
	var HighLim6 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".HighLim6",""))%>';
	var LowLimR6 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".LowLimR6",""))%>';
	var HighLimR6 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".HighLimR6",""))%>';
	var funcCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".funcCode",""))%>';
	var CrncyCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".CrncyCode",""))%>';
	var AplliDate = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".AplliDate",""))%>';
	var RecVerifyType = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".RecVerifyType",""))%>';

</script>


<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showAccountIdList.js",sProfileId)%>"></script>

<script language="JavaScript">
</script>

<script language="JavaScript">
	printBlock();
	printFooterBlock();
</script>
