<%--
//Generated by Customization WB Generator
//Do not edit this file directly.
//Instead, modify the properties in the tool and regenerate.
--%>

<%@ page import="applcommon.ParseValue" %>
<%@ page import="com.infy.bbu.jsputil.*"%>
<%@ page import="java.util.Vector"%>
<%@ taglib uri="taglib.tld" prefix="arjsp" %>
<arjsp:init groupName="Customize" isEntryPoint="false" />

<%
	String sProfileId = ProfilesManager.getProfileInSession(session);
	String sSubGrpName = (String)ARJspCurr.getInput("subGroupName","");
	String sGrpName = ARJspCurr.getCurrentGroup();
	String pageName = (String)ARJspCurr.getInput("jspName","");
	String sPopUpExceptionWindow = (String)ARJspCurr.getInput(sGrpName+".PopUpExceptionWindow" ,"false");
	String sReferralMode = (String)ARJspCurr.getInput("refSubMode" ,"");
	ARJspCurr.setInput(sGrpName+".PopUpExceptionWindow","false");


	int iCurrentSetSize = Integer.parseInt((String)ARJspCurr.getInput(sSubGrpName+".setSize","0"));
	int iListMaxDisplay = Integer.parseInt((String)ARJspCurr.getInput(sSubGrpName+".MaxRecsPerPage","20"));
	int iCurrentPage = Integer.parseInt((String)ARJspCurr.getInput(sSubGrpName+".currentPage","0"));
	int startRecord = (iCurrentPage-1)*iListMaxDisplay;
	int iMaxPage=Integer.parseInt((String)ARJspCurr.getInput(sSubGrpName+".maxPage","0"));
	int dispNum = startRecord + iListMaxDisplay;
	int iCounter;
	/*Vector vctMRMField = new Vector();
	vctMRMField.add("RefCode");
	vctMRMField.add("ItemCode");
	vctMRMField.add("ItemDescription");
	vctMRMField.add("UnitPrice");
	vctMRMField.add("DeleteFlag");
	ARJspCurr.setInput(sSubGrpName+"_"+pageName+".mrmFields", vctMRMField);*/

	iCurrentSetSize = 20;
	iListMaxDisplay = 20 ;
%>

%>
<script>

	var sPopUpExceptionWindow = '<%=sPopUpExceptionWindow%>';
	var sReferralMode = '<%=sReferralMode%>' ;

	var subGroupName = '<%=ParseValue.checkString(ARJspCurr.getInput("subGroupName",""))%>';
	var funcCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".funcCode",""))%>';
	var TotalAmount = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".TotalAmount",""))%>';
	var chkDeleteFlag = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".chkDeleteFlag",""))%>';
	var LoanAccount = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".LoanAccount",""))%>';
	var LoanAccountName = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".LoanAccountName",""))%>';
	var CustID = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".CustID",""))%>';
	var LoanAcid = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".LoanAcid",""))%>';
	var SchemeCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".SchemeCode",""))%>';
	var MISCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".MISCode",""))%>';
	var LoanDate = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".LoanDate",""))%>';
	var OperativeAccount = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".OperativeAccount",""))%>';
	var LoanAmount = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".LoanAmount",""))%>';
	var Status = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".Status",""))%>';
	var OrderNo = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".OrderNo",""))%>';
	var OwnContribAmount = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".OwnContribAmount",""))%>';
	var ContributionAccount = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".ContributionAccount",""))%>';
	var Recoverfrm = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".Recoverfrm",""))%>';


	var CurrentPage = '<%=iCurrentPage%>';
	var MaxPage = '<%=iMaxPage%>';
	var startRecord = <%=startRecord%>;
	var ListMaxDisplay = <%=iListMaxDisplay%>;
	var CurrentSetSize = '<%=iCurrentSetSize%>';

	var iListMaxDisplay='<%=iListMaxDisplay%>';
	var RefCode = new Array(iListMaxDisplay);
	var ItemCode = new Array(iListMaxDisplay);
	var ItemDescription = new Array(iListMaxDisplay);
	var UnitPrice = new Array(iListMaxDisplay);
	var DeleteFlag = new Array(iListMaxDisplay);
</script>



<%
	for(int i=0;i<iListMaxDisplay;i++)
	{
		iCounter= startRecord + i;
	%>
	<script language="JavaScript">
		RefCode['<%=i%>']= '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".RefCode_"+iCounter,""))%>';
		ItemCode['<%=i%>']= '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".ItemCode_"+iCounter,""))%>';
		ItemDescription['<%=i%>']= '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".ItemDescription_"+iCounter,""))%>';
		UnitPrice['<%=i%>']= '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".UnitPrice_"+iCounter,""))%>';
		DeleteFlag['<%=i%>']= '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".DeleteFlag_"+iCounter,""))%>';
	</script>
	<%
	}
%>

<script language="JavaScript">
	printBlock();
	printFooterBlock();
</script>

