logging:
  level:
    ROOT: INFO
    org.hibernate: INFO
    com.equitybank.gag.telco_b2c: INFO
    com.netflix.discovery.DiscoveryClient: INFO

server:
  port: 8582

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: ${CD_SPRING_DATASOURCE_URL}
    username: ${CD_SPRING_DATASOURCE_USERNAME}
    password: ${CD_SPRING_DATASOURCE_PASSWORD}
    hikari:
      idleTimeout: 60000
      connectionTimeout: 60000
      maxLifetime: 30000
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.Oracle12cDialect
      ddl-auto: update
    show-sql: false

equity-orange:
  account:
    alias: '000000000000'
  endpoint:
      transactions: ${CD_ORANGE_B2C_TRANSACTIONS_BASE_URL}
      status: ${CD_ORANGE_B2C_STATUS_BASE_URL}
      noexpiretoken: ${CD_ORANGE_B2C_NONEXPIRETOKEN}
      
service:
 activation:
  airtime: true
  b2c: false
     
orange:
  cd:
   airtime:
    pin: ${CD_ORANGE_AIRTIME_PURCHASE_PIN}
    channelMsisdn: ${CD_ORANGE_AIRTIME_PURCHASE_CHANNEL_MSISDN}
    password: ${CD_ORANGE_AIRTIME_PURCHASE_PASSWORD}
    extCode: ${CD_ORANGE_AIRTIME_PURCHASE_EXTCODE}
    loginId: ${CD_ORANGE_AIRTIME_PURCHASE_LOGINID}
    requestURL: ${CD_ORANGE_AIRTIME_BASE_URL}
    request:
     REQUEST_GATEWAY_CODE: ${CD_ORANGE_AIRTIME_REQUEST_GATEWAY_CODE}
     SERVICE_PORT: ${CD_ORANGE_AIRTIME_SERVICE_PORT}
     REQUEST_GATEWAY_TYPE: ${CD_ORANGE_AIRTIME_REQUEST_GATEWAY_TYPE}
     LOGIN: ${CD_ORANGE_AIRTIME_LOGIN}
     SOURCE_TYPE: ${CD_ORANGE_AIRTIME_SOURCE_TYPE}
     PASSWORD: ${CD_ORANGE_AIRTIME_PASSWORD}
    whiteList: 0986676678,2437000000
    limit:
     USD: 1.5
     CDF: 3000
    mock:
     scenario:
        buy: success   
        
        
     
     
        
        