#WORKFLOW Properties
#Thu Jun 19 17:31:24 EAT 2025
StartOfAutomationTables=1
NoOfAutomationThreads=19
Server_name=A
NoOfAutomationTables=4
IS_IRD_ENTRY_FORDUMMYTOCORE=N
DisableRecovery=true
DeleteAll=false
