#!/bin/bash

# Export the Jasypt secret key as an environment variable
export CD_SPRING_DATASOURCE_URL="#{CD-SPRING-DATASOURCE-URL}#"
export CD_SPRING_DATASOURCE_USERNAME="#{CD-SPRING-DATASOURCE-USERNAME}#"
export CD_SPRING_DATASOURCE_PASSWORD="#{SPRING-DATASOURCE-PASSWORD}#"

export CD_VODACOM_B2C_LOGIN_USERNAME="equityb2w"
export CD_VODACOM_B2C_LOGIN_PASSWORD='Equity@25$!~'

# export CD_VODACOM_B2C_LOGIN_USERNAME="#{CD-VODACOM-B2C-LOGIN-USERNAME}#"
# export CD_VODACOM_B2C_LOGIN_PASSWORD="#{CD-VODACOM-B2C-LOGIN-PASSWORD}#"

#export CD_VODACOM_B2C_LOGIN_USERNAME="#{CD-VODACOM-B2C-LOGIN-USERNAME}#"
#export CD_VODACOM_B2C_LOGIN_PASSWORD="#{CD-VODACOM-B2C-LOGIN-PASSWORD}#"
export CD_VODACOM_B2C_LOGIN_SERVICEPROVIDERNAME="#{CD-VODACOM-B2C-LOGIN-SERVICEPROVIDERNAME}#"
#export CD_VODACOM_B2C_SHORTCODE="#{CD-VODACOM-B2C-LOGIN-SHORTCODE}#"
export CD_VODACOM_B2C_SHORTCODE="1543"
#export CD_VODACOM_B2C_LOGIN_URL="http://localhost:8085/insight/SOAPIn"
export CD_VODACOM_B2C_LOGIN_URL="https://192.168.115.57:8091/insight/SOAPIn"
#export CD_VODACOM_B2C_DISBURSEMENT_URL="http://localhost:8085/iPG/B2C"
#export CD_VODACOM_B2C_DISBURSEMENT_URL="https://uatipg.m-pesa.vodacom.cd:8094/iPG/B2C"
export CD_VODACOM_B2C_DISBURSEMENT_URL="https://192.168.115.57:8094/iPG/B2C"
export CD_VODACOM_B2C_CALLBACK_URL="http://196.216.242.224:8085/api/v1/vodacom/b2c/callback"

export CD_VODACOM_B2B_LOGIN_USERNAME="#{CD-VODACOM-B2B-LOGIN-USERNAME}#"
export CD_VODACOM_B2B_LOGIN_PASSWORD="insight@8"
export CD_VODACOM_B2B_SHORTCODE="#{CD-VODACOM-B2B-SHORTCODE}#"
export CD_VODACOM_B2B_BANKSHORTCODE="#{CD-VODACOM-B2B-BANKSHORTCODE}#"
# export CD_VODACOM_B2B_LOGIN_URL="http://192.168.115.57:8091/insight/B2BLogin"
export CD_VODACOM_B2B_LOGIN_URL="https://192.168.115.57:8107/insight/B2BLogin"
export CD_VODACOM_B2B_DISBURSEMENT_URL="https://192.168.115.57:8094/insight/B2B"
export CD_VODACOM_B2B_CALLBACK_URL="http://196.216.242.224:8085/api/v1/vodacom/b2b/callback"

export CD_VODACOM_AIRTIME_THIRDPARTYID="#{CD-VODACOM-AIRTIME-THIRDPARTYID}#"
export CD_VODACOM_AIRTIME_PASSWORD="#{CD-VODACOM-AIRTIME-PASSWORD}#"
export CD_VODACOM_AIRTIME_IDENTIFIER="#{CD-VODACOM-AIRTIME-IDENTIFIER}#"
export CD_VODACOM_AIRTIME_SHORTCODE="#{CD-VODACOM-AIRTIME-SHORTCODE}#"
export CD_VODACOM_AIRTIME_SECURITYCREDENTIAL="#{CD-VODACOM-AIRTIME-SECURITYCREDENTIAL}#"
#export CD_VODACOM_AIRTIME_RESULT_URL="http://localhost:8085/api/vodacom/airtimetopupcallback"
export CD_VODACOM_AIRTIME_RESULT_URL="http://localhost:8185/api/vodacom/airtimetopupcallback"
#export CD_VODACOM_AIRTIME_REQUEST_URL="http://localhost:8085/external/airtime/buy"
#export CD_VODACOM_AIRTIME_REQUEST_URL="http://localhost:8185/external/airtime/buy"
export CD_VODACOM_AIRTIME_REQUEST_URL="https://192.168.115.57:8094/external/airtime/buy"
export CD_VODACOM_AIRTIME_POS_DEVICE_ID_KEY="POSDeviceID"
export CD_VODACOM_AIRTIME_POS_DEVICE_ID_VALUE="POS234789"
export CD_VODACOM_AIRTIME_RECEIVER_PARTY_IDENTIFIER="10086"

export CD_VODACOM_NAMECHECK_LOGIN_USERNAME="apigateway1" #{CD-VODACOM-NAMECHECK-LOGIN-USERNAME}#
export CD_VODACOM_NAMECHECK_LOGIN_PASSWORD="Vod@com#2025" #{CD-VODACOM-NAMECHECK-LOGIN-PASSWORD}#
export CD_VODACOM_NAMECHECK_TOKEN_URL="https://192.168.115.57:9090/oauth/v1"
export CD_VODACOM_NAMECHECK_URL="https://192.168.115.57:9091/api/v1"
export CD_VODACOM_BUSINESS_SERVICE_CALLBACK_URL="https://10.11.6.110:8443/api/v1/b2c/callback"


export CD_VODACOM_B2C_MOCK_LOGIN_URL="http://localhost:8085/insight/SOAPIn"
export CD_VODACOM_B2C_MOCK_DISBURSEMENT_URL="http://localhost:8085/iPG/B2C"
export CD_VODACOM_B2C_MOCK_CALLBACK_URL="http://localhost:8085/api/v1/vodacom/b2c/callback"

export KE_SAFARICOM_B2B_CHECKSUM="CheckSum0"
export KE_SAFARICOM_B2B_SHORTCODE="100001"
export KE_SAFARICOM_B2B_PASSWORD="Password0"
export KE_SAFARICOM_B2B_QUEUETIMEOUT_URL="http://localhost:8085/api/v1/safaricom/b2b/queuetimeout/callback"
export KE_SAFARICOM_B2B_RESULT_URL="http://localhost:8085/api/v1/safaricom/b2b/callback"
export KE_SAFARICOM_B2B_SECURITY_CREDENTIAL_PUBLIC_KEY="-----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA8rM5lxew7fQsdEsQWhwI0iwE45YioA/2BGvURO2+I5sB/q7EYrBWypmkmuX/dkx5yKh2m6sLDIDV/4LH7IHzGpKDiNxyA2Y2hRNsYtYYNiVmMZdyDd89r4fY+MuwLs5UK4o0Cd7nInMgUlCXSMTiEGtGYOTGW81gH6ZVWTL83HKu/F3VKHLSG1qcVGuXQiBlm1s4JxWkaSrN8DOPs2HnlcOJP37VE+2Evb1ewRaO4/qEbrYaV+6B0CySNwkYoRnnfDjOosQD+ewVik3aBqVnwVqX+0MrPhlRoa3VNGWSYreuM2xpQagpqol5EJB23GIIXG7QQbwQVHrt5J4u9S3Z7wIDAQAB-----END PUBLIC KEY-----"
export KE_SAFARICOM_B2B_SERVICE_ID="107031000"
export KE_SAFARICOM_B2B_SP_ID="107031"
export KE_SAFARICOM_B2B_SP_PASSWORD="Safaricom123!"
export KE_SAFARICOM_B2B_THIRDPARTY_ID="broker_4"
export KE_SAFARICOM_B2B_USERNAME="username"
export KE_SAFARICOM_B2B_DEBIT_PARTY_SHORT_CODE="100001"
# export KE_SAFARICOM_B2B_REQUEST_URL="https://192.168.9.48:18423/mminterface/request"
export KE_SAFARICOM_B2B_REQUEST_URL="http://localhost:8085/mminterface/request"

# Print a confirmation message
echo "Environment variables have been set."