DROP SEQUENCE CUSTOM.CUST_DENOM_CASHX_SEQ
/
CREATE SEQUENCE CUSTOM.CUST_DENOM_CASHX_SEQ INCREMENT BY 1 START WITH 1 MINVALUE 1 MAXVALUE 99999999 CYCLE NOCACHE NOORDER
/
DROP SYNONYM CUSTOM.DENOM_CASHX_SEQ
/
CREATE SYNONYM CUSTOM.DENOM_CASHX_SEQ FOR CUSTOM.CUST_DENOM_CASHX_SEQ
/
GRANT SELECT ON  CUSTOM.CUST_DENOM_CASHX_SEQ TO TBAGEN
/
GRANT SELECT ON  CUSTOM.DENOM_CASHX_SEQ TO TBAGEN
/
commit
/

