--====================================================================================================
-- Table Name                   : CUST_EIT_BACKUP_TABLE
-- Synonym Name                 : C_EIT_BACKUP
-- Index Name                   :
-- Unique Index On              :
-- Date                         :
-- Description                  : This sql script is used to create a customized CUST_EIT_BACKUP_TABLE table
-- Author                       :
-- Bank                         : EQUITY BANK
-- Modification History :
-- <Version No.>    <Date>        <Author Name>         <Description>
--	0.1	  21-10-2012	   Parikshith
--====================================================================================================

Rem TABLE NAME: CUST_EIT_BACKUP_TABLE

DROP TABLE CUST_EIT_BACKUP_TABLE
/

CREATE TABLE CUST_EIT_BACKUP_TABLE
(
  ENTITY_ID                 VARCHAR2(12 CHAR),
  ENTITY_TYPE               VARCHAR2(5 CHAR),
  EIT_DATE                  DATE,
  ACCRUED_UPTO_DATE_CR      DATE,
  ACCRUED_UPTO_DATE_DR      DATE,
  BOOKED_UPTO_DATE_CR       DATE,
  BOOKED_UPTO_DATE_DR       DATE,
  LAST_BOOK_CR_TRAN_ID      VARCHAR2(9 CHAR),
  LAST_BOOK_DR_TRAN_ID      VARCHAR2(9 CHAR),
  LAST_INT_CR_TRAN_ID       VARCHAR2(9 CHAR),
  LAST_INT_DR_TRAN_ID       VARCHAR2(9 CHAR),
  LAST_INT_CR_TRAN_DATE     DATE,
  LAST_INT_DR_TRAN_DATE     DATE,
  INTEREST_RATE             NUMBER(9,6),
  NRML_ACCRUED_AMOUNT_CR    NUMBER(22,6),
  NRML_ACCRUED_AMOUNT_DR    NUMBER(22,6),
  NRML_BOOKED_AMOUNT_CR     NUMBER(22,6),
  NRML_BOOKED_AMOUNT_DR     NUMBER(22,6),
  NRML_INTEREST_AMOUNT_CR   NUMBER(22,6),
  NRML_INTEREST_AMOUNT_DR   NUMBER(22,6),
  PENAL_ACCRUED_AMOUNT_DR   NUMBER(22,6),
  PENAL_BOOKED_AMOUNT_DR    NUMBER(22,6),
  PENAL_INTEREST_AMOUNT_DR  NUMBER(22,6),
  PENAL_ADV_INT_AMOUNT_DR   NUMBER(22,6),
  ADDNL_ACCRUED_AMOUNT_DR   NUMBER(22,6),
  ADDNL_BOOKED_AMOUNT_DR    NUMBER(22,6),
  ADDNL_INTEREST_AMOUNT_DR  NUMBER(22,6),
  QIS_ACCRUED_AMOUNT_DR     NUMBER(22,6),
  QIS_BOOKED_AMOUNT_DR      NUMBER(22,6),
  QIS_INTEREST_AMOUNT_DR    NUMBER(22,6),
  STOCK_ACCRUED_AMOUNT_DR   NUMBER(22,6),
  STOCK_BOOKED_AMOUNT_DR    NUMBER(22,6),
  STOCK_INTEREST_AMOUNT_DR  NUMBER(22,6),
  OVDU_ACCRUED_AMOUNT_DR    NUMBER(22,6),
  OVDU_BOOKED_AMOUNT_DR     NUMBER(22,6),
  OVDU_INTEREST_AMOUNT_DR   NUMBER(22,6),
  LCHG_USER_ID              VARCHAR2(15 CHAR),
  LCHG_TIME                 DATE,
  RCRE_USER_ID              VARCHAR2(15 CHAR),
  RCRE_TIME                 DATE,
  BANK_ID                   VARCHAR2(8 CHAR)
)
TABLESPACE CUSTOM_TBLS
/

CREATE INDEX CUSTOM.IDX_CUST_EIT_BACKUP ON CUSTOM.CUST_EIT_BACKUP_TABLE
(ENTITY_ID, EIT_DATE, BANK_ID)
/

CREATE INDEX CUSTOM.IDX_QRY_CUST_EIT_BACKUP ON CUSTOM.CUST_EIT_BACKUP_TABLE
(ENTITY_TYPE, EIT_DATE, BANK_ID)
/

CREATE SYNONYM CUSTOM.C_EIT_BACKUP FOR CUSTOM.CUST_EIT_BACKUP_TABLE
/

CREATE SYNONYM TBAADM.C_EIT_BACKUP FOR CUSTOM.CUST_EIT_BACKUP_TABLE
/

CREATE SYNONYM TBAGEN.C_EIT_BACKUP FOR CUSTOM.CUST_EIT_BACKUP_TABLE
/

CREATE SYNONYM TBAUTIL.C_EIT_BACKUP FOR CUSTOM.CUST_EIT_BACKUP_TABLE
/

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.CUST_EIT_BACKUP_TABLE TO TBAADM
/

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.CUST_EIT_BACKUP_TABLE TO TBAGEN
/

GRANT SELECT ON CUSTOM.CUST_EIT_BACKUP_TABLE TO TBAUTIL
/
