DROP TABLE CUSTOM.CUST_DENOM_MASTER_MOD_TBL CASCADE CONSTRAINTS;

CREATE TABLE CUSTOM.CUST_DENOM_MASTER_MOD_TBL
(
  SOL_ID        VARCHAR2(20 BYTE)               NOT NULL,
  CRNCY_CODE    VARCHAR2(5 BYTE)                NOT NULL,
  DENOM_IND     CHAR(1 BYTE)                    NOT NULL,
  DENOM_VALUE   NUMBER(10,2)                    NOT NULL,
  DENOM_COUNT   NUMBER(20),
  TELLER_ID     VARCHAR2(20 BYTE),
  RCRE_USER_ID  VARCHAR2(15 BYTE)               NOT NULL,
  RCRE_TIME     DATE                            NOT NULL,
  LCHG_USER_ID  VARCHAR2(15 BYTE)               NOT NULL,
  LCHG_TIME     DATE                            NOT NULL,
  DEL_FLG       CHAR(1 BYTE)                    NOT NULL,
  BANK_ID       VARCHAR2(8 CHAR)
);

CREATE UNIQUE INDEX CUSTOM.IDX_CUST_DENOM_MASTER_MOD_TBL ON CUSTOM.CUST_DENOM_MASTER_MOD_TBL
(SOL_ID, CRNCY_CODE, DENOM_IND, DENOM_VALUE, TELLER_ID, 
BANK_ID);


DROP SYNONYM CUSTOM.C_DENM_MOD;

CREATE SYNONYM CUSTOM.C_DENM_MOD FOR CUSTOM.CUST_DENOM_MASTER_MOD_TBL;

DROP SYNONYM TBAADM.C_DENM_MOD;

CREATE SYNONYM TBAADM.C_DENM_MOD FOR CUSTOM.CUST_DENOM_MASTER_MOD_TBL;

DROP SYNONYM TBAGEN.C_DENM_MOD;

CREATE SYNONYM TBAGEN.C_DENM_MOD FOR CUSTOM.CUST_DENOM_MASTER_MOD_TBL;

DROP SYNONYM TBAUTIL.C_DENM_MOD;

CREATE SYNONYM TBAUTIL.C_DENM_MOD FOR CUSTOM.CUST_DENOM_MASTER_MOD_TBL;

GRANT SELECT ON CUSTOM.CUST_DENOM_MASTER_MOD_TBL TO ALLTAB;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.CUST_DENOM_MASTER_MOD_TBL TO TBAADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.CUST_DENOM_MASTER_MOD_TBL TO TBAGEN;

GRANT SELECT ON CUSTOM.CUST_DENOM_MASTER_MOD_TBL TO TBAUTIL;

