CREATE TABLE CUSTOM.CUST_DENOM_TRAN_DETAIL
(
  SOL_ID             VARCHAR2(20 BYTE)          NOT NULL,
  DXFER_ID           VARCHAR2(13 BYTE)          NOT NULL,
  DXFER_FLG          CHAR(3 BYTE)               NOT NULL,
  PTRAN_TYPE         CHAR(1 BYTE)               NOT NULL,
  CRNCY_CODE         VARCHAR2(3 BYTE)           NOT NULL,
  DENOM_IND          CHAR(1 BYTE)               NOT NULL,
  DENOM_VALUE        VARCHAR2(80 BYTE)          NOT NULL,
  DENOM_COUNT        VARCHAR2(80 BYTE)          NOT NULL,
  TYPE               VARCHAR2(2 BYTE),
  TELLER_ID          VARCHAR2(20 BYTE)          NOT NULL,
  TRAN_DATE          DATE                       NOT NULL,
  VALUE_DATE         DATE                       NOT NULL,
  AUTH_MATRIX_ID     VARCHAR2(5 BYTE),
  PART_TRAN_SRL_NUM  VARCHAR2(4 CHAR)           NOT NULL,
  RCRE_USER_ID       VARCHAR2(15 BYTE)          NOT NULL,
  RCRE_TIME          DATE                       NOT NULL,
  LCHG_USER_ID       VARCHAR2(15 BYTE)          NOT NULL,
  LCHG_TIME          DATE                       NOT NULL,
  BANK_ID            VARCHAR2(8 CHAR)
);


CREATE UNIQUE INDEX CUSTOM.IDX_C_DETD ON CUSTOM.CUST_DENOM_TRAN_DETAIL
(SOL_ID, DXFER_ID, CRNCY_CODE, DENOM_IND, TRAN_DATE, 
DXFER_FLG, PTRAN_TYPE, TELLER_ID, TYPE, PART_TRAN_SRL_NUM)
;


CREATE SYNONYM CUSTOM.C_DETD FOR CUSTOM.CUST_DENOM_TRAN_DETAIL;


CREATE SYNONYM TBAGEN.C_DETD FOR CUSTOM.CUST_DENOM_TRAN_DETAIL;


CREATE SYNONYM TBAUTIL.C_DETD FOR CUSTOM.CUST_DENOM_TRAN_DETAIL;


CREATE SYNONYM TBAADM.C_DETD FOR CUSTOM.CUST_DENOM_TRAN_DETAIL;


GRANT SELECT ON CUSTOM.CUST_DENOM_TRAN_DETAIL TO READONLY;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.CUST_DENOM_TRAN_DETAIL TO TBAADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.CUST_DENOM_TRAN_DETAIL TO TBAGEN;

GRANT SELECT ON CUSTOM.CUST_DENOM_TRAN_DETAIL TO TBAUTIL;
