SET DEFINE OFF;
Insert into CUSTOM.C_CPVALUE
   (PARAMETER_ID, LEVELCODE_1, PARAMETER_VALUE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID, MODULE_NAME)
 Values
   ('OCTMCHRGEVT', 'ALL', 'EFTOUT', 'Y', 'N', 'USER1', TO_DATE('06/07/2013 13:53:58', 'MM/DD/YYYY HH24:MI:SS'), 'USER1', TO_DATE('06/07/2013 13:53:58', 'MM/DD/YYYY HH24:MI:SS'), '11', 'TRADE_FINANCE');
Insert into CUSTOM.C_CPVALUE
   (PARAMETER_ID, LEVELCODE_1, PARAMETER_VALUE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID, MODULE_NAME)
 Values
   ('OCTMCHRGEVT', 'ALL', 'EFTOUT', 'Y', 'N', 'USER1', TO_DATE('06/07/2013 13:53:58', 'MM/DD/YYYY HH24:MI:SS'), 'USER1', TO_DATE('06/07/2013 13:53:58', 'MM/DD/YYYY HH24:MI:SS'), '50', 'TRADE_FINANCE');
Insert into CUSTOM.C_CPVALUE
   (PARAMETER_ID, LEVELCODE_1, PARAMETER_VALUE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID, MODULE_NAME)
 Values
   ('OCTMCHRGEVT', 'ALL', 'EFTOUT', 'Y', 'N', 'USER1', TO_DATE('06/07/2013 13:53:58', 'MM/DD/YYYY HH24:MI:SS'), 'USER1', TO_DATE('06/07/2013 13:53:58', 'MM/DD/YYYY HH24:MI:SS'), '54', 'TRADE_FINANCE');
Insert into CUSTOM.C_CPVALUE
   (PARAMETER_ID, LEVELCODE_1, PARAMETER_VALUE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID, MODULE_NAME)
 Values
   ('OCTMCHRGEVT', 'ALL', 'EFTOUT', 'Y', 'N', 'USER1', TO_DATE('06/07/2013 13:53:58', 'MM/DD/YYYY HH24:MI:SS'), 'USER1', TO_DATE('06/07/2013 13:53:58', 'MM/DD/YYYY HH24:MI:SS'), '55', 'TRADE_FINANCE');
Insert into CUSTOM.C_CPVALUE
   (PARAMETER_ID, LEVELCODE_1, PARAMETER_VALUE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID, MODULE_NAME)
 Values
   ('OCTMCHRGEVT', 'ALL', 'EFTOUT', 'Y', 'N', 'USER1', TO_DATE('06/07/2013 13:53:58', 'MM/DD/YYYY HH24:MI:SS'), 'USER1', TO_DATE('06/07/2013 13:53:58', 'MM/DD/YYYY HH24:MI:SS'), '56', 'TRADE_FINANCE');
COMMIT;
