<%--
//Generated by Customization WB Generator
//Do not edit this file directly.
//Instead, modify the properties in the tool and regenerate.
--%>
<%@ page import="finbranchUtil.*" %>
<%@ page import="applcommon.ParseValue" %>
<%@ page import="com.infy.bbu.jsputil.*"%>
<%@ page import="FABCommon.SecurityInfo70"%>
<%@ taglib uri="taglib.tld" prefix="arjsp" %>
<arjsp:init groupName="Customize" isEntryPoint="false" />

<%
	String sProfileId = ProfilesManager.getProfileInSession(session);
	String sSubGrpName = (String)ARJspCurr.getInput("subGroupName","");
	String sGrpName = ARJspCurr.getCurrentGroup();
	String sPopUpExceptionWindow = (String)ARJspCurr.getInput(sGrpName+".PopUpExceptionWindow" ,"false");
	String sReferralMode = (String)ARJspCurr.getInput("refSubMode" ,"");
	ARJspCurr.setInput(sGrpName+".PopUpExceptionWindow","false");
	SecurityInfo70 securityInfo = (SecurityInfo70)session.getAttribute("FinUserInfo");



String refNum = "";

if(("V".equals(ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".funcCode",""))))||("X".equals(ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".funcCode","")))))
{
finbranchUtil.MenuMiscInfo menuMiscInfo = (finbranchUtil.MenuMiscInfo)ARJspCurr.getInput(finbranchUtil.MenuMiscInfo.getObjectName(), null);
        if (menuMiscInfo != null)
                                {
 refNum = ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".refNum",""));
menuMiscInfo.setRefNum(refNum);
                                }
}


%>
<script>

	var sPopUpExceptionWindow = '<%=sPopUpExceptionWindow%>';
	var sReferralMode = '<%=sReferralMode%>' ;

	var subGroupName = '<%=ParseValue.checkString(ARJspCurr.getInput("subGroupName",""))%>';
	var BODDate= "<%=(securityInfo.bodDate).substring(0,10)%>";
	var funcCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".funcCode",""))%>';
	var txnTypeDesc = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".txnTypeDesc",""))%>';

	var debitEntity = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".debitEntity",""))%>';
        var debitEntityDesc = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".debitEntityDesc",""))%>';
	var drAcctNum = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".drAcctNum",""))%>';
        var drAcctNumEntityId = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".drAcctNumEntityId",""))%>';
        var drAcctNumSolId = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".drAcctNumSolId",""))%>';
        var drAcctNumCcy = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".drAcctNumCcy",""))%>';
        var drAcctName = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".drAcctName",""))%>';
	var creditEntity = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".creditEntity",""))%>';
        var creditEntityDesc = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".creditEntityDesc",""))%>';
	var crAcctNum = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".crAcctNum",""))%>';
	var crAcctNumEntityId = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".crAcctNumEntityId",""))%>';
	var crAcctNumSolId = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".crAcctNumSolId",""))%>';
	var crAcctNumCcy = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".crAcctNumCcy",""))%>';
	var crAcctName = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".crAcctName",""))%>';
	var refCrncy = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".refCrncy",""))%>';
	var refAmt = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".refAmt",""))%>';
	var rateCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".rateCode",""))%>';
	var rate = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".rate",""))%>';
	var treaRefNum = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".treaRefNum",""))%>';
        var treaRate = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".treaRate",""))%>';
	var tranAmt = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".tranAmt",""))%>';
	var tranAmtCcy = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".tranAmtCcy",""))%>';
	var chargeEventId = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".chargeEventId",""))%>';
	var chargeAmt = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".chargeAmt",""))%>';
	var chargeAmtCcy = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".chargeAmtCcy",""))%>';
	var refNo = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".refNo",""))%>';
	var nostroAcct = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".nostroAcct",""))%>';
	var nostroAcctName = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".nostroAcctName",""))%>';
	var vostroAcct = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".vostroAcct",""))%>';
	var tranParticularsCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".tranParticularsCode",""))%>';
	var tranParticular = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".tranParticular",""))%>';
	var tranRmks = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".tranRmks",""))%>';
	var tranRmks2 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".tranRmks2",""))%>';

	var instrumentType = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".instrumentType",""))%>';
        var instrumentAlpha = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".instrumentAlpha",""))%>';
        var instrumentDate = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".instrumentDate",""))%>';
        var instrumentNum = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".instrumentNum",""))%>';

	var targetCcy = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".targetCcy",""))%>';
	var cifIdForSig = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".cifIdForSig",""))%>'; 

	var varbiotest = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".varbiotest",""))%>';

	homeCrncyCode = "";	

	if(funcCode=='V' || funcCode =='X'){
        isAuditEnabled="true";
        }


</script>

<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showAccountIdList.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("getRefCodeList.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showRateCodes.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showRefCode.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("getInstrTypeList.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("common_functions.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/custom/javascripts/<%=VRPKeys.getFile("custom_functions.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showSearcher.js",sProfileId)%>"></script>


<script language="JavaScript">
	printBlock();
	printFooterBlock();
</script>

