logging:
  level:
    ROOT: INFO
    org.jpos: INFO
    org.hibernate: INFO

# Finacle configs
finacle:
  iso:
    timeout:
      connectTimeout: 10000    # Timeout in ms for establishing connection
      socketTimeout: 50000     # Timeout in ms for waiting for response
    echo:
      timeout: 5000 # Timeout in ms for echo service waiting for response
jpos:
  tm:
    # Max number of Transaction Managers allowed.
    max-tms: 50

    # Queue depth threshold. If all active TM queues exceed this, a new TM is created.
    # This counts incoming transactions not yet picked up (backlog), distinct from TM's internal 'sessions'.
    queue-depth-threshold: 10

    # The ABSOLUTE path to jPOS Q2's deploy directory where TM templates and instances are located.
    q2-tm-dir: "/u01/gag/papss/papss-outbound-technical-service-ms/deploy"

    # The *relative path* within the 'q2-deploy-dir' where states.xml is located.
    q2-states-relative-path: "cfg"

    # Filename prefix for generated TM XMLs.
    tm-filename-prefix: "transaction-manager-tm-"

    # Queue name prefix for TMs.
    tm-queue-prefix: "transaction-manager-queue-q"

    # Relative path to TM template file within deploy-dir. Must be manually placed there.
    tm-template-relative-path: "cfg/transaction-manager-tm-template.xml"

    # Timeout in milliseconds for dispatching to jPOS space/queue
    dispatch-timeout-ms: 10000

# ssl configs
server:
  port: 10443
  ssl:
    enabled: true
    key-store: '/u01/gag/papss/certs/papss-equitygroup.p12'
    key-store-password: 'papss-equitygroup!'
    key-store-type: PKCS12
    key-alias: papss-equitygroup
    trust-store: '/u01/gag/papss/certs/truststore-papss-equitygroup.p12'
    trust-store-password: 'papss-equity!'
    trust-store-type: PKCS12
    trust-aliases:
      papss: papss-moc
      omni: omni
      remittance: remittance

# enable this if you want to skip host verification, or trust all certs during mtls handshake
http:
  ssl:
    trust-all: true
    skip-hostname-verification: true

# Async thread configs
async:
  core-pool-size: 20        # Always keep 20 threads alive
  max-pool-size: 50         # Can burst up to 50 during spikes
  queue-capacity: 5000      # Buffer up to 5k tasks before rejecting
  keep-alive-seconds: 60    # Non-core threads live for 60s when idle

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/papss_db
    username: papss_user
    password: papss_pass
    hikari:
      poolName: Hikari
      auto-commit: false
      maximum-pool-size: 50
      minimum-idle: 10
      idle-timeout: 30000          # Close idle connections after 30s
      connection-timeout: 20000    # Wait max 20s for a connection
      max-lifetime: 1800000        # Recycle connections every 30 mins
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 500
        prepStmtCacheSqlLimit: 4096
        useServerPrepStmts: true
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.Oracle12cDialect
      ddl-auto: validate
    show-sql: false

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

# PAPSS Urls
papss:
  ips-domain: 'pm.test.papssnet.papss.com'
  ips-port: '443'
  urls:
    common-url: 'https://pm.test.papssnet.papss.com/papss/Message'
    fx-rate-base-url: 'https://pm.test.papssnet.papss.com/papss/FXRate'
    namecheck: 'https://pm.test.papssnet.papss.com/papss/api/v1/outbward/nameenquiry'
    participants-base-url: 'https://pm.test.papssnet.papss.com/papss/api/participants'
    status-check: 'https://pm.test.papssnet.papss.com/papss/api/v1/outbward/txnstatusquery'
    transaction: 'https://pm.test.papssnet.papss.com/papss/api/v1/outbward/fundstransfercredit'

# Account Details
accounts:
  credit-gl: "0810262907103"
  commission-gl: "0000000000"

limits:
  outbound:
    max-transaction-limit: 999999
    daily-transaction-limit: 999999
    velocity-limit: 99999999