logging:
  level:
    ROOT: INFO
    org.jpos: INFO
    org.hibernate: INFO

# ------------------------------------------------------------
# FINACLE CONFIGURATION
# ------------------------------------------------------------
finacle:
  fi:
    ke-url: 'https://finacleprod1j2eefi.ebsafrica.com:30600/FISERVLET/fihttp'
  iso:
    timeout:
      connectTimeout: 10000    # Timeout in ms for establishing connection
      socketTimeout: 50000     # Timeout in ms for waiting for response
    echo:
      timeout: 5000 # Timeout in ms for echo service waiting for response

# ------------------------------------------------------------
# FX RATE CONFIG
# ------------------------------------------------------------
fx-rate:
  delay:
    ms: 300000
  initial:
    delay:
      ms: 4000

# ------------------------------------------------------------
# JPOS CONFIG
# ------------------------------------------------------------
jpos:
  tm:
    # Max number of Transaction Managers allowed.
    max-tms: 50

    # Queue depth threshold. If all active TM queues exceed this, a new TM is created.
    # This counts incoming transactions not yet picked up (backlog), distinct from TM's internal 'sessions'.
    queue-depth-threshold: 10

    # The ABSOLUTE path to jPOS Q2's deploy directory where TM templates and instances are located.
    q2-tm-dir: "/app/home/upgtp/papss-outbound-technical-service-ms/deploy"

    # The *relative path* within the 'q2-deploy-dir' where states.xml is located.
    q2-states-relative-path: "cfg"

    # Filename prefix for generated TM XMLs.
    tm-filename-prefix: "transaction-manager-tm-"

    # Queue name prefix for TMs.
    tm-queue-prefix: "transaction-manager-queue-q"

    # Relative path to TM template file within deploy-dir. Must be manually placed there.
    tm-template-relative-path: "cfg/transaction-manager-tm-template.xml"

    # Timeout in milliseconds for dispatching to jPOS space/queue
    dispatch-timeout-ms: 10000

# ------------------------------------------------------------
# HTTPS RUNTIME CONFIG
# ------------------------------------------------------------
server:
  port: 10443
  ssl:
    enabled: true

    # Keystore containing Equity private key and DigiCert-issued client certificate. Required for TLS setup within the application runtime
    key-store: '/app/home/upgtp/certs/PAPSS/keystores/papss_equitygroupholdings_com.jks'
    key-store-password: ${PAPSS_KEYSTORE_PASSWORD}
    key-store-type: 'JKS'
    key-alias: ${PAPSS_KEY_ALIAS}

    # Truststore containing PAPSS, OMNI, and other partner certificates
    trust-store: '/app/home/upgtp/certs/PAPSS/keystores/truststore-papss-prod.jks'
    trust-store-password: ${PAPSS_TRUSTSTORE_PASSWORD}
    trust-store-type: 'JKS'

    # Application-level aliases (used by the application, not by TLS itself)
    trust-aliases:
      omni: 'omni'
      remittance: 'remittance'

# -------------------------------------------------------------------
# PAPSS cryptographic configuration
# Used for:
#  - Outbound mTLS authentication to PAPSS
#  - ISO 20022 XML digital signature generation
# -------------------------------------------------------------------
papss:
  equity-bank-id: 'KE100030'
  fx-rate-name: 'KE100030-SSA_3-DEF-KES-USD'
  signing:
    # Keystore containing Equity private key and DigiCert-issued client certificate. Used for mTLS and signing service for XML signatures
    key-store: '/app/home/upgtp/certs/PAPSS/keystores/papss_equitygroupholdings_com.jks'
    key-store-password: ${PAPSS_KEYSTORE_PASSWORD}
    key-store-type: 'JKS'
    key-alias: ${PAPSS_KEY_ALIAS}

  ssl:
    # Truststore used by Apache HttpClient to validate PAPSS HTTPS certificates
    trust-store: '/app/home/upgtp/certs/PAPSS/keystores/truststore-papss-prod.jks'
    trust-store-password: ${PAPSS_TRUSTSTORE_PASSWORD}
    trust-store-type: 'JKS'

# ------------------------------------------------------------
# TLS FLAGS
# ------------------------------------------------------------
http:
  ssl:
    trust-all: false
    skip-hostname-verification: true

## PAPSS message signing configs
#papss:
#  equity-bank-id: 'KE100030'
#  fx-rate-name: 'KE100030-SSA_3-DEF-KES-USD'
#  signing:
#    key-store: '/app/home/upgtp/certs/PAPSS/keystores/EQUITYY-c1.p12'
#    key-store-password: 'secure'
#    key-store-type: 'PKCS12'
#    key-alias: 'equityy'
#  ssl:
#    trust-store: '/app/home/upgtp/certs/PAPSS/keystores/papss_truststore.p12'
#    trust-store-password: 'changeit'
#    trust-store-type: 'PKCS12'

# enable this if you want to skip host verification, or trust all certs during mtls handshake
#http:
#  ssl:
#    trust-all: false
#    skip-hostname-verification: true

# ------------------------------------------------------------
# ASYNC THREAD POOL
# ------------------------------------------------------------
async:
  core-pool-size: 20        # Always keep 20 threads alive
  max-pool-size: 50         # Can burst up to 50 during spikes
  queue-capacity: 5000      # Buffer up to 5k tasks before rejecting
  keep-alive-seconds: 60    # Non-core threads live for 60s when idle

# ------------------------------------------------------------
# DATASOURCE
# ------------------------------------------------------------
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: oracle.jdbc.OracleDriver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

    hikari:
      poolName: Hikari
      auto-commit: false
      maximum-pool-size: 30
      minimum-idle: 10
      idle-timeout: 30000  # Close idle connections after 30s
      connection-timeout: 20000  # Wait max 20s for a connection
      max-lifetime: 1800000  # Recycle connections every 30 mins
      # leak-detection-threshold: 15000  # Detect leaked connections after 15s
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 500
        prepStmtCacheSqlLimit: 4096
        useServerPrepStmts: true
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.OracleDialect
      ddl-auto: validate
    show-sql: false

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

# ------------------------------------------------------------
# PAPSS ENDPOINTS
# ------------------------------------------------------------
service:
  urls:
    common-url: 'https://pm.prod.papssnet.papss.com/papss/Message'
    fx-rate-base-url: 'https://pm.prod.papssnet.papss.com/papss/FXRate'
    post-fx-rate-url: 'https://pm.prod.papssnet.papss.com/papss/FXRateApi'
    participants-base-url: 'https://pm.prod.papssnet.papss.com/papss/api/participants'

# ------------------------------------------------------------
# ACCOUNT DETAILS
# ------------------------------------------------------------
accounts:
  credit-gl:
    papss-settlement:
      kes: ${PAPSS_SETTLEMENT_KES}
      usd: ${PAPSS_SETTLEMENT_USD}
    bank-income:
      kes: ${PAPSS_BANK_INCOME_KES}
      usd: ${PAPSS_BANK_INCOME_KES}

# ------------------------------------------------------------
# LIMITS
# ------------------------------------------------------------
limits:
  outbound:
    max-transaction-limit: 999999
    daily-transaction-limit: 999999
    velocity-limit: 99999999
