logging:
  level:
    ROOT: INFO
    org.jpos: INFO
    org.hibernate: INFO

# Finacle configs
finacle:
  fi:
    ke-url: 'https://finaclepreprodweb.ebsafrica.com:11500/FISERVLET/fihttp'
  iso:
    timeout:
      connectTimeout: 10000    # Timeout in ms for establishing connection
      socketTimeout: 50000     # Timeout in ms for waiting for response
    echo:
      timeout: 5000 # Timeout in ms for echo service waiting for response

# Fx rate updater delays
fx-rate:
  delay:
    ms: 300000
  initial:
    delay:
      ms: 4000

jpos:
  tm:
    # Max number of Transaction Managers allowed.
    max-tms: 50

    # Queue depth threshold. If all active TM queues exceed this, a new TM is created.
    # This counts incoming transactions not yet picked up (backlog), distinct from TM's internal 'sessions'.
    queue-depth-threshold: 10

    # The ABSOLUTE path to jPOS Q2's deploy directory where TM templates and instances are located.
    q2-tm-dir: "/u01/gag/papss/papss-outbound-technical-service-ms/deploy"

    # The *relative path* within the 'q2-deploy-dir' where states.xml is located.
    q2-states-relative-path: "cfg"

    # Filename prefix for generated TM XMLs.
    tm-filename-prefix: "transaction-manager-tm-"

    # Queue name prefix for TMs.
    tm-queue-prefix: "transaction-manager-queue-q"

    # Relative path to TM template file within deploy-dir. Must be manually placed there.
    tm-template-relative-path: "cfg/transaction-manager-tm-template.xml"

    # Timeout in milliseconds for dispatching to jPOS space/queue
    dispatch-timeout-ms: 10000

# ssl configs
server:
  port: 10443
  ssl:
    enabled: true
    key-store: '/u01/gag/papss/certs/papss-equitygroup.p12'
    key-store-password: 'papss-equitygroup!'
    key-store-type: 'PKCS12'
    key-alias: 'papss-equitygroup'
    trust-store: '/u01/gag/papss/certs/truststore-papss-equitygroup.p12'
    trust-store-password: 'papss-equity!'
    trust-store-type: 'PKCS12'
    trust-aliases:
      omni: 'omni'
      remittance: 'remittance'

# PAPSS message signing configs
papss:
  equity-bank-id: 'KE1011'
  fx-rate-name: 'KE1011-SSA_3-DEF-KES-USD'
  signing:
    key-store: '/u01/gag/papss/certs/EQUITYY-c1.p12'
    key-store-password: 'secure'
    key-store-type: 'PKCS12'
    key-alias: 'equityy'
  ssl:
    trust-store: '/u01/gag/papss/certs/papss_truststore.p12'
    trust-store-password: 'changeit'
    trust-store-type: 'PKCS12'

# enable this if you want to skip host verification, or trust all certs during mtls handshake
http:
  ssl:
    trust-all: false
    skip-hostname-verification: true

# Async thread configs
async:
  core-pool-size: 20        # Always keep 20 threads alive
  max-pool-size: 50         # Can burst up to 50 during spikes
  queue-capacity: 5000      # Buffer up to 5k tasks before rejecting
  keep-alive-seconds: 60    # Non-core threads live for 60s when idle

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: oracle.jdbc.OracleDriver
    url: ${CD_SPRING_DATASOURCE_URL}
    username: ${CD_SPRING_DATASOURCE_USERNAME}
    password: ${CD_SPRING_DATASOURCE_PASSWORD}

#    url: 'jdbc:oracle:thin:@10.1.9.178:1540:c4testdb'
#    username: 'eneza'
#    password: 'welcome1'
    hikari:
      poolName: Hikari
      auto-commit: false
      maximum-pool-size: 30
      minimum-idle: 10
      idle-timeout: 30000  # Close idle connections after 30s
      connection-timeout: 20000  # Wait max 20s for a connection
      max-lifetime: 1800000  # Recycle connections every 30 mins
      # leak-detection-threshold: 15000  # Detect leaked connections after 15s
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 500
        prepStmtCacheSqlLimit: 4096
        useServerPrepStmts: true
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.OracleDialect
      ddl-auto: validate
    show-sql: false

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

# PAPSS Urls
service:
  urls:
    common-url: 'https://pm.test.papssnet.papss.com/papss/Message'
    fx-rate-base-url: 'https://pm.test.papssnet.papss.com/papss/FXRate'
    post-fx-rate-url: 'https://pm.test.papssnet.papss.com/papss/FXRateApi'
    participants-base-url: 'https://pm.test.papssnet.papss.com/papss/api/participants'

# Account Details
accounts:
  credit-gl:
    papss-settlement:
      kes: '0001100407023'
      usd: '0001100407024'
    bank-income:
      kes: '0006500607025'
      usd: '0006500607025'

limits:
  outbound:
    max-transaction-limit: 999999
    daily-transaction-limit: 999999
    velocity-limit: 99999999


