package com.equitybank.gag.papss.its.jpos.iso8583.packager;

import org.jpos.iso.*;

/**
 * FinPackagersFinacle is a custom ISO 8583 packager for handling ISO 8583 messages
 * specific to the Finacle system. It extends the ISOBasePackager and defines
 * a comprehensive set of ISO 8583 fields with appropriate field types and lengths.
 */
public class FinaclePackager extends ISOBasePackager {
    private static final boolean pad = false;
    protected ISOFieldPackager fld[] = {
            /*000*/ new IFA_NUMERIC(4, "Message Type Indicator"),
            /*001*/ new IFB_BITMAP(16, "Bitmap"),
            /*002*/ new IFA_LLNUM(19, "Primary Account number"),
            /*003*/ new IFA_NUMERIC(6, "Processing Code"),
            /*004*/ new IFA_NUMERIC(12, "Amount, Transaction"),
            /*005*/ new IFB_NUMERIC(12, "Amount, Reconciliation", pad),
            /*006*/ new IFB_NUMERIC(3, "Amount, Cardholder billing", pad),
            /*007*/ new IFA_NUMERIC(10, "Date and time, transmission"),
            /*008*/ new IFB_NUMERIC(8, "Amount, Cardholder billing fee", pad),
            /*009*/ new IFB_NUMERIC(8, "Conversion rate, Reconciliation", pad),
            /*010*/ new IFB_NUMERIC(8, "Conversion rate, Cardholder billing", pad),
            /*011*/ new IFA_NUMERIC(6, "Systems trace audit number"),
            /*012*/ new IFA_NUMERIC(12, "Date and time, Local transaction"),
            /*013*/ new IFB_NUMERIC(2, "Date, Effective", pad),
            /*014*/ new IFB_NUMERIC(2, "Date, Expiration", pad),
            /*015*/ new IFB_NUMERIC(4, "Date, Settlement", pad),
            /*016*/ new IFB_NUMERIC(4, "Date, Conversion", pad),
            /*017*/ new IFA_NUMERIC(4, "Date, Capture"),
            /*018*/ new IFB_NUMERIC(4, "Merchant type", pad),
            /*019*/ new IFB_NUMERIC(3, "Country code, Acquiring institution", pad),
            /*020*/ new IFB_NUMERIC(3, "Country code, Primary account number", pad),
            /*021*/ new IFB_NUMERIC(3, "Country code, Forwarding institution", pad),
            /*022*/ new IFB_NUMERIC(4, "Point of isoservice data code", pad),
            /*023*/ new IFB_NUMERIC(2, "Card sequence number", pad),
            /*024*/ new IFA_NUMERIC(3, "Function code"),
            /*025*/ new IFB_NUMERIC(2, "Message reason code", pad),
            /*026*/ new IFB_NUMERIC(2, "Card acceptor business code", pad),
            /*027*/ new IFB_NUMERIC(1, "Approval code length", pad),
            /*028*/ new IFB_NUMERIC(9, "Date, Reconciliation", pad),
            /*029*/ new IFB_NUMERIC(9, "Reconciliation indicator", pad),
            /*030*/ new IFB_NUMERIC(9, "Amounts, original", pad),
            /*031*/ new IFB_NUMERIC(9, "Acquirer reference data", pad),
            /*032*/ new IFA_LLNUM(12, "Acquirer institution ident code"),
            /*033*/ new IFB_LLNUM(99, "Forwarding institution ident code", pad),
            /*034*/ new IFB_LLNUM(99, "Primary account number, extended", pad),
            /*035*/ new IFA_LLNUM(37, "Track 2 data"),
            /*036*/ new IFB_LLLNUM(104, "Track 3 data", pad),
            /*037*/ new IF_CHAR(12, "Retrieval reference number"),
            /*038*/ new IF_CHAR(6, "Approval code"),
            /*039*/ new IF_CHAR(3, "Action code"),
            /*040*/ new IF_CHAR(3, "Service code"),
            /*041*/ new IF_CHAR(8, "Card acceptor terminal identification"),
            /*042*/ new IF_CHAR(15, "Card acceptor identification code"),
            /*043*/ new IFA_LLCHAR(40, "Card acceptor name/location"),
            /*044*/ new IFA_LLCHAR(20, "Additional response data"),
            /*045*/ new IFA_LLCHAR(76, "Track 1 data"),
            /*046*/ new IFA_LLLCHAR(204, "Amounts, Fees"),
            /*047*/ new IFA_LLLCHAR(999, "Additional data - national"),
            /*048*/ new IFA_LLLCHAR(999, "Additional data - private"),
            /*049*/ new IF_CHAR(3, "Currency code, Transaction"),
            /*050*/ new IF_CHAR(3, "Currency code, Reconciliation"),
            /*051*/ new IF_CHAR(3, "Currency code, Cardholder billing"),
            /*052*/ new IFB_NUMERIC(8, "Personal identification number (PIN) data", pad),
            /*053*/ new IFB_NUMERIC(10, "Security related control information", pad),
            /*054*/ new IFB_LLCHAR(99, "Amounts, additional"),
            /*055*/ new IFA_LLLBINARY(255, "IC card system related data"),
            /*056*/ new IFA_LLNUM(36, "Original data elements"),//2011-06-16 Changed from 35 to 36
            /*057*/ new IFA_NUMERIC(3, "Authorization life cycle code"),
            /*058*/ new IFA_LLNUM(11, "Authorizing agent institution Id Code"),
            /*059*/ new IFA_LLLCHAR(999, "Transport data"),
            /*060*/ new IFB_LLLCHAR(999, "Reserved for national use"),
            /*061*/ new IFA_LLLCHAR(999, "Reserved for national use"),
            /*062*/ new IFA_LLLCHAR(999, "Reserved for private use"),
            /*063*/ new IFB_LLNUM(25, "Reserved for private use", pad),
            /*064*/ new IFA_BINARY(8, "Message authentication code field"),
            /*065*/ new IFA_BINARY(8, "Reserved for ISO use"),
            /*066*/ new IFA_LLLCHAR(204, "Amounts, original fees"),
            /*067*/ new IFA_NUMERIC(2, "Extended payment data"),
            /*068*/ new IFA_NUMERIC(3, "Country code, receiving institution"),
            /*069*/ new IFA_NUMERIC(3, "Country code, settlement institution"),
            /*070*/ new IFA_NUMERIC(3, "Country code, authorizing agent Inst."),
            /*071*/ new IFA_NUMERIC(8, "Message number"),
            /*072*/ new IFA_LLLCHAR(999, "Data record"),
            /*073*/ new IFA_NUMERIC(6, "Date, action"),
            /*074*/ new IFA_NUMERIC(10, "Credits, number"),
            /*075*/ new IFA_NUMERIC(10, "Credits, reversal number"),
            /*076*/ new IFA_NUMERIC(10, "Debits, number"),
            /*077*/ new IFA_NUMERIC(10, "Debits, reversal number"),
            /*078*/ new IFA_NUMERIC(10, "Transfer, number"),
            /*079*/ new IFA_NUMERIC(10, "Transfer, reversal number"),
            /*080*/ new IFA_NUMERIC(10, "Inquiries, number"),
            /*081*/ new IFA_NUMERIC(10, "Authorizations, number"),
            /*082*/ new IFA_NUMERIC(10, "Inquiries, reversal number"),
            /*083*/ new IFA_NUMERIC(10, "Payments, number"),
            /*084*/ new IFA_NUMERIC(10, "Payments, reversal number"),
            /*085*/ new IFA_NUMERIC(10, "Fee collections, number"),
            /*086*/ new IFA_NUMERIC(16, "Credits, amount"),
            /*087*/ new IFA_NUMERIC(16, "Credits, reversal amount"),
            /*088*/ new IFA_NUMERIC(16, "Debits, amount"),
            /*089*/ new IFA_NUMERIC(16, "Debits, reversal amount"),
            /*090*/ new IFA_NUMERIC(10, "Authorizations, reversal number"),
            /*091*/ new IFA_NUMERIC(3, "Country code, transaction Dest. Inst."),
            /*092*/ new IFA_NUMERIC(3, "Country code, transaction Orig. Inst."),
            /*093*/ new IFA_LLNUM(11, "Transaction Dest. Inst. Id code"),
            /*094*/ new IFA_LLNUM(11, "Transaction Orig. Inst. Id code"),
            /*095*/ new IFA_LLCHAR(99, "Card issuer reference data"),
            /*096*/ new IFA_LLLBINARY(999, "Key management data"),
            /*097*/ new IFA_AMOUNT(1 + 16, "Amount, Net reconciliation"),
            /*098*/ new IF_CHAR(25, "Payee"),
            /*099*/ new IFA_LLCHAR(11, "Settlement institution Id code"),
            /*100*/ new IFA_LLNUM(11, "Receiving institution Id code"),
            /*101*/ new IFA_LLCHAR(17, "File name"),
            /*102*/ new IFA_LLCHAR(20, "Account identification 1"),
            /*103*/ new IFA_LLCHAR(28, "Account identification 2"),
            /*104*/ new IFA_LLLCHAR(100, "Transaction description"),
            /*105*/ new IFA_NUMERIC(16, "Credits, Chargeback amount"),
            /*106*/ new IFA_NUMERIC(16, "Debits, Chargeback amount"),
            /*107*/ new IFA_NUMERIC(10, "Credits, Chargeback number"),
            /*108*/ new IFA_NUMERIC(10, "Debits, Chargeback number"),
            /*109*/ new IFA_LLCHAR(84, "Credits, Fee amounts"),
            /*110*/ new IFA_LLCHAR(84, "Debits, Fee amounts"),
            /*111*/ new IFA_LLLCHAR(999, "Reserved for ISO use"),
            /*112*/ new IFA_LLLCHAR(999, "Reserved for ISO use"),
            /*113*/ new IFA_LLLCHAR(999, "Reserved for ISO use"),
            /*114*/ new IFA_LLLCHAR(999, "Reserved for ISO use"),
            /*115*/ new IFA_LLLCHAR(999, "Reserved for ISO use"),
            /*116*/ new IFA_LLLCHAR(999, "Reserved for national use"),
            /*117*/ new IFA_LLLCHAR(999, "Reserved for national use"),
            /*118*/ new IFA_LLLCHAR(999, "Reserved for national use"),
            /*119*/ new IFB_LLLCHAR(999, "Reserved for national use"),
            /*120*/ new IFB_LLLCHAR(999, "Reserved for national use"),
            /*121*/ new IFB_LLLCHAR(999, "Reserved for national use"),
            /*122*/ new IFB_LLLCHAR(999, "Reserved for national use"),
            /*123*/ new IFA_LLLCHAR(999, "Reserved for private use"),
            /*124*/ new IFA_LLLCHAR(999, "Reserved for private use"),
            /*125*/ new IFA_LLLCHAR(999, "Reserved for private use"),
            /*126*/ new IFA_LLLCHAR(999, "Reserved for private use"),
            /*127*/ new IFA_LLLCHAR(999, "Reserved for private use"),
            /*128*/ new IFB_BINARY(8, "Message authentication code field")
    };

    public FinaclePackager() {
        super();
        setFieldPackager(fld);
    }
}

