DROP TABLE CUSTOM.AUDIT_MERCHANTS_TABLE CASCADE CONSTRAINTS;

CREATE TABLE CUSTOM.AUDIT_MERCHANTS_TABLE
(
  CHANNEL_ID                VARCHAR2(10 BYTE),
  MERCHANT_DESC             VARCHAR2(100 BYTE),
  MERCHANT_ID               VARCHAR2(100 BYTE),
  MERCH_PURCHASE_PAYABLE    VARCHAR2(16 BYTE),
  MERCH_CASHBACK_PAYABLE    VARCHAR2(16 BYTE),
  MERCH_COMM_PAYABLE        VARCHAR2(16 BYTE),
  MERCH_SETTLEMENT_ACCOUNT  VARCHAR2(16 BYTE),
  MERCH_CASHBACK_COMM       VARCHAR2(5 BYTE),
  MERCH_PURCHASE_COMM       VARCHAR2(5 BYTE),
  ENTERER_ID                VARCHAR2(15 BYTE),
  ENTERER_DATE              DATE,
  VFD_USER_ID               VARCHAR2(15 BYTE),
  VFD_DATE                  DATE,
  AUDIT_SRL_NUM             VARCHAR2(100 BYTE),
  AUDIT_BOD_DATE            DATE,
  FUNC_CODE                 CHAR(1 BYTE),
  BANK_ID                   VARCHAR2(8 CHAR)
);

CREATE INDEX CUSTOM.IDX_AMERCHANTS_AUDITSRLNUM ON CUSTOM.AUDIT_MERCHANTS_TABLE
(AUDIT_SRL_NUM);


CREATE INDEX CUSTOM.IDX_AMERCHANTS_MERCHANID ON CUSTOM.AUDIT_MERCHANTS_TABLE
(MERCHANT_ID, BANK_ID);

DROP SYNONYM CUSTOM.C_AMERCHANTS;

CREATE SYNONYM CUSTOM.C_AMERCHANTS FOR CUSTOM.AUDIT_MERCHANTS_TABLE;



DROP PUBLIC SYNONYM C_AMERCHANTS;

CREATE PUBLIC SYNONYM C_AMERCHANTS FOR CUSTOM.AUDIT_MERCHANTS_TABLE;

GRANT SELECT ON CUSTOM.AUDIT_MERCHANTS_TABLE TO ALLTAB;


GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.AUDIT_MERCHANTS_TABLE TO TBAGEN;


GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.AUDIT_MERCHANTS_TABLE TO TBAUTIL;

