CREATE TABLE CUSTOM.CUST_CHQ_MAINT_TABLE
(
  REQ_ID          VARCHAR2(9 BYTE),
  FORACID         VARCHAR2(16 BYTE),
  BRANCH_ID       VARCHAR2(8 BYTE),
  BEGIN_CHQ_NUM   VARCHAR2(8 BYTE),
  NUM_OF_CHB      NUMBER(4),
  NUM_OF_CHQ_LVS  NUMBER(4),
  AUTH_USER_ID    VARCHAR2(15 BYTE),
  REQ_STATUS      CHAR(1 BYTE),
  REQ_DATE        DATE,
  DOWNLOAD_ID     VARCHAR2(15 BYTE),
  DOWNLOAD_DATE   DATE,
  LCHG_USER_ID    VARCHAR2(15 BYTE),
  LCHG_TIME       DATE,
  RCRE_USER_ID    VARCHAR2(15 BYTE),
  RCRE_TIME       DATE,
  DEL_FLG         CHAR(1 BYTE),
  BANK_ID         VARCHAR2(3 BYTE),
  BOOK_SIZE       VARCHAR2(20 BYTE)
);


CREATE SYNONYM CUSTOM.CUSTOM_CBR FOR CUSTOM.CUST_CHQ_MAINT_TABLE;


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON CUSTOM.CUST_CHQ_MAINT_TABLE TO TBAADM;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON CUSTOM.CUST_CHQ_MAINT_TABLE TO TBAGEN;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON CUSTOM.CUST_CHQ_MAINT_TABLE TO TBAUTIL;
