DROP TABLE CUSTOM.ADT_CUSTOM CASCADE CONSTRAINTS;

CREATE TABLE CUSTOM.ADT_CUSTOM
(
  REF_NUM               VARCHAR2(15 BYTE),
  TABLE_NAME            VARCHAR2(12 BYTE),
  TABLE_KEY             VARCHAR2(100 BYTE),
  AUDIT_SRL_NUM         VARCHAR2(3 BYTE),
  AUDIT_SOL_ID          VARCHAR2(8 BYTE),
  ACID                  VARCHAR2(11 BYTE),
  GL_SUB_HEAD_CODE      VARCHAR2(5 BYTE),
  ENTERER_ID            VARCHAR2(15 BYTE),
  AUTH_ID               VARCHAR2(15 BYTE),
  RMKS                  VARCHAR2(100 BYTE),
  AUDIT_DATE            VARCHAR2(100 BYTE),
  MODIFIED_FIELDS_DATA  VARCHAR2(240 BYTE),
  FUNC_CODE             VARCHAR2(10 BYTE),
  INIT_SOL_ID           VARCHAR2(8 BYTE),
  AUDIT_BOD_DATE        VARCHAR2(100 BYTE),
  CALLER_MODULE         VARCHAR2(10 BYTE),
  REFERRAL_ID           VARCHAR2(12 BYTE),
  BANK_ID               VARCHAR2(8 BYTE),
  AUTH_DATE             VARCHAR2(100 BYTE),
  AUTH_BOD_DATE         VARCHAR2(100 BYTE),
  MOP_ID                VARCHAR2(8 BYTE)
);

