--DROP TABLE CUSTOM.CUST_SAL_UPLD_PROCESS_TABLE CASCADE CONSTRAINTS;

CREATE TABLE CUSTOM.CUST_SAL_UPLD_PROCESS_TABLE
(
  EMPLOYER         VARCHAR2(10 BYTE),
  EMPLOYEE_ID      VARCHAR2(15 BYTE),
  UPL_ACCT_NO      VARCHAR2(16 BYTE),
  ACCT_CRNCY_CODE  VARCHAR2(3 BYTE),
  UPL_ACCT_NAME    VARCHAR2(80 BYTE),
  SAL_CR_AMT       NUMBER(20,4),
  TRAN_PARTICULAR  VARCHAR2(50 BYTE),
  SOL_ID           VARCHAR2(8 BYTE),
  FORACID          VARCHAR2(16 BYTE),
  UPL_KEY          VARCHAR2(6 BYTE),
  UPL_DATE         DATE,
  UPL_STATUS       CHAR(1 BYTE),
  LCHG_USER_ID     VARCHAR2(15 BYTE),
  LCHG_TIME        DATE,
  RCRE_USER_ID     VARCHAR2(15 BYTE),
  RCRE_TIME        DATE,
  CHRG_FLG         CHAR(1 BYTE),
  DEL_FLG          CHAR(1 BYTE),
  INVALID          VARCHAR2(2 BYTE),
  RMK              VARCHAR2(100 BYTE),
  GAM_ACCT         VARCHAR2(80 BYTE),
  GAM_EMP_ID       VARCHAR2(10 BYTE),
  Batch            Varchar2(1 Byte),
  Gam_Sol_Id       Varchar2(8 Byte),
  BANK_ID           Varchar2(8 Byte)
)
TABLESPACE CUSTOM_TBLS
PCTUSED    40
PCTFREE    10
INITRANS   50
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        32
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
NOMONITORING;



CREATE INDEX CUSTOM.IDX_C_SUP_EMPLOYER ON CUSTOM.CUST_SAL_UPLD_PROCESS_TABLE
(EMPLOYER, UPL_STATUS, CHRG_FLG, DEL_FLG,BANK_ID)
LOGGING
TABLESPACE CUSTOM_IDXSPACE
PCTFREE    10
INITRANS   50
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        32
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX CUSTOM.IDX_C_SUP_FORACID ON CUSTOM.CUST_SAL_UPLD_PROCESS_TABLE
(FORACID, BANK_ID)
LOGGING
TABLESPACE CUSTOM_IDXSPACE
PCTFREE    10
INITRANS   50
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        32
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX CUSTOM.IDX_C_SUP_UPL_ACCT_NO ON CUSTOM.CUST_SAL_UPLD_PROCESS_TABLE
(UPL_ACCT_NO, SOL_ID, BANK_ID)
LOGGING
TABLESPACE CUSTOM_IDXSPACE
PCTFREE    10
INITRANS   50
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        32
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX CUSTOM.IDX_C_EMP_USR ON CUSTOM.CUST_SAL_UPLD_PROCESS_TABLE
(EMPLOYER, RCRE_USER_ID, BANK_ID)
NOLOGGING
TABLESPACE CUSTOM_IDXSPACE
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        32
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

DROP SYNONYM  custom.C_SUP;

CREATE SYNONYM custom.C_SUP  FOR custom.CUST_SAL_UPLD_PROCESS_TABLE;

Grant Delete, Insert, Select, Update On Custom.CUST_SAL_UPLD_PROCESS_TABLE To Tbagen,Tbautil,Tbaadm;




