CREATE TABLE CUSTOM.UNIV_DATA
(
  ACCTNUM         VARCHAR2(15 BYTE),
  REFNUM          VARCHAR2(25 BYTE),
  NAME            VARCHAR2(300 BYTE),
  ENTERER_ID      VARCHAR2(15 BYTE),
  AUDIT_DATE      DATE,
  AUDIT_BOD_DATE  TIMESTAMP(6) WITH LOCAL TIME ZONE,
  FUNC            VARCHAR2(1 BYTE),
  BANK_Id	  VARCHAR2(8 CHAR)
)
TABLESPACE CUSTOM_TBLS
PCTUSED    40
PCTFREE    10
INITRANS   50
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        32
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;

CREATE SYNONYM CUSTOM.C_UNIV FOR CUSTOM.UNIV_DATA;

GRANT ALL ON CUSTOM.UNIV_DATA TO TBAADM,TBAGEN,TBAUTIL;


