CREATE TABLE CUSTOM.INTERENTITY_CLG_DETAIL_TBL
(
  ZONE_CODE                VARCHAR2(10 CHAR),
  ZONE_DATE                DATE,
  SOL_ID                   VARCHAR2(8 CHAR),
  ZONE_CCY                 VARCHAR2(3 CHAR),
  SET_NUM                  VARCHAR2(6 CHAR),
  BANK_ID                  VARCHAR2(8 CHAR),
  CREDIT_ENTITY            VARCHAR2(8 CHAR),
  CR_ACCOUNT_ID            VARCHAR2(16 CHAR),
  INSTRMNT_ENTITY          VARCHAR2(8 CHAR),
  INSTRMNT_ALPHA           VARCHAR2(6 CHAR),
  INSTRMNT_DATE            DATE,
  INSTRMNT_NUM             VARCHAR2(16 CHAR),
  INSTRMNT_AMT             NUMBER(20,4),
  INSTRMNT_BANK_CODE       VARCHAR2(6 CHAR),
  INSTRMNT_BR_CODE         VARCHAR2(6 CHAR),
  INSTRMNT_SORT_CODE       VARCHAR2(9 CHAR),
  CHARGE_EVENT_ID          VARCHAR2(25 CHAR),
  CHARGE_AMT               NUMBER(20,4),
  CHARGE_CRNCY_CODE        VARCHAR2(3 CHAR),
  VALUE_DATE               DATE,
  TARGET_ZONE_CODE         VARCHAR2(10 CHAR),
  TARGET_ZONE_DATE         DATE,
  TARGET_SOL_ID            VARCHAR2(8 CHAR),
  TARGET_SET_NUM           VARCHAR2(6 CHAR),
  BANK_CODE                VARCHAR2(6 CHAR),
  BR_CODE                  VARCHAR2(6 CHAR),
  SORT_CODE                VARCHAR2(9 CHAR),
  NOSTRO_ACCOUNT_ID        VARCHAR2(16 CHAR),
  VOSTRO_ACCOUNT_ID        VARCHAR2(16 CHAR),
  PAYING_ACCOUNT_ID        VARCHAR2(16 CHAR),
  TRAN_PARTICULAR          VARCHAR2(50 CHAR),
  TRAN_RMKS                VARCHAR2(30 CHAR),
  REVERSE_FLG              CHAR(1 BYTE),
  STATUS_FLG               CHAR(1 BYTE),
  ENTITY1_TRAN_ID          VARCHAR2(9 CHAR),
  ENTITY1_TRAN_DATE        DATE,
  ENTITY2_TRAN_ID          VARCHAR2(9 CHAR),
  ENTITY2_TRAN_DATE        DATE,
  CHARGE_TRAN_ID           VARCHAR2(9 CHAR),
  CHARGE_TRAN_DATE         DATE,
  TARGET_CHARGE_TRAN_ID    VARCHAR2(9 CHAR),
  TARGET_CHARGE_TRAN_DATE  DATE,
  REJECT_REASON_CODE       VARCHAR2(2 CHAR),
  LCHG_USER_ID             VARCHAR2(15 CHAR),
  LCHG_TIME                DATE,
  RCRE_USER_ID             VARCHAR2(15 CHAR),
  RCRE_TIME                DATE,
  UBP_REF_NUM              VARCHAR2(20 CHAR)
);


CREATE SYNONYM TBAADM.INTERENTITY_CLG_DETAIL_TBL FOR CUSTOM.INTERENTITY_CLG_DETAIL_TBL;


CREATE SYNONYM TBAGEN.INTERENTITY_CLG_DETAIL_TBL FOR CUSTOM.INTERENTITY_CLG_DETAIL_TBL;


CREATE SYNONYM TBAUTIL.INTERENTITY_CLG_DETAIL_TBL FOR CUSTOM.INTERENTITY_CLG_DETAIL_TBL;


CREATE SYNONYM TBAADM.IECD FOR CUSTOM.INTERENTITY_CLG_DETAIL_TBL;


CREATE SYNONYM TBAGEN.IECD FOR CUSTOM.INTERENTITY_CLG_DETAIL_TBL;


CREATE SYNONYM TBAUTIL.IECD FOR CUSTOM.INTERENTITY_CLG_DETAIL_TBL;


CREATE SYNONYM CUSTOM.IECD FOR CUSTOM.INTERENTITY_CLG_DETAIL_TBL;


GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.INTERENTITY_CLG_DETAIL_TBL TO TBAGEN;

GRANT SELECT ON CUSTOM.INTERENTITY_CLG_DETAIL_TBL TO TBAUTIL;
