DROP SEQUENCE CUSTOM.RTGS_AUTO_SEQUENCE;

CREATE SEQUENCE CUSTOM.RTGS_AUTO_SEQUENCE
  START WITH 80879
  MAXVALUE 99999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

GRANT SELECT ON CUSTOM.RTGS_AUTO_SEQUENCE TO FINACLEESB;

GRANT SELECT ON CUSTOM.RTGS_AUTO_SEQUENCE TO POLARISEFT;

GRANT SELECT ON CUSTOM.RTGS_AUTO_SEQUENCE TO TBAADM;

GRANT SELECT ON CUSTOM.RTGS_AUTO_SEQUENCE TO TBAGEN;
