CREATE TABLE CUSTOM.C_CPARAM_VALUE_TABLE
(
  PARAMETER_ID     VARCHAR2(30 BYTE),
  LEVELCODE_1      VARCHAR2(8 BYTE),
  LEVELCODE_2      VARCHAR2(8 BYTE),
  PARAMETER_VALUE  VARCHAR2(500 BYTE),
  ENTITY_CRE_FLG   CHAR(1 BYTE),
  DEL_FLG          CHAR(1 BYTE),
  RCRE_USER_ID     VARCHAR2(15 BYTE),
  RCRE_TIME        DATE,
  LCHG_USER_ID     VARCHAR2(15 BYTE),
  LCHG_TIME        DATE,
  BANK_ID          VARCHAR2(10 CHAR)            NOT NULL,
  MODULE_NAME      VARCHAR2(30 BYTE)
);


CREATE UNIQUE INDEX CUSTOM.IDX_C_CPARAM_VALUE ON CUSTOM.C_CPARAM_VALUE_TABLE
(PARAMETER_ID, LEVELCODE_1, LEVELCODE_2, MODULE_NAME, BANK_ID);


CREATE SYNONYM TBAADM.CUST_C_CPARAM_VALUE_TABLE FOR CUSTOM.C_CPARAM_VALUE_TABLE;


CREATE SYNONYM TBAGEN.CUST_C_CPARAM_VALUE_TABLE FOR CUSTOM.C_CPARAM_VALUE_TABLE;


CREATE SYNONYM TBAUTIL.CUST_C_CPARAM_VALUE_TABLE FOR CUSTOM.C_CPARAM_VALUE_TABLE;


CREATE SYNONYM CUSTOM.CUST_C_CPARAM_VALUE_TABLE FOR CUSTOM.C_CPARAM_VALUE_TABLE;


CREATE SYNONYM TBAADM.C_CPVALUE FOR CUSTOM.C_CPARAM_VALUE_TABLE;


CREATE SYNONYM TBAGEN.C_CPVALUE FOR CUSTOM.C_CPARAM_VALUE_TABLE;


CREATE SYNONYM CUSTOM.C_CPVALUE FOR CUSTOM.C_CPARAM_VALUE_TABLE;


CREATE SYNONYM TBAUTIL.C_CPVALUE FOR CUSTOM.C_CPARAM_VALUE_TABLE;


CREATE SYNONYM TBAADM.C_CPARAM_VALUE_TABLE FOR CUSTOM.C_CPARAM_VALUE_TABLE;


CREATE SYNONYM TBAGEN.C_CPARAM_VALUE_TABLE FOR CUSTOM.C_CPARAM_VALUE_TABLE;


CREATE SYNONYM TBAUTIL.C_CPARAM_VALUE_TABLE FOR CUSTOM.C_CPARAM_VALUE_TABLE;


GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.C_CPARAM_VALUE_TABLE TO TBAGEN;

GRANT SELECT ON CUSTOM.C_CPARAM_VALUE_TABLE TO TBAUTIL;
