logging:
  level:
    ROOT: INFO
    com.bishop.microservices.registry: INFO

server:
  port: 8581

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/