logging:
  level:
    ROOT: INFO
    com.equitybank.gag.registry: INFO

spring:
  profiles:
    active: prod
  application:
    name: TELCO-B2C-REGISTRY

server:
  port: 8581

eureka:
  instance:
    appname: telco-b2c-registry
    instanceId: telcoB2cRegistry:${spring.application.instance-id:${random.value}}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    enabled: true
    fetch-registry: false
    register-with-eureka: false
    instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 10
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/
  server:
    # see discussion about enable-self-preservation:
    # https://github.com/jhipster/generator-jhipster/issues/3654
    enable-self-preservation: false
    peer-node-read-timeout-ms: 30000
  dashboard:
    path: /registry
