<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsa="http://www.w3.org/2005/08/addressing/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://cps.huawei.com/cpsinterface/api_requestmgr" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:req="http://cps.huawei.com/cpsinterface/request" xmlns:common="http://cps.huawei.com/cpsinterface/common" xmlns:response="http://cps.huawei.com/cpsinterface/response" targetNamespace="http://cps.huawei.com/cpsinterface/api_requestmgr">
	<wsdl:types>
		<xs:schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:req="http://cps.huawei.com/cpsinterface/request" elementFormDefault="qualified" targetNamespace="http://cps.huawei.com/cpsinterface/api_requestmgr">
			<import namespace="http://cps.huawei.com/cpsinterface/request" schemaLocation="CPSInterface_API_Request.xsd"/>
			<import namespace="http://cps.huawei.com/cpsinterface/response" schemaLocation="CPSInterface_API_Response.xsd"/>
			<xs:element name="Request" type="req:Request"/>
			<xs:element name="Response" type="response:Response"/>
		</xs:schema>
	</wsdl:types>
	<wsdl:message name="RequestMessage">
		<wsdl:part name="RequestMsg" element="tns:Request">
        </wsdl:part>
	</wsdl:message>
	<wsdl:message name="ResponseMessage">
		<wsdl:part name="ResponseMsg" element="tns:Response">
        </wsdl:part>
	</wsdl:message>
	<wsdl:portType name="APIRequestMgrPortType">
		<wsdl:operation name="APIRequest">
			<wsdl:input message="tns:RequestMessage">
            </wsdl:input>
			<wsdl:output message="tns:ResponseMessage">
            </wsdl:output>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="APIRequestMgrBinding" type="tns:APIRequestMgrPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="APIRequest">
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="APIRequestMgrService">
		<wsdl:port name="APIRequestMgrServicePort" binding="tns:APIRequestMgrBinding">
			<soap:address location="http://cps.huawei.com/cpsinterface/request"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
