package com.huawei.cps.cpsinterface.api_requestmgr;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2025-03-03T22:36:55.147+08:00
 * Generated source version: 4.0.3
 *
 */
@WebServiceClient(name = "APIRequestMgrService",
                  wsdlLocation = "file:/Users/ronaldcheruiyot/Documents/java-projects/DRC-PROJECTS/tech-b2c-vodacom-cd-ms/src/main/resources/wsdl/CBPInterface_API_Request.wsdl",
                  targetNamespace = "http://cps.huawei.com/cpsinterface/api_requestmgr")
public class APIRequestMgrService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://cps.huawei.com/cpsinterface/api_requestmgr", "APIRequestMgrService");
    public final static QName APIRequestMgrServicePort = new QName("http://cps.huawei.com/cpsinterface/api_requestmgr", "APIRequestMgrServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/ronaldcheruiyot/Documents/java-projects/DRC-PROJECTS/tech-b2c-vodacom-cd-ms/src/main/resources/wsdl/CBPInterface_API_Request.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(APIRequestMgrService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/Users/ronaldcheruiyot/Documents/java-projects/DRC-PROJECTS/tech-b2c-vodacom-cd-ms/src/main/resources/wsdl/CBPInterface_API_Request.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public APIRequestMgrService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public APIRequestMgrService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public APIRequestMgrService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public APIRequestMgrService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public APIRequestMgrService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public APIRequestMgrService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns APIRequestMgrPortType
     */
    @WebEndpoint(name = "APIRequestMgrServicePort")
    public APIRequestMgrPortType getAPIRequestMgrServicePort() {
        return super.getPort(APIRequestMgrServicePort, APIRequestMgrPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns APIRequestMgrPortType
     */
    @WebEndpoint(name = "APIRequestMgrServicePort")
    public APIRequestMgrPortType getAPIRequestMgrServicePort(WebServiceFeature... features) {
        return super.getPort(APIRequestMgrServicePort, APIRequestMgrPortType.class, features);
    }

}
