package com.huawei.cps.cpsinterface.api_requestmgr;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2025-03-03T22:36:55.089+08:00
 * Generated source version: 4.0.3
 *
 */
@WebService(targetNamespace = "http://cps.huawei.com/cpsinterface/api_requestmgr", name = "APIRequestMgrPortType")
@XmlSeeAlso({com.huawei.cps.cpsinterface.request.ObjectFactory.class, ObjectFactory.class, com.huawei.cps.cpsinterface.response.ObjectFactory.class, com.huawei.cps.cpsinterface.common.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface APIRequestMgrPortType {

    @WebMethod(operationName = "APIRequest")
    @WebResult(name = "Response", targetNamespace = "http://cps.huawei.com/cpsinterface/api_requestmgr", partName = "ResponseMsg")
    public com.huawei.cps.cpsinterface.response.Response apiRequest(

        @WebParam(partName = "RequestMsg", name = "Request", targetNamespace = "http://cps.huawei.com/cpsinterface/api_requestmgr")
        com.huawei.cps.cpsinterface.request.Request requestMsg
    );
}
