DROP TABLE CUSTOM.C_LADISB_PAYOFF_OLDLOAN CASCADE CONSTRAINTS;

CREATE TABLE CUSTOM.C_LADISB_PAYOFF_OLDLOAN
(
  SRNO               VARCHAR2(15 BYTE),
  LOAN_FORACID       VARCHAR2(15 BYTE),
  LOAN_OP_FORACID    VARCHAR2(15 BYTE),
  LA_OP_AMT          NUMBER,
  LA_OP_CRNCY_CODE   VARCHAR2(3 CHAR),
  OLD_FORACID        VARCHAR2(15 BYTE),
  OLD_LA_AMT         NUMBER,
  OLD_LA_CRNCY_CODE  VARCHAR2(3 CHAR),
  PAYOFF_FLG         VARCHAR2(1 CHAR),
  DEL_FLG            VARCHAR2(1 CHAR),
  ENTITY_CRE_FLG     VARCHAR2(1 CHAR),
  RCRE_TIME          DATE,
  LCHG_USER_ID       VARCHAR2(15 BYTE),
  RCRE_USER_ID       VARCHAR2(15 BYTE),
  LCHG_TIME          DATE,
  TRAN_ID            VARCHAR2(15 BYTE),
  BANK_ID            VARCHAR2(3 BYTE)
);

CREATE UNIQUE INDEX CUSTOM.LD_PAYOFF ON CUSTOM.C_LADISB_PAYOFF_OLDLOAN
(LOAN_FORACID, OLD_FORACID, BANK_ID);

GRANT SELECT ON CUSTOM.C_LADISB_PAYOFF_OLDLOAN TO ALLTAB;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.C_LADISB_PAYOFF_OLDLOAN TO TBAADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.C_LADISB_PAYOFF_OLDLOAN TO TBAGEN;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.C_LADISB_PAYOFF_OLDLOAN TO TBAUTIL;
