CREATE TABLE CUSTOM.CUST_UAD_MAIN_TABLE
(
  USER_ID            VARCHAR2(30 BYTE),
  ACTUAL_ROLE_ID     VARCHAR2(30 BYTE),
  TEMPORARY_ROLE_ID  VARCHAR2(30 BYTE),
  EXPIRY_DATE        DATE,
  ENTITY_CRE_FLG     CHAR(1 BYTE),
  DEL_FLG            CHAR(1 BYTE),
  RCRE_USER_ID       VARCHAR2(15 BYTE),
  RCRE_TIME          DATE,
  LCHG_USER_ID       VARCHAR2(15 BYTE),
  LCHG_TIME          DATE,
  BANK_ID            VARCHAR2(8 CHAR),
  ROLLBACK           CHAR(1 BYTE)
);


CREATE UNIQUE INDEX CUSTOM.C_UAD_IDX ON CUSTOM.CUST_UAD_MAIN_TABLE
(USER_ID);


CREATE SYNONYM CUSTOM.C_UAD FOR CUSTOM.CUST_UAD_MAIN_TABLE;


CREATE SYNONYM TBAGEN.C_UAD FOR CUSTOM.CUST_UAD_MAIN_TABLE;


CREATE SYNONYM TBAUTIL.C_UAD FOR CUSTOM.CUST_UAD_MAIN_TABLE;


CREATE SYNONYM TBAADM.C_UAD FOR CUSTOM.CUST_UAD_MAIN_TABLE;


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON CUSTOM.CUST_UAD_MAIN_TABLE TO TBAADM;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON CUSTOM.CUST_UAD_MAIN_TABLE TO TBAGEN;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON CUSTOM.CUST_UAD_MAIN_TABLE TO TBAUTIL;
