DROP TABLE CUSTOM.CUST_DENOM_ROUNDOFF_DETAIL CASCADE CONSTRAINTS;

CREATE TABLE CUSTOM.CUST_DENOM_ROUNDOFF_DETAIL
(
  SOL_ID          VARCHAR2(20 BYTE)             NOT NULL,
  DXFER_ID        VARCHAR2(13 BYTE)             NOT NULL,
  DXFER_FLG       CHAR(3 BYTE)                  NOT NULL,
  PTRAN_TYPE      CHAR(1 BYTE)                  NOT NULL,
  CRNCY_CODE      VARCHAR2(3 BYTE)              NOT NULL,
  TRAN_DATE       DATE                          NOT NULL,
  ROUNDOFF_AMT    NUMBER(10,2)                  NOT NULL,
  TELLER_ID       VARCHAR2(15 BYTE)             NOT NULL,
  STATUS          CHAR(1 BYTE),
  AUTH_MATRIX_ID  VARCHAR2(5 BYTE),
  BANK_ID         VARCHAR2(8 CHAR)
);

CREATE UNIQUE INDEX CUSTOM.IDX_C_DERD ON CUSTOM.CUST_DENOM_ROUNDOFF_DETAIL
(SOL_ID, DXFER_ID, DXFER_FLG, PTRAN_TYPE, CRNCY_CODE, 
TRAN_DATE, TELLER_ID);


DROP SYNONYM CUSTOM.C_DERD;

CREATE SYNONYM CUSTOM.C_DERD FOR CUSTOM.CUST_DENOM_ROUNDOFF_DETAIL;

DROP SYNONYM TBAADM.C_DERD;

CREATE SYNONYM TBAADM.C_DERD FOR CUSTOM.CUST_DENOM_ROUNDOFF_DETAIL;

DROP SYNONYM TBAGEN.C_DERD;

CREATE SYNONYM TBAGEN.C_DERD FOR CUSTOM.CUST_DENOM_ROUNDOFF_DETAIL;

DROP SYNONYM TBAUTIL.C_DERD;

CREATE SYNONYM TBAUTIL.C_DERD FOR CUSTOM.CUST_DENOM_ROUNDOFF_DETAIL;

GRANT SELECT ON CUSTOM.CUST_DENOM_ROUNDOFF_DETAIL TO ALLTAB;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.CUST_DENOM_ROUNDOFF_DETAIL TO TBAADM;

GRANT SELECT ON CUSTOM.CUST_DENOM_ROUNDOFF_DETAIL TO TBAUTIL;
