DROP TABLE CUSTOM.C_WTH_GSP_DET_MOD CASCADE CONSTRAINTS;

CREATE TABLE CUSTOM.C_WTH_GSP_DET_MOD
(
  WTH_TAX_APP_FLG  CHAR(1 CHAR),
  WTH_TAX_PCNT     NUMBER(20,4),
  BACID            VARCHAR2(16 CHAR),
  SCHM_TYPE        VARCHAR2(3 CHAR),
  SCHM_CODE        VARCHAR2(5 CHAR),
  MOP_ID           VARCHAR2(8 CHAR),
  DEL_FLG          CHAR(1 BYTE),
  ENTITY_CRE_FLG   CHAR(1 BYTE),
  BANK_ID          VARCHAR2(8 CHAR)
)
/

CREATE UNIQUE INDEX CUSTOM.C_WTH_GSP_DET_MOD_PK ON CUSTOM.C_WTH_GSP_DET_MOD (SCHM_TYPE,SCHM_CODE,MOP_ID,BANK_ID);

DROP SYNONYM CUSTOM.C_WTHDM;

CREATE SYNONYM CUSTOM.C_WTHDM FOR CUSTOM.C_WTH_GSP_DET_MOD;


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON CUSTOM.C_WTH_GSP_DET_MOD TO TBAADM;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON CUSTOM.C_WTH_GSP_DET_MOD TO TBAGEN;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON CUSTOM.C_WTH_GSP_DET_MOD TO TBAUTIL;
