--DROP TABLE CUSTOM.INT_URL_TXN CASCADE CONSTRAINTS;

CREATE TABLE CUSTOM.INT_URL_TXN
(
  IC_SESSION_ID  VARCHAR2(100 BYTE) NOT NULL,
  IC_URL         VARCHAR2(45 BYTE),
  BANK_ID	 VARCHAR2(8 CHAR)
)
TABLESPACE CUSTOM_TBLS
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;

DROP SYNONYM CUSTOM.IUTX;

CREATE SYNONYM CUSTOM.IUTX FOR CUSTOM.INT_URL_TXN;
