<%--
//Generated by CMM Framework
//Do not edit this file directly.
//Instead, modify in CMM menu and regenerate.
--%>

<%@ page import="applcommon.ParseValue" %>
<%@ page import="applcommon.AppProperties" %>
<%@ page import="com.infy.bbu.jsputil.*"%>
<%@ page import="applcommon.ProfileProperties"%>
<%@ page import="java.util.Vector"%>
<%@ page import="FABCommon.SecurityInfo70"%>
<%@ taglib uri="taglib.tld" prefix="arjsp" %>
<%@ taglib uri="custom.tld" prefix="custom" %>
<arjsp:init groupName="Customize" isEntryPoint="false" />

<%
	String sProfileId = ProfilesManager.getProfileInSession(session);
	String sSubGrpName = (String)ARJspCurr.getInput("subGroupName", "");
	String sGrpName = ARJspCurr.getCurrentGroup();
	String pageName = (String)ARJspCurr.getInput("jspName", "");
	String sPopUpExceptionWindow = (String)ARJspCurr.getInput(sGrpName + ".PopUpExceptionWindow", "false");
	String sReferralMode = (String)ARJspCurr.getInput("refSubMode", "");
	ARJspCurr.setInput(sGrpName + ".PopUpExceptionWindow", "false");
	SecurityInfo70 securityInfo = (SecurityInfo70)session.getAttribute("FinUserInfo");
%>
<script>

	var sPopUpExceptionWindow = '<%=ParseValue.checkString(sPopUpExceptionWindow)%>';
	var sReferralMode = '<%=ParseValue.checkString(sReferralMode)%>';
	var subGroupName = '<%=ParseValue.checkString(ARJspCurr.getInput("subGroupName",""))%>';
	var BODDate	 = '<%= ParseValue.checkString((securityInfo.bodDate).substring(0,10))%>';
	var sHomeCrncyCode 	 = '<%=ParseValue.checkString(securityInfo.homeCrncyCode)%>';
	var sAmtFormat	 = '<%=ParseValue.checkString(ProfileProperties.getProperty(sProfileId,"amountFormat"))%>';
	var cmmFetchCallMode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".cmmFetchCallMode",""))%>';
	var cmmSubmitCallMode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".cmmSubmitCallMode",""))%>';
	var cmmErrorDetails = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".cmmErrorDetails",""))%>';
	var funcCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".funcCode",""))%>';
	var cifId = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".cifId",""))%>';
</script>

<script language="javascript" src="../Renderer/custom/javascripts/<%=VRPKeys.getCustomFile("custom_functions.js",sProfileId)%>" > </script >
<script language="javascript" src="../Renderer/custom/javascripts/<%=VRPKeys.getCustomFile("cd_atf_functions.js",sProfileId)%>" > </script >
<script language="javascript" src="../Renderer/custom/javascripts/cprofile/<%=VRPKeys.getCustomFile("cprofile_common_functions.js",sProfileId)%>" > </script >
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showPaySysIdList.js",sProfileId)%>"> </script>
	<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showPaysysIDOnFuncCode.js",sProfileId)%>"> </script>
	<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("event_handler.js",sProfileId)%>" > </script>
	<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showRefCode.js",sProfileId)%>"></script>
<script language = "JavaScript">
</script>

<script language="JavaScript">
	printCritBlock();
	printCritFooterBlock();
</script>
<%@include file = "../../javascripts/core_signature.js" %>