<%--
//Generated by Customization WB Generator
//Do not edit this file directly.
//Instead, modify the properties in the tool and regenerate.
--%>

<%@ page import="applcommon.ParseValue" %>
<%@ page import="com.infy.bbu.jsputil.*"%>
<%@ page import="java.util.Vector"%>
<%@ taglib uri="taglib.tld" prefix="arjsp" %>
<arjsp:init groupName="Customize" isEntryPoint="false" />

<%
	String sProfileId = ProfilesManager.getProfileInSession(session);
	String sSubGrpName = (String)ARJspCurr.getInput("subGroupName","");
	String sGrpName = ARJspCurr.getCurrentGroup();
	String pageName = (String)ARJspCurr.getInput("jspName","");
	String sPopUpExceptionWindow = (String)ARJspCurr.getInput(sGrpName+".PopUpExceptionWindow" ,"false");
	String sReferralMode = (String)ARJspCurr.getInput("refSubMode" ,"");
	ARJspCurr.setInput(sGrpName+".PopUpExceptionWindow","false");

%>
<script>

	var sPopUpExceptionWindow = '<%=sPopUpExceptionWindow%>';
	var sReferralMode = '<%=sReferralMode%>' ;

	var subGroupName = '<%=ParseValue.checkString(ARJspCurr.getInput("subGroupName",""))%>';
	var funcCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".funcCode",""))%>';	
	var tranType = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".tranType",""))%>';
	var cdscnumber = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".cdscnumber",""))%>';
	var ordernumber = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".ordernumber",""))%>';
	var accountnumber = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".accountnumber",""))%>';
	var tranid         = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".tranid",""))%>';
	var clientname      ='<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".clientNameLabel",""))%>';
</script>

<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showAccountIdList.js",sProfileId)%>" >
</script>



<script language="JavaScript">
	printBlock();
	printFooterBlock();
</script>

