//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT026332:"Signaler (rapporter) à  ",FLT026333:"Type de de sous transaction (transfert) ",FLT026334:"DATE(dd-mm-yyyy)"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);
