//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT000003:" rôle de ID",FLT000004:"Fonction",FLT000005:"SELECTIONNER--",FLT000006:"Ajouter",FLT000007:" Supprimer",FLT000008:"Vérifier",FLT000009: "Modifier",FLT000010:"Demande",FLT000011: " Devise"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);
