//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT021242:"Fonction",FLT021243:"Date de la zone",FLT021244:"Code de la  zone", FLT021245:"Définir le Numéro.",FLT021247:"Sélectionner--",FLT021248:" A - Ajouter",FLT021249:": D - Supprimer",FLT021250:"G - Régulariser",FLT021251:"I - Demande des renseignements (informations)",FLT021252:"M - Modifier",FLT021253:" R - Libération",FLT021254:" V - Vérifier",FLT021255:" Rejet externe",FLT007661:"Paiement de facture",FLT007530:"ID de Biller",FLT031859:"Type de service"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY 
var jspErr={};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);
