//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT021242:"Fonction",FLT021243:"Type de transaction (transfert) ",FLT021244:" Nom du module", FLT021245:"Idnetifiant de parametres",FLT021246:"Id Sol",FLT021247:"Sélectionner--",FLT021248:" A - Ajouter",FLT021249:" I – Demander/s’informer ",FLT021250:"C - Annuler le paramètre",FLT021251:"V - Vérifier le paramètre",FLT021252:"V - Modifier la veleur de paramètres",FLT021253:"VV - Vérifier la valeur de paramètres",FLT021254:"Demander la valeur du paramètre",FLT021255:"Annuler la valeur du paramètre",FLT021256:" effacer la veleur de paramètre",FLT021257:"Verifier le parametre effacé ",FLT021258:"CD - Dépôt en espèces",FLT021259:"CW-retrait despece",FLT021260:"TT-Transaction de transfert",FLT021261:" PA - Paiement à A / c. GL",FLT021262:"Identifiant de Transaction",FLT021263:"Date de la transaction (transfert)",FLT021264:"numéro du transaction ",FLT021265:" TF - Transférer des fonds à une autre entité A / c.",FLT021266:"RF - Recevoir des fonds dune autre entité A / c.",FLT021267:"Identifiant de niveau générique",FLT021268:"Id Sol"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY 
var jspErr={};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);
