//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT004977:" (Aller)",FLT032015:"Custom Mapping of Rate Codes",FLT006657:"Fonction",FLT032032:"RateCode(Cash Tran)",FLT032033:"RateCode(Transfer Tran)",FLT000193:"Envoyer  (soumettre) ",FLT000194:"Valider",FLT001721:"Annuler /Effacer ",FLT026526:" OK"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY 
var jspErr={};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);
