//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT000003:"ID du client",FLT000004:"Fonction",FLT000005:"Sélectionner",FLT000006:"Ajouter",FLT000007:" Supprimer"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);
