//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT026339:"Fonction",FLT026340:"Imprimer", FLT026336:"Sélectionner",FLT026334:" OCLG",FLT026335:"OCLG2",FLT026338:"Définir lID",FLT026333:"Code de la  zone",FLT026337:" Date de la zone", FLT026332:"Option Rpt"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

