//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT026332:" Code de réception ",FLT026333:"SET ID (Etablissement du numéro d’identification)",FLT026334:"FLT026334: DATE",FLT026335:"REMARKS",FLT026341:"Sélectionner--",FLT026342:"P-Processus "};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

