//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT004977:" (Aller)",FLT031734:"FLT031734: Maintenance des dénominations monétaires",FLT112254:"Fonction",FLT030604:" Devise",FLT004977:" (Aller)",FLT001439:"Effacer",FLT700022:"Sélectionner--",FLT031595:" A - Ajouter",FLT034011:" I – Demander/s’informer ",FLT031596:"M - Modifier",FLT034012:": D - Supprimer",FLT031736:"FLT031736: U – pas à supprimer "};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY
var jspErr={FAT000924:"Enter a value in the field."};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);
