--====================================================================================================
-- Table Name		: C_LADISB_PAYOFF_OLDLOAN
-- Synonym Name 	: C_LDPO
-- Date			: 25-Oct-2018
-- Description		: This table is used for Capturing old and new loan account details, for which loan restructure has happend
-- Author		: Vindiadevi_R
-- Modification History :
--<Version No.> <Date> <Author Name> <Description>
--====================================================================================================

DROP TABLE CUSTOM.C_LADISB_PAYOFF_OLDLOAN CASCADE CONSTRAINTS;

CREATE TABLE CUSTOM.C_LADISB_PAYOFF_OLDLOAN 
(	
	SRNO VARCHAR2(15 CHAR), 
	LOAN_FORACID VARCHAR2(16 CHAR), 
	LOAN_OP_FORACID VARCHAR2(16 CHAR), 
	LA_OP_AMT NUMBER(20,4), 
	LA_OP_CRNCY_CODE VARCHAR2(3 CHAR), 
	OLD_FORACID VARCHAR2(16 CHAR), 
	OLD_LA_AMT NUMBER(20,4), 
	OLD_LA_CRNCY_CODE VARCHAR2(3 CHAR), 
	PAYOFF_FLG CHAR(1 BYTE), 
	DEL_FLG CHAR(1 BYTE), 
	ENTITY_CRE_FLG CHAR(1 BYTE), 
	RCRE_TIME DATE, 
	LCHG_USER_ID VARCHAR2(15 CHAR), 
	RCRE_USER_ID VARCHAR2(15 CHAR), 
	LCHG_TIME DATE, 
	TRAN_ID VARCHAR2(15 CHAR), 
	BANK_ID VARCHAR2(8 CHAR), 
	FUNCCODE CHAR(1 BYTE)
);

DROP SYNONYM CUSTOM.C_LDPO;

CREATE OR REPLACE SYNONYM CUSTOM.C_LADISB_PAYOFF_OLDLOAN FOR CUSTOM.C_LADISB_PAYOFF_OLDLOAN;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.C_LADISB_PAYOFF_OLDLOAN TO TBAADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.C_LADISB_PAYOFF_OLDLOAN TO TBAGEN;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.C_LADISB_PAYOFF_OLDLOAN TO TBAUTIL;