			<%-- *************** FILE GENERATED BY JSP GENERATOR FOR CUSTOMIZATION ***************** --%>

<%@ taglib uri="taglib.tld" prefix="arjsp" %>
<arjsp:init groupName="tlgxfer" isEntryPoint="false" />
<%@ include file="../custom/commonInclude.jsp" %>
<custom:incfile file="tlgxfer_det_custom.jsp"/>
<%
	String Message = (String)ARJspCurr.getInputWithGroup("Message","");
	String applName = (String)ARJspCurr.getInputWithGroup("applName","");
	String txncrncy = (String)ARJspCurr.getInputWithGroup("txncrncy","");
	String txnAmt = (String)ARJspCurr.getInputWithGroup("txnAmt","");
	String settlcrncy = (String)ARJspCurr.getInputWithGroup("settlcrncy","");
	String settAmt = (String)ARJspCurr.getInputWithGroup("settAmt","");
	String settChrg = (String)ARJspCurr.getInputWithGroup("settChrg","");
	String benAcct = (String)ARJspCurr.getInputWithGroup("benAcct","");
	String benAcctCrncy = (String)ARJspCurr.getInputWithGroup("benAcctCrncy","");
	String benAcctSol = (String)ARJspCurr.getInputWithGroup("benAcctSol","");
	String benAcctName = (String)ARJspCurr.getInputWithGroup("benAcctName","");
	String benName = (String)ARJspCurr.getInputWithGroup("benName","");
	String benAddr = (String)ARJspCurr.getInputWithGroup("benAddr","");
	String benSwiftAddr = (String)ARJspCurr.getInputWithGroup("benSwiftAddr","");
	String benBankClearingCode = (String)ARJspCurr.getInputWithGroup("benBankClearingCode","");
	String benBankAcct = (String)ARJspCurr.getInputWithGroup("benBankAcct","");
	String exchRateCode = (String)ARJspCurr.getInputWithGroup("exchRateCode","");
	String acctNum = (String)ARJspCurr.getInputWithGroup("acctNum","");

	//FOLLOWING VARIABLES IS REQUIRED FOR REFERRAL.

	String sGrpName = ARJspCurr.getCurrentGroup();
	String sPopUpExceptionWindow = (String)ARJspCurr.getInput(sGrpName+".PopUpExceptionWindow" ,"false");
	String sReferralMode = (String)ARJspCurr.getInput("refSubMode" ,"");
	ARJspCurr.setInput(sGrpName+".PopUpExceptionWindow","false");
	String sGroupName = ARJspCurr.getCurrentGroup();
	ARJspCurr.setInput(sGroupName+".PopUpExceptionWindow","false");

%>

<html>
<body leftmargin="0" topmargin="0" rightmargin="0" class="cbody" onLoad="javascript:fnOnLoad();">
<LINK href="../Renderer/stylesheets/services.css" rel=STYLESHEET  title="Finacle Stylesheet"type= text/css />
<script language="javascript" src="../Renderer/javascripts/finbranchResource_INFENG.js" ></script>
<script language="javascript" src="../Renderer/javascripts/dynamic_combo.js" > </script>
<script language="javascript" src="../Renderer/javascripts/cust_functions.js" > </script>
<script language="javascript" src="../Renderer/javascripts/common_functions.js" > </script>
<script language="javascript" src="../Renderer/javascripts/hotkeyprocessor_link.js" > </script>
<custom:mbuild/>
<script language="javascript" src="../Renderer/javascripts/menuLayer.js" > </script>
<script language="javascript" src="../javascripts/custom_common_functions.js" > </script>

<%@ include file="../javascripts/appl_inc.js" %> 
<%@ include file="../javascripts/header.js" %>
<%@ include file="../javascripts/display_err.js" %>

<script language="javascript" src="../custom/javascripts/jsperr/<%=LocaleMapper.getLangCode(pageContext)%>/tlgxfer_det_errmsg_<%=LocaleMapper.getLangCode(pageContext)%>.js"></script>
<script language="javascript" src="../custom/javascripts/jspjs/<%=LocaleMapper.getLangCode(pageContext)%>/tlgxfer_det_<%=LocaleMapper.getLangCode(pageContext)%>.js"></script>

<form name="date" action="../tlgxfer/tlgxfer_ctrl.jsp" method="post">

<script>
	var sPopUpExceptionWindow = '<%=sPopUpExceptionWindow%>';
	var sReferralMode = '<%=sReferralMode%>' ;
	var funcCode = '<%=ParseValue.checkString(ARJspCurr.getInputWithGroup("funcCode",""))%>';
	var ObjForm = document.forms[0];

function fnOnLoad(){
	if(funcCode =='V' || funcCode =='I' || funcCode =='D' || funcCode =='U' ||  funcCode =='X' || sReferralMode =='I' || sReferralMode =='S'){
		fnDisableFormControls(ObjForm);
	}
	fnPopUpExceptionWindow(ObjForm.actionCode);
	if((typeof(WF_IN_PROGRESS) != "undefined") && (WF_IN_PROGRESS == "PEAS")){
		checkCustErrExecNextStep("<%=Message%>");
	}
}

function fnValidateData(){
	return true;
}

function fnSubmitForm(btnObj){
	doSubmit(btnObj.id);
}

</script>

<table width="100%" align="center" border="0">
<tbody>
<tr>
	<%
	if(!Message.equals("NULL")){
	%>
	<td style="color:red"><%=Message%></td>
	<%
	}
	else{
	%>
	<td style="color:red">&nbsp;&nbsp;&nbsp;</td>
	<%
	}
	%>
</tr>
</tbody>
</table>


<input type="hidden" name="actionCode" id="actionCode">
<input type="hidden" name="tabName">
<input type="hidden" name="callMode" id="callMode" value="E">
<input type="hidden" name="pagename" value="tlgxfer_det.jsp">

<table width="100%" border="0" cellpadding="0" cellspacing="0" class="ctable">
  <tr>
	<td>
		<table width="100%" border="0" cellpadding="0" cellspacing="0">
			<tr>
			  <td class="page-heading">Create TT Instruction</td>
			</tr>
	  	</table>
	  	<br>
	   	<table width="100%" border="0" cellspacing="0" cellpadding="0" class="innertabletop1">
			<tr>
			  	<td width="20%" class="textlabel"><script>document.write(jspRes.FLT006657)</script></td>
				<td  class="coloumnwidth">&nbsp;</td>
			  	<td align = "left">Add</td>
			</tr>
			<tr>
				<td width="20%" class="textlabel"><script>document.write(jspRes.FLT000265)</script></td>
				<td  class="coloumnwidth">&nbsp;</td>
				<td colspan="4"  class="textfielddisplaylabel"><%=acctNum%>&nbsp;</td> 		 	
			</tr>
	  	</table>
		<table width="100%" border="0" cellpadding="0" cellspacing="0" class="tableborder">
		  	<tr>
				<td>
					<table width="100%" border="0" cellpadding="0" cellspacing="0" class="innertable">
						<tr class="innertabletop1">
							<td colspan="5" align="right">
								<table border="0" cellspacing="0" cellpadding="0">
									<tr>
										<td align="right">
											<a href="javascript:showHelpFile('afsmcrit_help.htm');">
											<img src="../images/help.gif" width="47" height="21"  vspace="1" border="0"></a>
										</td>
									</tr>
								</table>
							</td>
						 </tr>

						
						 <tr>
							<td class="textlabel"><script>document.write(jspRes.FLT016366)</script></td>
							<td class="textfield"><input name="applName" id="applName" value= "<%=applName%>" type="TEXT" class="textfieldfont" size="9" maxlength="50"></td>
						 </tr>
						 <tr>
							<td class="textlabel"><script>document.write(jspRes.FLT016367)</script></td>
							<td  class="textfield"><input name="txncrncy" id="txncrncy" value= "<%=txncrncy%>" type="text" class="textfieldfont" size="25" maxlength="3" >&nbsp;</td>

							<td  class="coloumnwidth">&nbsp;</td>
							<td class="textlabel"><script>document.write(jspRes.FLT016368)</script></td>
							<td  class="textfield"><input name="txnAmt" id="txnAmt" value= "<%=txnAmt%>" type="TEXT" class="textfieldfont" size="15" maxlength="80"></td>
						 </tr>
						 <tr>
							<td class="textlabel"><script>document.write(jspRes.FLT016369)</script></td>
							<td  class="textfield"><input name="settlcrncy" id="settlcrncy" value= "<%=settlcrncy%>" type="text" class="textfieldfont" size="25" maxlength="3">&nbsp;</td>

							<td  class="coloumnwidth">&nbsp;</td>
							<td class="textlabel"><script>document.write(jspRes.FLT016370)</script></td>
							<td  class="textfield"><input name="settAmt" id="settAmt" value= "<%=settAmt%>" type="TEXT" class="textfieldfont" size="15" maxlength="80"></td>
						 </tr>
						 <tr>
							<td class="textlabel"><script>document.write(jspRes.FLT016371)</script></td>
							<td  class="textfielddisplaylabel"><input type="radio" name="settChrg" id="settChrg" value="Y" onClick="fnChangeofSettChargeFlg()" >Yes
							<input name="settChrg" id="settChrg_1" type="radio" value="N" onClick="fnChangeofSettChargeFlg();" checked selected>No
							</td>
						 </tr>
						 <tr>
							<td class="textlabel"><script>document.write(jspRes.FLT016372)</script></td>
							<td colspan="4"  class="textfield"><input name="benAcct" id="benAcct" value= "<%=benAcct%>" type="text" class="textfieldfont" size="25" maxlength="36" >&nbsp;
								<a href="#">
								<img src="../images/search_icon.gif" width="16" height="17" border="0"></a>
								&nbsp;
								<input name="benAcctCrncy" id="benAcctCrncy" value= "<%=benAcctCrncy%>" type="text" disabled="true" class="labelwithoutwidth" size="3" maxlength="3">
								<input name="benAcctSol" id="benAcctSol" value= "<%=benAcctSol%>" type="text" disabled="true" class="labelwithoutwidth"  size="8" maxlength="8">
								<input name="benAcctName" id="benAcctName" value= "<%=benAcctName%>" type="text" disabled="true" class="label" size="25" maxlength="25">
							</td>
						 </tr>
						 <tr>
							<td class="textlabel"><script>document.write(jspRes.FLT016373)</script></td>
							<td class="textfield"><input name="benName" id="benName" value= "<%=benName%>" type="TEXT" class="textfieldfont" size="9" maxlength="50"></td>

							<td  class="coloumnwidth">&nbsp;</td>
						      <td class="textlabel"><script>document.write(jspRes.FLT016374)</script></td>
							<td class="textfield"><textarea name="benAddr" id="benAddr" class="textfieldfont"></textarea></td>

</textarea>
						 <tr>
							<td class="textlabel"><script>document.write(jspRes.FLT016375)</script></td>
							<td class="textfield"><input name="benSwiftAddr" id="benSwiftAddr" value= "<%=benSwiftAddr%>" type="TEXT" class="textfieldfont" size="9" maxlength="6">&nbsp;</td>
							<td  class="coloumnwidth">&nbsp;</td>

							<td class="textlabel"><script>document.write(jspRes.FLT016376)</script></td>
							<td class="textfield"><input name="benBankClearingCode" id="benBankClearingCode" value= "<%=benBankClearingCode%>" type="TEXT" class="textfieldfont" size="9" maxlength="6">&nbsp;</td>
						</tr>
						<tr>
							<td class="textlabel"><script>document.write(jspRes.FLT016379)</script></td>
							<td colspan="4"  class="textfield"><input name="benBankAcct" id="benBankAcct" value= "<%=benBankAcct%>" type="text" class="textfieldfont" size="25" maxlength="36" >&nbsp;
							<a href="#">
							<img src="../images/search_icon.gif" width="16" height="17" border="0"></a>
						      &nbsp;
							<input name="benAcctCrncy" id="benAcctCrncy" value= "<%=benAcctCrncy%>" type="text" disabled="true" class="labelwithoutwidth" size="3" maxlength="3">
							<input name="benAcctSol" id="benAcctSol" value= "<%=benAcctSol%>" type="text" disabled="true" class="labelwithoutwidth"  size="8" maxlength="8">
							<input name="benAcctName" id="benAcctName" value= "<%=benAcctName%>" type="text" disabled="true" class="label" size="25" maxlength="25"></td>
						</tr>
						<tr>
							<td class="textlabel"><script>document.write(jspRes.FLT001406)</script></td>
						      <td  class="textfield"><input name="exchRateCode" id="exchRateCode" value= "<%=exchRateCode%>" type="text" class="textfieldinsidemultirec1" size="25" maxlength=3></td>
						</tr>
					</table>
				</td>
			</tr>
		</table>

	</td>
  </tr>
</table>

<script language="JavaScript">
printFooterBlock();
ObjForm.settChrg.value ='<%=ParseValue.checkString(ARJspCurr.getInputWithGroup("settChrg",""))%>';
checkRadio(ObjForm.settChrg,ObjForm.settChrg.value);
ObjForm.benAcct.value ='<%=ParseValue.checkString(ARJspCurr.getInputWithGroup("benAcct",""))%>';
checkRadio(ObjForm.benAcct,ObjForm.benAcct.value);

function printFooterBlock()
{
	with (document) {
	if ((sReferralMode == 'I')||(sReferralMode == 'S')){
	write('<div align="left" class="ctable">');
	if (sReferralMode == 'S'){
	write('<input type="button" class="Button" id="Submit" value="SUBMIT" onClick="javascript:return doRefSubmit(this);" hotKeyId="Submit" >');
	}
	writeRefFooter();
	write('<input type="button" class="Button" id="_BackRef_" value="CANCEL" onClick="javascript:return doSubmit(this.id);" hotKeyId="Cancel" >');
	write('</div>');
	}else{
	write('<div align="left" class="ctable">');
	if(funcCode !='I'){
	write('<input name="Submit" type="button" class="button" onClick="return doSubmit(this.id)" id="Submit" value="Submit">');
	write('<input name="Validate" type="button" class="button" onClick="return doSubmit(this.id)" id="Validate" value="Validate">');
	write('<input name="Cancel" type="button" class="button" onClick="return doSubmit(this.id)" id="Cancel" value="Cancel">');
	}else{
	write('&nbsp;<input class="button" type="button" id="Back" value="OK" onClick="javascript:return doSubmit(this.id)">');
	}
	writeFooter();
	write('</div>');
	}
	} //End with()
}//End function

</script>
</form>
</body>
</html>
			<%-- ****************************** END OF FILE ***************************** --%>
