<%--
//Generated by Customization WB Generator
//Do not edit this file directly.
//Instead, modify the properties in the tool and regenerate.
--%>

<%@ page import="applcommon.ParseValue" %>
<%@ page import="com.infy.bbu.jsputil.*"%>
<%@ taglib uri="taglib.tld" prefix="arjsp" %>

<%!
        public static final String _ARJSP_JSP_NAME = "cdpsp/cdpsp_det_ginc.jsp";
%>

<%@ include file="../../finbranch_common.jsp" %>
<arjsp:init groupName="Customize" isEntryPoint="false" />

<%
	String sProfileId = ProfilesManager.getProfileInSession(session);
	String sSubGrpName = (String)ARJspCurr.getInput("subGroupName","");
	String sGrpName = ARJspCurr.getCurrentGroup();
	String sPopUpExceptionWindow = (String)ARJspCurr.getInput(sGrpName+".PopUpExceptionWindow" ,"false");
	String sReferralMode = (String)ARJspCurr.getInput("refSubMode" ,"");
	ARJspCurr.setInput(sGrpName+".PopUpExceptionWindow","false");
	FABCommon.SecurityInfo70        securityInfo    = (FABCommon.SecurityInfo70)session.getAttribute("FinUserInfo");

%>
<script>

	var sPopUpExceptionWindow = '<%=sPopUpExceptionWindow%>';
	var sReferralMode = '<%=sReferralMode%>' ;
	var subGroupName = '<%=ParseValue.checkString(ARJspCurr.getInput("subGroupName",""))%>';
	var funcCode= '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".funcCode",""))%>';
	var NatIdNum= '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".NatIdNum",""))%>';
	var FirstName = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".FirstName",""))%>';
	var LastName = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".LastName",""))%>';
	var MiddleName = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".MiddleName",""))%>';
	var MobileNum = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".MobileNum",""))%>';
	var AddressLine1 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".AddressLine1",""))%>';
	var AddressLine2 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".AddressLine2",""))%>';
	var EmailId = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".EmailId",""))%>';
	var Occupation = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".Occupation",""))%>';
	var CurrencyC = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".CurrencyC",""))%>';
	var KraPin = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".KraPin",""))%>';
	var BODDate = '<%=(securityInfo.bodDate).substring(0,10)%>';
</script>

<%@include file='../../javascripts/core_signature.js'%>

<script language="javascript" src="../Renderer/javascripts/lists/showAccountIdList.js" > </script>
<script language="javascript" src="../Renderer/custom/javascripts/custom_functions.js"></script>
<script language="javascript" src="../Renderer/custom/javascripts/common_functions.js"></script>
<script language="javascript" src="../Renderer/custom/javascripts/custom_common_functions.js"></script>
<script language="javascript" src="../Renderer/custom/javascripts/cust_fetch_list.js"></script>

<script language="JavaScript">
	printBlock();
	printFooterBlock();
</script>
