pring:
  application:
    name: papss-middleware-service
  datasource:
    url: jdbc:oracle:thin:@10.1.9.178:1540:c4testdb
    username: eneza
    password: welcome1
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      pool-name: HikariCP
      auto-commit: false
      maximum-pool-size: 20
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      leak-detection-threshold: 150000
      initialization-fail-timeout: 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        boot.allow_jdbc_metadata_access: false
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: false
        jdbc.batch_size: 50
        order_inserts: true
        order_updates: true
        connection.provider_disables_autocommit: true
    open-in-view: false

logging:
  level:
    com.papss.middleware: DEBUG
    org.springframework.web.client.RestTemplate: INFO
    org.apache.http: DEBUG

papss:
  participants:
    - apiKey: 706b3dac-21ca-4755-906f-841117db9eab
      country: KE
      inst_bic: EQBLKENA
      inst_id: KE1011
      salt: supersecretsalt
      sslKeyAlias: equityy
      keyStorePath: /var/papss/certs/EQUITYY-c1.jks
      keyPass: secure
      keyStoreType: JKS
      provider: SunJCE
  system:
      enableInbound: true
      enableOutbound: true
      pollingExecutorThreadDelay: 10000
      pollingExecutorThreadRate: 10000
      pollingExecutorsPerParticipant: 3
      pollingSleepTime: 5000
      toClearingSystemId: XA0001
      ipsBaseUrl: pm.test.papssnet.papss.com
      ipsPort: 443
core:
  banking:
    url: http://localhost:8082/papss-core-banking-mock-server
    path:
      credit-transfer: "/ft"
      name-inquiry: "/name-enquiry"
      recon: "/settlement-recon"
      tx-confirmation: "/txn-confirmation"
      recall-request: "/recall-request"
      payment-return: "/payment-return"