<%--
//Generated by Customization WB Generator
//Do not edit this file directly.
//Instead, modify the properties in the tool and regenerate.
--%>

<%@ page import="applcommon.ParseValue" %>
<%@ page import="com.infy.bbu.jsputil.*"%>
<%@ page import="java.util.Vector"%>
<%@ page import="FABCommon.SecurityInfo70"%>
<%@ taglib uri="taglib.tld" prefix="arjsp" %>
<arjsp:init groupName="Customize" isEntryPoint="false" />

<%
	String sProfileId = ProfilesManager.getProfileInSession(session);
	String sSubGrpName = (String)ARJspCurr.getInput("subGroupName","");
	String sGrpName = ARJspCurr.getCurrentGroup();
	String pageName = (String)ARJspCurr.getInput("jspName","");
	String sPopUpExceptionWindow = (String)ARJspCurr.getInput(sGrpName+".PopUpExceptionWindow" ,"false");
	String sReferralMode = (String)ARJspCurr.getInput("refSubMode" ,"");
	ARJspCurr.setInput(sGrpName+".PopUpExceptionWindow","false");
	SecurityInfo70 securityInfo = (SecurityInfo70)session.getAttribute("FinUserInfo");

	String SfuncCode = (String)session.getAttribute("SfuncCode");
        String SzoneCode = (String)session.getAttribute("SzoneCode");

%>
<script>

	var sPopUpExceptionWindow = '<%=sPopUpExceptionWindow%>';
	var sReferralMode = '<%=sReferralMode%>' ;

	var subGroupName = '<%=ParseValue.checkString(ARJspCurr.getInput("subGroupName",""))%>';
	var BODDate= "<%=(securityInfo.bodDate).substring(0,10)%>";
	var contextSolId = "<%=(securityInfo.contextSolId)%>";
	var funcCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".funcCode",""))%>';
	var critCrAcctNum = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".critCrAcctNum",""))%>';
	var zoneCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".zoneCode",""))%>';
	var zoneDate = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".zoneDate",""))%>';
	var zoneCCY = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".zoneCCY",""))%>';
	var smInstrument = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".smInstrument",""))%>';
	var noOfChq = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".noOfChq",""))%>';
	var totalCrAmt = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".totalCrAmt",""))%>';
	var setNum = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".setNum",""))%>';
	var billPayYes = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".billPayYes",""))%>';
	var hoccmFuncDesc = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".hoccmFuncDesc",""))%>';
	var valType = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".valType",""))%>';
	var critBatchNum = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".critBatchNum",""))%>';
	var critTranId = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".critTranId",""))%>';
	var billerCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".billerCode",""))%>';
	var billerId = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".billerId",""))%>';
	var zoneIdentifier = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".zoneIdentifier",""))%>';
	var responseValue = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".responseValue",""))%>';
	var typOfServ = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".typOfServ",""))%>';
	var hoccmBankId = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".hoccmBankId",""))%>';
	var hoccmUserId = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".hoccmUserId",""))%>';

	var SfuncCode = '<%=SfuncCode%>';
	var SzoneCode = '<%=SzoneCode%>';
	//alert("SfuncCode : " + SfuncCode + " " + SzoneCode);
	if(SfuncCode == "null")
	{
		<%
			session.setAttribute("SfuncCode","null");
			session.setAttribute("SzoneCode","null");		
		%>
	}
	else
	{
		//funcCode = SfuncCode;
		//zoneCode = SzoneCode;
	}
</script>


<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("cust_pre_evt.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("cust_post_evt.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showAccountIdList.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("common_functions.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showZoneCode.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/custom/javascripts/hoccm/<%=VRPKeys.getFile("callVeracious.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/custom/javascripts/hoccm/<%=VRPKeys.getFile("getBillDetailSection.js",sProfileId)%>"></script>

<script language="JavaScript">
	printBlock();
	printFooterBlock();
</script>

