<%--
//Generated by Customization WB Generator
//Do not edit this file directly.
//Instead, modify the properties in the tool and regenerate.
--%>

<%@ page import="java.util.HashMap,applcommon.ParseValue,finbranchUtil.CustomMultiRecHandler" %>
<%@ page import="com.infy.bbu.jsputil.*"%>
<%@ page import="java.util.Vector"%>
<%@ taglib uri="taglib.tld" prefix="arjsp" %>
<%@ taglib uri="custom.tld" prefix="custom" %>
<arjsp:init groupName="Customize" isEntryPoint="false" />

<%
	String sProfileId = ProfilesManager.getProfileInSession(session);
	String sSubGrpName = (String)ARJspCurr.getInput("subGroupName","");
	String sGrpName = ARJspCurr.getCurrentGroup();
	String pageName = (String)ARJspCurr.getInput("jspName","");
	String sPopUpExceptionWindow = (String)ARJspCurr.getInput(sGrpName+".PopUpExceptionWindow" ,"false");
	String sReferralMode = (String)ARJspCurr.getInput("refSubMode" ,"");
	ARJspCurr.setInput(sGrpName+".PopUpExceptionWindow","false");

	HashMap hmMultiRecData = (HashMap)ARJspCurr.getInput(sSubGrpName+".multiRecData",null);
	String inputFields[][] = {
		{"d2InstAmt","text",""},
		{"d2InstNum","text",""},
		{"d2InstDate","text",""},
		{"d2PayingAcctNum","text",""},
		{"d2BankCode","text",""},
		{"d2TranCode","text",""},
		{"d2BatchNum","text",""},
		{"d2TranId","text",""},
		{"d2InstFreetext","text",""},
		{"d2BrCode","text",""},
	};
	String currentPosition =(String)ARJspCurr.getInput("hoccm_det2.currentPosition","0");
	String lowerLimit =(String)ARJspCurr.getInput(sSubGrpName+".lowerLimit","0");
	String higherLimit =(String)ARJspCurr.getInput(sSubGrpName+".higherLimit","0");
	String totalMRHRecords =(String)ARJspCurr.getInput(sSubGrpName+".mrhTotalRecords","0");
	int lowLimit = Integer.parseInt(lowerLimit);
	int highLimit = Integer.parseInt(higherLimit);
	int totRec = Integer.parseInt(totalMRHRecords);
%>
<script>

	var selectedRow = 0;
	var totalRec = '<%=totRec%>';
	var lowerLmt = '<%=lowLimit%>';
	var highestLimit = '<%=highLimit%>';
	var currentPosition ='<%=currentPosition%>';
	var totalMRHRecords ='<%=totalMRHRecords%>';
	var sPopUpExceptionWindow = '<%=sPopUpExceptionWindow%>';
	var sReferralMode = '<%=sReferralMode%>' ;

	var subGroupName = '<%=ParseValue.checkString(ARJspCurr.getInput("subGroupName",""))%>';
	var d2CrAcctNum = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2CrAcctNum",""))%>';
	var d2CrAmt = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2CrAmt",""))%>';
	var d2AcctFreetext1 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2AcctFreetext1",""))%>';
	var d2AcctFreetext2 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2AcctFreetext2",""))%>';
	var d2InstAmt = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2InstAmt",""))%>';
	var d2InstNum = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2InstNum",""))%>';
	var d2InstDate = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2InstDate",""))%>';
	var d2PayingAcctNum = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2PayingAcctNum",""))%>';
	var d2BankCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2BankCode",""))%>';
	var d2TranCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2TranCode",""))%>';
	var d2BatchNum = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2BatchNum",""))%>';
	var d2TranId = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2TranId",""))%>';
	var d2InstFreetext = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2InstFreetext",""))%>';
	var d2BrCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2BrCode",""))%>';
	var OutCallFlg = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".OutCallFlg",""))%>';
	var funcCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".funcCode",""))%>';
	var critCrAcctNum = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".critCrAcctNum",""))%>';
	var zoneCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".zoneCode",""))%>';
	var zoneDate = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".zoneDate",""))%>';
	var zoneCCY = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".zoneCCY",""))%>';
	var smInstrument = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".smInstrument",""))%>';
	var noOfChq = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".noOfChq",""))%>';
	var totalCrAmt = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".totalCrAmt",""))%>';
	var setNum = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".setNum",""))%>';
	var critBatchNum = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".critBatchNum",""))%>';
	var critTranId = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".critTranId",""))%>';
	var hoccmFuncDesc = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".hoccmFuncDesc",""))%>';
	var zoneIdentifier = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".zoneIdentifier",""))%>';
	var hoccmBankId = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".hoccmBankId",""))%>';
	var hoccmUserId = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".hoccmUserId",""))%>';

	var d2TotalRecords = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2TotalRecords",""))%>';

	var d2MRInstAmt_1 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstAmt_1",""))%>';
	var d2MRInstNum_1 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstNum_1",""))%>';
	var d2MRInstDate_1 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstDate_1",""))%>';
	var d2MRPayingAcctNum_1 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRPayingAcctNum_1",""))%>';
	var d2MRBankCode_1 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBankCode_1",""))%>';
	var d2MRTranCode_1 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRTranCode_1",""))%>';
	var d2MRBatchNum_1 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBatchNum_1",""))%>';
	var d2MRTranId_1 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRTranId_1",""))%>';
	var d2MRPayingAcctName_1 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRPayingAcctName_1",""))%>';
	var d2MRBrCode_1 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBrCode_1",""))%>';

	var d2MRInstAmt_2 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstAmt_2",""))%>';
        var d2MRInstNum_2 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstNum_2",""))%>';
        var d2MRInstDate_2 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstDate_2",""))%>';
        var d2MRPayingAcctNum_2 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRPayingAcctNum_2",""))%>';
        var d2MRBankCode_2 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBankCode_2",""))%>';
        var d2MRTranCode_2 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRTranCode_2",""))%>';
        var d2MRBatchNum_2 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBatchNum_2",""))%>';
        var d2MRTranId_2 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRTranId_2",""))%>';
        var d2MRPayingAcctName_2 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRPayingAcctName_2",""))%>';
        var d2MRBrCode_2 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBrCode_2",""))%>';

	var d2MRInstAmt_3 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstAmt_3",""))%>';
        var d2MRInstNum_3 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstNum_3",""))%>';
        var d2MRInstDate_3 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstDate_3",""))%>';
        var d2MRPayingAcctNum_3 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRPayingAcctNum_3",""))%>';
        var d2MRBankCode_3 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBankCode_3",""))%>';
        var d2MRTranCode_3 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRTranCode_3",""))%>';
        var d2MRBatchNum_3 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBatchNum_3",""))%>';
        var d2MRTranId_3 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRTranId_3",""))%>';
        var d2MRPayingAcctName_3 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRPayingAcctName_3",""))%>';
        var d2MRBrCode_3 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBrCode_3",""))%>';

	var d2MRInstAmt_4 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstAmt_4",""))%>';
        var d2MRInstNum_4 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstNum_4",""))%>';
        var d2MRInstDate_4 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstDate_4",""))%>';
        var d2MRPayingAcctNum_4 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRPayingAcctNum_4",""))%>';
        var d2MRBankCode_4 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBankCode_4",""))%>';
        var d2MRTranCode_4 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRTranCode_4",""))%>';
        var d2MRBatchNum_4 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBatchNum_4",""))%>';
        var d2MRTranId_4 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRTranId_4",""))%>';
        var d2MRPayingAcctName_4 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRPayingAcctName_4",""))%>';
        var d2MRBrCode_4 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBrCode_4",""))%>';

	var d2MRInstAmt_5 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstAmt_5",""))%>';
        var d2MRInstNum_5 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstNum_5",""))%>';
        var d2MRInstDate_5 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstDate_5",""))%>';
        var d2MRPayingAcctNum_5 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRPayingAcctNum_5",""))%>';
        var d2MRBankCode_5 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBankCode_5",""))%>';
        var d2MRTranCode_5 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRTranCode_5",""))%>';
        var d2MRBatchNum_5 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBatchNum_5",""))%>';
        var d2MRTranId_5 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRTranId_5",""))%>';
        var d2MRPayingAcctName_5 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRPayingAcctName_5",""))%>';
        var d2MRBrCode_5 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBrCode_5",""))%>';

	var d2MRInstAmt_6 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstAmt_6",""))%>';
        var d2MRInstNum_6 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstNum_6",""))%>';
        var d2MRInstDate_6 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstDate_6",""))%>';
        var d2MRPayingAcctNum_6 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRPayingAcctNum_6",""))%>';
        var d2MRBankCode_6 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBankCode_6",""))%>';
        var d2MRTranCode_6 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRTranCode_6",""))%>';
        var d2MRBatchNum_6 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBatchNum_6",""))%>';
        var d2MRTranId_6 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRTranId_6",""))%>';
        var d2MRPayingAcctName_6 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRPayingAcctName_6",""))%>';
        var d2MRBrCode_6 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBrCode_6",""))%>';

	var d2MRInstAmt_7 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstAmt_7",""))%>';
        var d2MRInstNum_7 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstNum_7",""))%>';
        var d2MRInstDate_7 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstDate_7",""))%>';
        var d2MRPayingAcctNum_7 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRPayingAcctNum_7",""))%>';
        var d2MRBankCode_7 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBankCode_7",""))%>';
        var d2MRTranCode_7 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRTranCode_7",""))%>';
        var d2MRBatchNum_7 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBatchNum_7",""))%>';
        var d2MRTranId_7 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRTranId_7",""))%>';
        var d2MRPayingAcctName_7 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRPayingAcctName_7",""))%>';
        var d2MRBrCode_7 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBrCode_7",""))%>';

	var d2MRInstAmt_8 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstAmt_8",""))%>';
        var d2MRInstNum_8 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstNum_8",""))%>';
        var d2MRInstDate_8 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstDate_8",""))%>';
        var d2MRPayingAcctNum_8 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRPayingAcctNum_8",""))%>';
        var d2MRBankCode_8 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBankCode_8",""))%>';
        var d2MRTranCode_8 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRTranCode_8",""))%>';
        var d2MRBatchNum_8 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBatchNum_8",""))%>';
        var d2MRTranId_8 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRTranId_8",""))%>';
        var d2MRPayingAcctName_8 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRPayingAcctName_8",""))%>';
        var d2MRBrCode_8 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBrCode_8",""))%>';

	var d2MRInstAmt_9 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstAmt_9",""))%>';
        var d2MRInstNum_9 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstNum_9",""))%>';
        var d2MRInstDate_9 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstDate_9",""))%>';
        var d2MRPayingAcctNum_9 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRPayingAcctNum_9",""))%>';
        var d2MRBankCode_9 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBankCode_9",""))%>';
        var d2MRTranCode_9 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRTranCode_9",""))%>';
        var d2MRBatchNum_9 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBatchNum_9",""))%>';
        var d2MRTranId_9 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRTranId_9",""))%>';
        var d2MRPayingAcctName_9 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRPayingAcctName_9",""))%>';
        var d2MRBrCode_9 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBrCode_9",""))%>';

	var d2MRInstAmt_10 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstAmt_10",""))%>';
        var d2MRInstNum_10 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstNum_10",""))%>';
        var d2MRInstDate_10 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstDate_10",""))%>';
        var d2MRPayingAcctNum_10 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRPayingAcctNum_10",""))%>';
        var d2MRBankCode_10 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBankCode_10",""))%>';
        var d2MRTranCode_10 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRTranCode_10",""))%>';
        var d2MRBatchNum_10 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBatchNum_10",""))%>';
        var d2MRTranId_10 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRTranId_10",""))%>';
        var d2MRPayingAcctName_10 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRPayingAcctName_10",""))%>';
        var d2MRBrCode_10 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBrCode_10",""))%>';

	var d2MRInstAmt_11 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstAmt_11",""))%>';
        var d2MRInstNum_11 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstNum_11",""))%>';
        var d2MRInstDate_11 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstDate_11",""))%>';
        var d2MRPayingAcctNum_11 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRPayingAcctNum_11",""))%>';
        var d2MRBankCode_11 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBankCode_11",""))%>';
        var d2MRTranCode_11 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRTranCode_11",""))%>';
        var d2MRBatchNum_11 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBatchNum_11",""))%>';
        var d2MRTranId_11 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRTranId_11",""))%>';
        var d2MRPayingAcctName_11 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRPayingAcctName_11",""))%>';
        var d2MRBrCode_11 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBrCode_11",""))%>';

	var d2MRInstAmt_12 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstAmt_12",""))%>';
        var d2MRInstNum_12 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstNum_12",""))%>';
        var d2MRInstDate_12 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstDate_12",""))%>';
        var d2MRPayingAcctNum_12 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRPayingAcctNum_12",""))%>';
        var d2MRBankCode_12 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBankCode_12",""))%>';
        var d2MRTranCode_12 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRTranCode_12",""))%>';
        var d2MRBatchNum_12 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBatchNum_12",""))%>';
        var d2MRTranId_12 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRTranId_12",""))%>';
        var d2MRPayingAcctName_12 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRPayingAcctName_12",""))%>';
        var d2MRBrCode_12 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBrCode_12",""))%>';

	var d2MRInstAmt_13 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstAmt_13",""))%>';
        var d2MRInstNum_13 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstNum_13",""))%>';
        var d2MRInstDate_13 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstDate_13",""))%>';
        var d2MRPayingAcctNum_13 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRPayingAcctNum_13",""))%>';
        var d2MRBankCode_13 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBankCode_13",""))%>';
        var d2MRTranCode_13 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRTranCode_13",""))%>';
        var d2MRBatchNum_13 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBatchNum_13",""))%>';
        var d2MRTranId_13 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRTranId_13",""))%>';
        var d2MRPayingAcctName_13 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRPayingAcctName_13",""))%>';
        var d2MRBrCode_13 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBrCode_13",""))%>';

	var d2MRInstAmt_14 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstAmt_14",""))%>';
        var d2MRInstNum_14 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstNum_14",""))%>';
        var d2MRInstDate_14 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstDate_14",""))%>';
        var d2MRPayingAcctNum_14 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRPayingAcctNum_14",""))%>';
        var d2MRBankCode_14 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBankCode_14",""))%>';
        var d2MRTranCode_14 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRTranCode_14",""))%>';
        var d2MRBatchNum_14 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBatchNum_14",""))%>';
        var d2MRTranId_14 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRTranId_14",""))%>';
        var d2MRPayingAcctName_14 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRPayingAcctName_14",""))%>';
        var d2MRBrCode_14 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBrCode_14",""))%>';

	var d2MRInstAmt_15 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstAmt_15",""))%>';
        var d2MRInstNum_15 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstNum_15",""))%>';
        var d2MRInstDate_15 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstDate_15",""))%>';
        var d2MRPayingAcctNum_15 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRPayingAcctNum_15",""))%>';
        var d2MRBankCode_15 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBankCode_15",""))%>';
        var d2MRTranCode_15 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRTranCode_15",""))%>';
        var d2MRBatchNum_15 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBatchNum_15",""))%>';
        var d2MRTranId_15 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRTranId_15",""))%>';
        var d2MRPayingAcctName_15 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRPayingAcctName_15",""))%>';
        var d2MRBrCode_15 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBrCode_15",""))%>';

        var d2MRInstAmt_16 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstAmt_16",""))%>';
        var d2MRInstNum_16 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstNum_16",""))%>';
        var d2MRInstDate_16 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstDate_16",""))%>';
        var d2MRPayingAcctNum_16 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRPayingAcctNum_16",""))%>';
        var d2MRBankCode_16 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBankCode_16",""))%>';
        var d2MRTranCode_16 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRTranCode_16",""))%>';
        var d2MRBatchNum_16 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBatchNum_16",""))%>';
        var d2MRTranId_16 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRTranId_16",""))%>';
        var d2MRPayingAcctName_16 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRPayingAcctName_16",""))%>';
        var d2MRBrCode_16 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBrCode_16",""))%>';

        var d2MRInstAmt_17 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstAmt_17",""))%>';
        var d2MRInstNum_17 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstNum_17",""))%>';
        var d2MRInstDate_17 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstDate_17",""))%>';
        var d2MRPayingAcctNum_17 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRPayingAcctNum_17",""))%>';
        var d2MRBankCode_17 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBankCode_17",""))%>';
        var d2MRTranCode_17 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRTranCode_17",""))%>';
        var d2MRBatchNum_17 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBatchNum_17",""))%>';
        var d2MRTranId_17 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRTranId_17",""))%>';
        var d2MRPayingAcctName_17 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRPayingAcctName_17",""))%>';
        var d2MRBrCode_17 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBrCode_17",""))%>';

        var d2MRInstAmt_18 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstAmt_18",""))%>';
        var d2MRInstNum_18 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstNum_18",""))%>';
        var d2MRInstDate_18 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstDate_18",""))%>';
        var d2MRPayingAcctNum_18 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRPayingAcctNum_18",""))%>';
        var d2MRBankCode_18 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBankCode_18",""))%>';
        var d2MRTranCode_18 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRTranCode_18",""))%>';
        var d2MRBatchNum_18 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBatchNum_18",""))%>';
        var d2MRTranId_18 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRTranId_18",""))%>';
        var d2MRPayingAcctName_18 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRPayingAcctName_18",""))%>';
        var d2MRBrCode_18 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBrCode_18",""))%>';

        var d2MRInstAmt_19 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstAmt_19",""))%>';
        var d2MRInstNum_19 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstNum_19",""))%>';
        var d2MRInstDate_19 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstDate_19",""))%>';
        var d2MRPayingAcctNum_19 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRPayingAcctNum_19",""))%>';
        var d2MRBankCode_19 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBankCode_19",""))%>';
        var d2MRTranCode_19 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRTranCode_19",""))%>';
        var d2MRBatchNum_19 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBatchNum_19",""))%>';
        var d2MRTranId_19 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRTranId_19",""))%>';
        var d2MRPayingAcctName_19 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRPayingAcctName_19",""))%>';
        var d2MRBrCode_19 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBrCode_19",""))%>';

        var d2MRInstAmt_20 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstAmt_20",""))%>';
        var d2MRInstNum_20 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstNum_20",""))%>';
        var d2MRInstDate_20 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstDate_20",""))%>';
        var d2MRPayingAcctNum_20 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRPayingAcctNum_20",""))%>';
        var d2MRBankCode_20 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBankCode_20",""))%>';
        var d2MRTranCode_20 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRTranCode_20",""))%>';
        var d2MRBatchNum_20 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBatchNum_20",""))%>';
        var d2MRTranId_20 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRTranId_20",""))%>';
        var d2MRPayingAcctName_20 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRPayingAcctName_20",""))%>';
        var d2MRBrCode_20 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBrCode_20",""))%>';


        var d2MRInstAmt_21 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstAmt_21",""))%>';
        var d2MRInstNum_21 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstNum_21",""))%>';
        var d2MRInstDate_21 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstDate_21",""))%>';
        var d2MRPayingAcctNum_21 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRPayingAcctNum_21",""))%>';
        var d2MRBankCode_21 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBankCode_21",""))%>';
        var d2MRTranCode_21 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRTranCode_21",""))%>';
        var d2MRBatchNum_21 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBatchNum_21",""))%>';
        var d2MRTranId_21 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRTranId_21",""))%>';
        var d2MRPayingAcctName_21 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRPayingAcctName_21",""))%>';
        var d2MRBrCode_21 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBrCode_21",""))%>';

        var d2MRInstAmt_22 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstAmt_22",""))%>';
        var d2MRInstNum_22 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstNum_22",""))%>';
        var d2MRInstDate_22 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstDate_22",""))%>';
        var d2MRPayingAcctNum_22 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRPayingAcctNum_22",""))%>';
        var d2MRBankCode_22 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBankCode_22",""))%>';
        var d2MRTranCode_22 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRTranCode_22",""))%>';
        var d2MRBatchNum_22 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBatchNum_22",""))%>';
        var d2MRTranId_22 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRTranId_22",""))%>';
        var d2MRPayingAcctName_22 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRPayingAcctName_22",""))%>';
        var d2MRBrCode_22 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBrCode_22",""))%>';

        var d2MRInstAmt_23 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstAmt_23",""))%>';
        var d2MRInstNum_23 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstNum_23",""))%>';
        var d2MRInstDate_23 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstDate_23",""))%>';
        var d2MRPayingAcctNum_23 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRPayingAcctNum_23",""))%>';
        var d2MRBankCode_23 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBankCode_23",""))%>';
        var d2MRTranCode_23 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRTranCode_23",""))%>';
        var d2MRBatchNum_23 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBatchNum_23",""))%>';
        var d2MRTranId_23 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRTranId_23",""))%>';
        var d2MRPayingAcctName_23 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRPayingAcctName_23",""))%>';
        var d2MRBrCode_23 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBrCode_23",""))%>';


        var d2MRInstAmt_24 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstAmt_24",""))%>';
        var d2MRInstNum_24 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstNum_24",""))%>';
        var d2MRInstDate_24 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstDate_24",""))%>';
        var d2MRPayingAcctNum_24 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRPayingAcctNum_24",""))%>';
        var d2MRBankCode_24 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBankCode_24",""))%>';
        var d2MRTranCode_24 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRTranCode_24",""))%>';
        var d2MRBatchNum_24 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBatchNum_24",""))%>';
        var d2MRTranId_24 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRTranId_24",""))%>';
        var d2MRPayingAcctName_24 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRPayingAcctName_24",""))%>';
        var d2MRBrCode_24 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBrCode_24",""))%>';

        var d2MRInstAmt_25 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstAmt_25",""))%>';
        var d2MRInstNum_25 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstNum_25",""))%>';
        var d2MRInstDate_25 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRInstDate_25",""))%>';
        var d2MRPayingAcctNum_25 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRPayingAcctNum_25",""))%>';
        var d2MRBankCode_25 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBankCode_25",""))%>';
        var d2MRTranCode_25 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRTranCode_25",""))%>';
        var d2MRBatchNum_25 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBatchNum_25",""))%>';
        var d2MRTranId_25 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRTranId_25",""))%>';
        var d2MRPayingAcctName_25 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRPayingAcctName_25",""))%>';
        var d2MRBrCode_25 = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".d2MRBrCode_25",""))%>';




</script>


<script language="javascript" src="../Renderer/custom/javascripts/hoccm/<%=VRPKeys.getCustomFile("hoccm_MULTI_REC_2.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("cust_pre_evt.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("cust_post_evt.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showAccountIdList.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("common_functions.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/custom/javascripts/hoccm/<%=VRPKeys.getFile("callVeracious.js",sProfileId)%>"></script>

<script language="JavaScript">
	printBlock1();
</script>
<script language="JavaScript">
	printBlock2();
</script>

<script language="JavaScript">
	printFooterBlock();
</script>

