logging:
  level:
    ROOT: INFO

# ssl configs
server:
  port: 60443
  ssl:
    # key-store for ssl and payload signing
    enabled: true
    key-store: '/Users/bishop/Programming/projects/work/WorkSpace/NetBeans/GAG/GAGApplications/PAPSS/certs/uat/channel-side/channel-services.p12'
    key-store-password: 'channel_services!'
    key-store-type: PKCS12
    key-aliases:
      omni: omni
      remittance: remittance

# enable this if you want to skip host verification, or trust all certs during mtls handshake
http:
  ssl:
    trust-all: true
    skip-hostname-verification: true

# Async thread configs
async:
  core-pool-size: 20        # Always keep 20 threads alive
  max-pool-size: 50         # Can burst up to 50 during spikes
  queue-capacity: 5000      # Buffer up to 5k tasks before rejecting
  keep-alive-seconds: 60    # Non-core threads live for 60s when idle

urls:
  namecheck: 'https://localhost:10443/api/v1/outbound/namecheck'
  transaction: 'https://localhost:10443/api/v1/outbound/credit-transfer'
  statusCheck: 'https://localhost:10443/api/v1/outbound/status-check'