SET DEFINE OFF;
Insert into CUSTOM.C_CPARAM_MASTER_TABLE
   (MODULE_NAME, PARAMETER_LEVEL, PARAMETER_ID, PARAMETER_DESC, PARAMETER_TYPE, QUERY_ID, LIST_TYPE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID)
 Values
   ('ERP', 'BNKL', 'ACCTNUM', 'Suspense Account for ERP', 'AN', ' ', 'FT', 'Y', 'N', 'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE, '11');
Insert into CUSTOM.C_CPARAM_MASTER_TABLE
   (MODULE_NAME, PARAMETER_LEVEL, PARAMETER_ID, PARAMETER_DESC, PARAMETER_TYPE, QUERY_ID, LIST_TYPE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID)
 Values
   ('ERP', 'BNKL', 'COUNT', 'Max Part Transaction for ERP ', 'AN', ' ', 'FT', 'Y', 'N', 'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE, '11');
Insert into CUSTOM.C_CPARAM_MASTER_TABLE
   (MODULE_NAME, PARAMETER_LEVEL, PARAMETER_ID, PARAMETER_DESC, PARAMETER_TYPE, QUERY_ID, LIST_TYPE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID)
 Values
   ('ERP', 'BNKL', 'PARTICULAR', 'Transaction Particulars', 'AN', ' ', 'FT', 'Y', 'N', 'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE, '11');
Insert into CUSTOM.C_CPARAM_MASTER_TABLE
   (MODULE_NAME, PARAMETER_LEVEL, PARAMETER_ID, PARAMETER_DESC, PARAMETER_TYPE, QUERY_ID, LIST_TYPE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID)
 Values
   ('ERP', 'BNKL', 'RATECODE', 'Rate Code to be used in ERP', 'AN', ' ', 'FT', 'Y', 'N', 'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE, '11');
Insert into CUSTOM.C_CPARAM_MASTER_TABLE
   (MODULE_NAME, PARAMETER_LEVEL, PARAMETER_ID, PARAMETER_DESC, PARAMETER_TYPE, QUERY_ID, LIST_TYPE, ENTITY_CRE_FLG, DEL_FLG, RCRE_USER_ID, RCRE_TIME, LCHG_USER_ID, LCHG_TIME, BANK_ID)
 Values
   ('ERP', 'BNKL', 'TRAN_NAME', 'Transaction Name', 'AN', ' ', 'FT', 'Y', 'N', 'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE, '11');
COMMIT;
