DROP TABLE CUSTOM.C_WTH_ACCT_OPEN CASCADE CONSTRAINTS;

CREATE TABLE CUSTOM.C_WTH_ACCT_OPEN
(
  WTH_TAX_APP_FLG             CHAR(1 BYTE),
  FORACID                     VARCHAR2(16 CHAR ),
  SCHM_TYPE                   VARCHAR2 (3 CHAR),
  SCHM_CODE                   VARCHAR2 (5 CHAR),
  LCHG_USER_ID                VARCHAR2(15 CHAR),
  LCHG_TIME                   DATE,
  RCRE_USER_ID                VARCHAR2(15 CHAR),
  RCRE_TIME                   DATE,
  DEL_FLG                     CHAR (1 Byte),
  ENTITY_CRE_FLG              CHAR (1 Byte),
  BANK_ID          	      VARCHAR2(8 CHAR)
 ) 
 TABLESPACE SYSTEM;
 
 
 CREATE UNIQUE INDEX CUSTOM.IDX_C_WTH_ACCT_OPEN ON CUSTOM.C_WTH_ACCT_OPEN
 (FORACID,BANK_ID)
 LOGGING
 TABLESPACE IDX_TRANS
 PCTFREE    10
 INITRANS   2
 MAXTRANS   255
 STORAGE    (
             INITIAL          1M
             NEXT             1M
             MINEXTENTS       1
             MAXEXTENTS       UNLIMITED
             PCTINCREASE      0
             BUFFER_POOL      DEFAULT
            )
NOPARALLEL;

DROP SYNONYM CUSTOM.C_WTHAO;

CREATE SYNONYM CUSTOM.C_WTHAO FOR CUSTOM.C_WTH_ACCT_OPEN;


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON CUSTOM.C_WTH_ACCT_OPEN TO TBAADM;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON CUSTOM.C_WTH_ACCT_OPEN TO TBAGEN;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON CUSTOM.C_WTH_ACCT_OPEN TO TBAUTIL;





 
