

CREATE TABLE CUSTOM.CCARD_SETTLEMENT_TABLE
(
  ROW_CODE               VARCHAR2(2 BYTE),
  ROW_NUMBER             VARCHAR2(6 BYTE),
  TRANSFER_NUMBER        VARCHAR2(10 BYTE),
  TRANSFER_CODE          VARCHAR2(8 BYTE),
  DEBIT_ACCOUNT          VARCHAR2(32 BYTE),
  CREDIT_ACCOUNT         VARCHAR2(32 BYTE),
  TRANSFER_AMOUNT        VARCHAR2(15 BYTE),
  TRANSFER_LOCAL_AMOUNT  VARCHAR2(15 BYTE),
  TRANSFER_DESCRIPTOR    VARCHAR2(100 BYTE),
  AMOUNT_SIGN            VARCHAR2(1 BYTE),
  GROUP_IDENTIFIER       VARCHAR2(9 BYTE),
  TRANSFER_TYPE          VARCHAR2(1 BYTE),
  REFERENCE_NUMBER       VARCHAR2(32 BYTE),
  RESERVED               VARCHAR2(7 BYTE),
  TERMINAL_SYMBOL        VARCHAR2(1 BYTE),
  DELIMITER              VARCHAR2(2 BYTE),
  PARTICULARS            VARCHAR2(80 BYTE),
  UPLDSTATUS             VARCHAR2(1 BYTE),
  VALID                  VARCHAR2(1 BYTE),
  REMARKS                VARCHAR2(30 BYTE),
  BANK_ID                VARCHAR2(8 BYTE)
);


CREATE OR REPLACE SYNONYM CUSTOM.C_CCST FOR CUSTOM.CCARD_SETTLEMENT_TABLE;


GRANT SELECT ON CUSTOM.CCARD_SETTLEMENT_TABLE TO ALLTAB;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.CCARD_SETTLEMENT_TABLE TO TBAADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.CCARD_SETTLEMENT_TABLE TO TBAGEN;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.CCARD_SETTLEMENT_TABLE TO TBAUTIL;

