DROP TABLE CUSTOM.CUST_INWREM_TABLE CASCADE CONSTRAINTS;

CREATE TABLE CUSTOM.CUST_INWREM_TABLE
(
  ACID          VARCHAR2(11 CHAR),
  FORACID       VARCHAR2(16 CHAR),
  ZONE_CODE     VARCHAR2(10 CHAR),
  ZONE_DATE     DATE,
  SOL_ID        VARCHAR2(8 CHAR),
  ZONE_SRL_NUM  VARCHAR2(6 CHAR),
  INST_NUM      VARCHAR2(16 CHAR),
  INST_AMT      NUMBER(20,4),
  REJ_TYPE      CHAR(1 BYTE),
  REJ_CODE_1    VARCHAR2(2 CHAR),
  RCRE_USER_ID  VARCHAR2(15 CHAR),
  RCRE_TIME     DATE,
  BANK_ID       VARCHAR2(8 CHAR)
);


CREATE UNIQUE INDEX CUSTOM.IDX_CUST_INWREM_TABLE ON CUSTOM.CUST_INWREM_TABLE
(ZONE_CODE, ZONE_DATE, SOL_ID, ZONE_SRL_NUM, BANK_ID);

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.CUST_INWREM_TABLE TO TBAADM;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.CUST_INWREM_TABLE TO TBAGEN;

GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.CUST_INWREM_TABLE TO TBAUTIL;

GRANT SELECT ON CUSTOM.CUST_INWREM_TABLE TO ALLTAB;
