DROP TABLE CUSTOM.C_WTH_GSP_DET CASCADE CONSTRAINTS;

CREATE TABLE CUSTOM.C_WTH_GSP_DET
(
  WTH_TAX_APP_FLG             CHAR(1 CHAR),
  WTH_TAX_PCNT                NUMBER(20,4),
  BACID                       VARCHAR2(16 CHAR),
  SCHM_TYPE                   VARCHAR2 (3 Char),
  SCHM_CODE                   VARCHAR2 (5 Char),
  MOP_ID                      VARCHAR2 (8 Char),
  DEL_FLG                     CHAR (1 Byte),
  ENTITY_CRE_FLG              CHAR (1 Byte),
  BANK_ID                     VARCHAR2(8 CHAR)
 ) 
/

CREATE UNIQUE INDEX CUSTOM.C_WTH_GSP_DET_PK ON CUSTOM.C_WTH_GSP_DET (SCHM_TYPE,SCHM_CODE,MOP_ID,BANK_ID);

DROP SYNONYM CUSTOM.C_WTHD;

CREATE SYNONYM CUSTOM.C_WTHD FOR CUSTOM.C_WTH_GSP_DET;


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON CUSTOM.C_WTH_GSP_DET TO TBAADM;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON CUSTOM.C_WTH_GSP_DET TO TBAGEN;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON CUSTOM.C_WTH_GSP_DET TO TBAUTIL;





 
