Rem     This file will insert records into C_EIT_HIST table
Rem     selecting from EIT and GAM table.

INSERT INTO CUSTOM.C_EIT_HIST SELECT 
EIT.ENTITY_ID ,
EIT.ENTITY_TYPE ,
GCT.DB_STAT_DATE ,
EIT.ACCRUED_UPTO_DATE_CR ,
EIT.ACCRUED_UPTO_DATE_DR ,
EIT.LAST_ACCRUAL_RUN_DATE_CR ,
EIT.LAST_ACCRUAL_RUN_DATE_DR ,
EIT.BOOKED_UPTO_DATE_CR ,
EIT.BOOKED_UPTO_DATE_DR ,
EIT.LAST_BOOK_RUN_DATE_CR ,
EIT.LAST_BOOK_RUN_DATE_DR ,
EIT.BOOK_FOR_REV_DATE_CR ,
EIT.BOOK_FOR_REV_DATE_DR ,
EIT.LAST_BOOK_CR_TRAN_ID ,
EIT.LAST_BOOK_DR_TRAN_ID ,
EIT.LAST_BOOK_CR_TAN_DATE ,
EIT.LAST_BOOK_DR_TAN_DATE ,
EIT.INTEREST_CALC_UPTO_DATE_CR ,
EIT.INTEREST_CALC_UPTO_DATE_DR ,
EIT.LAST_INTEREST_RUN_DATE_CR ,
EIT.LAST_INTEREST_RUN_DATE_DR ,
EIT.LAST_INT_CR_TRAN_ID ,
EIT.LAST_INT_DR_TRAN_ID ,
EIT.LAST_INT_CR_TRAN_DATE ,
EIT.LAST_INT_DR_TRAN_DATE ,
EIT.CUMM_CR_INT_ADJ_AMT ,
EIT.CUMM_DR_INT_ADJ_AMT ,
EIT.NEXT_INT_RUN_DATE_DR ,
EIT.TOT_INT_PAID_LAST_FY ,
EIT.TOT_INT_COLL_LAST_FY ,
EIT.TOT_DR_INT_ACC_LAST_FY ,
EIT.TOT_CR_INT_ACC_LAST_FY ,
EIT.NRML_ACCRUED_AMOUNT_CR ,
EIT.NRML_ACCRUED_AMOUNT_DR ,
EIT.NRML_BOOKED_AMOUNT_CR ,
EIT.NRML_BOOKED_AMOUNT_DR ,
EIT.NRML_INTEREST_AMOUNT_CR ,
EIT.NRML_INTEREST_AMOUNT_DR ,
EIT.NRML_ADV_INT_AMOUNT_CR ,
EIT.NRML_ADV_INT_AMOUNT_DR ,
EIT.NRML_AMORTIZED_AMOUNT_CR ,
EIT.NRML_AMORTIZED_AMOUNT_DR ,
EIT.NRML_INT_SUSPENSE_AMT_DR ,
EIT.PENAL_ACCRUED_AMOUNT_DR ,
EIT.PENAL_BOOKED_AMOUNT_DR ,
EIT.PENAL_INTEREST_AMOUNT_DR ,
EIT.PENAL_ADV_INT_AMOUNT_DR ,
EIT.PENAL_AMORTIZED_AMOUNT_DR ,
EIT.PENAL_INT_SUSPENSE_AMT_DR ,
EIT.ADDNL_ACCRUED_AMOUNT_DR ,
EIT.ADDNL_BOOKED_AMOUNT_DR ,
EIT.ADDNL_INTEREST_AMOUNT_DR ,
EIT.QIS_ACCRUED_AMOUNT_DR ,
EIT.QIS_BOOKED_AMOUNT_DR ,
EIT.QIS_INTEREST_AMOUNT_DR ,
EIT.STOCK_ACCRUED_AMOUNT_DR ,
EIT.STOCK_BOOKED_AMOUNT_DR ,
EIT.STOCK_INTEREST_AMOUNT_DR ,
EIT.OVDU_ACCRUED_AMOUNT_DR ,
EIT.OVDU_BOOKED_AMOUNT_DR ,
EIT.OVDU_INTEREST_AMOUNT_DR ,
EIT.NO_RECALC_BEFORE_DATE ,
EIT.CURR_ADV_INT_AMT ,
EIT.INT_DAILY_FACTOR ,
EIT.COMPINT_ACCRUED_AMOUNT_DR ,
EIT.COMPINT_BOOKED_AMOUNT_DR ,
EIT.COMPINT_INTEREST_AMOUNT_DR ,
EIT.PENALINT_ACCRUED_AMOUNT_DR ,
EIT.PENALINT_BOOKED_AMOUNT_DR ,
EIT.PENALINT_INTEREST_AMOUNT_DR ,
EIT.PENALPRNC_ACCRUED_AMOUNT_DR ,
EIT.PENALPRNC_BOOKED_AMOUNT_DR ,
EIT.PENALPRNC_INTEREST_AMOUNT_DR ,
EIT.COMPPRNC_ACCRUED_AMOUNT_DR ,
EIT.COMPPRNC_BOOKED_AMOUNT_DR ,
EIT.COMPPRNC_INTEREST_AMOUNT_DR ,
EIT.UNPAID_NRML_INT_AMOUNT_CR ,
EIT.LAST_NRML_BOOKED_AMOUNT_CR ,
EIT.LAST_NRML_BOOKED_AMOUNT_DR ,
EIT.LAST_PENAL_BOOKED_AMOUNT_DR ,
EIT.LAST_ADDNL_BOOKED_AMOUNT_DR ,
EIT.LAST_QIS_BOOKED_AMOUNT_DR ,
EIT.LAST_STOCK_BOOKED_AMOUNT_DR ,
EIT.LAST_OVDU_BOOKED_AMOUNT_DR ,
EIT.LAST_COMPINT_BOOKED_AMOUNT_DR ,
EIT.LAST_PENALINT_BOOKED_AMOUNT_DR ,
EIT.LAST_PENPRNC_BOOKED_AMOUNT_DR ,
EIT.LAST_COMPPRNC_BOOKED_AMOUNT_DR ,
EIT.COMPOUND_AMOUNT_CR ,
EIT.COMPOUND_DATE_CR ,
EIT.INTEREST_RATE ,
EIT.LCHG_USER_ID ,
EIT.LCHG_TIME ,
EIT.RCRE_USER_ID ,
EIT.RCRE_TIME,
EIT.BANK_ID 
FROM TBAADM.EIT,TBAADM.GCT
WHERE EIT.BANK_ID=GCT.BANK_ID
AND EIT.BANK_ID='&1'
/
COMMIT
/
declare

cursor c1 is 
select gct.bank_id,db_stat_date,acid,int_suspense_amt,penal_int_suspense_amt from 
tbaadm.cot,tbaadm.gct 
where gct.bank_id='&1' and cot.bank_id='&1';

begin
    for rec in c1 loop
        begin
            update CUSTOM.C_EIT_HIST set NRML_INT_SUSPENSE_AMT_DR=rec.int_suspense_amt,PENAL_INT_SUSPENSE_AMT_DR=rec.penal_int_suspense_amt
            where BOD_DATE=rec.db_stat_date
            and entity_type='ACCNT'
            and entity_id=rec.acid
            and bank_id=rec.bank_id;
        exception when others then
            NULL;
        end;
    
    end loop;
end;
/
COMMIT
/
declare

cursor c1 is 
select gct.bank_id,db_stat_date,acid,int_suspense_amt,penal_int_suspense_amt from 
tbaadm.ta_cot,tbaadm.gct 
where gct.bank_id='&1' and ta_cot.bank_id='&1';

begin
    for rec in c1 loop
        begin
            update CUSTOM.C_EIT_HIST set NRML_INT_SUSPENSE_AMT_DR=rec.int_suspense_amt,PENAL_INT_SUSPENSE_AMT_DR=rec.penal_int_suspense_amt
            where BOD_DATE=rec.db_stat_date
            and entity_type='ACCNT'
            and entity_id=rec.acid
            and bank_id=rec.bank_id;
        exception when others then
            NULL;
        end;
    
    end loop;
end;
/
COMMIT
/
exit
/
