
  CREATE TABLE "CUSTOM"."CUSTOM_FINACLEUSER_MAPPING_TBL" 
   (	"ROLE_ID" VARCHAR2(15 CHAR), 
	"USER_WORK_CLASS" VARCHAR2(3 CHAR), 
	"DESCRIPTION" VARCHAR2(50 CHAR), 
	"PROXY_POST_ALLWD" CHAR(1 BYTE), 
	"REMOTE_ACCESS_FLG" CHAR(1 BYTE), 
	"VIRTUAL_FLG" CHAR(1 BYTE), 
	"PRIMARY_GROUP_ID" VARCHAR2(30 CHAR), 
	"USER_GROUP_NAME" VARCHAR2(30 CHAR), 
	"IS_GLOBAL_ADMIN" CHAR(1 BYTE), 
	"SSO_ROLE_ID" VARCHAR2(15 CHAR), 
	"SSO_ROLE_NAME" VARCHAR2(30 CHAR), 
	"ASSIGN_SSOADMIN" CHAR(1 BYTE), 
	"CRE_ASSIGN_SVSSERVER" CHAR(1 BYTE), 
	"CRE_ASSIGN_REPORT_INFRA" CHAR(1 BYTE), 
	"ASSIGN_ADMIN_WORKFLOW" CHAR(1 BYTE), 
	"ASSIGN_FCSE" CHAR(1 BYTE), 
	"ASSIGN_FINACLE_INTEGRATOR" CHAR(1 BYTE), 
	"CRE_ASSIGN_CORE_SERVER" CHAR(1 BYTE), 
	"ASSIGN_CRM_SERVICE" CHAR(1 BYTE), 
	"CRE_ASSIGN_CRM_SERVER" CHAR(1 BYTE), 
	 CONSTRAINT "C_USERMAPPING" UNIQUE ("ROLE_ID", "USER_WORK_CLASS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 16384 NEXT 16384 MINEXTENTS 1 MAXEXTENTS 505
  PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CUSTOM_TBLS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 16384 NEXT 16384 MINEXTENTS 1 MAXEXTENTS 505
  PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CUSTOM_TBLS" ;

  CREATE OR REPLACE SYNONYM "CUSTOM"."C_FINACLEUSER_MAPPING_TBL" FOR "CUSTOM"."CUSTOM_FINACLEUSER_MAPPING_TBL";
  
  GRANT UPDATE ON "CUSTOM"."CUSTOM_FINACLEUSER_MAPPING_TBL" TO "TBAUTIL";
  GRANT SELECT ON "CUSTOM"."CUSTOM_FINACLEUSER_MAPPING_TBL" TO "TBAUTIL";
  GRANT INSERT ON "CUSTOM"."CUSTOM_FINACLEUSER_MAPPING_TBL" TO "TBAUTIL";
  GRANT DELETE ON "CUSTOM"."CUSTOM_FINACLEUSER_MAPPING_TBL" TO "TBAUTIL";
  GRANT UPDATE ON "CUSTOM"."CUSTOM_FINACLEUSER_MAPPING_TBL" TO "TBAGEN";
  GRANT SELECT ON "CUSTOM"."CUSTOM_FINACLEUSER_MAPPING_TBL" TO "TBAGEN";
  GRANT INSERT ON "CUSTOM"."CUSTOM_FINACLEUSER_MAPPING_TBL" TO "TBAGEN";
  GRANT DELETE ON "CUSTOM"."CUSTOM_FINACLEUSER_MAPPING_TBL" TO "TBAGEN";
  GRANT UPDATE ON "CUSTOM"."CUSTOM_FINACLEUSER_MAPPING_TBL" TO "TBAADM";
  GRANT SELECT ON "CUSTOM"."CUSTOM_FINACLEUSER_MAPPING_TBL" TO "TBAADM";
  GRANT INSERT ON "CUSTOM"."CUSTOM_FINACLEUSER_MAPPING_TBL" TO "TBAADM";
  GRANT DELETE ON "CUSTOM"."CUSTOM_FINACLEUSER_MAPPING_TBL" TO "TBAADM";
