CREATE TABLE CUSTOM.INTERENTITY_TRAN_DETAIL_TBL
(
  IE_TXN_REF_NO         VARCHAR2(10 CHAR),
  TRAN_TYPE             CHAR(1 BYTE),
  TRAN_SUB_TYPE         VARCHAR2(2 CHAR),
  INIT_ENTITY_ID        VARCHAR2(8 CHAR),
  TARGET_ENTITY_ID      VARCHAR2(8 CHAR),
  ENTITY1_TRAN_ID       VARCHAR2(9 CHAR),
  ENTITY1_TRAN_DATE     DATE,
  ENTITY2_TRAN_ID       VARCHAR2(9 CHAR),
  ENTITY2_TRAN_DATE     DATE,
  CHARGE_TRAN_ID        VARCHAR2(9 CHAR),
  CHARGE_TRAN_DATE      DATE,
  CR_ACCOUNT_ID         VARCHAR2(16 CHAR),
  DR_ACCOUNT_ID         VARCHAR2(16 CHAR),
  REF_AMT               NUMBER(20,4),
  REF_CRNCY_CODE        VARCHAR2(3 CHAR),
  RATE_CODE             VARCHAR2(5 CHAR),
  RATE                  NUMBER(21,10),
  TRAN_AMT              NUMBER(20,4),
  TRAN_CRNCY_CODE       VARCHAR2(3 CHAR),
  CHARGE_EVENT_ID       VARCHAR2(25 CHAR),
  CHARGE_AMT            NUMBER(20,4),
  CHARGE_CRNCY_CODE     VARCHAR2(3 CHAR),
  REF_NO                VARCHAR2(20 CHAR),
  NOSTRO_ACCOUNT_ID     VARCHAR2(16 CHAR),
  VOSTRO_ACCOUNT_ID     VARCHAR2(16 CHAR),
  INSTRMNT_ALPHA        VARCHAR2(6 CHAR),
  INSTRMNT_DATE         DATE,
  INSTRMNT_NUM          VARCHAR2(16 CHAR),
  INSTRMNT_TYPE         VARCHAR2(5 CHAR),
  TRAN_PARTICULAR_CODE  VARCHAR2(5 CHAR),
  TRAN_PARTICULAR       VARCHAR2(50 CHAR),
  REMARKS1              VARCHAR2(30 CHAR),
  REMARKS2              VARCHAR2(50 CHAR),
  ZONE_CODE             VARCHAR2(10 CHAR),
  ZONE_CCY              VARCHAR2(3 CHAR),
  ZONE_DATE             DATE,
  VALUE_DATE            DATE,
  REVERSE_FLG           CHAR(1 BYTE),
  LCHG_USER_ID          VARCHAR2(15 CHAR),
  LCHG_TIME             DATE,
  RCRE_USER_ID          VARCHAR2(15 CHAR),
  RCRE_TIME             DATE,
  TREA_REF_NUM          VARCHAR2(16 CHAR),
  TREA_RATE             NUMBER(21,10)
);


CREATE SYNONYM TBAADM.INTERENTITY_TRAN_DETAIL_TBL FOR CUSTOM.INTERENTITY_TRAN_DETAIL_TBL;


CREATE SYNONYM TBAGEN.INTERENTITY_TRAN_DETAIL_TBL FOR CUSTOM.INTERENTITY_TRAN_DETAIL_TBL;


CREATE SYNONYM TBAUTIL.INTERENTITY_TRAN_DETAIL_TBL FOR CUSTOM.INTERENTITY_TRAN_DETAIL_TBL;


CREATE SYNONYM TBAADM.IETD FOR CUSTOM.INTERENTITY_TRAN_DETAIL_TBL;


CREATE SYNONYM TBAGEN.IETD FOR CUSTOM.INTERENTITY_TRAN_DETAIL_TBL;


CREATE SYNONYM TBAUTIL.IETD FOR CUSTOM.INTERENTITY_TRAN_DETAIL_TBL;


CREATE SYNONYM CUSTOM.IETD FOR CUSTOM.INTERENTITY_TRAN_DETAIL_TBL;


GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOM.INTERENTITY_TRAN_DETAIL_TBL TO TBAGEN;

GRANT SELECT ON CUSTOM.INTERENTITY_TRAN_DETAIL_TBL TO TBAUTIL;
