CREATE SEQUENCE CUSTOM.ICHQBOOKREQ_SEQ_11
  START WITH 1
  MAXVALUE 99999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


CREATE SYNONYM CUSTOM.ICHQBOOKREQ_SEQ_11_SYN FOR CUSTOM.ICHQBOOKREQ_SEQ_11;


GRANT SELECT ON CUSTOM.ICHQBOOKREQ_SEQ_11 TO TBAADM;

GRANT SELECT ON CUSTOM.ICHQBOOKREQ_SEQ_11 TO TBAGEN;

GRANT SELECT ON CUSTOM.ICHQBOOKREQ_SEQ_11 TO TBAUTIL;


CREATE SEQUENCE CUSTOM.ICHQBOOKREQ_SEQ_50
  START WITH 1
  MAXVALUE 99999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


CREATE SYNONYM CUSTOM.ICHQBOOKREQ_SEQ_50_SYN FOR CUSTOM.ICHQBOOKREQ_SEQ_50;


GRANT SELECT ON CUSTOM.ICHQBOOKREQ_SEQ_50 TO TBAADM;

GRANT SELECT ON CUSTOM.ICHQBOOKREQ_SEQ_50 TO TBAGEN;

GRANT SELECT ON CUSTOM.ICHQBOOKREQ_SEQ_50 TO TBAUTIL;


CREATE SEQUENCE CUSTOM.ICHQBOOKREQ_SEQ_54
  START WITH 1
  MAXVALUE 99999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


CREATE SYNONYM CUSTOM.ICHQBOOKREQ_SEQ_54_SYN FOR CUSTOM.ICHQBOOKREQ_SEQ_54;


GRANT SELECT ON CUSTOM.ICHQBOOKREQ_SEQ_54 TO TBAADM;

GRANT SELECT ON CUSTOM.ICHQBOOKREQ_SEQ_54 TO TBAGEN;

GRANT SELECT ON CUSTOM.ICHQBOOKREQ_SEQ_54 TO TBAUTIL;


CREATE SEQUENCE CUSTOM.ICHQBOOKREQ_SEQ_55
  START WITH 1
  MAXVALUE 99999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


CREATE SYNONYM CUSTOM.ICHQBOOKREQ_SEQ_55_SYN FOR CUSTOM.ICHQBOOKREQ_SEQ_55;


GRANT SELECT ON CUSTOM.ICHQBOOKREQ_SEQ_55 TO TBAADM;

GRANT SELECT ON CUSTOM.ICHQBOOKREQ_SEQ_55 TO TBAGEN;

GRANT SELECT ON CUSTOM.ICHQBOOKREQ_SEQ_55 TO TBAUTIL;


CREATE SEQUENCE CUSTOM.ICHQBOOKREQ_SEQ_56
  START WITH 1
  MAXVALUE 99999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


CREATE SYNONYM CUSTOM.ICHQBOOKREQ_SEQ_56_SYN FOR CUSTOM.ICHQBOOKREQ_SEQ_56;


GRANT SELECT ON CUSTOM.ICHQBOOKREQ_SEQ_56 TO TBAADM;

GRANT SELECT ON CUSTOM.ICHQBOOKREQ_SEQ_56 TO TBAGEN;

GRANT SELECT ON CUSTOM.ICHQBOOKREQ_SEQ_56 TO TBAUTIL;
