CREATE TABLE CUSTOM.EQU_UPLOAD_TABLE
(
  UPLDREFNUM    VARCHAR2(16 BYTE),
  UPLDNAME      VARCHAR2(80 BYTE),
  AMOUNT        NUMBER(20,4),
  FORACID       VARCHAR2(16 BYTE),
  ACCT_NAME     VARCHAR2(80 BYTE),
  SOL_ID        VARCHAR2(8 BYTE),
  VALID         VARCHAR2(1 BYTE),
  REMARKS       VARCHAR2(80 BYTE),
  RCRE_USER_ID  VARCHAR2(15 BYTE),
  UPLDSTATUS    VARCHAR2(1 BYTE),
  FILE_NAME     VARCHAR2(80 BYTE),
  PF_NUMBER     VARCHAR2(20 BYTE),
  BANK_ID       VARCHAR2(3 BYTE)
);


CREATE INDEX CUSTOM.IDX_C_EQU_FORACID ON CUSTOM.EQU_UPLOAD_TABLE
(FORACID, BANK_ID)
;


CREATE SYNONYM CUSTOM.C_EQU FOR CUSTOM.EQU_UPLOAD_TABLE;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON CUSTOM.EQU_UPLOAD_TABLE TO TBAADM;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON CUSTOM.EQU_UPLOAD_TABLE TO TBAGEN;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON CUSTOM.EQU_UPLOAD_TABLE TO TBAUTIL;


