SET DEFINE OFF;
Insert into TBAADM.EXT
   (EXCP_CODE, DEL_FLG, CODE_TYPE, MIN_WORK_CLASS, EXCP_WORK_CLASS, TOT_MOD_TIMES, LCHG_USER_ID, LCHG_TIME, RCRE_USER_ID, RCRE_TIME, IGNORE_XCPN_FLG, IGNORE_PTRAN_TYPE, TS_CNT, AUTH_MATRIX_ID, BANK_ID, CHANNEL_EXCPN_FLG)
 Values
   ('A01', 'N', 'X', '110', 
    '110', 0, 'CM03356', sysdate, 'SYSTEM', 
    sysdate, 'N', ' ', 1, 'REF2', 
    '11', 'N');
Insert into TBAADM.EXT
   (EXCP_CODE, DEL_FLG, CODE_TYPE, MIN_WORK_CLASS, EXCP_WORK_CLASS, TOT_MOD_TIMES, LCHG_USER_ID, LCHG_TIME, RCRE_USER_ID, RCRE_TIME, IGNORE_XCPN_FLG, IGNORE_PTRAN_TYPE, TS_CNT, AUTH_MATRIX_ID, BANK_ID, CHANNEL_EXCPN_FLG)
 Values
   ('A01', 'N', 'X', '150', 
    '150', 0, 'VIJJI2', sysdate, 'SYSTEM', 
    sysdate, 'N', ' ', 2, 'REF2', 
    '50', 'N');
Insert into TBAADM.EXT
   (EXCP_CODE, DEL_FLG, CODE_TYPE, MIN_WORK_CLASS, EXCP_WORK_CLASS, TOT_MOD_TIMES, LCHG_USER_ID, LCHG_TIME, RCRE_USER_ID, RCRE_TIME, IGNORE_XCPN_FLG, IGNORE_PTRAN_TYPE, TS_CNT, AUTH_MATRIX_ID, BANK_ID, CHANNEL_EXCPN_FLG)
 Values
   ('A01', 'N', 'X', '150', 
    '150', 0, 'TEST1', sysdate, 'SYSTEM', 
    sysdate, 'Y', ' ', 5, 'REF2', 
    '54', 'Y');
Insert into TBAADM.EXT
   (EXCP_CODE, DEL_FLG, CODE_TYPE, MIN_WORK_CLASS, EXCP_WORK_CLASS, TOT_MOD_TIMES, LCHG_USER_ID, LCHG_TIME, RCRE_USER_ID, RCRE_TIME, IGNORE_XCPN_FLG, IGNORE_PTRAN_TYPE, TS_CNT, AUTH_MATRIX_ID, BANK_ID, CHANNEL_EXCPN_FLG)
 Values
   ('A01', 'N', 'X', '110', 
    '110', 0, 'SYSTEM', sysdate, 'SYSTEM', 
    sysdate, 'N', ' ', 1, 'REF1', 
    '55', 'N');
Insert into TBAADM.EXT
   (EXCP_CODE, DEL_FLG, CODE_TYPE, MIN_WORK_CLASS, EXCP_WORK_CLASS, TOT_MOD_TIMES, LCHG_USER_ID, LCHG_TIME, RCRE_USER_ID, RCRE_TIME, IGNORE_XCPN_FLG, IGNORE_PTRAN_TYPE, TS_CNT, AUTH_MATRIX_ID, BANK_ID, CHANNEL_EXCPN_FLG)
 Values
   ('A01', 'N', 'X', '110', 
    '110', 0, 'SYSTEM', sysdate, 'SYSTEM', 
    sysdate, 'N', ' ', 6, 'REF1', 
    '56', 'N');
--COMMIT;


Insert into TBAADM.EXT
   (EXCP_CODE, DEL_FLG, CODE_TYPE, MIN_WORK_CLASS, EXCP_WORK_CLASS, TOT_MOD_TIMES, LCHG_USER_ID, LCHG_TIME, RCRE_USER_ID, RCRE_TIME, IGNORE_XCPN_FLG, IGNORE_PTRAN_TYPE, TS_CNT, AUTH_MATRIX_ID, BANK_ID, CHANNEL_EXCPN_FLG)
 Values
   ('A02', 'N', 'X', '110', 
    '110', 0, 'CM03356', sysdate, 'SYSTEM', 
    sysdate, 'N', ' ', 1, 'REF2', 
    '11', 'N');
Insert into TBAADM.EXT
   (EXCP_CODE, DEL_FLG, CODE_TYPE, MIN_WORK_CLASS, EXCP_WORK_CLASS, TOT_MOD_TIMES, LCHG_USER_ID, LCHG_TIME, RCRE_USER_ID, RCRE_TIME, IGNORE_XCPN_FLG, IGNORE_PTRAN_TYPE, TS_CNT, AUTH_MATRIX_ID, BANK_ID, CHANNEL_EXCPN_FLG)
 Values
   ('A02', 'N', 'X', '150', 
    '150', 0, 'VIJJI2', sysdate, 'SYSTEM', 
    sysdate, 'N', ' ', 2, 'REF2', 
    '50', 'N');
Insert into TBAADM.EXT
   (EXCP_CODE, DEL_FLG, CODE_TYPE, MIN_WORK_CLASS, EXCP_WORK_CLASS, TOT_MOD_TIMES, LCHG_USER_ID, LCHG_TIME, RCRE_USER_ID, RCRE_TIME, IGNORE_XCPN_FLG, IGNORE_PTRAN_TYPE, TS_CNT, AUTH_MATRIX_ID, BANK_ID, CHANNEL_EXCPN_FLG)
 Values
   ('A02', 'N', 'X', '150', 
    '150', 0, 'TEST1', sysdate, 'SYSTEM', 
    sysdate, 'Y', ' ', 5, 'REF2', 
    '54', 'Y');
Insert into TBAADM.EXT
   (EXCP_CODE, DEL_FLG, CODE_TYPE, MIN_WORK_CLASS, EXCP_WORK_CLASS, TOT_MOD_TIMES, LCHG_USER_ID, LCHG_TIME, RCRE_USER_ID, RCRE_TIME, IGNORE_XCPN_FLG, IGNORE_PTRAN_TYPE, TS_CNT, AUTH_MATRIX_ID, BANK_ID, CHANNEL_EXCPN_FLG)
 Values
   ('A02', 'N', 'X', '110', 
    '110', 0, 'SYSTEM', sysdate, 'SYSTEM', 
    sysdate, 'N', ' ', 1, 'REF1', 
    '55', 'N');
Insert into TBAADM.EXT
   (EXCP_CODE, DEL_FLG, CODE_TYPE, MIN_WORK_CLASS, EXCP_WORK_CLASS, TOT_MOD_TIMES, LCHG_USER_ID, LCHG_TIME, RCRE_USER_ID, RCRE_TIME, IGNORE_XCPN_FLG, IGNORE_PTRAN_TYPE, TS_CNT, AUTH_MATRIX_ID, BANK_ID, CHANNEL_EXCPN_FLG)
 Values
   ('A02', 'N', 'X', '110', 
    '110', 0, 'SYSTEM', sysdate, 'SYSTEM', 
    sysdate, 'N', ' ', 6, 'REF1', 
    '56', 'N');
	
	
	
	
	
	--Adding Record in MMSG

Insert into TBAADM.MMSG
   (MSG_ID, DEL_FLG, MSG_LITERAL, MSG_LENGTH, SOURCE_TYPE, SOURCE_FILE, VERIFIED_FLG, ALT_MSG_LENGTH)
 Values
   ('EXT54A01', 'N', 'AMOUNT BASED REFERRAL', 0, 'EXT', 
    'EXCEPTIONS', ' ', 0);

Insert into TBAADM.MMSG
   (MSG_ID, DEL_FLG, MSG_LITERAL, MSG_LENGTH, SOURCE_TYPE, SOURCE_FILE, VERIFIED_FLG, ALT_MSG_LENGTH)
 Values
   ('EXT50A01', 'N', 'AMOUNT BASED REFERRAL', 0, 'EXT', 
    'EXCEPTIONS', ' ', 0);

Insert into TBAADM.MMSG
   (MSG_ID, DEL_FLG, MSG_LITERAL, MSG_LENGTH, SOURCE_TYPE, SOURCE_FILE, VERIFIED_FLG, ALT_MSG_LENGTH)
 Values
   ('EXT11A01', 'N', 'AMOUNT BASED REFERRAL', 0, 'EXT', 
    'EXCEPTIONS', ' ', 0);
	
Insert into TBAADM.MMSG
   (MSG_ID, DEL_FLG, MSG_LITERAL, MSG_LENGTH, SOURCE_TYPE, SOURCE_FILE, VERIFIED_FLG, ALT_MSG_LENGTH)
 Values
   ('EXT55A01', 'N', 'AMOUNT BASED REFERRAL', 0, 'EXT', 
    'EXCEPTIONS', ' ', 0);

Insert into TBAADM.MMSG
   (MSG_ID, DEL_FLG, MSG_LITERAL, MSG_LENGTH, SOURCE_TYPE, SOURCE_FILE, VERIFIED_FLG, ALT_MSG_LENGTH)
 Values
   ('EXT56A01', 'N', 'AMOUNT BASED REFERRAL', 0, 'EXT', 
    'EXCEPTIONS', ' ', 0);
	

Insert into TBAADM.MMSG
   (MSG_ID, DEL_FLG, MSG_LITERAL, MSG_LENGTH, SOURCE_TYPE, SOURCE_FILE, VERIFIED_FLG, ALT_MSG_LENGTH)
 Values
   ('EXT54A02', 'N', 'AMOUNT BASED REFERRAL', 0, 'EXT', 
    'EXCEPTIONS', ' ', 0);

Insert into TBAADM.MMSG
   (MSG_ID, DEL_FLG, MSG_LITERAL, MSG_LENGTH, SOURCE_TYPE, SOURCE_FILE, VERIFIED_FLG, ALT_MSG_LENGTH)
 Values
   ('EXT50A02', 'N', 'AMOUNT BASED REFERRAL', 0, 'EXT', 
    'EXCEPTIONS', ' ', 0);

Insert into TBAADM.MMSG
   (MSG_ID, DEL_FLG, MSG_LITERAL, MSG_LENGTH, SOURCE_TYPE, SOURCE_FILE, VERIFIED_FLG, ALT_MSG_LENGTH)
 Values
   ('EXT11A02', 'N', 'AMOUNT BASED REFERRAL', 0, 'EXT', 
    'EXCEPTIONS', ' ', 0);
	
Insert into TBAADM.MMSG
   (MSG_ID, DEL_FLG, MSG_LITERAL, MSG_LENGTH, SOURCE_TYPE, SOURCE_FILE, VERIFIED_FLG, ALT_MSG_LENGTH)
 Values
   ('EXT55A02', 'N', 'AMOUNT BASED REFERRAL', 0, 'EXT', 
    'EXCEPTIONS', ' ', 0);

Insert into TBAADM.MMSG
   (MSG_ID, DEL_FLG, MSG_LITERAL, MSG_LENGTH, SOURCE_TYPE, SOURCE_FILE, VERIFIED_FLG, ALT_MSG_LENGTH)
 Values
   ('EXT56A02', 'N', 'AMOUNT BASED REFERRAL', 0, 'EXT', 
    'EXCEPTIONS', ' ', 0);
	
	--Insert Values in Custom table

Insert into CUSTOM.C_CAM
   (EXCP_CODE, AUTH_MATRIX_ID, BANK_ID)
 Values
   ('A01', 'REF1', '11');


Insert into CUSTOM.C_CAM
   (EXCP_CODE, AUTH_MATRIX_ID, BANK_ID)
 Values
   ('A01', 'REF1', '50');

   Insert into CUSTOM.C_CAM
   (EXCP_CODE, AUTH_MATRIX_ID, BANK_ID)
 Values
   ('A01', 'REF1', '54');

   Insert into CUSTOM.C_CAM
   (EXCP_CODE, AUTH_MATRIX_ID, BANK_ID)
 Values
   ('A01', 'REF1', '55');

   Insert into CUSTOM.C_CAM
   (EXCP_CODE, AUTH_MATRIX_ID, BANK_ID)
 Values
   ('A01', 'REF1', '56');
   
   
   
Insert into CUSTOM.C_CAM
   (EXCP_CODE, AUTH_MATRIX_ID, BANK_ID)
 Values
   ('A02', 'REF2', '11');


Insert into CUSTOM.C_CAM
   (EXCP_CODE, AUTH_MATRIX_ID, BANK_ID)
 Values
   ('A02', 'REF2', '50');

   Insert into CUSTOM.C_CAM
   (EXCP_CODE, AUTH_MATRIX_ID, BANK_ID)
 Values
   ('A02', 'REF2', '54');

   Insert into CUSTOM.C_CAM
   (EXCP_CODE, AUTH_MATRIX_ID, BANK_ID)
 Values
   ('A02', 'REF2', '55');

   Insert into CUSTOM.C_CAM
   (EXCP_CODE, AUTH_MATRIX_ID, BANK_ID)
 Values
   ('A02', 'REF2', '56');
