<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.moneygram.com/cacheSettingsSchema"
	xmlns:cs="http://www.moneygram.com/cacheSettingsSchema"
	elementFormDefault="qualified">
 
 
 <xs:element name="cacheSettings" type="cs:CacheSettings" />
 
 <xs:complexType name="CacheSettings">
		<xs:sequence>
			<xs:element maxOccurs="unbounded" minOccurs="0" name="cacheEnv" type="cs:CacheEnv" />
		</xs:sequence>
</xs:complexType>
	
 
	<xs:complexType name="CacheEnv">
		<xs:sequence>
			<xs:element maxOccurs="1" minOccurs="0" name="envName" type="xs:string" />
			<xs:element name="dataSetVersion" type="cs:DataSetVersions" maxOccurs="unbounded" minOccurs="0"  />
			<xs:element name="excludedOperations" type="cs:ExcludedOperation" />
			<xs:element name="excludedFields" type="cs:ExcludedField" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="DataSetVersion">
		<xs:sequence>
			<xs:element name="operationName" type="xs:string"   />
			<xs:element name="version" type="xs:string" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="ExcludedOperation">
		<xs:sequence>
			<xs:element name="operationName" type="xs:string" maxOccurs="unbounded" minOccurs="0"  />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="ExcludedField">
		<xs:sequence>
			<xs:element name="fieldName" type="xs:string" maxOccurs="unbounded" minOccurs="0" />
			</xs:sequence>
	</xs:complexType>

			
	

</xs:schema> 