#!/bin/bash

# Export the Jasypt secret key as an environment variable
export CD_SPRING_DATASOURCE_URL="#{CD-SPRING-DATASOURCE-URL}#"
export CD_SPRING_DATASOURCE_USERNAME="#{CD-SPRING-DATASOURCE-USERNAME}#"
export CD_SPRING_DATASOURCE_PASSWORD="#{CD-SPRING-DATASOURCE-PASSWORD}#"
export CD_SSL_KEYSTORE_LOCATION="#{CD-SSL-KEYSTORE-LOCATION}#"
export CD_SSL_KEYSTORE_PASSWORD="#{CD-SSL-KEYSTORE-PASSWORD}#"
export CD_SSL_KEYSTORE_ALIAS="#{CD-SSL-KEYSTORE-ALIAS}#"

export CD_SECURITY_JWT_SECRET_KEY="#{CD-SECURITY-JWT-SECRET-KEY}#"
export CD_SECURITY_JWT_USERNAME="#{CD-SECURITY-JWT-USERNAME}#"
export CD_SECURITY_JWT_PASSWORD="#{CD-SECURITY-JWT-PASSWORD}#"
export CD_SECURITY_CHANNELS_CERTIFICATE_FOLDER="#{CD-SECURITY-CHANNELS-CERTIFICATE-FOLDER}#"
export CD_FINACLE_FI_ENDPOINT="#{CD-FINACLE-FI-ENDPOINT}#"

# Print a confirmation message
echo "Environment variables have been set."