tlgxfer.funcCode_ENABLED = enabled
tlgxfer.funcCode_MANDATORY = N
tlgxfer.acctNum_ENABLED = enabled
tlgxfer.acctNum_MANDATORY = N
tlgxfer.accountCrncy_ENABLED = enabled
tlgxfer.accountCrncy_MANDATORY = N
tlgxfer.solId_ENABLED = enabled
tlgxfer.solId_MANDATORY = N
tlgxfer.acctName_ENABLED = enabled
tlgxfer.acctName_MANDATORY = N
tlgxfer.applName_ENABLED = enabled
tlgxfer.applName_MANDATORY = N
tlgxfer.txncrncy_ENABLED = enabled
tlgxfer.txncrncy_MANDATORY = N
tlgxfer.txnAmt_ENABLED = enabled
tlgxfer.txnAmt_MANDATORY = N
tlgxfer.settlcrncy_ENABLED = enabled
tlgxfer.settlcrncy_MANDATORY = N
tlgxfer.settAmt_ENABLED = enabled
tlgxfer.settAmt_MANDATORY = N
tlgxfer.settChrg_ENABLED = enabled
tlgxfer.settChrg_MANDATORY = N
tlgxfer.benAcct_ENABLED = enabled
tlgxfer.benAcct_MANDATORY = N
tlgxfer.benAcctCrncy_ENABLED = enabled
tlgxfer.benAcctCrncy_MANDATORY = N
tlgxfer.benAcctSol_ENABLED = enabled
tlgxfer.benAcctSol_MANDATORY = N
tlgxfer.benAcctName_ENABLED = enabled
tlgxfer.benAcctName_MANDATORY = N
tlgxfer.benName_ENABLED = enabled
tlgxfer.benName_MANDATORY = N
tlgxfer.benAddr_ENABLED = enabled
tlgxfer.benAddr_MANDATORY = N
tlgxfer.benSwiftAddr_ENABLED = enabled
tlgxfer.benSwiftAddr_MANDATORY = N
tlgxfer.benBankClearingCode_ENABLED = enabled
tlgxfer.benBankClearingCode_MANDATORY = N
tlgxfer.benBankAcct_ENABLED = enabled
tlgxfer.benBankAcct_MANDATORY = N
tlgxfer.exchRateCode_ENABLED = enabled
tlgxfer.exchRateCode_MANDATORY = N
tlgxfer.tranNum_ENABLED = enabled
tlgxfer.tranNum_MANDATORY = N
