package com.moneygram.agentconnect1512;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2025-02-07T12:16:14.342+01:00
 * Generated source version: 4.0.3
 *
 */
@WebServiceClient(name = "AgentConnectService",
                  wsdlLocation = "https://extws.moneygram.com/extws/AgentConnectWSDL?Version=1512",
                  targetNamespace = "http://www.moneygram.com/AgentConnect1512")
public class AgentConnectService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.moneygram.com/AgentConnect1512", "AgentConnectService");
    public final static QName AgentConnect = new QName("http://www.moneygram.com/AgentConnect1512", "AgentConnect");
    static {
        URL url = null;
        try {
            url = new URL("https://extws.moneygram.com/extws/AgentConnectWSDL?Version=1512");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AgentConnectService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "https://extws.moneygram.com/extws/AgentConnectWSDL?Version=1512");
        }
        WSDL_LOCATION = url;
    }

    public AgentConnectService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AgentConnectService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AgentConnectService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public AgentConnectService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public AgentConnectService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public AgentConnectService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns AgentConnect
     */
    @WebEndpoint(name = "AgentConnect")
    public AgentConnect getAgentConnect() {
        return super.getPort(AgentConnect, AgentConnect.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AgentConnect
     */
    @WebEndpoint(name = "AgentConnect")
    public AgentConnect getAgentConnect(WebServiceFeature... features) {
        return super.getPort(AgentConnect, AgentConnect.class, features);
    }

}
