
package com.moneygram.agentconnect1512;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.3
 * 2025-02-07T12:16:14.206+01:00
 * Generated source version: 4.0.3
 */

@WebFault(name = "errors", targetNamespace = "http://www.moneygram.com/AgentConnect1512")
public class Errors_Exception extends Exception {

    private com.moneygram.agentconnect1512.Errors faultInfo;

    public Errors_Exception() {
        super();
    }

    public Errors_Exception(String message) {
        super(message);
    }

    public Errors_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public Errors_Exception(String message, com.moneygram.agentconnect1512.Errors errors) {
        super(message);
        this.faultInfo = errors;
    }

    public Errors_Exception(String message, com.moneygram.agentconnect1512.Errors errors, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = errors;
    }

    public com.moneygram.agentconnect1512.Errors getFaultInfo() {
        return this.faultInfo;
    }
}
