logging:
  level:
    ROOT: INFO
    org.hibernate: INFO
    com.equitybank.gag.telco_b2c: INFO
    com.netflix.discovery.DiscoveryClient: INFO

# For multiple server port configuration
http:
  port: 7080
https:
  port: 8443

server:
#  port: 8443
  ssl:
    enabled: true
    key-store: ${CD_SSL_KEYSTORE_LOCATION}
    key-store-password: ${CD_SSL_KEYSTORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: ${CD_SSL_KEYSTORE_ALIAS}

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
#    driverClassName: oracle.jdbc.driver.OracleDriver
    driverClassName: oracle.jdbc.OracleDriver
    url: ${CD_SPRING_DATASOURCE_URL}
    username: ${CD_SPRING_DATASOURCE_USERNAME}
    password: ${CD_SPRING_DATASOURCE_PASSWORD}
    hikari:
      poolName: Hikari
      auto-commit: false
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 30000  # Close idle connections after 30s
      connection-timeout: 20000  # Wait max 20s for a connection
      max-lifetime: 1800000  # Recycle connections every 30 mins
#      leak-detection-threshold: 15000  # Detect leaked connections after 15s
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 500
        prepStmtCacheSqlLimit: 4096
        useServerPrepStmts: true
  jpa:
    hibernate:
#      dialect: org.hibernate.dialect.Oracle12cDialect
      dialect: org.hibernate.dialect.OracleDialect
      ddl-auto: update
    show-sql: false

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

signature:
  validation:
    enabled: true
    isInternal: false
    certificate:
      path: ${CD_SECURITY_CHANNELS_CERTIFICATE_FOLDER}

finacle:
  debit-credit:
    enabled:
      b2c-transaction: false
      airtime-topup: false
      imt: true
      float: true
    countries:
      float: 43,54,11

  gls:
    # Democratic Republic of Congo (DRC) specific configurations
    drc:
      b2c:
        credit: '15000137010375'
        commission: '1500034701000'
      float-purchase:
        vodacom:
          credit-CDF: ${CD_VODACOM_FLOAT_PURCHASE_CREDIT_CDF_GL}#
          credit-USD: ${CD_VODACOM_FLOAT_PURCHASE_CREDIT_USD_GL}#
          commission: '000'
        airtel:
          credit-CDF: ${CD_AIRTEL_FLOAT_PURCHASE_CREDIT_CDF_GL}#
          credit-USD: ${CD_AIRTEL_FLOAT_PURCHASE_CREDIT_USD_GL}#
          commission: '000'
        orange:
          credit-CDF: '230001613110187'
          credit-USD: '230001613120178'
#          credit-CDF: '15000147030080'
#          credit-USD: '15000147030081'
          commission: '15000657010029'
      airtime:
        credit: '15000137010375'
        commission: '1500034701000'
      imt:
        credit: '15000117030034'
        commission: '1500034701000'

    # Kenya specific configurations
    kenya:
      float-purchase:
        safaricom:
          credit-KES: ${KE_SAFARICOM_FLOAT_PURCHASE_CREDIT_KES_GL}#
          commission: '000'
        airtel:
          credit-KES: ${KE_AIRTEL_FLOAT_PURCHASE_CREDIT_KES_GL}#
          commission: '000'

    # South Sudan specific configurations
    south-sudan:
      float-purchase:
        mtn:
          credit-SSP: ${SS_MTN_FLOAT_PURCHASE_CREDIT_SSP_GL}#
          commission: '000'

  endpoints:
    fi: ${CD_FINACLE_FI_ENDPOINT}#

# Finacle over the counter float purchase account mappings
telco:
  accounts:
    drc:
      vodacom:
        custodyaccount:
#          usd: '010183946120267'
#          cdf: '010183946110276'
          usd: '511200030380188'
          cdf: '511200030379897'
      airtel:
        custodyaccount:
          usd: '010184069120050'
          cdf: '010184069110156'
    ss:
      mtn:
        custodyaccount:
          ssp: ${SS_MTN_TRUST_ACCOUNT_SSP}#
    kenya:
      airtel:
        trustaccount: ${KE_AIRTEL_TRUST_ACCOUNT}#
        trustaccountmsisdn: ${KE_AIRTEL_TRUST_ACCOUNT_MSISDN}#
      tmt:
        warid:
          fincale:
            f123: ${TMT_WARID_FINACLE_F123}#
    ug:
      airtel:
        f102: ${UG_AIRTEL_F102}#
    rwanda:
      airtel:
        trustaccount: ${RW_AIRTEL_TRUST_ACCOUNT}#

# Transaction fees
fees:
  drc:
    b2c:
      commission: '0'
    airtime:
      commission: '0'
    imt:
      commission: '0'

# Interval between echo operations in milliseconds (default: 10000 ms / 10 seconds)
echo:
  interval: 10000

  # Timeout for the echo request in milliseconds (default: 5000 ms / 5 seconds)
  timeout: 5000

# JWT bearer token configs
security:
  jwt:
    secret-key: ${CD_SECURITY_JWT_SECRET_KEY}
  user:
    username: ${CD_SECURITY_JWT_USERNAME}
    password: ${CD_SECURITY_JWT_PASSWORD}
    
# Services enabled
enabled:
  services:
    telco:
      version1:
        name-check-airtime-topup: true
        name-check-bank-to-wallet: true
        name-check-float-purchase: true
        airtime-topup-json: true
        airtime-status-json: true
        float-purchase-json: false
        bank-to-wallet-json: false
        bank-to-wallet-status-json: false
      version2:
        airtime-topup-xml: true
        float-purchase-xml: true
        bank-to-wallet-xml: true
    imt:
      moneygram-outbound: true
      moneygram-inbound: true
      thunes-outbound: true
      wendi-outbound: true
    others:
      database-operation: true

wendi:
  client_id: 'EQUITY'