version: '3.8'

services:
  papss-middleware:
    image: ghcr.io/papssafrica/papss-middleware-service:main
    container_name: papss-middleware
    restart: always
    network_mode: "host"
    volumes:
      - /u01/gag/papss/certs:/var/papss/certs
      - /u01/gag/papss/middleware/config/application.yml:/app/config/application.yml
      - /u01/gag/papss/jdbc/ojdbc6-11.2.0.3.jar:/app/libs/ojdbc6.jar
    environment:
      - SPRING_CONFIG_LOCATION=/app/config/application.yml
      - JAVA_OPTS=-cp/app/ojdbc6.jar:/app/app.jar
      - SERVER_PORT=9090
    extra_hosts:
      - "pm.test.papssnet.papss.com:10.109.10.138"
   # ports:
    #  - "9090:8080"
    # networks:
     # - papss-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  papss-network:
    driver: bridge                